AliceO2Group/O2Physics

- PWGLF/TableProducer/cascadebuilder.cxx
thanks for spotting, @creetz16 ! :-D
> Fix minor bug in kf path

- Common/TableProducer/evtPlanesTable.cxx
- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/qVectorsCorrection.cxx
> COMMON: deletion of printing

- PWGCF/FemtoWorld/Tasks/femtoWorldEfficiencyTask.cxx
Fix filling MCTruthAll histograms to fill them with particles of positive or negative charge.
Add minus/TOFmatchingAll histogram.
Add configurable to choose PID without TOF
> PWGCF: Update efficiency task

- PWGCF/FemtoUniverse/Core/FemtoUtils.h
- PWGCF/FemtoUniverse/TableProducer/CMakeLists.txt
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx
- PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
FemtoUniverse 
- introducing two new tasks: Producer + TrackTrack task for running over MC truth.
- introducing producer to run over McParticles
- track-track-task to get information from McParticles stored in FemtoUniverse tables
- fixes of configurable names and clangs
- Bonus: comment fixes in FemtoUtils
> PWGCF: FemtoUniverse: MCtruth Producer and Task

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/DataModel/CandidateSelectionTables.h
- PWGHF/TableProducer/CMakeLists.txt
- PWGHF/TableProducer/candidateCreatorBs.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
Adding QA histogram + ML selection to DS candidate selector and B0 MC matching to Bs candidate creator @fgrosa @fcatalan92 .
> PWGHF: Add ML selection to Ds candidate selector + B0 matching to Bs candidate creator

- PWGHF/Core/HfMlResponse.h
- PWGHF/TableProducer/candidateSelectorD0.cxx
- PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
- PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
Waiting for https://github.com/AliceO2Group/O2Physics/pull/3351 to be merged to include also Ds.
> PWGHF: simplify logic to parss of ML models

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update MaterialBudget
> PWGEM/PhotonMeson: update MaterialBudget

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
reduce dependency on centrality
> PWGEM/PhotonMeson: reduce dependency on centrality

- PWGHF/TableProducer/candidateSelectorD0.cxx
Adding debug histograms for BDT application
> PWGHF: Add debug histograms for BDT application in D0 selector

- .gitignore
- PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
1. add '.cache' to .gitignore
clangd stores the index inside the project root when using background
indexing, other IDEs might also do this. this file is should not be shared and thus is okay to ignore in vc
2. add exploratory task for v0 photons @ddobrigk @dsekihat
> PWGEM/PhotonMeson: Add MCV0 task

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
fix for event index (first PCM)
> PWGEM/PhotonMeson: fix for event index (first PCM)

- PWGLF/TableProducer/cascadebuilder.cxx
@ZFederica should help with your problems! I will still cross-check further
> Fix minor issues with KF implementation

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
- PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
* enabling track cleaning and CPR for MC Truth Particles,
* adding mc truth process to the FemtoUniverse producer.
> PWGCF: FemtoUniverse -- MC Truth fixes

- PWGLF/TableProducer/LFResonanceInitializer.cxx
Add event correction nSparse for Trigger efficiency, vertex selection check of `INEL>0` events
> Add event correction data

- PWGMM/Mult/Tasks/dndeta-hi.cxx
@joonsukbae there was a bug in the condition - parenthesis was placed incorrectly.
> PWGMM: dndeta-hi: fix bug in condition

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/CutsLibrary.h
HI, 
I added a new cut with a kinetic cut in the cuts library.
Cheers
Xiaozhi
> add the cut with only kinetic

- PWGEM/PhotonMeson/DataModel/mcV0Tables.h
- PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
- PWGEM/PhotonMeson/Utils/TrackSelection.h
Restructures and add to the mcv0 task for phase-space studies:
* optional output as a TTree for debugging and optimization
* Adds some general templates for track selection
* Adds some histograms to the output
> PWGEM/PhotonMeson: MC V0 phase-space studies

- PWGLF/TableProducer/cascadebuilder.cxx
Implementation of pt dep cosPA cut
> Changes in PWGLF/TableProducer/cascadebuilder.cxx

- Common/DataModel/TrackSelectionTables.h
- PWGLF/DataModel/spectraTOF.h
- PWGLF/TableProducer/lfTPCPID.cxx
- PWGLF/Tasks/spectraTOF.cxx
- Update track selection table, add flag for TPC quality
- orthogonalize track cuts
> LF: Add ITS and TPC info

- PWGLF/TableProducer/lambdakzerobuilder.cxx
@ddobrigk have a look if it makes sense to you
> Avoid crash with no collisions

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
- PWGEM/PhotonMeson/TableProducer/createPCM.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: reduce random ee pairs
> PWGEM/PhotonMeson: reduce random ee pairs

- PWGHF/ALICE3/TableProducer/candidateCreatorChic.cxx
- PWGHF/ALICE3/TableProducer/candidateCreatorX.cxx
- PWGHF/ALICE3/TableProducer/candidateSelectorChicToJpsiGamma.cxx
- PWGHF/ALICE3/TableProducer/candidateSelectorXToJpsiPiPi.cxx
- PWGHF/ALICE3/Tasks/taskChic.cxx
- PWGHF/ALICE3/Tasks/taskJpsi.cxx
- PWGHF/ALICE3/Tasks/taskX.cxx
- PWGHF/D2H/TableProducer/dataCreatorD0PiReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
- PWGHF/D2H/Tasks/taskBplus.cxx
- PWGHF/D2H/Tasks/taskBplusReduced.cxx
- PWGHF/D2H/Tasks/taskD0.cxx
- PWGHF/D2H/Tasks/taskDplus.cxx
- PWGHF/D2H/Tasks/taskLb.cxx
- PWGHF/D2H/Tasks/taskLc.cxx
- PWGHF/D2H/Tasks/taskLcToK0sP.cxx
- PWGHF/D2H/Tasks/taskXicc.cxx
- PWGHF/DataModel/CandidateSelectionTables.h
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorB0.cxx
- PWGHF/TableProducer/candidateCreatorBplus.cxx
- PWGHF/TableProducer/candidateCreatorLb.cxx
- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
- PWGHF/TableProducer/candidateCreatorXicc.cxx
- PWGHF/TableProducer/candidateSelectorBplusToD0Pi.cxx
- PWGHF/TableProducer/candidateSelectorLbToLcPi.cxx
- PWGHF/Tasks/taskLcCentrality.cxx
Remove unnecessary commented `Printf` and replace others with `LOGF(debug`
> PWGHF: Improve debugging logs

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/MCSignalLibrary.cxx
Add more cuts to be tested for prefilter studies
> Add more prefilter cuts

- PWGLF/DataModel/LFNucleiTables.h
- PWGLF/TableProducer/LFTreeCreatorNuclei.cxx
- PWGLF/Tasks/LFNucleiBATask.cxx
@njacazio : Hi Nicolo, could you please approve the changes? 
Thnx!
> [BaTask]3D histos added for antiD analysis

- PWGLF/TableProducer/cascadebuilder.cxx
add addidtional QA histograms for cosPA cut check
> Change in cascadebuilder.cxx

- PWGJE/TableProducer/jetfinder.cxx
- PWGJE/TableProducer/jetfinder.h
- PWGJE/TableProducer/jetfinderhf.cxx
The bug prevented filters being applied to the pT of particles for particle level jets
> PWGJE: fixing bug for particle level configurables

- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/trackJetqa.cxx
Hello,
I have written this code for performing track quality assurance in the jet framework. In order to do so, I also modified the CMakeLists. 
Here @jloemker and anybody who has suggestions, please let me know!
> PWGJE: Task producing jet tracking qa histograms

- PWGDQ/Core/CutsLibrary.cxx
More cuts for prefilter and skimming test
> More cuts for prefilter and skimming test

- PWGDQ/Core/CutsLibrary.cxx
One additional cut for prefilter studies
> One additional cut for prefilter studies

- PWGHF/DataModel/CandidateSelectionTables.h
- PWGHF/TableProducer/CMakeLists.txt
- PWGHF/TableProducer/candidateSelectorBsToDsPi.cxx
> PWGHF: Add ML selection in Bs selector

- PWGLF/Tasks/f0980analysis.cxx
> [PWGLF] updates for RT analysis

- PWGMM/UE/Tasks/ue-zdc-analysys.cxx
The task needed some fixes and we also reduced the number of bins for some TH2D.
> Fixing the task for few remaining issues

- PWGLF/TableProducer/nucleiSpectra.cxx
> PWG-LF: extend nuclei task to protons

- PWGLF/Tasks/QC/tpc_dedx_qa.cxx
- added configurable momentum binning
- extended pseudorapidity to +/- 0.9
- added (anti)deuterons
- added protection in case of missing centrality calibration
> added (anti)deuterons

- PWGLF/Tasks/cascadecorrelations.cxx
also fix naming: trigger and assoc instead of 0 and 1.
> PWGLF: Add QA and THnSparses for correlation

- PWGLF/Tasks/QC/tpc_dedx_qa.cxx
Optimized binning to reduce memory consumption
> optimized binning

- PWGJE/Tasks/trackJetqa.cxx
Hello everyone,
I have updated the task _trackJetqa.cxx_. Specifically:
- I have fixed a typo on the Y axis of the sigma1Pt histograms
- I have added some more sigma1Pt histograms when activating specific ITS layers
- I have added a pT histogram for tracks that have a TRD match
@jloemker @mverwe 
Thank you!
> PWGJE: Updating task producing jet tracking qa histograms

- Common/Tasks/ft0Qa.cxx
- PWGJE/Tasks/trackJetqa.cxx
Per-collision analysis was supplemented by per-BC analysis.  FT0 time, amplitude and multiplicity histograms for BC task were added to HistogramRegistry.
> Per-BC analysis was added

- PWGLF/Tasks/phianalysis.cxx
Simple update for PbPbQA purpose.
> Update phi task based on k892 task

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
Add opening angle and further cuts for dielectron prefilter studies
> Add opening angle and further cuts for dielectron prefilter studies

- PWGEM/PhotonMeson/Core/CMakeLists.txt
- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/CutsLibrary.h
- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/dalitzQC.cxx
PWGEM/PhotonMeson: add DalitzEE
> PWGEM/PhotonMeson: add DalitzEE

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/dalitzQC.cxx
- PWGEM/PhotonMeson/Utils/PairUtilities.h
> PWGEM/PhotonMeson: update dalitz

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzQCMC.cxx
- PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: update dalitz for MC
> PWGEM/PhotonMeson: update dalitz for MC

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update histograms for V0
> PWGEM/PhotonMeson: update histograms for V0

- PWGLF/Tasks/vzero_cascade_absorption.cxx
> Add Process switch

- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
Adding McCollisionId to the event table to match it with the MC particle table.
@qgp @vkucera
> PWGHF: Add McCollisionId to the event table of treeCreatorLcToPKPi

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson: update for low B
> PWGEM/PhotonMeson: update for low B

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMaker.cxx
- PWGDQ/Tasks/tableReader.cxx
HI, 
I am adding the histograms for the run-by-run QA of the ongoing pb-pb data-taking, I closed the previous one since a error, 
now it has been fixed in the new PR
Cheers
Xiaozhi
> adding the histograms for the run-by-run QA of the ongoing pb-pb data-taking

- PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: fix to SVz calculation. Thanks to @amaringarcia .
> PWGEM/PhotonMeson: fix to SVz calculation

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson: update track selection for low B
> PWGEM/PhotonMeson: update track selection for low B

- Common/Tasks/CMakeLists.txt
- Common/Tasks/evtPlanesResolution.cxx
- Common/Tasks/qVectorsCorrection.cxx
Add task for calculations of event plane resolution
> [Commom] Add task for calculations of event plane resolution

- ALICE3/Tasks/alice3-dilepton.cxx
@ddobrigk this should be what we discussed. could you have a look?
> Include configurable to use generated pt/eta for acceptance selection

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
PWGEM/PhotonMeson: update tagging method for low B
> PWGEM/PhotonMeson: update tagging method for low B

- PWGDQ/Tasks/dqEfficiency.cxx
- PWGDQ/Tasks/tableReader.cxx
Fixing the issue with the indexes in the dilepton-hadron task
> [PWGDQ] Fixing the issue with the indexes in the dilepton-hadron task

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGEM/PhotonMeson: update eID for dalitz
> PWGEM/PhotonMeson: update eID for dalitz

- PWGJE/Tasks/jetvalidationqa.cxx
Hi @nzardosh , @Archita-Dash , @fkrizek ,
I added the control vertex histogram (where there is no selection applied) and additional track cut histograms for further checks.
Best,
Johanna
> [PWGJE Validation] Track cut histograms and control vertex

- PWGDQ/Core/CutsLibrary.cxx
Add cuts for low B field analysis
> add lowB field cut

- PWGDQ/Core/VarManager.h
> PWGDQ/Core: add ITSibAny

- PWGLF/TableProducer/LFResonanceInitializer.cxx
Updated spherocity calculation.
> PWGLF: Update LFResonanceInitializer.cxx

- PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
Fixing the logic and uncommenting CPR and track cleaning for FemtoUniverse.
> PWGCF: FemtoUniverse -- Fixing CPR and track cleaning

- PWGDQ/Core/CutsLibrary.cxx
Prefilter study additional cuts
> Prefilter study additional cuts

- Common/DataModel/EvtPlanes.h
- Common/DataModel/Qvectors.h
- Common/TableProducer/evtPlanesTable.cxx
- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/evtPlanesResolution.cxx
> COMMON: updates on TPC Q-vectors

- PWGDQ/TableProducer/tableMakerJpsiHf.cxx
Fixing issue with J/psi-D0 histogram filling
> PWGDQ: Fixing issue with histogram filling

- PWGDQ/Core/CutsLibrary.cxx
More cuts for postcalibration + low B field
> More cuts for postcalibration + low B field

- PWGLF/Tasks/f0980analysis.cxx
> [PWGLF] fix axis

- PWGDQ/Core/HistogramsLibrary.cxx
Adding 3D histo to mc truth output to add DCA
> PWGEM/DQ add 3D hist mee,pt,dca to MC Truth Pair list

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- Tutorials/PWGEM/pcm/CMakeLists.txt
- Tutorials/PWGEM/pcm/pcmtutorial.cxx
[PWGEM/PhotonMeson: reduce histogram size]
[Tutorial/PWEM/pcm add pcm tutorial]
> Tutorials/PWGEM: add pcm tutorial

- PWGLF/Tasks/QAHistTask.cxx
Bugfix: Added code to fill the species specific DCA XY & DCA Z histograms.
> QAHistTask: fixed an error

- PWGLF/Tasks/nonPromptCascade.cxx
- Calculate masses from associated tracks, requiring V0 daughters tracks in TPC
- Histograms binning changed
> Updating mass calculation

- PWGEM/PhotonMeson/TableProducer/createPCM.cxx
- Tutorials/PWGEM/pcm/CMakeLists.txt
- Tutorials/PWGEM/pcm/pcmtutorial.cxx
Tutorials/PWGEM/pcm: update pcm tutorial
> Tutorials/PWGEM/pcm: update pcm tutorial

- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMakerJpsiHf.cxx
- PWGDQ/Tasks/tableReader.cxx
Adding process function without DCA tables from DQ
> PWGDQ: Adding process function without DCA tables from DQ

- PWGDQ/Core/CutsLibrary.cxx
Add cuts to make a prefilter scan in pp 13 TeV for Davud
> prefilter scan

- PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
- update to keep up with changes in O2/run (more than one event per dataframe from kine_publisher and mctracks_proxy possible)
- simplified some configurables, some optimizations
> PWGEM: update lmeeLFCocktail task

- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
- PWGCF/FemtoWorld/Tasks/femtoWorldEfficiencyTask.cxx
Adding PID TOFbeta histograms to FemtoWorld Efficiency Task
> PWGCF: FemtoWorld - Adding TOFbeta histograms to EfficiencyTask

- EventFiltering/PWGLF/filterf1proton.cxx
@skundu692 replacing calls to RecoDecay functions as per @vkucera's request
> Replace RecoDecay::getMass with constants

- PWGLF/Tasks/cascadecorrelations.cxx
Add multiple selection criteria (mainly track quality & topo), add invmass & multiplicity to correlation info
> [PWGLF] cascadecorrelations: add topo selections, inv mass & multiplicity

- PWGHF/Core/PDG.h
- PWGHF/Core/make_pdg_header.py
> PWGHF: PDG: Add Xi0

- Common/CCDB/EventSelectionParams.cxx
- Common/CCDB/EventSelectionParams.h
- Common/TableProducer/eventSelection.cxx
- DPG/Tasks/AOTEvent/eventSelectionQa.cxx
+ added check if bunch crossing is far from ITS RO Frame border
+ finetuned TCE cross sections
> Check if bunch crossing is far from ITS RO Frame border

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
- PWGEM/PhotonMeson/TableProducer/createPCM.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/gammaConversions.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/PCMUtilities.h
- Tutorials/PWGEM/pcm/CMakeLists.txt
- Tutorials/PWGEM/pcm/pcmtutorial.cxx
This PR contains following 2 commits.
PWGEM/PhotonMeson: add a table producer for photon conversion
Tutorials/PWGEM: update pcm tutorial
> Tutorials/PWGEM: update pcm tutorial

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: quick fix to photon conversion builder
> PWGEM/PhotonMeson: quick fix to photon conversion builder

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: clean up histograms
> PWGEM/PhotonMeson: clean up histograms

- Tools/ML/MlResponse.h
- Tutorials/ML/CMakeLists.txt
- Tutorials/ML/applyMlSelection.cxx
- Tutorials/ML/applyOnnxModel.cxx
- Tutorials/ML/dpl-config_applyMlSelection.json
- Tutorials/ML/run_applyMlSelection.sh
@ddobrigk Please merge at your earliest convenience. Thanks!
> Preparation for ML tutorial at O2AT3

- Common/Core/EventPlaneHelper.cxx
- Common/Core/EventPlaneHelper.h
- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/evtPlanesResolution.cxx
add variable for different modulations
> [Common] add variable for different modulations for the event plane determination

- PWGLF/Tasks/f0980analysis.cxx
- PWGLF/Tasks/k1analysis.cxx
- PWGLF/Tasks/k892analysis.cxx
- PWGLF/Tasks/lambda1520SpherocityAnalysis.cxx
- PWGLF/Tasks/lambda1520analysis.cxx
- PWGLF/Tasks/phianalysis.cxx
Remove unused table subscriptions for stand-alone processing.
> PWG-LF: Remove table dependency

- PWGDQ/DataModel/MchTrkEffTables.h
- PWGDQ/TableProducer/CMakeLists.txt
- PWGDQ/TableProducer/tableMakerMuonMchTrkEfficiency.cxx
- PWGDQ/Tasks/CMakeLists.txt
- PWGDQ/Tasks/taskMuonMchTrkEfficiency.cxx
First version of the MCH tracking efficiency determination code. 
It contains a table header, a table maker class and a task to read the output. 
It is separated from the general table maker as it can be run either before or after it.
> PWG-DQ: First version of the MCH tracking efficiency determination code

- PWGDQ/Core/CutsLibrary.cxx
> Fix TOF PID for low B field

- PWGJE/DataModel/TrackJetQa.h
- PWGJE/TableProducer/jettrackderived.cxx
- PWGJE/Tasks/trackJetqa.cxx
Hi all,
I added some more event and track information for
1) the general jet-track-quality assurance: @alicecaluisi this should be complete now.
2) the track uncertainty at high pT (for the PbPb data with centrality and multiplicity)
Cheerio,
Johanna
> [PWGJE] Adding track and event info to jettracktable producer

- DPG/Tasks/AOTTrack/MonitorFilterBit.cxx
Adding selection of strange-decay particles and fixing displacement selection at generator level.
> Adding selection of strange-decay particles.

- PWGDQ/Core/MCSignalLibrary.cxx
- PWGEM/Dilepton/Tasks/MCtemplates.cxx
> PWGEM: update MCtemplates task

- PWGDQ/Core/VarManager.h
PWGDQ/Core: add sel8 in VarManager
> PWGDQ/Core: add sel8 in VarManager

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/MCSignalLibrary.cxx
Add one sel8 event cut and further MC signals
> Event cuts and MC signal

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update photon table producer
> PWGEM/PhotonMeson: update photon table producer

- Tutorials/PWGLF/Resonance/README.md
- Tutorials/PWGLF/Resonance/resonances_step0.cxx
Basic task to read the resonance table and run track loop
> PWGLF: Update the first resonance tutorial base

- PWGDQ/Tasks/taskMuonMchTrkEfficiency.cxx
> PWG-DQ: Fix initialization parameter

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/TableProducer/createPCM.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: update v0 photon cuts
> PWGEM/PhotonMeson: update v0 photon cuts

- DPG/Tasks/AOTTrack/PID/qaPIDTOFMC.cxx
- DPG/Tasks/AOTTrack/PID/qaPIDTPCMC.cxx
- DPG/Tasks/AOTTrack/qaEfficiency.cxx
- Add HMPID info in qaEfficiency
- Update PID MC tasks, fix duplicated histos
> DPG HMPID efficiency and PID MC info:

- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
This PR contains:
- Added topological selection flag check before setting PID selection flag bit.
> [PWGHF] Fixed Ds selection flag

- PWGJE/Tasks/emctmmonitor.cxx
- Removed AliPhysics Histograms since they are outdated after the inclusion of the EMCal Performance paper cuts
- Changed the dPhi and dEta binning to have their range be the same as set in the cuts
- Added NSigma plots for all global tracks before cuts and NSigma plots for electron and positron with the E/p cut for more QA (requested by TPC group to investigate discrepance in number of electrons and positrons at low track pT)
- Removal of code parts that are already in the cell oder cluster QA task (leading cell amplitude fraction)
- Removal of `numberOfClustersSM` since we don't fill any SM wise histograms in this task
> [EMCAL-689] EMC TM: Add NSigma Plots and clean up

- PWGLF/TableProducer/cascadebuilder.cxx
- PWGLF/TableProducer/lambdakzerobuilder.cxx
- Tutorials/PWGLF/Strangeness/strangeness_step0.cxx
- Tutorials/PWGLF/Strangeness/strangeness_step1.cxx
- Tutorials/PWGLF/Strangeness/strangeness_step2.cxx
- Tutorials/PWGLF/Strangeness/strangeness_step3.cxx
- Tutorials/PWGLF/Strangeness/strangeness_step4.cxx
1. Update of the Strangeness Tutorial
2. Fix of the cascade and V0 binding names in the corresponding builders
> PWGLF: Strangeness Tutorial

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Tasks/phosQC.cxx
PWGEM/PhotonMeson: reduce dependency, data size and speed up process
> PWGEM/PhotonMeson: reduce dependency, data size and speed up process

- PWGHF/TableProducer/candidateSelectorToXiPi.cxx
- change PID method: statusTpcAndTof --> statusTpcOrTof
- change default values of configurables
> PWGHF: change PID method in toXiPi candidateSelector

- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
PWGEM/PhotonMeson: quick fix for dalitz QC
> PWGEM/PhotonMeson: quick fix for dalitz QC

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/TableProducer/tableMaker.cxx
I added TH2F "dimuon-vtxncontrib" histgram in PWGDQ/Core/HistogramLibrary.cxx.
> Add "dimuon-vtxncontrib" histogram in PWGDQ/Core/HistogramLibrary.cxx

- PWGJE/Tasks/jetfragmentation.cxx
Added xi=ln(1/z), theta (dist to jet axis)
Simplified code and reduced duplication with templating
> [PWGJE] Updates to jet fragmentation task

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
PWGEM/PhotonMeson: quick update on v0 photon cut
> PWGEM/PhotonMeson: quick update on v0 photon cut

- Tutorials/PWGEM/pcm/pcmtutorial.cxx
- For the tutorial, a minimal version of the code is necessary as a starting point
- The complete solution of the code will be available at https://github.com/AliceO2Group/analysis-tutorials/tree/master/o2at-3
> [Tutorial/PWGEM]: Skim tutorial code

- Tutorials/PWGLF/Resonance/resonances_step1.cxx
- Tutorials/PWGLF/Resonance/resonances_step2.cxx
TOF and TPC selection is super easy to read
> PWGLF: Tutorial update - Simplify the TOF selection part

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/CMakeLists.txt
- PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
- PWGHF/HFC/Tasks/CMakeLists.txt
- PWGHF/HFC/Tasks/taskCorrelationLcHadrons.cxx
Lc-Hadron correlator and task development, which Lc is for the decay channel Lc->PKPi
> PWGHF: Lc-H correlator and task development

- EventFiltering/PWGMM/multFilter.cxx
- EventFiltering/filterTables.h
> remove flatFV0 bit

- .gitignore
@ktf @TimoWilken 
I've added several lines based on github's templates https://github.com/github/gitignore
This should avoid unnecessary rebuilds for some users.
> Common: Update .gitignore for IDE files

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: recover pion rejection with TOF in low B
> PWGEM/PhotonMeson: recover pion rejection with TOF in low B

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
PWGEM/PhotonMeson: fix for DCAxy,z of v0 photons
> PWGEM/PhotonMeson: fix for DCAxy,z of v0 photons

- Common/Core/EventPlaneHelper.cxx
- Common/Core/EventPlaneHelper.h
- Common/DataModel/Qvectors.h
- Common/TableProducer/evtPlanesTable.cxx
- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/qVectorsCorrection.cxx
corrects for JOINABILITY
Add one additional column
> [Common] corrects for jionability of Q-Vector

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: fix for single photon task
> PWGEM/PhotonMeson: fix for single photon task

- PWGJE/Tasks/emctmmonitor.cxx
- Add EtaPhi histograms for all selected tracks, matched tracks before dEta, dPhi cut and after dEta, dPhi cut, as well as for positive and negative charged tracks
- Changed NSigma_e axis to go from -10 to +3 -> -10 to +30 to ensure we see basically all tracks in those plots. Imporant for us to find out if we see less positivley charged matched tracks due to NSigma cut or not
- Add configurable to enforce TRD hits for the matched tracks
> [EMCAL-689] emctmmonitor: Add Track Eta Phi histograms and TRD hit config

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
PWGEM/PhotonMeson: quick fix to dalitz QC
> PWGEM/PhotonMeson: quick fix to dalitz QC

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: remove unnecessary histograms
> PWGEM/PhotonMeson: remove unnecessary histograms

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/CMakeLists.txt
- PWGDQ/Tasks/taskJpsiHf.cxx
Adding task to process reduced tables of Jpsi-D0 analysis
> [PWGDQ] Adding task to process reduced tables of Jpsi-D0 analysis

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzMuMu.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/PhotonMeson: update for dimuon
> PWGEM/PhotonMeson: update for dimuon

- PWGHF/TableProducer/treeCreatorBplusToD0Pi.cxx
- PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
> PWGHF: Fix bug in McParticle and McCollision indices in tree creators

- PWGJE/Tasks/trackJetqa.cxx
> Jet QA: unify axes

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson: update muon cut
> PWGEM/PhotonMeson: update muon cut

- Common/TableProducer/PID/pidBayes.cxx
- Common/TableProducer/PID/pidTPC.cxx
- Common/TableProducer/PID/pidTPCFull.cxx
- PWGCF/JCorran/Core/JHistManager.h
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/TwoParticleCorrelations/Core/EventSelectionFilterAndAnalysis.cxx
- PWGCF/TwoParticleCorrelations/Core/PIDSelectionFilterAndAnalysis.cxx
- PWGEM/Dilepton/Utils/MomentumSmearer.h
> Add support for fmt 10.1.1

- PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
There were bugs in the pair check method for track-v0 combination.
> PWGCF FemtoUniverse PairCleaner update for track-v0

- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
PWGEM/PhotonMeson: fix for Join
> PWGEM/PhotonMeson: fix for Join

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
Add a new variable: kSignedPt in Varmanager.h; 
Add some histograms in subgroup tpcvspt and itsvspt.
> Add histograms about tpc(and its) vs. signed pt

- PWGJE/DataModel/EMCALMatchedTracks.h
- PWGJE/TableProducer/CMakeLists.txt
- PWGJE/TableProducer/emcalMatchedTracksTask.cxx
- First version of the table producer that was asked for in the linked JIRA ticket
> [O2-4360] First implementation of cluster-matchedtracks-writer

- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/PhotonMeson: add QA histograms for e/mu
> PWGEM/PhotonMeson: add QA histograms for e/mu

- PWGJE/DataModel/EMCALMatchedTracks.h
- PWGJE/TableProducer/emcalMatchedTracksTask.cxx
> [O2-4360] EMCALMatchedTracks: Add QPt column

- PWGDQ/Core/CutsLibrary.cxx
More PID scenarios for low B field and Pb--Pb
> more PID scenarios

- Common/Core/TableHelper.h
- Common/DataModel/Multiplicity.h
- Common/TableProducer/PID/pidTPCBase.h
- Common/TableProducer/multiplicityTable.cxx
- Split table for barrel multiplicity
- Add proto MC multiplicities
- Add fatal in case mult is misconfigured and Zeq is requested
> Split even more multiplicities

- PWGEM/PhotonMeson/DataModel/mcV0Tables.h
- PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
- PWGEM/PhotonMeson/Utils/TrackSelection.h
Add RPhi histogram to monitor bias of found&reco svertex against phi.
> PWGEM/PHOTONMESON: Add RPhi dependence plots

- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzMuMu.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
PWGEM/PhotonMeson: update on event mixing for dileptons
> PWGEM/PhotonMeson: update on event mixing for dileptons

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
PWGEM/PhotonMeson: update dilepton QC MC
> PWGEM/PhotonMeson: update dilepton QC MC

- PWGLF/Tasks/nonPromptCascade.cxx
- Removed unused histograms
- Adjusted histograms binning
> [PWGLF] Removing unused histograms in nonPromptCascade task

- PWGMM/Tasks/multiplicityPbPb.cxx
Removed TPC cut
Removed subscription to TracksExtra
> PWGMM/Tasks/multiplicityPbPb.cxx  TPC cut removed

- PWGLF/TableProducer/lambdakzerobuilder.cxx
...just in case it helps @f3sch :-D
> Example pcm qa at builder

- PWGHF/TableProducer/candidateSelectorToXiPi.cxx
- PWGUD/Core/CMakeLists.txt
- PWGUD/Core/SGCutParHolder.cxx
- PWGUD/Core/SGCutParHolder.h
- PWGUD/Core/SGCutParHolderLinkDef.h
- PWGUD/Core/SGSelector.h
- PWGUD/Core/UDHelpers.h
- PWGUD/DataModel/UDTables.h
- PWGUD/TableProducer/CMakeLists.txt
- PWGUD/TableProducer/SGCandProducer.cxx
New Table producer written to study inclusive nuclear reactions based on requiring FIT veto on one side of the event only.
> PWG-UD: Single Gap producer

- EventFiltering/PWGLF/strangenessFilter.cxx
- EventFiltering/filterTables.h
- propagate tracks for mass calculation
- additional histograms for selected Xi/Omega
- add cosine pointing angle
- require minimum number of TPC clusters for daughters
> Improve strangeness tracking filtering

- PWGCF/Femto3D/DataModel/singletrackselector.h
> Change derived data tables names

- PWGLF/TableProducer/cascadebuilder.cxx
- PWGLF/TableProducer/lambdakzerobuilder.cxx
* Adds preselector bookkeeping with better detail 
* fixes a few counting issues in QA histograms
* Adds meaningful X axis labels for selection statistics counters
> Extra builder QA

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
- remove unnecessary enum for cascade type
- change default values of configurables in trackIndexSkimCreator for LfCascade struct
> PWGHF: change configurable default values for struct LfCascade

- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
- simplify cascade mass cut
- add cut on cascade DCAxy to PV
> PWGHF: improve cascade preselection in toXiPi creator

- PWGJE/Tasks/emctmmonitor.cxx
> [BUG] Another incorrect Preslice

- PWGDQ/Core/CutsLibrary.cxx
HI Ionut
I added the a cut for the PWGDQ skimmed tree production.
and please have a look and approve it.
Xiaozhi
> add the cut for the PWGDQ skimmed tree production

- PWGJE/DataModel/TrackJetQa.h
- PWGJE/TableProducer/jettrackderived.cxx
- PWGJE/Tasks/trackJetqa.cxx
Hi @nzardosh , @alicecaluisi,
during the first checks of the track resolution at high pT i noticed some issues with the multiplicity measures. Thus I want to double check them with additional histograms.
(these changes are the same as in the approved PR https://github.com/AliceO2Group/O2Physics/pull/3908 ; I apparently closed the PR after approving without merging.)
Cheerio,
Johanna
> [PWGJE & PbPb QA] Adding multiplicity correlations

- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
- add std::abs to cascade dca preselction in toXiPi creator
> PWGHF: add abs to dca cut in toXiPi creator

- EventFiltering/PWGLF/strangenessFilter.cxx
- fix bachelor masses used for invariant mass calculation
- adjust histogram binning
- add option to cut on CPA and DCA
> Fix strangeness tracking filter

- PWGEM/PhotonMeson/TableProducer/createPCM.cxx
- PWGLF/DataModel/LFStrangenessPIDTables.h
- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/CMakeLists.txt
- PWGLF/TableProducer/cascadebuilder.cxx
- PWGLF/TableProducer/cascadecollisionbuilder.cxx
- PWGLF/TableProducer/cascadefinder.cxx
- PWGLF/TableProducer/cascadepid.cxx
- PWGLF/TableProducer/lambdakzerobuilder.cxx
- PWGLF/TableProducer/lambdakzerocollisionbuilder.cxx
- PWGLF/TableProducer/lambdakzerofinder.cxx
- PWGLF/TableProducer/lambdakzeromcbuilder.cxx
- PWGLF/TableProducer/lambdakzeropid.cxx
* modularizes the various data tables such that they can be used independently 
* adds some extra debug information for the TOF pid studies 
* creates some tables that can be used as derived data for detailed studies
* general streamlining / cleaning / commenting / QA counter improvements
> [PWGLF] Strangeness data model improvements

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update for relaxed v0 cut
> PWGEM/PhotonMeson: update for relaxed v0 cut

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- implement improvements from ST filter to tree creator
- add missing variables to tree
> PWGHF: Improve tree creator for Omega_c with ST

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
Extending the PR https://github.com/AliceO2Group/O2Physics/pull/3948 to the 2 prongs candidate creator
> PWGHF: Add number of primary-vertex contributors in the 2-prong candidate creator

- PWGJE/Tasks/jetfinderQA.cxx
Adding histograms to test rejection of outliers through cutting on jet pT based on the pThat of the event. Currently adding a 2d histogram of jet pT at particle and detector level for a range of outlier cuts.
Note - pThat isn't currently in the collision table. We derive pThat from the weights, based on the calculation of the weight in PYTHIA (see https://www.pythia.org/latest-manual/PhaseSpaceCuts.html ) . We confirmed that the pThat calculation is as expected based on the min and max values of 5 and 300 respectively, that are set in the simulation. See the figure below of the pT hat values.
> Adding pThat histograms

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: implement prefilter for dielectron
> PWGEM/PhotonMeson: implement prefilter for dielectron

- PWGJE/DataModel/EMCALMatchedTracks.h
- PWGJE/TableProducer/emcalMatchedTracksTask.cxx
- Add track alpha and TOF PID NSgima for electrons and pions
> [O2-4360] EMCALMatchedTracks: Add track alpha and TOF PID

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
PWGEM/PhotonMeson: fix for prefilter
> PWGEM/PhotonMeson: fix for prefilter

- PWGLF/TableProducer/LFResonanceInitializer.cxx
- PWGLF/TableProducer/LFTreeCreatorNuclei.cxx
- PWGLF/TableProducer/cascqaanalysis.cxx
- PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
- PWGLF/TableProducer/spectraDerivedMaker.cxx
- PWGLF/Tasks/LFNucleiBATask.cxx
- PWGLF/Tasks/QC/resonanceqa.cxx
- PWGLF/Tasks/QC/tpc_dEdx_postcalibration.cxx
- PWGLF/Tasks/cascadecorrelations.cxx
- PWGLF/Tasks/phianalysisrun3.cxx
- PWGLF/Tasks/rhoanalysis.cxx
- PWGLF/Tasks/spectraTOF.cxx
Table required split to avoid non needed CPU usage
> Clean LF centrality/multiplicity table sub

- Common/Core/trackUtilities.h
- Common/TableProducer/trackPropagation.cxx
> Track propagation with ID

- PWGDQ/Core/CutsLibrary.cxx
Add a new set of cuts to the CutsLibrary.cxx for dielectron selection
> New cuts for jpsi2ee electron selection

- PWGLF/Tasks/QC/CMakeLists.txt
- PWGLF/Tasks/QC/lfpropStudy.cxx
QC task to study parameters of propagated tracks.
@njacazio
> PWGLF: Add task to study track propagation

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- add charge of Omega and bachelor
- fix track association
- streamlining
- update histograms
> PWGHF: Fix tree creator for Omega_c using ST

- PWGHF/Core/HfHelper.h
- PWGHF/D2H/Tasks/taskDs.cxx
This PR adds the histogram of the invariant mass of the reconstructed KK pair to the task output
- Refactored deltaMassPhiDsToKKPi and deltaMassPhiDsToPiKK
> [PWGHF] Added invariant mass of KK pair histogram

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- add V0 and Xi mass to tree output
- fix some variables in tree filling
> PWGHF: Update tree creator for Omega_c using ST

- PWGHF/Core/SelectorCuts.h
Hi @fgrosa , adding some slots for a finer pT binning during ML inference.
> PWGHF: Add extra slots for ML models inference

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- additional variables for Xi rejection
- improved usage of propagated tracks
> PWGHF: Refine tree creator for Omega_c using ST

- PWGDQ/TableProducer/tableMaker.cxx
- PWGLF/Tasks/QC/vertexQA.cxx
While working on the Run 2 converted data,
one has to access the GRPObject from GLO/GRP/GRP.
This has been added to the tableMaker.cxx
> Added CCDB Path and Object of Mag Field for Run 2

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: add histograms for muon
PWGEM/PhotonMeson: fix for e pt resolution
PWGEM/PhotonMeson: set v0 photon min pt 100 MeV
> PWGEM/PhotonMeson: fix for e pt resolution

- PWGLF/Tasks/QC/v0cascadesqa.cxx
- PWGLF/Tasks/hStrangeCorrelation.cxx
eta axis added to the invariant mass histograms
> PWGLF: Change in v0cascadesqa.cxx

- PWGLF/DataModel/LFStrangenessPIDTables.h
- PWGLF/TableProducer/cascadepid.cxx
- PWGLF/TableProducer/lambdakzeropid.cxx
> Add extra TOF debug information for testing purposes

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- exclude cascade daughters as associates
- restart from original track parameters for each combination
> PWGHF: Improve omegac tree creator using ST

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: update for TPConly tracks
> PWGEM/PhotonMeson: update for TPConly tracks

- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/jetHadronRecoil.cxx
Adding a task for studying the Hadron-Jet recoil observable.
> PWGJE: Adding Hadron-Jet analysis code

- PWGLF/TableProducer/nucleiSpectra.cxx
[PWG-LF]: bugfix in DeltaP histograms (separate by charge and species)
> [PWG-LF]: bugfix in DeltaP histograms (separate by charge and species)

- PWGLF/TableProducer/cascademcbuilder.cxx
...this should not be necessary, but apparently it is (not understood yet).
> Add typecast

- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: quick fix for TPConly tracks
> PWGEM/PhotonMeson: quick fix for TPConly tracks

- PWGDQ/Core/HistogramsLibrary.cxx
Fix to avoid double histo definition
> Fix to avoid double histo definition

- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/gammaConversions.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: replace collisionId with globalIndex for consistency
> PWGEM/PhotonMeson: replace collisionId with globalIndex

- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
Dear @victor-gonzalez, 
I added new filters for the skimming and the production of derived data. 
I also added a new column in the collision table for the multiplicity percentiles.
could you please merge the commit? thank you!!
> adding new column and filters

- Common/Core/EventPlaneHelper.cxx
- Common/Core/EventPlaneHelper.h
- Common/DataModel/Qvectors.h
- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/qVectorsCorrection.cxx
> [Common/EventPlane] Updates on initial assignment on constant, structrue of qvectors, and others

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
- PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've changed the default value for process_switch for V0s to false.
> PWGCF - FemtoUniverse - V0 process switched to false 

- PWGDQ/Core/CutsLibrary.cxx
Adding a new track and pair cut  for trigger studies
> PWGEM: Add new cut for trigger study

- Common/TableProducer/CMakeLists.txt
- Common/TableProducer/v0converter.cxx
part of effort: https://alice.its.cern.ch/jira/browse/O2-4491
> Add V0 converter

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
It prints too many unnecessary lines and slows down the operation.
> commented out debug print option

- Common/TableProducer/v0converter.cxx
> Change default V0Type to standard V0

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
TODO: fix process doing MC Truth production in the main producer
> PWGCF: FemtoUniverse -- Changes to the MC Truth producer

- PWGJE/Tasks/jetfragmentation.cxx
Fixed bug in calculation of z
Changed default z bins to exclude 0 and include 1
Weight is now properly propagated when filling response matrix
First attempt at dealing with unmatched particle level jets
Added track pt resolution histogram
Changed default binnings to even numbers to allow for easier rebinning
> [PWGJE] Bug fixes and updates to fragmentation task

- PWGJE/Tasks/jetfinderQA.cxx
- PWGJE/Tasks/jetfinderfullQA.cxx
- PWGJE/Tasks/jetfinderhfQA.cxx
According to the previous analysis in pp collisions 13 TeV by Yongzhen Hou, jet area range should be larger in case of R = 0.6 or larger.
> PWGJE: Broader area range for larger R

- PWGJE/Tasks/jetfinderQA.cxx
- PWGJE/Tasks/jetfinderfullQA.cxx
- PWGJE/Tasks/jetfinderhfQA.cxx
> PWGJE : Adding the ability to cut on pT hat in the QA tasks

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Small updates on the track-D0 task. Changes in the invMass histograms and partition. I've added two new configurables.
> Changes in invMass histograms

- Common/Tasks/qVectorsCorrection.cxx
> [Event plane] fix bug

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
PWGEM/PhotonMeson: update material budget study with dalitz ee
> PWGEM/PhotonMeson: update material budget study with dalitz ee

- PWGDQ/Core/CutsLibrary.cxx
Some more pair cuts for trigger studies
> PWGEM: additional pair mass cuts for trigger studies

- EventFiltering/PWGLF/strangenessFilter.cxx
- adjust binning for ST mass histograms
- add option to use resolution-based mass cut for non-tracked cascades
> Update strangeness filter

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/TableProducer/tableMaker.cxx
This code processes and skims the updated AO2Ds containing the MFT cluster size, expliting the existing process function and adding an additional one for the option without event filtering.
> [PWGDQ] Adding histograms and reduced table for MFT pid studies

- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Adding preliminary selection for tracks based on chosen TPC TOF nSigma cuts. Changing FT0 max default configurable value to 200.
> PWGCF: FemtoUniverse - Adding TPC TOF combined nSigma cuts to Producer

- PWGLF/DataModel/LFStrangenessPIDTables.h
- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/cascadepid.cxx
- PWGLF/TableProducer/lambdakzeropid.cxx
- PWGLF/TableProducer/strangederivedbuilder.cxx
* improves TOF intercept calculation with an analytical segmented detector intercept (no energy losses considered but better geometry) 
* segments true raw info separately from actual pid for ease of exploring with derived data
> [PWGLF] Strangeness TOF PID updates

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/lambdakzeropid.cxx
- PWGLF/TableProducer/strangederivedbuilder.cxx
- PWGLF/Tasks/QC/CMakeLists.txt
- PWGLF/Tasks/QC/strangepidqa.cxx
Spoiler: This actually seems to be working properly! More to follow ...
> Add strange TOF PID QA task

- PWGDQ/Core/CutsLibrary.cxx
New triggers on the suggestion of Ivan and Sebastian
> PWGEM: Add some new triggers to study

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've changed the configurables' name in the FemtoUniverseProducer and applied them in the code.
In the task I've changed the partitions and histograms, and I've added some configurables.
> PWGCF: FemtoUniverse - D mesons update

- PWGHF/D2H/Tasks/CMakeLists.txt
- PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Dear @fgrosa @vkucera @fcatalan92 @samrangy and @jessica, here I am adding a D2H task for D* analysis. It contains basic Signal and QA histograms.
I would like to invite you all to review it and give suggestions which can be added to it to make it more generalized for any D* analysis. 
Upto this point, we already developed this code offline since I had to present the update in ALICE India Meet (21-Nov to 24-Nov).
> PWGHF: Adding D2H task for D* Analysis.

- PWGDQ/Core/HistogramsLibrary.cxx
Adding histogram for centrality studies
> [PWGDQ] Adding histogram for centrality studies

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
> PWGEM/PhotonMeson: add DCA_3D for dielectrons

- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
- added full nSigmaTOF in the FemtoDerived.h
- added full tracks for TOF in the producer task
- modified V0 task to adopt with the above changes
> PWGCF: FemtoUniverse -- added full precision nSigmaTOF

- PWGUD/Core/DGCutparHolder.cxx
- PWGUD/Core/DGCutparHolder.h
- PWGUD/Core/DGSelector.h
- PWGUD/Core/UDHelpers.h
veto trigger available: TVX, TSC. TCE. TOR
> PWG-UD Enable different types of vetoes with FIT detectors:

- CODEOWNERS
> Update LF codeowners

- Common/Tasks/qVectorsCorrection.cxx
> [Event Plane] fine binning

- Common/TableProducer/multiplicityTable.cxx
@strogolo here is the change you asked for. Sorry it took me a while. I had many local changes that I had to organise!
> make multiplicityTable CCDB settings configurable

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzMuMu.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
> PWGEM/PhotonMeson: fix DCA_3D

- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Deleting TOF nSigma cut from Producer, leaving only hasTOF check.
> PWGCF: FemtoUniverse - Deleting TOF nSigma cut from Producer

- PWGHF/D2H/Tasks/taskDs.cxx
This PR enlarges the mass range of the hMass output histogram for the Ds meson
> PWGHF: Change range of Ds mass histogram

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
update histograms for true conversion points
> PWGEM/PhotonMeson: update histograms for true conversion points

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
add cuts for eta < 1.2 for photons
> PWGEM/PhotonMeson: add cuts for eta < 1.2 for photons

- PWGEM/PhotonMeson/Core/EMCPhotonCut.h
- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/emcalPi0EnergyScaleCalib.cxx
- PWGJE/Tasks/emcvertexselectionqa.cxx
- Add a vertexQA task to investigate the quality of vertices depending on contributing tracks
- Add a task to reconstruct pi0s in different calorimeter regions to extract an energy scale parameter based on their mass
- Fix M02 cut, so that it is only applied for clusters with more than one cell
> PWGEM+JE: Add vertexQA and absolute energy calibration scale pi0 task

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
> PWGEM/PhotonMeson: update PCM cuts

- PWGJE/Tasks/emcalPi0EnergyScaleCalib.cxx
- Add inv mass and eta-phi histograms column by column and row by row
- Minor bug fixes
> PWGJE: Add more differential absolute energy scale extraction

- PWGEM/Tasks/phosCalibration.cxx
Added an option to read BadMap, CalibParams, L1Phase from user CCDB for calibration purposes
> PWGEM: Update phosCalibration.cxx

- PWGLF/Tasks/CMakeLists.txt
- PWGLF/Tasks/derivedcascadeanalysis.cxx
New analysis task for the cascade analysis based on the derived data
> PWGLF: new task

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
update RZ cut in material budget task
> PWGEM/PhotonMeson: update RZ cut in material budget task

- PWGEM/Dilepton/Tasks/MCtemplates.cxx
Adding some missing references
> PWGEM: MCTemplates.cxx add missing references

- Common/DataModel/PIDResponse.h
- Common/TableProducer/PID/pidTOFBase.cxx
> Add TOF PID flags for match

- PWGJE/Tasks/emcalPi0EnergyScaleCalib.cxx
- Calculate pi0s per module category (full, two-third, one-third)
- Move initilization of two global variables into the init function 
- Remove category enum as it is only used once
> [EMCAL-1111] Enable absolute energy calib extraction per module type

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Corrections in the producer and D0 task. Removing bad cut on pT and correcting small mistakes in mass histograms filling.
> PWGCF: FemtoUniverse - D0 analysis update

- PWGMM/Mult/Tasks/dndeta.cxx
> PWGMM: dndeta: Consolidate response histograms to reduce output size

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/TableProducer/tableMaker.cxx
- PWGDQ/Tasks/tableReader.cxx
First version of the task to analyze MFT and global tracks for PID studies. The output is saved into a flat tree to allow local analysis.
> [PWGDQ] Adding task to process MFT tracks for PID

- PWGCF/TableProducer/filterCorrelations.cxx
The update now includes the FT0M, FT0A and FT0C centrality info
> Updating task to add centrality info

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
> PWGEM/PhotonMeson: update skimming PCM

- PWGLF/TableProducer/LFTreeCreatorNuclei.cxx
- PWGLF/Tasks/LFNucleiBATask.cxx
Dear @njacazio ,
Please have a look at this commit and approve it.
@giovannimalfattore : Please have a look.
Thank you.
Best regards,
Rutuparna
> [BATask-PWGLF] minor corrections and add histos for MC study

- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
> PWGEM/PhotonMeson: update PCB

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/tableReader.cxx
Adding process function to create tree with MFT tracks associated to a global tracks only
> [PWGDQ] Adding process functions for MDT PID

- Common/TableProducer/PID/pidTOFBase.cxx
- DPG/Tasks/AOTTrack/PID/qaPIDTOF.cxx
> TOF: add QC check on good match

- PWGLF/Tasks/nonPromptCascade.cxx
> Keep bachelor if compatible with one of the two cascades

- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
> PWGEM/PhotonMeson: improve event mixing

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/tableReader.cxx
Adding missing variable to the data model
> [PWGDQ] Adding missing variable to the data model

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
update pcb to remove bad quality photons
> PWGEM/PhotonMeson: update pcb to remove bad quality photons

- PWGMM/Mult/Tasks/dndeta-hi.cxx
But the configurable axis with variable-width option will be reflected later.
> Suggestion reflected

- PWGJE/Tasks/jetfragmentation.cxx
Fixed v0Frag process with right tables
Added unidentified V0 hists
Added hists for nV0s (both incl and ID) per event and per jet
> [PWGJE] Jet Fragmentation: First implementation of V0 fragmentation for data

- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
This reverts commit 58386287d06e00981e733f235e92049413fcab86.
> PWGCF: FemtoUniverse -- Reverted back to stored nSigmaTOF

- PWGLF/DataModel/LFSlimNucleiTables.h
- PWGLF/TableProducer/nucleiSpectra.cxx
@mpuccio @ivorobye this includes ITS-cluster sizes to the table
> Add its cluster size to nuclei table

- PWGHF/D2H/TableProducer/candidateSelectorB0ToDPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
@AlexBigO can you have a look? Thanks!
> PWGHF: allow the application of PID to the bachelor pion regardless the D daughters

- PWGJE/Tasks/emcalPi0EnergyScaleCalib.cxx
- Add configurable that allows to restrict the cluster acceptance
- Either only or all but clusters behind TRD structure
- Either only EMCal or only DCal clusters
- Add basic 2d invariant mass-pT histogram to prevent double counting when monitoring the calibration
- Change TRD columns based on observations in calibration
> [EMCAL-1111] Enable more differential absolute energy calibration

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
More cuts for QC of Pb--Pb + mean cluster size in ITS (first for non-skimmed)
> Cuts definition + mean ITS cluster size

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
> LF: Derived data cascade analysis

- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
Dear @njacazio ,
Could you please approve it?
Thank you.
Rutuparna
> [BaTask] MC pTshift correction histos for DantiD

- PWGDQ/Core/CutsLibrary.cxx
Add one cut for Pb--Pb to reduce the number of cuts in the QC
> Add one cut

- Common/Tools/Multiplicity/multCalibrator.cxx
> Common: protect against underflow

- PWGUD/DataModel/UDTables.h
- PWGUD/TableProducer/UPCCandidateProducer.cxx
Changes:
* Reduced ZDC table containing: timeZNA, timeZNC, energyCommonZNA, energyCommonZNC
* Some minor fixes
> Adding reduced ZDC info to UPCCandidateProducer

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/trackIndexSkimCreator.cxx
This PR implements the proper filters and partitions in order to speedup the HF combinatorial (especially when multiple channels are enabled).
Still to be tested, please do not merge yet.
> PWGHF: optimise HF combinatorial

- EventFiltering/PWGEM/EMPhotonFilter.cxx
- EventFiltering/PWGEM/EMPhotonFilterQC.cxx
- EventFiltering/filterTables.h
> EventFiltering/PWGEM: update photon trigger

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
Dear @victor-gonzalez,
In this commit we fix the recent bug with index referencing that appeared after the O2 update happened a week ago.
We also added some minor improvements. Could you please approve it?
Thank you.
@njacazio @sofiatomassini
> fixing index referencing and adding minor improvements and adjustments

- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/qVectorsCorrection.cxx
> [Event Plane] Adding CCDB connection

- Tutorials/src/tracksCombinations.cxx
Follow up to https://github.com/AliceO2Group/AliceO2/pull/12393
> Added unit test for partition block combinations

- PWGUD/Tasks/upcTauTau13topo.cxx
- Kaon and proton veto added to selection
- minor changes in configurables
- histogram labels adopted to the ALICE style
- added control histograms per cut
- added track type histograms
- minor style and comment corrections
> PWGUD: K and p PID veto added to tautau analysis + many histograms

- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
Dear @victor-gonzalez 
I changed the table producer task too add the right way to access the particle origin in MC
could you please approve this change?
Thank you,
Sofia
@glromane @njacazio
> updated MC origin info

- EventFiltering/PWGLF/nucleiFilter.cxx
Add number of filtered events QA for 3-body decayed hypertirton
> Add number of filtered events QA for 3-body decayed hypertirton

- Common/TableProducer/fwdtrackextension.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/dqEfficiency.cxx
- PWGDQ/Tasks/dqFlow.cxx
- PWGDQ/Tasks/tableReader.cxx
- Adding variables for DQ flow study
> [PWGDQ]adding variables for DQ flow

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
> PWGEM/PhotonMeson: update histogram binning

- PWGEM/PhotonMeson/Core/DalitzEECut.h
> PWGEM/PhotonMeson: fix for XOR

- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
> PWGEM/PhotonMeson: update pi0/eta MC task

- PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
- PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
Here we change V0datas to V0dataswithoutrackX
> PWGLF: h-strange corr. analysis subscription cleanup

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
add quick QA histograms for V0s
> PWGEM/PhotomMeson: add quick QA histograms for V0s

- PWGLF/Tasks/Nuspex/hypertriton3bodyMCQA.cxx
- PWGLF/Tasks/Nuspex/hypertriton3bodyanalysis.cxx
Small change: add event selection restrict the Z position of primary vertex < 10cm
> PWGLF: Add event selection of vertexZ for hypertriton 3-body analysis

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
add MC gen part + cut adjustments
> PWGLF: cascade analysis

- PWGUD/Tasks/upcTauTau13topo.cxx
To avoid issue #4573 
Qtot configurable
> PWGUD: To avoid issue #4573 + Qtot configurable

- Common/Core/EventPlaneHelper.cxx
- Common/Core/EventPlaneHelper.h
- Common/Tasks/qVectorsCorrection.cxx
> [Event Plane] Fixing event plane resolution

- PWGDQ/Tasks/CMakeLists.txt
- PWGDQ/Tasks/dqCorrelation.cxx
@mguilbau @sjzhu0v0 @lucamicheletti  First commit of dqCorrelations Task. After discussion with Ionut, to be mainly used for barrel. To be further developped
> [PWGDQ] Adding dq-Correlations task

- Common/TableProducer/fwdtrackextension.cxx
- PWGDQ/Tasks/tableReader.cxx
- Adding dimuon invariant mass spectra for unambiguous tracks only
- Adding muon tracks to fwdtrackestension
> [PWGDQ] Adding QA plots for ambiguous tracks studies

- PWGCF/Flow/Tasks/FlowPbPbTask.cxx
small changes: 
1. change ccdb url; 
2. using enum for index;
major changes: 
1. change pt bins; 
2. add code to produce NUA
3. add code to read NUA and NUE
> PWGCF: flow-pbpb: apply NUA and NUE weights

- PWGJE/Core/JetTaggingUtilities.h
- PWGJE/TableProducer/jettaggerhf.cxx
- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/jettaggerhfQA.cxx
I have already done a pull request for heavy flavor tagging codes but I have changed more simple because I think it is important to make skeleton code.
https://github.com/AliceO2Group/O2Physics/pull/4350
I should appreciate it if experts could help me make a good choice.
Core/JetTaggingUtilities.h
Add getGeoSign and calculation of dca_xyz
if dca_xyz measurement is made in common, I will remove it.
TableProducer/jettaggerhf.cxx
algorithm's name changed and add with gluon shower
Task/jettaggerhfTC.cxx
There are task of general QA for hf tagger and analysis of track counting method for prototype.
> [PWGJE] First update tagging QA

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
update PCM with ITSonly tracks
> PWGEM/PhotonMeson: update PCM with ITSonly tracks

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
implement filter for v0Type > 0
> PWGEM/PhotonMeson: implement filter for v0Type > 0

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/dptdptcorrelations.cxx
Also collisions within ITS read out frame border are rejected
> Second step towards identified analysis

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
revert mean ITS cluster size cut
> PWGEM/PhotonMeson: revert mean ITS cluster size cut

- PWGLF/Tasks/Strangeness/kinkAnalysis.cxx
> Fix bc() access

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/MCUtilities.h
> PWGEM/PhotonMeson: update nm task mc

- PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
Update info to know if in three-body case the events being mixed have actually at leat three tracks
> Updated Mask for mixing of three-body

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Fix the bit mask setup for the Track properties selections
> Fix track properties mask

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
minor quick fix to pca cut in pcb
> PWGEM/PhotonMeson: minor quick fix to pca cut in pcb

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
> PWGEM/PhotonMeson: update PCM cut

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
Complete the muon quality cuts in the HFL muon source task for MC and add a configurable mcMask cut
> PWGHF: Complete the muon quality cuts in the HFL muon source task

- DPG/Tasks/AOTTrack/qaEventTrack.cxx
- Adding some pT resolution and pull histograms to `qaEventTrack` task to compare with results for secondary tracks from Lambdas.
- minor changes
@adubla and @njacazio
> DPG: Add pT resolution histos + minor changes

- PWGDQ/Core/CutsLibrary.cxx
Implement a new trigger without DCA.
> PWGEM: new Trigger, without DCA cut

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
PWGEM/Dilepton: update ML tree DDA
PWGEM/PhotonMeson: add nolls per bc in em event table
> PWGEM/Dilepton: update ML tree DDA

- PWGLF/Tasks/Resonances/f0980analysis.cxx
> [PWGLF] add ep analysis

- PWGHF/TableProducer/treeCreatorToXiPi.cxx
Fix Index pointing error by subscribing to Tracks table in toXiPiTreeCreator
> PWGHF: fix index pointing error in tree creator

- EventFiltering/PWGEM/EMPhotonFilter.cxx
- EventFiltering/PWGEM/EMPhotonFilterQC.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
> EventFiltering/PWGEM: update photon trigger qc task

- PWGDQ/Core/VarManager.h
Fixing the calculation of the Psi EP in DQ flow framework
> [PWGDQ] Fixing the calculation of the Psi EP in DQ flow framework

- DPG/Tasks/AOTTrack/V0Cascades/perfK0sResolution.cxx
- add way to compute inv mass from daughters
> K0Perf: Add check on the ITS IB

- PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
Possibility to reduce the number of background tracks/pairs written to the table.
Default values of the configurables leave the task unchanged.
> PWGEM: bg reduction factor for treeCreator

- PWGUD/Tasks/CMakeLists.txt
- PWGUD/Tasks/PolarisationRho.cxx
- Tutorials/PWGUD/CMakeLists.txt
First task for analysis in the central barrel of:
- 2pi states
- 2K states 
- 2K states without PID, using only ITS
- 4pi states 
- 6pi states (3+3 tau topology)
- Rho polarisation
> [PWGUD] Exclusive 2pi, 2K, 2particles, 4pi, 6pi, rho polarisation

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
> PWGEM/Dilepton: update tree creator DDA

- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/qVectorsCorrection.cxx
> [Event plane] Checking detector gain

- PWGEM/Dilepton/Tasks/MCtemplates.cxx
An update to test if current version  runs on hyper loop. 
still have to update track selection for selected events 
(There is no event selection for when filling track histograms)
> PWGEM: update MCtemplate task, 

- PWGLF/DataModel/LFzdcSPtables.h
- PWGLF/TableProducer/CMakeLists.txt
- PWGLF/TableProducer/zdcSP.cxx
- **Add small task to filter out ZDC info**
> Add task to filter out ZDC info

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
update tree creator DDA to tag kaon
> PWGEM/Dilepton: update tree creator DDA to tag kaon

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
update Kaon selection via phi->KK
> PWGEM/Dilepton: update Kaon selection via phi->KK

- PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
Ciao @fgrosa !
Hopefully, this is the final correction on the previous PR.
> PWGHF: Fix typo in MC checks in DPi creator

- PWGDQ/Core/CutsLibrary.cxx
> PbPb TOF required QA

- PWGLF/TableProducer/LFResonanceInitializer.cxx
adding switch for event plane analysis
> [PWGLF] adding switch for event plane analysis

- EventFiltering/PWGLF/nucleiFilter.cxx
- **Fix TPCinnerParam to be a rigidity**
> Fix inner param for the nuclei filter

- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
@ZFederica could you please cross check that this is ok? Thanks!
> EventFiltering/PWGHF: Add min cut on Xi for Xi+bachelor triggers

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
Add std::abs for cascade dca preselctions in cascades derived data production struct
> PWGHF: fix cascades derived data

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorCascade.cxx
- PWGHF/TableProducer/candidateCreatorDstar.cxx
- PWGHF/TableProducer/trackIndexSkimCreator.cxx
@fcatalan92 @fgrosa here the implementation for the 3 prong. If you agree with it, I can go ahead also with the rest.
> PWGHF: add centrality selection in candidate creators.

- PWGLF/DataModel/Vtx3BodyTables.h
- PWGLF/TableProducer/CMakeLists.txt
- PWGLF/TableProducer/decay3bodybuilder.cxx
- PWGLF/TableProducer/hypertriton3bodybuilder.cxx
- PWGLF/TableProducer/hypertriton3bodyfinder.cxx
- PWGLF/Tasks/Nuspex/hypertriton3bodyMCQA.cxx
- PWGLF/Tasks/Nuspex/hypertriton3bodyanalysis.cxx
Move TPC PID MC check to tasks
Implement hyperhelium4 hypothesis
Add configurable for bachelor charge
> PWGLF: Change hypertriton 3body decay builder to a common task

- Common/TableProducer/qVectorsTable.cxx
- PWGLF/TableProducer/nucleiSpectra.cxx
> [event plane] adding gain equalization

- PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
Hello @fgrosa, I added a way to distinguish between:
- `D* -> D Pi0/gamma`
- `D* -> D0 Pi`
- `D` not coming from `D*`
by adding the pdg codes (as indicated in the comments L445-L450), which is made possible by removing the `break` in the "charm mother hypotheses" loop.
> PWGHF: Implement extra MC checks in DPi creator

- PWGHF/TableProducer/candidateCreator3Prong.cxx
> PWGHF: Fix typo in KKPi channel of candidateCreator3Prong

- PWGEM/Dilepton/DataModel/lmeeMLTables.h
- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
add a process for training primary/secondary electron
> PWGEM/Dilepton: add a process for training primary/secondary electron

- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
- fixing the order of the parameters in the fillQA function in the
debug-track task
- unify the configurable axis object for multTempFit across the pair tasks and add more info in the description
> [PWGCF - FemtoDream]: Minor fixes

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
revert a method for tagging kaon
> PWGEM/Dilepton: revert a method for tagging kaon

- PWGCF/Core/AnalysisConfigurableCuts.h
- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/dptdptcorrelations.cxx
- PWGCF/TwoParticleCorrelations/Tasks/CMakeLists.txt
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also reorganized the PID configurable and the PID selector 
Also standard use of the self configuration
> Efficiency and QA task for identified analyses

- PWGLF/Tasks/Resonances/KshortKshort.cxx
Since the program was consuming too much memory, I added boolean configurable for the QA plots, so that I do not fill their histograms when I don't want.
> added boolean configurable for the QA plots

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
minor update for ML tree creator DDA
> PWGEM/Dilepton: minor update for ML tree creator DDA

- PWGLF/DataModel/EPCalibrationTables.h
- PWGLF/DataModel/LFHypernucleiTables.h
- PWGLF/TableProducer/epvector.cxx
- PWGLF/TableProducer/hyperRecoTask.cxx
- PWGLF/Tasks/Resonances/phipbpb.cxx
> Use EP tables for H3L + fix calibration typo

- PWGLF/DataModel/LFzdcSPtables.h
- PWGLF/TableProducer/zdcSP.cxx
- **Add run number to the calibration output**
> Add run number to the calibration output

- PWGHF/TableProducer/candidateCreatorDstar.cxx
Hi @fgrosa ,
In this I tried to remove use of Material LUT as instructed in [ D2H Meeting 
20/02/2024](https://indico.cern.ch/event/1363522/contributions/5818623/attachments/2804512/4893507/2024Feb20_D2H_CoordinatorsReport.pdf).
Please see if I am not making any mistake though I tested it by building and running locally.
> PWGHF: removing use of material LUT

- PWGCF/FemtoDream/Core/femtoDreamContainer.h
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
- Possibility to obtain the smearing matrix for different MC origins (can be activated with the configurable "ConfOptsmearingByOrigin")
> [PWGCF-FemtoDream] Optional: MCorigin in Smearing

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
Cuts and histos for PID studies in PbPb
> PID studies for PbPb

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
> PWGEM/Dilepton: update ML tree creator DDA

- PWGCF/Core/AnalysisConfigurableCuts.h
- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/dptdptcorrelations.cxx
- PWGCF/Tasks/match-reco-gen.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also incorporated the track selection according to MM criteria option
> Additional information for PID quality control

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
Add event histos for centrality-dependent process functions and small updates on the task
> Update the task heavy-ion-mult.cxx

- PWGEM/PhotonMeson/DataModel/gammaTables.h
quick fix for dynamic column for ITSob
> PWGEM/PhotonMeson: quick fix for dynamic column for ITSob

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
> PWGEM/Dilepton: optimize Omega mass range

- PWGDQ/Core/CutsLibrary.cxx
fix + larger number of TPC clusters
> fix + larger number of TPC clusters

- DPG/Tasks/AOTTrack/qaEventTrack.cxx
> DPG: add 3D histogram TPC clusters vs. eta vs. pt.

- Common/Tasks/multiplicityDerivedQa.cxx
- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterCharmHadronSignals.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
Hi @zhangbiao-phy could you please have a look? If it's fine for you, still do not merge it since I would like to wait because I also want to add the event selection cut on the time-frame edges. Thanks!
> EventFiltering/PWGHF: implement pT-dependent mass cut

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
> PWGMM: heavy-ion-mult: add TF border selection

- PWGLF/Tasks/Resonances/deltaanalysis.cxx
> added histograms TPC only

- PWGCF/Flow/Tasks/FlowPbPbTask.cxx
Hi victor, I have seen your suggestion of "using the templated version of add to simplify your code", but there is some issues on my local computer so I can't test the code.
I will apply your suggestion in next PR.
> PWGCF: pbpb-flow: fix QA plots

- PWGDQ/Tasks/filterPbPb.cxx
Remove vetos based on tracks and muons tables, to make filter consistent with tableMaker_withAssoc. Remove unnecessary code.
> PWGDQ: Remove cuts based on tracks and muons tables from filterPbPb

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- additional variables for topological selection
> PWGHF: Update tree creator for Omega_c (ST)

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/tableReader.cxx
adding event mixing calculation for DQ flow
> [PWGDQ]adding event mixing calculation for DQ flow

- Common/TableProducer/multiplicityTable.cxx
> Common: Optimise sliceby use in multiplicity-table

- PWGDQ/Core/VarManager.h
PWGDQ/Core: update VarManager for TF border and ITSROF border
> PWGDQ/Core: update VarManager for TF border and ITSROF border

- EventFiltering/PWGEM/EMPhotonFilter.cxx
- EventFiltering/PWGEM/EMPhotonFilterQC.cxx
EventFiltering/PWGEM: update for No TF Border
> EventFiltering/PWGEM: update for No TF Border

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add QA histograms on the TPC signal for the positive and negative V0 decay daughters
> Add TPC signal QA histograms

- Common/TableProducer/centralityTable.cxx
Testing for MC centrality calibration for the Pb-Pb 2023 period, almost ready...
> Common: print an explicit warning of MC scaling use

- PWGJE/DataModel/EMCALMatchedCollisions.h
- PWGJE/TableProducer/emcalCorrectionTask.cxx
- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/mcgeneratorstudies.cxx
- Add task that extracts generated pt spectrum of a specific particle
- Add isemcreadout boolean to emcalcollisionmatching table
> PWGJE: Add task for MC generator studies and write EMCreadout status to table

- PWGJE/Tasks/jetHadronRecoil.cxx
Range on dphi changed to 0 to 2pi, adding a dphi cut of |dphi - pi| < 0.6 to pt plots
> PWGJE: Adding minor changes to pt and phi plots

- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
update alias_raw and selection_raw
> PWGEM/PhotonMeson: update alias_raw and selection_raw

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/gammaConversions.cxx
remove duplicated V0Recalculation table
> PWGEM/PhotonMeson: remove duplicated V0Recalculation table

- PWGCF/FemtoUniverse/Core/FemtoUniverseCollisionSelection.h
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've changed the FemtoUniverseCollisionSelection.h. Changes regarding isSelected().
> PWGCF:FemtoUniverse - fixing collision selection

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
More differential PID studies if poassible for Pb--Pb
> More differential PID studies if poassible

- PWGEM/PhotonMeson/Core/EMEventCut.h
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
change filling event histograms
> PWGEM/PhotonMeson: change filling event histograms

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
change how to fill collision counter
> PWGEM/PhotonMeson: change how to fill collision counter

- PWGLF/TableProducer/LFResonanceInitializer.cxx
> [PWGLF] correct description

- PWGHF/Core/SelectorCuts.h
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
This PR adds the possibility of applying selections on the chi2PCA of Ds candidates
> PWGHF: Add chi2PCA cut to Ds selector

- PWGEM/Tasks/phosPi0.cxx
Corrected invariant mass filling - added needed cuts for the second cluster.
> PWGEM/Tasks: phosPi0 - corrected inv. mass filling

- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzMuMu.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
> PWGEM/PhotonMeson: improve mixed event loop

- PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
- PWGEM/Dilepton/Utils/MCUtilities.h
> PWGEM/Dilepton: add MCUtilities.h for HFee

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
@fgrosa here the PR we discussed about. Let me know if you like this version where the `THnSparse`s can be switched on/off. This of course introduces a bit of `if` statements. If you prefer I can keep everything active w/o `if`s, let me know what you prefer.
> PWGHF: split THnSparses of HF polarization task, one per cosThStar axis.

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Tasks/filterPPwithAssociation.cxx
Rejecting events on the TF boundaries
> Implementation of TF boundaries in the DQ filter task

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've changed femtoUniversePairTaskTrackD0.cxx. I've added some configurables and histograms. I've added a new process function to calculate the angular correlations using side-band method.
> PWGCF: FemtoUniverse - update in D0 analysis task

- PWGHF/Tasks/taskMcValidation.cxx
In this way the task `o2-analysis-hf-task-mc-validation` can have sub-wagons.
> PWGHF: Remove obsolete table with HF signal info

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
Make separate between kNoITSROFrameBorder and kNoTimeFrameBorder selection conditions to estimate the percentage of event rejection in each of these conditions
> PWGMM:Mult:Update heavy-ion-mult.cxx

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
PWGEM/PhotonMeson: re-organize ll cuts
> PWGEM/PhotonMeson: re-organize ll cuts

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
PWGEM/PhotonMeson: update pair dca 3d cut for ll
> PWGEM/PhotonMeson: update pair dca 3d cut for ll

- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
PWGEM/PhotonMeson: add dynamic column for primary e/mu tables
> PWGEM/PhotonMeson: add dynamic column for primary e/mu tables

- Common/TableProducer/qVectorsTable.cxx
> [event plane] add ccdb for gain eq

- PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR contains a fix to the Ds meson template in the taskFlowCharmHadrons code
> PWGHF: fix Ds template in flow task

- PWGHF/HFC/TableProducer/correlatorDMesonPairs.cxx
This PR aims to update correlatorDMesonPairs.cxx by adding the cuts implemented and discussed on correlatorDMesonParisTesting.cxx. In particular:
- Adding a configurable only to select the events which have an invariant mass that is close to the PDG one
- Adding a cut to avoid having candidates who share a daughter track
- Updating the construction of the for loop for the second candidates
> PWGHF: add extra cuts on correlatorDMesonPairs.cxx

- Common/TableProducer/qVectorsTable.cxx
> [event plane] configurable path

- PWGDQ/Core/HistogramsLibrary.cxx
Adding histograms to flow-dimuon category
> [PWGDQ] Adding histograms to flow-dimuon category

- PWGLF/Tasks/Resonances/KshortKshort.cxx
> corrected the rapidity acceptence from < 0.5 to <= 0.5 to get more stats

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
@fgrosa this is the PR that we discussed. Actually I did not manage to test it locally due to the issue that I've mentioned [here](https://mattermost.web.cern.ch/alice/pl/4usqpqj1piyj8xto8xiinj3aqe), waiting for its resolution.
> PWGHF: add rotational background for Lc->pKpi.

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I have modified the process for evaluating the efficiencies and added some configurables in order to modify the axis of the histograms. Let me know if you have any comments or suggestions.
Best regards,
Samuele
> PWGHF: Ds-h correlation, process efficiency

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
Adding histogram for v2 resolution correction
> [PWGDQ] Adding histogram for v2 resolution correction

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/HFC/TableProducer/correlatorDMesonPairsTesting.cxx
- PWGHF/TableProducer/candidateSelectorD0.cxx
- PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
- PWGHF/TableProducer/candidateSelectorDstarToD0Pi.cxx
- PWGHF/TableProducer/candidateSelectorLc.cxx
- PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
- PWGHF/TableProducer/derivedDataCreatorD0ToKPi.cxx
- PWGHF/TableProducer/pidCreator.cxx
- PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
- PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
- PWGHF/TableProducer/treeCreatorDstarToD0Pi.cxx
- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
I kept the extended-table data model commented out in hope of future possibility of conditional spawning.
> PWGHF: Replace extended TPC+TOF tables with tables produced by PID creator

- Common/TableProducer/qVectorsTable.cxx
add safety for ccdb connection
> [event plane] add safety for ccdb connection

- PWGUD/Core/SGSelector.h
- PWGUD/TableProducer/SGCandProducer.cxx
SG Selector function adjusted to return the BS of the closes non-empty BC and not just a flag that it is not empty.
For this BC, and not for the collision BC the ZDC and FIT info is filled into the derived data.
> PWG-UD: SGCand producer fills FIT and ZDC info for the busy bunch crossing

- Common/TableProducer/qVectorsTable.cxx
> [event plane] correct for exception

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
add TF border rejection in ML tree creator DDA
> PWGEM/Dilepton: add TF border rejection in ML tree creator DDA

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add TOF selections based on the deltaT info for positive and negative V0 daughters
Fix the loop on the generated candidates
> Add TOF selections + fix generated candidates loop

- PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h
- DCA_z axis are added in for the template plots when running in debug mode
- multiplicity axis is now also used only in debug mode
> [PWGCF -FemtoDream]: Add DCA_z plots

- PWGLF/TableProducer/LFResonanceInitializer.cxx
> [PWGLF] add EP ana into ColCut

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
minor fix to nocut in DalitzEECut
> PWGEM/PhotonMeson: minor fix to nocut in DalitzEECut

- PWGDQ/Core/HistogramsLibrary.cxx
Adding event-mixing R2SP vs mass for event1 and event2 in the histogramLibry
> {PWGDQ] Adding event-mixing R2SP vs mass for event1 and event2 in the histogramLibry

- Common/TableProducer/qVectorsTable.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
> [event plane] fix timestamp

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Add boolean to enable/disable TPC QA plots
- Add centralityVsNch QA plot in real and MC data processing functions
> Add boolean to enable/disable TPC QA plots + add centralityVsNch QA plot

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
TF event selection, nsigma histograms
> PWGLF: changes in derivedCascadeAnalysis.cxx

- PWGLF/Tasks/Nuspex/CMakeLists.txt
- PWGLF/Tasks/Nuspex/deutRtTask.cxx
Add Task for analysing Deuteron RT
> PWGLF: Add Task for analysing Deuteron RT

- PWGDQ/Tasks/dqFlow.cxx
Removing unused dependences in flow task using central q-vectors
> [PWGDQ] Removing unused dependences in flow task

- PWGDQ/Tasks/CMakeLists.txt
- PWGDQ/Tasks/MIDefficiency.cxx
Added task to calculate MID efficiency from AO2Ds + modified cmake file to compile the task
> [PWGDQ] Added task to calculate MID efficiency from AO2Ds

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/k892SpherocityAnalysis.cxx
Added the analysis code for K*(892)_Spherocity_Analysis; also made changes in the CMake list
> K892 update

- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
> EventFiltering/PWGHF: add configurable to force TOF proton PID in femto

- PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
PWGLF: Fix MClabels subscription in nonPromptCascade.cxx
> PWGLF: Fix MClabels subscription in nonPromptCascade.cxx

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Changes in the task for D0 analysis. I've changed the configurables type and some binning in the histograms.
> PWGCF: FemtoUniverse - D0 task update

- DPG/Tasks/AOTTrack/qaEventTrack.cxx
Added a configurable bool to apply a timeframe cut on collisions
> [AOTTrack] added a timeframe cut on collisions

- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/crCharmHadronization.cxx
- PWGJE/Tasks/hffragmentationfunction.cxx
PWGJE : task created for studying the D0 and Lambda_c hadronization differences. 
That is done mainly with the jet-HF candidate distance in eta-phi plane observable.
Currently only D0 jets are being considered.
Lambda_c jets will be included in the analysis in the future.
> PWGJE : Jet charm hadronization

- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
> mixed events

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also incorporate electrons and muons to QC
> [PWGCF] Limit the garbage when there is TOF

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add QA plots on the TOF delta time for the positive and negative decay daughters, as a function of centrality, V0 pT, pos/neg pT and pos/neg pTot
> Add TOF QA plots

- PWGLF/TableProducer/nucleiSpectra.cxx
> Add histograms for nuclei flow

- PWGDQ/Core/VarManager.h
Fixing varManager for flow analysis using the central framework
> [PWGDQ] Fixing var manager for flow analysis

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
> PWGLF: change in derivedcascadeanalysis.cxx

- PWGDQ/Core/VarManager.h
Minor fix in the EP calculation
> [PWGDQ] Minor fix in the EP calculation

- Common/Core/EventPlaneHelper.cxx
- Common/TableProducer/qVectorsTable.cxx
> [event plane] updates for FV0

- PWGDQ/Core/HistogramsLibrary.cxx
Optimizing histograms for flow analysis
> [PWGDQ] Optimizing histograms for flow analysis

- PWGDQ/Tasks/CMakeLists.txt
This is a PR to fix the accidental error that I made with my previous PR https://github.com/AliceO2Group/O2Physics/pull/5082, apparently the later just removed two tasks that were there before in CMakeLists.txt. I express sincerely my apologies to people who were having trouble with this mistake...
> [PWGDQ] Fix for mistake of accidentally deleted tasks in CMakeLists.txt

- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- With the configurable "ConfRandomizePair" it is possible to randomize, which particle is used as particle 1 and particle 2 in the pairs of identical particles. This seems to be necessary due to the implicit ordering of the tracks in the framework
> [PWGCF - FemtoDream] Randomizing particle 1 and particle 2

- PWGLF/TableProducer/nucleiSpectra.cxx
> Correct filling of dedx histogram

- PWGHF/Core/HfMlResponseDplusToPiKPi.h
This PR adds columns in HfMlResponseDplusToPiKPi
> PWGHF: Adding columns in Dplus MlResponse

- PWGHF/Core/HfMlResponseXicToPKPi.h
- PWGHF/D2H/Tasks/taskLc.cxx
- PWGHF/TableProducer/candidateSelectorXicToPKPi.cxx
- PWGHF/TableProducer/treeCreatorXicToPKPi.cxx
Adding variables for combined PID with TPC and TOF, and other variables, to match those of the Lc analysis
> PWGHF: adding comb PID to Xic

- PWGDQ/Tasks/dqFlow.cxx
This is a PR for having in flow task the weights for acceptance using Generic Framework from PWGCF. A proper CCDB user-path will be created for saving weights.
> [PWGDQ] Add acceptance weights for Q-vector

- PWGHF/Tasks/taskMcEfficiencyToXiPi.cxx
Fix (add missing absolute value) in task for efficiency calculation toXiPi
> PWGHF: fix in efficiency calculation toXiPi

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
@fgrosa I think we overlooked it last time
> PWGHF: remove refusal rot. axis for Lc MC.

- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
Hi @fgrosa , here is the fix :)
Note: this line was only missing at the "DplusPi creation" level, not at the "D0Pi creation" level
> PWGHF: Add missing line to DplusPi creator

- PWGMM/Mult/DataModel/ReducedTables.h
- PWGMM/Mult/TableProducer/reducer.cxx
* Make sure descriptions correspond to type names so that merging can find the index
* Replace `info` logging level by `debug`
> PWGMM: Mult: fix reduced data model descriptions and excessive logging

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
Adding signed pair DCA to VarManager and HistogramsLibrary
> PWGEM: Add signed pair DCA variable

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/DataModel/DerivedTables.h
- PWGHF/TableProducer/CMakeLists.txt
- PWGHF/TableProducer/derivedDataCreatorLcToPKPi.cxx
> PWGHF: Add Lc -> P K Pi derived-data creator

- PWGJE/Tasks/jetfragmentation.cxx
* Added hists for unidentified V0s (pT/z, ctau/M/R/etc)
* Added (pt_part, pt_det, M_K, M_L, M_aL) hists for identified, matched V0s
> [PWGJE]: Jet Fragmentation: Added more histograms for matched V0s

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add maximum V0 decay radius cut (to potentially cut out data/MC discrepancy regions)
> Add maximum V0 decay radius cut

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/kstarpbpb.cxx
> kstar flow

- PWGLF/TableProducer/LFResonanceInitializer.cxx
- Update Lambda(1520) PDG code from `3124` to `102134`
- Add other resonances
> Update Resonance PDG codes

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack3DMultKtExtended.cxx
This reverts commit 727f259ded6c0417f7435a7d1f5d6300c5aa8cd5.
> Revert "PWGCF: FemtoUniverse -- Add mixing in centrality, PID fix

- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also incorporated the nsigmas histograms
> Reduce the number of needed histograms

- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
> mc centrality

- PWGLF/TableProducer/nucleiSpectra.cxx
Addition of a condition to ignore PID pre-selections for MC particles in the nucleiSpectra struct. This change ensures that the MC particles are processed correctly without the pre-selection bias. Also, add logic to only store particles of interest based on configuration settings, improving the efficiency of particle storage.
> Ignore PID pre-selections for MC particles in nucleiSpectra

- PWGHF/DataModel/DerivedTables.h
- PWGHF/TableProducer/derivedDataCreatorD0ToKPi.cxx
- PWGJE/Core/JetHFUtilities.h
> PWGHF: Sync derived D0 collision tables with Lc

- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
- [URGENT] Fix event rejection due to centrality estimator 
- Remove hard cut [obsolete] 
- Fix rapidity bug in DCAxy plots
- Fix bug that caused memory leak if enable both after/before cut DCA histograms
- Code clean up
> [PWGLF] LightNucleiTask - Fix event selection bug

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/TableProducer/LFResonanceInitializer.cxx
- PWGLF/Tasks/Resonances/k892analysis.cxx
@BongHwi Please approve
Thanks
> added manual track selection cuts

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Allows for the switch of reconstructed pT/rapidity to generated pT/rapidity in MC
> Use generated pt and rapidity in MC

- PWGLF/TableProducer/lambdakzeromcfinder.cxx
> PWGLF: deal with TPC-only duplicates in findable exercise

- PWGDQ/Tasks/mchAlignRecord.cxx
* Added MCH-MID matching selection
* Removed non necessary setup for track fitter
* Setup for global tracking configuration
> [PWGDQ] Add global configuration for tracking parameters used in record task

- Common/TableProducer/qVectorsTable.cxx
> [event plane] fix

- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
In this commit we're adding the TimeFrame event cut that was suggested by the Physics Coordination and also fix the cut on the number of shared clusters in TPC. Could you please approve it. Thank you.
> adding TimeFrame cut and TPC Ncls fraction cut

- PWGLF/Tasks/Nuspex/nuclei_in_jets.cxx
> Fix iteration on particles

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I've added a new step in the process to evaluate candidate efficiencies. 
Cheers,
Samuele
> PWGHF: HFC, Adding new step in candidate efficiency evaluation

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
PWGEM/PhotonMeson: minor update on histogram bins and ee cut
> PWGEM/PhotonMeson: minor update on histogram bins and ee cut

- PWGCF/Core/AnalysisConfigurableCuts.h
- PWGCF/Core/PWGCFCoreLinkDef.h
- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/match-reco-gen.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also
- incorporated overall minimum momentum for analysis
- default estimator when processes with no centrality
- PID processes removal from filter collision task
- preparation for potential FullPID basis
> Fine tuning the track selection

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update histograms in MC
> PWGEM/PhotonMeson: update histograms in MC

- PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: adjust MC primary selection
> PWGEM/PhotonMeson: adjust MC primary selection

- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: replace MC primary selection
> PWGEM/PhotonMeson: replace MC primary selection

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
> modify mix event PID selection

- PWGCF/Flow/Tasks/FlowPbPbTask.cxx
possible problem in the phi correction
> PWGCF: pbpb-flow: fill NUA after additional track cut

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
Reduce the dimension of THnSparse and add centrality 1D histo inside track loop
> Update on PWGMM/Mult/Tasks/heavy-ion-mult.cxx

- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
PWGEM/PhotonMeson: improve MC primary selection in tagging
> PWGEM/PhotonMeson: improve MC primary selection in tagging

- Common/TableProducer/caloClusterProducer.cxx
- PWGEM/Tasks/CMakeLists.txt
- PWGEM/Tasks/phosAlign.cxx
- PWGEM/Tasks/phosCalibration.cxx
- PWGEM/Tasks/phosNbar.cxx
- PWGEM/Tasks/phosNonlin.cxx
- PWGEM/Tasks/phosPi0.cxx
- caloClusterProducer: fix for noCPV events
- phosPi0 rewritten to have same code for data and MC
- bug fixes
> - class phosNonlin for nonlinearity calculation

- PWGLF/TableProducer/cascqaanalysis.cxx
Following event selections are added to the task:
1. kIsGoodZvtxFT0vsPV
2. kNoSameBunchPileup
3. kIsVertexITSTPC
> PWG-LF: Event Sel. Update in Casc. Table Producer (Xi/Omega analysis)

- PWGEM/Tasks/phosNonlin.cxx
- PWGEM/Tasks/phosPi0.cxx
> mass calculation fixed

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
> PWGHF: Fix the BeautyToLightDecayMu histograms in HFL muon source task

- PWGDQ/Tasks/tableReader.cxx
Minor fix in filling dilepton histograms
> [PWGDQ] Minor fix in filling dilepton histograms

- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
> additional event selection cuts

- PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
- PWGLF/Tasks/Nuspex/QAHistTask.cxx
Added a TPCsignal histogram for checking MC truth in both tasks.
> Update for QAHistTask & NucleiHistTask

- Common/TableProducer/centralityTable.cxx
@nepeivodaRS many thanks for catching this!!
> Common: Fix bug in inel > 0 embedding

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/lambdakzerobuilder.cxx
Related to https://its.cern.ch/jira/browse/O2-4684
> PWGLF: implementation of Ivanov downscaling (optional)

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: fix Partition filter does not match declared table type
> PWGEM/Dilepton: fix Partition filter does not match declared table type

- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/PhotonMeson: change track::v001::detectorMap
> PWGEM/PhotonMeson: change track::v001::detectorMap

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
PWGEM/PhotonMeson: add evsel bits
> PWGEM/PhotonMeson: add evsel bits

- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- PWGEM/PhotonMeson/Tasks/phosQC.cxx
PWGEM/PhotonMeson: remove 2 columns from event table
PWGEM/PhotonMeson: suppress compilation warning
> PWGEM/PhotonMeson: remove 2 columns from event table

- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/PhotonMeson: add process to skim ee/mumu with TTCA
> PWGEM/PhotonMeson: add process to skim ee/mumu with TTCA

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: add down scaling factor for ML DDA
> PWGEM/Dilepton: add down scaling factor for ML DDA

- Common/TableProducer/qVectorsTable.cxx
> [event plane] fix memory lick

- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: add RZ cut to reconstructed-true photon in MC
> PWGEM/PhotonMeson: add RZ cut to reconstructed-true photon in MC

- PWGLF/Tasks/Resonances/deltaanalysis.cxx
> Add single track histograms for delta analysis

- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
> improved pid selection and mc

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I've joined the track table with the track-selection table to apply a quality selection on the associated particles.
Best regards,
Samuele
> PWGHF: Ds-h correlation, added track selection for associated particles

- PWGLF/TableProducer/Nuspex/LFTreeCreatorNuclei.cxx
- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
- Add last EventSelection to both Table Producer and Analysis Task
- Remove "doCalibration" mode
> [PWGLF] LightNucleiTask - Add last EventSelection to Analysis Task

- PWGLF/Tasks/Resonances/deltaanalysis.cxx
> Add histograms for generated daughters

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
improved PID selection and track selection
> improved PID selection

- DPG/Tasks/AOTTrack/qaMatchEff.cxx
Set a new configurable `b_useAnalysisTrackSelections`  to mark if use analysis track cuts.
When set to true, TrackSelection `cutObject` will be replaced by `getGlobalTrackSelectionRun3ITSMatch` calling from `TrackSelectionDefaults`
> Set a new flag to mark if use analysis track cuts

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: fix MC indexing for daughters
> PWGEM/PhotonMeson: fix MC indexing for daughters

- PWGLF/Tasks/Resonances/k892analysis.cxx
- Simplify the track cuts for a better systematic check
- Increase the histogram size from float to double type.
> [PWGLF] Simplify track selection options

- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
PWGEM/PhotonMeson: fix RZ cut in MC
> PWGEM/PhotonMeson: fix RZ cut in MC

- PWGCF/FemtoDream/Core/femtoDreamDetaDphiStar.h
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackV0.cxx
A possible bug was found in CPR code for FemtoDream. The fix is now implemented, but also old version of the code is included. This is needed to test the effect o nthe hyperloop using exaclty the same train. Later on, once this is understood, only the correct version of the code will be kept.
> Study of CPR - possible bug found

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
PWGEM/PhotonMeson: update event counter histogram
> PWGEM/PhotonMeson: update event counter histogram

- PWGHF/Tasks/taskMcValidation.cxx
@cterrevo @ZFederica @zhangbiao-phy @DelloStritto @stefanopolitano FYI
> PWGHF: revamp MC validation task

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson: add TPConly eID for ee
> PWGEM/PhotonMeson: add TPConly eID for ee

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzMuMu.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
PWGEM/PhotonMeson: remove unnecessary min pin cut for eID
PWGEM/PhotonMeson: improve mixing event
> PWGEM/PhotonMeson: remove unnecessary min pin cut for eID

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
fix track identification to improve signal
> fix track identification

- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
PWGEM/PhotonMeson: quick fix to mixing event
> PWGEM/PhotonMeson: quick fix to mixing event

- PWGCF/JCorran/Core/JHistManager.cxx
- PWGCF/JCorran/Tasks/jflucAnalysisTask.cxx
> PWGCF: JCorran: Fix track filters

- PWGJE/Tasks/jetfragmentation.cxx
* Added hists for V0 pt resolution in jets
* Need to take absolute value of DCA posneg in V0 cut variation hist
> [PWGJE] Jet Fragmentation: Bug fix and extra histograms

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I've found an error in the histograms names, now it is fixed
Cheers,
Samuele
> PWGHF: Ds-h, Fixing the histograms names in MC process

- PWGHF/HFL/Tasks/taskSingleMuonReader.cxx
Add the derived table singleMuon for TTree related analysis
> PWGHF: Add derived table in HFL single muon task

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
@mfaggin could you please have a look? Thanks!
> PWGHF: add D0 inv mass in sparse and possibility to apply rot bkg for D*

- PWGLF/Tasks/Resonances/kstarqa.cxx
Added MC in the code for the debugging of lower efficiency in pp datasets.
> added MC in the code

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/createEMEvent.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- Tutorials/PWGEM/pcm/pcmtutorial.cxx
PWGEM/PhotonMeson: update for q vector and reorganize to include headers
> PWGEM/PhotonMeson: update for q vector and reorganize to include headers

- PWGLF/DataModel/LFStrangenessTables.h
@ddobrigk following up our discussion from a while ago to make the v0 standard bit explicit.
> LF: make standard v0 explicit

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
Fixing "_M_range_check" in tmpVec
> PWGCF : FemtoUniverse -- Fixing _M_range_check

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've correct the cuts in the producer and the task for D0/D0bar analysis.
> PWGCF:FemtoUniverse - correction of the cuts

- PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
- Add cut on TempFitVar (for tracks DCAxy) in the pair track track task
- Add cut on TempFitVar (for tracks DCAxy) in the pair track track v0 (leave v0 out for now)
- Clean up configurables in pair track v0 task
> PWGCF: FemtoDream update

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/PhotonMeson: re-organize ee cuts
PWGEM/PhotonMeson: recalculate cov. mat. for ee
> PWGEM/PhotonMeson: re-organize ee cuts

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerDalitzMuMu.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/PhotonMeson: reduce data size
> PWGEM/PhotonMeson: reduce data size

- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/PhotonMeson: change default values for configurables
> PWGEM/PhotonMeson: change default values for configurables

- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
PWGEM/PhotonMeson: add HF hadrons in MC
> PWGEM/PhotonMeson: add HF hadrons in MC

- PWGMM/Mult/Tasks/dndeta.cxx
Granular event selection to be able to exclude TF border selection in MC.
> PWGMM: Mult: granular event selection

- PWGJE/Tasks/jettaggerhfQA.cxx
AxisSpec data type are moved in "init()" function to able to adjust in hyperloop job.
> PWGJE : AxisSpec modification

- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
> fix mc part

- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
PWGEM/PhotonMeson: quick fix to HF->ee in MC
> PWGEM/PhotonMeson: quick fix to HF->ee in MC

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/dqEfficiency.cxx
Improve histograms for MC studies
> [PWGDQ] Improve histograms for MC studies

- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
PWGEM/PhotonMeson: add process EE MC only
> PWGEM/PhotonMeson: add process EE MC only

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
PWGEM/PhotonMeson: fix to scalar product
> PWGEM/PhotonMeson: fix to scalar product

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
PWGEM/PhotonMeson: update histogram bins
> PWGEM/PhotonMeson: update histogram bins

- PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
Fix of bug discovered when trying to run on hyperloop.
> PWGUD: buxfix for errors from hyperloop

- PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
- PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyTask.cxx
For now the efficiency task is using AOD file as an input file, but I'm planning on switching it to the FemtoAOD.
> PWGCF: FemtoUniverse -- First step for working efficiency task for FemtoUniverse (work in progress)

- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
- PWGLF/Tasks/Nuspex/nuclei_in_jets.cxx
- PWGLF/Tasks/Resonances/kstarqa.cxx
- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
> PWGLF: Fix compilation warnings

- PWGDQ/TableProducer/tableMaker.cxx
Adding extra process function for associated muons with centrality
> [PWGDQ] Adding extra process function for associated muons with centrality

- PWGEM/Tasks/phosElId.cxx
> PWGEM: Fix compilation warnings

- PWGEM/Dilepton/Tasks/MCtemplates.cxx
Add an additional process function to fill Track histograms filtered by events
> PWGEM MCtemplate add process function to fill track Histograms correctly

- EventFiltering/cefpTask.cxx
> Fix bit position when having more than 64 triggers

- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
@glromane @sofiatomassini @njacazio @neelimaagrawal
> PWGCF: add gen level information for efficiency computation

- PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
Add pT dependent DCA cut also debug track task and collision masker.
> PWGCF: Add pt dependent to FemtoDream 

- PWGLF/Tasks/Resonances/lambda1520analysis.cxx
1. Added event selection cuts
2. Updated MC part
> PWGLF: Update lambda1520analysis task

- PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
Fixed MC tracking efficiency calculation.
> Update + Fix: NucleiHistTask.cxx

- PWGLF/Tasks/Resonances/k892analysis.cxx
- PWGLF/Tasks/Resonances/phianalysis.cxx
Phi - Fix combination method, add track cut options, add TOF bypass option
K892 - Add TOF bypass option
> PWGLF: Phi and K982 task add TOF bypass option

- PWGUD/Tasks/CMakeLists.txt
- PWGUD/Tasks/SGTrackSelector.h
- PWGUD/Tasks/sgD0Analyzer.cxx
- PWGUD/Tasks/sgFITAnalyzer.cxx
- PWGUD/Tasks/sgFourPiAnalyzer.cxx
- PWGUD/Tasks/sgSpectraAnalyzer.cxx
- PWGUD/Tasks/sgTwoPiAnalyzer.cxx
> [PWGUD] PV Contributor check added to FourPi Analyzer

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
This PR contains 2 commits:
PWGEM/PhotonMeson: quick fix for handling string
PWGEM/PhotonMeson: add flexible kinetic values for V0s
> PWGEM/PhotonMeson: quick fix for handling string

- PWGUD/Tasks/CMakeLists.txt
Addition of missing workflows for PWGUD analysis in CMakeLists.txt.
> PWGUD: adding missing workflows in CMakeLists.txt

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
- add efficiency after event reconstruction
- simplify, streamline configuration
> [DPG] Update QaEfficiency

- PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Add as variable the QA histograms to be filled.
Add QA histograms for dielectrons
Add the B to be able to properly calculate PhiV
> Add more flexibility for QA

- PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
> Add histo QA all dileptons

- EventFiltering/PWGUD/diffractionFilter.cxx
- EventFiltering/filterTables.h
1st bit for DG events with less than 4 PV tracks
2nd bit for DG events with more than 3 PV tracks
> added 2nd filter bit to diffraction filter

- PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
Fixed pT for reconstructed He3 & He4
> Fix NucleiHistTask.cxx

- PWGUD/Core/DGCutparHolder.h
- PWGUD/Core/DGSelector.h
- PWGUD/Core/UDHelpers.h
- PWGUD/TableProducer/DGCandProducer.cxx
goodCollision fixed
new evsel selections added
slight refactor of dgproducer wrt latest changes
> [PWGUD] Fix of logic in goodCollision function + refactor

- PWGDQ/Core/CutsLibrary.cxx
Keeping the default cases the same
> Add different track cuts for our scenarios

- PWGDQ/Core/MCSignalLibrary.cxx
additional MC Signals for dielectrons PWGEM
> [PWGEM] additional MC signals, differentiate D mesons, Lambda c, beuaty decay

- Common/Tasks/qVectorsCorrection.cxx
- PWGMM/Lumi/Tasks/lumiStability.cxx
> [Common] add event selection

- PWGLF/Tasks/Strangeness/CMakeLists.txt
- PWGLF/Tasks/Strangeness/phik0sanalysis.cxx
Adding phi-k0s rapidity correlation analysis task
> Adding phi-k0s correlation analysis task

- PWGLF/Tasks/Resonances/kstarqa.cxx
Polarization in kstar and phi resonances.
> added code for the polarization studies in the Kstar and Phi resonances

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/TableProducer/Resonances/LFResonanceInitializer.cxx
Add two more flags: `kTrig10`, `kSel10`
> PWGLF: Add two more flags in resonance MC event histogram

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
PWGEM/PhotonMeson: add flexible kinetic values for V0s
PWGEM/PhotonMeson: add 2 dynamic columns
PWGEM/PhotonMeson: add flexible pcm-qc
> PWGEM/PhotonMeson: add flexible pcm-qc

- PWGCF/Tasks/correlations.cxx
This is a PR with the modifications related to efficiency calculation. This also includes a few fixes related to the multiplicity axis in MC.
> Modifications and fixes related to efficiency and MC closure

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I've added some checks regarding the Ds decay channel both in the processMcRec and in the process for evaluating the candidate efficiency. Let me know for any comments.
Best regards,
Samuele
> PWGHF: Ds - h, Adding Ds decay channel control

- PWGDQ/Core/CutsLibrary.cxx
To be able to run only with tracking cut in MC
> Tracking cuts of PbPb analysis

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
In this commit we change the shape of double-track cut from rectangular to elliptical. Could you please approve it. Thank you.
> elliptical shape for deta & dphi cut

- PWGHF/Core/SelectorCuts.h
- PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
- PWGHF/TableProducer/candidateSelectorLc.cxx
- PWGHF/TableProducer/trackIndexSkimCreator.cxx
- PWGHF/Utils/utilsAnalysis.h
- Utility function to cut on dca_xy extended to cut also on dca_z
- Utility function to cut on TPC track properties implemented
- Utility function to cut on ITS track properties implemented
> PWGHF: implement track selection for HF tasks

- DPG/Tasks/AOTEvent/eventSelectionQa.cxx
QA: adding a block for occupancy in time window study
> update eventSelectionQa.cxx: adding a block for occupancy in time window study

- Common/DataModel/Qvectors.h
- Common/TableProducer/qVectorsTable.cxx
- PWGCF/Tasks/correlations.cxx
TH3F input only from CCDB for qvector calibration
> [Common] TH3F input only from CCDB for qvector calibration

- DPG/Tasks/AOTTrack/PID/qaPIDTPCSignal.cxx
> [DPG] update signal QC

- PWGMM/Lumi/Tasks/lumiStability.cxx
A little change due to issue in hyperloop
> PWGMM Lumi

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
1) rework on heavy-ion-mult task
2) Add new event selection criteria
> rework on PWGMM/Mult/Tasks/heavy-ion-mult.cxx

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I've added/modified some processes in order to perform the MC Closure test part at the analysis level. Let me know for any comment.
Cheers,
Samuele
> PWGHF: Ds-h correlation, added parts for MC Closure Test

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGEM/Dilepton/Utils/MomentumSmearer.h
Fix momentumsmearer to be able to run efficiency task without smearing file + add 2D histo mee,ptee with more bins but without DCA histos and phiv histo up to larger mass
> Fix MomentumSmearer + more histos

- PWGLF/Tasks/Nuspex/hadronnucleicorrelation.cxx
Ciao @ercolessi, please have a look into the PR. Thanks, Arvind.
>  [PWG-LF] Histogram added for thr rec and gen ditribution in dleta eta and phi

- PWGLF/Utils/collisionCuts.h
Add QA plot for the ITSonly vertex check.
> PWGLF: Modify the variable name and add QA plot

- PWGCF/FemtoDream/Core/femtoDreamDetaDphiStar.h
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackV0.cxx
dphi deta plots as a function of eta and phi, at PV, cut possible at PV, diff deta dphi cut for pp and pL pairs in ppL task
> CPR updates for preliminaries

- PWGLF/Tasks/Resonances/phianalysisTHnSparse.cxx
- PWGLF/Utils/rsnOutput.h
- eta cut
- preparation for systematics
- Function for filling pointPair
- ...
> [PWGLF] Improvements in phianalysisTHnSparse wokflow

- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
Just a minor fix on the histograms names.
Cheers,
Samuele
> PWGHF: Ds-h correlation, Fixed histograms names

- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
PWGEM/PhotonMeson: fix for event mixing in ee
> PWGEM/PhotonMeson: fix for event mixing in ee

- ALICE3/Tasks/alice3-qa-singleparticle.cxx
> A3: update singleqa

- PWGLF/TableProducer/Strangeness/cascqaanalysis.cxx
- PWGLF/Tasks/Nuspex/spectraTOF.cxx
- PWGLF/Tasks/Strangeness/cascpostprocessing.cxx
1. multNTracksPVeta1 -> isInelGt0()/isInelGt1()
2. sel8 -> separate selections: kIsTriggerTVX, kNoTimeFrameBorder, kNoITSROFrameBorder
3. hFT0MsignalPVContr histogram for QC
4. QC histograms in postprocessing
> PWG-LF: event selection update in cascade analysis
