DataModel/include/AnalysisDataModel/HFSecondaryVertex.h
Tasks/PWGHF/HFCandidateCreatorXicc.cxx
Tasks/PWGHF/taskXicc.cxx

Resolve the issue related to get an index of Xic candidates.
- Replace the `trackxic.getProngID(0).getRaw()` to `trackxic.globalIndex()` to get a proper index of Xic candidates.
- Add `o2::soa::Index<>` in HfCandProng3Base 
- Remove unsed histogram

PWGHF: Resolve the issue and remove unused histogram in Ξcc task

---

Tasks/PWGHF/HFTrackIndexSkimsCreator.cxx

String lookups are done per candidate, making it extremely slow for
no reason. Caching the position of the indices should give a rather
significant boost to loosely cut setups.

PWGHF: Cache lookups in Array2D

---

Tasks/PWGHF/HFTrackIndexSkimsCreator.cxx

- apply to 2 prongs same improvements implemented for 3 prongs in https://github.com/AliceO2Group/O2Physics/pull/47 and https://github.com/AliceO2Group/O2Physics/pull/39
- use partitions to loop only over positive/negative tracks
It was tested and it gives exactly the same result as the previous version (but it should be faster)

PWGHF: Speedup loops and preselections

---

DataModel/include/AnalysisDataModel/HFSecondaryVertex.h
Tasks/PWGHF/HFCandidateCreator3Prong.cxx
Tasks/PWGHF/HFTreeCreatorLcToPKPi.cxx

The prong ordering information is needed to consider only the right signal candidate in the ML training when the PID is used.
@ginnocen @vkucera

PWGHF: Adding the information about the prong ordering (Lc -> p K pi or Lc -> pi K p)

---

PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx

Adding track partitions in skimming by https://github.com/AliceO2Group/O2Physics/pull/51 does not work.

PWGHF: Revert use of partitions in skimming

---

PWGCF/Tasks/dptdptcorrelations-simchl.cxx

For the Run 3 productions still needs the TrackExtensionTask being patched

The gen <=> reco mapping tests task

---

PWGHF/TableProducer/HFCandidateCreatorX.cxx

Adding a threshold on the pion pt in the X candidate creator

PWGHF:  setting minimum pion pT in X candidate creator

---

PWGCF/Tasks/dptdptcorrelations-simchl.cxx

The full workflow is now built via configuration
Tested
- pp
- pp MC
- pp MC Run3
- PbPb
- PbPb MC
Also converted the info logs to debug logs but easily
rolled back if needed

Getting rid of `customize`

---

ALICE3/TableProducer/alice3-pidTOF.cxx
ALICE3/Tools/handleParamTOFResoALICE3.cxx
Common/Core/PID/PIDTOF.h
Common/Core/PID/PIDTPC.h
Common/TableProducer/PID/pidBayes.cxx
Common/TableProducer/PID/pidTOF.cxx
Common/TableProducer/PID/pidTOFFull.cxx
Common/TableProducer/PID/pidTOFbeta.cxx
Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx
Common/Tools/handleParamTOFReso.cxx
Common/Tools/handleParamTPCBetheBloch.cxx

- Move from http://ccdb-test.cern.ch:8080 to http://alice-ccdb.cern.ch
- Remove dependence of the collision in PID methods
- Getting collision from track

Change default ccdb path for PID

---

PWGHF/Tasks/taskLc.cxx

Extended the pT range of distributions of generated and reconstructed Lc candidates in the LcMC task, to match the pT range in the 2D histogram of inv. mass vs. pT.

PWGHF: update in the pT ranges in hf-task-lc-mc

---

PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx

@ginnocen 
Add selection on primary vertex:
* x, y, z
* number of contributors
* chi^2 (not divided by n. d. f.)

PWGHF: Add primary-vertex selection in skimming

---

PWGHF/TableProducer/CMakeLists.txt
PWGHF/Tasks/CMakeLists.txt
Tutorials/Skimming/CMakeLists.txt
cmake/O2PhysicsAddExecutable.cmake
cmake/O2PhysicsNameTarget.cmake

This changes all executable names in the PWG folders such that they contain the pwg name. E.g.
o2-analysis-correlations --> o2-analysis-cf-correlations
Given that hf had done this manually, it is removed from their cmake files. So no change happens for the hf tasks.

CMake: Adding PWG name to executable name

---

EventFiltering/PWGHF/HFFilter.cxx

First draft for the HF-Femto trigger

HF Femto Trigger

---

PWGCF/Tasks/dptdptcorrelations-simchl.cxx

Also incorporated the active detectors output both before and after
selection cuts
Strange, with the same selection cuts we get more tracks (one thousand (5%)
with the latest nightly MBTB production) if we go through the tracks table
based on a concrete collision than if we go through the whole tracks table
checking the selection of each track associated collision

Selection cuts into the reco <-> gen mapping check task

---

PWGHF/DataModel/HFCandidateSelectionTables.h
PWGHF/DataModel/HFSecondaryVertex.h
PWGHF/TableProducer/HFCandidateCreatorX.cxx
PWGHF/TableProducer/HFTreeCreatorXToJpsiPiPi.cxx
PWGHF/TableProducer/HFXToJpsiPiPiCandidateSelector.cxx
PWGHF/Tasks/taskX.cxx

PWGHF: add dimuon channel to X task

---

PWGMM/Tasks/dndeta.h

Temporary workaround to be able to run on hyperloop.

PWGMM: set switches in pseudorapidity task to true by default

---

CODEOWNERS

Hopefully this means that only one person from the team has to approve PRs to `PWGHF`.

Try using team as code owner

---

CODEOWNERS

Reverts AliceO2Group/O2Physics#132 as it didnt work.

Revert "Try using team as code owner"

---

PWGHF/Tasks/taskLc.cxx

Added (ALICE3) centrality as another dimension of the inv. mass histogram to be able to select offline for the desired centrality range.

PWGHF: Add (ALICE3) centrality selection in the Λc task

---

EventFiltering/CMakeLists.txt
EventFiltering/PWGCF/CFFilter.cxx
EventFiltering/filterTables.h
PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/FemtoDreamMath.h
PWGCF/FemtoDream/FemtoDreamPairCleaner.h
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

Dear experts,
this is the first version of 3-body trigger. As you will see, it is a bit slow, because there are sliceBy() and Partitions used for every collision. The current idea is to run femto skimming task and pipe the output to trigger. The CFFilter task currently takes as input aod::FullCollision const& col as well as the full FemtoDreamCollisions and FemtoDreamParticles tables. Then inside the code, I check, if the current collision is present in FemtoDreamCollision table -> if it is not, I set the trigger to false. Otherwise, the trigger is applied by forming triplets out of the particle candidates but for this, I have to use only the particles which are coming from specific collision thus inside the process task I apply the partitions. Please, let me know if there is a more …

ThreeBody Trigger

---

PWGHF/Tasks/CMakeLists.txt
PWGHF/Tasks/HFCorrelatorD0D0barBarrelFullPID.cxx

Linked to temporary codes committed via https://github.com/AliceO2Group/O2Physics/pull/141

PWGHF: added temporary DDbar correlator to exploit full barrel PID selection

---

.github/workflows/codeowner-self-approval.yml

This action runs when auto-merge is enabled, and approves the PR using the alibuild user if the submitter of the PR is the code owner of all code in the PR.
I've tested this using <https://github.com/TimoWilken/pr-review-action-test> (it correctly approved when I edited a file owned by me and alibuild, and correctly didn't approve when I edited a file owned only by alibuild).
Cc: @jgrosseo

Allow code owners to self-approve pull requests

---

.github/workflows/codeowner-self-approval.yml

This prevents someone who is not the code owner, but has "Write" permissions on the repository from enabling auto-merge and thereby requesting auto-approval.

Only auto-approve PRs if requested by PR author

---

PWGHF/DataModel/HFCandidateSelectionTables.h
PWGHF/TableProducer/HFDplusToPiKPiCandidateSelector.cxx
PWGHF/Tasks/taskDPlus.cxx

PWGHF: Separate prompt/nonprompt D+ and add different efficiency steps

---

Common/DataModel/StrangenessTables.h
PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx
PWGLF/TableProducer/lambdakzerofinder.cxx

see https://alice.its.cern.ch/jira/browse/O2-2635

Fix cascade issues in analysis 

---

PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/Tasks/taskLc.cxx

* Updated 3-prong creator
* Updated Lc task
@vkucera Note how 3-prong creator was handled: since MC matching task needs the extended table, corresponding process function can be put directly into the extension task and it will have access to the extended table without subscribing. 
Note that this requires https://github.com/AliceO2Group/AliceO2/pull/7439 to work properly.

PWGHF: Use process switches instead of workflow options for Lc analysis chain

---

PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/Tasks/taskD0.cxx

With a similar implementation of that used for the Lc in PR #230

PWGHF: Use process switches instead of workflow options for 2prong creator and taskD0

---

PWGCF/FemtoDream/FemtoDreamCollisionSelection.h
PWGCF/FemtoDream/FemtoDreamContainer.h
PWGCF/FemtoDream/FemtoDreamEventHisto.h
PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/femtoDreamHashTask.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

- Modified binning of histograms for single particles, events and SE/ME distributions for quicker benchmarking with Run2 results 
- Removal of some obsolete variables in producer
- add class for Event QA (for QA at level of the analysis task)
- Removal of entries in Labeled array for track cuts in TT task and removal in the partition for selecting tracks (now partition relies only on bit cut)
- bit cut for protons set to default (pT>0.5, η = 0.8)

Binning histograms, multiplicity, remove obsoletes, add QA event TT task

---

Common/TableProducer/trackextension.cxx

Trackextension is the only part of the code that uses https://alice-ccdb.cern.ch. A simple
move to `http:` should solve the problem with certificates discussed on mattermost. 
This would also follow
the approach in many other places of the code (see `git grep alice-ccdb`).
Maybe the CCDB location should be a global property for all tasks anyway.

Trackextension: use http://alice-ccdb.cern.ch

---

EventFiltering/PWGCF/CFFilter.cxx
PWGCF/FemtoDream/FemtoDreamDetaDphiStar.h
PWGCF/FemtoDream/FemtoDreamPairCleaner.h

1. Close pair rejection included in trigger,
2. ppp trigger added,
3. obtaining V0 daughters from table had a bug, fixed in both FemtoDreamDetaDphiStar and FemtoDreamPairCleaner cases.

Included close pair rejection in trigger, ppp trigger, fix in V0 checks

---

EventFiltering/CMakeLists.txt
EventFiltering/PWGLF/strangenessFilter.cxx
EventFiltering/filterTables.h

This code is co-authored by @ChiaraDeMartin95
Dear experts,
this is the first version of the LF strangeness trigger task. 
As you will see we save some QA histos which are crucial at this stage to make sure our selections are compatible with Run3 data. In the future if necessary we can decide to remove them.
Please let us know if you have comments or suggestions.

LF (strangeness) triggers implementation

---

PWGJE/Tasks/CMakeLists.txt
PWGJE/Tasks/emccellmonitor.cxx

Cell monitor task used to monitor cell-related observables (amplitude,
time, occupancy) at AOD level. Ported from AliEmcalCellMonitorTask
in AliPhysics.
Pending features to be added in the next steps:
- Trigger selection
- Retrieval of bad channel map from CCDB
- Separation of cells in cluster / isolated

[EMCAL-733] Port cell monitor task from EMCAL analysis framework

---

PWGCF/DataModel/DptDptFiltered.h
PWGCF/TableProducer/CMakeLists.txt
PWGCF/TableProducer/dptdptfilter.cxx
PWGCF/TableProducer/dptdptfilter.h
PWGCF/Tasks/CMakeLists.txt
PWGCF/Tasks/dptdptcorrelations.cxx
PWGCF/Tasks/dptdptfilterqa.cxx
PWGCF/Tasks/match-reco-gen.cxx

It feeds
- match-reco-gen independent separated from the filter-qa task
- dptdptcorrelations independent
- dptdpt-filter-qa independent separated from the match-reco-gen task

Filter task separated in its own task dptdpt-filter

---

PWGJE/Tasks/emccellmonitor.cxx

Cell count hist was incorrectly accessed as
cellCountSM/cellAmpSM due to copy/paste
error when creating hard coded supermodule
histogram names.

[EMCAL-733] Fix copy/paste error in SM-based histogram names

---

EventFiltering/filterTables.h
PWGDQ/Core/CutsLibrary.h
PWGDQ/Tasks/filterPP.cxx

In filteringTables.h:
- Addition of the DQ trigger table containing :  Single Electron, Single Low Pt Muon, Single High Pt Muon, DiElectron, Dimuon triggers
In filterPP.cxx :
- Addition of the muon triggers in the filtering task
- Produces the DQTable as an output
In CutsLibrary.h :
- Addition of a high and low pT cuts for muon tracks

Addition of the Dilepton & Quarkonia triggers in the Central Event Filtering

---

Common/Core/aodMerger.cxx

avoids crashes if the inputs.txt list for some reason contains files that dont exist or are not reachable

aod-merger: add option to skip non-existing files

---

Common/DataModel/Centrality.h
Common/TableProducer/centralityTable.cxx
Common/Tasks/centralityQa.cxx

Also incorporated SPD Clusters for pp data and CL0 and CL1 for PbPb data

Centrality estimation using SPD tracklets

---

EventFiltering/PWGHF/HFFilter.cxx
EventFiltering/filterTables.h

- add track pT in tables for ML training
- add trigger for events with multiple charm-hadron candidates

[Event filtering]: implement few improvements

---

EventFiltering/PWGHF/HFFilter.cxx
PWGHF/DataModel/HFSecondaryVertex.h
PWGHF/TableProducer/HFD0CandidateSelector.cxx
PWGHF/TableProducer/HFD0CandidateSelectorALICE3Barrel.cxx
PWGHF/TableProducer/HFD0CandidateSelectorALICE3Forward.cxx
PWGHF/TableProducer/HFD0CandidateSelectorparametrizedPID.cxx
PWGHF/TableProducer/HFJpsiCandidateSelector.cxx
PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx
PWGHF/Tasks/HFSelOptimisation.cxx

* Remove DCA columns from HFSelTrack
* Add `TracksExtended` in corresponding track joins for HF tasks
This moves track DCA calculation to central  `track-extension`/`alice3-track-extension` tasks.

PWGHF: remove DCA from HFSelTrack table and use TracksExtended instead

---

Common/DataModel/EventSelection.h
Common/TableProducer/eventSelection.cxx

* custom deltaBC for collision-FT0 matching window, set to 300 bcs by default. Used as a workaround to increase FT0 matching efficiency for pilot beams
* foundFV0 index added in bcsel and evsel tables
* bux fixes in collision-FT0 matching algorithm

Custom deltaBC, foundFV0 and bug fixes

---

Common/DataModel/Multiplicity.h
Common/TableProducer/multiplicityTable.cxx

Add TPC multiplicity (estimated by # of tracks with NClsFindable >0) to mult table for run2 processing
Processing with the run3 option appears to not work (same size() method on the partition gives a single unphysical value to all rows in the dataframe), to be revisited (set to -1 in case of run3 processing for now)

add TPC multiplicity to multiplicity table

---

Common/DataModel/TrackPropagation.h
Common/TableProducer/CMakeLists.txt
Common/TableProducer/trackPropagation.cxx
Tutorials/CMakeLists.txt
Tutorials/src/propagatedTracks.cxx

adding propagated tracks tables

---

Common/TableProducer/multiplicityTable.cxx

put as draft for @victor-gonzalez to comment
With this patch the processRun3 function is changed to take an iterator via `soa::Join<Collisions, EvSels>::iterator`, instead of the `for (auto& collision : collisions)`. This way the same TPC partition works in both the run2 and run3 modes, without the extra overhead that would be introduced by an internal partition (as mentioned at https://github.com/AliceO2Group/O2Physics/pull/349#issuecomment-979825010)
Does anything speak against handling the iterator in this way for run3?

Add TPC mult for run3 processing

---

Common/Core/TableHelper.h
Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx

- Use common utilities
- Add track cuts in QA
- Add event cuts in QA
- Extend available QA plots

Update TPC QA

---

PWGMM/Tasks/CMakeLists.txt
PWGMM/Tasks/lumi.cxx

[PWGMM] init lumi PR

---

Common/Core/PID/PIDResponse.h
Common/Core/PID/PIDTOF.h
Common/Core/PID/TOFReso.h
Common/TableProducer/PID/CMakeLists.txt
Common/TableProducer/PID/pidBayes.cxx
Common/TableProducer/PID/pidTOF.cxx
Common/TableProducer/PID/pidTOFBase.h
Common/TableProducer/PID/pidTOFFull.cxx
Common/TableProducer/PID/pidTOFbeta.cxx

- Add Run3 PID response using TOF event time
- Add utility to compute TOF mass
- Extend documentation
- Use common utils for TOF PID task
- Extend beta functions
Extend Efficiency task
- Add track cuts to efficiency
- Improve CPU efficiency
Extend track selection task
- Add track quality histograms
Fix warning in pidBayes

Add first EventTime maker task

---

Common/DataModel/EventSelection.h
Common/TableProducer/eventSelection.cxx
Common/TableProducer/ft0CorrectedTable.cxx
Common/TableProducer/multiplicityTable.cxx
Common/Tasks/eventSelectionQa.cxx
Common/Tasks/ft0Qa.cxx
PWGMM/Tasks/dndeta.h

* Added foundBC index to EvSel table
* Declared foundFT0, foundFV0 and foundBC as index columns
* Changes in user tasks:
- Check for foundFT0==-1 via collision.has_foundFT0()
- Access data directly via collision.foundFT0() instead of iterator_at(foundFT0).

foundFT0, foundFV0 and foundBC as index columns

---

.github/workflows/codeowner-self-approval.yml

1. Parse the CODEOWNERS file properly -- `git check-ignore` uses slightly different syntax and precedence rules, so we can't use that.
2. if another codeowner has already approved the PR, then consider that OK for the relevant CODEOWNER lines.
This means that if e.g. a PR authored by A changes files Fa and Fb, and A owns Fa, and B owns Fb, then auto-approval is still possible as long as B approves the PR.
Not properly tested yet, though I should be able to do that on Monday.

Fix PR auto-approval script

---

.github/workflows/codeowner-self-approval.yml

When a PR is approved by someone, but auto-merge was not requested, then we
don't want to auto-approve.

Don't run self-approval on a simple approval

---

Common/TableProducer/trackextension.cxx

Without this we get a segfault on exit (probably due to a  double delete) on the grid. Moreover, when compiling with `-fsanitize=address` it complains about:
```
[47474:track-extension]: ==47474==ERROR: AddressSanitizer: SEGV on unknown address 0x7f893300006d (pc 0x00000041ef1c bp 0x60b000236000 sp 0x7fffaf0c9f48 T0)
[47474:track-extension]: ==47474==The signal is caused by a READ memory access.
[47474:track-extension]:     #0 0x41ef1c in std::_Sp_counted_ptr<TGeoManager*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /home/alitrain/eulisse/sw2/ubuntu1804_x86-64/GCC-Toolchain/v10.2.0-alice2-1/include/c++/10.2.0/bits/shared_ptr_base.h:380
```
With this change in, address sanitizer does not complain.

Workaround crash in track-extension

---

Common/TableProducer/trackextension.cxx

This reverts commit cfc2e3da30470eaaea84955c162e3e7d14a0821d.

Revert "Workaround crash in track-extension (#402)"

---

Tutorials/src/eventMixing.cxx

2 simple examples with declaration in struct and inside `process()`.
Note: This does not work yet with Filtered and Partitioned tables, work ongoing.

Event mixing: Examples for new interface

---

Tutorials/src/mcHistograms.cxx

* explcit check introduced in O2 PR #7866 makes certain analyses fail in
case an invalid index is found for an MCParticle associated to a track
* before, memory was randomly accessed in that case
* to be applied in affected analyses

Skip tracks w/o MC particle

---

Common/Core/RecoDecay.h
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFD0CandidateSelectorALICE3Barrel.cxx
PWGHF/TableProducer/HFD0CandidateSelectorparametrizedPID.cxx
PWGHF/TableProducer/HFLcCandidateSelectorparametrizedPID.cxx
PWGHF/Tasks/HFMCValidation.cxx

* explcit check introduced in O2 PR [#7866](https://github.com/AliceO2Group/AliceO2/pull/7866) makes certain analyses fail in
case an invalid index is found for an MCParticle associated to a track

[PWGHF] Add protection for tracks without associated MC particle

---

PWGCF/TableProducer/dptdptfilter.cxx
PWGCF/TableProducer/dptdptfilter.h

Also fixing few warnings on not used parameters

Tracking the collision mutltiplicity

---

dependencies/FindKFParticle.cmake
dependencies/O2PhysicsDependencies.cmake

This commit adds the necessary CMake find_package commands to find the KFParticle package in O2Physics so that it can be used in analysis tasks.
Currently KFParticle is defined in alidist as a dependency of O2, so is already built as part of the software chain, but is not explicitly included for O2Physics -- not sure if this means we would also need a corresponding change in alidist (see previous discussion in https://github.com/AliceO2Group/AliceO2/pull/6992 where it was suggested to move the dependency from O2 to O2Physics instead)

Add KFParticle to dependencies

---

EventFiltering/cefpTask.cxx
EventFiltering/filterTables.h

I prepared this PR to update and fix the following issue:
- add the `FILTER_CONFIGURABLE()` for `DQ, HF, CF, Jet, Strangeness, Mult` filters which were missing
- fix the `AvailableFilters` for `DQ, HF, CF`. The previous names were not matching the related filterTable names.
- fix the `FilteringTaskNames` for `CF` which was not matching the implemented workflow (i.e. `o2-analysis-cf-threebodyfemto-filter`)
Thanks and regards,
Stefano

CEFP: Fixing to cefpTask and filterTables

---

Common/Core/PID/BetheBloch.h

Decouple O2Physics from the (large) tpc::Detector header.
Use novel BetheBloch header instead.

Include new BetheBloch header from O2

---

PWGDQ/Tasks/tableReader.cxx

The "processJpsiToMuMuVertexingSkimmed" function uses covariance tables which enables the use of the pair vertexing method.

Adding dimuon vertexing process

---

PWGHF/DataModel/HFSecondaryVertex.h
PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx

This allows to decouple execution of skimming and candidate
creators which is needed to run the HF analyses from skims
stored in the input AOD file.

PWGHF: Remove HFSelTrack from BigTracks

---

EventFiltering/PWGHF/HFFilter.cxx

`aod::HFSelTrack` was removed from `aod::BigTracks` here https://github.com/AliceO2Group/O2Physics/pull/495

[Event filtering] Add back HFTrackSel in join of track tables

---

Common/DataModel/StrangenessTables.h
PWGLF/TableProducer/cascadebuilder.cxx

This uses an alternate way of accessing cascades, as discussed with @jgrosseo. 
The hCascCandidate histogram now does proper bookkeeping of the cascade candidate generation, with bins 1-17 storing the various selection levelss (i.e. 0 -> all candidates considered, 16 -> candidate passing everything and correctly built). This should allow for further quick debugging in case of difficulties. 
Still to be implemented: material corrections + some further minor tuning.

Use de-ref via V0link in casc builder, other fixes

---

Common/CCDB/macros/upload_event_selection_params.C
Common/TableProducer/eventSelection.cxx
Common/Tasks/eventSelectionQa.cxx

* kIsPultupFromSPD flags fixed in run2-converted data. Using kIsPileupFromSPD instead of kPileupInMultBins workaround
* fixed run ranges in upload_event_selection_params.C
* processRun3 set to false by default in eventSelectionQa

Using kIsPileupFromSPD instead of kPileupInMultBins

---

PWGJE/TableProducer/emcalCorrectionTask.cxx

The GeoManager is needed in order
to calculate the cluster kinematics.
Loading via the GeoManager fails on
HyperLoop due to a missing Geometry
file, instead it needs to be obtained
from the CCDB.

[EMCAL-670] Initialize GeoManager from CCDB

---

PWGHF/TableProducer/HFCandidateCreatorX.cxx

Improving the selection of the X(3872) in the candidate creator adding configurable cuts on Jpsi mass and pion pT

PWGHF: improving X(3872) candidate selection

---

PWGLF/Tasks/spectraCharged.cxx

To temporarily workaround the problem with isPhysicalPrimary, select the particles directly using PID @mario-krueger @yelmard

PID as temporary workaround for primaries

---

PWGLF/Tasks/spectraCharged.cxx

Event selection is fixed so that it now also works correctly for converted Run2 MC and data @mario-krueger @yelmard

Fix event selection in charged particle spectra task

---

Common/Tools/handleParamBase.h
Common/Tools/handleParamTOFReso.cxx
Common/Tools/handleParamTPCBetheBloch.cxx

- Add common utility for CCDB handling
- Add possibility to create timestamp based objects based on run number

Extend handling of PID response param

---

PWGLF/Tasks/spectraCharged.cxx

Remove temporary workaround for primary particle selection now that isPhysicalPrimary is fixed

Charged spectra update primary particle selection

---

PWGDQ/Core/CutsLibrary.h
PWGDQ/Core/VarManager.h
PWGDQ/DataModel/ReducedInfoTables.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerMC.cxx
PWGDQ/Tasks/dqEfficiency.cxx
PWGDQ/Tasks/tableReader.cxx

Adding the table DileptonExtra to fill vertexing information, indices of single tracks and rapidity.
Adding a tracktype variable for muons to the VarManager and to the ReducedMuons, as well as cuts to select specific types in the CutsLibrary.
Finally, also adding at processMuMuVertexing to the dqEfficiency task.

Adding extra dilepton table for muon and tracktype variable for muon

---

PWGHF/Tasks/HFMCValidation.cxx

This PR adds more histograms and decay channels to the MC validation task. For the reco part I removed the dependency from the selector to allow the checks for several decay channels without requiring the dependency on all the selectors. I think that for the quantities checked in this task there is also no need to apply refined selections and the preselections are enough. Let me know if you agree @vkucera @apalasciano @mmazzilli!

PWGHF: Extend HF MC task with more outputs and channels

---

Common/Core/RecoDecay.h

@jgrosseo @vkucera I noticed that sometimes the indices are overflow (@aalkin told me something similar in a private chat when helping me with the debugging). This causes a segmentation violation (e.g. I debugged downloading locally the same inputs used for this hyperloop train https://alimonitor.cern.ch/train-workdir/tests/0002/00020645/stdout.log). I remember that this could be likely avoided asking for primary particles from a chat with @jgrosseo, but I also think that the method in `RecoDecay.h` should be generic for any usecase (also non primary particles). Let me know if you have different opinions or suggestions for better implementations!

RecoDecay, PWGHF: Add protection for index double-counting

---

Common/DataModel/TrackPropagation.h
PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/femtoDreamDebugTrack.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

Add momentum at the primary vertex to `TrackPropagation.h`
It is extremely important for femtoscopy analyses.
I added momentum as `DECLARE_SOA_DYNAMIC_COLUMN`. I wanted to add it as `DECLARE_SOA_EXPRESSION_COLUMN` (because it is used very often and to be consistent with `aod::Tracks`), but I could not because hyperbolic functions are not defined in `Core/Framework/BasicOps.h`.

Propagate momentum to PV

---

PWGDQ/DataModel/ReducedInfoTables.h
PWGDQ/Tasks/dqEfficiency.cxx
PWGDQ/Tasks/tableReader.cxx

An extra column is added to the dilepton table in order to store the information about the MC decision between signal and background

PWGDQ: add an extra colum to dilepton table for mcDecision

---

Tutorials/src/eventMixing.cxx
Tutorials/src/tracksCombinations.cxx

Hi @jgrosseo 
I updated the tracksCombination tutorial to show the usage of the new Binning Policy interface.
There is an example how to use configurable binning - I would suggest everyone that uses selfCombinations (you + FemtoDream + PWGDQ) to update the codes. We can perhaps advertise this at a Monday meeting?
Also, would we like to provide more support for configurable bins, to allow for defining configurable Binning Policy also outside `process()`?
Updated event mixing examples commented out, as they will cause compilation errors until we merge mixing integration. I will submit this integration in the next PR after https://github.com/AliceO2Group/AliceO2/pull/8362 will be merged.

[Event mixing] Update tutorials for new binning policy

---

PWGDQ/TableProducer/tableMakerMC.cxx

mctrack.daughtersIds() contains only the first and the last index of the decay daughters. Therefore the size of the vector daughters was always <= 2. At the moment of filling daughterRange, all but the first two decay daughters were lost.

fix daughters indexes saving into reducedMCTrack

---

DPG/Tasks/qaImpPar.cxx

- `useTriggerkINT7` [default: `false`]: apply the MB trigger selection
- `useIsGlobalTrackFilter` [default: `true`]: apply the filter for `isGlobalTrack`

[DPG]: add two new Configurables to qaImpPar workflow.

---

Common/DataModel/CaloClusters.h
Common/TableProducer/CMakeLists.txt
Common/TableProducer/caloClusterProducer.cxx
PWGEM/Tasks/CMakeLists.txt
PWGEM/Tasks/phosCellQA.cxx
PWGEM/Tasks/phosCluQA.cxx

First implementation of Run2  PHOS Tender and EMCAL AnalysisFramework.
Table CaloCluster to be discussed/agreed with EMCAL and probably replace table PWGJE/DataModel/EMCALClusters.h

Calo Tender implemented

---

PWGJE/DataModel/EMCALClusters.h
PWGJE/TableProducer/emcalCorrectionTask.cxx

Calos and Collision need to be mapped to BCId to use it as index column. The process function should also accept BCs without collision, taking (0,0,0) as vertex location for the cluster kinematics, to support stand-alone partitions. The index column of the cluster needs to be BCId instead of collision.
In addition the message about the number of cells found by the correction task need to be changed to LOG(debug), too
verbose on hyperloop.

[EMCAL-670] Map calos and collision to BCId, use BC ID as index column for the clusters

---

Common/Core/RecoDecay.h
EventFiltering/PWGHF/HFFilter.cxx
PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFCandidateCreatorCascade.cxx
PWGHF/TableProducer/HFCandidateCreatorChic.cxx
PWGHF/TableProducer/HFCandidateCreatorX.cxx
PWGHF/Tasks/HFMCValidation.cxx
PWGHF/Tasks/taskBPlus.cxx
PWGHF/Tasks/taskChic.cxx
PWGHF/Tasks/taskD0.cxx
PWGHF/Tasks/taskDPlus.cxx
PWGHF/Tasks/taskJpsi.cxx
PWGHF/Tasks/taskLb.cxx
PWGHF/Tasks/taskLc.cxx
PWGHF/Tasks/taskLcCentrality.cxx
PWGHF/Tasks/taskLcK0sP.cxx
PWGHF/Tasks/taskX.cxx
PWGHF/Tasks/taskXic.cxx
PWGHF/Tasks/taskXicc.cxx

@jgrosseo @vkucera @aalkin I am reverting this again to the indices (using the table offset explicitly for grouped tables) because of the error that I still get in analysing the MC data with @aalkin offline. In case it's helpful for debug, I can open a second PR as last time with the implementation that uses slices, let me know.
I also ping @AnnalenaKa and @strogolo who asked me about this issue last week, this PR should fix it.

[RecoDecay, Event Filtering, PWGHF] Revert to daughter indices using explicitly offset

---

Common/Core/aodMerger.cxx

This assumes that the first tree that is retrieved is always the one with the
highest cycle (--> the latest). E.g. in case of:
KEY: TTree	O2mcparticle_001;2	O2mcparticle_001 [current cycle]
KEY: TTree	O2mcparticle_001;1	O2mcparticle_001 [backup cycle]
this tree will be merged only 1x (otherwise it is merged on itself).

[O2-2896] When a tree was already merge, don't merge it again.

---

.github/workflows/code-formatting.yml

ActionLint complains about this.
Cc: @vkucera

Move untrusted PR branch name into env var

---

.github/workflows/code-formatting.yml

Add a whitespace check like the one in AliceO2Group/AliceO2.
Also, change the copyright header check so that it marks errors in GitHub's diff view as well.
I've not tested this workflow as a whole yet (only the `git diff` line and the awk script separately), but if it's OK, this can be merged and I'll fix issues if and when they arise.

Improve code formatting checks

---

EventFiltering/PWGLF/nucleiFilter.cxx
EventFiltering/cefpTask.cxx
EventFiltering/filterTables.h

First implementation of the output table of the CEFP. 
This table contains the BCId, the collision time and the CEFP decision and it will be consumed by the reconstruction.

Output table of CEFP (first implementation)

---

PWGDQ/Tasks/filterPP.cxx

Change in the track selection task so that the Selection flag table has always the same size as the track table.
Track selection does not need to run on both tracks and events

Small fix in trigger task

---

Common/Core/RecoDecay.h
EventFiltering/PWGHF/HFFilter.cxx
PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFCandidateCreatorCascade.cxx
PWGHF/TableProducer/HFCandidateCreatorChic.cxx
PWGHF/TableProducer/HFCandidateCreatorX.cxx
PWGHF/Tasks/HFMCValidation.cxx
PWGHF/Tasks/taskBPlus.cxx
PWGHF/Tasks/taskChic.cxx
PWGHF/Tasks/taskD0.cxx
PWGHF/Tasks/taskDPlus.cxx
PWGHF/Tasks/taskJpsi.cxx
PWGHF/Tasks/taskLb.cxx
PWGHF/Tasks/taskLc.cxx
PWGHF/Tasks/taskLcCentrality.cxx
PWGHF/Tasks/taskLcK0sP.cxx
PWGHF/Tasks/taskX.cxx
PWGHF/Tasks/taskXic.cxx
PWGHF/Tasks/taskXicc.cxx

Usage of particle slices is working now thanks to https://github.com/AliceO2Group/AliceO2/pull/8588

[RecoDecay, Event Filtering, PWGHF] Revert to MC particle slices

---

PWGJE/DataModel/EMCALClusterDefinition.h
PWGJE/DataModel/EMCALClusters.h
PWGJE/TableProducer/emcalCorrectionTask.cxx
PWGJE/Tasks/emcclustermonitor.cxx

This PR is the beginning of the efforts to solve two problems:
1. Allow multiple clusterizers to run at the same time, even though there is only a single table for emcal clusters
2. Deal with clusters that could not be matched to a collisions ID
The first problem is solved by introducing a EMCalClusterDefinition class that contains all the information about what is considered as a cluster. This information is then stored as an int in the cluster table. It has the added advantage that it can also be used for easy steering of the EMCal correction framework. In the current implementation, the correction framework can be given an arbitrary number of cluster definitions as a string separated by commas.
The second problem is solved by using two exclusive tables, where one table contains …

[EMCAL-734] split EMCal cluster table and added cluster definition class

---

Common/Core/aodMerger.cxx

Hi @jgrosseo,
we started this debug long ago, but still surprise come along... My understanding is that if we have a VLA long `n` and in the following iteration we have `n-1` we have 1 slot with memory not managed where apparently from time to time we get rubbish. This fixes my local reproducer, @chiarazampolli is also checking with her reproducer.
Cheers,
Max

Set to 0 indices between iterations

---

Common/DataModel/Multiplicity.h
Common/TableProducer/multiplicityTable.cxx
Common/Tasks/multiplicityQa.cxx

As per discussions in the WP4+WP14 meetings, this PR adds an INEL>0 switch to the multiplicityQa task so that pp collisions can be calibrated as they were in Run 2: with an INEL>0 (at least one charged particle within |eta|<1.0) condition applied to the calibration sample.

incremental update: add INEL>0 condition

---

PWGDQ/Core/CutsLibrary.h

This is a PR to add two new cut setting in the CutsLibrary.h 
- lmee_GlobalTrackRun3
- lmee_GlobalTrackRun3_lowPt
both rely on a new cut called "TightGlobalTrackRun3" which is a copy of "TightGlobalTrack" without the `kIsITSrefit` and `kIsTPCrefit`. These two flags seem only to be available for converted data from Run2, hence I removed them to analyse Run3 data.

Adding a copy of TightGlobalTrack cut without ITS/TPC refit

---

Tutorials/src/tracksCombinations.cxx

Remove obsolete comment about multiplicity and the corresponding workaround

Event mixing: Update combinations tutorial

---

PWGDQ/Core/CutsLibrary.h

Adding two more cut settings for dielectric analysis:
- lmeePID_TPChadrejTOFrecRun3
- lmee_GlobalTrackRun3_TPC_ePID_lowPt
These apply loose and some stricter PID cuts to select electrons.
This should reduce the size of the output, necessary for a train.

Adding additional cuts to reduce the size of the output

---

PWGDQ/Tasks/dqEfficiency.cxx

Fixing the issue with the dqEfficiency histograms filling. The issue was related to the double counting of the MC signals when creating the histograms.

PWGDQ: fixing the issue with the dqEfficiency histograms filling

---

PWGDQ/Core/CutsLibrary.h

Resolving an issue of the current cut setting "lmeePID_TPChadrejTOFrecRun3" in PWGDQ/Core/CutsLibrary.h.
Currently the signal is rejected instead of kept.
By setting the 4th variable (which is responsible to exclude signal) to false, the selection is kept.

PWGDQ: Correction to cut setting lmeePID_TPChadrejTOFrecRun3

---

PWGLF/Tasks/v0cascadesqa.cxx

Hi, @aimeric-landou since when we run this task on Hyperloop we don't get the QA outputs I thought to change it to the stardard ones. 
(many of the changes in the commit are just super minor clang fixes on comments ... apologies if they create a bit of entropy)
Could you have a look?

Set output to standard instead of QualityObject

---

PWGEM/PhotonMeson/Tasks/CMakeLists.txt
PWGEM/PhotonMeson/Tasks/emcalPi0QC.cxx

- Task to obtain invariant mass vs. pt histograms for basic pi0 analysis
- Goal to validate mass position and width of the pi0 using O2 and
compare to AliPhysics
- Basic classes for photons and mesons added
- Task is NOT to be used for physics analyses and only serves the
purpose of QC!
- Task based on clustermonitor task in PWGJE

[EMCAL-737] Adding EMCal pi0 qc task

---

PWGDQ/Core/MCSignal.h
PWGDQ/Core/VarManager.h
PWGDQ/Tasks/dqEfficiency.cxx

Here is a fix for the internal index after sliceBy, a fix to fill the DCA in sigma variable in the varManager for reduced track, propose way to access to the first mother by Anton.

SliceBy, firstmother and DCA in sigma

---

CODEOWNERS

to speed up the workflow we propose to add Mattia and Nicolo as DPG code owners

add DPG code owners

---

Tutorials/src/associatedExample.cxx
Tutorials/src/extendedColumns.cxx
Tutorials/src/mcHistograms.cxx

Updates tutorials to use new `sliceBy` variant with framework-managed cache.
Depends on https://github.com/AliceO2Group/AliceO2/pull/9213.

Tutorials: adapt to new sliceBy

---

PWGMM/Mult/Tasks/dndeta-mft.cxx

When analyzing MC, it makes the histogram EventsNtrkZvtxGen different to EventsNtrkZvtx, and allows a correction on vertex splitting

Added correction on vertex splitting

---

cmake/O2PhysicsAddExecutable.cmake
cmake/O2PhysicsAddWorkflow.cmake

Instead of only using it for compilation. Hopefully, this will keep memory use during compilation within available limits.

Use compilation job pool for linking as well

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx
Common/Tools/handleParamTPCResponse.cxx

Previously the CCDB call made for the TPC PID response during init() was preventing newer CCDB calls during the track loop due to the caching. This patch removes the CCDB call during initialisation and the CCDB is only requested during the track loop so that the correct response object for the BC is loaded.

fix caching behaviour for TPC CCDB objects

---

PWGHF/Tasks/HFMCValidation.cxx

This PR adds a TH2 with decay length vs hadron species, useful to debug the charm-hadron origin tag

[PWGHF] Add histogram of decay length at gen level

---

ALICE3/Tasks/alice3-cdeuteron.cxx
Common/Tasks/eventSelectionQa.cxx
DPG/Tasks/qaEventTrack.cxx
EventFiltering/PWGUD/DGHelpers.h
PWGDQ/TableProducer/tableMakerMC.cxx
PWGDQ/Tasks/dqEfficiency.cxx
PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx
PWGEM/PhotonMeson/Tasks/gammaConversions.cxx
PWGLF/TableProducer/LFTreeCreatorNuclei.cxx
PWGLF/Tasks/spectraCharged.cxx
PWGUD/Tasks/diffMCDataScanner.cxx
PWGUD/Tasks/diffMCQA.cxx
PWGUD/Tasks/diffQA.cxx

This replaces all the cases where old `sliceBy` is used by the new syntax, accompanied by `Preslice<>` declaration. Using it will ensure that the actual slicing code is run one per dataframe and its results are cached and re-used, providing considerable improvement in performance.
PR is split into individual commits, as this change needs to be verified to produce exactly the same result as original code. Specifically its interaction with filters needs to be validated. Please tests these commits and report the results here.

Framework: Move to new sliceBy() syntax

---

Common/Core/RecoDecay.h
EventFiltering/PWGHF/HFFilter.cxx
PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFCandidateCreatorChic.cxx
PWGHF/TableProducer/HFCandidateCreatorX.cxx
PWGHF/Tasks/HFMCValidation.cxx
PWGHF/Tasks/taskBPlus.cxx
PWGHF/Tasks/taskChic.cxx
PWGHF/Tasks/taskD0.cxx
PWGHF/Tasks/taskDPlus.cxx
PWGHF/Tasks/taskJpsi.cxx
PWGHF/Tasks/taskLb.cxx
PWGHF/Tasks/taskLc.cxx
PWGHF/Tasks/taskLcCentrality.cxx
PWGHF/Tasks/taskLcK0sP.cxx
PWGHF/Tasks/taskX.cxx
PWGHF/Tasks/taskXic.cxx
PWGHF/Tasks/taskXicc.cxx

This PR fixes the search of the mother particles, in particular when needed at partonic level (i.e. non-prompt tagging for HF analyses). In the previous version, only the first element of the mothers vector was checked, however most of the times the beauty quark is not in the first element. This was the origin of the issue related to the non-prompt tagging found in [O2-2761](https://alice.its.cern.ch/jira/browse/O2-2761), now fixed with this PR.

[PWGHF]: Fix search of mothers to work also at partonic level

---

ALICE3/Core/TOFResoALICE3.h
ALICE3/TableProducer/alice3-pidTOF.cxx
Common/Core/AnalysisCoreLinkDef.h
Common/Core/PID/PIDTOF.h
Common/Core/PID/ParamBase.cxx
Common/Core/PID/ParamBase.h
Common/Core/PID/TOFReso.h
Common/TableProducer/PID/pidBayes.cxx
Common/TableProducer/PID/pidTOF.cxx
Common/TableProducer/PID/pidTOFBase.cxx
Common/TableProducer/PID/pidTOFBase.h
Common/TableProducer/PID/pidTOFFull.cxx
Common/TableProducer/PID/pidTOFbeta.cxx
Common/Tools/handleParamBase.h
Common/Tools/handleParamTOFReso.cxx
DPG/Tasks/qaPIDTOF.cxx
DPG/Tasks/qaPIDTOF.h
DPG/Tasks/qaPIDTOFMC.cxx
DPG/Tasks/qaPIDTPC.h
DPG/Tasks/qaPIDTPCMC.cxx

- bypass previous DetectorResponse common structure (will be removed)
- New structure holds only parameters
- Implementation is left in code only
- Add additional param getter
- Using data member as mass defined at compile time
- Fix warning of overriding streamers
- Simplify TOF param handler
- Add performance plotting
- Add validity based on run range
- Add parameters to metadata
- Add PID simple mode w/o slicing
- Add possibility to turn on and off slices
- Extend TOF PID tasks
- Fix pidTOF switches
- Update default par name to TOFResoParams, add FT0 only ev time
- Clean includes
- Extend TOF QA plots
- Add ev time reso
- Fill ev time per class

Simplify TOF PID Response parameter usage

---

PWGDQ/Core/MCProng.cxx
PWGDQ/Core/MCProng.h
PWGDQ/Core/MCSignal.h
PWGDQ/Core/MCSignalLibrary.h
PWGEM/Tasks/CMakeLists.txt

Implemented a setter function in the MCprong files to give the option, when defining a MCsignal in the MCSignalLibrary.h to check the MC signal from the mother to the daughter (In time).
Therefore the MC signal needs the mother pdg code as first entry and its daughter as second:
e.g. 
```
if (!nameStr.compare("LFQdecayToE")) {
MCProng prong(2, {900, 11}, {true, true}, {false, false}, {0, 0}, {0, 0}, {false, false});
prong.SetSignalInTime(0, true);                                                    // set direction to check for daughters (true, in time) or for mothers (false, back in time)
signal = new MCSignal(name, "LF meson  + quarkonia decays into e", {prong}, {-1}); // pi0,eta,eta',rho,omega,phi,jpsi,psi2s mesons
return signal;
}
```
The CheckProng function in MCSignal.h then checks …

Implement setter function to check MC signal from mother to daughter

---

Common/Core/RecoDecay.h
EventFiltering/PWGHF/HFFilter.cxx
PWGHF/DataModel/HFSecondaryVertex.h
PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFCandidateCreatorChic.cxx
PWGHF/TableProducer/HFCandidateCreatorX.cxx
PWGHF/Tasks/HFMCValidation.cxx
PWGHF/Tasks/HFSelOptimisation.cxx
PWGHF/Tasks/taskD0.cxx
PWGHF/Tasks/taskDPlus.cxx
PWGHF/Tasks/taskLc.cxx
PWGHF/Tasks/taskLcCentrality.cxx

This PR implements a specific method to tag prompt/non-prompt charm hadrons, as discussed in [Nonprompt_tagging_fgrosa_2022Jul04.pdf](https://indico.cern.ch/event/1178012/contributions/4948661/attachments/2474891/4246862/Nonprompt_tagging_fgrosa_2022Jul04.pdf). 
I just have a doubt regarding the output values of the `checkCharmHadronOrigin` function: they correspond to the `hf_cand::OriginType` enum, but are independently defined since the HF code should not be included in the common one. A possible solution to have it uniquely defined would be to move the `hf_cand::OriginType` enum in the Common code, or alternatively to move the method `checkCharmHadronOrigin` in the HF code (however it could also be useful for DQ, since it can be used to tag charmonia as well). @vkucera do you have …

[Common, PWGHF, Event Filtering] Implement specific method to tag prompt/nonprompt charm hadrons

---

PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFCandidateCreatorCascade.cxx
PWGHF/TableProducer/HFCandidateCreatorXicc.cxx
PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx
PWGHF/Tasks/taskD0.cxx
PWGHF/Tasks/taskDPlus.cxx
PWGHF/Tasks/taskJpsi.cxx
PWGHF/Tasks/taskLc.cxx
PWGHF/Tasks/taskLcCentrality.cxx
PWGHF/Tasks/taskX.cxx
PWGHF/Tasks/taskXic.cxx

Related PRs:
- https://github.com/alisw/AliPhysics/pull/20723
- https://github.com/AliceO2Group/Run3Analysisvalidation/pull/350

PWGHF: Standardise validation histograms (names, binning)

---

PWGLF/Tasks/v0cascadesqa.cxx

Hi @njacazio, this is part of the debug of the problem with cascades efficiencies.

Fix MC association + add debug histos

---

DPG/Tasks/qaEventTrack.cxx

@njacazio here the development discussed before (thanks @fgrosa for the profitable discussion). I removed the explicit collision grouping from the `process`, adopting as workaround a manual grouping with `sliceBy`. Let me know if you like this solution.

DPG: add qa of tracks not matched to collisions.

---

PWGDQ/Core/CutsLibrary.h
PWGDQ/Core/MCSignalLibrary.h
PWGDQ/Core/VarManager.h

More cut and signal definition + nb of its clusters for Run 3

More cut and signal definition + nb of its clusters for Run 3

---

DPG/Tasks/qaEventTrack.cxx

Further histograms to check the correct matching of tracks to collisions. In particular, here we test:
- how many tracks are associated to collisions;
- how many tracks associated to a reco collision have a gen. particle that belongs to the MCcollision the reco. one points to
- have a look at it differentially in z-vertex residual and particle type (phy. primary, secondary)

DPG: test correct track-to-collision matching with MC info.

---

Common/TableProducer/trackPropagation.cxx

Add compatibility with new GRP scheme

---

Common/TableProducer/PID/CMakeLists.txt
Common/TableProducer/PID/pidTPCML.cxx
Common/TableProducer/PID/pidTPCML.h

* Out of line code to reduce memory usage while compiling pidTPC tasks
* Change to use an array for the intermediate tracks representation.
It would probably be better to read directly the values from the
arrow tables, but that will come in a different PR.

Improve pidTPCML.cxx

---

PWGHF/Tasks/HFMCValidation.cxx

@mfaggin let me know if it looks reasonable to you!

PWGHF: add information about tracks with ambiguous collision association

---

PWGMM/Mult/Tasks/vertexing-fwd.cxx

I added some comments for readability, I put a template to avoid writing twice the same process function with just a small variation, and I implemented the DCAxy cut. The ambiguous tracks having a DCAxy > maxDCAXY will just stay ambiguous.

Commented added template and cut of DCAxy

---

Common/Tools/handleParamTPCResponse.cxx

TPC PID response handler's CCDB access was broken by a previous commit that modified the timestamp initialisation in handleParamBase.h (#934). This PR fixes the incompatibility and removes redundancies with the options that were added to the base header.
Only impacts the parameter object handler tool; the analysis tasks are unaffected.

Fix CCDB access in TPC PID response handler tool

---

PWGJE/Core/JetUtilities.h
PWGJE/DataModel/EMCALClusterDefinition.h
PWGJE/DataModel/EMCALClusters.h
PWGJE/TableProducer/emcalCorrectionTask.cxx
PWGJE/Tasks/emcclustermonitor.cxx

The following things changed:
- adaptation of cluster definition and corresponding filter. From now on the integer hast to be used to filter, since runtime changes to the filter when using a string as a configurable are not supported by framework. The correction framework and task have to now be run like this for example:
`o2-analysis-je-emcal-correction-task --clusterDefinition "kV3Default" \
| o2-analysis-je-emc-clustermonitor --clusterDefinition 10`
- implemeted cluster to track matching by adapting the jetmatching algorithm using a KDTree. This has the advantage of improved performance for Run3 with O(n log(n)). The algorithm is adapted to contain not only the closest match but the K closest matches to a cluster within a specified radius. At the same time K closest clusters for each …

[EMCAL-734][EMCAL-689] implemented track matching and connection between cell and cluster

---

CODEOWNERS

...so that the analysis coordinator can, in turn, change codeowners and manage responsible users

Update codeowners to add analysis coordinator

---

PWGLF/Tasks/CMakeLists.txt
PWGLF/Tasks/cascadeanalysisMC.cxx

Some adjustments (in particular a declarative cascade MC association filter) still to be done, but important to have zeroth order version there now

Cascade analysis mc task - first commit

---

PWGMM/Mult/TableProducer/CMakeLists.txt
PWGMM/Mult/TableProducer/trackPropagation.cxx
PWGMM/Mult/Tasks/dndeta.cxx

This is a first attempt to account for ambiguous tracks by trying to associate them to compatible collisions. The best collision is determined as one for which DCA is the smallest, out of all collisions (if any) associated to compatible BCs. 
A dedicated task produces a table, joinable with `AmbiguousTracks` that contains collision index and refitted track parameters. 
@fgrosa this may also work for you, you can access ambiguous tracks, re-associated to a (single) collision by subscribing to `soa::SmallGroups<soa::Join<aod::AmbiguousTracks, aod::BestCollisions>> const& atracks`. Note that this simple method does not create duplicated associations.

PWGMM: dndeta: refit ambiguous tracks

---

PWGLF/Tasks/phianalysis.cxx

Hello @BongHwi ,
recently in July I extended the mixing interface with a new binning policy type. Therefore, I will keep `ColumnBinningPolicy` and `FlexibleBinningPolicy` as precise names, and with https://github.com/AliceO2Group/AliceO2/pull/9528 I will remove the general `BinningPolicy` alias to avoid future confusions. Please let me update your code and follow with my O2 PR.
FYI, there is an up-to-date event mixing documentation at https://aliceo2group.github.io/analysis-framework/docs/framework/eventMixing.html which I update after any major change.

Update binning policy class name to the new interface in new task in PWGLF

---

PWGLF/TableProducer/lambdakzerobuilder.cxx

Hi, @ddobrigk and @njacazio 
this is the patch that recovers the error when running the lambdakzerobuilder on Run 2 converted data. There was a problem in the type of the timestamp.

lambdakzerobuilder: add patch for type error Run 2

---

PWGHF/Tasks/taskD0.cxx

Just a signficant zoom on the d0xd0 axis, since in the current version the axis is too wide and the whole distribution is described by 2 bins.

PWGHF: Minimal fix to range of d0xd0 histogram in D0mass task

---

PWGHF/HFC/TableProducer/HFCorrelatorD0D0bar.cxx
PWGHF/HFC/TableProducer/HFCorrelatorD0D0barBarrelFullPID.cxx
PWGHF/HFC/TableProducer/HFCorrelatorDplusDminus.cxx

Switch from Filters to Partitions in DDbar correlation codes to be fully consistent with mulitple processes, subscribing to different sets of joined tables

PWGHF: substitute Filters with Partitions in DDbar correlation codes

---

PWGDQ/Core/VarManager.h

Correcting the computation of the error on pseudo-proper time. The previous method was giving nan values.

Correcting Tauz error computation

---

DPG/Tasks/AOTTrack/qaMatchEff.cxx

- dcaXY selection added;
- possibility to use pt(TPC), i.e. calculated from the inner wall of TPC.
CAVEATS:
- selections on TPC kinematic variables not possible in AO2Ds. Only pt(TPC) cut is applied "by hand" when pt(TPC) is enabled;
- pt(TPC) calculated using tan(lambda) from tracking (value at the inner wall of TPC not available).

DPG: update ITS-TPC match. eff. workflow to improve the comparison with QC.

---

PWGDQ/DataModel/ReducedInfoTables.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerMC.cxx

Adding QA for ambiguous tracks via configurable:
- additional index to flag a track as ambiguous or not in the reducedAOD
- additional histograms for ambiguous tracks only

PWGDQ: adding QA for ambiguous tracks

---

CMakeLists.txt
cmake/O2PhysicsAddHeaderOnlyLibrary.cmake
cmake/O2PhysicsAddLibrary.cmake
cmake/O2PhysicsDataFile.cmake
cmake/O2PhysicsSetROOTPCMDependencies.cmake
cmake/rootcling_wrapper.sh.in
packaging/CMakeLists.txt
packaging/O2PhysicsConfig.cmake

For many reasons (including Open Access) would be required to be able to use O2Physics as (external) dependency for various downstream projects.
So far this is work in progress, as i do not understand the complete cmake structure of O2 which i tried to copy to O2Physics
At this moment the error that i get is:
```
2022-09-21@12:36:05:DEBUG:O2Physics:O2Physics:o2physics: -- Configuring done
2022-09-21@12:36:12:DEBUG:O2Physics:O2Physics:o2physics: CMake Error: INSTALL(EXPORT) given unknown export "O2PhysicsTargets"
```
and it's not clear to me where to look
@ktf @TimoWilken guys, if you have time to take a look maybe you can spot some obvious problem given your experience with the cmake insides of O2.
Thanks a lot!

export the cmake info for usage of O2Physics as dependency

---

DPG/Tasks/AOTTrack/qaEventTrack.cxx

- sliceBy usage removed from processData
- new processTrackMatch for track-to-collision association QA

DPG: optimize CPU consumption in qaEventTracks.cxx

---

PWGDQ/Tasks/tableReader.cxx

Fixing the issue with ccdb path

PWGDQ: Fixing the issue with ccdb path

---

DPG/Tasks/AOTTrack/qaEventTrack.cxx

- Execution for procesTrackMatch alone fixed
- BugF fix: retrieve the track from the amb. track table via trackId(), not globalIndex()
- New algorithm based simply on iterator and indices comparison, instead of the slow std::find

DPG: update code to count ambiguous tracks

---

PWGHF/Core/HFSelectorCuts.h
PWGHF/DataModel/HFSecondaryVertex.h
PWGHF/TableProducer/HFLcK0sPCandidateSelector.cxx

- make the cuts and the ptBins for the Lc->K0sP analysis configurable via the .json config file (analogous to the other tasks, defaults defined in HFSelectorCuts.h)
- changed nonsensical cut on the candidates's pt in the cut matrix to a cut on the V0's pt
Related PR: https://github.com/AliceO2Group/Run3Analysisvalidation/pull/362

PWGHF: make LctoK0sP cut matrix configurable

---

PWGHF/HFL/Tasks/CMakeLists.txt
PWGHF/HFL/Tasks/HFmAnalysis.cxx

This task is derived from the DQ framework and it is used to extract the observables on single muons (pT, eta, sign of the muon, DCA,  etc) needed for the HF-muon analysis. It is indeed linked to HF since the final goal is to measure muons from charm decays and muons from beauty decays, separately from the information estracted with this task.

PWGHF: add single muon analysis task

---

PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx

Hi @vkucera @cterrevo @ginnocen @fcolamar ,
I fixed the GRP object query for the magnetic field used for the PV refit, since from the first implementation the data type changed for Run 3. I have tested it locally and the execution succeded.
I put the PR in draft for the moment, as usual. Let me know what you think.

PWGHF: fix B-field Run 3 GRP object for PV refit.

---

PWGDQ/Tasks/dqFlow.cxx

Fixing the CCDB issue for dqFlow Task like tableReader https://github.com/AliceO2Group/O2Physics/pull/1299.
Also CCDB path can be commented like https://github.com/AliceO2Group/O2Physics/pull/1322 for hyperloop operations but  CCDB path is used in the dqFlow task unlike tableReader so I want to keep there

[PWG-DQ] Fix CCDB Path for dqFlow Task

---

CMakeLists.txt

Apparently, CMake doesn't enable the "C" language by default for some users, which we need to use some O2Physics dependencies (like LibFFI).
This fixes a problem reported by email on alice-project-analysis-task-force.

Fix build on MacOS Monterey

---

Common/Tools/Multiplicity/CMakeLists.txt
PWGUD/Tasks/CMakeLists.txt

Some CMake files have a copyright notice with messed-up formatting. This fixes them, in preparation for the CI copyright check to also cover CMake files (see alisw/ali-bot#1199).

Fix copyright notice in CMake files

---

CMakeLists.txt
Common/Core/CMakeLists.txt
Common/DataModel/CMakeLists.txt
Common/TableProducer/CMakeLists.txt
Tools/PIDML/CMakeLists.txt
cmake/O2PhysicsAddHeaderOnlyLibrary.cmake
cmake/O2PhysicsAddLibrary.cmake
dependencies/FindKFParticle.cmake
dependencies/FindONNXRuntime::ONNXRuntime.cmake
dependencies/Findfjcontrib.cmake
dependencies/O2PhysicsDependencies.cmake

@hristov @TimoWilken  A few fixes / improvements (hopefully) in some CMake files for your consideration : 
- the `o2physics_add_header_only_library` was creating libraries in the `O2::` namespace instead of `O2Physics::' one (which might explain the failed attempt by @adriansev #1324) 
- with the fix above DataModel can now be a proper (header-only) library
- the two added CMake find modules are not strictly necessary for a stack completely driven by aliBuild, but helps in case e.g. ONNXRuntime is installed by other means (and should not hurt 100% alibuild stacks)

Some CMake fixes/improvements

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

- Add option to use cov matrices of tracks as weights in the calculation of decay point (to be checked!). Default true to match Run 2 operation. Parameter name: `d_UseWeightedPCA`
- Add option to change material correction for cascades

Builder changes 

---

PWGDQ/TableProducer/tableMakerMC.cxx

In Run3 there can be "fake collisions". That means one might encounter collisions where there exists no corresponding MC Collision.

add protection from missing mcCollision

---

PWGCF/FemtoWorld/TableProducer/femtoWorldProducerTask.cxx
PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskTrackTrack.cxx

I've changed PID function for Kaons and I've added a small change in the invariant mass cut for phi mesons

Fixing Kaon PID in FemtoWorld

---

PWGEM/Dilepton/Tasks/dileptonEE.cxx

Commenting out some ccdb lines which were also removed for the TableReader

PWGEM: disable CCDB reference

---

PWGDQ/Core/CutsLibrary.h

Adjust the rejection cuts of pions, kaons and protons

PWGDQ: adjust pion/kaon/proton rejection cuts

---

PWGDQ/Core/HistogramsLibrary.h
PWGDQ/Tasks/tableReader.cxx

HI, Ionut 
(1) I did small changes to split the TPC post_calibration histogram from the existing tpcpid histogram. Now once I switch off the TPC post_calibration histogram, the normal TPC PID histogram is still there. 
(2) cleaned the code by removing some empty space. 
Cheers
Xiaozhi

small changes to split the TPC post_calibration histogram from the existing tpcpid histogram    

---

PWGHF/TableProducer/HFCandidateCreator2Prong.cxx
PWGHF/TableProducer/HFCandidateCreator3Prong.cxx
PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx
PWGHF/Utils/UtilsBfieldCCDB.h
PWGHF/Utils/utilsBfieldCCDB.h

- Common utility to query the CCDB and set the magnetic field in the `o2::base::Propagator` object
- Implemented for `HFTracksIndexSkimCreator.cxx` and `HFCandidateCreator2,3Prong`
- Missing for multi-decay candidate creators (eg: `B0`, `B+`)

PWGHF: B field setting from CCDB.

---

PWGUD/Core/UPCCutparHolder.cxx
PWGUD/Core/UPCCutparHolder.h
PWGUD/Core/UPCHelpers.h
PWGUD/TableProducer/UPCCandidateProducer.cxx

* Add a possibility to check for ITS-TPC tracks near candidates, similarly to PF-protection
* Add a configurable FT0 check range
* Move filling of central barrel track QA histograms to a separate task

Update for UPC candidate producer

---

PWGUD/TableProducer/UPCCandidateProducer.cxx

* Use `int` Configurables instead of `int8_t`
* Collect ITS-TPC tracks only if track search is needed

Fixing typos in UPC candidate producer 

---

PWGCF/FemtoDream/femtoDreamProducerTask.cxx

Fix work around that was used in the past to analyse pilot beam data.

PWGCF: fix multiplicity determination in femtoDreamProducerTask

---

PWGDQ/Core/CutsLibrary.h

Hi
Tight the number of TPC clusters cut for 22m testing since the space charge distortion correction is missing, we select high-quality track at the moment
Cheers
Xiaozhi

tight the number of TPC clusters cut for 22m testing

---

PWGDQ/Tasks/dqEfficiency.cxx

When creating histograms for muons, the naming of the histogram classes begins with TrackBarrel instead of Muon. This causes the choice of the wrong variable list to fill.

fix typo: was TrackBarrel instead of Muon in muon-selection process

---

CMakeLists.txt
Common/DataModel/CMakeLists.txt
cmake/O2PhysicsAddHeaderOnlyLibrary.cmake

an attempt at #1454
as we're using CMake >= 3.23, I guess we could use the concept of file sets to install those includes. 
Note the addition of the `HEADERS` param to `o2_physics_add_header_only_library` which is used to be explicit about which headers should be installed (i.e. which ones are part of the public interface of the "library"). Note also that in O2 it's kind of easier to know which includes are public as there's a dedicated directory for that (at the price of a strange stuttering structure `include/LIBNAME/headername.h`)
@adriansev would you have an example package that is trying to use an O2Physics installation to build something ? so I could try on my side and see whether the installation is actually usable ?

install DataModel includes

---

PWGCF/FemtoDream/FemtoDreamObjectSelection.h

Warning occurs if the loop object is constant, but we we create a copy of it and do not use a reference. This is fixed with this patch. 
Also containing some changes to pass MegaLinter checks.

PWGCF: fix compiler warning in FemtoDream framework

---

PWGCF/TwoParticleCorrelations/Core/CMakeLists.txt
PWGCF/TwoParticleCorrelations/Core/FilterAndAnalysisFramework.cxx
PWGCF/TwoParticleCorrelations/Core/FilterAndAnalysisFramework.h
PWGCF/TwoParticleCorrelations/Core/TwoPartCorrLinkDef.h
PWGCF/TwoParticleCorrelations/TableProducer/CMakeLists.txt
PWGCF/TwoParticleCorrelations/TableProducer/skimmingconf.h
PWGCF/TwoParticleCorrelations/TableProducer/twoParticleCorrelationsFiltering.cxx
PWGCF/TwoParticleCorrelations/TableProducer/twoParticleCorrelationsRegisterSkimming.cxx
PWGCF/TwoParticleCorrelations/TableProducer/twoParticleCorrelationsSkimming.cxx

Now the signature of the skimming configuration is stored in the CCDB and the check of the consistency between skimmed data configuration and analysis configuration is supported

Policy entity for orchestrating skimming and analysis

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx
Common/TableProducer/PID/pidTPCML.cxx
Common/TableProducer/PID/pidTPCML.h

It was noticed that upon running within singularity containers on a SLURM cluster, ONNX has difficulties to allocate the correct resources if the number of CPU's is limited. A manually set value for the number of available threads fixed this issue. This should not affect the code any further, since the default value lets ONNX choose the number of threads automatically.

Adding Configurable to set number of threads for ONNX

---

PWGDQ/Core/CutsLibrary.h

- electron cut with TPC post-calibration corrected value
- very loose muon selection (matching and acceptance only)

More Cuts for testing :

---

CPPLINT.cfg

This category of errors seems to be only related to Chromium development.
See
- https://stackoverflow.com/questions/33653326/google-style-guide-chrono-is-an-unapproved-c11-header
- https://github.com/iotaledger/entangled/issues/213

cpplint: Ignore unapproved C++11 headers

---

PWGDQ/Core/CutsLibrary.h
PWGDQ/Core/HistogramsLibrary.h
PWGDQ/Core/VarManager.h
PWGDQ/Tasks/dileptonMuMu.cxx
PWGDQ/Tasks/dqEfficiency.cxx
PWGDQ/Tasks/filterPP.cxx
PWGDQ/Tasks/tableReader.cxx
PWGEM/Dilepton/Tasks/dileptonEE.cxx
PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx

Changes to Histogramslibrary.h
- Regroup the different histogram groups used for pairs
Changes to tableReader:
- Add configurables to add histograms
- Adjust DefineHistogram function to pass configurables
- use adjusted group names from HistogramsLibrary.h
- Add configurable to define mixingDepth in config.json file 
Suggestion to change naming of process functions from "JpsiToEE" -> "DecayToEE"
This change is applied to several tasks.
I also will add a pull request to the PythonInterfaceOOP to adjust the renaming.
Change to CutsLibrary.h:
- Add kTPCncls cut to TightGlobalTrack group

PWGDQ/EM: edit tableReader, regroup pair histograms, rename processFunctions, add cut

---

PWGDQ/Core/CutsLibrary.h
PWGDQ/Core/HistogramsLibrary.h
PWGDQ/Core/MCSignalLibrary.h
PWGDQ/Core/VarManager.cxx
PWGDQ/Core/VarManager.h
PWGDQ/DataModel/ReducedInfoTables.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerMC.cxx
PWGDQ/Tasks/CMakeLists.txt
PWGDQ/Tasks/DalitzSelection.cxx

Adding DalitzSelection.cxx for selecting electrons from dalitz decays (running on framework)
Keeping information from the dalitz Selections in tableMaker and tableMakerMC
AnalysisPrefilterSelection in the tableReader to run dalitz selection and prefilter

PWGDQ: Add task for dalitz selection

---

.github/workflows/mega-linter.yml

@TimoWilken I suspect that this has been causing cancellation of the action runs due to ongoing checks in other PRs.
Could you please check?

MegaLinter: Make concurrency groups unique per PR

---

PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/FemtoDreamCollisionSelection.h
PWGCF/FemtoDream/FemtoDreamContainer.h
PWGCF/FemtoDream/FemtoDreamEventHisto.h
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTaskV0Only.cxx

Use multNtrPV to estimate the charge particle multiplicity of an event and add it as a column to FemtoDreamCollision table.
The V0M signal, which has been used so far, might not be needed in the future, but it will be kept for now.

PWGCF: Add column to FemtoDreamCollision table for charge particle multiplicity

---

EventFiltering/cefpTask.cxx
EventFiltering/filterTables.h

Updates in the CEFP:
- add CefpSelected bitmap to the CEFP output table to keep track of selected triggers
- add CefpTrigger bitmap to the CEFP output table to keep track of fired triggers
- add globalBCId to the output table 
- modify the output table for future filtering per BCs

Implement bitmap for CEFP output

---

DPG/Tasks/AOTTrack/PID/qaPIDTOF.h
DPG/Tasks/AOTTrack/PID/qaPIDTPC.h

Changes default parameters of the nsigma axis for the TPC and TOF QA tasks, to avoid filling/plotting issues due to the discrete binning in the "tiny" PID tables.

Change default binning of PID QA tasks

---

PWGDQ/Core/CutsLibrary.h
PWGDQ/Tasks/filterPP.cxx

In filterPP.cxx : naming the single muon and dimuon histogram manager with "Muon" seemed to confuse the histogram manager on which histograms to fill. Therefore the dimuon histogram manager with "PairForward" to avoid any confusions
In CutsLibrary.h :  add a cut for low pT dielectron analyis : |n sigma e TPC| < 5, without momentum cut, |eta_e| < 0.9, chi2 TPC < 4, N TPC crossed rows > 80, Ncls ITS > 0

Correction of a bug in filterPP.cxx + new cut in the CutsLibrary.h file

---

Common/Core/TrackSelectorPID.h
PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx

- suggestion for additional Bayes PID option in TrackSelectorPID.h
- uses a cut on the Bayesian probability for selected particle species, below which it is rejected
- let me know what you think about it
- updated PID selection in candidate-selector-lc-to-k0s-p for bachelor track using the TrackSelectorPID class  
- related PR https://github.com/AliceO2Group/Run3Analysisvalidation/pull/381

PWGHF: new PID selection for candidate-selector-lc-to-k0s-p

---

.github/workflows/mega-linter.yml

@TimoWilken This should avoid including unrelated files in the list of files checked by MegaLinter when the differences w.r.t. upstream are due to the PR branch not being up to date.

MegaLinter: Checkout the merge commit instead of PR HEAD

---

PWGDQ/Core/VarManager.h

Remove momentum ordering which was implemented by a misunderstanding.

PWGDQ: fix definition of PhiV, remove momentum ordering

---

PWGHF/Tasks/taskMcValidation.cxx

Following @fgrosa suggestion, I cleaned up `HfTaskMcValidationGen` and fixed the checks on the momentum conservation and the number of daughters of the decays.

PWGHF: Cleanup and fix MC gen. level validation

---

PWGMM/Mult/Tasks/dndeta-hi.cxx

Add dN/dEta distribution code for heavy-ion based on dndeta.cxx code 
If you have some asking for me, please contact.

PWGMM: dndeta-hi.cxx update for hyperloop

---

.github/workflows/mega-linter.yml

Running on the merge commit is necessary to get the right list of modified files.
@TimoWilken 
Problem with listing the modified files reported: https://github.com/oxsecurity/megalinter/issues/2125

MegaLinter: Checkout the right merge commit 

---

PWGDQ/Core/CutsLibrary.h
PWGDQ/Core/HistogramsLibrary.h

- reduce bins of PhiV plot, due to too large memory consumption
- implement cut which should be used to skim data for EM lmee

Adjust binning of phiV hist, add cut for data skimming

---

PWGDQ/Tasks/filterPP.cxx

Fix the naming convention of the histograms in filterPP.cxx to match the new names in the HistogramLibrary.h

Fix histograms names in filterPP.cxx

---

PWGJE/Tasks/emccellmonitor.cxx

Exclude low-E cells which have a poor time resolution
from time distribution histograms. Amplitude cut is settable.

[EMCAL-733] Add amplitude cut for cell time histograms

---

Common/TableProducer/CMakeLists.txt
Common/TableProducer/collisionConverter.cxx

* adds collision converter task to swap XZ and YY elements of collision covariance matrix 
* more information on the problem this intends to fix is [here](https://indico.cern.ch/event/1219192/contributions/5128952/attachments/2542060/4376840/DDChinellato-MondayMeeting-7Nov2022-1.pdf) 
* goes together with https://github.com/AliceO2Group/AliceO2/pull/10424

Collision covariance matrix: converter with fix

---

PWGDQ/Tasks/tableReader.cxx

Quick fix of table reader.
Misspelling prevents filling of muon histograms

PWGDQ: Table Reader, fix bug in muon histogram filling

---

Common/Core/PID/TPCPIDResponse.h

Small bugfix to the TPC response to use the expected signal, not the measured signal, to define the sigma

PID: fix definition of expected sigma

---

PWGDQ/Core/CutsLibrary.h

Added Comments to categorise cuts related to low-mass dielectrons.
Re-organised cuts within the above comment sections.
(No cuts were deleted or edited. Only placed at other locations)
Added one cut using corrected pid spectra.

PWGDQ: Comment and Reorder lmee cuts, add cut using corrected PID

---

DPG/Tasks/AOTTrack/qaEventTrack.cxx
PWGLF/DataModel/LFStrangenessTables.h
PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/cascadefinder.cxx
PWGLF/TableProducer/multistrangebuilder.cxx

This commit replaces the straight-line cascade DCAxy calculation with a proper DCAxy calculated from a track propagation call that could even use material corrections (disabled by default, to be checked further). This is a very minor change but partially this already goes in the direction of having this information calculated independently perhaps even with more information (e.g. strangeness tracking).

cascade DCAxy now from proper propagation

---

PWGHF/HFC/TableProducer/correlatorD0Hadrons.cxx

Added protection for avoiding having empty tables to which sliceByCached method is applied, in D0-h correlation task

PWGHF: added protection to D0-h correlation task

---

PWGDQ/Tasks/tableReader.cxx

There is an error with the default value which is an empty string in the cfgPrefilterPairCut

PWGDQ: prefilter - protection against null string

---

PWGDQ/Core/HistogramsLibrary.h
PWGDQ/Core/VarManager.cxx
PWGDQ/Core/VarManager.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/Tasks/dqEfficiency.cxx
PWGDQ/Tasks/tableReader.cxx

1) Apply the TPC postcalibration via CCDB
- postcalibration can be applied either in table-maker (produced skims will already include postcalibrated TPC n-sigmas) or at the analysis level. 
- calibration parameters are loaded from CCDB (path can be specified via configurables) based on timestamp.
2) timestamp was added in the datamodel. Currently, BC quantities via BCsWithTimestamps are not computed in the VarManager due to problems at compilation or running which are not yet understood. So for now, the BC related quantities are computed directly in the table-maker. Note that this does not affect the skimmed data model, which includes the BC info in a different table.

[PWG-DQ] Apply TPC postcalibration via CCDB

---

PWGLF/Tasks/cascadeanalysisMC.cxx

* the builder autodetect feature is picking up still _default_ cuts and not json-specific cuts from other tasks (in contact with Giulio and Anton about it, might be a framework bug, not sure) but in anticipation of it working, I am committing this change also for the MC tasks

change to use autodetect feature

---

PWGDQ/Core/VarManager.h
PWGDQ/Tasks/dqFlow.cxx

- Make the task able to compute q-vectors using forward MFT tracks (even if centrality is not yet available). 
- Add a small fix to prevent to fill nan values for dilepton into FillPairVn function.
- Add more configurables for minimal/maximal eta values for selecting ranges and gaps.

PWGDQ: add forward q-vector process, configurables and small fix

---

PWGJE/TableProducer/emcalCorrectionTask.cxx
PWGJE/Tasks/CMakeLists.txt
PWGJE/Tasks/emcclustermonitor.cxx
PWGJE/Tasks/emceventselectionqa.cxx

- [EMCAL-670, EMCAL-850] Outsource event selection histograms to dedicated task
+ global BC % 3564 for all triggered BCs, BCs with
EMCAL readout, BCs with EMCAL cell content and
collisions
+ Adapt EMCAL readout check for run2 data
- [EMCAL-734] Add more histograms to cluster monitor
+ Number of clusters per event / bc total and per
supermodule
+ Cluster energy spectrum vs. supermodule ID
+ Per supermodule:
* Time vs. energy
* Number of cells vs. energy
* Shower shape parameters vs. energy

[EMCAL-670, EMCAL-734, EMCAL-850] Dedicated QA task for EMCAL event selection + more histograms in cluster task

---

PWGHF/Tasks/taskLc.cxx

Hi,
looking at the code I see that when filling the `MC/reconstructed` histograms for the Lc mass we do not check explicitly the real mass hypothesis, but we do only rely on the response from the reconstructon cuts (`isSelLcToPKPi` and `isSelLcToPiKP`). If we do not do it, we risk to do double counting if for our reconstructed candidate both `isSelLcToPKPi` and `isSelLcToPiKP` are true, even if we know that this is a real Lc from here: https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/Tasks/taskLc.cxx#L321
Am I right or is there something that I am missing?

PWGHF: add check on PDG code for Lc 1st daughter in MC.

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx

Setting the log-level for the NN application to debug to avoid spamming the output.

Bug-fix: Setting log-level to debug for the application of the NN

---

PWGEM/PhotonMeson/TableProducer/produceMesonCalo.cxx
PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx

- moved LOG(info) calls from the process function to the init function to reduce the time it's called

PWGEM/PhotonMeson: changed LOG info call

---

Common/TableProducer/collisionConverter.cxx

Interestingly, in MC, a very very small (order of 1 per million or less) fraction of PVs seem to have very-close-to-zero negative CYY values. This is likely a numerical precision problem (to be checked with Ruben after the holiday period). In the meantime, this PR increases the tolerance so that it doesn't trigger on that. Precision check was CYY < -1e-8, is now CYY < -1e-6.

increase tolerance for CYY check

---

PWGLF/Tasks/QC/straRecoStudy.cxx

This is required following #1734 , according to which very small but negative CYY can appear (potentially due to numerical effects). Further cross-checks still to happen + will check with Ruben once holiday period is over

add safety to CYY check

---

PWGMM/Mult/Tasks/dndeta.cxx

* Only add histograms to registry when the corresponding process is enabled
* Use `THnSparse` in place of `TH3` to save memory

PWGMM: dndeta: various improvements

---

PWGDQ/Core/HistogramsLibrary.h
PWGDQ/Core/VarManager.cxx
PWGDQ/Core/VarManager.h
PWGDQ/Tasks/dqFlow.cxx

- Standardize the task name for DQ framework, also for qvector histograms
- Make available the centrality values from the FT0C detector for this task by creating a new `ObjType` called `CollisionCentRun3` in order to fill the associated centrality values within the `VarManager` 
- Modify the qvector processes to add the centrality and add the associated histograms 
- Reorganize the libraries and change of `int` values into `uint8_t`

PWGDQ: standardize task, histo names and make centrality available

---

Common/TableProducer/trackPropagation.cxx

This will remove the unnecessary loading of the full ALICE geometry in the track propagator (not required when propagating with the LUT approach). It will still be tested before going ahead

remove loading of full geometry (not req. by LUT)

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

In this PR, the builders have been changed such that the TGeoVolume etc loading only happens if the TGeo correction is requested and LUT loading only happens if the LUT correction is requested. This will be tested just in case before going ahead, to be sure all is fine

do not load TGeo if using LUT or no correction

---

PWGMM/Mult/Tasks/dndeta.cxx

Using `Join::contains<>()` code for inclusive and centrality-binned versions is unified. 
Depends on https://github.com/AliceO2Group/AliceO2/pull/10578.
@ddobrigk as discussed

PWGMM: dndeta: reduce code duplication

---

PWGEM/Dilepton/Tasks/MCtemplates.cxx

Fix notation of if case to be compatible with older clang compiler versions.

PWGEM: fix clang errors for older versions

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx

Suggestion for a `PROCESS_SWITCH` for HfTrackIndexSkimCreatorCascades, instead of the `--doCascades` option.
The motivation is to allow to enable the cascade task also on HyperLoop.
The empty dummy `processNoCascades` function seems to be necessary when switching off the main `processCascades`  (the workflow gets stuck without it).
In principle one could also build a similar process switch for HfTrackIndexSkimCreator (with default=true), to switch it off when running with HfTrackIndexSkimCreatorCascades instead.
I don't know how these changes should be transferred to https://github.com/AliceO2Group/Run3Analysisvalidation/blob/master/codeHF/workflows.yml

PWGHF: process_switch to enable/disable HfTrackIndexSkimCreatorCascades

---

Common/Tasks/CMakeLists.txt
Common/Tasks/integrationTest.cxx

Added a task to serve as Run 3 integration tester. Checks data model, collision and BC associated basics, and allows for basic output. Optionally includes also 2D correlations between track counters.

Integration test task

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

Based on needs for software triggering and the content shown at the [AOT meeting of the 12th](https://indico.cern.ch/event/1236818/contributions/5203341/attachments/2574614/4439297/DDChinellato-2023-StrangenessReconstructionInO2-02.pdf). 
This PR adds the possibility to pre-filter TPC Ncrossedrows at the preselector level, avoiding loops on candidates with ITS-only tracks if not required (and with the filtering being arrow-based). It also adds an extra flag such that TPC requirements (dE/dx and Ncrossedrows) can optionally only be applied to baryon/heavy daughters. To preserve standard operation, the new flag defaults to false; using it will make it possible to also explore strangeness measurements with the meson prong not having dE/dx information. @ChiaraDeMartin95 and @ercolessi : this …

Improve strangeness builder preselectors

---

Common/TableProducer/trackselection.cxx

This PR just aims to dump at screen a few words to help the user understanding which global track selection set is used in the analysis. In particular:
-  some `LOG(info)` are added mentioning which function is called
-  a `LOG(warning)` is added for the case `itsMatching==0` and `isRun3==true`. By construction, since PR #1433 this configuration is equal to `itsMatching==1` and `isRun3==true`, but it was never explicitly mentioned.
Tagging @njacazio and @ChiaraDeMartin95 , just for their info

Add warning for global track selection setting.

---

EventFiltering/PWGJE/fullJetFilter.cxx
PWGJE/Tasks/FullJetTriggerQATask.cxx

If the jet finder produces jets of various radii, the jet trigger will only consider jets of a single radius (configurable, but should be 0.2).
The QA histograms have a jet R axis. This allows to check the trigger bias on jets of radii other than the one triggered on.

Jet trigger and QA now work for more jet radii

---

ALICE3/Tasks/CMakeLists.txt
ALICE3/Tasks/alice3-cdeuteron.cxx

This PR moves the existing ALICE 3 code to the new standalone DCAFitter library to avoid depending on DetectorsVertexing unnecessarily.

Move ALICE 3 to dedicated DCAFitter library

---

PWGHF/TableProducer/CMakeLists.txt
PWGHF/TableProducer/candidateCreator2Prong.cxx
PWGHF/TableProducer/candidateCreator3Prong.cxx
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateCreatorBplus.cxx
PWGHF/TableProducer/candidateCreatorCascade.cxx
PWGHF/TableProducer/candidateCreatorChic.cxx
PWGHF/TableProducer/candidateCreatorLb.cxx
PWGHF/TableProducer/candidateCreatorOmegac.cxx
PWGHF/TableProducer/candidateCreatorX.cxx
PWGHF/TableProducer/candidateCreatorXicc.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx
PWGHF/TableProducer/treeCreatorBplusToD0Pi.cxx
PWGHF/TableProducer/treeCreatorChicToJpsiGamma.cxx
PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
PWGHF/TableProducer/treeCreatorLbToLcPi.cxx
PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
PWGHF/TableProducer/treeCreatorXToJpsiPiPi.cxx
PWGHF/TableProducer/treeCreatorXiccToPKPiPi.cxx

* remove `ROOT::EG` as linked library from table builders (not necessary, not used) 
* fully remove `DetectorsVertexing` or `DCAFitter` dependency from tree creators, not used
* move to `DCAFitter` standalone library for those tasks that use the `DCAFitter`
* kept `DetectorsVertexing` dependency for the [trackIndexSkimCreator.cxx](https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/TableProducer/trackIndexSkimCreator.cxx), which uses seemingly `pvertexer` classes

PWGHF: Streamline HF library dependencies

---

PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx

* remove unnecessary links to DetectorsBase
* Move to linking DCAFitter dedicated library instead of DetectorsVertexing

PWGEM: streamline library linking

---

PWGDQ/Core/CMakeLists.txt
PWGDQ/Core/VarManager.h
PWGDQ/Tasks/CMakeLists.txt
PWGDQ/Tasks/v0selector.cxx

* remove unnecessary linking to DetectorsBase
* Move to link to DCAFitter standalone library instead of DetectorsVertexing to reduce memory consumption

PWGDQ: Streamline linked libraries

---

PWGDQ/Core/HistogramsLibrary.cxx

The current binning of the dimuon invariant mass is not able to see the improvement on the low mass resonances for the global matched MFT-MCH forward tracks. In order to see this effect I added one specific histogram with a bin size of 5 MeV/c2 instead of 20 MeV/c2 (for the general one).

PWGDQ: add histogram with finer binning for low mass dimuons

---

Scripts/find_dependencies.py

@ddobrigk 
This fix makes it possible to look for the tree name, which is what the O2 error reports.
**Rationale:**
For a table declared as:
```c++
DECLARE_SOA_TABLE(TableType, "AOD", "TreeName",
```
that cannot be found, O2 throws the error:
```
Couldn't get TTree "DF_<...>/O2treename ...
```
`TableType` appears in the field `binding` in the JSON file (with suffix `Extension` for extended tables), whereas `TreeName` appears in the field `description`.
**Note:**
If `TableType` and `TreeName` are different (modulo capitalisation), it is actually impossible to find the table producer by following the [instructions in the troubleshooting documentation](https://aliceo2group.github.io/analysis-framework/docs/troubleshooting/#tree-not-found), because the [automatically generated list of …

Find dependencies: Get description instead of binding.

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx

This seems to be a bug in which V0 index is written into the HfCascades table, because the wrong V0s are then picked up in the candidateCreatorCascade.
Compare to how the V0s are loaded in the candidateCreatorCascade:
https://github.com/AliceO2Group/O2Physics/blob/27d0817f4c5ea57083ed56b53c47fe66b3ac9ca1/PWGHF/TableProducer/candidateCreatorCascade.cxx#L111

PWGHF: bugfix for v0 indices in HfCascades

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

- changes DCA to PV to use PV from secondary decay and not from track; further studies required
- to follow tomorrow: remove completely the dependence from track propagator in Run 3 analysis + tuning

strangeness builder improvements

---

PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerMC.cxx

The information on ambiguous tracks belonging to a dimuon is not properly filled in the flat tables, since this is done when the condition "muonHasCov" is respected. At the same time the information on ambiguous tracks are set for muon only (without cov). The addition of a new process function for MuonWithCov fixes the issue

PWGDQ: fixing issue with ambiguous tracks for flat tables

---

PWGDQ/TableProducer/tableMakerMC.cxx
PWGDQ/Tasks/dqEfficiency.cxx
PWGDQ/Tasks/tableReader.cxx

-Writing collision timestamp in reduced event tables in tableMakerMC
-Fetching magnetic field from ccdb for propagation of tracks used in secondary vertexing

Fetching magnetic field from ccdb for propagation of tracks

---

PWGLF/TableProducer/lambdakzerobuilder.cxx

This PR adds a QA option for the `lambdakzerobuilder` such that it is able to bookkeep ITS cluster maps very flexibly, with fully customizable binning. Since these are 2D histograms that are heavy, they are only created in memory in case the option to QA is enabled (default: disabled, of course). To be tested further

add QA option (def false) for ITS clu map

---

Common/TableProducer/PID/CMakeLists.txt
Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCBase.cxx
Common/TableProducer/PID/pidTPCBase.h
Common/TableProducer/PID/pidTPCFull.cxx

@jezwilkinson @chiarazampolli @noferini @strogolo  here's my proposal of decoupling, we should add a dependency on o2-analysis-pid-tpc-base to both PID tasks, I tested it and it works, what do you think? We could also make sure that the value in the other table is picked up from the one of the TPC, of course it creates another dependency, I don't know if this is what we want

PID: Decouple multiplicity from TPC PID

---

EventFiltering/PWGHF/HFFilter.cxx
EventFiltering/PWGHF/HFFilterHelpers.h

Small fix to use a qt instead of pt axis for the Armenteros Podolanski plot. And also fixed the alpha ranges for the same plot.

update HFFilter for gammas

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx
PWGHF/TableProducer/trackToCollisionAssociator.cxx

- do not create histograms if the process function is not enabled
- fix name of flag for track preselection in track-to-collision-associator

PWGHF: apply minor adjustments

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/Tasks/tableReader.cxx

Rework pair cuts in SameEventPairing so that the case without any pair cuts is always calculated and filled.

PWGEM/DQ Rework Paircuts in TableReader, add reverse of phiV cut

---

CMakeLists.txt
Scripts/CMakeLists.txt

* since anyway only useful in alienv, they can now be run via ${O2PHYSICS_ROOT}/share/scripts/<script>.py --> no need to run from SOURCE dir (which is not well-defined)
* can be used via cvmfs --> GRID/Hyperloop

Install python scripts

---

PWGEM/PhotonMeson/DataModel/gammaTables.h
PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
PWGEM/PhotonMeson/TableProducer/gammaSelection.cxx
PWGEM/PhotonMeson/TableProducer/produceMesonCalo.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
PWGEM/PhotonMeson/Utils/gammaSelectionCuts.h

- gammaSelectionCuts.h:
- put sliceBy call outside of loop to reduce CPU time
- gammaTables.h:
- created combined namespace for calo clusters
- added pT dynamic column for EMCal which also support analysis of particles with mass
- renamed some namespaces to fit a common naming scheme and to easier to understand
- due to the renaming of some columns and some namespaces there are multiple changes over many files!

[PWGEM-8] PWGEM: Clean up of header files

---

DPG/Tasks/AOTTrack/qaEfficiency.cxx

Unfortunately, this PR requires many code changes though it intends to fix just a few things:
- added histograms for "all" = all selected particles together
- added histograms and efficiencies for primaries for eta and phi
- remove a few redundant brackets in `isInAcceptance()`
- allow variable binning (line 1003)
@ginnocen FYI

Add efficiencies for primaries and all particle species

---

EventFiltering/PWGCF/CFFilterAll.cxx
EventFiltering/PWGCF/CFFilterQA.cxx

Only keep trigger events, otherwise the event mixing is not working properly.

Bugfix FilterQA

---

PWGHF/TableProducer/candidateCreator2Prong.cxx
PWGHF/TableProducer/candidateCreator3Prong.cxx
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateCreatorBplus.cxx
PWGHF/TableProducer/candidateCreatorCascade.cxx
PWGHF/TableProducer/candidateCreatorChic.cxx
PWGHF/TableProducer/candidateCreatorLb.cxx
PWGHF/TableProducer/candidateCreatorToXiPi.cxx
PWGHF/TableProducer/candidateCreatorX.cxx
PWGHF/TableProducer/candidateCreatorXicc.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx

@vkucera I implemented what was discussed at the last HF O2 meeting. 
To not bloat the configuration too much, I have hardcoded the settings of the vertexer to the default minimisation (which is the chi2 one) everywhere unless for the `HfTrackIndexSkimCreator`, `HfCandidateCreator2Prong`, and `HfCandidateCreator3Prong` which could be used for further testing.

PWGHF: Move to using chi2 in vertexer

---

EventFiltering/filterTables.h
EventFiltering/selectBCRange.cxx

Hi @peressounko: your task was not read by the CEFP; now, it should be appropriately integrated.
Hi @pbuehler: this is not a solution, but at least the chain will not crash anymore. Whenever you have the proper fix, feel free to open the PR!

Fix EM integration and empty BC ranges

---

Common/TableProducer/PID/pidTPCBase.cxx

Reverts AliceO2Group/O2Physics#2061
the previous PR makes test with Run2 converted data fail, we will further investigate this during the week

Revert "PID: Using TrackExtra instead of tracks"

---

PWGJE/Tasks/CMakeLists.txt
PWGJE/Tasks/emcclustermonitor.cxx
PWGJE/Tasks/emctmmonitor.cxx

First step to seperate the track matching monitoring from the cluster monitoring to be independet of tracks in cluster monitor task.

[EMCAL-689] Seperate track matching monitor task from emcclustermonitor

---

PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx

- dirty fix to be able to use V0 from the V0finder in the Pi0EtaToGammaGamma.cxx
- pcm-qc currently not useable with this

[PWGEM-6] Quick fix for Pi0EtaToGammaGamma.cxx to use V0 from finder

---

PWGJE/Tasks/emctmmonitor.cxx

- Add configurables for the TPC PID NSigma ranges for electron signal and background and Pion signal used for electron rejection.

[EMCAL-689] Add configurable NSigma ranges

---

PWGJE/TableProducer/jetfinder.cxx

Option for ghost recalculation in the the GhostAreaSpec steered with Configurable
- 1: Ghosts recalculated for each ClusterSequenceArea
- Anything else (preferably 0): One set of ghosts used for all ClusterSequenceAreas

[PWGJE]: Add option for switching on/off ghost recalculation

---

Common/TableProducer/eventSelection.cxx

@mpuccio as discussed just now!
@ekryshen, this changes the evsel processRun3 to depend on TracksIU and not Tracks for the track counting. It will mean that the track propagation workflow isn't necessary at all in some cases (strangeness analyses etc). Please jump up in case I am missing something

depend on TracksIU in Run 3

---

EventFiltering/PWGCF/CFFilterQA.cxx

Configurable ConfKeepAllSelectedParticles also kept events that did not pass the event selection.

PWGCF: fix in FilterQA

---

EventFiltering/cefpTask.cxx
EventFiltering/filterTables.h
EventFiltering/selectBCRange.cxx

@pbuehler please have a look. I changed the code to be sure that we always include the original BC from `collision.foundBC_as<BCs>();` in the output range.
@strogolo I changed the final part of the CEFP, as the output tree was showing 0 globalBC.

Fix CEFP output and simplify the BC range selection

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/Core/HistogramsLibrary.cxx

PWGDQ: replace 6.3 by actual `2. * TMath::Pi()` in histogramLibrary
PWGEM: 
- Add Eta vs VtxZ histogram to kinematic output class
- Tighten tracking cuts for electron selection

PWGDQ/EM: Change 6.3 to 2*Pi; tighten dielectron track cuts

---

Common/Core/TrackSelectorPID.h
PWGHF/TableProducer/candidateSelectorBplusToD0Pi.cxx
PWGHF/TableProducer/candidateSelectorD0.cxx
PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
PWGHF/TableProducer/candidateSelectorLc.cxx
PWGHF/TableProducer/candidateSelectorLcMl.cxx
PWGHF/TableProducer/candidateSelectorToXiPi.cxx
PWGHF/TableProducer/candidateSelectorXicToPKPi.cxx
PWGHF/TableProducer/candidateSelectorXiccToPKPiPi.cxx
Tools/KFparticle/qaKFParticle.cxx

- Clarify by renaming `getStatusTrackPIDAll` to `getStatusTrackPIDTpcOrTof` and initialising `nSigma..Cond..` to `0` (which means disabled) instead of `±1000` (which means a completely open PID selection)
- Adding the D2H Run2 PID strategy: TpcAndTof or TPC only in case TOF not available (and vice versa when TPC not available) as `getStatusTrackPIDTpcAndTof`
@vkucera, what do you think?

PWGHF: Clarify and extend PID selections

---

PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx

Change the Combinations Policy to Full index policy in the same event process function of the pair-track-v0 task.
Note that previously, most of the pairs were lost because of the from index policy.
This change fixes that issue

CombinationsFullIndexPolicy in track-v0 task

---

PWGHF/TableProducer/candidateSelectorLcMl.cxx

Currently, it is enough to set activateQA=2 to get histograms, but setting 0/1 will be more intuitive.

PWGHF: Small fix of flag condition to save histograms in Lc ML selector

---

PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx

- updated PID section to use the new `TrackSelectorPID::getStatusTrackPIDTpcAndTof` introduced in #2109
- split standard and Bayesian PID into separate process functions `processWithStandardPID` and `processWithBayesPID`. This way, one does not have to run the task `o2-analysis-pid-bayes` when not using Bayesian PID (until now it always needs to be included).
- removed debug messages

PWGHF: updated PID in candidateSelectorLcToK0sP

---

PWGJE/Tasks/emctmmonitor.cxx

- Add electron and background A- and C-Side E/p plots to investigate A-/C-Side dependencies we currently see in Run3

[EMCAL-689] Add seperate A- and C-Side E/p plots

---

PWGDQ/Tasks/dqEfficiency.cxx

The histograms with the MC truth were empty because FIllTrack doesn't operate on the same variables used to fill the histograms for the MC truth. 
Also, in processDielectronKaonSkimmed `gkTrackFillMap` was changed to `gkTrackFillMapWithCov` to allow the reconstruction of the B+ decay vertex/

Fix wrong function to fill MC truth

---

PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/refitPvDummy.cxx

@vkucera this PR fixes the the bug spotted by @jgrosseo due to the introduction of the collision id in the tables produced in the track-index-skim-creator as a consequence of the development for the treatment of the ambiguous tracks.
In fact, in the Run2 converted data, the collision id is not present, hence it has to be added on the fly.

PWGHF: Define version 001 of track-index skim creator tables to fix Run2 validation

---

Common/CCDB/macros/upload_trigger_aliases_run3.C
Common/TableProducer/eventSelection.cxx
Common/Tasks/eventSelectionQa.cxx

* Workaround for triggerBC in apass2/3 (shifted by -294 bcs)
* Use TracksIU instead of Tracks in the evselQA
* latest macro for uploads of trigger aliases

Workaround for triggerBC in apass2/3

---

EventFiltering/PWGJE/fullJetFilter.cxx
EventFiltering/filterTables.h
PWGJE/TableProducer/jetfinder.cxx
PWGJE/Tasks/FullJetTriggerQATask.cxx

- Jet finder: Add cuts on
- Cluster energy
- Cluster time
- Cluster exoticity (default: true)
- Trigger task
- Add new tags for
- EMCAL readout
- Neutral jet trigger
- Low threshold gamma triggers
- Gamma trigger:
- Low and high thresholds
- Cluster and exoticity cut
- Setter for observable type pt or energy
- Jet trigger
- Settable jet type (full or neutral jet)
- QA task:
- Add status bits for new trigger flags
- Add histograms for low threshold for gamma trigger
- Settable observable type for clusters (energy or pt)

[EMCAL-903] Update gamma/jet trigger and EMCAL observables in jet finder

---

PWGJE/TableProducer/emcalCorrectionTask.cxx

- Add 6 configs for exotic cluster cuts:
1. logWeight - logarithmic weight for the cluster center of gravity calculation
2. exoticCellFraction - Good cell if fraction < 1-ecross/ecell
3. exoticCellDiffTime - If time of candidate to exotic and close cell is larger than exoticCellDiffTime (in ns), it must be noisy, set amp to 0
4. exoticCellMinAmplitude - Check for exotic only if amplitude is larger than this value
5. exoticCellInCrossMinAmplitude - Minimum energy of cells in cross, if lower not considered in cross
6. useWeightExotic - States if weights should be used for exotic cluster cut
- Related to this PR https://github.com/AliceO2Group/AliceO2/pull/10932 !

[EMCAL-688] [EMCAL-670] Add configs for exotic cluster check

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/Tasks/tableReader.cxx

**The purpose of this PR is to add FillDileptonTrackVertexing to the tableReader for the dileptonHadron-trask.** Main alterations is in this very same task (using the index of the legs to get the full track info of the electrons, in order to do the secondary vertexing, and to check that the hadron candidate is not the same as the legs). Therefore a secondary list DileptonsExtra is a parameter to dileptonHadron, and the covariance is added in order to do the secondary vertexing. I altered the default cuts used in the tableReader. The default cut cannot be empty as the hadron cut must be in the last bit, as the code is currently structured.

Secondary vertexing in dileptonHadron added to tableReader

---

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx

Can run now on non-skimmed data the pairing. Flag to pair only physical primary tracks to reduce CPUs.

Update of the efficiency task

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx
PWGHF/TableProducer/candidateSelectorLcMl.cxx
Tools/ML/model.cxx
Tools/ML/model.h

Hi @fcatalan92 @ChSonnabend 
Recently I developed a Lc selector that uses BDT models developed by Fabrizio. I used the ML framework, but I needed some adjustments for BDT:
- different output types, not only floats
- BDT has output values in tensor[1], not tensor[0]. Currently, my solution is to use the outputs from the last tensor in a vector. In case someone else will have a yet different model with different outputs, we can again make adjustments.
Let me know if the changes there are fine for you.

Ml model update

---

PWGCF/Tasks/correlations.cxx
PWGDQ/Tasks/tableReader.cxx
PWGHF/HFC/Tasks/taskFlow.cxx

This removes direct usage of `GroupSlicer` class in favor of `Preslice` declaration. Framework mechanisms for grouping will be updated to use caches and thus reduce time used for table slicing, however it will make direct usage of `GroupSlicer` more complicated and invalidate the current code. 
This _should_ produce identical behavior, however, the people responsible for this particular code should validate the change. This also will improve performance of the relevant tasks slightly.

Remove direct slicer uses

---

cmake/O2PhysicsAddHeaderOnlyLibrary.cmake
cmake/O2PhysicsAddLibrary.cmake
cmake/O2PhysicsLinkAllSubDirs.cmake

This gives the possibility to use include files which internally refer to the original directory structure.

Symlinks to reproduce the directory structure

---

EventFiltering/PWGJE/fullJetFilter.cxx

std::round prevents the configurable from being
evaluated at runtime, therefore always the default R
is selected.

[EMCAL-903] Change set R selection from float to int

---

PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx

Since one always has to have one process function active and in the Pi0Eta task there is the PCMQC task which currently had the VO table even in the dependencies of the dummy process function, one would have needed V0s even when just running the Pi0Eta task for calo.

[PWGEM-12] Reduce dummyProcess table subscription

---

EventFiltering/CMakeLists.txt

Update PUBLIC_LINK_LIBRARIES for EM filter to be used in the CEFP

Fix public link libraries for EM filter

---

PWGHF/D2H/Tasks/taskB0.cxx
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateSelectorB0ToDPi.cxx
PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx

Hey @fgrosa @iouribelikov  !
Here are the fixes applied to the B0 workflow, everything works (I get filled histograms in output of the execution command line) but there still might be some mistakes :)
One of the main modifications I applied to the candidate creator is removing the double loop on D+/D-: I now check the sign of `sign(D) * sign(Pi)` to only keep pairs that have opposite electric charge.
Also, the `processMc` functions work as well.
-----------------------------------------------------------------------------------------
List of fixes:
- `candidateSelectorDpluToPiKPi.cxx`
- modify PID selection (put in a function): TpcOrTof --> TpcAndTof + add configurable to accept PIDNotApplicable status (default value set to `true`)
- `candidateCreatorB0.cxx`
- [loop over D- & loop over …

PWGHF: Fix B0 workflow and modify PID selections in Dplus selector

---

DPG/Tasks/AOTTrack/qaMatchEff.cxx

1. write a unique template function to handle all the `process`;
2. add process functions with IU tracks.
CAVEAT: in the current version, the track-propagation workflow is still necessary, because the `makethn` is not `constexpr` and therefore the table `aod::TracksDCA` is always necessary. Use `minPropagationRadius==0` in this case.
POSSIBLE IMPROVEMENT: put `makethn` as a `constexpr` variable and add further process functions to enable the `THnSparse` filling.
---> not a priority now!
3. remove useless newlines (I hope no more are there);
4. fix some names;
5. switch TH1F to TH1D to avoid floating point issues;

[DPG]: updates on qaMatchEff.cxx

---

PWGJE/Tasks/emctmmonitor.cxx

- To get a cleaner sample the option to cut for cluster timing and a min M02 can now be used

[EMCAL-689] Add Option to filter cluster for timing and M02

---

Common/TableProducer/eventSelection.cxx

The issue is the following:
```
root [0] float n = 4.1e9
(float) 4.10000e+09f
root [1] float newN = n + 1.f
(float) 4.10000e+09f
root [2] newN - n
(float) 0.00000f
```
for large runs, this is happening systematically. With doubles this is still fine until 10e15
```
root [0] double n = 4.1e15
(double) 4.1000000e+15
root [1] double newN = n + 1.
(double) 4.1000000e+15
root [2] newN - n
(double) 1.0000000
```

Counters should use double

---

PWGHF/TableProducer/candidateCreatorB0.cxx

Hi @fgrosa ! Here is the new structure of the code:
- Loop over `aod::Collision const& collisions`
- Loop over D candidates associated to this collision
- Repropagate the daughter(s) to this collision if needed
- Propagate D daughters to D decay vertex and get `pVec` of these daughters at this vertex (previsouly, I was getting the impulsion of the `track0,1,2` and not the `pVec` values (modified by `getPxPyPz`). 
Is it better to call `getPxPyPz` (from [trackUtilities.h](https://github.com/AliceO2Group/O2Physics/blob/master/Common/Core/trackUtilities.h#L97)) or `getPxPyPzGlo` (from [TrackParametrization](https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/Reconstruction/src/TrackParametrization.cxx#L127)) ?
- Loop over tracks associated to this collision
- Propagate D and Pion …

PWGHF: Handle ambiguous tracks in B0 candidate creator and get bz from CCDB

---

PWGHF/D2H/Tasks/taskB0.cxx
PWGHF/TableProducer/candidateSelectorB0ToDPi.cxx
PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx

Hey @fgrosa @iouribelikov ! Here are the new modifications:
- Dplus and B0 selectors:
- add QA histograms filled if `activateQA` is set to `true` (`false` by default)
- follow issue #2257
- fix bug: the `flag` used to be defined outside the loop over candidates so it was not refreshed (set back to `0`) at each iteration
- B0 task:
- fill new histograms when B0 daughters are in acceptance (`isProngInAcceptance()` function added)

PWGHF: Add QA histograms in Dplus and B0 selectors, follow issue #2257 and add histograms for prongs in acceptance in B0 task

---

Common/Core/CMakeLists.txt
Common/Core/aodMerger.cxx
Common/Core/aodMerger.h
Common/Core/aodThinner.cxx

This tool reduces the AOD size by the following approach:
- Remove all TPC only tracks
- Remove all V0s which refer to any removed track
- Remove all cascade which refer to any removed V0
- Remove all ambiguous track entries which point to a track with collision
- Adjust all indices
Small changes to aod merger to have a common input header and some fixes in comments
(This is mainly work by @mmazzilli. I just did the final cleanup)

Introducing AOD thinner

---

PWGLF/DataModel/LFStrangenessTables.h
PWGLF/TableProducer/CMakeLists.txt
PWGLF/TableProducer/cascademcfinder.cxx
PWGLF/TableProducer/lambdakzeromcfinder.cxx

This PR adds the tasks `lambdakzeromcfinder` and `cascademcfinder` that re-reconstruct the V0 and Cascade index tables from MC, and then the *regular builder* (and even MC QC tasks such as the `straRecoStudy`) can be used fully transparently to build and study the pure-MC-index pairs or triplets. Since no track quality requirements whatsoever are applied to the index rebuilding, this will allow for a synthetic exercise in which the maximum attainable efficiency ('findable') is calculable at analysis level. N.B.: this does not take into account collision reconstruction efficiency.

MC finders for synthetic findable exercise 

---

Common/TableProducer/CMakeLists.txt
Common/TableProducer/caloLabelConverter.cxx

- Add caloLabelConverter task to convert McCaloLabels_000 to McCaloLabels_001 for backwards compatibility. The amplitude fraction which is new in McCaloLabels_001 will be initilised with 0 since we don't have that information in tge old McCaloLabels_000. This change is connected to https://github.com/AliceO2Group/AliceO2/pull/10670

[EMCAL-888] Add caloLabelConverter task

---

PWGLF/TableProducer/cascademcfinder.cxx
PWGLF/TableProducer/lambdakzeromcfinder.cxx

wasn't captured correctly due to CI check bug (thanks for pointing this out @aalkin !)

Fix clang compilation

---

DPG/Tasks/AOTTrack/qaEfficiency.cxx

Follow-up to the yesterday's discussion.
The original code doesn't work well in the case of negative particles / positive antiparticles like electrons/positrons.

DPG: Fix histogram index calculation

---

Common/DataModel/CollisionAssociation.h
Common/TableProducer/trackToCollisionAssociator.cxx

@jgrosseo I have reintroduced the possibility to enable the "reversed" table for ambiguous tracks (i.e. the one filled per track with an array of collision indices). Could you please have a look? Thanks!

Common: Restore table filled per track with vector of compatible collisions

---

PWGLF/DataModel/LFStrangenessTables.h
PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/cascadefinder.cxx
PWGLF/Tasks/cascadeanalysis.cxx
PWGLF/Tasks/cascadeanalysisMC.cxx

* creates a process function (disabled by default) that creates a tracked cascade table for posterior analysis 
* the tracked cascade table (`TraCascData`) is currently kept separate from the main cascade table (`CascData`) for development purposes - possibility to unify to be studied once development is more advanced 
* further testing pending

Strangeness tracking for cascade builders

---

PWGHF/Tasks/taskMcValidation.cxx

@fcatalan92 @jgrosseo I adapted this task to work with the "HF definition" of ambiguous tracks from the track-to-collision associator in view of the change of the ambiguous track table content in the AO2Ds. It depends on https://github.com/AliceO2Group/O2Physics/pull/2346

PWGHF: Adapt MC validation task to HF time-based definition of amb tracks

---

PWGJE/Tasks/CMakeLists.txt
PWGJE/Tasks/jetvalidationqa.cxx

Hi @nzardosh , @fkrizek, 
here is the basic jet-validation-qa task, performed on **global instead of hybrid tracks**. This should allow Filip to test the validation tools before I extend the task to handle MC from run2 (and run3 ?). I propose to change the cuts in AliPhysics accordingly, or to invite experts from tracks to a discussion to find a 'hybrid track solution' for ambiguous tracks in O2Physics. 
Cheerio,
Johanna

[PWGJE] Validation task for Jetfinder on run2 data

---

PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx

After updating O2 and O2Physics the ConfigurableAxis were crashing the task already at initialization of the histograms (I don't know why or what has changed that this is not working anymore). I replaced them for the time being by hard coded axes (as we had also in the Run2 cocktail analysis task) in order to have a running version for testing and also the O2 tutorial until I find out what's going on.

PWGEM: replace ConfigurableAxis with hard coded axes

---

PWGDQ/Core/CutsLibrary.cxx

I think the cut kaonPIDnsigma was mistakenly deleted since kaonPID still uses it. If kaonPID is applied the table-maker crashes. Restoring kaonPIDnsigma solves the problem.

Restore kaonPIDnsigma

---

PWGHF/TableProducer/treeCreatorChicToJpsiGamma.cxx
PWGHF/TableProducer/treeCreatorLbToLcPi.cxx
PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
PWGHF/TableProducer/treeCreatorXToJpsiPiPi.cxx
PWGHF/TableProducer/treeCreatorXiccToPKPiPi.cxx

PWGHF: Adding candidate/particle origin MC infos in the tree creators

---

PWGJE/TableProducer/emcalCorrectionTask.cxx

- Since the fIndexBCs_foundBC indedx is not sorted (anymore?) we need to make adjustments. Anton proposed to use soa::SmallGroups, however, we realised that this would not work with the current implementation. It needs an update, where you can specify by which index column it would be grouped. Also an update to the sliceBy function to handle unsorted indices is on the way. Until then I suggest to use this quick fix, so that we can still use the fIndexBCs_foundBC.

[EMCAL-670] Quick fix for unsorted fIndexBCs_foundBC

---

Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask4.cxx
Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask5.cxx

@ariedel-cern @victor-gonzalez I'm trying to remove the old API from O2, but it keeps appearing in O2Physics :) For the tutorial it definitely makes more sense to use the new API.

Tutorials: hotfix to use new API

---

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGEM/PhotonMeson/DataModel/gammaTables.h
PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
PWGEM/PhotonMeson/Tasks/pcmQC.cxx
PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson/Utils/MCUtilities.h

PWGEM/PhotonMeson: update MC analysis

PWGEM/PhotonMeson: update MC analysis

---

PWGLF/TableProducer/cascadebuilder.cxx

* this PR adds an option in which cascades that weren't tracked are skipped from processing. 
* this allows for a significant reduction in the overall CPU cost of the cascade building. 
* Potential improvement: redo V0s only if belonging to cascades that were tracked (coming soon)

Add option to process only tracked cascades

---

.clang-format

Configure clang-format to format JSON files like O2 would dump them, i.e. with 4-space indents. This way, we can track O2-generated JSON files in the repo directly, without having to reformat them.
Tested with an existing JSON file in the O2Physics repo; seems to work.
This came up in #2445.

Use O2-like 4-space indents in JSON files

---

Common/TableProducer/caloLabelConverter.cxx

**caloLabelConverter**:
- After some consideration we decided that we do not need the mask column in the McCaloLabel table so we dropped it. This commit is just to adapt the caloLabelConverter to this change in the table structure. As a starting point the filling will be commented out until the changes to the data structure are merged in O2.

[EMCAL-888] caloLabelConverter: Preparation for removal of mask column

---

PWGHF/TableProducer/candidateSelectorToXiPi.cxx

Only one deletion:
- remove nITSClusters selection on pi<-casc

PWGHF: remove nITSClusters selection on pi<-casc

---

PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx

Avoid having Error messages from GetRandom() each time a pT bin with an empty histogram is called (blows up the log file)

PWGEM: avoid Errors from GetRandom() for empty histograms

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx

Needed for urgent QA checks on new data.
The only potential problem that I see is that analysers should be warned to set also etaMinTrack2Prong/3Prong/Bach/V0Daug (depending on what objects they use) in their json files, otherwise the default values will be taken, and if they change the default eta cut by only modifying etaMaxTrack2Prong/3Prong/Bach/V0Daug (and only that) with respect to the default, the behavior will not be what they would expect.
I had tried to set the default min values to a specific unphysical value (-99999.), and then, in the init, set etaMinTrack2Prong to -etaMaxTrack2Prong in case the value of the min eta configurable is still -99999. (meaning that it was not set in the json), but it seems that a configurable cannot have its value reassigned at a later stage, with …

PWGHF: adding daughter track min/max eta selection

---

PWGDQ/Core/VarManager.h

Fix a typo in the calculation of the variable kQuadDCAsigXYZ.
The wrong covariance matrix index has been used. 
cZY instead of cYY

PWGDQ/EM VarManager.h: Fix typo in DCAxyz calculation

---

DPG/Tasks/AOTTrack/qaEventTrack.cxx

@mfaggin I added a TH3 for the check I showed at the last AOT-Track meeting. 
I decided not to modify `Tracks/TPC/tpcNClsFoundVsEta`, which now holds the same information as the new histogram, to avoid the need for post-processing to have the TPC cls vs eta plot. Let me know if you prefer the two histograms to be merged.

Add histogram for TPC checks vs vertex z

---

DPG/Tasks/AOTTrack/MonitorFilterBit.cxx

Fixing the overwriting of the histograms 'Tracks/RecoMCRad1mumto5mmCollMatch/histptFB4' and 'Tracks/RecoMCRad1to15cmCollMatch/histptFB4'.

[DPG/Tasks/AOTTrack]: Fix Typo in MonitorFilterBit.cxx

---

PWGJE/Tasks/jetvalidationqa.cxx

Hi @nzardosh , @fkrizek , @aimeric-landou (I could not tag the others),
here we have the updated jetvalidation.cxx with two structures that will allow us to split the work for the mc and data processes easily such that we can perform the validation on ESD's very independent of the ongoing developments for the mc analysis. We can also merge them in the future.
* The trackselection works just like for the jetfinder (we call the function from jetfinder.h for it) but please make sure to configure the hybridTracksJE for the jetfinder **and** jetvalidation when running on ESD's. Please avoid using them for processes that run on hyperloop (for now).
* There is a link for example configurables and run macros to help others getting started
* There is a long todo list from simple task to more …

[PWGJE Validation]: Implement configurable for hybrid trackselection, extension for run3 data and run2,run3 MC 

---

PWGHF/D2H/Tasks/taskD0.cxx

This PR just adds another control plot for the D0 invariant mass, needed for QA checks related to quality of alignment on Run3 data.

PWGHF: Add D0 phi vs invariant mass histogram

---

Common/CCDB/EventSelectionParams.h
Common/TableProducer/eventSelection.cxx
Common/Tasks/eventSelectionQa.cxx

* using maps for closest TVX or FT0-OR searches
* using TRD-matched and TOF-matched tracks for collision time estimate
* introduced selection on colliding bc pattern
* finetuned margins

Clean-up and finetuning of event selection

---

PWGLF/DataModel/LFHyperhelium4Tables.h
PWGLF/TableProducer/CMakeLists.txt
PWGLF/TableProducer/hyhe4builder.cxx
PWGLF/TableProducer/threebodymcfinder.cxx
PWGLF/Tasks/CMakeLists.txt
PWGLF/Tasks/hyhe4analysis.cxx

This PR adds work from Navneet Kumar, Natasha Sharma, Lokesh Kumar, and myself, who are studying the possibility of measuring double-hypernuclei going into hyperhelium-4 and then hyperhelium-4 into helium-3, proton and pion (see [PAG talk](https://indico.cern.ch/event/1187403/contributions/5025252/attachments/2506230/4306417/Double_HyperNuclei.pdf) as reference). The first step is to check for the 3-body decay of the hyperhelium-4, which is what the first tools provided here do. Having that in mind, this PR: 
- adds a three-body decay MC-based finder `threebodymcfinder` that, similarly to [what has been presented last week at the AOT Tracks](https://indico.cern.ch/event/1281698/contributions/5387798/attachments/2640630/4569917/Strangeness-Reco-04.pdf), re-creates the Decay3Body table with …

Adding code for Hyperhelium-4 study 

---

PWGJE/Tasks/emctmmonitor.cxx

- Add histograms for electrons and positrons separatly as well as positive and negative charged hadrons for the background estimation. From TPC side we expect a difference between electrons and positrons.

[EMCAL-689] Add E/p histograms depending on track charge

---

PWGEM/PhotonMeson/DataModel/gammaTables.h
PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx

- skimmed EMCal cluster table now includes variable sized array of track index and their eta, phi, p and pT values for track matching. The index can be used to comapre with V0 daughters and the other values were previously stored in an extra table. So with this change we can reduce the number of tables and need less sliceBy, Preslice stuff.

[PWGEM-8] Change skimmed EMCal data table to include vector of matched tracks

---

PWGDQ/TableProducer/tableMaker.cxx

This is a suggestion of additional processes to the DQ framework, following [this PR](https://github.com/AliceO2Group/O2Physics/pull/2525) implementing track-collision association for forward tracks. These processes use the output tables of the `fwdtrack-to-collision-associator` task.

[PWGDQ] Adding processes for muons based on fwdtrack-collision association tables

---

EventFiltering/PWGCF/CFFilterQA.cxx
PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/FemtoDreamCutculator.h
PWGCF/FemtoDream/FemtoDreamPairCleaner.h
PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/FemtoDreamV0Selection.h
PWGCF/FemtoDream/FemtoUtils.h
PWGCF/FemtoDream/femtoDreamCutCulator.cxx
PWGCF/FemtoDream/femtoDreamDebugTrack.cxx
PWGCF/FemtoDream/femtoDreamDebugV0.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTaskV0Only.cxx

This PR will fix the V0 selection for the pairTrackV0 task in FemtoDream. In particular,
- CutBit for the V0 itself is now functioning properly and
- the CutBit can now also be applied to the children of the V0 as well as PID cuts.
The selection of the V0s still needs a bit of work to allow for the systematic variations of the PID cuts. These will follow in a future PR. For now analysis can be performed with standard cuts on the PID of the V0 children.
This PR also contains clean-ups for the debug task and abstracts the creation of debug histograms into the designated class. Further cleanup will also follow in the future (espcially for configurables) as well as the merging of tasks. There are a several tasks that have a lot of copy-paste code that can be more elegantly handled with …

PWGCF: Fix V0 selection in FemtoDream

---

ALICE3/TableProducer/onTheFlyTOFPID.cxx

* this adds a calculation of analytical track length to a TOF layer, solving a problem that appears due to the ALICE track parametrization and leading to the following comparison between numerical (previous) and analytical values of track lengths (given here as an example for B = 2T and rTOF = 1m): 
```
Pt:	0.000	Length:	0.000000,	 analytical: -100.000000,	delta = -100.0000000000
Pt:	0.100	Length:	28.060884,	 analytical: -100.000000,	delta = -128.0608825684
Pt:	0.200	Length:	58.917965,	 analytical: -100.000000,	delta = -158.9179687500
Pt:	0.300	Length:	90.278923,	 analytical: 171.579880,	delta = 81.3009567261
Pt:	0.400	Length:	81.894432,	 analytical: 126.392189,	delta = 44.4977569580
Pt:	0.500	Length:	119.894913,	 analytical: 119.895638,	delta = 0.0007247925
Pt:	0.600	Length:	117.071625, …
```

Analytical length calculator added

---

ALICE3/TableProducer/onTheFlyTOFPID.cxx

* corrects a minor bug in which the inner TOF time resolution is used for the outer TOF resolution.  @hscheid this can't be why the outer TOF isn't great but it's still a bug...

Correct usage of time configurables - i/oTOF

---

PWGLF/Tasks/k1analysis.cxx
PWGLF/Tasks/k892analysis.cxx

Partition was introduced to have the same format as the event-mixing process.
But it's revealed that it uses too much CPU time, so I decided to avoid using it.

Add Light task not using partition

---

PWGHF/TableProducer/candidateSelectorD0.cxx

This PR fixes the issue with the max pT set for PID in the D0 selection, see e.g. selection efficiency (red) obtained by setting max pT=5 GeV/c:
In fact, in the previous version whenever one of the two track had pT > pTmax, the PID selection relied on the other track only. For example if it was supposed to be a kaon it was sufficient to be compatible with the pion hypothesis to be rejected, even if compatible with the kaon hypothesis. However, most of the kaons are compatible with pions and viceversa, especially if at high pT.
In general, the rejection of a kaon(pion) only based on the compatibility with pion(kaon) should be avoided, because it leads to drastic loss of efficiency (because pions and kaons are mostly overlapping, except for very low pT).

PWGHF: fix logic for D0 PID

---

PWGHF/D2H/TableProducer/candidateSelectorB0ToDPiReduced.cxx
PWGHF/DataModel/CandidateSelectionTables.h
PWGHF/TableProducer/candidateSelectorB0ToDPi.cxx

Hi @vkucera, I put the selection functions in `CandidateSelectionTables.h` (the same way the reconstruction functions are implemented in `CandidateReconstructionTables.h`).
Following issue #2594 .
------------------
Modifications applied:
- move `selectionTopol` and `selectionPID` to `CandidateSelectionTables.h` under `hf_sel_candidate_b0` namespace and add the required headers
- add arguments for the configurables of the tasks
- specific issue linked to `acceptPIDNotApplicable`. This is a boolean configurable, so the operators `!` and `&&` lead to compilation errors. Solution proposed: use `acceptPIDNotApplicable.value` of type `bool` as argument of `selectionPID`
- modify the code in `candidateSelectorB0ToDPi.cxx` to adapt it to the latest version (similar to the one of …

PWGHF: Factor out common functions used in B0 selectors

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/Tasks/filterPPwithAssociation.cxx

Fix in filterPPwithassociation :
-Fill Histograms correctly
-Replace BCsWithtimastamps with BCs to avoid segmentation fault breaks
Adding more Hight pT cuts for muons : 
- pT >8 Gev/c & pT>10 GeV/C added as muonHighPt4 and muonHighPt5 repectively
- pT > 20 GeV/c renamed as muonHighPt6

Fix in the filterPPWithassociation + More Cuts in the Library

---

Common/DataModel/TrackSelectionTables.h
Common/TableProducer/trackToCollisionAssociator.cxx
PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx

1. insert a new mask for Filters with only ITS quality cuts (useful for SigmaC soft pions)
2. configurable for track-selections in track-to-coll. associator (good also for other developments)
3. use re-associated tracks for SigmaC soft pions and add recalculation of dcaXY, dcaZ for reassigned tracks

PWGHF: update SigmaC creator and track-to-coll. associator.

---

PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx

Dear all,
I have implemented the event mixing for Ds-hadron correlations in Data and MCRec mode following the same done for the Dplus.
I see the commit "Implementation of Event Mixing for D+-hadron correlations" and I have already updated my code implementing some suggestions made on that commit. Let me know if there is something to change so this pull request can go ahead quickly.
Thanks in advance,
Best regards,
Samuele

PWGHF: Implementation of Event Mixing for Ds-hadrons correlations

---

PWGLF/Tasks/spectraTOF.cxx

Hey @njacazio,
this is the additional configurable to check for tracks with only TRD information. 
Cheers, 
Johanna

PWGLF: Adding 'TRD only' check for TOF

---

PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson/Core/EMCPhotonCut.h
PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
PWGEM/PhotonMeson/Utils/PairUtilities.h

PWGEM/PhotonMeson: re-activate EMC track matching veto
PWGEM/PhotonMeson: add v0leg-cluster matching
PWGEM/PhotonMeson: add cuts for PCM

PWGEM/PhotonMeson: update on 2 photon analyses

---

PWGLF/Tasks/spectraTOF.cxx

Hi @njacazio,
the changes to monitor the event time selection for TOF with and without TRD.
Here are the configurables for TRD only and no TRD, as well as the event time selection.
We also enabled the centrality histograms from FT0M and FT0A.
Cheers,
Johanna

[PWGLF]  spectraTOF: requirements for no TRD and evTime histograms 

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

* fixes a bug in which a `bool` is incorrectly typecast into a `char` in a `std::vector<char>` used for convenience (n.b.: `std::vector<bool>` does not behave like a normal array in C++)

Fix cast bug

---

PWGJE/Tasks/jetvalidationqa.cxx
PWGLF/Tasks/spectraTOF.cxx

Hello, @fkrizek, @nzardosh , @aimeric-landou  
I would like to **improve the jetvalidationqa (process for the validation on ESD's)** with the following changes:
- Configurables for filter and the axis of the histograms
- Filter on tracks and explicit association per collision (L. 195): **this step should be done for the MC struct as well** (together with the matching when someone finds the time).
The first point is rather for the beauty and flexibility of the code, the second point is crucial to reduce the abundance of tracks in the histograms. The changes been validated for the processESD() on converted run2 AOD's.
Cheers, 
Johanna

[PWGJE Validation]: Add filter, configurables and explicit track to collision association

---

EventFiltering/PWGLF/strangenessFilter.cxx
EventFiltering/filterTables.h

@mpuccio @lietava @strogolo 
As discussed at the Trigger Meeting on Friday this PR is to split the Omega trigger into standard and large decay radius one. The possibility to cut the standard omega sample for lower radii is also included.
The filterTable.h file was also modified to include an additional trigger please consider if any change is needed in the CEFP code.
This was tested locally will be tested on hyperloop when merged.
Cc: @ChiaraDeMartin95 @njacazio @alcaliva

Add Omega with high radius trigger

---

Tools/KFparticle/qaKFEventTrack.cxx
Tools/KFparticle/qaKFParticle.cxx
Tools/KFparticle/qaKFParticleLc.cxx

Fix event selection with sel8 trigger as filter:
Previously, the event selection was not working because a retrun was used. In the PR the event selection is replaced by a filter and the filtered events are passed to the process function. Like this, the event selection is always applied properly.
Also, the simple track selections are replaced by a filter.
@lupengzhong, @ddobrigk

Tools/KFparticle: Fix event selection

---

PWGHF/TableProducer/candidateCreatorBplus.cxx

Different options "UseAbsDCA" for the two vertexers:
B+  : set to true by default, false not compatible with V0 track
D0  : configurable

PWGHF: B+ creator, fix UseAbsDCA flags in vertexers

---

PWGHF/TableProducer/candidateSelectorToXiPi.cxx

- Require minimum tpcCrossedRowsOverFindableClustersRatio for the remaining tracks in candidateSelectorToXiPi and add the corresponding Fill statements in the QA histogram (and change histogram name)
- Add the absolute value to DCA selections in the candidateSelectorToXiPi

PWGHF: add quality cut for tracks, more fills for a QA histo, update selection ToXiPi task

---

Common/TableProducer/centralityTable.cxx
Common/TableProducer/multiplicityTable.cxx

* adds `reserve` statements to multiplicity and centrality tables 
* tested to be fine more carefully than last time!

Reserve memory beforehand

---

PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
PWGLF/Tasks/hStrangeCorrelation.cxx

* this PR separates the specific V0 and cascade correlations such that independent trains don't have the same workflow requirements. Specifically, this will make V0 trains lighter due to the absence of the cascade building.

Separate functions to alleviate memory issues

---

PWGDQ/Core/MCSignalLibrary.cxx

Bring some order to the defined signals in MCSignalLibrary.
separate into case  
- ElectronSignals: electron from Mother ... 
- DecaySignals: Mother with daughter electron ...

PWGEM: bookkeeping of electron and mu signals

---

PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/FemtoDreamContainer.h
PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

- The classification for the particle origin is now fixed and consistent with the implementation in AliPhysics: The differential DCA histogramms are filled only in case of correcly identified particles
- a fix in the producer tasks in order to correctly retrieve the magnetic field from the ccdb in case of anchored monte carlo. The flag "ConfForceGRP" needs to be set to "True", if one runs over unanchored MC (like e.g. LHC21k6_pp)
- added a new (and optional) histogram, to be used only in case of large statistics: it produces a histogramm with the axis k*, multiplicity and mT (with reduced binning). It is activated by setting the configurable "ConfUse3D" to true
@AntonRiedel

Fixes and new (optional) histogram

---

PWGHF/D2H/Tasks/taskBplus.cxx
PWGHF/TableProducer/candidateSelectorBplusToD0Pi.cxx

- candidateSelectorBPlus: PID compatibility D0 and pion. 
--> IsSelD0 in the B+ creator provides already the candidate with PID enabled
- taskBplus: minor changes

PWGHF: Fix PID compatibility B+ daughters

---

PWGHF/TableProducer/candidateSelectorD0.cxx

Useful to produce cut variable distributions for background, only exploiting candidates in the sideband region, in view of studying the optimal selection values.
Option activated via a dedicated configurable in the D0 selector, kept as false in the default configuration to preserve backward compatibility

PWGHF: adding option to select only background candidates on D0 data analysis

---

PWGDQ/Core/CutsLibrary.cxx

Adding the possibility to cut on the tracktype of muons
Create a special denomination for cuts used in the Central Event Filtering Task

Adding trackType to the Muon Cuts

---

PWGCF/FemtoWorld/Core/FemtoWorldPionContainer.h
PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskPionPion.cxx

femtoWorldPairTaskPionPionPion.cxx is changed, so that it not only works for pions of opposite charge, but also the same. Output is put in folders named according to event type and charges.

PWGCF: adding analysis of pairs of pions of the same charge

---

EventFiltering/PWGCF/CFFilterQA.cxx
PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/FemtoDreamCollisionSelection.h
PWGCF/FemtoDream/FemtoDreamContainer.h
PWGCF/FemtoDream/FemtoDreamCutculator.h
PWGCF/FemtoDream/FemtoDreamDetaDphiStar.h
PWGCF/FemtoDream/FemtoDreamEventHisto.h
PWGCF/FemtoDream/FemtoDreamMath.h
PWGCF/FemtoDream/FemtoDreamObjectSelection.h
PWGCF/FemtoDream/FemtoDreamPairCleaner.h
PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/FemtoDreamSelection.h
PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/FemtoDreamV0Selection.h
PWGCF/FemtoDream/FemtoUtils.h
PWGCF/FemtoDream/femtoDreamCutCulator.cxx
PWGCF/FemtoDream/femtoDreamDebugTrack.cxx
PWGCF/FemtoDream/femtoDreamDebugV0.cxx
PWGCF/FemtoDream/femtoDreamHashTask.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTaskV0Only.cxx

This PR contains several bug fixes of the FemtoDream framework:
- add missing |eta| cut on V0s
- replace LOG calls in CutCulator with std::cout. CutCulator is a standalone binary for generating bitmasks used by the tasks in femtodream. Using std::cout makes the output much easier to parse.
- Recent update to the MC code has broken the debug tasks. This will be fixed.
- The o2-aod-merger makes implicit assumptions on the table names since it is a standalone binary not part of the framework. As such all tables within femtodream had to be renamed to conform with o2-aod-merger.

PWGCF: bug fixes in femtodream

---

PWGDQ/Core/HistogramManager.cxx
PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGUD/Tasks/DGCandAnalyzer.cxx

* Ensures consistency with the rest of the messages.
* Allows for verbosity selection.
* Thread safe once we move to multithreading.
* Minor warnings fixes.

Use Framework Logger

---

PWGHF/Core/SelectorCuts.h
PWGHF/D2H/Tasks/taskB0.cxx
PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateSelectorB0ToDPi.cxx

Hey @iouribelikov @fgrosa !
Modifications:
- extra checks at MC reconstruction level
- sync `selectionFlagD` between B0 creator and selector
- add modifs that were implemented in the split worflow tasks

PWGHF: Add checks for B0 background in MC + sync selectionFlagD between B0 creator and selector

---

PWGJE/Tasks/jetvalidationqa.cxx

Hey @fkrizek and @GijsvWeelden,
Many thanks for your comments on the jetvalidation task ! I included the following changes.
For the **jetTrackCollisionQa** (Filip):
- all abs() are changed to fabs()
- the trackSelection check applies now also for the potential leading track
**-> This fixes the number of leading tracks.**
For the **mcJetTrackCollisionQa** (Gijs):
- the loop over detector and particle level jets are now in the .has_mcCollision() loop
- the 'fillMcTrackHistos' function got the collision as additional argument to do a track to collision association
- the jets themselves are now also associated with the collisionId/mcCollisionId 
**-> This fixes the over-counting of jets.**
Cheers, 
Johanna

[PWGJE Validation] Include track check for leading tracks in jetTrackCollisionQa and fix overcounting of jets in mcJetTrackCollisionQa 

---

PWGHF/D2H/Tasks/taskDs.cxx
PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/candidateCreator3Prong.cxx

This PR contains a flag to select Ds decay channel to be considered in 3Prongs MC Gen matching to be consistent with AliPhysics.
Three possible options available: 
1. flag = 0 -> Ds->PhiPi->KKPi, default (fig1)
2. flag = 1 -> Ds->K*0barK->KKPi (fig2)
3. flag = 2 -> Both (fig3)
[Flag_0.pdf](https://github.com/AliceO2Group/O2Physics/files/11488424/Flag_0.pdf) fig1
[Flag_1.pdf](https://github.com/AliceO2Group/O2Physics/files/11488426/Flag_1.pdf) fig2
[Flag_2.pdf](https://github.com/AliceO2Group/O2Physics/files/11488428/Flag_2.pdf) fig3

PWGHF: adding flag to select Ds decay channel in candidateCreator3Prong

---

PWGCF/FemtoDream/FemtoUtils.h
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

Remove unnecessary LOG calls in FemtoDreamProducer and FemtoUtils. Depending on the dataset, they can trigger a warning that the log file is too large.

PWGCF: Remove unnecessary logging in FemtoDream

---

PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx

Hi @fgrosa !
I added configurables to fill only signal or only (a fraction of) background.
For the MC part, I defined `Partition`s allowing to apply the `if` condition (`if (fillOnlySignal)` or `if (fillOnlyBackground)`) outside the loop over candidates.

PWGHF: fill only signal or background (fraction) in D+ tree creator

---

PWGJE/TableProducer/jetfinder.cxx
PWGJE/TableProducer/jetfinder.h
PWGJE/TableProducer/jetfinderhf.cxx
PWGJE/Tasks/jetvalidationqa.cxx

Hi @fkrizek, @archita-dash,
in order to get more jets for the comparison to AliPhysics I included a configurable for the event selection 7 (or 8 for run3). 
As we apply a jet-to-collision association we restricted the amount of jets in O2Physics to jets from collisions that passed the evSel7. Knowing that the Jetfinder from O2Physics does not use the evSel7 for run2 we should have the ability to consider collisions (and thus collision associated jets) with and without the sel7.
**Excluding the evSel7 leads to slightly (when tested on one single AOD.root) more jets in the jetvalidation output !** 
Lets hope that this PR gets merged soon such that we can make a proper comparison for the output with and without the evSel7.
Cheerio,
Johanna

[PWGJE Validation] Adding configurable for flexible usage of evSel7,8

---

PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx

PWGEM/PhotonMeson: add qc_w_mee cut
PWGEM/PhotonMeson: fill event QA histogram

PWGEM/PhotonMeson: fill event QA and add a cut

---

PWGLF/Tasks/hStrangeCorrelation.cxx

* fixes `kTH2F` -> `kTH3F` bug 
* adds a switch that allows for the `THnF` objects to not store under and overflow. Estimated reduction in memory consumption is of about a factor 2. This is a hack, and it should actually be implemented as a bool option in the main `THn` implementation in ROOT. But in the meantime, this should do the trick...

Bugfix, improvements

---

PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
PWGLF/Tasks/hStrangeCorrelation.cxx

* fixes a bug in the binning definitions of the THnF objects (in both no-overflow and regular-overflow modes) 
* adds a parametric cut on DCAxy for both trigger and associated pions

DCAxy selection, bugfixes

---

PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
PWGLF/Tasks/hStrangeCorrelation.cxx

Required for fully consistent, transparent no-under/overflow expansion later

Add THnF axes for reference

---

PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
PWGHF/TableProducer/candidateCreator2Prong.cxx
PWGHF/TableProducer/candidateCreator3Prong.cxx
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateCreatorBplus.cxx
PWGHF/TableProducer/candidateCreatorCascade.cxx
PWGHF/TableProducer/candidateCreatorToXiPi.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx
PWGHF/Utils/utilsBfieldCCDB.h

@vkucera @fcolamar @ginnocen this PR removes the unnecessary load of the geometry, which should also allow us to reduce by a good amount the memory usage on hyperloop.

PWGHF: Remove TGeo load from HF creators

---

Common/Core/CollisionAssociation.h

Without it only works if the passed argument is a reference itself

Add missing references

---

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGEM/PhotonMeson/Core/HistogramsLibrary.h
PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/PhotonMeson/Tasks/pcmQC.cxx
PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx

move pcm QC histograms to fillhistoclass

PWGEM/PhotonMeson: move pcm QC histograms to fillhistoclass

---

Common/Core/aodMerger.cxx

This will prevent the creation of huge parent files maps in the case of
slimmed derived dataset creation

Optionally skip the creation of parent files list

---

PWGLF/DataModel/LFHStrangeCorrelationTables.h
PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
PWGLF/Tasks/hStrangeCorrelation.cxx

* adds a cospa selection dedicated to lambdas, to make it such that a tighter cut is allowed (Run 2 used 0.995 for lambdas, 0.97 for K0) 
* adds QA plots that will allow for quick'n'dirty spectra extraction (**NOT** a replacement for a full spectrum analysis for sure) but just meant to check if candidates coming in as potential associated are reasonable and consistent with expectations

Add lambda cospa, add QA spectra

---

PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx

Dear all, 
I have found out an error regarding the table used to run over the candidates in MCRec process of the correlatorDsHadrons. Before I selected all Ds with a flagDs = 1, 5 or 7; now I use a table where the Ds selected are all with a flagDs = 7.
Samuele

PWGHF: Fix the error of using a wrong table in MCRec for Ds-h correlations

---

ALICE3/Core/DelphesO2TrackSmearer.cxx
ALICE3/Core/DelphesO2TrackSmearer.h
ALICE3/DataModel/OTFTOF.h
ALICE3/TableProducer/onTheFlyTOFPID.cxx
ALICE3/TableProducer/onTheFlyTracker.cxx
ALICE3/Tasks/alice3-dilepton.cxx

A couple of commits to:
* Get eta and pt resolution from TrackSmearer
* Fix some inconsistencies in variable naming
* Add QA histograms for OTF TOF

Add getters for pt/eta res in track smearer

---

PWGLF/TableProducer/cascademcfinder.cxx
PWGLF/TableProducer/lambdakzeromcfinder.cxx

* adds a broad `y` preselection + a pdg code preselection to MC-finder for better CPU efficiency. Both selections done declaratively with arrow `Filter` declarations.

Declarative filter for mc finder speed

---

PWGHF/D2H/Tasks/taskB0.cxx
PWGHF/D2H/Tasks/taskB0Reduced.cxx
PWGHF/D2H/Tasks/taskBplus.cxx
PWGHF/D2H/Tasks/taskD0.cxx
PWGHF/D2H/Tasks/taskDplus.cxx
PWGHF/D2H/Tasks/taskDs.cxx
PWGHF/D2H/Tasks/taskLb.cxx
PWGHF/D2H/Tasks/taskLc.cxx
PWGHF/D2H/Tasks/taskXic.cxx

In general, the cut on generated and reconstructed rapidity might be different for efficiency calculation. In particular, if `-1` is set (no cut) it has a much different (and maybe undesired) effect on reconstructed (limited by acceptance anyway) and generated (limited by the MC settings)

PWGHF: split configurable for generated and reconstructed rapidity cut

---

PWGCF/FemtoDream/FemtoDreamCutculator.h
PWGCF/FemtoDream/FemtoDreamObjectSelection.h
PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/FemtoDreamSelection.h
PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/FemtoUtils.h
PWGCF/FemtoDream/femtoDreamCutCulator.cxx
PWGCF/FemtoDream/femtoDreamDebugTrack.cxx
PWGCF/FemtoDream/femtoDreamDebugV0.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

Fixes contained in this PR:
- Standardized the naming of configurables (i.e. proper namespaces) such that the configurables for certain track types are close to each other in the HY interface
- Systematical variations of PID selections for Tracks are now working regardless of the selected Nsigma values 
- Adjust binning for certain QA histograms

PWGCF: Bugfix Femtodream

---

Tools/KFparticle/qaKFEventTrack.cxx
Tools/KFparticle/qaKFParticle.cxx
Tools/KFparticle/qaKFParticleLc.cxx

These instances of TGeoManager load seem unnecessary - @lupengzhong , can you please take a look? It seems that the material LUT is loaded right on top, and the `matCorr` is set to be material LUT and the TGeo is never used. Please note that not loading the TGeo saves about 250MB of memory.

remove unnecessary TGeo load

---

PWGDQ/Core/CutsLibrary.cxx

Introduce new PID cuts, using post calibration variables.
@dsekihat Could you please have a look. Thank you.

PWGEM: adding new dielectron PID cuts using post calibration

---

Common/TableProducer/centralityTable.cxx

@ChiaraDeMartin95 @nepeivodaRS @mfaggin @strogolo @ekryshen this adds an option to embed the inel > 0 selection automatically in the evaluation of percentiles, such that events not satisfying the selection will be assigned percentile 100.5 and will therefore be out of range for analysis. Note: defaults to false currently!

embed INELgtZERO sel if requested

---

EventFiltering/PWGHF/HFFilter.cxx
EventFiltering/PWGHF/HFFilterHelpers.h
EventFiltering/PWGHF/HFFilterQC.cxx
EventFiltering/filterTables.h

This PR was implemented with @ZFederica. It adds:
- triggers for charm baryon --> Xi + Pi/K
- reorganisation of configurables to avoid hitting the limit of data members

EventFiltering: add charm-baryon triggers and reorganise configurables

---

PWGLF/TableProducer/lambdakzeromcfinder.cxx

* creates a new path for MC finding for findable exercises, such that desired MC particles are found starting from the prongs (as done in e.g. Run 2). Significantly faster than sweeping all MC particles, considering that a PoI must have left at least one prong for the search procedure to even really begin. Starts with partitioned positive/negative tracks. 
* Old `mcParticle`-based method kept for legacy and cross-checking for now (in separate process function).

MC finder optimization

---

PWGHF/TableProducer/candidateCreatorToXiPi.cxx
PWGHF/TableProducer/candidateSelectorToXiPi.cxx

- remove comparison index cascade-index track pi <- charm (wrong) in creator
- implement check on different index when filling saved events histogram (selector)

PWGHF: change indexes in toXiPi tasks

---

Common/Tasks/multiplicityQa.cxx

* adds a number of QA plots and better configurability to the multiplicity QA task
* allows for checking number of reconstructed PVs vs multiplicity in MC 
* allows for switching the check from equalized to non-equalized quantities

Mult QA: add process function for event studies at low mult

---

PWGHF/HFC/Tasks/taskCorrelationDMesonPairs.cxx

I added a set of THnSparse's with a finer binning for mass correlations, and fixed histogram titles to make them more readeable when the pair is not D-Dbar.

PWGHF: add FinerBinning hists and fix hist titles on taskCorrelationDMesonPairs

---

PWGHF/TableProducer/candidateCreator2Prong.cxx
PWGHF/TableProducer/candidateCreator3Prong.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx

This PR allows us to not fill and to not process the tables filled with the PV refit information if the feature is not enabled. This implies a reduction of the memory used and it avoids to process these tables in the 2-prong and 3-prong creators (and consequently it is not needed to write the PV refit tables on disk if the derived AO2Ds containing the track-index-skim-creator tables are produced), if the PV refit is not enabled. 
To achieve it, I had to templatise the process functions of the track-index-skim and the 2-prong and 3-prong creators. This means that the current `doPvRefit` configurable will be replaced by several `PROCESS_SWITCH` (i.e. `processPvRefit` and `processNoPvRefit`).
I still have to complete the tests, but @mfaggin and @vkucera @fcolamar @ginnocen you can start …

PWGHF: avoid production and subscription of PVrefit tables if not enabled

---

PWGHF/TableProducer/candidateCreator2Prong.cxx
PWGHF/TableProducer/candidateCreator3Prong.cxx

@vkucera I unfortunately noticed only now that the default values of the `PROCESS_SWITCH` were not properly set in my previous PR https://github.com/AliceO2Group/O2Physics/pull/2878. It's not a big issue since they are anyway configurables, but it would be good to have the correct default values to avoid to cause troubles to users.

PWGHF: set appropriately default configurables for PV refit and add protection

---

PWGCF/Tasks/dptdptcorrelations.cxx

Matching the post-processing when unidentified

First step towards the identified analysis

---

ALICE3/DataModel/A3DecayFinderTables.h
ALICE3/TableProducer/alice3-decayfinder.cxx

End-of-the-week working point for ALICE 3 otf analysis chain. Includes:
* adds a fully customizable, per-prong, pT-dependent DCAxy selection in the decay daughter track preselection device
* adds a second process function to the finder device to look for three-prong decays
* ...more to follow

Working point for a3 otf sim analysis

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx
Common/Tools/handleParamBase.h
Common/Tools/handleParamTPCResponse.cxx

Adding support for TPC parameter handler + response tasks to save/request specific pass number for multiple objects with same name.
New features:
- Task will now correctly print the used parameters after loading the object from CCDB (previously: would only report the parameters from the default object)
- Able to load specific object with different pass name for same path + timestamp (default behaviour unchanged: will load the latest uploaded object for the timestamp if "passname" configurable unspecified)
Plan to change default behaviour in future to automatically determine pass name, when pulling from AO2D metadata is available

Add metadata handling for TPCResponse CCDB objects

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx

A "has_collision()" check was moved in https://github.com/AliceO2Group/O2Physics/pull/2923/ and stopped protecting the bc() call for tracks without associated collision. This commit should fix the issue

fix has_collision() protection on TPC response

---

PWGCF/FemtoWorld/Core/FemtoWorldCollisionSelection.h
PWGCF/FemtoWorld/Tasks/CMakeLists.txt
PWGCF/FemtoWorld/Tasks/femtoWorldEfficiencyTask.cxx

Adding possibility to calculate efficiencies for pions, kaons, and protons in Femto World

FemtoWorld: adding Efficiency Task

---

PWGEM/Dilepton/Tasks/MCtemplates.cxx

Using the MC truth informations again on pair level, after improving the MC signal selection.

PWGEM: Reintroduce runMCGen after fixes in MCSignal.h

---

PWGLF/DataModel/spectraTOF.h
PWGLF/TableProducer/spectraDerivedMaker.cxx
PWGLF/Tasks/spectraTOF.cxx

Hi @njacazio ,
here are two additional configurables to select a certain eta range for the analysis and the modification for the nsigmaTPCTOF to use the THnSparse. 
Let me know if I should change something (or add more to the task).
Best,
Johanna

[PWGLF] Configurables for eta range selection and THnSparse in spectarTOF.cxx

---

PWGDQ/Core/MCSignal.h
PWGDQ/Core/MCSignalLibrary.cxx

Implented functionallity to check the Signal also "In Time".
Before only the mother were selected and looped over.
Now also the daughter loop is implemented.

PWGEM/DQ: Add same pdgInHistory functionality for InTime Signal

---

ALICE3/Tasks/alice3-lutmaker.cxx

@njacazio this is definitely a minimal change that we need to add for code safety...  but on top of that, maybe for Run 3 LUT stuff, we should do a minimum crossed rows selection and so on?

Add has_mcParticle check to LUT maker

---

PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/FemtoDreamCollisionSelection.h
PWGCF/FemtoDream/FemtoDreamObjectSelection.h
PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/FemtoDreamSelection.h
PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/FemtoDreamV0Selection.h
PWGCF/FemtoDream/FemtoUtils.h
PWGCF/FemtoDream/femtoDreamDebugTrack.cxx
PWGCF/FemtoDream/femtoDreamDebugV0.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTaskV0Only.cxx

Changes in this PR:
- Add a cutcounter to the FemtoDreamProducer task that keeps track of the number of particles cut by each specified cut as well as its variations
- Add several configurables to the DebugTasks to change the binning of histograms used for a data-driven purity estimation
- Change the subscription of the FemtoDreamProducerTask to the full PID helper tasks for TPC and TOF. With the normal helper task, only nSigma values of up to +/- 6.35 were given. With the full helper task arbitrarily large values can be computed, which is necessary for the data-driven estimation of purities.
- Change the behavior of the FemtoDreamProducerTask to not store collision in which there are no tracks/V0 that do not fulfill the loosest configuration of the specified cuts.

PWGCF: Update Femtodream

---

Common/DataModel/EventSelection.h
Common/TableProducer/eventSelection.cxx
Common/Tasks/eventSelectionQa.cxx
PWGUD/Tasks/diffMCDataScanner.cxx
PWGUD/Tasks/upcAnalysis.cxx
PWGUD/Tasks/upcForward.cxx
Tutorials/Skimming/spectraUPCProvider.cxx
Tutorials/Skimming/spectraUPCReference.cxx

1. Removed redundant and unused columns from bcsel and evsel tables:
evsel::BBV0A, evsel::BBV0C, evsel::BGV0A, evsel::BGV0C,
evsel::BBFDA, evsel::BBFDC, evsel::BGFDA, evsel::BGFDC,
evsel::MultRingV0A, evsel::MultRingV0C, evsel::SpdClusters, evsel::NTracklets
2. EvselQA and UD-related tasks are updated. Instead of bb and bg flags, using:
bool checkV0 = col.selection_bit(kIsBBV0A) || col.selection_bit(kIsBBV0C) || !col.selection_bit(kNoBGV0A) || !col.selection_bit(kNoBGV0C);
bool checkFDD = col.selection_bit(kIsBBFDA) || col.selection_bit(kIsBBFDC) || !col.selection_bit(kNoBGFDA) || !col.selection_bit(kNoBGFDC);
2. Protection against empty FT0 table

Reduce evsel and bcsel table contents

---

Common/Core/CMakeLists.txt

This was working so far only accidentally, since most tasks are pulling in the library via other dependencies, while other tasks were ok with only the header present, which is present in any case from the O2 installation.

O2Physics tasks use GRP, so pull in the library

---

PWGCF/FemtoUniverse/Core/FemtoUniverseObjectSelection.h
PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
PWGCF/FemtoUniverse/Core/FemtoUniversePhiSelection.h
PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx

* Adding the option to store Phi mesons in the FemtoAOD.root data for the FemtoUniverse. 
* Adding the track-phi task for FemtoUniverse.
In the next PR:  
* enable storage of Phi will be in the process switch (because not everyone will need them, so we don't want to save them),
* check selection for the tracks, now only PID is working, I would like to use setSelection (like in the FemtoUniverse).

PWGCF: FemtoUniverse - adding phi to the producer and creating a track-phi task

---

PWGHF/TableProducer/treeCreatorXicToPKPi.cxx

- `BCId` and `NumContrib` columns are removed from tables similar to the `treeCreatorLcToPKPi.cxx` task

PWGHF: Remove `BCId` and `NumContrib` columns from `treeCreatorXicToPKPi` 

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

This PR: 
* adds the possibility of selecting on a specific mother PDG for the MC-associated V0 and cascade building. It is potentially useful, for instance, for building only Lambdas that are truly (in the MC assoc sense) from Xi, K0 from a LambdaC decay, Xi/Omega from a XiC/OmegaC decay, and so on. 
* adds some extra QA histograms for both V0s and cascades.

Add PDG-of-mother option + QA

---

ALICE3/TableProducer/onTheFlyTOFPID.cxx
ALICE3/TableProducer/onTheFlyTracker.cxx
ALICE3/Tasks/alice3-qa-singleparticle.cxx
Common/Tasks/multiplicityQa.cxx
PWGCF/TableProducer/filterCorrelations.cxx
PWGJE/TableProducer/jetfinder.cxx
PWGJE/TableProducer/jetfinderhf.cxx
PWGJE/Tasks/jetsubstructurehf.cxx
PWGLF/TableProducer/cascqaanalysis.cxx
PWGLF/Tasks/spectraCharged.cxx
PWGMM/Mult/Tasks/dndeta-hi.cxx
PWGMM/Mult/Tasks/dndeta-mft.cxx
PWGMM/Mult/Tasks/dndeta.cxx
PWGMM/Mult/Tasks/effpt-mft.cxx
PWGMM/Mult/Tasks/run2dndeta.cxx
PWGMM/UE/Tasks/uecharged.cxx
Tutorials/src/mcHistograms.cxx
Tutorials/src/usingPDGService.cxx

This is a preparation for including the `o2::O2DatabasePDG::Mass` function in the `o2::framework::O2DatabasePDG` service.
It has to be merged first, to avoid the `template argument 1 is invalid` error.

Make O2DatabasePDG service class unambiguous

---

EventFiltering/PWGJE/fullJetFilter.cxx
PWGJE/Tasks/FullJetTriggerQATask.cxx

- Print info message with thresholds (once) based on hardware trigger setup
- Add histogram for max. cluster / jet in the filter
- Fix histogram in QA tasks which were not filled

[EMCAL-850] Update monitoring in filter and info messages

---

PWGJE/TableProducer/jetmatching.cxx

The jet matcher was flooding the log with info messages that are more suitable for debug mode.

Changed log messages from info to debug so log file is not too large

---

PWGHF/TableProducer/candidateCreatorCascade.cxx

Bug fix for finding generated $\Lambda_c^+\to pK^0_S$ and $\Lambda_c^- \to \bar{p}K^0_S$.  Currently $\Lambda_c^-$ are missed because the flag `acceptAntiParticles` in `RecoDecay::isMatchedMCGen` does not work for the $K^0_S$ (does not have an antiparticle, so the PDG code -310 that `RecoDecay::isMatchedMCGen` is looking for in that case does not exist, such that no $\Lambda_c^-$ is ever accepted)

PWGHF: candidateCreatorCascade: fix McGen

---

PWGCF/FemtoWorld/TableProducer/femtoWorldProducerTask.cxx
PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskTrackD0.cxx

Changes in the femtoWorldProducerTask.cxx and femtoWorldPairTaskTrackD0.cxx.
Functionalities in the producer: one can store only tracks, track and V0s, tracks and phi mesons or tracks and D0 mesons.
Functionalities about centrality kept: one can choose to run over Run2 or Run3 data.

PWGCF: FemtoWorld - D0 analysis - corrected producer

---

ALICE3/TableProducer/onTheFlyTracker.cxx

+cleanups
@ddobrigk change in line 354 should prevent crashes in vertexing that happened due to track times reaching float upper limit.

ALICE3: Fix onTheFlyTracker collision time sampling

---

PWGHF/ALICE3/TableProducer/treeCreatorChicToJpsiGamma.cxx
PWGHF/ALICE3/TableProducer/treeCreatorXToJpsiPiPi.cxx
PWGHF/TableProducer/treeCreatorB0ToDPi.cxx
PWGHF/TableProducer/treeCreatorBplusToD0Pi.cxx
PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx
PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
PWGHF/TableProducer/treeCreatorLbToLcPi.cxx
PWGHF/TableProducer/treeCreatorLcToK0sP.cxx
PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
PWGHF/TableProducer/treeCreatorToXiPi.cxx
PWGHF/TableProducer/treeCreatorXicToPKPi.cxx
PWGHF/TableProducer/treeCreatorXiccToPKPiPi.cxx

This PR includes:
- improvements in the D0 tree creator including the possibility to store a "lite" tree for ML trainings (similar to the D+ one)
- fix of tree creator table names (the previous ones should not work with the AOD merger)

PWGHF: Improve tree creator for D0 mesons and fix table names of tree creators

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx

refinements to TPC and TPCFull table producers:
- Adds ability to skip TPC-only tracks in NN application
- Skip tracks with missing TPC in NN application (and fix to fill table with -999 for invalid tracks as expected)
- minor bugfix in accessing NCl normalisation for NN
- Soft fallback with warning in case specific pass requested but not available (will be used with metadata access)

TPC PID: add compatibility with "skipTPCOnly" option for TPC PID NN application

---

PWGJE/Tasks/jetfragmentation.cxx

Added eta cuts for jets so we can turn off fiducial cuts in the jet finder. Allows for better matching between particle and detector level jets.

[PWGJE] Jet Fragmentation: add eta cuts for jets

---

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx

Done: 
* Phi meson cuts,
* removing (temporarily TOF from PID) in track-Phi.

PWGCF: FemtoUniverse -- PID without TOF and Phi cuts

---

Common/Core/RecoDecay.h

RecoDecay: Add message about deprecating getMassPDG

---

PWGLF/DataModel/LFStrangenessTables.h
PWGLF/TableProducer/CMakeLists.txt
PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/Tasks/QC/CMakeLists.txt
PWGLF/Tasks/QC/kfPerformanceStudy.cxx

* will allow for extensive testing with larger statistics 
* `CascData` kept unmodified; `KFCascData` provided in case KF particle path requested 
* KF particle path does *not* require the `lambdakzerobuilder` since lambdas are re-built using the exact case-by-case constraint from the bachelor. 
* Simultaneous generation of `CascData` and `KFCascData` is possible; `Linked` tables provide cross-referencing between base `Cascades` table and the `CascData` and `KFCascData` analysis tables for convenient access and comparisons (see example QC task `kfPerformanceStudy`). 
* to follow: adjustments and optimizations + similar path also for V0s in the `lambdakzerobuilder`

add KF particle cascade builder path

---

EventFiltering/PWGJE/fullJetFilter.cxx
EventFiltering/filterTables.h
PWGJE/Tasks/FullJetTriggerQATask.cxx

- Add very low gamma threshold on-min. bias triggered
events to bridge to Level-0 trigger
- Add very high gamma threshold to inspect the full
integrated luminosity (mostly Level-0, negligible
impact on min. bias)
- Enable both triggers only on trigger-like runs
- Add dedicated QA histograms for new triggers
- Add dedicated QA histograms for min. bias and
Level-0 hardware triggers
- Remove redundant 2D histograms

[EMCAL-903] Add support for 2 more gamma triggers

---

PWGHF/ALICE3/TableProducer/candidateCreatorChic.cxx
PWGHF/ALICE3/TableProducer/candidateCreatorX.cxx
PWGHF/D2H/TableProducer/dataCreatorD0PiReduced.cxx
PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateCreatorBplus.cxx
PWGHF/TableProducer/candidateCreatorCascade.cxx
PWGHF/TableProducer/candidateCreatorLb.cxx
PWGHF/TableProducer/candidateCreatorXicc.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx

O2 [PR11713](https://github.com/AliceO2Group/AliceO2/pull/11713) splits V0 and Cascades classes to separate physics (kinematics) and indices (of prongs and PV) classes. Therefore, the dummy prondID indices passed to the V0 constructor in O2Physics should be suppressed

Fix obsolete V0 c-tor folling O2 PR11713

---

PWGDQ/Core/CutsLibrary.cxx

I have reworked the existing cut settings.
Using a for loop to define Cuts equally for post calibration and without.
All cuts are now available for both versions.

PWGEM: Rework existing cut settings to be available with/out post calibration correction

---

PWGCF/TwoParticleCorrelations/Core/CMakeLists.txt

Without this, it's not clear to me how one can avoid the error about the missing DptDptBinningCuts dictionary.

Make sure PWCCFCore is available to TwoParticleCorrelations

---

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx

FemtoUniverse: TrackTrackTask
- fix in charge selection (now works with json configurables)
- adding pT selection at the task level for both tracks
FemtoUniverse: Producer
- processMC false by default

PWGCF: FemtoUniverse - fix in charge selection

---

EventFiltering/filterTables.h

@vfeuilla: when changing the filter task is essential to change it here as well, otherwise the CEFP will ignore the presence of the DQ filters in the chain

Change DQ filter task name in the filter tables

---

PWGDQ/Core/CutsLibrary.cxx

Add cut with Tighter PID (|nsigma| < 3.0) and sharper pIN cut (pIN > 1.2) for electrons for Trigger Selection

Add cut for electrons for Trigger selection

---

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx

PWGCF: FemtoUniverse:
In the TrackTrackTask:
Particle swapping when creating the pairs (p1, p2) <-> (p2, p1).
Also adding a comment with information about the particle codes in producer.

PWGCF: FemtoUniverse - TrackTrackTask part swapping in pairs

---

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx

* Setting global tracks (using filters) to reduce the number of processed pairs.
* Setting custom cuts (using filters and configurables).

PWGCF: FemtoUniverse -- Add global track filter + custom filter (with configurables)

---

PWGHF/Core/SelectorCuts.h
PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/trackIndexSkimCreator.cxx

Hi @deependra170598, @skundu692, @fcatalan92, @vkucera, @lvermunt,
This PR implements the possibility to produce the table with daughter indices for D* candidates. In particular, the indices of the soft pion and the D0 daughter are stored.
The track selection for the soft pion is independent of the other tracks. In particular, it allows us to use also ITS-standalone tracks, set a lower pT threshold, and to set a different DCA cut (typically only upper values to remove secondaries from material and strangeness).
The D* selection is added in the for loops for the 3-prongs to exploit as much as possible the already existing code. 
It has still to be properly tested (I also want to evaluate the overhead compared to 2 prongs only and 2+3 prongs), but if you want you can start having a look at …

PWGHF: implement D*+ in track-index-skim-creator

---

PWGCF/FemtoUniverse/Core/FemtoUniverseCutculator.h
PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx

Changes to the FemtoUniverse package:
1) Change of the default Track-Track task to use bitmap for selection cuts and PID (this task does NOT use the Extended table)
2) Creation of the Track-Track Extended task from the previous default Track-Track task  (this task uses the Extended table)
3) Change of the CutCalculator to read FemtoUniverse settings from the JSON files
4) Change of the CMakeList to add the Extended Track-Track task

FemtoUniverse: bitmask changes to producer and track-track task

---

PWGHF/TableProducer/candidateSelectorD0.cxx

@fgrosa 
Removing decayLengthXYNormalized from the input features of Bdt

PWGHF: Removing decayLengthXYNormalized from Bdt

---

PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx

* Removing unused configurables and other small fixes added to the MC producer.
* Fixing naming in the track-Phi task.
* Adding femto and angular containers for same and mixed events for the track-track.
* Adding PDG vs pT plot for MC Truth particles.

PWGCF: FemtoUniverse -- Removing unused configurables from MC producer + fixing names in track-Phi

---

PWGCF/FemtoUniverse/Tasks/femtoUniverseDebugTrack.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx

Previously, to select a particle for analysis, two configurables had to be changed: `ConfTrackChoicePartOne` (which selects the PID) and `ConfPDGCodePartOne` (which sets the particle's mass). This could cause unnecessary errors if the user forgot to change both of these variables. I decided to get rid of one of them. Now the only thing to remember is to set the PDG code of the particle.

PWGCF: FemtoUniverse -- Changing PID configurables

---

PWGHF/TableProducer/candidateSelectorD0.cxx

Moving the BDT debug histogram

PWGHF: Fix issue with the debug histogram for BDT in the D0 selector

---

.mega-linter.yml
CPPLINT.cfg
pyproject.toml
pyrightconfig.json

- Create `pyproject.toml` for Python linters.
- Disable function length check in cpplint. 
- @iarsene @dsekihat @feisenhu This stops MegaLinter from complaining about too long functions in the PWGDQ code. The remaining errors reported in the PWGDQ PRs should be fixed before merging.

Update linters configuration

---

PWGCF/DataModel/singletrackselector.h
PWGCF/TableProducer/CMakeLists.txt
PWGCF/TableProducer/singletrackselector.cxx

@njacazio @fbellini @neelimaagrawal

add track selector

---

PWGJE/Tasks/jetsubstructurehf.cxx
PWGJE/Tasks/jetsubstructurehfoutput.cxx

This fixes the subscription of `processDummy` in `JetSubstructureHFOutputTask` which cannot subscribe to `McCollisions` when running the `JetSubstructureOutputMCParticleLevelD0` template instance on real data and therefore crashes.

PWGJE: Fix dummy subscription in HFJ substructure output task

---

PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx

- added an extra bin to the event histogram to check if all three min number of gamma candiadates and the sel8 condidations are met at the same time. Right now we can only see if either sel8 is selected or if the minimum nuber of photons for each of the methods are there. But there could be the case where we have no overlap between the events statisfying each of the conditions.

[PWGEM-10] createEMReducedEvent add bin to check for sel8 and MinNGamma

---

Common/Core/CollisionAssociation.h
Common/TableProducer/fwdtrackToCollisionAssociator.cxx
Common/TableProducer/trackToCollisionAssociator.cxx

@sarahherrmann this PR should fix the issue that you spotted with the BC window for MFT tracks. I set the default to `115` for the forward track associator, while at `60` for the central barrel (considering that `60 * 4` gives what we had before).
Please check if it looks good to you. Thanks!

Core: modify maximum bc offset for tracks to be considered in time-based reassociation

---

CODEOWNERS

After a discussion among HF conveners and Vit and Francesco, we have all agreed to modify the ownership of HF codes, granting it to PAG coordinators and PWG conveners for the overall HF folder, in order to optimize the code and PR handling.
This PR updates the code ownership in this sense.

Rearranging HF code owners

---

PWGHF/D2H/DataModel/ReducedDataModel.h
PWGHF/D2H/TableProducer/CMakeLists.txt
PWGHF/D2H/TableProducer/candidateCreatorB0Reduced.cxx
PWGHF/D2H/TableProducer/candidateCreatorBplusReduced.cxx
PWGHF/D2H/TableProducer/candidateSelectorB0ToDPiReduced.cxx
PWGHF/D2H/TableProducer/candidateSelectorBplusToD0PiReduced.cxx
PWGHF/D2H/TableProducer/dataCreatorD0PiReduced.cxx
PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
PWGHF/D2H/Tasks/taskB0.cxx
PWGHF/D2H/Tasks/taskB0Reduced.cxx
PWGHF/D2H/Tasks/taskBplus.cxx
PWGHF/D2H/Tasks/taskBplusReduced.cxx
PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/DataModel/CandidateSelectionTables.h
PWGHF/TableProducer/candidateCreatorB0.cxx
PWGHF/TableProducer/candidateCreatorBplus.cxx

@AlexBigO @apalasciano I made few changes in the reduced data model for B hadrons:
- I made it self contained so that the access to the parent `AO2D` files should not be needed anymore
- I changed a bit the data model, fragmenting more the tables (e.g. the covariances for pion and D tracks are separated now) and replacing the topological variables for the D mesons with the position of their decay vertex (so that we can recompute the topological variables if we want).
I still have to test the code, but you can already have a look if the changes are fine for you. Thanks!

PWGHF: make the reduced data format for B hadrons self contained

---

PWGLF/TableProducer/LFResonanceInitializer.cxx
PWGLF/Utils/collisionCuts.h

It has to be placed in the main task.
Add a configurable variable to bypass this calculation.

Hotfix: Move spheoricty function from CollCuts

---

PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx

Hi @vkucera !
In the end I defined a new `struct` before the main one in the selector, to `Spawns` the PID tables. I aim at using these tables in `prong0_as()` command, and I don't know if there is a way to both `Spawns` and consume a table in a `struct` (as I understand it, it is not possible), so spawning them *a priori* in a different `struct` is the only solution I found for the moment.
I added the columns and tables definitions in `CandidateReconstructionTables.h`, and put the possibility to compute combined PID variables also for the tiny/non-full versions of the PID tables.

PWGHF: Expression columns to compute combined PID variables

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/Core/HistogramsLibrary.cxx
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/Tasks/filterPbPb.cxx

- Debug and add missing logic to DG filter to bring on par with DGCandProducer from PWGUD
- Remove unnecessary track selection task from filterPbPb
- Add/modify cuts and histograms relevant to DG rho0 analysis
- tableMaker: Make cut on eta in barrelSelectedTracks filter configurable (default is previously hard-coded value)

PWGDQ: filterPbPb improvements

---

PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/PhotonMeson/DataModel/mcV0Tables.h
PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/PhotonMeson/Utils/TrackSelection.h

First commit is a cleanup commit (functionality stays the same):
- change bool comparisons from & to && -> gets rid of a lot of anoying compiler warnings since these appeared in header files
- moved one enum in the photon meson namespace to not pollute the global namespace
- some minor changes to improve readability (mostly subjective and just where I spotted it)
I can drop this commit upon request, just these compiler warnings are _really_ annoying when I wanted to search for the ones I was responsible for :)
Second commit added the following for the MCV0 study:
- add information of kinematics of propagated mcParticles
- add information of the photon particle
- add primary vertex information

PWGEM/PhotonMeson: MCV0 studies and cleanup

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/TableProducer/tableMaker.cxx

- CutsLibrary: Create open eta cut for event selection skims
- CutsLibrary: More separation in cuts for flexibility
- TableMaker: Enable barrel histograms for one process function in which they were missing

PWGDQ: Change cuts relevant for DG rho0 analysis

---

PWGCF/FemtoDream/CMakeLists.txt
PWGCF/FemtoDream/FemtoDreamContainerThreeBody.h
PWGCF/FemtoDream/FemtoDreamMath.h
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrackTrack.cxx

The first version of the code extends the two-body femtoscopy to the three-body case. Besides the three-body task, the femtoDreamContainer for three-body case was created separately as it requires different histograms. We will consider merging the containers once the code is validated and finalised. 
This version of the code works only for three identical track selections, it will be extended as the next step to any three particles (once this code is validated on the hyperloop to provide reasonable results).

First code version for three-body task

---

PWGLF/DataModel/LFResonanceTables.h
PWGLF/TableProducer/LFResonanceInitializer.cxx
PWGLF/Tasks/f0980analysis.cxx
PWGLF/Tasks/k1analysis.cxx
PWGLF/Tasks/k892analysis.cxx
PWGLF/Tasks/lambda1520SpherocityAnalysis.cxx
PWGLF/Tasks/lambda1520analysis.cxx
PWGLF/Tasks/phianalysis.cxx

The PID Selection flag has been introduced for the filter-level selection but never used.
To have a simplest shape, I removed the selection flag and add the hasTOF variable.

Remove the PID selection flag and add HasTOF

---

PWGJE/Tasks/emctmmonitor.cxx

- Change of pT binning, to follow in line with a pT binning which was used in AliPhysics
- Added cuts for track-cluster dPhi and dEta as configurable
- Added cluster cut for M02 max as well as a high pT region for a stronger M02 max cut as configurable
- All the cut standard values are identical to what was used in the EMCal perfomance paper for Run 2

[EMCal-689] emctmmonitor: change pT binning and added cuts

---

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx

Phi mesons in MC data are NOT primary particles, so for now, this is a workaround to have any results for MC (added as a comment in the file).

PWGCF: Femtouniverse -- Fixing Phi mesons in MC 

---

PWGDQ/Core/HistogramsLibrary.cxx

This reverts commit 98b11da990ae857105ae79156a26d950357de273.
The commit was based on miscommunication and should be reverted. It is not functional

Revert "PWGEM/DQ add 3D hist mee,pt,dca to MC Truth Pair list (#3643)"

---

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
Common/TableProducer/CMakeLists.txt
Common/TableProducer/tracksextraConverter.cxx

Pinging @mpuccio , @ddobrigk 
This has to be merged after  [#12044(O2)](https://github.com/AliceO2Group/AliceO2/pull/12044), could you have a look at this in the meanwhile?

Add Converter for new track extra dataformat

---

PWGHF/D2H/DataModel/ReducedDataModel.h
PWGHF/D2H/TableProducer/dataCreatorD0PiReduced.cxx
PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx

@AlexBigO @apalasciano I added the possibility to add the ML scores to the reduced D-meson tables for the reduced B data format. It looks like a big change since I had to slightly change the implementation of the data creators, i.e. the templetised function now takes a single collision and the loop is moved in the process functions because otherwise I could not use the `sliceBy` (that is different in case of tables with and without BDT scores), but the effective differences are very few.

PWGHF: Add the possibility to store D-meson ML scores in reduced B data model

---

PWGHF/TableProducer/candidateSelectorD0.cxx

@mfaggin following discussion in https://github.com/AliceO2Group/O2Physics/pull/3646

PWGHF: fix filling of histograms for ML application debug

---

Common/TableProducer/CMakeLists.txt
Common/TableProducer/tracksExtraConverter.cxx

[Common] Uniform tracks extra converter to the coding conventions

---

PWGHF/HFL/Tasks/taskSingleMuon.cxx
PWGHF/HFL/Tasks/taskSingleMuonSource.cxx

A protection for the selection of MCH-MID matched tracks is added in taskSingleMuon.
New histograms of eta and number of collisions are added and the quarkonium decay muons are removed from heavy quark decay muons in taskSingleMuonSource.

PWGHF: Add protection in single muon task and modify the selection conditions in muon source task

---

PWGDQ/Core/HistogramsLibrary.cxx
PWGDQ/Core/VarManager.h
PWGDQ/DataModel/ReducedInfoTables.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerJpsiHf.cxx
PWGDQ/Tasks/tableReader.cxx

Hi  @iarsene and @dsekihat
- trackBarrelInfo table added to store the collision index and vertex position for cross PWGs analyses. The table is used by the table-reader in a dedicated process function, since in 2022 reduced table produced for QM this extra table is not present. This temporary solution will be fixed once ReducedTracksBarrelInfo will be saved in the new reduced datasets.
- Separation of histograms for JPsiToMuMu and JPsiToEE

[PWGDQ] Adding collision info to dielectron tables for HF combined analyses

---

PWGCF/FemtoDream/FemtoDreamParticleHisto.h

It has been observed that the distribution of shared clusters in the TPC can be very differently for different periods (at least for data taken in 2022). Therefore we add additional debug histograms to study this effect.

PWGCF: add additional debug histograms in FemtoDream

---

Common/TableProducer/PID/pidTPC.cxx
Common/TableProducer/PID/pidTPCFull.cxx

Update partition according to the new tracks-extra dataformat. The new ITSClusterMap is evaluated only dynamically from the static ITSClusterSizes column

[Common] Update TPC PID Partition

---

PWGUD/Core/DGSelector.h
PWGUD/Core/UDHelpers.h
PWGUD/TableProducer/DGBCCandProducer.cxx
PWGUD/TableProducer/DGCandProducer.cxx
PWGUD/Tasks/DGCandAnalyzer.cxx
Tutorials/PWGUD/CMakeLists.txt
Tutorials/PWGUD/UDTutorial_03a.cxx
Tutorials/PWGUD/UDTutorial_03b.cxx
Tutorials/PWGUD/UDTutorial_04.cxx

. several smaller updates
. addition of UDTutorials0[3a, 3b, 4]

PWG-UD: UDTurials03[a,b] and UDTutorials04

---

PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx

Modification on the candidate creator done to enable the case w/o time-reassociated tracks, given that the `time-to-collision-associator` is quite CPU consuming and its importance for soft pions might be not crucial (to be tested in analysis).
Major changes:
- new `process` functions to handle this
- new `template` functions to handle the different data-type for the soft pion track

PWGHF: SigmaC candidate creation w/ or w/o time-reassociated tracks 

---

CODEOWNERS

@ddobrigk I found why I didn't have permission to merge a ML-related PR last time. The folder path was wrong.

Fix ML folder path in CODEOWNERS file

---

PWGHF/Core/HfMlResponse.h
PWGHF/Core/HfMlResponseDplusToPiKPi.h
PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
Tools/ML/MlResponse.h

Hi @fcatalan92 , @fgrosa !
I moved as much methods as I could to the mother class and put the `enum` as a template typename to give more generality. Also, this way the macros work for any type`U`, and we avoid `static_cast<int>` as we had before.
From what I found, calling `getInputFeatures` does not create a copy of the vector (feature of modern C++ compiler) so I left it this way.

Tools, PWGHF: Add flexibility to ML model input features definition

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

This PR adds a QA histogram to the cascade pre-selector such that we can now cross-check how many cascades where actually in a given AO2D versus how many were selected for actually being built. With this histogram, it will be simpler to diagnose cascade building from the base `Cascades` table all the way to the more analysis-geared `CascDatas` table.

Change QA options

---

PWGJE/TableProducer/jetfinder.h
PWGJE/TableProducer/jetfinderhf.cxx
PWGJE/Tasks/jetTutorial.cxx
PWGJE/Tasks/jetTutorialSkeleton.cxx
PWGJE/Tasks/jetfinderQA.cxx
PWGJE/Tasks/jetfinderhfQA.cxx
PWGJE/Tasks/jetsubstructure.cxx
PWGJE/Tasks/jetsubstructurehf.cxx
PWGJE/Tasks/triggerCorrelations.cxx

Please note that this is an intermediate step of the ongoing effort to optimise memory consumption and to unify the location from where we pick the PDG masses. The ultimate goal is to get the masses from [`CommonConstants/PhysicsConstants.h`](https://github.com/AliceO2Group/AliceO2/blob/dev/Common/Constants/include/CommonConstants/PhysicsConstants.h) or from the `O2DatabasePDG` service.

PWGJE: Remove RecoDecay::getMassPDG

---

PWGLF/TableProducer/f1protonInitializer.cxx
PWGLF/TableProducer/filterf1proton.cxx
PWGLF/TableProducer/v0qaanalysis.cxx
PWGLF/Tasks/QC/resonanceqa.cxx
PWGLF/Tasks/QC/v0cascadesqa.cxx
PWGLF/Tasks/hyperon-reco-test.cxx
PWGLF/Tasks/lambdakzeroanalysis.cxx
PWGLF/Tasks/lambdakzeroanalysisMC.cxx
PWGLF/Tasks/phianalysisrun3.cxx
PWGLF/Tasks/v0postprocessing.cxx

Please note that this is an intermediate step of the ongoing effort to optimise memory consumption and to unify the location from where we pick the PDG masses. The ultimate goal is to get the masses from [`CommonConstants/PhysicsConstants.h`](https://github.com/AliceO2Group/AliceO2/blob/dev/Common/Constants/include/CommonConstants/PhysicsConstants.h) or from the `O2DatabasePDG` service.
Requires https://github.com/AliceO2Group/O2Physics/pull/3692

PWGLF: Remove RecoDecay::getMassPDG

---

Tutorials/PWGHF/dpl-config_skim.json
Tutorials/PWGHF/dpl-config_task.json
Tutorials/PWGHF/run_skim.sh
Tutorials/PWGHF/run_task.sh

- The tracks-extra-converter workflow is needed after the merge of this PR:
https://github.com/AliceO2Group/AliceO2/pull/12087
- The zdc-converter workflow is needed if we decide to run the exercise on the the MC charm enriched production LHC22b1b, that would allow to see a peak also running on very small files.
@vkucera @fcolamar let me know if you agree on doing the exercise on a MC production, otherwise, I can remove the zdc-converter, but I guess we will need anyway the tracks-extra converter

PWGHF: O2AT, adding tracks-extra and zdc converter workflows.

---

ALICE3/TableProducer/OTF/onTheFlyRICHPID.cxx
ALICE3/TableProducer/OTF/onTheFlyTOFPID.cxx
Common/Core/RecoDecay.h
PWGCF/FemtoDream/FemtoDreamV0Selection.h
PWGCF/FemtoUniverse/Core/FemtoUniversePhiSelection.h
PWGCF/FemtoUniverse/Core/FemtoUniverseV0Selection.h
PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoWorld/Core/FemtoWorldPhiSelection.h
PWGCF/FemtoWorld/TableProducer/femtoWorldProducerTask.cxx
PWGHF/TableProducer/candidateCreator2Prong.cxx
PWGHF/TableProducer/candidateCreator3Prong.cxx
PWGHF/TableProducer/candidateCreatorCascade.cxx
PWGLF/TableProducer/f1protonreducedtable.cxx
PWGLF/Tasks/f0980analysis.cxx
PWGLF/Tasks/k1analysis.cxx
PWGLF/Tasks/k892analysis.cxx
PWGLF/Tasks/lambda1520SpherocityAnalysis.cxx
PWGLF/Tasks/lambda1520analysis.cxx
PWGLF/Tasks/phianalysis.cxx
PWGLF/Tasks/rhoanalysis.cxx
Tools/KFparticle/KFUtilities.h
Tutorials/PWGLF/Resonance/resonances_step1.cxx

This is the last step of the `RecoDecay` part of the ongoing effort to optimise memory consumption and to unify the location from where we pick the PDG masses. The ultimate goal is to get the masses from [`CommonConstants/PhysicsConstants.h`](https://github.com/AliceO2Group/AliceO2/blob/dev/Common/Constants/include/CommonConstants/PhysicsConstants.h) (when the PDG code is known at compile time) or from the `O2DatabasePDG` service (otherwise).
See details in the dedicated issue: https://github.com/AliceO2Group/O2Physics/issues/2178
**Notes for code owners and developers:**
- Several files across O2Physics have been affected by the removal of the dependency of `RecoDecay` on `TDatabasePDG.h` and `TPDGCode.h` because they implicitly relied on it. This can be avoided if each file …

RecoDecay: Remove getMassPDG

---

PWGJE/Tasks/emctmmonitor.cxx

- Fixed missing second fill argument for NSigma histograms (the track pT)

[EMCAL-689] emctmmonitor: Bugfix missing fill argument

---

PWGJE/Core/CMakeLists.txt
PWGJE/Core/FastJetUtilities.cxx
PWGJE/Core/FastJetUtilities.h
PWGJE/Core/JetBkgSubUtils.cxx
PWGJE/Core/JetBkgSubUtils.h
PWGJE/Core/JetFinder.cxx
PWGJE/Core/JetFinder.h
PWGJE/Core/PWGJECoreLinkDef.h
PWGJE/TableProducer/jetfinder.cxx
PWGJE/TableProducer/jetfinder.h
PWGJE/TableProducer/jetfinderhf.cxx

Implementing background subtraction methods in the O2Physics PWGJE framework. Three background estinators has been added:
- Median background estimator (as in AliPhysics).
- Rho sparse estimator, which is used for sparse events like in pp or p-Pb.
- The perpendicular cone method (used in few papers).
And three background subtraction methods has been added:
- The rho area subtraction.
- The fastjet builtin constituent subtraction method (eventwise).
- The fastjet builtin constituent subtraction jet-by-jet (jetwise).
This task also subtracted the background from the jet mass in the same methods.

Implementing background subtraction in the JE framework

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx

Investigating a crash reported by @deependra170598 in the D* creator under development (see PR https://github.com/AliceO2Group/O2Physics/pull/3567), I fixed 3 bugs in the finding of D* mesons:
1) The selection flag of D0 mesons not selected because of track selections was not reset to 0, causing the creation of D* candidates associated to no D0 mesons or the previous last one (@deependra170598 this was the bug causing the crash in your code).
2) Only half of the D* candidates were found because in the 3-prong loops were triangular, however `(trackPos1 trackNeg1)_2prong trackPos2` is not equivalent to `(trackPos2 trackNeg1)_2prong trackPos1` for D* mesons because the pion from D0 and the soft pion are not exchangeable (while they are for 3-prong candidates). 
3) The D* table was filled …

PWGHF: Fix D* finding

---

PWGJE/DataModel/TrackJetQa.h
PWGJE/TableProducer/jettrackderived.cxx

Hi @nzardosh , @alicecaluisi ,
there was a mismatch in the table definition and filling which caused the histograms to be filled with different entries than expected.
This PR fixes the issue from  signed1Pt to DCAz and reduces the columns to the essential entries.
Cheerio,
Johanna

[PWGJE] Fixing jetTrackDerived (table producer for track QA)

---

PWGHF/Tasks/taskMcValidation.cxx

This PR add the possibility of using the subGeneratorId information recently added to the HF MC generator to select specific events from a gap-triggered production.

PWGHF: Add possibility to select MC event based on generator information

---

PWGLF/DataModel/LFStrangenessTables.h
PWGLF/Tasks/cascadeanalysis.cxx
PWGLF/Tasks/cascadeanalysisMC.cxx

This PR moves the most commonly used variables to expression columns in the strangeness model. As next few steps, the CosPAs will be changed into regular columns, so they can be filtered on, and indices and other variables will be further separated into sub-tables that are joinable.
Combined with the already modular strangeness PID tables and some further adjustments, one of the goals here is that, should the need arise, the intermediate format from the builders could already serve as derived data.

Move to expression columns for most used columns

---

PWGCF/FemtoDream/FemtoDreamParticleHisto.h
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx

- In both tasks the user can specify continous cuts on the pT and eta, independently for both particles
- The cuts are implemented with Partitions and Filters instead of if statements as was te case before for the pT
- Moved the invariant mass histograms from the debug QA task to the main task
- Added the configurable for the mixing depth in the combination policy
- fixed the default value of the maximum k* cut

Added filtering to the track-track and track-v0 task

---

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGEM/PhotonMeson/Core/HistogramsLibrary.h
PWGEM/PhotonMeson/DataModel/gammaTables.h
PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx

[PWGEM/PhotonMeson: add a column in v0 photon table]
[PWGEM/PhotonMeson: add phiv template for pi0 and photon]

PWGEM/PhotonMeson: add phiv template for pi0 and photon

---

PWGDQ/DataModel/ReducedInfoTables.h
PWGDQ/TableProducer/tableMakerJpsiHf.cxx
PWGDQ/Tasks/taskJpsiHf.cxx

Hi @lucamicheletti93 I have adapted the JPsi-D code for what concerns the D0 BDT tables to be compatible with the new developments in HF https://github.com/AliceO2Group/O2Physics/pull/3789

PWGDQ: Adapt D0 BDT columns to new development in HF

---

EventFiltering/PWGCF/CFFilterAll.cxx

Add cut on correlation between reconstructed momentum and momentum at the inner wall of the TPC. 
This is an update to the previous PR. The cut can now optionally be performed either on the difference or on the ratio of the difference over the reconstructed momentum.

PWGCF: Trigger update

---

PWGHF/TableProducer/candidateSelectorD0.cxx

Fix for bug introduced in https://github.com/AliceO2Group/O2Physics/pull/3789
The tables `TracksPidPiExt` and `TracksPidKaExt` are consumed but not produced.

PWGHF: Fix missing Spawn in D0 selector

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx

In this PR I added more centrality estimators and I split the process functions for each centrality estimator to avoid the process of centrality tables which are not used.

PWGHF: Add more centrality estimators

---

PWGMM/Mult/Core/CMakeLists.txt
PWGMM/Mult/Core/include/Axes.h
PWGMM/Mult/Core/include/Functions.h
PWGMM/Mult/Core/include/Histograms.h
PWGMM/Mult/Core/include/Selections.h
PWGMM/Mult/Tasks/common.h
PWGMM/Mult/Tasks/dndeta.cxx
PWGMM/Mult/Tasks/puremc-dndeta.cxx

Extensive rework of dndeta.cxx code:
* Separate common definitions for axes, histograms and selections into dedicated headers
* Separate track filters into logical parts
* Replace histogram identifiers with named strings for consistency and the ability to use them in external post-processing
* Unified binning and labeling for event selection and efficiency histograms
* Separate process functions that use ambiguous tracks and those that do not
* Simplify centrality detection
* Separate histogram registries for binned and inclusive cases

PWGMM: dndeta: rework

---

PWGDQ/Core/HistogramsLibrary.cxx
PWGDQ/Core/VarManager.cxx
PWGDQ/Core/VarManager.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/Tasks/filterPbPb.cxx

* TableMaker: Use 32 highest bits of o2::aod::reducedevent::Tag to store lowest 32 bits of DQEventFilter
* VarManager: Add enum for event filter bits
* HistogramsLibrary: Add histograms for DG/SG filters
* filterPbPb now saves both SG and DG events

[PWGDQ] Add event filter to tag column in reducedEvents

---

PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/candidateCreator3Prong.cxx
PWGHF/TableProducer/treeCreatorLcToPKPi.cxx

The info about the prong contributors to the PV is needed to properly estimate the barrel multiplicity.
PR to be extended to the 2-prong candidate creator.
@fgrosa @vkucera

PWGHF: adding the info about the number of prongs that contributes to the PV estimation in the candidate creator.

---

PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx

PWGEM/PhotonMeson: add protection for mass

PWGEM/PhotonMeson: add protection for mass

---

PWGMM/Mult/Tasks/dndeta.cxx

* fix duplicated counting for INEL>0 (PV)

PWGMM: dndeta: separate generator-level counters

---

PWGDQ/DataModel/ReducedInfoTables.h

Fixing the index format for MFT in ReducedMuonsExtra and declaring it as for MCH tracks. 
This modification fixes the problem at AOD merging in hyperloop.

[PWGDQ] Fixing the index format for MFT in ReducedMuonsExtra

---

PWGHF/TableProducer/candidateCreatorToXiPi.cxx

Since treating an uint8_t like an int in the Filter is not possible, replace table filtering with TESTBIT function in the candidates loop (toXiPi candidateCreator - process function dedicated to derived data)

PWGHF: change filter -> testbit in toXiPi creator

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/Core/VarManager.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/Tasks/filterPbPb.cxx

* Use 8 largest bits of reducedevent::Tag to store eventFilter instead of 32 largest bits
* VarManager: Write doublegap and singlegap booleans from reducedevent, making them available to tableReader
* CutsLibrary: Add cuts for selecting double/single gap events
* filterPbPb: Add config string for event type (any combination of 'singlegap', 'doublegap')
* tableMaker: Add process function appropriate for DG/SG filter with forward tracks

PWGDQ: Improve filterPbPb and add muon process function

---

PWGLF/DataModel/LFResonanceTables.h
PWGLF/Tasks/QC/efficiencyQA.cxx
PWGLF/Tasks/f0980analysis.cxx
PWGLF/Tasks/k1analysis.cxx
PWGLF/Tasks/k892analysis.cxx
PWGLF/Tasks/lambda1520SpherocityAnalysis.cxx
PWGLF/Tasks/lambda1520analysis.cxx
PWGLF/Tasks/phianalysis.cxx
Tutorials/PWGLF/Resonance/resonances_step1.cxx
Tutorials/PWGLF/Resonance/resonances_step2.cxx

Updated from `MultV0M` to `Cent`
The variable `MultV0M` has contained the multiplicity/Centrality of the event which the type (V0M.FT0) can be set during the filter process.

PWGLF: Update the common column name

---

EventFiltering/PWGCF/CFFilterAll.cxx

Add options to reject tracks whose assumed PID during tracking does not correspond to the selected PID selected in the analysis. This rejection can be turned on/off with a switch and can be applied up to a configurabel p_TPC threshold. It can also be configured independently for protons and deuterons.

PWGCF: Update trigger

---

EventFiltering/PWGLF/strangenessFilter.cxx

- wrong variable used for DCA cut (so far unused)

Fix ST selection for strangeness filter

---

PWGDQ/Core/CutsLibrary.cxx
PWGDQ/Core/HistogramsLibrary.cxx
PWGDQ/Core/VarManager.h
PWGDQ/Tasks/tableReader.cxx

**KF vertexing implemented in dileptonHadron-task**
* PWGDQ/Tasks/taleReader.cxx, l 1214-1217: Use of KFparticle for 3 prong vertexing included as a configurable
* Initialization of DCAfitter or KFparticle in PWGDQ/Tasks/taleReader.cxx (l 1277-1298)  and PWGDQ/Core/varManager.h (l 562-566)
* PWGDQ/Core/VarManager.h, l 2120-2202: FillDileptonTrackVertexing splitt in two parts: 1) DCA fitter, 2) KFparticle. KFparticle follows the structure of KFparticle implemented in FillPairVertexing. For now only implemented for BtoJpsiEEK, but easily generalizable. 
**Run 2 definitions of decay length and pseudoproper decay time implemented for the 2 and 3 prong decay**
In Run 2 decay length was defined as projected onto the momentum axis. Implemented to allow for Run 2 vs Run 3 comparisons. 
* decay …

PWGDQ: Vertexing for pair and triplet (2 and 3 prong decays)

---

PWGLF/TableProducer/lambdakzeromcfinder.cxx

This prong-path is still highly unoptimised, but at least there's now one less bug :-D

Bugfix in prong-path MC findable

---

PWGHF/Core/HfMlResponseDsToKKPi.h
PWGHF/DataModel/CandidateSelectionTables.h
PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx

Dear all,
In view of the selection of Ds-meson candidates with ML technique, I've added the separation between the different mass hypothesis in candidateSelectorDsToKKPi for the applyMl case. I've added a new HfMlResponseDsToKKPi following the same done for the D0 and D+ mesons.
Let me know for any comment/advise you have.
Best regards,
Samuele

PWGHF: Modified candidateSelectorDsToKKPi. Added HfMlResponseDsToKKPi

---

PWGDQ/Core/VarManager.h
PWGDQ/Tasks/tableReader.cxx

Creation of a dedicated process function (processDecayToMuMuSkimmedWithColl) with collision info for muons to allow backward compatibility

[PWGDQ] Adding dedicated process function for muons with collision info

---

PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx

PWGEM/PhotonMeson: remove unnecessary PHOS/EMC dep. in MaterialBudget

PWGEM/PhotonMeson: remove unnecessary PHOS/EMC dep. in MaterialBudgey

---

PWGJE/TableProducer/jettrackderived.cxx
PWGJE/Tasks/trackJetqa.cxx

Hi @alicecaluisi , @nzardosh ,
this fixes the method isEventSelected() in the trackJetqa and the table in the corresponding table producer.
I also added a rejection histogram to monitor how many collisions are not present in the full process (to explain the subtle difference in the number of tracks between the full and derived process).
Cheerio,
Johanna

[PWGJE] fix track table production and isEventSelected()

---

PWGHF/TableProducer/candidateCreatorToXiPi.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx

Modify the struct HfTrackIndexSkimCreatorTagSelTracks to implement a set of selection dedicated to the bachelor track in LF cascade+bachelor decays. Until now the selections dedicated to bachelor track of V0+bachelor decays were used also for the above-mentioned channel.

PWGHF: implement track selections for bachelor in lfCascade+bachelor decays

---

PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx

Adding the code for D0/D0bar mesons to the FemtoUniverse. I've modified .h files in the Core folder. I've added missed part for TempFitVarName in the FemtoDerived.h file. In the producer I've added the function for filling table with D mesons and process for them. I've modified CMakeLIsts.txt, because I've also added a first version of a task to run D0 analysis (check the simple distributions, like invMass, pT).

PWGCF - adding DO mesons to FemtoUniverse

---

PWGHF/TableProducer/trackIndexSkimCreator.cxx

This PR fixes a bug in the selection on the invariant mass difference of the reconstructed kaons pair and the phi meson

PWGHF: Fix delta mass (phi,KK) selection in track skimming

---

PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx

Hello, just fixing typos in DplusPi creator in the process function with MC truth and ML info on D candidates.
Note: these typos are not present in D0Pi creator.

PWGHF: Fix typos in DplusPi creator

---

PWGLF/TableProducer/lambdakzerofinder.cxx
PWGLF/TableProducer/lambdakzeromcfinder.cxx

@shahor02 this is required so that the change in O2 can go or, indeed, the analysis CI might complain as the new version of O2 will not compile against the older version of O2Physics. Once O2Physics switches to being built against the new O2, I can switch these tasks to produce the generic `V0s`. 
Technically, once this PR is merged, we could ignore the fullCI because then for sure the compilation will work...

Switch table producers that produce V0s to produce V0s_001 temporarily

---

PWGHF/TableProducer/candidateCreatorToXiPi.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx
PWGHF/TableProducer/treeCreatorOmegacSt.cxx

Fixing the name to be consistent with the names of other particles.
Requires https://github.com/AliceO2Group/AliceO2/pull/12378
@qgp

PWGHF: Rename XiCZero -> XiC0

---

PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/CMakeLists.txt
PWGCF/FemtoDream/FemtoDreamCutculator.h
PWGCF/FemtoDream/FemtoUtils.h
PWGCF/FemtoDream/femtoDreamCollisionMasker.cxx
PWGCF/FemtoDream/femtoDreamDebugTrack.cxx
PWGCF/FemtoDream/femtoDreamDebugV0.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx

Introduce two new features in FemtoDream
1. PID selection with bit masks
Bit masks for the PID selection in FemtoDream have been implemented from the very beginning, but the selection of them has been very clunky and the user had to provide a lot of unnecessary information to compute the bit mask at run time. Now the mechanism has been overhauled. The user gets the bit masks for different PID selections from the cutculator directly and then just passes them as a configurable.
2. Event selection and mixing with bit masks
Event mixing has been very primitive so far, i.e. using the framework-provided functions to generate binned groups of events and then pairing particles from these events to generate a mixed event sample. However, so far there has been no check if a track that passed the …

PWGCF: Masked Mixing in FemtoDream

---

PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx

Fix the typo which breaks the collision masking for track-v0 pairing.

PWGCF: fix typo

---

PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx

PWGEM/PhotonMeson: update efficiency for primary muon
PWGEM/PhotonMeson: change default value in TAP
PWGEM/PhotonMeson: remove unnecessary dep.

PWGEM/PhotonMeson: update efficiency for primary muon

---

PWGDQ/Tasks/tableReader.cxx

Hi @iarsene , @feisenhu , @dsekihat , 
here is my proposal to avoid the two prong fitters for the dielectron low mass analysis. 
I realized that when Florian implemented the PhiV calculation, he is taking the magnetic field from one of this fitter, so that we need still to put the write Bz value for this one. It makes me also aware that probably the option to use the KF filter is not working properly for our phiv calculation then....one reason more to clean this up.
Since nobody seems to complain, I double the functions we would need to stay transparent for the others.
Do not hesitate to comment....
Thanks,
Raphaelle

NoTwoProngFitter

---

PWGEM/PhotonMeson/Tasks/emcalPi0QC.cxx
PWGJE/DataModel/EMCALMatchedCollisions.h
PWGJE/TableProducer/emcalCorrectionTask.cxx

- Add table EMCALMatchedCollisions, which for every collision contains a boolean stating whether multiple collisions were found in the BC
- That table is filled in the emcalCorrectionTask for every collision to make it joinable with the collision table
- emcalPi0QC task reads this table to enable correct event normalization
- Bug fix in emcalPi0QC task NCell cut
- Combined event histograms in emcalPi0QC task

PWGJE+EM: Add EMCal ambiguous collision table and include in QC task

---

PWGDQ/TableProducer/tableMaker.cxx

Add processBarrelOnly functions  with Cov and Cent and Mults

---

Common/Core/CollisionAssociation.h

This PR fixes the type of the globalBC vector, which has to be signed since it is filled with `-1` for unassigned tracks (thanks @jgrosseo for spotting it!)

Common: fix type of globalBC

---

EventFiltering/PWGHF/HFFilter.cxx
EventFiltering/PWGHF/HFFilterHelpers.h
EventFiltering/PWGLF/strangenessFilter.cxx
PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGHF/TableProducer/candidateCreatorCascade.cxx
PWGHF/TableProducer/candidateCreatorToXiPi.cxx
PWGHF/TableProducer/trackIndexSkimCreator.cxx
PWGLF/DataModel/LFResonanceTables.h
PWGLF/DataModel/LFStrangenessTables.h
PWGLF/TableProducer/LFResonanceInitializer.cxx
PWGLF/TableProducer/QC/strangenessQC.cxx
PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/cascadefinder.cxx
PWGLF/TableProducer/cascademcbuilder.cxx
PWGLF/TableProducer/cascadepid.cxx
PWGLF/TableProducer/cascqaanalysis.cxx
PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx
PWGLF/TableProducer/lambdakzerofinder.cxx
PWGLF/TableProducer/strangederivedbuilder.cxx
PWGLF/Tasks/QC/straRecoStudy.cxx
PWGLF/Tasks/QC/v0cascadesqa.cxx
PWGLF/Tasks/cascadeanalysis.cxx
PWGLF/Tasks/cascadeanalysisMC.cxx
PWGLF/Tasks/cascadecorrelations.cxx
PWGLF/Tasks/hStrangeCorrelation.cxx
PWGLF/Tasks/hyperon-reco-test.cxx
Tutorials/PWGLF/Strangeness/strangeness_step4.cxx

This PR takes into account the recent implementation of the `V0Type` column in the V0 data model to ensure safety of the analysis of V0s. It means to compartmentalize the standard V0s and the V0s built solely for the purpose of cascade finding, since these two populations have very different selection criteria at the secondary vertexer level and therefore cannot be mixed. 
The main change is that standard V0s (including photons, if those are meant to be built) are saved in `V0Datas`, while V0s built *solely* for the sake of cascade analysis are built in the `V0fCDatas` ('for Cascades') table. This means that no duplication of `DCAFitter` calls takes place at building/analysis time, while making absolutely sure that the V0s dedicated solely for cascade building are not analysed by mistake …

Safety changes for V0 type

---

PWGHF/D2H/DataModel/ReducedDataModel.h
PWGHF/D2H/TableProducer/candidateCreatorB0Reduced.cxx
PWGHF/D2H/TableProducer/candidateCreatorBplusReduced.cxx
PWGHF/D2H/TableProducer/dataCreatorD0PiReduced.cxx
PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
PWGHF/D2H/Tasks/taskB0Reduced.cxx
PWGHF/DataModel/CandidateReconstructionTables.h

In this PR I added the re-propagation of re-associated pion tracks (not done before). 
In addition, it removes the usage of the LUT for the DCAFitter since HF decays should always be within the beampipe, there is no need of material correction (this should be fixed everywhere in HF code, since it allows us to spare memory)

PWGHF:Add missing repropagation of reassociated tracks

---

PWGJE/Tasks/jetfinderQA.cxx
PWGJE/Tasks/jetfinderfullQA.cxx
PWGJE/Tasks/jetfinderhfQA.cxx

- option to fill track histograms with weights
- this is done in the weighted and unweighted scenario with new fillHistogramTracks function for common histogram filling
- include weighted number of collision histogram when enabling this option (as well as the unweighted number of collisions, which may still be useful)

add weighted track and number of collisions option

---

PWGDQ/Core/VarManager.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerMC.cxx

- Moving initialization of magnetic field for muon propagation to avoid flooding logs
- Fixing magnetic field used in single muon propagation following KF vertexing
- Removing duplicate initialization of ccdb manager in tableMaker
- Adding muon propagation options in tableMakerMC

[PWGDQ] Various fixes for muons 

---

PWGCF/FemtoWorld/Tasks/femtoWorldEfficiencyTask.cxx

Adding TOFmatchingPi, TOFmatchingKa, TOFmatchingPr histograms for particles with TOF info to femtoWorldEfficiencyTask.cxx.

PWGCF: add TOFMatching histograms for different particles

---

PWGCF/FemtoDream/FemtoDreamTrackSelection.h
PWGCF/FemtoDream/FemtoDreamV0Selection.h
PWGCF/FemtoDream/femtoDreamDebugV0.cxx
PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/femtoDreamProducerTask.cxx

Two fixes:
- For v0 daughters, certain track variables get recomputed by the lambdakzero-builder. Since these values are used to fill the femto tables, these values should also explicitly be used for the daughter selections.
- Fix bug in debug-v0 task

PWGCF: Fix FemtoDream

---

PWGDQ/Core/CutsLibrary.cxx

Adjust PID selection for triggers, so it is momentum dependent in the pion rejection

PWGEM: adjust TOF PID cut, momentum dependent

---

PWGCF/Femto3D/Core/femto3dPairTask.h
PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
PWGCF/Femto3D/Tasks/femto3dQA.cxx

Dear @victor-gonzalez,
In this commit:
1. "femto3dPairTask": we're adding the calculation of the 3D k* in the LCMS and filling the corresponding histograms.
2. "singleTrackSelector": adding the options to choose cent. & must. estimators, cut on TOFchi2 and options to run on the Run2 data to perform the comparison of 3D femto characteristics calculation with results from a previous analysis.
Could you please approve the commit. Thank you.

adding 3D k* calculation and new flags for mult./cent.

---

PWGHF/TableProducer/candidateSelectorDstarToD0Pi.cxx

In this PR, we are propagting the changes made in the [PR](https://github.com/AliceO2Group/O2Physics/pull/4292/files).
The selection cut variable for D0 in the Dstar selector class has been renamed.

PWGHF: Correction to D0 Selection cut in Dstar Selector Task

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx
PWGLF/TableProducer/strangederivedbuilder.cxx

This PR adds an option (default: `false`) to round some variables that are never used to their full precision in analysis. The idea behind this is to make the resulting data, if saved to disk, much more compressible and therefore save space. 
Side note: the `float roundToPrecision( float number, float step = 0.01)` function could be generally useful to round variables before saving derived data AO2D. The idea is that it rounds a certain number in an axis that is quantized by the variable 'step'; the rounded number is placed halfway between n*step and (n+1)*step such that analysis can be done with absolutely no issue with precision 'step'. Maybe it could be placed in a utils header in the `Common` directory in a next iteration if it really pays off - I will test and see how well this works …

PWGLF / strange derived data: rounding some vars for better disk use

---

DPG/Tasks/TPC/tpcSkimsTableCreator.cxx

Patch to TPC PID track skimmer task to properly enable momentum-dependent downscaling via Tsallis function (method was already implemented and applied for TPC+TOF tree, but not properly enabled for V0 candidates)

enable momentum-dependent Tsallis downscaling for V0 tree

---

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx

Small changes in femtoUniverseProducerTask.cxx regarding D mesons. I've deleted two configurables and modified fillD0mesons function.

PWGCF-FemtoUniverse: update for D0 in the producer

---

PWGHF/Core/SelectorCuts.h
PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
PWGHF/TableProducer/candidateSelectorDstarToD0Pi.cxx

1. Increased number of pT bins for selected Dstar and D0 candidates
2. Inequality condition for ```d0SoftPiNormalised``` is corrected.

PWGHF: Change in number of pT Bins and selection criteria for d0SoftPiNormalised

---

PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx

This PR contains:
- Process functions dedicated to D mesons selected via linear selections for scalar product study; 
- Minor fixes;

PWGHF: Adding process functions for linearly-selected D+ and Ds

---

PWGCF/FemtoDream/Core/femtoDreamCollisionSelection.h
PWGCF/FemtoDream/TableProducer/femtoDreamProducerReducedTask.cxx
PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx

- add a process switch in the producer task to run MC without centrality
calibration

PWGCF: process switch MC without centrality

---

PWGJE/Tasks/emcalPi0EnergyScaleCalib.cxx

- Make eta and phi axis configurable to reduce memory consumption when needed

[EMCAL-1111] Introduce configurable eta and phi axis in energy scale calib task

---

PWGEM/PhotonMeson/Core/CutsLibrary.cxx
PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
PWGEM/PhotonMeson/Core/HistogramsLibrary.h
PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx

remove unnecessary propagation

PWGEM/PhotonMeson: remove unnecessary propagation

---

PWGLF/DataModel/LFSlimStrangeTables.h
PWGLF/TableProducer/CMakeLists.txt
PWGLF/TableProducer/LFStrangeTreeCreator.cxx

The goal of this data model is to provide slim tables of V0's for ML studies. Only the BDT input columns are stored. The table producer is expected to run on a small fraction of the full statistics.

add slim table for ML applications

---

PWGDQ/DataModel/MchTrkEffTables.h
PWGDQ/TableProducer/tableMakerMuonMchTrkEfficiency.cxx
PWGDQ/Tasks/taskMuonMchTrkEfficiency.cxx

This patch includes the option to select the track type in the analysis of the track efficiency uncertainty.

PWGDQ: Include selection on the muon track type on track-efficiency-uncertainty code

---

PWGJE/TableProducer/emcalCorrectionTask.cxx

- The global cell scale corrects for energy loss in the material in front of the emcal. The factor needs to be applied on cell level.
- Here, two scenarios are implemented: Calibration depending on the supermodule type (Full, 2/3, 1/3) or depending on the column of the Detector. The column by column calibration is supposed to distinguish regions behind the TRD support structure and the rest of the detector.
- The calibration is Off by default (will be enabled as soon as it is validated)
- The calibration coefficients are configurable and are stored in a vector

[EMCAL-1111] Add option for global cell scale in correction task

---

PWGLF/DataModel/LFStrangenessTables.h
PWGLF/TableProducer/lambdakzerobuilder.cxx
PWGLF/TableProducer/strangederivedbuilder.cxx

* adds optional q-vectors to strangeness derived builder and makes minor adjustments in the way q-vectors were declared in the strangeness derived data tables @mpuccio @ChiaraDeMartin95 
* adds optional positive and negative track positions at minima for refit studies @pzhristov 
* soon to follow: adjustments + addition of flattenicity and other variables

PWGLF: Extras in strangeness derived data

---

PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
PWGHF/DataModel/CandidateReconstructionTables.h
PWGHF/TableProducer/candidateCreatorDstar.cxx

@deependra170598 I made a small change in the D* table adding the soft pion sign, to avoid to access the track table later on to retrieve this information.

PWGHF: add sign of soft pion in D* table to avoid to access the track table

---

PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/Core/femtoDreamContainer.h
PWGCF/FemtoDream/Core/femtoDreamEventHisto.h
PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx

Since the multiplicity percentile is now made available by the femtodream produer, we can use it in the pair tasks. The following features have been added:
- One can now decide how the collisions are binned for computing the mixed event. Either the events are binned in intervals of MultNtr, MultPercentile, or both. The binning in a similar Vertex Z position is always implicit.
- One can now also filter collision according to MultNtr or MultPercentile.
- Since the multiplicity percentile is now available we will use a sparse 4D histogram to store pairs according to k*, mt, MultNtr and MultPercentile.

PWGCF: Add new binning policies in pair tasks

---

DPG/Tasks/TPC/tpcSkimsTableCreator.cxx

TPC PID skimmed table creator:
- Fix selection logic used for V0bits from V0 decay daughters (previously only positive track's bit was explicitly checked leading to more combinatorics in saved candidates + impurity for negative tracks)
- Fix crash introduced by https://github.com/AliceO2Group/AliceO2/pull/12573 [since daily-20240125] due to mismatched type on "v0.[pos|neg]Track_as\<Trks\>" with filtered table declaration in process()

Bugfixes on TPC skimmer task (V0 logic + dereferencing)

---

PWGLF/TableProducer/cascadebuilder.cxx
PWGLF/TableProducer/lambdakzerobuilder.cxx

Look for Casc/V0 Indices tables instead of Datas tables

PWGLF: Fix autodetect in strangeness builders

---

PWGUD/Tasks/CMakeLists.txt
PWGUD/Tasks/upcTauTau13topo.cxx

New UPC task on tau tau in 1+3 topology (electron+3pions) analysis added: PWGUD/Tasks/upcTauTau13topo.cxx . It is running on skimmed data. CMakeLists.txt file is also adopted to run this task.

New UPC analysis task on tau tau in 1+3 topology (electron+3pions) added

---

Common/TableProducer/trackPropagation.cxx

Restoring the original `processCovariance` name, unproperly changed into `processCovarianceData` in the PR #4425 .
- @benedikt-voelkel this should solve the issues you observed in the ALIBI-NIGHTLIES
- @jgrosseo this would imply to revert back the configurations of Hyperloop service wagons on tomorrow
Sorry to both for the inconvenience, we overlooked this detail

Restore processCovariance name.

---

PWGDQ/Core/VarManager.h
PWGDQ/TableProducer/tableMaker.cxx
PWGDQ/TableProducer/tableMakerMC.cxx

- Fixing initialization of magnetic field in tableMaker and tableMakerMC
- Fixing fetch of magnetic field value for global muon propagation
- Adding protection for case when KFVertexing outputs negative variances

[PWGDQ] Fixes for muon propagation

---

PWGCF/DataModel/FemtoDerived.h
PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx

Depending on the dataframe size the computation cost for event mixing might too high for a given dataset. Add the option to uniformly exclude events (i.e. downsampling) from the mixing pool and reduce the computational cost.

PWGCF: add downsampling to femtodream

---

PWGUD/Core/UPCHelpers.h
PWGUD/DataModel/UDTables.h
PWGUD/TableProducer/UPCCandidateProducer.cxx
PWGUD/TableProducer/fwdTrackPropagation.cxx

Changes:
* Adding Central- and Forward-selection-specific tables for UDCollisions. For forward event selection, additional table enables improved amplitude-based veto using T0A and V0A information
* Do not propagate forward tracks with z > -90 in fwdtrack-propagation
* Removing BCsWithSels from Central and Forward selection, as this table is not used

Update for UPCCandidateProducer
