.github/workflows/code-formatting.yml
Copied from O2.
Tested in my fork and working, except that alibuild/O2Physics doesn't exist.
@ktf, please could you fork AliceO2Group/O2Physics into alibuild/O2Physics and add the ALIBUILD_GITHUB_TOKEN secret?
=> Add clang-format check

.clang-format, .clang-tidy, CODEOWNERS, PWGHF/CMakeLists.txt, PWGLF/CMakeLists.txt, README.md, cmake/O2PhysicsAddLibrary.cmake
=> remove test folders

CMakeLists.txt
Requires alidist from https://github.com/alisw/alidist/pull/3197
=> Added ONNXRuntime as dependency

Tasks/PWGHF/HFCorrelatorD0D0bar.cxx, Tasks/PWGHF/HFCorrelatorDplusDminus.cxx, Tasks/PWGHF/taskCorrelationDDbar.cxx
Same modifications as those on old O2 PR
Re-applied here via patch as suggested by Vit's instructions
=> PWGHF: Adding efficiency weighting to DDbar code

Tasks/PWGHF/HFTrackIndexSkimsCreator.cxx
=> Remove unnecessary printout

ALICE3/include/ALICE3Analysis/RICH.h, ALICE3/src/alice3-lutmaker.cxx, ALICE3/src/pidRICHqa.cxx, Tasks/PWGPP/qaEfficiency.cxx
- Extended QA task for RICH with example of both RICHs
- Fix order of process arguments for efficiency task
- Fix order of process arguments for lut-maker task
=> Add Forward RICH table

Tasks/PWGPP/qaEventTrack.cxx
- Simplify options
- Improve histo style
=> Add possibility to turn off tasks in event QA

Tasks/PWGHF/taskJpsi.cxx
=> PWGHF: Hotfix for the daughter0_as issue in the Jpsi task

Tasks/PWGPP/qaEventTrack.cxx
=> Add Vertex efficiency histogram

Tasks/PWGHF/CMakeLists.txt, Tasks/PWGHF/HFTreeCreatorXToJpsiPiPi.cxx
X tree creator task for ML optimization
=> PWGHF: X tree creator task

ALICE3/src/alice3-cdeuteron.cxx
- Add generated particle histogram
=> Update cdeuteron task

PWGJE/TableProducer/jetfinder.cxx
Even though the tables are defined in the data model, they aren't
necessarily available, so we need to update the PROCESS_SWITCH options
accordingly
NOTE: This contains a few hacks around limitations in configuration
until more comprehensive options are available
=> Fixes for differentiating charged vs full jets

PWGHF/Tasks/taskD0.cxx
PWGHF: Fix the bin number of 3D histogram to reduce output file size
=> PWGHF: Fix the bin number of 3D histogram to reduce output file size

PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/HFTreeCreatorXiccToPKPiPi.cxx
=> PWGHF: Add Ξcc tree creator

ALICE3/Tasks/alice3-qa-multiplicity.cxx, PWGPP/Tasks/qaEfficiency.cxx
- Update A3 mult task
- Add MinContrib cut
- Update efficiency task
- Add multiplicity in efficiency task
- Add track length to efficiency task
=> Update QA tasks

PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/MCProng.cxx, PWGDQ/Core/MCSignalLibrary.h
=> PWGDQ/Core: add MC signals for LMEE

PWGDQ/Core/CMakeLists.txt, PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/MixingHandler.cxx, PWGDQ/Core/MixingHandler.h, PWGDQ/Core/MixingLibrary.h, PWGDQ/Core/PWGDQCoreLinkDef.h, PWGDQ/Tasks/dileptonMuMu.cxx, PWGDQ/Tasks/tableReader.cxx
Creation of MixingHandler.h and MixingHandler.cxx that:
- Allow to add several mixing variables (centrality, VtxZ, etc...) and the binning used
- Compute a mixing category for a given event
and other functionnalities
Creation of MixingLibrary.h that has a list a predifined mixing configurations to be used in analysis
Implementation of the MixingHandler tool in dileptonMuMu.cxx and tableReader.cxx
=> Addition of a mixing handler for event mixing

PWGDQ/Core/MCSignalLibrary.h
quick fix to MC signal indices
=> PWGDQ/Core: quick fix to MC signal indices

ALICE3/TableProducer/alice3-pidTOF.cxx, Common/Core/PID/PIDResponse.h, Common/Core/PID/PIDTOF.h, Common/Core/PID/PIDTPC.h, Common/TableProducer/PID/pidBayes.cxx, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFFull.cxx, Common/TableProducer/PID/pidTOFbeta.cxx, EventFiltering/PWGUD/diffractionFilter.cxx, PWGCF/FemtoDream/femtoDreamProducerTask.cxx, PWGLF/Tasks/NucleiSpectraEfficiencyLight.cxx, PWGLF/Tasks/NucleiSpectraTask.cxx, PWGLF/Tasks/spectraTOF.cxx, PWGLF/Tasks/spectraTOFtiny.cxx, PWGLF/Tasks/spectraTPC.cxx
Squashed PR https://github.com/AliceO2Group/O2Physics/pull/74 from @njacazio
=> tofSignal -> tracktime transition

ALICE3/Core/TOFResoALICE3.h, ALICE3/TableProducer/alice3-pidTOF.cxx, ALICE3/Tasks/alice3-cdeuteron.cxx, ALICE3/Tasks/pidRICHqa.cxx
=> Update FRICH QA code

Common/Core/TrackSelectorPID.h, PWGHF/Tasks/taskJpsi.cxx
PWGHF: add the pid flag for jpsi task
=> PWGHF: Add PID flags for the J/ψ task

PWGCF/Tasks/dptdptcorrelations-simchl.cxx
Also enhanced the collected information for the mapping
reconstructed <-> generated
=> Split processing of reco and MC reco

ALICE3/TableProducer/alice3-pidTOF.cxx, ALICE3/Tasks/pidRICHqa.cxx, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFFull.cxx, Common/TableProducer/PID/pidTOFbeta.cxx, Common/TableProducer/PID/pidTPC.cxx, Common/TableProducer/PID/pidTPCFull.cxx, PWGLF/Tasks/spectraTOF.cxx, PWGLF/Tasks/spectraTOFtiny.cxx, PWGLF/Tasks/spectraTPC.cxx, PWGLF/Tasks/spectraTPCtiny.cxx
- Simplified spectra TOF/TPC
- Change default axis limits of QA tasks
=> Update spectra tasks

PWGCF/FemtoDream/FemtoDreamTrackSelection.h, PWGCF/FemtoDream/FemtoDreamV0Selection.h, PWGCF/FemtoDream/femtoDreamProducerTask.cxx
- Fix bug in Daughters selection V0 (delete const static in isSelecte…dMinimal of Track
- Add possibility to init the histograms for Daughters from Track
- Add PIDSpecies function to put PID cuts on Daughters V0
=> Fix bugs Selection Daughters, PID Daughters and histos

PWGHF/Core/HFSelectorCuts.h, PWGHF/TableProducer/HFXiccToPKPiPiCandidateSelector.cxx
- Add minimum d0 cut on daughters of  Ξcc
=> PWGHF: Add minimum d0 cut on daughters of  Ξcc 

ALICE3/DataModel/ECAL.h, ALICE3/TableProducer/alice3-pidTOF.cxx, ALICE3/Tasks/ECALqa.cxx, ALICE3/Tasks/alice3-cdeuteron.cxx, ALICE3/Tasks/pidRICHqa.cxx
- c-deuteron
- Add inv. mass bins
- Remove duplicate histo
- Add inv mass vs pT
- Computing TOF time in task with ALICE3 workflow
- Compute combined TOF-RICH nsigmas
=> Extend A3 c-deuteron and RICH analyses

Common/TableProducer/eventSelection.cxx
@ekryshen since none of the additional tables used in event selection task are used directly, but only through index from the main argument, using grouping provides no benefit but decreases performance. 
P.S. note that diff is less scary with `git diff -w`, the original process is just wrapped in a loop over BCs.
=> Avoid grouping in event selection task where not needed

PWGHF/DataModel/HFCandidateSelectionTables.h, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/HFD0CandidateSelectorALICE3Barrel.cxx, PWGHF/TableProducer/HFD0CandidateSelectorALICE3Forward.cxx, PWGHF/Tasks/CMakeLists.txt, PWGHF/Tasks/taskD0ALICE3Barrel.cxx, PWGHF/Tasks/taskD0ALICE3Forward.cxx
@vkucera @ginnocen A temporary task for the study of D0 PID performance study for ALICE3 in the barrel and forward. Modification according to coding guidelines will be done later.
=> PWGHF: Temporary task for D0 PID performance study for ALICE3 in barrel and forward

PWGHF/DataModel/HFCandidateSelectionTables.h, PWGHF/TableProducer/HFD0CandidateSelectorALICE3Barrel.cxx, PWGHF/Tasks/taskD0ALICE3Barrel.cxx
@vkucera @ginnocen Add perfect PID case for D meson PID performance required for LOI
=> PWGHF: Add Perfect PID case for D0 PID performance

PWGCF/Tasks/dptdptcorrelations-simchl.cxx
Also enabling global tracks for Run3 tracks
=> Inclusion of DCA registering

PWGHF/DataModel/HFCandidateSelectionTables.h, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/HFD0CandidateSelectorALICE3Barrel.cxx, PWGHF/TableProducer/HFLcCandidateSelectorALICE3.cxx, PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx, PWGHF/Tasks/CMakeLists.txt, PWGHF/Tasks/taskD0ALICE3Barrel.cxx, PWGHF/Tasks/taskLcALICE3.cxx
@vkucera @ginnocen Task for the PID performance of Lc along with the information of D0 bar in D0 selector and histogram for n umber of contributors in skimming task
=> PWGHF: Temporary PID performance for Lc and add information for D0 bar

ALICE3/DataModel/ECAL.h, ALICE3/Tasks/pidRICHqa.cxx, Common/TableProducer/PID/pidTOFbeta.cxx, Common/TableProducer/PID/qaTOFMC.cxx
=> Filling fRICH MC nsigmas

PWGDQ/Core/MCProng.h, PWGDQ/Core/MCSignalLibrary.h
=> PWGDQ/Core: add HF signals for LMEE

ALICE3/DataModel/ECAL.h, ALICE3/Tasks/ECALqa.cxx
=> Update ECAL qa task

PWGHF/DataModel/HFCandidateSelectionTables.h, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/HFD0CandidateSelectorparametrizedPID.cxx, PWGHF/TableProducer/HFLcCandidateSelectorparametrizedPID.cxx, PWGHF/Tasks/CMakeLists.txt, PWGHF/Tasks/taskD0parametrizedPID.cxx, PWGHF/Tasks/taskLcparametrizedPID.cxx
@ginnocen This is the temporary task of parametrized PID selection for D0 and Lc reconstruction
=> PWGHF: PID parametrization for ALICE3 HF study

PWGDQ/Core/MCSignalLibrary.h
Adding muon signal to MCSignalLibrary.h
=> PWGDQ: Adding muon signal to MCSignalLibrary.h

PWGCF/Core/AnalysisConfigurableCuts.h, PWGCF/Core/PWGCFCoreLinkDef.h, PWGCF/Tasks/match-reco-gen.cxx
Basic track selection criteria can now be configured from the command line and `.json` file
=> Configurable for track selection criteria

EventFiltering/PWGHF/HFFilter.cxx
- add configurables to fill only signal/background
- add possibility to apply a scaling factor to limit size of derived tables
=> Event filtering: add possibility to fill derived tables with only signal/bkg

EventFiltering/CMakeLists.txt, EventFiltering/PWGJE/jetFilter.cxx, EventFiltering/filterTables.h
With this commit we have introduced event filtering for minimum bias events containing a high-pT charged jet  or a high-pT charged track
=> Added event selection for high pT ch jets + tracks

ALICE3/TableProducer/alice3-trackextension.cxx, ALICE3/TableProducer/alice3-trackselection.cxx, PWGDQ/Tasks/v0selector.cxx, PWGHF/TableProducer/HFD0CandidateSelectorALICE3Barrel.cxx, PWGHF/TableProducer/HFTrackIndexSkimsCreator.cxx, PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/cascadefinder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx, PWGLF/TableProducer/lambdakzerofinder.cxx
Preparing removing `TracksCov` from `FullTracks`
=> Reducing usage of TracksCov

Common/TableProducer/CMakeLists.txt, Common/TableProducer/trackextension.cxx
I created it in a specific branch to have my master available
I will transfer the comments from the previous PR draft
After that I will update it with the comments implemented
=> Run 3 DCA extraction

CODEOWNERS, PWGPP/Tasks/qaEventTrack.cxx
Currently this is for reference / discussions only. Not yet ready to be merged.
=> add QA task for event and track quantities on AOD level

Tutorials/src/histogramsFullTracks.cxx
to keep benchmarks consistent...
=> make sure to access all three track tables

PWGJE/Tasks/emccellmonitor.cxx
- Add option to reject certain BC IDs
- Add monitoring histograms for BC ID
before and after selection for events
and cells
=> [EMCAL-733] Add option to reject BC IDs

PWGMM/Tasks/dndeta.h
* use new isPhysicalPrimary()
* remove obsolete DCA cut at gen level
* add a flag to enable/disable event selection
=> PWGMM: update dndeta task

EventFiltering/PWGCF/CFFilter.cxx
Missing PID check included for protons and antiprotons
=> Include PID check for ppp trigger

DPG/Tasks/qaEfficiency.cxx
- Add event selection
- Add Y dependent efficiency
- Add TOF efficiency
=> Extend efficiency

DPG/Tasks/qaImpPar.cxx
- PROCESS_SWITCH implemented
- add possibility to use sel8() event selection
=> DPG: updates in Impact Parameter task

PWGDQ/Tasks/filterPP.cxx
The use of the partitions suddenly make the task crash. While it is investigated, a workaround without is put in place so the task still works
=> Partition not working. Use of a workaround

EventFiltering/PWGLF/strangenessFilter.cxx
@ChiaraDeMartin95 please have a look
=> WIP: LF triggers, make event selection configurable + fix in input tables

PWGCF/FemtoDream/femtoDreamPairTaskTrackTrack.cxx, PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx, PWGCF/Tasks/correlations.cxx, PWGDQ/Tasks/dileptonEE.cxx, PWGDQ/Tasks/dileptonMuMu.cxx, PWGDQ/Tasks/tableReader.cxx, Tutorials/src/eventMixing.cxx
Follow-up to AliceO2Group/AliceO2#7781
=> Adjust analysis tasks for GroupSlicer separated from AnalysisTask.h

PWGLF/Tasks/spectraCharged.cxx
FIll the histograms, additionally and add multPtSpec_trk_meas_evtcont 
@mario-krueger @yelmard
=> Fill histograms and add additional ones

PWGLF/Tasks/spectraCharged.cxx
- fix true multiplicity definition (count only primaries)
- avoid ambiguous collisions for now as it is not clear how to handle them
- select on zvtx position also for reconstructed collisions
=> PWGLF: several small fixes to chargedSpectra task

PWGDQ/Core/MCSignalLibrary.h
Psi(2S) signals added
Note: CLang Fixed as you suggest:
=> Modifications

PWGHF/Tasks/qaPidRejection.cxx
MC::isPhysicalPrimary will be removed.
=> PWGHF: Fix isPhysicalPrimary

PWGHF/TableProducer/HFD0CandidateSelectorparametrizedPID.cxx, PWGHF/TableProducer/HFLcCandidateSelectorparametrizedPID.cxx, PWGHF/Tasks/taskD0parametrizedPID.cxx
@vkucera Small changes in PID condition to avoid PID rejection at highpT and Add histogram to calculate a correction factor for Fiducial acceptance
=> PWGHF: Small changes in PID condition to avoid PID rejection at highpT and histogram for  Fiducial acceptance correction

PWGHF/TableProducer/HFBPlusToD0PiCandidateSelector.cxx
Re-Introducing Impact Parameters of B+ daughters
=> PWGHF: cut on Impact parameters of B+ daughters

PWGDQ/Tasks/filterPP.cxx
Adaptation of the subtasks in the FilterPP task to use the PROCESS_SWITCH functions
+ Removal of the Covariant track barrel info
+ Changing some function names for clarity
=> Adaptation of the FilterPP code to PROCESS_SWITCH functions

Tools/PIDML/qaPid.cxx
@Lukaszz99 - please see if it is OK for you.
=> PID ML: Add Bayes strategy to QA PID task

DPG/Tasks/qaImpPar.cxx
- filter on number of PV contributors
- possibility to enable/disable the diamond constraint (removed by defualt)
- possibility to avoid excluding tracks from PV refit (for debug)
=> DPG: further options for PV

PWGCF/DataModel/DptDptFiltered.h, PWGCF/TableProducer/dptdptfilter.cxx, PWGCF/TableProducer/dptdptfilter.h, PWGCF/Tasks/dptdptcorrelations.cxx, PWGCF/Tasks/dptdptfilterqa.cxx, PWGCF/Tasks/match-reco-gen.cxx
Also
- fixing double counting when no PID
- not selected by PID should not pass the filtering
- removed not needed using
- fixing not used warnings
=> Rolling back bool columns to uint8_t

DPG/Tasks/qaEfficiency.cxx
- Add trk info + phi eta maps
- Move to a sigle struct per charge
=> Extend efficiency task

PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/HFTreeCreatorBplusToD0Pi.cxx, PWGHF/Tasks/taskBPlus.cxx
=> PWGHF: B+ Tree Creator

PWGJE/TableProducer/emcalCorrectionTask.cxx
Convention for phi to be compatible
with the EMCAL geometry
implementation which uses 0 - 2 pi
in azimuth.
=> [EMCAL-670] Store cluster position in phi from 0 to 2 Pi

EventFiltering/PWGMM/multFilter.cxx, EventFiltering/filterTables.h
V0A info has been added, fix for mult transv
=> V0A info has been added, fix for mult transv

PWGLF/Tasks/spectraCharged.cxx
Add histogram, update McParticles, and fix bugs @mario-krueger @yelmard
=> Update spectraCharged, add histogram

Common/TableProducer/PID/pidTPC.cxx
- Add possibility to fetch the response parametrization with the timestamp
- timestamp task is now a dependency of the TPC PID task
=> PID: add possibility to use timestamp for Param

Common/TableProducer/trackPropagation.cxx
adding covariant matrix to track propagation task
adding track covariance propagation
=> adding Cov Matrices to track propagation

PWGEM/Tasks/CMakeLists.txt, PWGEM/Tasks/gammaConversions.cxx, PWGEM/Tasks/gammaConversionsmc.cxx
Add histos, tune binnings, introduce dynamic
retrieval of pointers of  histograms to be filled.
That is, get rid of registry.fill(HIST("compile
timeConstant" calls.
=> PWGEM/Tasks/gammaConversionsmc.cxx Add histos and enhance

Tutorials/src/mcHistograms.cxx
Motivated by https://alice.its.cern.ch/jira/browse/O2-2808
=> MCHistogram: Add simple analysis on physical primaries

Tutorials/CMakeLists.txt, Tutorials/OpenData/CMakeLists.txt, Tutorials/OpenData/flowAnalysis.cxx
This adds a first version of a flow analysis task, used to validate a similar open data demonstrator task.
=> OpenData: Added first version of flow task.

Common/Core/TrackSelection.h
@mario-krueger I think this should be needed to ask for real global tracks, what do you think?
=> Update Run3 track selection

PWGCF/FemtoDream/femtoDreamProducerReducedTask.cxx, PWGCF/FemtoDream/femtoDreamProducerTask.cxx
Change needed to run with Hyperloop
=> Fix producer

PWGMM/Tasks/CMakeLists.txt, PWGMM/Tasks/lumi.cxx
=> [PWGMM] refit PV

PWGLF/Tasks/lambdakzeroanalysis.cxx, PWGLF/Tasks/lambdakzeroanalysisMC.cxx
fixes: add abs() to armenteros cut & fix tpcPID for antilambdas
=> lambdakzeroanalysis - more armenteros plots & fixes

Common/Core/aodMerger.cxx
@jgrosseo 🤞 (this time after 5 times I always get consistent results :D )
=> Initialise the memory used for VLA branches

Tools/PIDML/pidML.h, Tools/PIDML/pidMLProducer.cxx
- update the producer task with multiplicity and centrality info
- fix to work with older MC (MCParticles_000)
=> PID ML: update producer task

DPG/Tasks/qaEfficiency.cxx
- simplify TEfficiency making
- add efficiency for primary and secondary particles
=> DPG: update efficiency QA

Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFFull.cxx
- changes after https://github.com/AliceO2Group/AliceO2/pull/8293
=> PID TOF: use the central method to remove the T0 bias

Common/Core/PID/PIDResponse.h, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTPC.cxx
- Update pid tasks accordingly
=> PID: Update tiny table packing

PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqEfficiency.cxx
Adding flat dilepton table that can be produced through a specific process in dqEfficiency, to be used by external analysis.
=> Dilepton flat tables

PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
MCHBitMap vs Pt TH2 added in HistogramsLibrary. TableMaker will produce the plot
=> MCHBitMap vs Pt TH2 added in PWGDQ histo library

PWGJE/DataModel/EMCALClusters.h, PWGJE/TableProducer/emcalCorrectionTask.cxx, PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/emcclustermonitor.cxx
- first commit of simple task to plot various EMCAL cluster properties. 
- the EMCALCluster table was extended to include additional cluster properties
=> [EMCAL-734] added EMCAL cluster monitor task

Tutorials/OpenData/flowAnalysis.cxx
Flow parameters calculated now also for pi, K, p, and high pt.
=> Added PID analysis in flow task for open access.

PWGCF/FemtoDream/FemtoDreamTrackSelection.h
=> Fix for string view in cutculator

PWGJE/Tasks/emccellmonitor.cxx, PWGJE/Tasks/emcclustermonitor.cxx
- Selection / Rejection ConfigurableParam
as comma-separated string
- Rejection / Selection implemented
in cell-monitor and cluster-monitor
task
=> [EMCAL-670, EMCAL-734] Add option to select / reject multiple BCs

Tutorials/OpenData/flowAnalysis.cxx
Added INT7 selection, magnetic field phi correction and dpi QA histograms for pi and p.
- event selection made now via an integer instead of bool to allow in future other triggers than INT7. By default the task uses int7+sel7 selection.
=> Improvements for OpenData/flowAnalysis

PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/MCSignalLibrary.h, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/dqEfficiency.cxx
Adding dilepton-track process function for dqEfficiency
=> PWGDQ: Adding dilepton-track process function for dqEfficiency

EventFiltering/PWGLF/strangenessFilter.cxx
Co-authored by @ChiaraDeMartin95
=> Event Filtering: LF filter fix access to casc daughters 

EventFiltering/PWGMM/multFilter.cxx, EventFiltering/filterTables.h
removing redundant filters, removing event filtering, testing flatenicity using FV0 info
=> removing redundant filters, removing event filtering

PWGHF/DataModel/HFSecondaryVertex.h, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/candidateCreatorDstar.cxx
=> PWGHF: Add dummy D* candidate creator

PWGCF/Tasks/correlations.cxx
For testing: new vs old mixing interface, mixing inside and outside process(), Run 2 vs Run 3
=> New mixing interface in correlations.cxx

PWGMM/Tasks/CMakeLists.txt, PWGMM/Tasks/vertexing-fwd.cxx
@sarahherrmann and @aalkin  reopening the previous PR here.
=> Forward vertexing for ambiguous tracks

PWGDQ/Tasks/filterPP.cxx
Correction of an error in the attribution in the list of provided cuts.
=> Correction of slight error in filterPP cut

Common/Core/PID/PIDResponse.h, Common/TableProducer/PID/CMakeLists.txt, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFBase.cxx, Common/TableProducer/PID/pidTOFBase.h, Common/TableProducer/PID/pidTOFFull.cxx, PWGLF/Tasks/spectraTOF.cxx, PWGLF/Tasks/spectraTOFtiny.cxx
- Now the user can access the information of the T0 during the analysis
- Update spectra tasks to subscribe to TOF flags
=> PID: Add table for TOF PID flags

PWGDQ/Core/HistogramsLibrary.h
Changing the binning of the DCA histograms
=> PWGDQ: DCA plot binning fix

Tools/PIDML/pidOnnxModel.h, Tools/PIDML/qaPidML.cxx, Tools/PIDML/simpleApplyPidOnnxModel.cxx
This will enable analysis on GRID
=> PIDML: Use github repository to access model files

PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqEfficiency.cxx
Adding MC truth template for dilepton-track
=> PWGDQ: adding MC truth template for dilepton-track

Common/Core/PID/PIDResponse.h, Common/DataModel/FT0Corrected.h, Common/TableProducer/PID/pidTOFBase.cxx, Common/TableProducer/PID/pidTOFbeta.cxx, DPG/Tasks/qaPIDTOF.h, DPG/Tasks/qaPIDTPC.h
This requires https://github.com/AliceO2Group/O2Physics/pull/639 to be merged before
=> Include T0 Event time in TOF Event time computation

DPG/Tasks/qaEfficiency.cxx
- Add ITS-TPC efficiency
- Add possibility to run QA on data on hyperloop
=> DPG: Unify qa Eff. in data and MC

Common/TableProducer/PID/CMakeLists.txt, DPG/Tasks/CMakeLists.txt, DPG/Tasks/qaEventTrack.cxx, DPG/Tasks/qaPIDTOFMC.cxx, DPG/Tasks/qaPIDTPCMC.cxx
- Avoid creating output histograms if not needed
- Move McParticles_000 to McParticles
=> Move QA tasks for PIDMC to DPG

PWGMM/Tasks/vertexing-fwd.cxx
Changes added by @sarahherrmann to run over new and older productions.
=> Add table for AmbiguousTracksMFT

PWGDQ/Tasks/v0selector.cxx
fix to Join<tracks, pidbits>
remove Omega -> Lambda K. (as TOF can easily select charged Kaons)
remove unnecessary photon QA.
=> update on PWGDQ/Tasks/v0selector.cxx

Common/Core/PID/PIDResponse.h, Common/Core/PID/PIDTOF.h, Common/TableProducer/PID/pidBayes.cxx, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFBase.cxx, Common/TableProducer/PID/pidTOFFull.cxx, Common/TableProducer/PID/pidTOFbeta.cxx
=> PID: Simplify workflow for Ev. Time

PWGDQ/Tasks/dqEfficiency.cxx
Adding process function for B+ analysis
=> PWGDQ: Adding process function for B+ analysis

PWGLF/Tasks/spectraCharged.cxx
Reverts AliceO2Group/O2Physics#888
=> Revert "PWGLF: dont mix int and double"

Common/DataModel/TrackSelectionTables.h
With this we are more differential in the cuts and we build similar cuts with filter bits
=> Add more masks for track cuts

Common/TableProducer/PID/pidTOFBase.cxx
=> PID: Fix CPU usage in slices

DPG/Tasks/qaEventTrack.cxx
@mfaggin here is what we discussed
=> DPG: Add monitoring of IU tracks

DPG/Tasks/qaEventTrack.cxx
@mfaggin with this we A) extend the monitoring B) fix an issue with the track loop, could you please also have a look?
=> DPG: Extend IU track monitoring

PWGMM/Mult/Tasks/dndeta.cxx
* Event selection efficiency vs mult histogram
* Cut on Z_rec - Z_gen
=> PWGMM: dndeta/multiplicity: Add mult efficiency

Common/Tasks/eventSelectionQa.cxx, PWGEM/PhotonMeson/Tasks/emcalPi0QC.cxx, PWGHF/TableProducer/HFBPlusToD0PiCandidateSelector.cxx, PWGHF/TableProducer/HFCandidateCreatorBPlus.cxx, PWGHF/TableProducer/HFCandidateCreatorChic.cxx, PWGHF/TableProducer/HFCandidateCreatorLb.cxx, PWGHF/TableProducer/HFCandidateCreatorX.cxx, PWGHF/TableProducer/HFCandidateCreatorXicc.cxx, PWGHF/TableProducer/HFChicToJpsiGammaCandidateSelector.cxx, PWGHF/TableProducer/HFLbToLcPiCandidateSelector.cxx, PWGHF/TableProducer/HFXToJpsiPiPiCandidateSelector.cxx, PWGHF/TableProducer/HFXiccToPKPiPiCandidateSelector.cxx, PWGHF/Tasks/taskBPlus.cxx, PWGHF/Tasks/taskLb.cxx, PWGJE/Tasks/emccellmonitor.cxx, PWGJE/Tasks/emcclustermonitor.cxx, PWGUD/Tasks/diffMCQA.cxx, PWGUD/Tasks/diffQA.cxx
Required by https://github.com/AliceO2Group/AliceO2/pull/9265
=> Framework: enforce references in process() arguments

DPG/Tasks/qaEventTrack.cxx
- Add track selection histogram
- Add possibility to select pt, eta, phi of tracks
- Simplify filters/partitions
=> DPG: Update QA ev track

PWGDQ/TableProducer/tableMakerMC.cxx
fills the mch correctly in the MC reduced tables
=> MCH Match index in mc tables

PWGLF/Tasks/v0cascadesqa.cxx
This code is coauthored by Klaudia (klaudia.sajdakova@cern.ch)
=> Fix QA task for v0s and cascades

PWGLF/TableProducer/lambdakzerobuilder.cxx
Hi @ddobrigk, I think the changes of this commit should be propagated also to processRun3 otherwise it crashes https://github.com/AliceO2Group/O2Physics/commit/5ffe363208e4f66044be0852983e13d4dfa13a5f
Is that ok?
=> Fix histogram names for processRun3

Common/DataModel/TrackSelectionTables.h
In line with documentation: https://github.com/AliceO2Group/analysis-framework/pull/146
=> Add more track selection columns

PWGCF/MultiparticleCorrelations/Tasks/CMakeLists.txt, PWGCF/MultiparticleCorrelations/Tasks/multiparticle-correlations-ar.cxx
Adding code skeleton for a new user task in the PWGCF/MultiparticleCorrelations area.
=> PWGCF: Add code skeleton to PWGCF/MultiparticleCorrelations

PWGMM/Mult/Tasks/dndeta.cxx
=> PWGMM: dndeta: add track selection and more control histos

PWGDQ/Core/MCSignalLibrary.h
One more MC signal for dielectron efficiency purpose
=> One more MC signal for dielectron efficiency

DPG/Tasks/qaMatchEff.cxx
- Track selection development: Mattia Faggin
- Check plots and binning changes: Rosario Turrisi
=> DPG: add track selections and check plots, modify binning

PWGHF/DataModel/HFSecondaryVertex.h, PWGHF/HFC/TableProducer/CMakeLists.txt, PWGHF/HFC/TableProducer/HFCorrelatorDplusHadrons.cxx, PWGHF/HFC/Tasks/CMakeLists.txt, PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
Dplus-hadron pairs table added for Dplus-hadron correlation task.
I will also add the correlation task soon.
=> PWGHF: Dplus-hadron pair tables added

PWGMM/Mult/Tasks/dndeta.cxx
* remove obsolete configurables
* remove obsolete fill statements
=> PWGMM: dndeta: Use track selection flag instead of explicit cut

CODEOWNERS
@lramona @alcaliva @lbariogl @BongHwi @lbarnby @mbombara @iravasen @njacazio I miss the users for Sourav and Chiara what do you think about this? I propose that we extend the merging to coordinators, but keep the same structure so that we avoid too much fragmentation, this PR is to discuss what to do
=> Add coordinators to codeowners

DPG/Tasks/qaPIDTOF.h, DPG/Tasks/qaPIDTPC.h
@AnnalenaKa thanks for the feedback! Added them back and few fixes/improvements!
=> Fix missing TOF plots

PWGHF/Tasks/HFMCValidation.cxx
This PR adds histograms to monitor:
- position of reco PV
- number of BCs associated to ambiguous tracks
- number of collisions associated to ambiguous tracks
- dispersion of collisions in Z direction compatible with an ambiguous track
- probability to associate tracks that have TOF matching to correct PV
=> PWGHF: add more checks for track-to-collision association

PWGCF/CMakeLists.txt, PWGCF/Tutorial/CFTutorialTask0.cxx, PWGCF/Tutorial/CFTutorialTask1.cxx, PWGCF/Tutorial/CFTutorialTask2.cxx, PWGCF/Tutorial/CFTutorialTask3.cxx, PWGCF/Tutorial/CFTutorialTask4.cxx, PWGCF/Tutorial/CFTutorialTask5.cxx, PWGCF/Tutorial/CMakeLists.txt, PWGCF/Tutorial/README.md, PWGCF/Tutorial/run-config.json, PWGCF/Tutorial/run.sh
Hi,
@lbariogl @zchochul  and me prepared the first Femto PAG tutorial which is happening the next week.
There will be more tutorial sessions in the future, and this Tutorial directory will serve to contain all tutorial materials for easy reference.
=> PWGCF: Add files for the first femto tutorial session

DPG/Tasks/qaEventTrack.cxx, DPG/Tasks/qaEventTrackLite.cxx
=> Add check on size

PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/Tasks/cascadeanalysis.cxx
- updates the cascade builder to avoid naming confusion in indices in the future
- updates cascade analysis to be also aware of ITSSA tracking possibility (still to be tested in Run 3) + further adjustments
=> Update cascade builder, analysis

PWGMM/Lumi/Tasks/lumi.cxx
=> [PWGMM] change type

PWGJE/DataModel/Jet.h
=> WIP: Add tables for HF jets

PWGMM/Lumi/Tasks/lumi.cxx
=> [PWGMM] delete unused headers

PWGMM/Lumi/Tasks/lumi.cxx
add magnet info and corresponding headers
=> [PWGMM] add magnet info and corresponding headers 

PWGHF/HFC/Tasks/taskFlow.cxx
=> PWGHF: Add cautionary comments to the flow task

DPG/Tasks/AOTTrack/qaEventTrack.cxx
@njacazio here the fix to the bug that was creating our headache.
=> DPG: bug fix for track index update in processDataIU,IUFiltered.

PWGDQ/Core/CutsLibrary.h
Adding more cuts for electron PID in the CutsLibrary.h to
=> More Cuts for large scale testing

PWGHF/HFC/Tasks/taskFlow.cxx
Split process functions based on the desired correlation case: h-h, HF-h or h-MFT
=> PWGHF: split process functions

EventFiltering/PWGLF/strangenessFilter.cxx
=> Add QA histos to LF filter

PWGLF/Tasks/v0cascadesqa.cxx
=> Fix efficiency computation for V0s + qa histos

PWGLF/TableProducer/lambdakzerobuilder.cxx
@AnnalenaKa this should do it! Note that it is a quick edit, though, so could you please check what I did? @njacazio, could you please also look at the code? Please be super critical and shout if it doesn't make sense! Thanks!
=> Adjust path check

PWGDQ/Core/CutsLibrary.h
Adding a cut for MCH-MID matched tracks
=> PWGDQ: Adding cut for MCH-MID tracks

PWGLF/TableProducer/lambdakzerobuilder.cxx
Hi @ddobrigk and @njacazio 
I tried to run the lambdakzerobuilder on the LHC22e data and the error about the grp object not being found still showed up. After another check and chat to Mattia we saw that the timestamp was also hardcoded and and this was leading to an error when getting the object. I changed that to the timestamp being taken from the bc. My test on the LHC22e set was running this time. But of course there could be some problem that I missed with Run 2 data. 
@ddobrigk of course this is your task and I don't mean to interfere. This is just a proposal to make the task working for the LHC22e and LHC22f datasets as well where we had some issues. Feel free to modify or delete my changes and suggestions as you wish.
I am sorry for not spotting this issue two days ago when going …
=> LambdakzeroBuilder: Timestamp from bc

Tutorials/src/eventMixing.cxx, Tutorials/src/eventMixingValidation.cxx
Hi @jgrosseo 
here is a use example of the new mixing variables.
Making it a draft until https://github.com/AliceO2Group/AliceO2/pull/9648 gets merged.
=> Event mixing: Mixing counters

DPG/Tasks/AOTTrack/qaEventTrack.cxx
- add correation plot eta vs. phi
- add counter for ambiguous tracks
=> [DPG]: update control plots for qaEventTrack.cxx

PWGHF/HFC/Tasks/taskFlow.cxx
* added processMC flag to avoid trigger selection when running on Run2 MC
* fix in HF mixing: collisions are grouped in bins of charged-particle multiplicity
=> PWGHF: MC flag, group collisions based on Nch in HF mixing

PWGDQ/Macros/README.md, PWGDQ/Macros/tutorial.py
fix typo in readme and tutorial.py
=> [PWG-DQ] fix typo in macros

PWGLF/TableProducer/cascadebuilder.cxx
Hi @ddobrigk, I realized that the cascadebuilder was also crashing on the GRP path check, so I tried to fix it following the most recent commits made on the lambdakzerobuilder in the past days.
This works for me now, could you have a look? Thanks!
=>  Adjust GRP path check + take timestamp from bc

DPG/Tasks/AOTTrack/qaEventTrack.cxx
@saganatt @apalasciano this PR shall fix the issue for run 2 converted data. You shall disable all the process functions and use the new ones `processRun2ConvertedData` or `processRun2ConvertedMC`. Let me know in case of further problems.
=> [DPG] add process for run 2 converted data.

EventFiltering/PWGJE/jetFilter.cxx, EventFiltering/filterTables.h, PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/ChJetTriggerQATask.cxx
This is code written by Filip (I am committing since his O2Physics build is broken) and adds some features for the charged jet trigger plus a QA task
=> Changes to Jet Trigger and addition of QA task on behalf of Filip

EventFiltering/PWGMM/multFilter.cxx, PWGMM/Mult/Tasks/flatenicityFV0.cxx
adding pTtrigger in flatenicity task
=> updating the weights

PWGDQ/Core/CutsLibrary.h
Adding more PID cuts sets for electron selection
Adding 2 other options for Low Pair Mass Cuts
=> More Cut options in the CutsLibrary.h

Common/Tasks/eventSelectionQa.cxx
to be used for rate-vs-time accounting
=> Set orbit-axis binning from ECS GRP

DPG/Tasks/AOTTrack/qaMatchEff.cxx
two new process functions added - just to get rid of track-collision association
=> added processing of tracks w/o loop on collisions

PWGDQ/Tasks/v0selector.cxx
PWGDQ/Tasks: fix pid for v0selector
=> PWGDQ/Tasks: fix pid for v0selector

PWGDQ/Core/CutsLibrary.h
Increase electron acceptance of tic from 100 to 110 in dEdx
=> PWGDQ: increase acceptance of tpc dEdx

PWGCF/FemtoWorld/Core/FemtoWorldContainer.h, PWGCF/FemtoWorld/Core/FemtoWorldParticleHisto.h, PWGCF/FemtoWorld/DataModel/FemtoWorldDerived.h, PWGCF/FemtoWorld/TableProducer/femtoWorldProducerTask.cxx, PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskTrackPhi.cxx
* Added invariant mass histogram for phi candidates
=> Femtoworld updates

Common/Core/CMakeLists.txt, Common/Core/TrackSelectionDefaults.cxx, Common/Core/TrackSelectionDefaults.h, Common/TableProducer/trackselection.cxx
@mfaggin what do you think of this?
=> Add customizable track selection

PWGMM/Lumi/Tasks/lumi.cxx
=> [PWGMM] updates for table production

Common/Tasks/eventSelectionQa.cxx
* col-vs-ft0 bc diff analysis for colisions with TRD
* track-vs-ft0 bc diff for ITSTPC-only tracks
=> Added col-vs-ft0 for colisions with TRD

PWGLF/DataModel/LFResonanceTables.h
Fix TOF PID issues when the track pool contains `TrackExtra`.
=> fix TOF PID issue

PWGLF/Tasks/spectraTOF.cxx
- Add efficiency
- Add even more plots
=> Extend spectra TOF task

PWGLF/Tasks/QC/v0cascadesqa.cxx
=> Additional debug histograms for V0s + evt selection

PWGHF/TableProducer/HFBPlusToD0PiCandidateSelector.cxx, PWGHF/TableProducer/HFCandidateCreatorBPlus.cxx, PWGHF/Tasks/taskBPlus.cxx
- Process_Switch added to B+ Task
- Related PR: https://github.com/AliceO2Group/Run3Analysisvalidation/pull/327
=> PWGHF: Include process_switch in B+ task

PWGLF/Tasks/QC/v0cascadesqa.cxx
=> Change histograms range

PWGLF/Tasks/QC/v0cascadesqa.cxx
=> 2D histo Radius vs Pt for V0s

Common/Core/CMakeLists.txt, PWGUD/Core/CMakeLists.txt, Tools/PIDML/CMakeLists.txt
=> Make dependency on ROOT::EG O2::CCDB explicit

PWGHF/HFC/TableProducer/HFCorrelatorD0D0bar.cxx, PWGHF/HFC/TableProducer/HFCorrelatorD0D0barBarrelFullPID.cxx, PWGHF/HFC/TableProducer/HFCorrelatorDplusDminus.cxx
Feature previously lost when switching from Filters to Partitions for the D meson selection
=> Add slicing of D meson tables by collisions

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Update the efficiency task adding the ULS and LS, the efficiency as a function of MC variables for rec.
=> Update of the efficiency task

Tools/PIDML/README.md, Tools/PIDML/pidOnnxInterface.h, Tools/PIDML/pidOnnxModel.h, Tools/PIDML/simpleApplyPidOnnxInterface.cxx, Tools/PIDML/simpleApplyPidOnnxModel.cxx
Hi @ddobrigk , let me know if this README is fine or whether you prefer adding such information to the official O2 Analysis documentation.
=> PID ML: Add readme for users

PWGLF/DataModel/LFResonanceTables.h, PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/phianalysis.cxx, PWGLF/Utils/collisionCuts.h
- Add MC table for resodaughters
- Revert TOF PID selection cut
=> Add MC functionality

EventFiltering/PWGHF/HFFilter.cxx
Hi @fgrosa , @zhangbiao-phy ! I send you this first shot so you can tell me if I am going in the right direction or not because I am not so confident about the lines I added ^^
I still need to determine the type of `scores` so I can define `candidates_vector`. Maybe this issue could be overcome by rebuilding an array made of `scores[0]`, `scores[1]` and `scores[2]` (that are floats I believe) and pushing it in the vector, but it would be better to have the type of `scores` I think.
PS: I don't know why but I had issues when I tried rebasing my branch with the master branch (that's why there are remnants of the previous PR for the invariant masses ^^)
=> Optimisation tree

PWGJE/TableProducer/jetfinderhf.cxx
to make is possible to run them on hyperloop
=> Instanstiate multiple HF jet finders by default

PWGCF/MultiparticleCorrelations/Tasks/multiparticle-correlations-ar.cxx
- Add configurable to silence the output of the task
- Rework configurable using ConfigurableAxis and LabelArrays
=> PWGCF: Update task multiparticle-correlations-ar

PWGDQ/Core/CutsLibrary.h, PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/tableReader.cxx
HI Ionut
We add the option to save the V0 candidates on the table maker and fill the ND histogram via the table reader.
We validate the code locally. 
Cheers
Xiaozhi
=> Add the option to save the V0 candidates able maker and table reader

DPG/Tasks/AOTTrack/PID/CMakeLists.txt, DPG/Tasks/AOTTrack/PID/qaPIDTOFBeta.cxx, DPG/Tasks/AOTTrack/PID/qaPIDTPC.h
=> Add task for TOF beta QA

PWGMM/Lumi/macros/merger.C, PWGMM/Lumi/macros/non_fac.C
updates on macros for luminous region fits
=> [PWGMM] updates on macros for luminous region fits

Common/CCDB/TriggerAliases.cxx, Common/CCDB/TriggerAliases.h, Common/CCDB/macros/upload_trigger_aliases_run3.C
First attempt to add trigger aliases for Run 3
=> kTVXinTRD and kTVXinEMC aliases added

PWGDQ/Tasks/v0selector.cxx
PWGDQ/Tasks: change n sigma cuts for v0 selection
=> PWGDQ/Tasks: change n sigma cuts for v0 selection

PWGDQ/Core/CutsLibrary.h
Add 3 additional pT cuts for muon tracks + fix of a bug
=> Additional pT cuts for muon tracks

PWGDQ/Tasks/v0selector.cxx
PWGDQ/Tasks: change QA histograms in v0selector
=> PWGDQ/Tasks: change QA histograms in v0selector

PWGUD/DataModel/UDTables.h, PWGUD/TableProducer/UPCCandidateProducer.cxx
* Add configurable range to check for FT0 signals
* Add isAmbiguous and isPVContributor flags for UD tracks
=> Update for UPC candidate producer

PWGDQ/Tasks/v0selector.cxx
PWGDQ/Tasks: update v0selector for photon conversion
=> PWGDQ/Tasks: update v0selector for photon conversion

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
Added first version of the lmee-lf-cocktail task.
(corresponds to https://github.com/alisw/AliPhysics/blob/master/PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx in Run2)
=> PWGEM: added lmee-lf-cocktail task

PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
HI 
I add a histogram for the ITS matching study. 
Cheers
Xiaozhi
=> add the istclusterMap for the ITS matching study

Common/TableProducer/trackextension.cxx, Common/TableProducer/trackselection.cxx, DPG/Tasks/AOTTrack/CMakeLists.txt, DPG/Tasks/AOTTrack/qaTrackSelection.cxx
- In track selection task add compatibility mode for tracks without IU
=> DPG: Add track sel QA task

PWGMM/Mult/Tasks/dndeta.cxx
* remove extra includes that are not needed
=> PWGMM: dndeta: add more control histograms

PWGMM/Mult/DataModel/bestCollisionTable.h, PWGMM/Mult/TableProducer/trackPropagation.cxx, PWGMM/Mult/Tasks/dndeta.cxx
* Separate reassignment table and refitted parameters table
* Use original track parameters in histograms
* Add separate DCA histograms for reassigned tracks
=> PWGMM: dndeta: update

PWGMM/Mult/TableProducer/trackPropagation.cxx
Compare absolute values of DCA
=> PWGMM: fix DCA check in ambiguous track propagation

Common/Tasks/CMakeLists.txt, Common/Tasks/cpvQa.cxx
Hello! This is a simple qa task for cpv detector.
=> Add CPV QA task

PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
=> LF: GRPMag fix for weak decay vtx

DPG/Tasks/AOTTrack/qaK0sTrackingEfficiency.cxx, PWGLF/TableProducer/cascadebuilder.cxx
- catch runtime errors of secondary vertexer
=> Extend V0 tracking QC

DPG/Tasks/AOTTrack/PID/CMakeLists.txt, DPG/Tasks/AOTTrack/PID/qaPIDWithV0s.cxx, DPG/Tasks/AOTTrack/qaTrackSelection.cxx
=> DPG PID: Add PID with V0s

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/v0gammaQA.cxx
=> PWGEM/Dilepton/Tasks: add v0gamma QA

PWGDQ/Core/CutsLibrary.h, PWGDQ/Core/MCSignalLibrary.h
Add same cuts for Run 2 converted data and Run 3 + add the requirement of physical primary for electrons from pi0
=> Add same cuts for Run 2 & 3

PWGEM/Dilepton/Tasks/v0gammaQA.cxx
PWGEM/Dilepton/Tasks: add event mixing
=> PWGEM/Dilepton/Tasks: add event mixing

DPG/Tasks/AOTTrack/PID/qaPIDWithV0s.cxx, DPG/Tasks/AOTTrack/qaTrackSelection.cxx
- Add more debug histos
- Extend track sel task
=> DPG: Update pid from V0s

PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
- Add histos to count them
@ddobrigk
=> LF: Catch fitter exceptions

PWGLF/DataModel/LFParticleIdentification.h, PWGLF/TableProducer/CMakeLists.txt, PWGLF/TableProducer/lfTPCPID.cxx
- Add param
- Add first try at LF tables for pid (for now kept as commented)
=> PWG-LF: Add simple LF particle identification

DPG/Tasks/TOF/CMakeLists.txt, DPG/Tasks/TOF/tofSkimsTableCreator.cxx, DPG/Tasks/TOF/tofSkimsTableCreator.h
This adds a derived dataset for TOF
=> TOF: Add first data skimmer for recursive calib.

PWGLF/DataModel/LFNucleiTables.h, PWGLF/Tasks/LFNucleiBATask.cxx
- Add new process functions to run on vanilla AO2Ds
- Align naming of LF data model to standard
- Small fixes (dEdx range)
=> PWGLF: Update NucleiTask --> LF model

Common/TableProducer/timestamp.cxx
Sometimes CTP resets orbit after SOR (but before SOX). So ccdb query with SOR timestamp provides wrong orbitReset reference. It usually affects the first run in the fill. It is more reliable to use EOR timestamp to request orbitReset.
=> Quering orbitReset timestamp with EOR timestamp instead of SOR

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Run also on no-skimmed data to debug
=> Run also on no-skimmed data to debug

PWGEM/Dilepton/Tasks/v0gammaQA.cxx
=> PWGEM/Dilepton/Tasks: add configurable v0max_mee

PWGLF/TableProducer/lfTPCPID.cxx
- Filling full tables
- Computing nsigma
=> PWG-LF: Update pid strategy

EventFiltering/CMakeLists.txt, EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterHelpers.h, EventFiltering/PWGHF/HFFilterQC.cxx
- Move ML methods to helpers file
- Improve selection of events with multi-charm candidates
=> [Event filtering]: improvements in the code

PWGDQ/Core/HistogramsLibrary.h
add some histogram for ITS matching QC
=> Add some histogram for ITS matching QC

PWGLF/Tasks/QC/CMakeLists.txt, PWGLF/Tasks/QC/resonanceqa.cxx
A very preliminary version of the analysis task for resonance QA
=> PWGLF: Very Preliminary task for Resonance QA

PWGLF/DataModel/LFResonanceTables.h, PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/CMakeLists.txt, PWGLF/Tasks/k892analysis.cxx, PWGLF/Tasks/lambda1520analysis.cxx, PWGLF/Tasks/phianalysis.cxx, PWGLF/Utils/collisionCuts.h
- Split the daughter table into the track, v0 tables
- Split MC-related processes
- Working version of Phi/K* task
=> Update Resonance tasks

PWGHF/D2H/Macros/HFInvMassFitter.cxx, PWGHF/D2H/Macros/HFInvMassFitter.h, PWGHF/D2H/Macros/config_massfitter.json, PWGHF/D2H/Macros/runMassFitter.C
first version mass fitter for PWGHF/D2H
=> PWGHF: mass fitter for d2h

PWGDQ/Tasks/v0selector.cxx
add some configurables in v0selector
=> PWGDQ/Tasks: add some configurables in v0selector

PWGEM/Dilepton/Tasks/v0gammaQA.cxx
=> PWGEM/Dilepton/Tasks: add histograms in v0 QA

PWGDQ/Tasks/tableReader.cxx
Recovered the histogram grouping via the cut for PID
Xiaozhi
=> recoved the histogram groupming via the cut for PID

DPG/Tasks/AOTTrack/PID/qaPIDTOFBeta.cxx, DPG/Tasks/AOTTrack/PID/qaPIDTOFEvTime.cxx, DPG/Tasks/AOTTrack/PID/qaPIDWithV0s.cxx
=> DPG: Add Ev. Time efficiency

PWGLF/TableProducer/lfTPCPID.cxx, PWGLF/Tasks/spectraTOF.cxx
- Add use case for TOF spectra analysis
=> LFPID: add more checks

PWGCF/TableProducer/dptdptfilter.cxx, PWGCF/TableProducer/dptdptfilter.h
Also incorporated additional track filters and the 2D DCA cut
=> Incorporated the PbPb Run 3 system

PWGLF/DataModel/LFParticleIdentification.h, PWGLF/TableProducer/lfTPCPID.cxx
- Add different marker to each table to ensure that they are joinable
=> LFPID: Fix in tables, now joiable tables

PWGHF/TableProducer/candidateCreatorBplus.cxx, PWGHF/Tasks/taskBplus.cxx
- Process Switch introduced
- Load Magnetic Field from CCDB
- Mass selection window in B+ creator (B+ task: histogram range changed accordingly)
=> PWGHF: B+ Candidate Creator update

PWGLF/Tasks/CMakeLists.txt, PWGLF/Tasks/QC/v0cascadesqa.cxx, PWGLF/Tasks/cascqaanalysis.cxx, PWGLF/Tasks/v0qaanalysis.cxx
cc @ChiaraDeMartin95 @ddobrigk
=> LF: add PID to dau tracks + tasks for selections tuning

PWGEM/PhotonMeson/Tasks/emcalPi0QC.cxx
- Add mixed events and rotation background calculation
- Fix loop over collisions instead of whole timeframes
- Added opening angle cut
=> PWGEM/PhotonMeson: Add Background calculation to pi0QC task

Common/Core/RecoDecay.h
=> RecoDecay: Add Ω0c mass

PWGJE/TableProducer/emcalCorrectionTask.cxx
EMCAL correction task needs the event selection
task to monitor that the BC analysed was actually
triggered
=> [EMCAL-670] Correlate correction task to event selection

EventFiltering/PWGCF/CFFilter.cxx
This patch removes hard coded values and makes the three body trigger more configurable.
This is needed since the three body trigger is expected to be able to run in the same workflow as the two body trigger and they need to be able to consume the same columns produced by the FemtoDreamProducerTask.
=> PWGCF: Update Three Body Trigger

PWGLF/Tasks/hypertritonAnalysis.cxx
* adds simple 2d QA plots for relevant variables
* Removes unnecessary cov matrix subscription for reduction of memory footprint
=> Update hypertriton QA for tests

DPG/Tasks/AOTTrack/qaEfficiency.cxx, DPG/Tasks/AOTTrack/qaEventTrack.h, DPG/Tasks/AOTTrack/qaEventTrackLiteProducer.cxx
=> DPG: Add TRD efficiency

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/DataModel/mesonTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/produceMesonCalo.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- add skimming task for EMCal clusters
- add first draft of a neutral meson task for emcal to validate skimming task
=> PWG-EM: Add skimmer task for emcal clusters

DPG/Tasks/AOTTrack/PID/qaPIDTOF.cxx, DPG/Tasks/AOTTrack/PID/qaPIDTOFBeta.cxx, DPG/Tasks/AOTTrack/PID/qaPIDTOFEvTime.cxx, DPG/Tasks/AOTTrack/qaEventTrack.cxx
- Add resolution plot in qaEventTrack
=> DPG: extend TOF PID QA with TRD

PWGMM/Mult/Tasks/dndeta-hi.cxx
* make dcaZ, dcaXY 1D Histogram at -10 < z < 10 in processCounting
* make eta-phi 2D Histogram at -10 < z < 10 in processCounting
=>     PWGMM : development and modification dndeta-hi.cxx code

DPG/Tasks/AOTTrack/PID/qaPIDTOFBeta.cxx, DPG/Tasks/AOTTrack/qaEfficiency.cxx
- Add length vs last TRD cluster plot
=> DPG: remove efficiency computed for all particle

Common/DataModel/Centrality.h, Common/TableProducer/centralityTable.cxx
* adds FT0A, FT0C to the centrality data model 
* adds FT0A, FT0C to the table producer for centrality 
* work ongoing
=> Update cent data model, task with FT0C, FT0A

Common/Tasks/multiplicityQa.cxx
* necessary for proper Pb-Pb calibration
=> update binning handling

EventFiltering/PWGHF/HFFilter.cxx
@mikesas I added two histos with the Dstar0 and Dstar_s+ masses to check that we actually trigger on real signals
=> [Event Filtering] Add QA histo with pT vs mass for D*0 and Ds*+

PWGLF/TableProducer/lfTPCPID.cxx, PWGLF/Tasks/spectraTOF.cxx
- Remove subscription to tiny tables
- Add parametrizations for negative particles
=> LF: spectra task, add centrality FT0C

PWGMM/Mult/Tasks/dndeta-hi.cxx
* add centrality analysis code
* add pt distribution analysis code
=> PWGMM: dndeta-hi.cxx modified 

PWGMM/Mult/TableProducer/trackPropagation.cxx, PWGMM/Mult/Tasks/dndeta-mft.cxx
need new dependency : trackselection, centrality-table and multiplicity-table
=> [PWGMM][dndeta-mft] binned in centrality, and added INEL>0 event class

EventFiltering/CMakeLists.txt, EventFiltering/PWGUD/diffractionBCFilter.cxx, EventFiltering/filterTables.h
This is an event filter task which selects BCs instead of Collisions
=> Added BC filter diffractionBCFilter

PWGMM/Mult/Tasks/dndeta.cxx
=> PWGMM: dndeta: fix possible double-counting of reassigned tracks

PWGLF/Tasks/QC/straRecoStudy.cxx, PWGMM/Lumi/Tasks/lumi.cxx
=> [PWGMM] addition of headers

DPG/Tasks/AOTTrack/qaEventTrack.cxx
@ddobrigk this should implement your suggestion
=> DPG: add correlation PV contr. with TOF and with TRD.

EventFiltering/PWGLF/strangenessFilter.cxx
=> LF: Change TOF condition for strangeness filters

Common/DataModel/CaloClusters.h, Common/TableProducer/caloClusterProducer.cxx, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPHOS.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
add pcm, phos table producer and a neutral mesons task
=> PWGEM/PhotonMeson: add pcm, phos skimmer and a neutral mesons task

PWGLF/TableProducer/CMakeLists.txt, PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
@ChiaraDeMartin95 @ercolessi this should reduce memory consumption a bit. I'll continue playing around...
=> Builder cleanup

PWGLF/Tasks/NucleiHistTask.cxx
Added Process_switches and fixed some bugs.
=> Feature & Bugfix; added Process_switches

PWGDQ/Core/HistogramManager.cxx, PWGLF/Tasks/NucleiHistTask.cxx
I have introduced a new sub-group for TOF and TPC PID histograms with a finer variable binning.
- tpcpid_fine
- tofpid_fine
If those are not used the histograms have the standard fixed binning.
=> PWGDQ: Introduce variable binning for TOF and TPC PID hists

PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
Adding histograms for alignment studies
=> PWGDQ: adding histograms for QA

PWGMM/Lumi/Tasks/lumi.cxx
=> [PWGMM] change lib directory

PWGHF/TableProducer/trackIndexSkimCreator.cxx
This PR improve the memory usage of the HF vertexer:
- Reduces by default the number of bins for the histograms with many bins (adding the possibility to set them)
- Does not create the histograms when the `fillHistogram` flag is `false`
- Avoids the loading of the `TGeoManager` (as done by @ddobrigk for the strangeness)
This is the memory usage before the improvement on a `AO2D.root` file of the LHC22m dataset (pass2)
And this is after
@vkucera @cterrevo @ginnocen @fcolamar if there are no major issues I would ask you if it is possible to merge it asap because, as discussed today at the trigger meeting, the memory reduction is mandatory to test the HFFilter.
=> PWGHF: improve memory usage

PWGDQ/Tasks/dqFlow.cxx
Mainly uncomment some lines here to be able to perform acceptance and efficiency correction from CCDB, enable the FlowContainer output to extend the measurements, and cleanup the useless quantities not used in the task
=> PWGDQ: enable corrections from ccdb, flowcontainer, and cleanup 

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/MCtemplates.cxx
Adding a new task to produce MC templates for (Di-)electrons.
=> PWGEM: Add Task to produce MC templates

PWGMM/Lumi/Tasks/lumi.cxx
=> [PWGMM] updates on magfield

PWGDQ/Core/HistogramsLibrary.h, PWGDQ/Core/MCSignalLibrary.h
Introduce new MC signals to the MCSignalLibrary.h
specifically heavy flavour signals with decay into electrons
=> PWGEM: Update and introduce new MC signals for electrons (HF, charm and beauty)

EventFiltering/PWGLF/strangenessFilter.cxx
@ChiaraDeMartin95 @ercolessi: it is working now as the default vertex cut is at 20, but formally the code needs this change
=> Always fill the trigger decision

PWGDQ/Tasks/v0selector.cxx
=> PWGDQ/Tasks: read V0Datas in v0selector

PWGJE/Tasks/emccellmonitor.cxx
Histogram cell time vs. cell abs ID for each of the 4
BC phases
=> [EMCAL-733] Add histograms for time distribution in different BC phases

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/GammaTableProducer.cxx, PWGEM/PhotonMeson/TableProducer/produceMesonCalo.cxx, PWGJE/Tasks/emcclustermonitor.cxx
PWGEM:
- Add GammaTableProducer task to cut on EMCal photon candidates
- Add skimmed cell info table
- Changed EMCal skimming and neutral meson task accordingly
PWGJE:
- Add Cluster QA histograms for track matching
=> PWGEM: Add GammaTableProducer

EventFiltering/CMakeLists.txt, EventFiltering/PWGLF/strangenessFilter.cxx, PWGLF/Tasks/CMakeLists.txt, PWGLF/Tasks/cascqaanalysis.cxx
=> LF filters: add QA and move to PID Full 

PWGLF/Tasks/LFNucleiBATask.cxx
- Uncomment TOF proton histogram fill line
=> [PWGLF] LightNucleiTask - Small fix

PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
also needed for indirect initTGrid memory check study
=> Enable B bypass if desired (bugfix)

CODEOWNERS
To speed up the merging of quick fixes
=> Adding myself in all the trigger subdirs

EventFiltering/PWGJE/jetFilter.cxx, EventFiltering/PWGLF/nucleiFilter.cxx, EventFiltering/cefpTask.cxx, EventFiltering/filterTables.h
- Fix schema evolution treatment in CEFP
- Fix bin label assignment
- Remove collision id from output table
=> Change CEFP to deal with schema evolution

PWGLF/Tasks/LFNucleiBATask.cxx
@giovannimalfattore @njacazio Could you please have a look?
=> [BANucleiTask] modified histograms with TRD

PWGDQ/Core/CutsLibrary.cxx
Adding more cuts for tests on the filterPP file
=> Adding More Cuts To The CutsLibrary.cxx

PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
- removes setMatLUT call from first init to prevent a spurious crash due to an implict (and not-up-to-date) magnetic field initialization inside the propagator 
- preselector processBuildValiddEdx changes from TPCLf to TPCFull tables to be compliant with CEFP operations
=> strangeness builders adjustments / fixes

PWGMM/Mult/Tasks/dndeta-hi.cxx
* add the analysis code for tagging V0 particle
* make histogram for V0 particle mass
* make histogram for V0 daughter particle eta
* make 'runCounting' code to simplify process
=>     PWGMM : dndeta-hi.cxx

PWGLF/Tasks/LFNucleiBATask.cxx
- Fix beta plots p interval
- Small fixes
- Add additional configurable TPC cuts
=> [PWGLF] LightNucleiTask - Fix TPC cuts

EventFiltering/CMakeLists.txt, EventFiltering/PWGEM/photonFilter.cxx, EventFiltering/filterTables.h
First draft of EM filter for photons etc.
Content still to be discussed
=> First version of photon filter

PWGLF/Tasks/QC/straRecoStudy.cxx
@ercolessi @ChiaraDeMartin95 @njacazio @mfaggin let's see. This will be fun :-D
=> add ITS cluster map study for secondaries

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/Tasks/tableReader.cxx
Added the DCAxyz variable to VarManager
Introduced process function to run TableReader with skimmed covariance tracks
New histogram subgroup: dielectrons
Fixe some MegaLinter errors
=> PWGDQ/EM: Add DCAxyz variable to VarManager, new processFunction, new subclass in HistogramLibrary

DPG/Tasks/AOTTrack/qaImpPar.cxx
1. add number of contributors axis for post-processing analyses
2. remove the gemoetry loading, not used
=> Few improvements in the impact parameter workflow

PWGDQ/Core/CutsLibrary.cxx
Adding a tighter TOF electron selection down to pt = 0.3 GeV/c
Reduce electron selection to -3;2 nsigma
=> PWGEM: Adjust and add tighter PID cuts

EventFiltering/PWGCF/CFFilterAll.cxx
Add rejection for autocorrelated pairs of particles
=> PWGCF: Trigger update

PWGJE/Tasks/emccellmonitor.cxx, PWGJE/Tasks/emceventselectionqa.cxx
- Use filter for selection of EMCAL cells (caloType=1)
- Cache number of cells per BC ID in unordered map
in order to aviod internal loop over cells for each
collision for speed reason
=> [EMCAL-850] Use fiter for selection of EMCAL cells

PWGHF/Core/SelectorCuts.h, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreatorCascade.cxx, PWGHF/TableProducer/trackIndexSkimCreator.cxx
Draft of  trackIndexSkimCreator
- Implement a track index skim creator for the HF candidates having cascade prong
- Refer to the code from the PWGLF/TableProducer/cascadebuilder.cxx and PWGHF/TableProducer/candidateCreatorOmegac.cxx
=> PWGHF: Add HF cascade prong to trackIndexSkimCreator

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Tasks/filterPP.cxx
filterPP.cxx: removing "MyBarrelTracksTiny" because obsolete
CutsLibrary.cxx : adding more cuts
=> PWGDQ : updates to the CutsLibrary & filterPP

PWGLF/DataModel/LFF1Tables.h, PWGLF/TableProducer/CMakeLists.txt, PWGLF/TableProducer/f1protonInitializer.cxx
Table producer task to test f1 reconstruction and f1-proton trigger
=> PWGLF: F1proton trigger

PWGLF/Tasks/NucleiHistTask.cxx
For ability to analyse lower pT ranges
=> Changed ptBinning

PWGJE/Tasks/emccellmonitor.cxx
Simple counter, based on presence of EMCAL cell
(after filter)
=> [EMCAL-733] Add counters for triggered events / BC

PWGHF/D2H/Tasks/taskLcToK0sP.cxx, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreatorCascade.cxx
- bugfix in `invMassLcToK0sP` in HfCascCand
- setting B field in candidateCreatorCascade from ccdb (copied this from candidateCreator2(3)Prong, hope it is OK like that)
- updated some histograms in taskLcToK0sP
=> PWGHF: bugfix and updates to the Lc->K0sP workflow

EventFiltering/PWGCF/CFFilterAll.cxx, EventFiltering/PWGCF/CFFilterQA.cxx
Small update to CF-filter and its QA
=> PWGCF: Update trigger

PWGMM/UE/Tasks/uecharged.cxx
A 2D histogram named hEtaLeadingVsPtLeading was added and the headers were rearrange (no new headers were added)
=> Add a 2D histogram named hEtaLeadingVsPtLeading

EventFiltering/PWGJE/fullJetFilter.cxx, EventFiltering/filterTables.h, PWGJE/Tasks/FullJetTriggerQATask.cxx
Added gamma trigger and qa
QA now includes the option to include only jets inside the EMCAL
Added leading jet/cluster spectra
=> Added gamma trigger and qa, some changes to full jet trigger qa

EventFiltering/CMakeLists.txt, EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterMLTrainings.cxx, EventFiltering/PWGHF/HFFilterPrepareMLSamples.cxx
@zhangbiao-phy I separated the process function for the ML trainings in a dedicated task to have a better organisation of the code.
=> [Event Filtering] Separate process function for ML trainings in dedicated task

Common/DataModel/CaloClusters.h, Common/TableProducer/caloClusterProducer.cxx, EventFiltering/PWGEM/photonFilter.cxx, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/skimmerPHOS.cxx, PWGEM/Tasks/phosCluQA.cxx, PWGEM/Tasks/phosPi0.cxx
Switch from BC in index to Collision + additional table of PHOS events without collision, a-la EMCAL.
Correct depending classes
=> Make Collisions index column in CaloTable

DPG/Tasks/AOTTrack/qaImpPar.cxx
thanks a lot to @galocco for spotting this issue!
=> DPG: fix dca recalculation after PV refit.

PWGMM/Mult/Tasks/dndeta-hi.cxx
* V0 particle ID tracking
* add mass peak histogram
* add analysis histogram to subtract background 
* make process function more simply
=>     * PWGMM dndneta-hi.cxx development

PWGJE/TableProducer/emcalCorrectionTask.cxx
Match clusters to collision according to their found
BC and not the BC from tracks from the reconstruction.
As such the framework matching has to be disabled
and in order to subscribe to all BC Change in logics:
- Pre-sort cells and global indices before BC loop
- In BC loop access pre-sorted cells objects
- Match collision(s) to cells using PreSlice with
foundBCId
- If cells found for BC run processing inside BC loop
as done previoisly
=> [EMCAL-670] Cluster-collision matching using foundBC

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
Add variable 1/pT
Add cuts to study asymmetry of charged tracks.
=> PWGEM: Add new cuts for 1/pt and eta study

PWGJE/TableProducer/emcalCorrectionTask.cxx
- Use framework Preslice instead of custom
lookup table for Cells
- Handle QA histograms with histogram registry
=> [EMCAL-670] Filter cells with Preslice

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/tableReader.cxx
There is a small bug for tableReader and dqEfficiency to call the KF Vertexing from the VarManager.h
=> PWGDQ: Fix small bugs for calling KF Vertexing

EventFiltering/PWGCF/CFFilterQA.cxx
- pull in latest changes of CFFilterAll.cxx
- use PP/PL for QA instead of PD/LD
=> Update filter QA task for PWGCF filters

PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
=> PWGEM/TableProducer: add ML input creator

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
update treeCreatorElectronML.cxx
=> PWGEM/Dilepton/TableProducer: update treeCreatorElectronML.cxx

EventFiltering/cefpTask.cxx
@strogolo, I think we will need to recreate the wagon tomorrow﻿
=> Add missing configurables of FullJet&PHOS triggers

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
update treeCreatorElectronML.cxx
=> PWGEM/Dilepton: update treeCreatorElectronML.cxx

ALICE3/TableProducer/alice3-pidTOF.cxx, Common/Core/PID/PIDTOF.h, Common/TableProducer/PID/CMakeLists.txt, Common/TableProducer/PID/pidBayes.cxx, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFFull.cxx, Common/TableProducer/PID/pidTOFbeta.cxx, Common/TableProducer/PID/pidTPCBase.cxx
Depends on https://github.com/AliceO2Group/AliceO2/pull/10760
=> TOF dev: move to next parameter container for pass handling

PWGHF/TableProducer/candidateCreatorB0.cxx, PWGHF/TableProducer/candidateCreatorBplus.cxx, PWGHF/TableProducer/candidateCreatorCascade.cxx, PWGHF/TableProducer/candidateCreatorChic.cxx, PWGHF/TableProducer/candidateCreatorLb.cxx, PWGHF/TableProducer/candidateCreatorToXiPi.cxx, PWGHF/TableProducer/candidateCreatorX.cxx, PWGHF/TableProducer/candidateCreatorXicc.cxx, PWGHF/TableProducer/trackIndexSkimCreator.cxx
@DanielSamitz @ZFederica This PR should fix your issues.
=> PWGHF: Add configurables for vertexer minimisation options

PWGLF/Tasks/LFNucleiBATask.cxx
@njacazio @giovannimalfattore This is a minor modification for MC.
=> [NucleiBaTask]minor modifications for MC histograms

PWGJE/TableProducer/jetfinder.cxx, PWGJE/Tasks/FullJetTriggerQATask.cxx
* The addition of extra filters speeds up the jet finder for full jets
* Added a histogram to the full jet trigger qa
=> Jet finder speed-up

PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/TableProducer/tableMakerMC.cxx, PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/tableReader.cxx
- Adding histograms to keep track of orphan tracks which excluded from the skimming
- Fixing magnetic field fetch from ccdb
=> Adding QA for orphan tracks and fixing magnetic field fetch from ccdb

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/HFC/TableProducer/CMakeLists.txt, PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx, PWGHF/HFC/Tasks/CMakeLists.txt, PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
we have added the first version of the code for the study of the Ds-hadron correlations. The implementation is based on the code for the Dplus-hadron correlations. Please let us know if you have comments.
Best regards
Samuele & Grazia
=> PWGHF: First implementation of code for Ds-hadron correlations

Common/TableProducer/CMakeLists.txt, Common/TableProducer/trackPropagationTester.cxx
* this PR is needed to do some tests with propagation on hyperloop 
* please be advised this is only temporary: the task will be deleted once all studies are converged
* A better solution for configurability will have to be discussed; will result in updates to code
=> Track propag experiment

PWGJE/DataModel/EMCALClusters.h, PWGJE/TableProducer/emcalCorrectionTask.cxx
- Correction for nonlinearity based on
NonlinearityHandler
- Nonlinearity function selectable
- Energy corrected for nonlinearity as additional
column in cluster table
=> [EMCAL-670] Add cluster nonlinearity and shaper saturation correction

PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/candidateSelectorLcMl.cxx, Tools/ML/model.cxx, Tools/ML/model.h
Lc candidate selector that pre-selects with PID, mass and CPA cuts, and then applies a BDT model from the trigger framework for the final selection.
=> PWGHF: Lc selector with BDT

PWGDQ/Tasks/tableReader.cxx
Fixing issue with Muon histograms filling
=> PWG-DQ: Fixing issue with Muon histograms filling

PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- Add EMC standanlone, PCM-EMC and PHOS-EMC
- Add RotationBackground for EMC (currently not working correctly, rotation itself seems to be off)
- Add Eta Phi hit map for V0 daughters in QC task (now needs pcm skimming task to run!)
=> [PWGEM-10] Add EMC to Pi0Eta Task

PWGLF/Tasks/hyperRecoTask.cxx
@fmazzasc @lbariogl have a look﻿
=> Add PID from the CCDB

PWGLF/DataModel/LFNucleiTables.h, PWGLF/TableProducer/LFTreeCreatorNuclei.cxx, PWGLF/Tasks/LFNucleiBATask.cxx
@njacazio Could you please check the PR?
=> [NucleiBaTask&Table] Configuration with ITS hits

PWGUD/Core/DGPIDSelector.cxx, PWGUD/Core/DGPIDSelector.h, PWGUD/Core/UDFSParser.cxx, PWGUD/Core/UDFSParser.h, PWGUD/DataModel/UDTables.h, PWGUD/TableProducer/DGBCCandProducer.cxx, PWGUD/TableProducer/DGCandProducer.cxx, PWGUD/TableProducer/UPCCandidateProducer.cxx, PWGUD/Tasks/CMakeLists.txt, PWGUD/Tasks/DGCandAnalyzer.cxx
. Beautyfications
. Extension of UDTables.h
=> Several changes

Common/Tools/trackSelectionRequest.cxx, Common/Tools/trackSelectionRequest.h
* still experimental, will still change and be tuned
* includes track selection configuration combiner (logical OR)
* missing: explicit ITS map requirement (i.e. L0||L1, etc etc) 
* further logic / algorithmic development needed
=> Expanding upon track selection request class

PWGHF/TableProducer/candidateCreatorToXiPi.cxx, PWGHF/TableProducer/candidateSelectorToXiPi.cxx
- add DCA fitter options
- fix TPC & TOF combined PID
=> PWGHF: add DCAFitter options and fix combined PID Omegac

.github/workflows/code-formatting.yml, .github/workflows/codeowner-self-approval.yml, .github/workflows/mega-linter.yml, .github/workflows/stale.yml
For security and to silence errors from MegaLinter.
Cc: @vkucera
=> Specify minimal set of GH Action permissions

PWGDQ/Core/CutsLibrary.cxx
Adding the following cuts for electron selection : 
- pT > 0.9
- pIN > 1.0
=>  PWGDQ/Core/CutsLibrary.cxx : Adding electron cuts 

PWGJE/Tasks/emctmmonitor.cxx
- Add missing fill of new A-/C-Side histograms for electron E/p in case pion rejection is not active
- Add info for TPC NSgima configurables to be more clear
- Changed if statements for TPC PID NSigma to be of format: lower boundary <= NSigma && NSigma <= upper boundary to be more clear, this includes a bug fix for the upper boundary of the electron background, where it was NSigma >= upper boundary
=> [EMCAL-689] EMCal TM: Add missing fill histo

PWGLF/Tasks/hyperRecoTask.cxx
=> Cleaner logic for nSigma selection

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/refitPvDummy.cxx
@jgrosseo @vkucera please have a look
=> PWGHF: Add cascades to table conversion and split in different process functions

PWGLF/Tasks/LFNucleiBATask.cxx
- Improve modularity of the task for AliHyperloop 
- Fix TOF histos
=> [PWGLF] LightNucleiTask - Minor fixes and optimization

Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFFull.cxx, Common/TableProducer/PID/pidTPCBase.cxx
- fix usage of IU tracks in pidTPCbase
=> PID TOF: use IU tracks in noslice processes

PWGHF/TableProducer/candidateSelectorLcMl.cxx
Hi @vkucera 
These are the follow-up updates to make the selector work well with BDT.
I slightly changed the condition for rejecting candidates. Based on the threshold values, the conditions in lines 313 and 319-320 are more or less equivalent. Let's see on Hyperloop what we get, then we can think more how to use the BDT output.
=> PWGHF: Fixes to Lc ML selector

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPHOS.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/gammaConversions.cxx
This PR has 3 commits.
PWGEM/PhotonMeson: add multiplicity variables
PWGEM/PhotonMeson/TableProducer: fix m02 cut in skimmmerPHOS
PWGEM/PhotonMeson: update photon conversion table
=> PWGEM/PhotonMeson: update PCM analysis

PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
update v0finder with TPConly tracks
=> PWGEM/PhotonMeson: update v0finder with TPConly tracks

PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
update pi0/eta task to reject v0s with large PCA
=> PWGEM/PhotonMeson/Task: update pi0/eta task to reject v0s with large PCA

PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
=> PWGEM/PhotonMeson/Tasks: quick fix to pi0eta task

PWGUD/Core/DGPIDSelector.h, PWGUD/Core/UDHelpers.h, PWGUD/Tasks/DGCandAnalyzer.cxx
. add histograms
. add cut of track eta
=> PWG-UD: update of DGCandAnalyzer

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
=> Move v0 and cascade tag table to PWGLF/DataModel

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: implement MC analysis
PWGEM/PhotonMeson: set default value m=0 in DYNAMIC_COLUMN
PWGEM/PhotonMeson/TableProducer: remove unnecessary definition
=> PWGEM//PhotonMeson: implement MC analysis

PWGDQ/Tasks/v0selector.cxx
=> PWGDQ: remove TOF from Join

PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
quick fix to wrong return in pcm QC
=> PWGEM/PhotonMeson: quick fix to wrong return in pcm QC

PWGHF/TableProducer/candidateCreatorB0.cxx, PWGLF/DataModel/LFStrangenessFinderTables.h, PWGLF/TableProducer/cascadefinder.cxx, PWGLF/TableProducer/lambdakzerofinder.cxx
still some further tuning to cascade cross-check coming soon
=> cross-check findable level at AO2D possible

PWGCF/JCorran/TableProducer/JCatalyst.cxx, PWGEM/Dilepton/Tasks/v0gammaQA.cxx
Currently broken and making all CI jobs fail, merging
=> Fix DCAFitter header location

PWGLF/DataModel/LFNucleiTables.h, PWGLF/TableProducer/LFTreeCreatorNuclei.cxx, PWGLF/Tasks/LFNucleiBATask.cxx
- Add filtering for light nuclei 
- Add ITS cluster cut 
- Minor fix for TOF mass 
- Add enableProton flag 
- Add qa plots 
- Move to debug flagged old qa plots 
- Simplify code (cutting out most strong-cut logic)
=> [PWGLF] LightNucleiTask - Add flag for particle processing

PWGEM/PhotonMeson/Core/CMakeLists.txt, PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/CutsLibrary.h, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/pcmQC.cxx
=> PWGEM/PhotonMeson: add photon selection

PWGCF/FemtoWorld/DataModel/FemtoWorldDerived.h, PWGCF/FemtoWorld/TableProducer/femtoWorldProducerTask.cxx, PWGCF/FemtoWorld/Tasks/CMakeLists.txt, PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskTrackD0.cxx
Update of femtoWorldProducerTask.cxx and FemtoWorldDerived.h, in which I've added 5 new columns for D0/D0bar analysis. I've also added one new file: femtoWorldPairTaskTrackD0.cxx, which gives the simple D0/D0bar analysis (for example: pT, invMass histograms).
=> PWGCF FemtoWorld simple D0 analysis

PWGDQ/Macros/DQFitter.py, PWGDQ/Macros/configFit.json, PWGDQ/Macros/plot_library.py, PWGDQ/Macros/tutorial.py
Update of the python fit library
=> PWGDQ: Updating DQ fit library

PWGMM/Mult/Tasks/dndeta-hi.cxx
dn-deta distribution for mft with mid-rapidity
=> dn-deta distribution for mft with mid-rapidity

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: update MC tasks
PWGEM/PhotonMeson: update createPCM with track-collision associator
=> PWGEM/PhotonMeson: update PCM for MC

CODEOWNERS
@mhemmer-cern added to CODEOWNERS
=> PWGEM adding rights for Marvin Hemmer

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
Replacing LMee light flavour cocktail analysis task with a new version that is running over McTracks instead of McParticles and can be used for on-the-fly analyses (see https://github.com/AliceO2Group/AliceO2/blob/dev/run/SimExamples/MCTrackToDPL/run.sh for an example)
=> PWGEM: updated LMee LF cocktail task

CODEOWNERS
Reflects change in DPG coord. @mfaggin @iouribelikov
=> Update DPG codeowners

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson: update createPCM for really TPC only tracks
PWGEM/PhotonMeson: reduce histogram binnings
=> PWGEM/PhotonMeson: update v0 finder for PCM

PWGEM/PhotonMeson/Core/CMakeLists.txt, PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/CutsLibrary.h, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Core/PHOSPhotonCut.cxx, PWGEM/PhotonMeson/Core/PHOSPhotonCut.h, PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
update histograms and cut settings for PCM
=> PWGEM/PhotonMeson: update histograms and cut settings for PCM

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/MCUtilities.h
move V0 rejection to skimmerGammaConv partially
=> PWGEM/PhotonMeson: move V0 rejection to skimmerGammaConv partially

PWGJE/TableProducer/emcalCorrectionTask.cxx
- Change to new initializer function for the cluster, cell and index container, which also initilizes the lookup table for the exotic cluster cut
- Connected to PR #10932 https://github.com/AliceO2Group/AliceO2/pull/10932
=> [EMCAL-670] [EMCAL-688] Change to new initializer function

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
=> PWGEM/PhotonMeson: add 2 new tasks

Tutorials/CMakeLists.txt, Tutorials/PWGEM/CMakeLists.txt, Tutorials/PWGEM/emcclustertutorial.cxx
- Add skeleton task in Tutorials/PWGEM for EMCal cluster hands on session
=> Add PWGEM cluster tutorial task

PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx
add kTVXinEMC in a skimming task
=> PWGEM/PhotonMeson: add kTVXinEMC in a skimming task

CODEOWNERS
Removing @xinyepeng , adding @fcatalan92 
@TimoWilken could you please update the write access for the two users?
=> Update PWG-HF D2H coordinators

Common/TableProducer/trackToCollisionAssociator.cxx
Thanks @dsekihat for spotting this.
=> Fix track filter enabling the configurable.

PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/hStrangeCorrelationFilter.cxx, PWGLF/Tasks/hStrangeCorrelation.cxx
Thanks a lot to Lucia! :-D
* use 2 different processes within the same task for mixed and same-event 
* adjust mixed event techniques 
* general improvement to task: extra modularity
=> Update h-Str correlations

PWGLF/DataModel/LFNucleiTables.h, PWGLF/TableProducer/LFTreeCreatorNuclei.cxx, PWGLF/Tasks/LFNucleiBATask.cxx
- Add isPVContributor cut 
- Add additional TOFExpMomentum histograms for debug 
- Fix minor issues and typos
=> [PWGLF] LightNucleiTask - Add PV cut

Tutorials/PWGEM/emcclustertutorial.cxx
- Removed some line that are not needed
=> [PWGEM] EMCal cluster tutorial clean up

PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
PWGEM/PhotonMeson: add kTVXinPHOS in a skimming task
=> PWGEM/PhotonMeson: add kTVXinPHOS in a skimming task

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx, PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton: add workflow for smearing
PWGEM/Dilepton: update tree creator for ML
=> PWGEM/Dilepton: update ML tree and add a workflow for smearing

PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
PWGEM/PhotonMeson: quick fix for event mixing
=> PWGEM/PhotonMeson: quick fix for event mixing

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: quick fix to index not sorted in MC
=> PWGEM/PhotonMeson: quick fix to index not sorted in MC

PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson: add configurable to reject TPConly tracks for V0
=> PWGEM/PhotonMeson: add configurable to reject TPConly tracks for V0

PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
- possibility to switch on/off the generation of a virtual photon for each pion in the event (advantage: if switched off one does not need to provide a parametrization file for the photon pT at all)
- allow .json file instead of .root file for photon pT file (--> can use same parametrization files as we have now for the generator)
=> PWGEM: allow .json format for parametrization file for virt. photon generation

PWGLF/DataModel/LFNucleiTables.h, PWGLF/TableProducer/LFTreeCreatorNuclei.cxx, PWGLF/Tasks/LFNucleiBATask.cxx
Hi @njacazio,
Please have a look.
Many thanks.
=> [BATask] Fixing bugs and issue with TableProducer from last commit

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: add conversion point histograms
=> PWGEM/PhotonMeson: add conversion point histograms

PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- Add NGamma candidate histograms for reduced event task for all three photon detection methods
=> [PWGEM-12] Add NGamma candidate histogram

Common/DataModel/TrackSelectionTables.h, DPG/Tasks/AOTTrack/qaEventTrack.cxx
@akalweit this PR is meant to address your requests of yesterday on the eta monitoring.
@jgrosseo @njacazio @iarsene @ktf @ddobrigk can you please have a look and approve? Thanks.
=> Add global trk w/o TPC cluster cuts and more QA plots.

PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/k892analysis.cxx, PWGLF/Tasks/phianalysis.cxx
Set configurable for event mixing pool
And optimise the nBins of QA histograms
=> Update MC PDG particle list to keep

PWGJE/Core/JetUtilities.h, PWGJE/DataModel/Jet.h, PWGJE/TableProducer/jetmatching.cxx, PWGJE/Tasks/jetmatchingqa.cxx
- generalize jet matching to D0, Lc, Bplus
- adapt jet matching QA
=> Generalize jet matching

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx
=> PWGDQ: Adding cuts for Z analysis

PWGJE/TableProducer/jetmatching.cxx, PWGJE/Tasks/jetmatchingqa.cxx
- add process switch
- avoid binding to HF table for inclusive jets
=> Improve jet matching

PWGLF/DataModel/LFQATables.h, PWGLF/TableProducer/cascademcfinder.cxx, PWGLF/TableProducer/lambdakzeromcfinder.cxx, PWGLF/Tasks/QC/CMakeLists.txt, PWGLF/Tasks/QC/mcCollisionExtra.cxx, PWGLF/Tasks/QC/straRecoStudy.cxx
* adds a QA task that creates MC-to-reco association for McCollisions
* adds corresponding QA data model 
* fixes ordering problems with V0 and cascade MC-label-based V0/Cascade table producers for full performance studies
* adds a number of quality assurance histograms to the MC-label-based V0/Cascade table producers
=> Performance tools for strangeness

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
=> PWGEM/PhotonMeson: update on MC analysis

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
=> PWGEM/PhotonMeson: update on event mixing

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/MCUtilities.h
=> PWGEM/PhotonMeson: update on MC analyses

PWGLF/DataModel/LFSlimNucleiTables.h, PWGLF/TableProducer/nucleiSpectra.cxx
Also, add the z vertex position to the output tree and fix the integer sign
=> Avoid two process functions for the MC

PWGHF/Tasks/taskMcEfficiency.cxx
Ciao @fgrosa I create a draft PR just to give you a reference. I tried the code locally and it runs. Here the scripts and config I used: [link](https://cernbox.cern.ch/s/p474LjRDF0it40t)
=> PWGHF: Add 3 prong structure with Lc->pKpi in MC ef. monitoring.

Common/TableProducer/multiplicityTable.cxx
=> Multiplicity: Add preslice

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx
replace aod::Tracks with aod::TracksIU
remove name "KF" in cut settings.
=> PWGEM/PhotonMeson: replace aod::Tracks with aod::TracksIU

CODEOWNERS
Adding @deepathoms 
@TimoWilken could you please update the write access for @deepathoms ?
=> Update PWG-HF HFC coordinators

PWGDQ/DataModel/ReducedInfoTables.h, PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton and PWGDQ: update smearing.cxx and ReducedInfoTables.h
=> PWGEM/Dilepton and PWGDQ: update smearing.cxx and ReducedInfoTables.h

PWGEM/PhotonMeson/Core/EMCPhotonCut.h, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/PHOSPhotonCut.h, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx, PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/PhotonMeson: activate EMC cut in pairing
Track matching is disabled, until matched track table is ready.
=> PWGEM/PhotonMeson: activate EMC cut in pairing

Common/DataModel/CollisionAssociation.h, Common/TableProducer/CMakeLists.txt, Common/TableProducer/fwdtrackToCollisionAssociator.cxx
@jgrosseo 
@sarahherrmann and I added a simple implementation of forward and mft track association to collisions, based on the code of `trackToCollisionAssociator.cxx`.
=> Forward and MFT track association to collisions

PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/TableProducer/hStrangeCorrelationFilter.cxx, PWGLF/Tasks/hStrangeCorrelation.cxx
Thanks to @kcui1 : mass regions added
=> Add mass region checks and histos

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
quick fix to PR2554 and update on histogram titles
=> PWGEM/PhotonMeson: quick fix to PR2554 and update on histograms

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx, PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx
PWGEM/PhotonMeson: add a task for single photon
PWGEM/PhotonMeson: add centrality slice
=> PWGEM/PhotonMeson: add a task for single photon and centrality slice

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/CMakeLists.txt, PWGDQ/Tasks/taskJpsiHf.cxx
Adding the task to combine dilepton tables with D candidates
=> PWGDQ: Adding J/psi - HF task

PWGEM/Dilepton/Tasks/smearing.cxx
=> Update of smearing task

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
=> Mininal QA histo fix

PWGLF/DataModel/LFHypernucleiTables.h, PWGLF/TableProducer/hyperRecoTask.cxx
=> Add PDG code to data structure

PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/CMakeLists.txt, PWGLF/Tasks/k1analysis.cxx
=> Basic K1 analysis task

PWGEM/Dilepton/Tasks/smearing.cxx
change double to float and replace McParticles_001 with McParticles
=> PWGEM/Dilepton: change double to float and replace McParticles_001

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
=> Include smearing

PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/Tasks/hStrangeCorrelation.cxx
* adds a self-correlation safeguard for collision mixing
* fixes a mass region check problem in data model 
* changes subscription of multiplicity into centrality percentiles
=> Fixes to h-Strangeness code

DPG/Tasks/AOTTrack/qaMatchEff.cxx
- fix TOF PID usage (only tracks with `hasTOF` true)
- remove useless new lines
=> DPG: Update matching efficiency code

PWGUD/AQC/CMakeLists.txt, PWGUD/AQC/udQC.cxx, PWGUD/CMakeLists.txt
The tasks for asynchronous quality control have been created in a new subdirectory.
=> PWG-UD: Added subdirectory for AQC 

PWGUD/Core/UDHelpers.h, PWGUD/DataModel/UDTables.h, PWGUD/TableProducer/DGBCCandProducer.cxx, PWGUD/TableProducer/DGCandProducer.cxx
update of zdc information in UDTables
=> PWG-UD: update of DGBCCandProducer and DGCandProducer

DPG/Tasks/MFT/CMakeLists.txt, DPG/Tasks/MFT/aQCMFTTracks.cxx
Creating folder "MFT/" in "DPG/Tasks/" to upload a basic analysis task for asynchronous QC checks on MFT tracks
=> Adding basic AO2D task for asynchronous QC on MFT tracks

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: update add track cov. in gammaTable.h
PWGEM/PhotonMeson: update on feed down in MC
PWGEM/PhotonMeson: replace sliceBy with sliceByUnsorted in MC
=> PWGEM/PhotonMeson: update MC and gammaTable.h

PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/cascademcfinder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx, PWGLF/TableProducer/lambdakzerolabelbuilder.cxx, PWGLF/TableProducer/lambdakzeromcfinder.cxx, PWGLF/Tasks/QC/straRecoStudy.cxx
* fixes an issue in which a bad quality track was preferred instead of a proper TPC track in the MC finding exercise for performance studies, leading to less than ideal (and badly representative) quality of the MC-found candidates in some cases
* Multiple improvements in QA functionality for strangeness performance studies
=> Multiple fixes to mc finding

PWGLF/Tasks/hStrangeCorrelation.cxx
* adds configurables to select the histograms that will be created & filled. Will make it possible to have finer control on memory consumption as required.
=> Add configurables

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update dca xy cut in PCM
PWGEM/PhotonMeson: add histograms for tracks
=> PWGEM/PhotonMeson: update DCA study and histograms

ALICE3/Tasks/alice3-lutmaker.cxx
=> A3: update lutmaker

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
=> PWGEM/PhotonMeson: update v0 cuts

PWGLF/Tasks/k892analysis.cxx
=> Update the axis information

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx, PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/PhotonMeson: update PCM cuts
PWGEM/PhotonMeson: update v0leg-cluster matching veto
PWGEM/PhotonMeson: update PCM cuts
=> PWGEM/PhotonMeson: update on PCM cuts and v0leg-cluster matching veto

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/cascadebuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx, PWGLF/Tasks/QC/straRecoStudy.cxx
* fixes a bug in the `dE/dx` preselection logic in the cascade builder
=> Fix preselector bug of yesterday

PWGLF/DataModel/LFSlimNucleiTables.h, PWGLF/TableProducer/nucleiSpectra.cxx
=> Fix slim derived data + eta studies

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreatorCascade.cxx, PWGHF/TableProducer/treeCreatorLcToK0sP.cxx
https://github.com/AliceO2Group/O2Physics/issues/2392 for treeCreatorLcToK0sP
=> PWGHF: adding particle origin MC information to LcToK0sP tree creator

PWGHF/D2H/Tasks/taskXic.cxx
In `PWGHF/D2H/Tasks/taskXic.cxx` task:
* Adding TOF/TPC nSigma histograms 
* Adding few more 1D and 2D histograms related to other observables
* Adding `Data` and `MC` directory structures to save histograms in the output
=> PWGHF: Add TPC/TOF nSig hist in Xic task

PWGCF/DataModel/DptDptFiltered.h, PWGCF/TableProducer/dptdptfilter.cxx, PWGCF/TableProducer/dptdptfilter.h, PWGCF/Tasks/dptdptcorrelations.cxx, PWGCF/Tasks/dptdptfilterqa.cxx, PWGCF/Tasks/match-reco-gen.cxx
Also 
- support for identified two-particle correlations analyses
- initial support for optional mixed events two-particle correlations
=> Efficient not stored derived data handling

Common/TableProducer/centralityTable.cxx, Common/TableProducer/multiplicityTable.cxx
Reverts AliceO2Group/O2Physics#2666
=> Revert "Reserve memory in mult/cent"

PWGDQ/Core/HistogramsLibrary.cxx
phiv histo separated for dielectrons
=> phiv histo separated for dielectrons

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Core/PHOSPhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/skimmerPHOS.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/phosQC.cxx
=> PWGEM/PhotonMeson: add a task for PHOS QC

PWGDQ/Core/HistogramsLibrary.cxx
change else if to if, to handle the dielectrons hist class as an independent class.
In that way the barrel and dielectrons histograms can be plotted in the same output.
=> PWGEM: dielectrons as own hist class

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Fix for efficiency on skimmed data
=> Fix for efficiency on skimmed data

PWGHF/TableProducer/candidateCreatorBplus.cxx
B+ Creator:
- typo in hEtaPi histogram range
- polishing
=> PWGHF: B+, typo in histogram range

PWGHF/D2H/Tasks/taskOmegacSt.cxx
- add reconstruction of decay vertex
- add additional histograms
=> PWGHF: Extend ST-based analysis of Omega_c

PWGDQ/Tasks/taskJpsiHf.cxx
- Adding filters for Jpsi-HF task
- Adding debug configurable
=> PWGDQ: Adding filters for Jpsi-HF task

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
PWGEM/Dilepton: update tree ML creator for HFee
=> PWGEM/Dilepton: update tree ML creator for HFee

Common/TableProducer/CMakeLists.txt, Common/TableProducer/PID/CMakeLists.txt
Should improve memory consumption (to be checked)
=> Remove unnecessarily linked libs from core services

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
PWGEM/Dilepton: update ml tree creator
=> PWGEM/Dilepton: update ml tree creator

PWGMM/Mult/Tasks/dndeta-hi.cxx
* Made it possible to control v0 analysis and mft analysis through bool function.
* Eliminate meaningless functions or axes
=> PWGMM : dndeta-hi.cxx

ALICE3/Tasks/alice3-dilepton.cxx
ALICE3: fix to pairing loop for LS
replace `CombinationsFullIndexPolicy` with `CombinationsStrictlyUpperIndexPolicy` for LS pairs.
=> ALICE3: fix to pairing loop for ULS and LS

PWGLF/Tasks/hStrangeCorrelation.cxx
add multiplicity dependence for trigger particles
=> Change in hStrangeCorrelation.cxx

PWGDQ/Core/HistogramsLibrary.cxx
Add a flexible binning for dielectron histograms
=> PWGEM: Add histogramm for large scale in mee,ptee,dca

PWGEM/Dilepton/Tasks/MCtemplates.cxx
Fix Preslicing in MCtemplates task
=> PWGEM: fix preslice error with PresliceUnsorted

PWGEM/PhotonMeson/Core/CMakeLists.txt, PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/CutsLibrary.h, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h, PWGEM/PhotonMeson/Core/PairCut.cxx, PWGEM/PhotonMeson/Core/PairCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
PWGEM/PhotonMeson: implement pair cut class
=> PWGEM/PhotonMeson: implement pair cut class

PWGHF/D2H/Tasks/taskXic.cxx, PWGHF/TableProducer/candidateSelectorXicToPKPi.cxx
Abs added to impPar, fixed histo names for background
=> PWGHF: Abs added to impPar  fixed histo names for Xic

PWGHF/D2H/Tasks/taskXic.cxx
PWGHF: adding ImpParXY histo for Xic task
=> PWGHF: adding ImpParXY histo for Xic

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: add conversion point Rxy vs. phi
=> PWGEM/PhotonMeson: add conversion point Rxy vs. phi

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
PWGEM/Dilepton: update HF->ee selection in ml tree maker
=> PWGEM/Dilepton: update HF->ee selection in ml tree maker

PWGCF/Flow/CMakeLists.txt, PWGCF/Flow/Core/CMakeLists.txt, PWGCF/Flow/TableProducer/CMakeLists.txt, PWGCF/Flow/Tasks/CMakeLists.txt, PWGCF/Flow/Tasks/flowPtEfficiency.cxx
Add New Task of pt differential efficiency for pt integrated flow analysis
A new folder of PWGCF/Flow is created
=> [PWGCF/PAG-Flow] Add New Task of pt differential efficiency

PWGHF/TableProducer/trackIndexSkimCreator.cxx, PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/TableProducer/hStrangeCorrelationFilter.cxx, PWGLF/Tasks/hStrangeCorrelation.cxx
implementation of h-Pion correlations
=> Change in hStrangeCorrelation

PWGLF/Tasks/cascqaanalysis.cxx
for INEL>0 there should be CHARGED particle within |eta| < 1.0
=> bug fix (charge check)

PWGLF/Tasks/lambda1520analysis.cxx
V0M multiplicity class added + other changes
=> Update with V0M class

PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/taskJpsiHf.cxx
- Fix histogram filling in dqEfficiency
- Removing filters of D-meson selection in Jpsi combination task
=> PWGDQ: Fixing MC histogram filling and Jpsi combination task

PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/jetfragmentation.cxx
Jet fragmentation in data and MC (detector and particle level)
=> Jet fragmentation task

PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/Tasks/CMakeLists.txt, PWGDQ/Tasks/filterPbPb.cxx
Currently one filter bit for DG events. Also does barrel track filter, implemented like in filterPP.
=> [PWGDQ] Add task filterPbPb for PbPb event filters

PWGLF/Tasks/spectraTOF.cxx
=> LF: spectra add more ev. time bins

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] delete duplications

PWGLF/TableProducer/LFResonanceInitializer.cxx
Add switch for FatalWhenNull
Use <false> temporarily If you want to proceed with the code without a magnetic field
=> [PWGLF] Add switch for FatalWhenNull

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] fix bug on f0980 ana

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
PWGEM/PhotonMeson: add a task for tag-and-probe method
=> PWGEM/PhotonMeson: add a task for tag-and-probe method

PWGHF/D2H/Tasks/taskD0.cxx
Added:
- 2D histogram of correlation of generated and reconstructed pt
- 2D histogram of correlation of generated and reconstructed y
- 3D correlation of inv. mass, generated pt and reconstructed pt
=> PWGHF: Add histos correlation of generated and reconstructed quantities (pt,y) for D0

PWGLF/TableProducer/lambdakzerobuilder.cxx
minor changes to QA to include photon QA as demo for PWG-EM efforts
=> strangeness builders: changes in QA for PCM tests

ALICE3/DataModel/collisionAlice3.h, ALICE3/TableProducer/onTheFlyTracker.cxx
Thanks a lot to @hscheid for the part that's actually his in this PR and that I shamelessly copied :-D
=> ALICE 3: fill table with multDensity

PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/Tasks/hStrangeCorrelation.cxx
Pushed on behalf of @lhusova. Thanks a lot, Lucia!
=> h-Strangeness 2pc update: bugfix, add QA histos

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx, PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx, PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx, PWGEM/PhotonMeson/Tasks/gammaConversions.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: include KFParticle for PCM
=> PWGEM/PhotonMeson: include KFParticle for PCM

PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Utils/collisionCuts.h
Add switch for multiplicity estimator and qa
=> [PWGLF] Add switch for multiplicity estimator and qa

Common/TableProducer/fwdtrackToCollisionAssociator.cxx, PWGMM/Mult/DataModel/bestCollisionTable.h, PWGMM/Mult/TableProducer/trackPropagation.cxx, PWGMM/Mult/Tasks/dndeta-mft.cxx
Also fix in fwdtracktoCollisionAssociator to have possibly doprocessFwdAssocWithTime==doprocessFwdStandardAssoc=false
=> [PWGMM] Updated dndeta-mft using fwdtrack-to-collision-associator 

PWGMM/Tasks/CMakeLists.txt, PWGMM/Tasks/multiplicityPbPb.cxx
Based on O2 tutorial vol.2 I created a simple task for making basic histograms that will be used for multiplicity analysis of Pb-Pb collisions from Run 3.
=> add new task for Pb-Pb multiplicity

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/cascadelabelbuilder.cxx, PWGLF/TableProducer/lambdakzerobuilder.cxx
* adds a process function to the cascade label producer that allows for the isolation of the bachelor-baryon correlation in MC for study if necessary (@ChiaraDeMartin95 ;-) ) 
* very minor changes to the QA plots for V0 building
=> strangeness tab.prod.: add bachelor-baryon corr tagger

Common/Core/PID/PIDTOF.h, Common/TableProducer/PID/pidTOF.cxx, Common/TableProducer/PID/pidTOFFull.cxx
- Releasing tables for performance
=> TOF PID: Add time shift

PWGLF/DataModel/cascqaanalysis.h, PWGLF/TableProducer/CMakeLists.txt, PWGLF/TableProducer/cascqaanalysis.cxx, PWGLF/TableProducer/v0qaanalysis.cxx, PWGLF/Tasks/CMakeLists.txt, PWGLF/Tasks/NucleiHistTask.cxx, PWGLF/Tasks/v0postprocessing.cxx
- Move cascade task to data model
- Add histograms for DCAxy/z of tracks
- add v0postprocessing task
=> Move cascade task to data model + v0 post processing

PWGLF/Tasks/lambda1520analysis.cxx
1. removed full LS histo 
2. added MELight process function 
3. added switch for pid selection cut
=> Update LS histo, MELight, pid cut

PWGHF/TableProducer/treeCreatorToXiPi.cxx
- add candidate collIision Id to treeCreatorToXiPi for rejection factor studies
=> PWGHF: add candidate collIision Id to treeCreatorToXiPi

PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx
PWGEM/PhotonMeson: update chi2/ndf for KFParticle
=> PWGEM/PhotonMeson: update chi2/ndf for KFParticle

ALICE3/TableProducer/onTheFlyTracker.cxx
* skips non-LUTtable species for now 
* adds some dummy track filling (@nzardosh @vkucera @mmazzilli), will still add TracksExtra shortly
=> OTF tracker adjustments

PWGLF/Tasks/lambda1520analysis.cxx
-  plus added configurable histo axes
=> Added TOF veto

PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
=> PWGHF: Adding collisionID info in the Lc->PKPi tree creator

PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
=> PWGHF: Adding collision index to the Lc MC particle tree

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] delete cout

Common/Core/TableHelper.h, Common/TableProducer/trackselection.cxx
=> TrkSel: Autoset the track selection

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx
PWGEM/PhotonMeson: update cuts and histograms for PCM
=> PWGEM/PhotonMeson: update cuts and histograms for PCM

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/TableProducer/createEMReducedMCEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx
PWGEM/PhotonMeson: improve W wire selection for PCM
=> PWGEM/PhotonMeson: improve W wire selection for PCM

PWGCF/TableProducer/dptdptfilter.cxx, PWGCF/Tasks/dptdptcorrelations.cxx
Also getting rid of the dependency on track-selection which caused crashes on the nightly tests
=> Generator level for efficient not stored derived data

PWGLF/Tasks/CMakeLists.txt, PWGLF/Tasks/cascadecorrelations.cxx, PWGLF/Tasks/strangecorrelations.cxx
An analysis task for angular correlations between two cascades
=> Analysis task for cascade correlations

Common/Tasks/multiplicityQa.cxx
@njacazio @ercolessi @ChiaraDeMartin95 @nepeivodaRS here goes! Let's see what comes out ...
=> Mult QA additions for Run 3 vs mult analysis corrections

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/PhotonMeson: update pairing for tagging method
=> PWGEM/PhotonMeson: update pairing for tagging method

PWGLF/TableProducer/hStrangeCorrelationFilter.cxx
=> Fix outrageous bug

PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskProtonAntiproton.cxx
Changing pT cuts for protons and antiprotons low from 0.13 to 0.5 and high from 1.5 to 2.5.
=> PWGCF: FemtoWorld: Changing pT cuts in ProtonAntiproton analysis task

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/MCUtilities.h
PWGEM/PhotonMeson: update conditional probability for tagging method
=> PWGEM/PhotonMeson: update conditional probability for tagging method

ALICE3/DataModel/A3DecayFinderTables.h, ALICE3/TableProducer/CMakeLists.txt, ALICE3/TableProducer/alice3-decayfinder.cxx
* adds an ALICE 3 OTF simulation decay processing/analysis task 
* includes pre-selections unique to OTF simulations (TOF PID, etc) 
* flexibility to be improved in the coming days: better pre-filters coming up
=> ALICE 3 study extension

PWGLF/Tasks/kinkAnalysis.cxx
This include a part of code that does the actual kink finding and that will be later moved to a dedicated table creator
=> First version of the kink analysis in AO2D

PWGHF/Tasks/taskMcEfficiency.cxx
@jgrosseo @mfaggin I have added the possibility to run the MC efficiency task with D+ and Ds. Could you please have a look if the implementation is fine with you? Thanks a lot!
=> PWGHF: Add D+ and Ds+ to MC efficiency task

PWGHF/D2H/Tasks/taskDs.cxx, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx, PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
@AlexBigO While looking at the Dplus tree creator for inspiration, I made some minor changes. The only notable one is that now the downsampling is performed if  `downSampleBkgFactor < 1.` and it is no more steered by `fillOnlyBackground` (this approach looks cleaner to me). Let me know if this is fine for you.
=> PWGHF: Add Ds tree creator + update Ds task and Dplus tree creator

EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterHelpers.h
- Fix bug in invariant mass selection for Xi and Lambda in Xi+bachelor trigger
- Make the cosPA cut for Xi and Lambda a configurable
- add cut on DCAxy Xi (configurable)
=> EventFiltering: fix mass selection for cascade and V0 in HFFilter

PWGJE/Tasks/jetfragmentation.cxx
Added MC detector and particle level matching, including fake (detector) jets, but excluding missed (particle) jets due to issue with the jet matching code
=> [PWGJE] Jet Fragmentation

PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/k892analysis.cxx
Including a simple MC DB update of the initializer.
=> Add track cut and QA plots, update mixing and multiplicity

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] add QA

EventFiltering/CMakeLists.txt, EventFiltering/PWGLF/strangenessFilter.cxx, EventFiltering/filterTables.h
- add QA histograms
- add additional (configurable) selection criteria
- separate Xi and Omega selection
- fix access to track properties of tracked objects
=> Extend event filter for strangeness tracking

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/PhotonMeson: update on V0PhotonCut
=> PWGEM/PhotonMeson: update on V0PhotonCut

ALICE3/TableProducer/alice3-decayfinder.cxx
simple fix, add a process switch
=> Add forgotten process switch declaration

Common/TableProducer/PID/CMakeLists.txt, DPG/Tasks/AOTTrack/PID/CMakeLists.txt, DPG/Tasks/AOTTrack/PID/qaHMPID.cxx
=> Clear HMPID, move it to DPG

PWGLF/DataModel/spectraTOF.h, PWGLF/TableProducer/spectraDerivedMaker.cxx, PWGLF/Tasks/spectraTOF.cxx
=> LF: Extend binning of nsigma

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
In this pull request I've commented some output printings used only in local execution in order to test the code.
Best regards,
Samuele
=> PWGHF: Ds-h correlations, removing of some output printing in ME process

PWGHF/TableProducer/treeCreatorD0ToKPi.cxx, PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
Together with @nzardosh, we attempted to make the tree creator output for Lc and D0 more uniform to facilitate post-processing.
=> PWGHF: Make tree creators for Lc and D0 uniform

PWGLF/Tasks/QC/lfpidqa.cxx
=> Add PiKaPr only in LF Qa

PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/Core/FemtoUniverseTrackSelection.h, PWGCF/FemtoUniverse/Tasks/femtoUniverseDebugTrack.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx
Adding PID (nsigma TPC, nsigma TOF) to the track-track task
=> PWGCF: FemtoUniverse PID cuts

PWGLF/Tasks/spectraTOF.cxx
Hi @njacazio,
here is the small change that you suggested, let me know if there is anything else I should include for it.
Cheerio,
Johanna
=> [PWGLF] Adding check for kaons as primary vertex contributors

PWGLF/Tasks/AntimatterAbsorptionHMPID.cxx
@alcaliva before approving this I let you confirm that it's ok.
I split IU and non IU tracks since you want to propagate them anyways.
For curiosity, @ddobrigk and @aalkin do you know why the compilation was doing fine and what was the behavior when asking for a track's pT?
=> LF: HMPID Split IU and non IU tracks

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/checkV0MC.cxx, PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: remove unnecessary lines
PWGEM/PhotonMeson: add a task to check MC V0s
PWGEM/PhotonMeson: implement searching window for PCM
=> PWGEM/PhotonMeson: implement searching window for PCM

PWGDQ/TableProducer/tableMaker.cxx
… add an option to retain only electron samples
=> PWGDQ：Add a process to generate a reduced table based on the pp-filter

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: add phiv and psipair with KF for PCM
=> PWGEM/PhotonMeson: add phiv and psipair with KF for PCM

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] reduce CPU usage

PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson: add a configurable for AP cut in V0 finder
=> PWGEM/PhotonMeson: add a configurable for AP cut in V0 finder

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] fix bug for QA

PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson: suppress warning
=> PWGEM/PhotonMeson: suppress warning

PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx
PWGEM/PhotonMeson: replace PtEtaPhiMVector with PxPyPzMVector
=> PWGEM/PhotonMeson: replace PtEtaPhiMVector with PxPyPzMVector

PWGDQ/Core/HistogramsLibrary.cxx
Correct Nb of bins. Forgot to change in #3109 
Remove redundant histograms
=> PWGEM: Correct number of bins. Remove redundant histograms

PWGLF/DataModel/LFResonanceTables.h, PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/k892analysis.cxx, PWGLF/Utils/collisionCuts.h
- Update Spherocity part (@yashpatley )
- Update manual trigger selection 
- Add Track selection parameters
- Add the option to skip filling the filter QA histograms (default: skip)
- Update K(892) task for the new track selection method
=> Major update of Resoinitializer

PWGLF/TableProducer/LFResonanceInitializer.cxx
=> Update the default parameters

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Tasks/filterPbPb.cxx
Configurable to choose "both", "either", "A", "C", "neither" for FIT veto in DG selector in filterPbPb
Create/rename some cuts and histograms relevant for rho0 photoproduction.
=> PWGDQ: filterPbPb - Make option for choosing FIT sides to use in DG veto.

PWGCF/DataModel/FemtoDerived.h, PWGCF/FemtoDream/FemtoDreamContainer.h, PWGCF/FemtoDream/FemtoDreamParticleHisto.h, PWGCF/FemtoDream/FemtoUtils.h, PWGCF/FemtoDream/femtoDreamPairTaskTrackV0.cxx
This PR contains:
- adding support for MC processing of Lambda particles
- address comments from previous PR https://github.com/AliceO2Group/O2Physics/pull/3118
- typo fixes
=> PWGCF: Update FemtoDream

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
As I currently do not know how to obtain Beam information from CCDB, I will define the Beam information as a pp collision at 13.6 TeV in the initial version.
=> PWGDQ：Add definition for HE and CS frames

PWGDQ/Core/CutsLibrary.cxx
- More mass Cuts
- Muon QualitCuts with loos pDCA
=> Adding cuts to the CutsLibrary :

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/TableProducer/createPCM.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversions.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: add a cut for PCM
=> PWGEM/PhotonMeson: add phiv for PCM

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Added features:
* every type of analysis has now its own process,
* more modular code.
Planned for the future:
* development on the selection part (figuring out the most efficient and easy from the point of view of a user solution for the particle cuts).
=> PWGCF: FemtoUniverse - adding modular structure to the producer

CODEOWNERS
Remove @ginnocen (ALICE3, PWGHF)
Remove @mvolkl (PWGHF/HFL)
Add @adubla (PWGHF)
Add @gtaillepied (PWGHF/HFL)
=> Update PWGHF code owners

PWGLF/DataModel/spectraTOF.h, PWGLF/TableProducer/spectraDerivedMaker.cxx, PWGLF/Tasks/spectraTOF.cxx
@jloemker could you also have a look pls?
=> LF: Change Sp datamodel

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
This PR adds:
* global tracks cuts for the tracks in the producer,
* minimized amount of lines of code.
=> PWGCF: FemtoUniverse -- Global track cuts applied in the producer

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Done:
* isGlobalTrack function added for the track-track and track-Phi analysis
=> PWGCF: FemtoUniverse -- isGlobalTrack function added 

Common/Core/TrackSelection.h, Common/Core/TrackSelectionDefaults.cxx, Common/Core/TrackSelectionDefaults.h, Common/TableProducer/trackselection.cxx
=> Add actual DCA setup

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I've introduced some histograms in order to control some issues on the phi and eta distributions of the Ds.
Best regards,
Samuele
=> PWGHF: Ds-h correlations, adding some control plots

PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/k892analysis.cxx
=> Fix bug on the track loop

PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/k892analysis.cxx
Taken from `tpcSkimsTableCreator`
=> Add track cut filter for efficient process

PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson: add a configurable for max pT of ITSonly tracks
=> PWGEM/PhotonMeson: add a configurable for max pT of ITSonly tracks

PWGLF/TableProducer/lfTPCPID.cxx
@alcaliva @ChiaraDeMartin95 @ercolessi
=> LF: Add lf post calib

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx
Switching on generation of the QA histograms for track-track task.
Adding GlobalTrackFilter to the analysis.
=> FemtoUniverse: TaskTrackTrack update (debug info)

PWGLF/DataModel/LFResonanceTables.h, PWGLF/TableProducer/LFResonanceInitializer.cxx, PWGLF/Tasks/k1analysis.cxx, PWGLF/Tasks/k892analysis.cxx
- Add `SiblingIds` for saving the track index of the same mother particle
- Fix bug and mistake on K892 QA histograms
- Update K1 analysis task
=> Update MC sibling information and analysis task

Tutorials/CMakeLists.txt, Tutorials/src/mcHistograms.cxx, Tutorials/src/usingPDGService.cxx
Requires https://github.com/AliceO2Group/AliceO2/pull/11668
=> Add the `O2DatabasePDG::Mass` function in the PDG tutorial

PWGLF/Tasks/k1analysis.cxx
- Not affecting the significance but reducing the background on the right-hand side of the peak.
- MC part is revised.
=> Update PiKa pair cut

PWGLF/TableProducer/lfTPCPID.cxx, PWGLF/Tasks/QC/tpc_dEdx_postcalibration.cxx
=> LF: pid calib update, fix skiptpconly

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx
- configurable to choose track sign for each track
- combinations for like-sign with proper policy (CombinationsFullIndexPolicy)
- simplification of the PID procedure for the general TrackTrack task
- adding pT cutoff for TOF usage for PID
-  bug fix in usage of Filter
=> FemtoUniverse: possibility to choose track sign + combinations fix

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx, PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all, 
I've closed the other pull request because when I tried to push new commits those changes appear in my forked repository but not in the PR. 
In this new one I solved some errors in the code.
Best regards,
Samuele
=> PWGHF: Ds-h correlations, solving some errors in the code

PWGDQ/Core/CutsLibrary.cxx
Adapt cut setting to select e+/e- tracks separately and tracks in +/- eta range.
=> PWGEM: New cut setting and adaptation of old ones

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/PhotonMeson: update V0 photon cuts for larger radius
=> PWGEM/PhotonMeson: update V0 photon cuts for larger radius

PWGHF/TableProducer/candidateSelectorLcMl.cxx
I forgot to PR this in the past. It is a small cosmetic fix.
=> PWGHF: Small fix to activateQA in Lc ML selector

PWGCF/FemtoUniverse/Core/FemtoUniverseContainer.h, PWGCF/FemtoUniverse/Core/FemtoUniversePhiSelection.h, PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0.cxx
* added $\Delta \eta \Delta \varphi$ plot for angular correlations
*  checked cuts
=> PWGCF: FemtoUniverse -- Adding Deta Dphi plot + fixing some cuts

PWGDQ/Core/CutsLibrary.cxx
Adjust a PID setting which should reject bad TOF tracks
=> PWGEM: Adjust PID, badTOFrej

PWGLF/TableProducer/lfTPCPID.cxx
=> LFPID: optimize CCDB access

PWGCF/FemtoUniverse/Core/FemtoUniverseContainer.h, PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/Core/FemtoUniversePhiSelection.h, PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0.cxx
Adding $\varphi$ vs $\eta$ QA plot
=> PWGCF: FemtoUniverse -- adding phi vs eta QA plot

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/TableProducer/createPCM.cxx
PWGEM/PhotonMeson: update createPCM and histograms
=> PWGEM/PhotonMeson: update createPCM and histograms

PWGJE/Tasks/jetvalidationqa.cxx
Hi @nzardosh,
for some reason the previous PR would not update after pushing the last fix to my maste branch.
Here are the requested changes. Sorry for the inconvenience !
=> [PWGJE validation] Fixing small bugs and typos 

PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/PhotonMeson: update V0 photon mee cut
=> PWGEM/PhotonMeson: update V0 photon mee cut

PWGLF/TableProducer/lfTPCPID.cxx
- add fatalization of errors
- add possibility to use default values if calibration is not found, in agreement with CF/HF scheme
- message improvements
- streamline
=> Next LF PID

PWGCF/FemtoWorld/Core/FemtoWorldDetaDphiStar.h, PWGCF/FemtoWorld/Core/FemtoWorldPairCleaner.h, PWGCF/FemtoWorld/Tasks/femtoWorldPairTaskTrackD0.cxx
Process switch for different analysis: track-track, track-V0s, track-phi and track-D0 and for different centrality (Run2/Run3).
Corrections in mixed and same event process functions in analysis task.
=> Femto world d0

EventFiltering/PWGJE/fullJetFilter.cxx
Previous implementation rejected trigger as min. bias trigger when it was at the same time a level-0 trigger
=> [EMCAL-903] Accept overlapping triggers as MB triggers

PWGDQ/Core/CutsLibrary.cxx
Add a PID setting corresponding to the PID selection of the pp, 5.02TeV dielectron paper
=> PWGEM: introduce PID setting equivalent to Run 2 pp 5.02TeV

PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx, PWGEM/PhotonMeson/Core/HistogramsLibrary.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
PWGEM/PhotonMeson: add a task for material budget study
=> PWGEM/PhotonMeson: add a task for material budget study

PWGCF/TableProducer/dptdptfilter.cxx, PWGCF/Tasks/dptdptcorrelations.cxx
Also fine tuning the track selection cuts
=> Simplifying the singles data taking. Use configuration

PWGDQ/Tasks/filterPPwithAssociation.cxx
Making the nSigmaForCompat a configurable parameter
=> Modification in filterPPwithassociation.cxx

PWGHF/DataModel/CandidateSelectionTables.h, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/candidateSelectorD0.cxx
ML selection added to the candidateSelectorD0 following the example of the selector of the Dplus (@fgrosa)
=> PWGHF: Add ML selection to the D0 candidate selector

PWGLF/TableProducer/lfTPCPID.cxx
@njacazio: the fix needed a fix﻿
=> Create a dummy LFPID table if there are no BCs

PWGDQ/Core/VarManager.h, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/tableReader.cxx
- CosPointingAngle added to the dimuon tree
- ordering of the dimuon tree in order to ease filling / modifictions
=> PWGDQ: Update of the dimuon table

PWGLF/Tasks/f0980analysis.cxx
=> [PWGLF] adding MC analysis

PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/candidateCreatorBs.cxx, PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
First implementation of Bs tree creator @fcatalan92 @fgrosa.
=> PWGHF: Add Bs tree creator

PWGDQ/Core/CutsLibrary.cxx
Add a new loose PID cut for electron selection
=> PWGEM: add loose electron selection, loose NSig

PWGHF/Core/SelectorCuts.h
Setting the binning for ML application
=> PWGHF: Set the binning for ML application
