- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
Fix PID selection in FemtoDreamDebugTrack task for MC processing.
> PWGCF: add missing PID selection

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/trackIndexSkimCreator.cxx
This PR adds two optimisations for the HF combinatorial:
- For Lc->pK0S, the bachelor track is filtered considering the proton PID (no other hypotheses are used)
- For 3-prong channels, it adds the possibility to apply a cut on the decay length computed with the first two tracks to avoid the third loop
> PWGHF: further optimise HF combinatorial

- PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
Add the option to use a unique seed in time for the downsampling. Also, apply a fix to disable the downsampling if the downsampling factor is set to a negative value, not the seed.
> PWGCF: fix seeding in collision masker

- PWGJE/Tasks/jetfragmentation.cxx
Use fastjet utilities deltaR method for distance calculation
Added functions for V0 checks
Added counting of identified V0s
Added THnSparseF to keep track of the number of all identified v0s in a jet
Added lifetimecut
Fixed cos(PA) axis label
Changed all hists from float to double
Added hists for mass diff, ratio, rel-diff for Lambda and antiLambda
Added V0 eta cuts
Jet eta cuts now derive from V0 eta cut
Added configurable mass windows for rejecting and accepting K0S, Lambda and antiLambda
> Added V0 identification

- EventFiltering/filterTables.h
- PWGDQ/Tasks/filterPP.cxx
- PWGDQ/Tasks/filterPPwithAssociation.cxx
This is a draft to include the dielectron triggers to the filtering schemes.
Using the filterPPwithAssociation.cxx task
Adding two filters: 
kLMeeIMR     (triggering for ee pairs with mass 1.3 to 3.5 GeV/c2)
kLMeeHMR   (triggering for ee pairs with mass above 3.5 GeV/c2)
Need to select LS pairs only for EM dielectron triggers.
So I implemented the selection of LS pairs by a comma separated list of booleans for each filter selected.
I would like to ask @vfeuilla to have a look at this PR. 
Local errors have prevented me to test it, yet.
> PWGEM/DQ: EM filters, Boolean list for like-sign pair selection

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
1. remove the filling of prompt BDT score (11th axis, exceeding the limit at 10);
2. use const AxisSpec objects to properly set axis titles.
> PWGHF: fix THnSparse in polarization task.

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/filterPPwithAssociation.cxx
Changes in the VarManager.h :
- Making the propagation of the mupn track to the vertex a utility function
- Adding FillPairPropagateMuon to propagate muon pairs
Changes in the filterPPwithAssociation.cxx :
- Use of the o2-analysis-track-to-collision-associator and o2-analysis-fwdtrack-to-collision-associator to do the track to collision association instead of doing it internally
- Adding the fPropMuon boolean to have the muon to vertex propagation if needed
> Implementing Muon to vertex propagation in the filterPP task

- PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
Hi @fgrosa , I just copied the MC checks that are already available in the standard workflow. We have some histograms with invariant mass distributions to directly see the different components. On top of that, we can access the decay types at the MC level thanks to the candidate `flagMcMatchRec` stored in the output AOD.
> PWGHF: Implement MC checks in B0 reduced workflow

- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
- take cosPA cascade and V0 from LF tables (--> computed wrt primary vertex) instead of re-computing them
- change vertex for cosPAXY calculation to primary vertex
> PWGHF: change vtx cospa calculation

- PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h
- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
- Correlated Plots: optionally activate ThnSparse to correlate kinematic-, PID and topological variables of the track and the multiplicity estimators of its associated collision
- Not (yet) implemented for daughter tracks
- No further changes in the configuration of other tasks necessary. Option is automatically inactive for the pair and triplet tasks
> [PWGCF] New option for the femtodream-debug task

- DPG/Tasks/AOTTrack/PID/qaPIDTPC.cxx
Adding separate configurable axes for the optional THnSparse - these were defined by the main histogram axes before, and the defaults were too high leading to issues in merging (both on hyperloop and locally). The new defaults on the sparse histos should be more reasonable.
> Add configurable axes for THnSparses in TPC PID QC

- PWGHF/Core/HfMlResponseB0ToDPi.h
- PWGHF/D2H/TableProducer/CMakeLists.txt
- PWGHF/D2H/TableProducer/candidateSelectorB0ToDPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
- PWGHF/DataModel/CandidateSelectionTables.h
Hi @fgrosa , I implemented the ML inference for B0 in the reduced workflow.
Modifs:
- new ML-dedicated header for B0
- reduced B0 selector adapted so one can use ML selection
- reduced B0 task templatized to process data/MC and also to process either with ML information on D meson or on B0 (if we want D meson ML scores, it is to train BDT for B0; and if we want B0 ML scores, we already used the D meson ML scores for the training so we don't need to access them again --> no need to access D meson and B0 ML scores simultaneously).
- a bug was fixed: the B0 candidate tables consumed by the MC process functions did not use to be filtered, they are now
@apalasciano I tag you in case you're interested in using ML for B+ :)
> PWGHF: Implement B0 ML and templatize task

- Common/TableProducer/trackPropagation.cxx
Fix to avoid conflicts with `TracksIU` defined here https://github.com/AliceO2Group/AliceO2/blob/66de30958153cd7badf522150e8554f9fcf975ff/Framework/Core/include/Framework/AnalysisDataModel.h#L392
This was creating unexpected issues with HF derived data.
Thanks @fgrosa for helping me in the debug.
@jgrosseo @ddobrigk to be merged asap.
> Fix data type to avoid conflicts with AnalysisDataModel.h

- PWGJE/Core/JetFinder.h
- Explicit default constructor prevented default construction of Jet Finder, leading to failure of extracting the configuration options from tasks using it
- Default constructor removed as it is not needed
- Member variables can be initialised as need through aggregate initialisation, e.g. `JetFinder jf{.etaMin = -.9, etaMax = .9};`
> PWGJE: Remove explicit constructor of JetFinder

- PWGDQ/Tasks/filterPP.cxx
- PWGDQ/Tasks/filterPPwithAssociation.cxx
Update filterPP task to also select LS pairs if list of boolean is set as configurable for each trigger defined
> PWGEM/DQ: add selection of LS pairs to filterPP task

- PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
@dsekihat in case of mcparticles without mothers for me the line `int motherid = mctrack.mothersIds()[0];` was crashing the task with a seg fault. The extra check `mctrack.has_mothers()` before trying to access the motherId array should protect against this.
> PWGEM: treeCreatorElectronMl: check for mothers before trying to access array

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Fix PID selections on the negative decay daughter of Lambda and Anti-Lambda candidates
> Fix PID selections on Lambda candidates

- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
> PWGEM/PhotonMeson: update foundBC

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- Add QC task "emcalQC.cxx" to monitor cluster properties and effects of cuts
- In createEMreducedevent: Use BCs selected by event selection (using Fit signal)
- Require one collision per BC in GammaGamma task for EMC methods
- Fix M02 cut in skimmerGammaCalo for one cell clusters
> PWGEM/PhotonMeson: Add EMC QC task and enable one collision in selected BC

- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/candidateCreatorB0Reduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
Ciao @fgrosa !
I implemented more checks for the partly reconstructed decays (where the 4 prongs have a common B mother, and where prongs 0,1 and 2 possibly have a common charm mother). This way, we'll be able to understand what is hiding inside the partly reco decay contribution in the B0 invariant mass distribution, and see if it is due to the MC generator config and/or if there is something else.
Modifications:
- in DPi creator: add a `checkDecayTypeMc` configurable to store PDG codes of beauty mother, charm mother, and prongs
- in B0 creator: add a new `process` function filling a new table with these PDG codes for B0 candidates
- in B0 selector: nothing new
- in B0 task: 2 new `process` functions so one can access these "MC checks" information with and without B0 ML selection + a new …
> PWGHF: Add extra checks for partly reco decays in B0 reduced workflow

- PWGHF/D2H/TableProducer/dataCreatorDplusPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
Hello again @fgrosa 
Thanks for reviewing and merging the PR #4723 so quickly :) and sorry, but I just realized that:
- the D mesons can decay into phi mesons then decaying into pions and kaons ([config file](https://github.com/AliceO2Group/O2DPG/blob/master/MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_with_Bforced_decay.cfg)) so the `maxDepth` set in the `getMother` function should be `2` for all the D meson hypothesis (and not only D*)
- it might be better to fill the MC check table without this selection on `flagMcMatchRec` so that one could access each component (pure signal, B0->Ds Pi, partly reco decay, ...) in the invariant mass distribution.
> PWGHF: Fix MC check to get charm mother information

- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMaker.cxx
This PR will evaluate muon DCA after muon propagation in table-maker and update them into muonExtra table.
> [PWGDQ] Add muon DCAs into derived data

- PWGCF/Flow/Tasks/FlowPbPbTask.cxx
1. Add more Event QA and track QA
2. additional track selection for TPC sector overlap
> PWGCF: flow-pbpb: magnet field depended additional track selection for TPC sector overlap

- PWGHF/TableProducer/candidateSelectorLc.cxx
- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
In this PR:
- The forward percentile multiplicity estimators has been added to the LcpKpi tree creator
- The ML cut is now applied in the Lc selector
> PWGHF: New features in LcpKpi task and tree creator

- PWGEM/PhotonMeson/Tasks/emcalPi0QC.cxx
- Require at least one cell to have fired per collision for correct event normalization
- Needed as EMCal trigger flag is not correctly set in some MCs (https://github.com/AliceO2Group/AliceO2/pull/12729)
- Required restructuring of processCollisions function to include BCs, as these are connected to the cells
- Event histogram extended to monitor how many events do not contain any EMCal cells
> PWGEM/PhotonMeson: Require EMCal cell in EMCPi0QC-task

- PWGDQ/Core/MixingLibrary.cxx
FTOC Centrality is added as mixing variable for event mixing.
> [PWGDQ]adding FTOC Centrality in MixingLibrary

- PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR contains:
- The histograms for the resolution of TPCpos-TPCneg couple for event-plane and scalar-product
- The FT0a/FT0c--FT0m combinations were removed since the subsystems  are correlated
> PWGHF: Adding TPCposTPCneg EP and SP resolutions

- PWGLF/TableProducer/LFResonanceInitializer.cxx
It bothers a lot of analyzers...
> PWG-LF: Resonance initializer - Disable CCDB and EP by default

- PWGCF/FemtoDream/Core/femtoDreamContainer.h
- Add the centrality calibration dimension to the extended plot in the femtodream container
> PWGCF: Add Centrality dimension

- PWGLF/TableProducer/nucleiSpectra.cxx
The number of TPC clusters could be used instead, but it's good to restore if for sake of backward compatibility
> Restore isReconstructed flag

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
In the struct that produces cascade-bachelor derived data, remove the continue statements and replace them with a boolean checking on the status of the cascade-bachelor pair
> PWGHF: fix bug in cascade derived data

- Common/CCDB/ctpRateFetcher.cxx
- Common/CCDB/ctpRateFetcher.h
Hello @mpuccio
This removes include of `AnalysisHelpers.h` as to not expose ASoA stuff to root cling - it breaks on c++20 features on linux - unblocking https://github.com/AliceO2Group/AliceO2/pull/12724.
Instead of `Service` wrapper the fetcher functions can use bare pointer. As I understand this is not used in O2Physics, but in QC? One would have to change the invocations to use the pointer from the service (accessible directly as `.service`).
> CCDB: do not include AnalysisHelpers.h in ROOT dictionaries

- .mega-linter.yml
This configuration provides cpplint and clang-format with an exhaustive list of extensions of files to check.
The list is a union of the cpplint default list and the extensions of C++ files found in the O2 and O2Physics repositories, most importantly it adds `.C` ROOT macros.
> MegaLinter: Make cpplint and clang-format check all C++ files. Disable clang-format

- PWGEM/PhotonMeson/Utils/TrackSelection.h
The include of `AnalysisDataModel.h` in a header, that is, in turn, included in ROOT dictionary, exposes some things to rootcling that it cannot chew. This removes the include and makes the template function more generic. Please consider reviewing this soon, as it blocks https://github.com/AliceO2Group/AliceO2/pull/12724.
> DPL Analysis: prevent data model being exposed to rootcling

- Common/DataModel/McCollisionExtra.h
- Common/TableProducer/mcCollsExtra.cxx
This is a first test of a tool that tags collisions according to the properties of their MC neighbours. It is meant such that we can properly calculate MC efficiencies given a certain specific-case gap configuration, taking into account also that the gap itself could contain a particle of interest (e.g. consider the Xi case). 
The basic rationale is to decompose the issues we see in the gap triggering "microscopically" isolating collisions for which the neighbours have or don't have a particle of interest, and to be able to calculate efficiencies in each of the various possibilites. Related to JIRA ticket [3702](https://its.cern.ch/jira/browse/O2-3702); tagging also @ercolessi @nepeivodaRS @ChiaraDeMartin95
> Common: create a MC Collision tool for MC context

- PWGCF/DataModel/FemtoDerived.h
- PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerReducedTask.cxx
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
- New template to estimate the effect of particles assiciated to the
wrong collision
- "Else" template to catch bugs in the determination of the MC origin of
the candidates (to be removed once the procedure is confirmed)
- remove unneeded configurable in the debug-track task
- histograms for the template fits can depend on the multiplicity
- bug fix in the fillQA for tracks in the TripletTrackTrackTrack task
> [PWGCF - FemtoDream] Include new template "WrongCollision" and 3D template histograms 

- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMaker.cxx
- PWGDQ/TableProducer/tableMaker_withAssoc.cxx
- PWGDQ/Tasks/CMakeLists.txt
- PWGDQ/Tasks/tableReader_withAssoc.cxx
Additional changes:
1) Adding enum to define the bits from the filteringTagsfor the muon and barrel tracks
2) fixing the problem with initialized mag field in table-reader-with-assoc
3) In tableMaker_withAssoc, the skimmed fwd tracks are selected according to propagated track params, but the skimmed tracks written to disk will be unpropagated so that the propagation can be applied at analysis time.
> [PWGDQ] Added filter bits for muon and barrel tracks to keep track whether muon propagation and TPC postcalib have been applied at skimming time

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
- inv. mass used for 4-vector calculation was always at 0 by mistake
- add protection due to double mass hypotheses
> PWGHF: fix Lc polarization

- DPG/Tasks/AOTTrack/tagAndProbeDmesons.cxx
This PR contains: 
- additional process function to collect tag topological and kinematic info in data and MC for DsPlus, Dstar
- helper function to collect tag pdg mother in MC and store topo. variables into the table
> PWGHF: Add Topology Tag kinematic and topology table HFTag and probe

- PWGLF/TableProducer/LFResonanceInitializer.cxx
I had to remove CentV0MRun2s from run3 events and disable the process for run2 by default.
> PWGLF: Resonance framework hotfix for run3 study

- PWGDQ/Tasks/tableReader.cxx
Dear DQ code experts,
it seems to me that for the same event pairing the filling of the histograms in lines https://github.com/AliceO2Group/O2Physics/blob/da70ecf75cb1484c9343e5c08445e9f097fe274f/PWGDQ/Tasks/tableReader.cxx#L1094-L1142 seems to get mixed up. E.g. sometimes I get more entries in histograms with pair cuts than in the corresponding histogram without pair cuts.
I think it should be fixed in line 1140, where the variable `iCut` is not shifted by the correct amount.
Sorry in case I'm missing something super obvious...
> PWGDQ: tableReader: fix pair histogram filling

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
Add information about charm baryon generated eta (needed for offline analysis) in the MC table produced by candidateCreatorToXiPi
> PWGHF: add generated eta information for charm baryon

- PWGEM/Tasks/phosCalibration.cxx
- PWGEM/Tasks/phosCellQA.cxx
- PWGEM/Tasks/phosCluQA.cxx
- PWGEM/Tasks/phosPi0.cxx
1. In phosCalibration fixed the issue connected with excessive ccdb queries which caused problems for the services. 
2. In phosCalibration and phosPi0 added a few new histograms to evaluate M02, M20 and number of cells in a cluster. Also implemented a new cut based on M02 and M20 values.
3. In phosCluQA and phosCellQA fixed remaining issues with wrong type conversions (.bc_as<> and .collision_as<>).
> Bug fixes for PWGEM/Tasks

- PWGLF/TableProducer/cascadebuilder.cxx
- PWGLF/TableProducer/lambdakzerobuilder.cxx
- Remove useless switch `skipGRPOquery` which was equivalent to switching between Run 2 and 3.
- Pick the right method automatically based on the enabled process function.
- Fix the wrong fatal message.
- Avoid misleading CCDB error messages caused by trying the Run 3 method with Run 2 input.
- Use the same field for DCAFitterN and KFParticle (instead of `lround` calculation for DCAFitterN and Run 3).
- Fix C++ issues reported by cpplint.
> PWGLF: Fix magnetic field retrieval in lambdakzero-/cascade-builder

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
Replace the pT-eta histograms to the Delta pT-pT histograms, and tighten the Rabs cut for muon source separation task.
> PWGHF: Modify the muon cuts and histograms in HFL muon source task

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add QA plots on the TPC Nsigma (as function of centrality and pT) of the positive and negative decay daughters of K0Short, Lambda and Anti-Lambda
> Add TPC NSigma QA plots

- PWGLF/DataModel/LFHStrangeCorrelationTables.h
- PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
@lhusova @kcui1 @ChiaraDeMartin95 minor bugfix after the split of V0Data into V0Core/V0Index
> PWGLF: h-strangeness bugfix

- Common/TableProducer/trackPropagation.cxx
- Common/Tools/TrackTuner.h
Fix in the smearing of out-of-diagonal term `sigmaZY` of the track cov. matrix in the `trackTuner`.
Error found running on derived data on HF trigger MC (`LHC22b1a`, `LHC22b1b`) on Hyperloop and enabling the `candidateCreator3Prong`.
In few cases the code was throwing the `invalid track covariance` error, triggered by [this](https://github.com/AliceO2Group/AliceO2/blob/66de30958153cd7badf522150e8554f9fcf975ff/Common/DCAFitter/include/DCAFitter/DCAFitterN.h#L38-L54), i.e. when the `detXY` is negative.
By fixing the `sigmaZY`, and adding a protection that restores the original `sigmaY2`, `sigmaZ2` and `sigmaZY` values in case of `detYZ = sigmaY2 * sigmaZ2 - sigmaZY * sigmaZY < 0` after the smearing, the `candidateCreator3Prong` worked with both `updateTrackCovMat=1` and `updatePulls=1`. The …
> Common/PWGHF: fix smearing of sigmaYZ cov. matrix term in TrackTuner, and add protection.

- PWGCF/Tasks/dptdptcorrelations.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Now it is feasible to order it with PID info collection or without it as well as within multiplicity classes or just MB
Additionally
- removing the self-configuration logging
- introducing the timestamp checking task
> Making more flexible the efficiency and QA task

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/filterPPwithAssociation.cxx
This PR Draft has not been tested yet!!!
Adapt `track selection` to perform a recalculation of the DCA parameter.
Following the example of the `TableReader_withAssoc` using
`VarManager::FillTrackCollision<TTrackFillMap>(track, collision);`
and the `void runMuonSelection()` function.
So far no flag has been introduced to select this recalculation.
@rbailhac @dsekihat @hscheid  I would appreciate if you could have a first look at this.
I'm not sure if this implementation is the way to go, but I tried to follow other examples.
> PWGDQ/EM add recalculation of DCA param of TrackToCollAssoc tracks

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also proper histogram run number labeling and get rid of self-initialization printouts
> Protect the exclusive run of the timestamp check task

- PWGCF/DataModel/FemtoDerived.h
- PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerReducedTask.cxx
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- FDExtMCTable: Properly include the extended FemtoDream Table for
additional information in the debug task (for now only the pdgCode
of the mothers is added)
for the mother particles is added)
- additonal histograms for the PDGcode of the Mother particle for each MCorigin (activated in the debug task)
- fix the categorization of MC origins in the producer task
>  [PWGCF-FemtoDream]: Debug task MC

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add TPC signal and TPC nsigma plots as a function of the track transverse and total momenta for the positive and negative decay daughters, in order to understand the efficiency dependence on centrality
> Add TPC QA plots for positive/negative V0 daughters

- PWGEM/PhotonMeson/Core/CMakeLists.txt
- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/CutsLibrary.h
- PWGEM/PhotonMeson/Core/EMEventCut.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Core/HistogramsLibrary.h
- PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h
- PWGEM/PhotonMeson/Tasks/CheckMCV0.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx
- PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx
- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Tasks/phosQC.cxx
add EMEventCut and rename namespace
> PWGEM/PhotonMeson: add EMEventCut and rename namespace

- PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
This PR adds the Ds sign to the tree creator output.
This is needed to study possible differences in the mass distribution between positive and negative candidates.
To avoid enlarging the lite tree, and because this information is not needed for the physics analysis, the variable was added to the full tree
> PWGHF: Add Ds sign to the output of the tree creator

- Common/DataModel/Multiplicity.h
- Common/TableProducer/multiplicityTable.cxx
- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/strangederivedbuilder.cxx
@romainschotter @lhusova This pull request:
* modifies the multiplicity data model for some extra MC QA by adding MC multiplicities that are joinable with `mcCollisions`. 
* In the LF derived data, it provides base functionality for linking `StraCollisions` to mc collisions and `V0MCCores/CascMCCores` to mc collisions. In doing so, it allows for the use of derived data to cross-check collision association for both V0s and Cascades in the analysis of Pb-Pb
> Common/PWGLF: coll assoc + mult debug extras

- PWGLF/Tasks/Strangeness/cascadeanalysisMC.cxx
Also subscribe to tracks table in the "withPID" process functions, both for run 2 and run 3
> PWGLF: add missing 'IU' in run 3 process function

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/CMakeLists.txt
- PWGHF/TableProducer/candidateSelectorD0.cxx
- PWGHF/TableProducer/pidCreator.cxx
Workflow to produce tables with combined TPC+TOF sigmas in static columns instead of extended tables with expression columns.
Rationale: Extended tables have to be spawned. Spawning cannot be conditional (yet) so it is not possible to produce extended tables for different particle species only when needed. Spawning needed tables inside different selector workflows makes it impossible to run these workflows together because of the conflicting table production.
Implementation in this PR:
- Produce normal tables with static columns for all particle species and table types (full, tiny).
- Run one process function per table to isolate subscriptions to parent PID tables (which automatically enable their filling by the PID task).
- Automatically disable process functions enabled for not needed …
> PWGHF: Add workflow for producing combined TPC+TOF NSigma

- PWGHF/Utils/utilsBfieldCCDB.h
A quick fix to allow passing `nullptr` when LUT is not needed.
> PWGHF: Make LUT optional in initCCDB

- Common/DataModel/Multiplicity.h
- Common/TableProducer/multiplicityTable.cxx
- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/strangederivedbuilder.cxx
@lhusova @romainschotter following also a suggestion from @lhusova, this adds enough information for us to explore a correlation cut on Number of PV contributors and global (=ITSTPC, not necessarily PV contribs) tracks, just for a cross-check.
> Common/LF: add some extras for QA of evsel based on PF info

- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
There is an upper limit on objects that can be defined in a workflow and that limit was hit in the track-v0 task. Removing the old same and mixed event process function (deprecated, use masked version instead)  resolves the problem. Hitting the limit does not throw a compilation error but the task cannot read any inputs anymore, making it unusable.
> PWGCF: Bugfix in pair-track-v0 task

- PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
This PR adds the Ds sign to the tree creator output.
This PR is similar to #5001 , but adds the sign information to the LITE table, since the usage of FULL tables has been discouraged
> PWGHF: Add Ds sign to tree creator

- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
Hello @fgrosa !
As we discussed, I have implemented the possibility of having a selection on the Ds prongs' DcaXY in the candidate selector.
The default configurables values are the same as the ones for the track-index-skim-creator.
> PWGHF: Add DcaXY selection to Ds selector

- PWGHF/TableProducer/treeCreatorXicToPKPi.cxx
fixing issue of unbound indices in XicpKpi MC trees
> PWGHF: removing index from FullPs tree

- PWGLF/TableProducer/nucleiSpectra.cxx
Adds a new flag to indicate if a track has TRD information. The flag was updated
to better reflect the presence of TRD data and improve clarity in the code.
> refactor: Update flag from kIsReconstructed to kHasTRD

- PWGHF/TableProducer/treeCreatorToXiPi.cxx
Fix index dereference in  treeCreatorToXiPi
> PWGHF: fix index dereference toXiPi

- PWGHF/D2H/Tasks/taskDs.cxx
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGLF/Tasks/Nuspex/QCspectraTPC.cxx
Hello @fgrosa , as you suggested I have added new process functions to the Ds task, one for each centrality estimator.
This allows to produce less centrality tables and to get a faster processing of data
> PWGHF: Reduce number of produced centrality tables in Ds task

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
@romainschotter I'm on fire! On fire with bugs! Here, I did not notice the bool from EvSel is actually a "NOT at border" and rejected everything "NOT at border". Now it's correct: I'm rejecting events that are NOT NOT at border... Phew.
> PWGLF: Fix bool check (double-negative...)

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
The change is temporary, and aims to check the Number of cluster dependence for each kind of global tracks. Once the MFT information is available in DQ's table-maker-MC, this change will be recovered.
> PWGHF: Add the NumberOfCluster in MFT information in the outputs of HFL single muon source task

- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- Change pi0 and eta decay channel to gammagamma (instead of mumugamma)
> PWGEM/PhotonMeson: Correct pi0 and eta decay channel for EMC

- PWGJE/Tasks/jetfragmentation.cxx
* Added event selection for data
* Added full treatment of missed particle level jets
* Added event selection for MC detector level, clarified that MC V0 processes are for matched V0s
* Added slicing on MCPjets in matched case, to allow for proper treatment of misses
* First attempt at V0 fragmentation in matched MC
* Added Response Matrix, Fakes and Misses
* Added correlation histograms for V0 parameters with pt for fakes and misses
* Added McV0Labels
* Joined mcd jcollisions with parent index table, so we can retrieve associated collisions
* Replaced filters with partitions
* Added fake/miss hists for V0s and identified V0s
* Added fake/miss filling functions for V0s
* Added fake/miss treatment in process function
* Added identified matched histograms
* Added matched V0 filling function …
> [PWGJE]: Jet Fragmentation: Fill Response Matrix

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
@romainschotter (and @lhusova) this fixes the decoding of the generated-level information that is stored encoded in our MC generated data, pending a proper solution in which we store some binned information together for convenience. It has been tested to work locally, though the main caveat (a **very** serious one) is that we have to use the same binning as the derived AO2D generation. 
@lhusova note that in fact our task decodes the full generated information *also* for the cascades, so this could be useful for you too if you like (or you can copy the relevant part)
> PWGLF: Fix decoding of generated information from derived AO2Ds

- PWGJE/DataModel/EMCALClusters.h
- PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add MC Cluster tables to `PWGJE/DataModel/EMCALClusters.h`
- Fill MC Cluster tables inside `PWGJE/TableProducer/emcalCorrectionTask.cxx`
IMPORTANT NOTE: This change is part part of two to include the MC Calo Labels into EMCal clusters. Part one is in O2 and required for this to compile. See PR https://github.com/AliceO2Group/AliceO2/pull/12660. 
Locally on a Mac everything runs fine, but on linux it crashes at the end of the ProcessMC function of the EMCalCorrectionTask. This crash is only for running the EMCalCorrectionTask with the ProcessMC. So to enable tests for more people and maybe even the GRID I thought we might want to push it. There should be no problem with all the currently used workflows and process functions!
> [EMCAL-670] [EMCAL-1109] Addition of EMCalMCCluster tables

- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.h
- PWGEM/PhotonMeson/TableProducer/createEMReducedEvent.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- Add minbias_noTBForROFCut event cutstring for MB events without ITSROF or TBF restrictions
- Query event cut settings (NoTFB and ITFROFB) in EMEventCut.h
- Add requireCaloReadout configurable to circumvent trigger requirement (wrong in certain MCs)
- Fix bin labels in emcQC task
> PWGEM/PhotonMeson: Add event selection cutstring and calo readout configurable

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I've modified the correlator in order to select collisions with the sel8 flag
Cheers,
Samuele
> PWGHF: Adding event selection in the correlatorDsHadrons task

- Common/TableProducer/mcCollsExtra.cxx
@romainschotter @lhusova I was looking at the wrong place for my bug. It was a silly mistake in an auxiliary tool. Now the decoding of generated histograms works fine!
> Common: fix forgotten line

- PWGHF/Core/HfHelper.h
- PWGHF/Core/HfMlResponseDsToKKPi.h
- PWGHF/D2H/Tasks/taskDs.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
- PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
This PR replaces the cos3PiK variable in the HfMlResponseDsToKKPi with its absolute value. This is to avoid confusion as the non-absolute value is not included in the Ds tree creator, and one cannot train a model using it as a feature
> PWGHF: Replace cos3PiK with its absolute value in HfMlResponseDsToKKPi

- PWGHF/Tasks/taskMcEfficiencyToXiPi.cxx
- PWGLF/Tasks/Resonances/lambda1520analysis.cxx
In the task that computes the efficiency for the xi pi decay channel: switch from info to debug for log messages. The reason for this change is the need to reduce the log file size on hyperloop (at the moment the size is above the limit and prevents from running the task)
> PWGHF: reduce size of log from toXiPi efficiency task

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
> PWGEM/PhotonMeson: reduce skimmed MC data size

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
Just corrected the order of members passed to getDeltaPhi function
Cheers,
Samuele
> PWGHF: correlatorDsHadrons, correct getDeltaPhi

- PWGLF/TableProducer/cascadepid.cxx
- PWGLF/TableProducer/lambdakzeropid.cxx
This PR: 
* corrects a small bug in the negative prong PID under the K0Short hypothesis (thanks @romainschotter for spotting!) 
* adds a cascade path for the TOF PID which may be of interest to @lhusova @ChiaraDeMartin95 @skundu692 @mpuccio 
As a side comment, this seems to perform better in Pb-Pb `pass2` than the first tests in `pass1` ([shown in the PAG](https://indico.cern.ch/event/1362697/contributions/5736690/attachments/2777839/4841421/DDChinellato-StrangenessTOF-01.pdf)). I'm testing a bit more. 
The next step, when I manage to find the time, is to calibrate the signals and store a calibration in the CCDB. This should allow for a direct Nsigma selection as well as an effective correction of energy loss at the lowest momentum, potentially increasing the usefulness of TOF pid in that …
> PWGLF: add cascade TOF pid code

- PWGHF/D2H/Tasks/taskLc.cxx
-  remove the redundant Configurable "applyML" 
-  replace the "Partition" with "Filter"
- Fixes https://github.com/AliceO2Group/O2Physics/pull/5040
> PWGHF: Lc task: Remove the redundant Configurable and keep using the Filter

- Common/Core/RecoDecay.h
- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
Hello @vkucera ! Here is my proposition to take B0(s) oscillation into account.
---------------------------------------
**The "issue" in a nutshell**
Let's suppose we aim at reconstructing the decay channel `B0bar -> D+ Pi-`. Currently, the code (at MC reco and gen levels) perfectly allows to do so by checking this decay channel with a set of pdg code signs `(-1 -> +1 -1)`. However, if B0 flavour oscillation occured, we actually have `B0 -> B0bar -> D+ Pi-`.
Here comes the "issue": in the genealogy of the decay products, the `B0bar` mother does not appear (when oscillation occurs), only the `B0` appears. In other words, the beauty meson after oscillation is "not seen" and one can only retrieve the pdg code of the beauty meson before oscillation, which of course leads to a rejection of the …
> Common | PWGHF: Take flavour oscillation into account at MC reco and gen levels

- PWGDQ/Core/VarManager.h
Fixing mother mc particle information. This modification solve dqEfficiency break when running on latest productions.
> [PWGDQ] Fixing mother mc particle information

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
@stefanopolitano is experiencing the following run-time error when using the `track-index-skim-creator` for local debugging:
```
[FATAL] Unhandled o2::framework::runtime_error reached the top of main of o2-analysis-hf-track-index-skim-creator, device shutting down. Reason: Failed to create filter: ExpressionValidationError: Function int32 castINT(uint16) not supported yet.
```
Probably, the data-type change done here https://github.com/AliceO2Group/O2Physics/commit/c8ea8cad372783aea1a9396bb4acd47d201baf73#diff-bc149e5241d965436914a3a7c144b71bcceb435b5bd18cf7887925e11151355dL204-L206 is responsible for it.
> PWGHF: explicit type-cast for whyRejectColl.

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/dptdptcorrelations.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also
- if there is TOF, always use it although the threshold were not reached (this should not make necessary to discard the garbage below a certain beta)
- the filters for the different matching now exclude the DCA cut
> Incorporated the electrons and muons also to the PID QC

- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
Hello @fgrosa !
I found another bug :)
We need to fill the DplusPi McRec table after the decay type checks, otherwise the `flag` value is not updated.
> PWGHF: Fill DplusPi McRec table after correlated bkg checks

- PWGLF/DataModel/LFStrangenessPIDTables.h
- PWGLF/TableProducer/lambdakzeropid.cxx
This PR adds an N-sigma calculation path for the strangeness TOF based on the latest Pb-Pb reconstruction. Being tested for the time being, kept as draft until confirmed @njacazio
> PWGLF: add TOF N-sigma for strangeness

- PWGCF/EbyEFluctuations/Tasks/RobustFluctuationObservables.cxx
new QA checks for FT0 vs track vertex, ITS ROF, etc.
> Update RobustFluctuationObservables.cxx: optimized + new QA

- PWGMM/Mult/DataModel/ReducedTables.h
Reduced BC table should have description "RBC" for the index to merge correctly.
> PWGMM: Mult: Update ReducedTables.h

- PWGHF/Core/HfMlResponseD0ToKPi.h
- PWGHF/Core/HfMlResponseDplusToPiKPi.h
- PWGHF/Core/HfMlResponseDsToKKPi.h
- PWGHF/Core/HfMlResponseLcToPKPi.h
- PWGHF/Core/HfMlResponseXicToPKPi.h
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
Also changed the name of impact parameter features in the HfMlResponseD0ToKPi  to explicitly be impactparameterXY
> PWGHF: Add columns of impact parameter z for daughters of 2-prong and 3-prong candidates

- PWGLF/TableProducer/nucleiSpectra.cxx
Remove unused ccdb options such as cfgGRPpath, cfgGRPmagPath, cfgLUTpath, and cfgGeoPath. Simplify the retrieval of the Bz field by directly fetching the GRPMagField object for the specified timestamp and initializing the field.
> Remove unused ccdb options and simplify Bz field retrieval

- PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
comparison of integer expressions of different signedness [-Wsign-compare]
> PWGHF: Fix compilation warnings: sign-compare

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGJE/TableProducer/emcalCorrectionTask.cxx
PWGEM:
- Add tables in gammaTables that contain
- The array of mcparticles contributing to the skimmed clusters
- One mcparticle with the em-mcid that is the largest contributor to a skimmed cluster
- Fill one table in skimmerGammaCalo and the other in associateMCinfo
- Implement pairing of true pi0s and etas in the GammaGammaMC task
PWGJE:
- Copy missing functionalities from data to MC workflow (Collision matching)
> PWGEM+JE: Add validated/true cluster and pi0 workflow for EMC

- DPG/Tasks/AOTEvent/eventSelectionQa.cxx
- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
Fix loop over generated particles in candidateCreatorToXiPi: now at each step of the decay chain all the daughters are taken into account
> PWGHF: fix loop over generated particles toXiPi

- PWGMM/Mult/TableProducer/trackPropagation.cxx
This will allow the bin entries to go up to 2^53, instead of 2.147E9
> [PWGMM] Change the type of histograms in trackPropagation.cxx

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
Add the additional pT TH1 histograms for MCH-MID match and MCH standalone tracks since the DCA and matching chi2 are not available in those types
> PWGHF: Add the availability for type3 and type 4 muon tracks in HFL muon source task

- PWGDQ/Macros/dqFlowAccWeights.C
This is a simple macro helping us to send produced GFWWeights for Q-vector to a CCDB user-path.
> [PWGDQ] Macro for sending GFWWeights to a user-path CCDB

- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
It seems that there is a bug/issue in the central mixing framework when using partitions of tables. Go back to the original implementation, where the underlying table of a partition is passed (which may result in larger memory usage, but the mixing is working as intended) to the combination object.
> PWGCF: fix for event mixing

- PWGDQ/Core/VarManager.h
- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/dqFlow.cxx
- PWGDQ/Tasks/tableReader.cxx
The Q-vectors from the central framework are now saved in a dedicated table which can be produced separately or together the standard Q-vector table from GFW.
This development is meant for the streaming campaing for Pb-Pb 2023 data.
> [PWGDQ] Adding flow extra table from central Q-vector framework

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've added a cut on eta for D0/D0bar candidates and in the task I've added the possibility to calculate the angular correlations either with all D0/D0bar (with cand. marked as both cand.) or with only D0/D0bar (marked as only D0/D0bar).
> PWGCF:FemtoUniverse - D0/D0bar analysis update

- PWGMM/Mult/TableProducer/particles2tracks.cxx
@aalkin to be tested, and as always super thanks for your help and the nice discussions :-D
> MM: particles 2 tracks alternate process test

- PWGLF/TableProducer/cascadepid.cxx
- PWGLF/TableProducer/lambdakzeropid.cxx
@njacazio can you please take a look to see if I got this right? Thank you very much!
> PWGLF: TOF PID checking hasTOF

- PWGLF/DataModel/LFStrangenessPIDTables.h
- PWGLF/TableProducer/cascadepid.cxx
- PWGLF/TableProducer/lambdakzeropid.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
* adjust NSigma getters to conform to usual convention of PID getters, i.e. `[detector]NSigma[species]` with extra `[A](...)[Z]` ordering for decay chains, with `[Z]` being the last state:
* `tofNSigmaLaPi`: negative pion from Lambda decay
* `tofNSigmaLaPr`: proton from Lambda decay 
* `tofNSigmaALaPi`: positive pion from AntiLambda decay 
* `tofNSigmaALaPr`: antiproton from AntiLambda decay 
* `tofNSigmaK0PiPlus`: positive pion from K0 decay 
* `tofNSigmaK0PiMinus`: negative pion from K0 decay
* `tofNSigmaXiLaPi`: negative pion from lambda from XiMinus decay (for matter, adjust automatically to positive pion from AntiLambda in case cascade sign is positive / antimatter)
* `tofNSigmaXiLaPr`: proton from lambda from XiMinus decay (for matter, adjust automatically to antiproton from …
> PWGLF: TOF Nsigs for cascades + adjustments

- PWGHF/D2H/Tasks/taskDs.cxx
This PR adds a folder structure to the output of the Ds task, which now also contains information on the Dplus-> piKpi  MC particles being reconstructed as Ds->KKPi.
For the folder structure, I have created an array of `std::unordered_map`s, one for each "type" of data  defined in the DataType enum, in order to avoid code repetition. Each map contains pointers to the histograms to be filled, with a proper label to identify them. For each type of data, the full set of histograms is created and filled, so that now the [comment](https://github.com/AliceO2Group/O2Physics/pull/4789#pullrequestreview-1890959400) on PR #4789 regarding the lack of multiplicity information for MC matched candidate has been resolved. 
For what concerns the need for adding an output for the Dplus-> piKpi, we are …
> PWGHF: Add output folder structure and Dplus -> piKpi MC information to Ds task

- EventFiltering/PWGMM/multFilter.cxx
This was causing a bug in the interface with the CEFP by increasing the size of the keepEvent array and shifting the bits by 1
> Remove unused constant kHighFv0Flat

- EventFiltering/PWGLF/filterf1proton.cxx
- EventFiltering/PWGLF/nucleiFilter.cxx
- EventFiltering/PWGLF/strangenessFilter.cxx
This is an example to be followed by the other PWGs to enable automatic verification of the consistency of the scalers with the CEFP reporting
> Standardise scalers reporting in LF

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
Minor update: reject events with centralities < 0 and > 100
> Small update PWGMM/Mult/Tasks/heavy-ion-mult.cxx

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
Separate the previous `LightDecayMu` into three components: `LightDecayMu`, `BeautyToLightDecayMu` and `CharmToLightDecayMu`
> PWGHF: Separate the HF-chain decay muons from light flavor decay muons in the HFL muon source task

- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx
- PWGEM/PhotonMeson/Utils/MCUtilities.h
- Add function that checks the decay chain of a cluster to see, whether it originated from a gamma from a pi0 or eta decay
- Include true pi0s in output whose photons converted in the detector material (mostly TOF)
> PWGEM/PhotonMeson: Include true pi0 for EMC with converted photons

- PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
For certain particles, like deuterons, we see contamination from other particle species in the momentum region where we rely on TPC information. It seems that we can reliably get rid of this contamination when we reject certain PID hypotheses depending on the TPC nsigma. Add this functionality here for debug, track-track-pair  and collision-masker tasks.
> PWGCF: add PID rejection in FemtoDream

- PWGDQ/Tasks/dqFlow.cxx
Fix bug of Q-vector normalisation coming from the insufficient size of type `uint8_t`
> [PWGDQ] Fix bug for Q-vector normalisation

- PWGCF/FemtoDream/Core/femtoDreamCollisionSelection.h
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerReducedTask.cxx
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
New event selection bits have been added to the central event selection task here PR https://github.com/AliceO2Group/O2Physics/pull/5411
In this PR they are added to the FemtoDream producer task. All the checks added are pending to be included in sel8 selection. Once this has been done, these additional checks can be removed again.
> PWGCF: add new event selection bits to FemtoDream producer

- Common/Core/TableHelper.cxx
Current problematic behaviour:
- `if (required && flag == 0)`:
- info "Table disabled but required" (correct, but should be at least warning if not error or fatal)
- `flag = 0` (redundant)
- info "Table disabled and not required" (incorrect)
- `if (!required && flag == 0)`:
- `flag = 0` (redundant)
- info "Table disabled and not required" (correct)
- `if (!required && flag < 0)`:
- `flag = 0` (correct)
- info "Table disabled and not required" ("disabled" is misleading when referring to -1)
Expected behaviour:
- `if (required && flag == 0)`:
- warn "Table disabled but required"
- `if (!required && flag == 0)`:
- info "Table disabled and not required"
- `if (!required && flag < 0)`:
- `flag = 0`
- info "Auto-disabling table"
Also in the `bool flag` version, setting `flag = false` is …
> Fix logic and reporting of table auto-enabling

- Common/TableProducer/multiplicityTable.cxx
> Fix default filling flag for MultsExtraMC in multiplicityTable

- PWGCF/FemtoDream/Core/femtoDreamCollisionSelection.h
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
This PR contains two fixes:
- There is an upper limit on configurables that can be declared in a task. With the last PR this limit was hit and not detected locally. Remove the configurable on using the TPC only charge track multiplicity since it has not been used in the past.
- Add one more advertised event selection bit kIsGoodZvtxFT0vsPV. After discussion with Igor, it is safe to include as long as one increases the limit set in the event selection task to a more reasonable value (like 4 instead of 1).
> PWGCF: add final event selection bit to FemtoDream

- PWGUD/Core/DGCutparHolder.cxx
- PWGUD/Core/DGCutparHolder.h
- PWGUD/Core/DGSelector.h
- PWGUD/Core/UDHelpers.h
- PWGUD/Tasks/upcTauCentralBarrelRL.cxx
It is 5 cuts in total. Currently implemented per-partes in the DGselector, but could be used in one function together too.
+ some small modifications to my personal task.
> [PWG-UD] Adding latest cuts from event selection task as an option to DGselector

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: remove unused histograms
> PWGEM/Dilepton: remove unused histograms

- PWGLF/DataModel/spectraTOF.h
- PWGLF/Tasks/Nuspex/spectraTOF.cxx
> LF: Add mismatched info

- PWGLF/TableProducer/lambdakzerobuilder.cxx
This pull request groups several configurables of the lambdakzerobuilder into `ConfigurableGroup`s to circumvent issues in which the configuration of this task is parsed incorrectly due to exceeding the maximum number of data members per analysis task in the O2 framework.
> PWGLF: cluster configurables into groups

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
This only apply, for the time being, to the pass3 variety of the global tracks selection
> Apply the same pT dependent DCAxy cut on DCAz

- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
PWGEM/PhotonMeson: fix for sliceByCachedUnsorted
> PWGEM/PhotonMeson: fix for sliceByCachedUnsorted

- PWGHF/D2H/Tasks/taskDplus.cxx
This PR introduces two process functions to the Dplus Task to fill THnSparse objects with candidate Mass, Pt and BDT scores for ML analysis .
The task's architecture now includes template functions for histogram filling, aiming to simplify future modifications and expansions.
> PWGHF: Modified Task Dplus adding THnSparse for ML

- PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR implements the `sliceBy` in the taskFlowCharmHadrons.cxx as discussed in https://github.com/AliceO2Group/O2Physics/pull/5089
> PWGHF: Adding sliceby in HF flow task

- PWGLF/TableProducer/converters/strangederivedconverter.cxx
@romainschotter @lhusova this will impact the current use of the TOF PID in the old AO2Ds. The new AO2Ds being produced now are unaffected - it is just a bug in the converter. Starting with the merge of this fix, the old AO2Ds can also be used just fine. Sorry for the slipup!
> PWGLF: fix strangederivedconverter TOF PID filling

- PWGJE/Tasks/jetfragmentation.cxx
* Removed mass rejection windows to change V0 PID from exclusive to inclusive
* Created separate DCA cuts for proton and pion daughters
* Moved DCA +- cuts to PID functions
* Added rel. diff. ptV0 histogram
* Renamed V0 configurables for clarity
* Added ThnSparse for V0 cut variation study
* Added Lambda0 reflection histograms
* Added matched identified V0 hists for all masses, to study double counting
* Added data hists: ptjet, ptv0, mass, mass, mass
* Changed reflection to only use V0 information
* Removed deprecated pdg configurables
> [PWGJE] Jet Fragmentation: Changes to V0 tagging, added histograms for background studies

- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
Remove the NumberOfCluster in MFT histograms
Add the DeltaPt column in the derived table
Recombine the heavy-flavour to pi, K to muon into light flavour muons
> PWGHF: Remove the NumberOfCluster in MFT histograms in HFL muon source task

- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
- added optional argument for the QA histogram init() to specify general histogram folder names. By default, the original behavior is used, in which the folder names are generated by particle name and the suffix.
- The V0 task now uses the extended functionality to specify folder names for the different V0 types, which was not possible before.
> PWGCF: FemtoUniverse -- added support for arbitrary QA histogram folder names

- PWGLF/DataModel/LFLithium4Tables.h
- PWGLF/TableProducer/Nuspex/lithium4analysis.cxx
New columns added to LFLithium4Tables.h (ITS cluster size, PID for tracking, MC transverse momentum for Li daughters). The sign of the Li and its daughters are now stored in the reconstructed transverse momentum.
> PWGLF: Lithium4analysis

- PWGHF/HFL/Tasks/CMakeLists.txt
- PWGHF/HFL/Tasks/taskSingleMuonReader.cxx
- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
1.Add the table-reader task for the single muons produced by DQ's table-maker in HFL
2.Remove the sel8 selection in muon source task
> PWGHF: Add the table-reader task for single muon in HFL

- .mega-linter.yml
Enable uploading artifacts with formatted files https://megalinter.io/latest/reporters/UpdatedSourcesReporter/
MegaLinter first runs the formatting and then the rest of linters. If those linters find errors, the line numbers they report in the log refer to the formatted files, not to the committed files.
The artifacts allow to download the formatted files and find the exact location reported by the linters.
> MegaLinter: Upload artifacts with formatted files

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
- I've fixed the evaluation of associated particle efficiency requiring to use only particles coming from sel8 events for the reconstructed part (numerator). 
- I've fixed the secondary particle contamination evaluation requiring that the Ds meson used to build the correlations is a real signal candidate.
Let me know if there are any comments,
Best regards,
Samuele
> PWGHF: Ds-h correlations, minor adjustments in assoc particle efficiency evaluation

- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
In this commit we're trying to improve the randomness mechanism for a pair assignment. In case of 3d we're sensitive to the projections of the relative momentum (in 1d we take an abs. value -- irrelevant). In principle pairs must be the same but the pair order [particle1, particle2] must be random. The pairing has a pattern and in order to eliminate it we used shuffling before, this time we just randomly choose the sign of the momenta difference p1 - p2 I.e. order. We expect it to be a more correct way of eliminating any patterns. Could you please approve this commit? Thank you.
> modifing randomness mechanism in a pair rel. momentum calculation

- PWGLF/TableProducer/Resonances/LFResonanceInitializer.cxx
- PWGLF/Utils/collisionCuts.h
1. `kNoSameBunchPileup` : Pileup rejection
2. `kIsGoodZvtxFT0vsPV` : removes collisions with large differences between z of PV by tracks and z of PV from FT0 A-C time difference.
3. `kIsVertexITSTPC` : selects collisions with at least one ITS-TPC track
> added new collision cuts

- Common/TableProducer/PID/pidTPC.cxx
- Common/TableProducer/PID/pidTPCFull.cxx
Addresses several issues that popped up with NN application in trigger selection:
- impose (configurable) cutoff in expected beta-gamma to remove artifacts reported by PWG-CF in very low-momentum antiprotons where network extrapolation causes issues (below this value only BB is used, betagamma >0.45 is set as a conservative default ) - plots below are expected dE/dx and nsigma for protons, (left) without the betagamma cutoff and (right) with the cutoff
- add protections for case where the collision table is not populated (CCDB timestamp request now only references the collision table if the track is explicitly associated to a collision, and from the BC table directly otherwise. Also disables NN correction for tracks with no associated collision, as the application uses info from the …
> beta-gamma cutoff, enable flags per species for NN

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
The extra factor of 0.1 that was scaling the magnetic field is removed.  
However, after removing this factor, the asin(<arg>) function for calculating dphi was blowing up at certain (mostly higher) values of radii. This is also taken care of by only allowing abs(<arg>) < 1.0.
> PWGCF : Femtouniverse -- Fixing bug in dphi calculation

- PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
This PR contains two features:
- Fix close pair rejection (CPR) and add configurables to use the old version if needed (for testing purposes, will be made default once validated)
- Group configurable into the configurable group. This should make interaction on hyperloop less painful and avoid hitting the maximum number of configurables in a task.
> PWGCF: Cleanup Pair task

- PWGCF/JCorran/Core/JFFlucAnalysis.cxx
- PWGCF/JCorran/Core/JFFlucAnalysis.h
- PWGCF/JCorran/Core/JQVectors.h
- PWGCF/JCorran/Tasks/jflucAnalysisTask.cxx
The Q-vector calculation code is moved from JFlucAnalysis to a shared header, so that other analyses under JCorran can take advantage of it. At the same time, the class is further templated to be more flexible under different requirements.
> PWGCF: Generic JQVectors class for JCorran

- PWGHF/TableProducer/candidateCreatorB0.cxx
- PWGHF/TableProducer/candidateCreatorBplus.cxx
Fixes a bug introduced by https://github.com/AliceO2Group/O2Physics/pull/5648
> PWGHF: Fix mistakenly removed parameters

- Common/Core/RecoDecay.h
- PWGHF/TableProducer/candidateCreatorToXiPi.cxx
Check the production process of particles when doing the MC matching (both rec and gen) so that only particles coming from the decay are taken into account. This is optional and can be controlled using the parameter checkProcess, which is by default false (so the default behaviour is not changed wrt the current version of O2Physics).
In particular the check on the process is done using the function `getProcess()`, that returns `kPDecay` for particles produced in a decay this function. This check is implemented inside `getMatchedMcRec` and `isMatchedMcGen`. Inside these functions the checks on the number of daughters have been removed because they do not allow to properly take into account only the desiderd daughters.
> Common: RecoDecay: Consider only particles coming from decay process when matching

- PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
- PWGHF/TableProducer/trackIndexSkimCreator.cxx
- PWGHF/Utils/utilsAnalysis.h
This PR contains a utility function for the track's DCA selection. 
- The selection is added in the `candidateSelectorDplusToPiKPi.cxx`
- The utility function is applied in the `candidateSelectorDsToKKPi.cxx` and  `trackIndexSkimCreator.cxx`
> PWGHF: Adding utility function for single track cut on min/max dcaxy

- PWGCF/EbyEFluctuations/Tasks/CMakeLists.txt
- PWGCF/EbyEFluctuations/Tasks/FactorialMomentsTask.cxx
- PWGCF/EbyEFluctuations/Tasks/nfMomentsTask.cxx
- Code to run Factorial Moments Analysis
- In an initial shape rn
> PWGCF: EbyE Intermittency analysis

- PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
I modified the definition for the calculation of multiplicity from V0M to T0M and also added the track selection in the task.
> PWGHF: Implementation of mult definition T0M and adding track selection

- PWGDQ/TableProducer/tableMaker.cxx
We need to always enable the use of the geometry for muons also when not using the propagation. Indeed, global muons need not to be propagated, but still require the geometry for the recomputation of the pDCA
> [PWGDQ Always retrieve geometry in tableMaker

- EventFiltering/cefpTask.cxx
- EventFiltering/filterTables.h
- EventFiltering/selectBCRange.cxx
- Removed unused include of BasicCCDBManager.
- Removed unused variables (cfgTimingCut, mRunNumber, mEndOfITSramp).
- Removed initCCDB method as it was no longer being used.
- Cleaned up commented-out code related to unused functionality.
- Simplified the run method by removing unnecessary code.
- Improved readability and maintainability by eliminating dead code segments.
refactor: Update CEFP trigger and decision columns
Modified the struct centralEventFilterTask to use std::array<uint64_t, 2> for the outTrigger and outDecision vectors to store trigger and decision information separately for each decision bin. Updated the column declarations to split CEFP triggers and decisions into two groups: cefpTriggered0/1 and cefpSelected0/1.
Make it work
> refactor: Remove unused code and redundant method in centralEventFilterTask

- PWGEM/Dilepton/Utils/MCUtilities.h
- PWGEM/PhotonMeson/Core/CutsLibrary.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.h
- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
PWGEM/PhotonMeson: update for HF->ee MC
> PWGEM/PhotonMeson: update for HF->ee MC

- PWGLF/Tasks/Resonances/KshortKshort.cxx
…upper index policy I used for the ME background, but since in the event mixing tracks are coming from the different events, we do not need to exclude the (1,2) and (2,1) pairs in case of Ks Ks
> fixed the low entries in the ME background 

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramManager.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/dqEfficiency.cxx
Add the check if the MC Pdg of the mother is needed before filling it in FillTrackMC. 
Initialize the variable used as kFALSE in the histogram manager to avoid always entering the calculation of a variable which is actually not need in any histo.
Put the MCMotherPdg histo in a separate list of histograms compared to "track/mc".
Put symmetric cuts in TPCnSigma_loose cut as TOFnSigma_loose cut to be symmetric.
> FillTrackMC and loose TPC/TOF cuts

- PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx
PWGEM/PhotonMeson: implement pre-selection of e for speedup
> PWGEM/PhotonMeson: implement pre-selection of e for speedup

- PWGEM/PhotonMeson/Core/HistogramsLibrary.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzMuMuQCMC.cxx
- PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: reduce histogram bins for ee
PWGEM/PhotonMeson: add protection against TTCA
PWGEM/PhotonMeson: change histogram bins in mee
> PWGEM/PhotonMeson: reduce histogram bins for ee

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/TableProducer/CMakeLists.txt
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
- PWGCF/Femto3D/TableProducer/singleTrackSelectorExtra.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
In this commit we add an additional table with pile-up flags to the data model. Task "singleTrackSelectorExtra.cxx" just produces a dummy table with the flags and needed only for compatibility with the derived data produced earlier, since the analysis tasks now use this additional collision table.
We also implemented a momentum cut (to the table producer) starting from which we remove tracks that are out of stored TOF Nsigma range -- this would decrease the derived data size significantly.
The MC task is now uses cent. and pair kT binning (as the main Pair task).
The Pair task also now includes dEta(dPhi*) histograms -- we were asked to add them also to the data distributions at the PAG (before it was only in MC).
Could you please approve this commit? Thank you. …
> adding table with pileup flags and new analysis distributions

- PWGCF/FemtoDream/Core/femtoDreamObjectSelection.h
- PWGCF/FemtoDream/Core/femtoDreamSelection.h
So far the upper/lower bounds were not included in the selection. Hence, for example, if one sets the lower bound of ITS clusters to 5, only tracks with at least 6 clusters are selected.
> PWGCF: Fix in FemtoDream producer

- EventFiltering/PWGHF/HFFilterHelpers.h
> EventFiltering: Fix compilation warnings

- DPG/Tasks/AOTTrack/tagAndProbeDmesons.cxx
`implicit-fallthrough`
@fgrosa , I suppose that you want to check only the condition for the given `channel` and not continue to other checks if the condition is not satisfied, right?
> DPG: Fix compilation warnings

- PWGCF/MultiparticleCorrelations/Core/MuPa-MemberFunctions.h
`type-limits`
@abilandz I commented out lines checking condition which can never be true because of the unsigned type of the `fRandomSeed` member.
> PWGCF: Fix compilation warnings

- PWGDQ/Core/CutsLibrary.cxx
> PWGDQ: Fix compilation warnings

- PWGHF/D2H/Tasks/taskD0.cxx
The number of bins for Bkg and FD score are reduced from 100 to 50, which allows us to able to create smaller AnalysisResults.root that can be merged on a large dataset. @atavirag
> PWGHF: reducing number of bins for ML scores in D0 output ThnSparse

- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGHF/Tasks/taskMcEfficiencyToXiPi.cxx
Fix efficiency calculation taking into account the production process of the daughters
> PWGHF: fix task for efficiency calculation checking daughter production process

- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
Use fixed CPR for mixed event in track-v0 task.
> PWGCF: Update track-v0 in femtodream

- PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
Make that we can set pool bins in the Json file
> PWGHF: Config Pool bins in Json file

- PWGCF/DataModel/FemtoDerived.h
- PWGCF/FemtoDream/Core/femtoDreamEventHisto.h
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamDebugV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackV0.cxx
A new table is added containing MC truth information for collisions. It
can be linked to the reconstruction table via a new index table. The
procedure is similar to the previously implemented table for MC true
information for particles
New tables:
- FDMCCollisions: Contains MC truth information (for now only the number
of produced paricles in |eta| < 0.8
- FDMCCollLabels: Linkable with FDCollisions to access the
FDMCCollisions table
> [PWGCF - FemtoDream]: Including MC collision table

- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
Add pt-dependent DCAxy cut for tracks in pair track-track task.
> PWGCF: Update pair track-track task in femtodream

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I have added a new table in order to store the information on track dcaXY , dcaZ and nTPCcrossedRows in order to evaluate the systematic uncertainties on the tracking efficiency and the secondary particle contamination. Let me know for any comment.
Best regards,
Samuele
> PWGHF: Ds-h correlations, Adding DCA and nTPCcrossedRowa for tracking efficiency and selection systematics

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/TableProducer/tableMaker.cxx
- **processAmbiguousMuonOnly** removed since the maximum number of process function has been reached
- **processAssociatedMuonOnlyWithCovAndCent** added to study time-association in Pb-Pb collisions
- **dimuon** histograms changed to reduce the output size (redundant histograms removed)
> [PWGDQ] Fixing issue with table-maker process function and updating dimuon histograms

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/TableProducer/Resonances/LFResonanceInitializer.cxx
- PWGLF/Tasks/Resonances/k892analysis.cxx
It introduces a new table `ResoMCCollisions` to keep the MC event flags.
Resoinitializer now saves the event correction histogram `hMCEventIndices` when we run the MC process.
The analyser can get the event correction factor, such as trigger efficiency from this.
Similarly, the signal loss correction factor can be calculated.
> PWGLF: Include event correction

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
> PWGLF: change in derivedcascadeanalysis.cxx

- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorCascade.cxx
- PWGHF/TableProducer/candidateCreatorDstar.cxx
- PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx
This PR implements the selection on the generated PV z position. In order to avoid human mistakes, the same value used in the reconstructed part is retrieved by the workflow of the reconstructed part. Not yet implemented for the XiPi creator because no event selection is present for the XiPi creator for the reconstructed part (@ZFederica let me know if you want me to include it).
> PWGHF: add selection on generated PV z position in creators

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGEM/Dilepton/Tasks/MCtemplates.cxx
HistogramsLibrary:
Change group name from `mctruth` to `mctruth_track`, so the single track histograms are not called if `mctruth_pair` is required.
Rename: To distinguish between track and MC track variables.
Mass -> MassMC
Rapidity->RapidityMC 
MCtempaltes:
Separate MCTrackGen for tracks and pairs. Add boolean.
> PWGEM MCtemplates seperate MCgenerated histograms for tracks and pairs

- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
in this commit we adjust some PID cuts to have more flexibility in TPC Nsigma cuts + adjust binning in double track heists. Could you please approve it. Thank you.
@njacazio @sofiatomassini @ercolessi
> minor adjustments to the analysis tasks

- Common/Core/PID/TPCPIDResponse.h
- Common/DataModel/PIDResponse.h
- Common/TableProducer/PID/pidTPC.cxx
- Common/TableProducer/PID/pidTPCBase.h
- Common/TableProducer/PID/pidTPCFull.cxx
Original pull request for TuneOnData https://github.com/AliceO2Group/O2Physics/pull/4733 had diverged due to large conflicting changes made in https://github.com/AliceO2Group/O2Physics/pull/5563. This commit resolves the conflicts and re-implements the tuneondata option based on the new NN configurables (beta-gamma cutoff and per-species "useNetwork" flags).
> implementation of TuneOnData for MC in TPC PID

- PWGUD/Core/SGTrackSelector.h
- PWGUD/Tasks/sgD0Analyzer.cxx
- PWGUD/Tasks/sgFITAnalyzer.cxx
- PWGUD/Tasks/sgFourPiAnalyzer.cxx
- PWGUD/Tasks/sgSpectraAnalyzer.cxx
- PWGUD/Tasks/sgTwoPiAnalyzer.cxx
Fixed bug in sgSpectra Task,
Added histos in D0.
Moved SGTrackSelector.h to Core folder
> [PWGUD] SG Tasks updated

- PWGJE/TableProducer/jettaggerhf.cxx
- PWGJE/Tasks/jettaggerhfQA.cxx
TableProducer/jettaggerhf.cxx
- Add trackProbQA to estimate quality of resolution function
- Change default values of resolution function
- Change parameter name intuitively
Tasks/jettaggerhfQA.cxx
- Create option to select to fill histogram within DCAxy, z, xyz and track counting method due to avoid memory problem to make many histograms
Thank you very much in advance.
> Add trackProbQA and avoid memory problem as dividing histograms

- PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Fix the filling of histos in the case a condition on TOFbeta is included in the track cuts.
Fix possible remaining variables from previous tracks..
> Fix filling of cuts with TOFbeta conditions

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
@njacazio in this PR I introduce a couple of fixes w.r.t. your last modifications for `processMC`:
- the `process` function must have a `MCCollision` (w/o `s`) if we want the reconstructed collisions to be grouped with generated ones. In this way, `mcParticles` are already grouped 
- when counting the generated particles in reconstructed collisions, you were missing the acceptance criteria, which were introducing significant differences between the two efficiencies
> DPG: fix collision grouping with MC coll. and acceptance gen. particles.

- PWGLF/Tasks/Resonances/k892analysis.cxx
z vertex cut is applied in the resonance initializer but in the MC case, we don't apply due to find the vertex selection efficiency.
> PWGLF: Apply additional vertex z cut on MC case

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
-isClosePair for track-V0 and V0-V0 now checks for mixed events and then applies globalIndex for V0 daughters
-Task also applies globalIndex for V0 daughters in case of mixed events only
> PWGCF: FemtoUniverse -- applied globalIndex on V0 daughters for mixed events only

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
- PWGLF/TableProducer/Strangeness/cascademcbuilder.cxx
- PWGLF/TableProducer/Strangeness/cascademcfinder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzerobuilder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeromcbuilder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeromcfinder.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
@lhusova @romainschotter with this PR, we can generate an extra flag in the findable derived data that is able to tell us easily if each and every "findable" candidate was actually found correctly. The ratio of found/findable is therefore viable within a single derived dataset with all findable, adding extra debug capabilities as we can more easily and reliably calculate the combined global tracking + svertexing efficiency... 
I will still test this before declaring it ready to merge. The changes necessary for this were a bit more complicated than I originally expected...
> PWGLF: add found tag in findable exercise

- CODEOWNERS
Adding Jonghan Park (github username jpxrk) as codeowner of PWGHF, in quality of HFL PAG coordinator
> Updating PWGHF codeowners

- PWGHF/Tasks/taskMcValidation.cxx
- Add generated-level check for charm baryons and Ds->K0*K->KKpi
- Split reconstructed validation part into multiple process functions to allow running with less dependencies (default is HF index-skim-creator only)
@cterrevo @ZFederica @zhangbiao-phy @DelloStritto @stefanopolitano FYI
> PWGHF: Add charm-hadron channels to taskMcValidation + workflow improvements

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
- PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've changed the following things:
- getting the index of the daughter particle of the charm meson,
- pair cleaning,
- new function to wrap deltaPhi to 0-PI range,
- binning in the angular correlation histograms.
> PWGCF:FemtoUniverse - corrections in D0 analysis

- PWGHF/D2H/Tasks/taskDs.cxx
This PR fixes the rapidity type in its declarations. `double`  is used instead of `float` as this is the type returned by the functions used to evaluate the rapidity
> PWGHF: Fix rapidity declaration in Ds task

- Tutorials/src/eventMixing.cxx
- Tutorials/src/eventMixingValidation.cxx
The O2 documentation will be updated soon [after I make jekyll working on my current machine].
FYI @jgrosseo
> Add `getBin()` calls and example of counters to the mixing event tutorial.

- DPG/Tasks/AOTTrack/qaMatchEff.cxx
Remove some unnecessary configurables to ensure not exceeding the limits.
Locally tested, the [WARN] message about "no input" has disappeared.
> Remove some unnecessary configurables

- Common/Core/RecoDecay.h
Extends `RecoDecay` with calculations of kinematic quantities using pT, η, φ as input.
- Supported input:
- pT, η, φ variables,
- container with pT, η, φ elements (accessible via index),
- container with pT, η, φ, m elements (accessible via index).
- Quantities: px, py, pz, p, e, y, (pt, eta, phi)
- Utilities:
- `setVectorFromVariables`, `setVariablesFromVector` (for PtEtaPhi(M) containers),
- `pVector` returns `std::array` with px, py, pz elements
- Indexing of pT, η, φ, (m) elements in the PtEtaPhi(M) containers is arbitrary and is specified by template arguments.
- Default instance `RecoDecayPtEtaPhi` uses 0, 1, 2, (3).
- Change `class` to `struct` to remove unnecessary code.
> RecoDecay: Add PtEtaPhi-based calculations

- PWGUD/Tasks/CMakeLists.txt
- PWGUD/Tasks/exclusivePentaquark.cxx
- PWGUD/Tasks/exclusivePhiLeptons.cxx
- PWGUD/Tasks/exclusiveTwoProtons.cxx
p+pbar task:
- added pt distributions for all interesting invariant mass ranges
- added control plots for polarisation of events in the sidebands to assure the nature of the physical process
phi->ee:
- introduced an exclusive phi->ee channel for measurements with SG events
p+Jpsi resonances:
- added a fun task to look for pentaquarks candidates requiring a Jpsi and a proton in TOF
- to be analysed with SG events
> [PWGUD] task phi->ee, p+pbar, p+Jpsi resonances

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/tableReader.cxx
- PWGDQ/Tasks/tableReader_withAssoc.cxx
This flag allows for an alternative computation of the reference flow in the cumulants method. Using it, one can compute this reference flow by averaging only over collisions producing a particle of interest, here dileptons, eventually with specific kinematics. The goal is to compare this alternative way of computing the reference flow with the one computed by the dqFlow task which averages over all collisions.
> [PWGDQ] Adding flag for first dilepton of collisions in dileptonflow table

- DPG/Tasks/AOTTrack/qaMatchEff.cxx
- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
In candidateCreator for xic0 and Omegac0, add (optional) selection on generated particles for:
- TF borders
- ITS ROF borders
> PWGHF: add TF and ITSROF borders cut omegac0xic0 creator

- .github/workflows/mega-linter.yml
Getting the list of modified files has been fixed in MegaLinter so we don't need to merge the branch into master anymore to run MegaLinter.
Plus it fixes the current issue, where the formatting PR includes also missing commits from upstream, added by the merge.
> MegaLinter: Checkout the HEAD of the PR

- PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx
PWGEM/PhotonMeson: quick fix for a process function
> PWGEM/PhotonMeson: quick fix for a process function

- Scripts/find_dependencies.py
**Current version:**
```bash
[O2Physics/latest] ~ $> ~/alice/O2Physics/Scripts/find_dependencies.py -t v0
Table: v0
v0 <- ['o2-analysis-v0converter', 'o2-analysis-lf-lambdakzerofinder', 'o2-analysis-weak-decay-indices']
```
**New version:**
```bash
[O2Physics/latest] ~ $> ~/alice/O2Physics/Scripts/find_dependencies.py -t v0
Table: v0
No producers found
```
```bash
[O2Physics/latest] ~ $> ~/alice/O2Physics/Scripts/find_dependencies.py -t v0_001
Table: v0_001
v0_001 <- ['o2-analysis-lf-lambdakzerofinder', 'o2-analysis-weak-decay-indices']
```
```bash
[O2Physics/latest] ~ $> ~/alice/O2Physics/Scripts/find_dependencies.py -t v0_002
Table: v0_002
v0_002 <- ['o2-analysis-v0converter']
```
> Find dependencies: Distinguish table versions

- PWGHF/DataModel/DerivedTables.h
- PWGHF/DataModel/DerivedTablesStored.h
- PWGHF/TableProducer/derivedDataCreatorD0ToKPi.cxx
- PWGHF/TableProducer/derivedDataCreatorLcToPKPi.cxx
- PWGJE/Core/JetHFUtilities.h
Add derived tables for MC collision properties.
- Derived MC particles point to derived MC collisions.
- Derived MC collisions can point to derived reconstructed collisions if `fillMcCollId`:
- If `!fillMcCollId`:
- Reconstructed collision is stored if it has selected HF candidates.
- MC collision is stored if it has selected HF MC particles.
- If `fillMcCollId`:
- Reconstructed collision is stored if it has selected HF candidates or if its matched MC collision has selected HF MC particles.
- MC collision is stored if it has selected HF MC particles or if it is matched to a stored reconstructed collision.
- Re-organise and split data models for standard derived tables and stored derived tables for better maintenance.
FYI @nzardosh @qgp @DelloStritto
> PWGHF: Add MC collision tables in self-contained derived format

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/tableReader.cxx
Move the filling of the event planes in VarManager::FillEvent
@iarsene: please let me know if you find double filling. l 1154 is just the VarManager::FillEvent for me, where I did not find the filling of the event planes.
ps: there is two implementations of the calculations of the event plane. I choose the "Helper" already used in the VarManager, which has nevertheless also his own function.
> Fill event plane in VarManager

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/dqEfficiency.cxx
- PWGDQ/Tasks/tableReader.cxx
Add the diElectronsAll table.
There is the configurable "fConfigFlatTables" to choose whether to output the diElectronsAll table.
> PWGDQ: Add diElectronsAll table

- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
Add missing `continue` statement in xic0-omegac0 candidate creator (fix error)
> PWGHF: Fix missing continue statement in Xic0Omegac0

- PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* Exclusion of J/psi IVM histograms from J/psi peak cut for peak fitting.
> PWGUD: fix of IVM histograms

- PWGHF/CMakeLists.txt
Saves about 40 minutes of integrated CPU time.
> PWGHF: Exclude PWGHF/ALICE3 from compilation

- PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
- PWGLF/Tasks/Nuspex/QAHistTask.cxx
NucleiHistTask:
- removed effciency calculations for MC
- removed unnecessary code
- added discrimination for nuclei with Z >= 2
- added sel8 selection for MC
QAHistTask:
- added discrimination for nuclei with Z >= 2
- added sel8 selection
- streamlined the naming of histogram registries (like in NucleiEfficiencyTask)
> Update NucleiHistTask & QAHistTask

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
The fill function for ZDC now sets the energy values to -1 if they are negative, for more straight-forward cutting and histogramming. The original values are still in the table itself.
> [PWGDQ] Set negative ZDC energies to -1. Add cuts for Lambdac including DCAz.

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
Due to a bug the Run 2 trigger class was always larger than `-1`, this was preventing to run with `useSel8Trigger = false`.
> PWGHF: Fix trigger selection for Run 2

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/TableProducer/converters/CMakeLists.txt
- PWGLF/TableProducer/converters/strarawcentsconverter2v4.cxx
@romainschotter @lhusova @ChiaraDeMartin95 this adds the 'occupancy in time range' variable (see Igor's talk at the DPG [earlier today](https://indico.cern.ch/event/1417779/contributions/5963217/attachments/2862271/5009062/ITSTPC_tracking_performance_vs_occupancy_in_time_windows_2024_05_23_updated.pdf)) to the strangeness derived data format. It also provides an appropriate converter so that existing derived data continues to be usable.
> PWGLF: add occupancy in time range to str. der. data

- PWGUD/Tasks/exclusiveTwoProtons.cxx
- PWGUD/Tasks/exclusiveTwoProtonsSG.cxx
Found a bug in the way that the DCA logic is treating 2 TOF-track topology for pp events (most of the statistics derives from the 1 TOF+1 TPC topology instead)
> [PWGUD] Fix DCA logic for 2 TOF-track topology

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
@fgrosa @fcolamar @gluparel @scattaru @mmazzilli @deepathoms this should help for the analysis of Samuele.
I still want to add the same code for the case w/o grouping by `mcCollisions`, I'll add it tomorrow and then I'll open the PR
> DPG/PWGHF: monitor single-track efficiency from HF decays

- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx
- PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: quick fix to 6283
> PWGEM/PhotonMeson: quick fix to 6283

- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
Hi @ddobrigk :)
Would it be possible to add these changes to the cascadebuilder? They would allow to run the cascadebuilder with the KF without having to run the lambdakzerobuilder to produce the V0Datas tables. 
As far as I see, the aod::V0Datas subscriptions in the cascadePreselector processes are not necessary. I ran some tests locally to make sure and everything looks fine so far. Am I overlooking something or could we indeed remove those subscriptions?
> PWGLF: Remove V0Datas tables from cascadePreselector processes in the cascadebuilder

- PWGLF/TableProducer/Strangeness/lambdakzerobuilder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeromcfinder.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
@pbuehler @rolavick this will hopefully allow for studying the properties of Lambdas with no collision association; it by the way automatically includes a TOF delta-time compatibility check that should be enough for the time compatibility requirement. 
@romainschotter this includes a V0 type check + a first-order occupancy minimum/maximum boundary configurable so we can check the raw yield per event and how that changes with occupancy.
> PWGLF: provisions for UPC Lambdas, occupancy studies, v0 type checker

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I have noticed a problem in the removal of the Ds daughters from the correlation analysis at the kinematic level.
Previous version of the code:
RecoDecay::getDaughters(particle, &listDaughters, arrDaughDsPDG, 2);
if (listDaughters.size() == 3) {
for (auto iProng = 0; iProng < listDaughters.size(); ++iProng) {
auto daughI = mcParticles.rawIteratorAt(listDaughters[iProng]);
prongsId[iProng] = daughI.globalIndex();
}
}
// Ds Hadron correlation dedicated section
for (const auto& particleAssoc : mcParticles) {
if (particleAssoc.globalIndex() == prongsId[0] || particleAssoc.globalIndex() == prongsId[1] || particleAssoc.globalIndex() == prongsId[2]) {
continue;
}
Now:
RecoDecay::getDaughters(particle, &listDaughters, arrDaughDsPDG, 2);
int counterDaughters = 0;
if (listDaughters.size() …
> PWGHF: Ds-h correlation: Solving a bug with Ds daughters removal

- PWGDQ/Core/HistogramsLibrary.cxx
It seems that subGroupStr.Contains does not like big letters. Putting "mcmother" instead of "mcMother" solves the issue.
> Fix to get the MotherPDGCode histogram

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaEMCEMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaPCMDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaPCMPCM.cxx
PWGEM/PhotonMeson: separate pi0eta task into subsystems
> PWGEM/PhotonMeson: separate pi0eta task into subsystems

- DPG/Tasks/AOTTrack/CMakeLists.txt
- DPG/Tasks/AOTTrack/qaTrackSplitting.cxx
> [DPG] Add task for split tracks

- Common/TableProducer/multiplicityExtraTable.cxx
Adds a minimum FT0C threshold to keep data volume down when saving the BC table for cross-checks.
> Common: BC table reduction -> min threshold for saving

- PWGDQ/TableProducer/tableMakerMC.cxx
The two reasons are:
a. Otherwise it is not possible to skimm with primary electrons for example. The rejection factor is much too small including secondary electrons from conversion happening far away (TRD...)
b. Otherwise there is an inconsistency between the signals defined at the reconstruction level (no source checked) and for reconstructed tracks in the histograms..
> Check the source of the signal for skimming

- PWGUD/Tasks/exclusivePentaquark.cxx
- PWGUD/Tasks/exclusivePhiLeptons.cxx
- PWGUD/Tasks/sgExclusivePhi.cxx
Exclusive phi->KK:
- adding selections on the average cluster sizes in ITS 
- misidentified electrons are already relativistic -> small cluster size
Exclusive phi->ee:
- identified bug in the selection for the angles of the pair
- added study on the aperture of the angle of the pair (names could be improved though)
Pentaquark searches:
- relaxed global pT requirement on the tracks
- tightened a lot the pT requirement on the lepton tracks
- tightened the aperture of the Jpsi mass window to look for pentaquarks
> [PWGUD] Fix angle selection for exclusive phi->ee

- PWGDQ/TableProducer/tableMakerMC.cxx
Since the commit #4585 the eventExtended table changes 
from
bc::GlobalBC, bc::TriggerMask, timestamp::Timestamp, reducedevent::TriggerAlias, cent::CentRun2V0M,...
to:
bc::GlobalBC, evsel::Alias, evsel::Selection, timestamp::Timestamp, cent::CentRun2V0M,...
This changes was not ported to the tablemakerMC. This leads to wrong timestamp in the skimmed format (wrong place) and crash when trying to take the magnetic field object in the CDD for example.
> Fix eventExtended format

- PWGHF/Core/HfHelper.h
- PWGHF/D2H/Tasks/taskD0.cxx
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorCascade.cxx
- PWGHF/TableProducer/candidateCreatorDstar.cxx
- PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx
- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
Building on top of what done for the D*.
Closes #6051
> PWGHF: add B mother information to candidate creators

- PWGJE/Tasks/hffragmentationfunction.cxx
PWGJE: prompt/non-prompt D0 data column was added to MC tables.
If the candidate/particle is prompt a boolean `true` value is stored and `false` otherwise
Prompt/non-prompt information will be used for efficiency estimation and feed-down subtraction.
> PWGJE : addition of prompt/non-prompt data column to MC process function

- PWGEM/Dilepton/Utils/MCUtilities.h
- PWGEM/PhotonMeson/Core/EMEventCut.cxx
- PWGEM/PhotonMeson/Core/EMEventCut.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx
- PWGEM/PhotonMeson/TableProducer/converters/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/converters/emeventsconverter.cxx
- PWGEM/PhotonMeson/TableProducer/createEMEvent.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCEMCEMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCPCMDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCPCMPCM.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/dielectronQC.cxx
- PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/EventHistograms.h
- PWGEM/PhotonMeson/Utils/MCUtilities.h
- PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: add occupancy in data model
PWGEM/PhotonMeson: reduce derived MC data size
In order to reduce derived data size of MC, the generated meson pT spectra (pi0, eta) are stored as binned data. Further more, acceptance information is not stored in the derived data, as this requires mother-daughter relation, which is heavy. Instead, acceptance information (i.e. pT histogram for each decay channel) for |y| < 0.8 or 0.9 is stored in AnalysisResults.root, when the skimming task runs. By doing these things, finally, the data compression factor is 60 in EM. The requirement is 60.
> PWGEM/PhotonMeson: add occupancy in data model

- PWGHF/HFC/Tasks/taskCorrelationDMesonPairs.cxx
- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
This PR aims to update the way sparse axes are configured in taskCorrelationDMesonPairs.cxx so that they can be modified directly on Hyperloop
> PWGHF: update sparse axes in taskCorrelationDMesonPairs.cxx

- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
If `searchUpToQuark` is `true` in `getCharmHadronOrigin`, the vector with the indexes of B mothers could be empty
> PWGHF: fix vector access if searchUpToQuark=true

- Common/TableProducer/centralityTable.cxx
This PR adds some QA histograms to the task for debug (optional).
Note that this would add EventSelection as a dependency to the centrality table, which is however already required by the multiplicity table.
Cc: @njacazio
> Extend centrality QA

- PWGLF/TableProducer/Strangeness/lambdakzeropid.cxx
- PWGLF/Tasks/QC/findableStudy.cxx
@gianniliveraro this should fix the issues in the findable test you are doing. Can you rebase and try this out? 
@pbuehler @rolavick this should allow for the calculation of TOF delta-times between daughter prongs also for unassociated V0s using the existing `lambdakzeropid.cxx` task - to be checked. These delta-times should be close to zero and don't require a collision PV to be reco'ed.
> PWGLF: adapt V0 TOF PID to be used also for coll-unassoc V0s

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
in this commit we're adding a possibility to use variable bin widths in 3D DCA histograms (finer binning is not needed at the edges of the dist-s) in the MC pair task in order to reduce output size;
plus some other minor adjustments.
Could you please approve it. Thank you.
> adding variable bin widths for DCA histos; plus some minor adjustments

- DPG/Tasks/AOTTrack/CMakeLists.txt
- DPG/Tasks/AOTTrack/tagAndProbeDmesons.cxx
- PWGLF/Tasks/Nuspex/spectraTOF.cxx
This PR adds 2 features to the D-meson tag-and-probe task:
1) the possibility to select the signal only in MC with MC truth (the MC info of the tag is propagated to the probe workflow via a new table)
2) the possibility to apply ML models to select the tags more efficiently
In addition, it adds the same variables used for the D0 to the other channels.
@arossi81 be careful that after merging this PR, if you synchronise the wagons on hyperloop, they might be reset to the default values.
> DPG/AOT: add MC truth and ML application in D-meson tag-and-probe

- PWGLF/Tasks/Strangeness/strangeness_in_jets.cxx
I realized that using float for the vector components I had introduced a small quantization error that resulted in a non-zero rapidity shift between the jet axis and UE cone axis. Using double fixes the problem.
> fixed perpendicular cone calculation

- PWGHF/Tasks/CMakeLists.txt
- PWGHF/Tasks/taskCharmHadImpactPar.cxx
For the time being only D0 and D+ implemented, more channels can be added if wished
> PWGHF: add task to monitor charm-hadron dca resolution and remove obsolete task from compilation

- PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
D+ - h correlation task:
- efficiency evaluation
- efficiency correction to correl distribution
- QA histogram
- removing obsolete code
> PWGHF: D+h correlations  -  efficiency correction

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/MCSignalLibrary.cxx
Adding a cut using only electron PID from TPC with no tracking cuts.
> PWGEM: Add cut with only TPC electron PID, no tracking

- PWGDQ/Tasks/v0selector.cxx
HI Ionut and HI Daiki
I made some small modifications to the V0 selectors and made the selection cut configurable.     This is the suggestion from the TPC PID group since the selection purity from PbPb is quite low. we want to optimise the cuts.
Cheers
Xiaozhi
> make the V0 selector cofigrable

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add same event selection capabilities as in real data, ie:
- Add missing occupancy selections in MC
- Add extra event selections in MC
> Add occupancy selections (+ extra event selections) in MC

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
in this commit we add a new double track cut. Could you please approve it. Thank you.
> adding new 2trck cut

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/tableReader.cxx
Add the possibility to used the Q vector from the central framework to define the hash in the event mixing + the possibility to use the occupancy variable in the event selection in the eventreader.
> Add Qvector from CFW and occupancy in event mixing/selection

- Common/CCDB/EventSelectionParams.cxx
- Common/CCDB/EventSelectionParams.h
- Common/TableProducer/eventSelection.cxx
Occupancy variable in evSel now is weighted wrt time separation b/n given collision and other events. 
Also, several new occupancy-based selection bits are added.
> update of occupancy-based event selection

- PWGHF/TableProducer/candidateSelectorLc.cxx
Tagging @DelloStritto @gluparel @strogolo @saganatt @zhangbiao-phy @1994ra for their info.
With this, the Bayes PID dependency can be removed, if not used. Beware of the new `processNoBayesPid` (`true` by default) and `processBayesPid`
> PWGHF: candidateSelectorLc: templatize process to remove Bayes PID table, if not used.

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/dqFlow.cxx
Adding extra table to compute Q-vectors from ZDC tables. The table is joinable and filled together with the Q-vectors from central framework
> [PWGDQ ]Adding extra table to compute Q-vectors

- EventFiltering/cefpTask.cxx
The double counting has been introduced with the extension of the trigger mask to 128 bits
> Avoid double counting in the CEFP summary plot

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add Centrality Vs Occupancy histograms to study the evolution of the occupancy distribution with centrality in real and MC data
> [PWGLF] Add Centrality Vs Occupancy histograms

- PWGJE/Core/JetTaggingUtilities.h
- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/bjetTreeCreator.cxx
This is a code that create a TTree with the b-jet parameters, including the track and secondary vertices info. This TTree will be provide features for machine learning algorithm that will be used for b-jet tagging.
> PWGJE: Implementation of a tree creator for b-jets 

- PWGDQ/TableProducer/CMakeLists.txt
- PWGDQ/TableProducer/tableMaker.cxx
- PWGDQ/TableProducer/tableMaker_withAssoc.cxx
- Removal of all the process function for muons not using convariance matrix (the implementation is still kept commented in the code). This is done becasue we reached the limit of process functions and output tables produced and this prevent the running of the table-maker
- Addition of a flag to run the event selection for events triggered by the CEFP (zorro). This functionality is still under development and needs to be tested once the trigger mask info is loaded to the ccdb for all the periods.
> [PWGDQ] Fixing table-maker + adding zorro tag to skimmed data

- PWGJE/Tasks/bjetTreeCreator.cxx
I made a mistake in the last pull request. I removed the +1 from the jet index in the tables to test what happens, but I completely forgot to put back. Now fixed.
> PWGJE: fixing the jet index in the b-jet tables

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/cascademcbuilder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeromcbuilder.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
@romainschotter @lhusova still testing...
> PWGLF: mc core for all gen

- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
1) Fixed a fatal thrown by the DCAFitter due to very small covariances for some rare muon tracks
2) Fixed a run time error in the init() of tableMakeMC_withAssoc appearing due to checking for non-existing process function names
3) Included the mcDecision in the Dielectrons and Dimuons tables in dqEfficiency_withAssoc
> [PWG-DQ] Small bug fixes

- PWGHF/Core/HfHelper.h
- PWGHF/Core/SelectorCuts.h
- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
- PWGHF/TableProducer/candidateSelectorLc.cxx
- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
1. add possibility to cu on K-pi invariant mass
2. propagate the info in the tree creator and polarization task
3. add info about direct-reso. decay channel in tree creator and polarization task
> PWGHF: add info about K-pi pairs from Lc->pKpi decays, and add direct/reso. decay channel info

- PWGMM/UE/Tasks/lambdak0sflattenicity.cxx
I have applied Competing V0 Rejection on K0s, Lambda and AntiLambda, thus converting TH3F to TH2F.
> PWGMM: Applied Competing V0 Rejection Cuts

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
This PR excludes non-prompt charm hadrons in the MC that come directly from beauty diquarks. The reason is that they have a strange pT correlation (pT charm hadron > pT beauty mother), which creates issues when reweighting the pT shape to reproduce the one of the B hadron in productions with pT-hard bins (low pTB gets very large weight, but it ends up in creating few charm hadrons with high pT and a very large weight that have very large uncertainties).
A similar issue is observed with bottomonia decaying to a pair of charm hadrons. In this case the decay is genuine, but it produces the same issue in the reweighting, so we remove them as well.
> PWGHF: remove pathological non-prompt charm hadrons

- PWGHF/HFL/Tasks/taskSingleMuonReader.cxx
- PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
1. Add the quarkonium decay muon histograms in the muon source task
2. Add the MC-related process in the muon reader task
3. Add back the R_abs histogram in the muon reader task
4. Change the binning of DCA in the muon reader task
> PWGHF: Add quarkonium decay muon histograms in HFL muon source task

- Common/TableProducer/timestamp.cxx
This avoids issues with runs with missing EOR information, see for instance 551230 (before it gets fixed)
> Use BasicCCDBManger::getRunDuration for better stability

- Common/TableProducer/qVectorsTable.cxx
This PR is to support vector of Qvector (https://github.com/AliceO2Group/O2Physics/pull/6577). In the previous version, only aod::QvectorXXXXs (FT0C, etc) or aod::Qvectors were accepted by comparing string. But, aod::QvectorXXXXVecs were not supported, and q vectors were -999.
In addition, suppress warning about comparison between int and size_t.
> Common/TableProducer/qVectorTable.cxx: bug fix to support vector of Qvector

- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: apply min pt cut to trackiu. This is necessary to keep consistency as online tracking, recommended by a tracking expert.
> PWGEM/PhotonMeson: apply min pt cut to trackiu

- PWGUD/DataModel/UDTables.h
To fix the previous [version](https://github.com/AliceO2Group/O2Physics/pull/6647/files) where information about fwd tracks indices was added (causing unbound indices `ERROR: Index on O2fwdtrack but no tree found` and `ERROR: Index on O2mfttrack but no tree found` when tested on hyperloop)
> PWGUD: add index of fwd tracks to UDTables (fix)

- PWGUD/DataModel/UDTables.h
- PWGUD/TableProducer/DGCandProducer.cxx
- PWGUD/TableProducer/SGCandProducer.cxx
- PWGUD/TableProducer/UPCCandidateProducer.cxx
- changes in #6712 reverted  (not necessary)
- information about indices used for forward matching is now stored in a separate table instead of UDFwdTracksExtra  (which was initially introduced in #6647)
> PWGUD: store fwd matching indices in a separate table

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- Was removed for data already in a previous PR
- Not needed anymore since this cut is performed already based on the central event selection bits
> PWGEM/PhotonMeson: Remove uniqueColl requirement from MC task

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Allows the detailed study of the population of tracks (afterburner or global) in the V0 analysis
> [PWGLF] Separate afterburner tracks from global tracks

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- avoid unbound indices because of inconsistent table/index naming
> Fix index and table naming

- DPG/Tasks/AOTTrack/qaMatchEff.cxx
Based on the comments at the DPG AOT meeting on June 27, 2024, add the occupancy selection for the ITS-TPC matching efficiency analysis.
Local test passed.
> Support the occupancy cut for the ITS-TPC m.e.

- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- PWGEM/PhotonMeson/Utils/ClusterHistograms.h
- PWGLF/Tasks/Nuspex/nuclei_in_jets.cxx
- Moved QA histograms from general cut library to ClusterHistograms.h (analogous to GammaGamma task)
- Adjust QC task to only run one cutstring and rather be called via multiple subwagons
- Adjust configurables to be in line with those of the GammaGamma task
> PWGEM/PhotonMeson: Adjust emcalQC task for EM framework changes

- Common/TableProducer/eventSelection.cxx
@altsybee This fixes the `int-in-bool-context` warning introduced in https://github.com/AliceO2Group/O2Physics/pull/6548 and also fixes the unnecessary evaluation of the condition and assignment when the result is already known.
Please check carefully that the logic has been preserved.
> Common: Event selection: Fix compilation warning

- PWGJE/Tasks/jetHadronRecoil.cxx
A new process function for matching MC with event weights, in preparation for the full anchored MC production expected soon.
Also changed the x axis ranges on the resolution plots to match with the change to plotting vs truth pT on all 3 histograms.
> PWGJE: Adding framework ready for jet-jet MC

- PWGDQ/DataModel/ReducedInfoTables.h
The DECLARE_SOA_TABLE_FULL macro is not needed in these cases where the first two bindings are the same.
this is how the DECLARE_SOA_TABLE macro is defined:
#define DECLARE_SOA_TABLE(_Name_, _Origin_, _Description_, ...) \
DECLARE_SOA_TABLE_FULL(_Name_, #_Name_, _Origin_, _Description_, __VA_ARGS__);
I propose this change since the _FULL macro definition has some clash with the jet framework
discussed with @aalkin
> PWGDQ: Removing _Full macro for tables which is not needed

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- Yesterdays PR removed two dimensions from the minv-pt histogram, but two zeros were still included in the filling of the rotation histogram, leading to Hyperloop tests to fail
- Removed the additional fill arguments, this should fix the issue
> PWGEM/PhotonMeson: Fix wrong dimension when filling rotation histograms

- PWGHF/D2H/Macros/ML/config_training_DplusToPiKPi.yml
- PWGHF/D2H/Macros/ML/train_models.py
Hi @fcatalan92 !
@VDiBella found a missing line in the ML training config file (the `tree_name` line). I must have accidentally deleted it when I modifed the config file to make it "dummy" for the `D2H/Macros` folder.
I also take the opportunity to add an extra `try... except` safety by defining one dedicated to `hipe4ml_converter` (as it is currently mixed with the `hipe4ml` one).
> PWGHF: add missing line in ML training config file

- PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
Removing the kaon PID check for the hadron (mostly proton) in the two track cut section of the code
> PWGCF: FemtoUniverse -- Changes in the two track cuts for the h-Phi analysis

- Common/Tasks/qVectorsCorrection.cxx
- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/candidateCreatorCharmResoReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
This PR implements:
- the possibility to keep the charm reso candidates that have daughters that share a daughter track for debug purposes
- an extended set of monitor histograms
- the possibility to pair D* mesons with single tracks instead of V0s
- few fixes (normalisation table filled twice per collision, unneeded tables consumed)
@Luca610 please check that it looks good to you.
> PWGHF: update code for D resonances

- PWGEM/Dilepton/Core/EMEventCut.cxx
- PWGEM/Dilepton/Core/EMEventCut.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/TableProducer/associateMCinfoPhoton.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Utils/EventHistograms.h
- PWGEM/PhotonMeson/Utils/NMHistograms.h
- Add a cut that requires kTVXinEMC and one for the hardware triggers in EMEventCut
- Add two columns for these cuts in hCollisionCounter
- Move "accepted" filling from 10 to 12
> PWGEM/PhotonMeson: Add EMC readout and trigger event cut

- PWGEM/Dilepton/Tasks/CMakeLists.txt
fixing CMake file (lmee-hf-cocktail was not included as dpl_worklfow, so it was not available on Hyperloop)
> PWGEM: properly add HF Cocktail task

- PWGCF/TwoParticleCorrelations/Tasks/lambdaR2Correlation.cxx
Some major changes made in this PR are as follows, 
1. Replaced the pseudo-rapidity and rapidity column in table producer task with only one variable based on type of analysis.
2. Added the lambda selection in the table producer task itself.
3. Added analyzeSingles and analyzePairs method in the correlation task.
Rest of the changes can be inferred from the code itself.
> PWGCF: Update lambdaR2Correlation.cxx

- PWGDQ/Tasks/tableReader.cxx
Set collisionId to zero by default to enable the use of processVnDecayToMuMuSkimmedWithWeights.
> Setting the collisionId to zero by default

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
- change all bool columns to int8_t
- reorder template-argument declaration in template functions
- add column to keep track of real Lc->pKpi reconstructed signal
- enable table filling only w/o grouping by mcCollision, to avoid memory leaks in case of 3-prong candidates (not only background, but also signal) that have reassociated daughters, for which the particles do not belong to the current mcCollisions. For the signal, these are cases recovered by the track-to-collision-associator, but with mcCollision grouping  in these cases a memory leak happens when retrieving the daughter-particle mother, because of the grouping of the particles table.
> PWGHF: fix filling of Lc->pKpi background table filling in polarization analysis.

- Scripts/find_dependencies.py
Sanitise JSON parsing for occurrences of non-Unicode characters in incorrect default values of `Configurable<std::vector<std::string>>` members (see https://github.com/AliceO2Group/AliceO2/pull/13252#issuecomment-2220091023).
> Dependency finder: Add protection against non-Unicode characters in JSON

- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
- PWGDQ/TableProducer/tableMaker_withAssoc.cxx
- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
- Adding checks in dqEfficiency to make sure considered particle has an associated mcparticle
- Adding refit option for global muons in tableMakerMC
- removing protection on global muon covariance in FillPairVertexing, this is fixed when using the option "UseAbsDCA" in the configuration of the DCAFitter
> [PWGDQ] Fixes in dqEfficiency_withassoc and adding muon refit in tableMakerMC

- PWGDQ/TableProducer/tableMaker.cxx
- PWGDQ/TableProducer/tableMaker_withAssoc.cxx
Adding configurable for ccdb path for zorro
> [PWGDQ] Adding configurable for ccdb path for zorro

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/TableProducer/associateMCinfoPhoton.cxx
- Ask for absolute value of rapidity when filling generated histogram
- Lost half of generated particles before
> PWGEM/PhotonMeson: Fix rapidity bug of generated particles

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Fixing a bug in fillMCParticle in femtoUniverseProducer to check if motherparticlesMC is empty or not before accesing its first element.
> PWGCF: Fix bug in fillMCParticle, check if motherparticlesMC is empty

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
Update of the D+-h correlation workflow, based on the developments of Ds-h correlations (by @scattaru) .
It includes code for the evaluation of:
- Secondary particle contamination
- Monte Carlo Closure test
- Include ML scores (Bkg, Prompt)
- Variations of sideband definition
> PWGHF: DhCorr task update with ML option

- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Utils/MCUtilities.h
PWGEM/Dilepton : improve HFee selection
> PWGEM/Dilepton : improve HFee selection

- Common/TableProducer/Converters/CMakeLists.txt
- Common/TableProducer/Converters/mcCollisionConverter.cxx
This change follows O2 [#13287](https://github.com/AliceO2Group/AliceO2/pull/13287) and adds a MC collision converter that fills a dummy EP angle for MC collisions. Created as draft for now.
> Common: add MC Collision converter

- PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx
Take out separation in different pair origins (Be_Be, BCe_Be, etc...) for HF cocktail for the moment. This was creating problems with the combinatorial background where not everything was correctly include. Only one full ULS and one LS histogram now. If needed in the future, one has to think how to properly separate into different pair types.
> PWGEM: fix HF cocktail task

- PWGEM/Dilepton/Utils/MomentumSmearer.h
The smearing task was crashing with a seg fault when reading the files from ccdb. Should be ok now for both options (local file and from ccdb).
> PWGEM: fix seg fault in MomentumSmearer

- PWGDQ/Tasks/tableReader_withAssoc.cxx
Adding process function for SameSideMixing where only tracks are used. No muon pairing.
Required to run on skimmed data sets which have no muon tables.
> [PWGDQ] add process function for SameSideMixing  Barrel only

- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
Delete one fillQA_base call in FemtoUniverseParticleHisto.h so it doesn't fill basic histos (pT, eta ...) twice for the same particle.
> PWGCF: Delete one fillQA_base call in FemtoUniverseParticleHisto.h

- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/DimuonCut.h
- PWGEM/Dilepton/Core/EMEventCut.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/CMakeLists.txt
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/Dilepton/Tasks/dielectronQC.cxx
- PWGEM/Dilepton/Tasks/dielectronQCMC.cxx
- PWGEM/Dilepton/Tasks/dimuonQCMC.cxx
- PWGEM/Dilepton/Tasks/singleElectronQCMC.cxx
PWGEM/Dilepton: fix dimuonQCMC
> PWGEM/Dilepton: fix dimuonQCMC

- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorCascade.cxx
- PWGHF/TableProducer/candidateCreatorDstar.cxx
- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
This PR removes the dependence on the centrality table for process functions w/o centrality cut
> PWGHF: removing dependence on centrality table for process function w/o centrality cut 

- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/Dilepton/Tasks/dielectronQC.cxx
- PWGEM/Dilepton/Tasks/dimuonQC.cxx
- PWGEM/Dilepton/Utils/EventHistograms.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
- PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/Dilepton: add q vector for 4th harmonics
> PWGEM/Dilepton: add q vector for 4th harmonics

- PWGEM/Dilepton/Tasks/CMakeLists.txt
- PWGEM/Dilepton/Tasks/dielectronQC.cxx
- PWGEM/Dilepton/Tasks/dielectronQCMC.cxx
- PWGEM/Dilepton/Tasks/dimuonQC.cxx
- PWGEM/Dilepton/Tasks/dimuonQCMC.cxx
- PWGEM/Dilepton/Tasks/singleElectronQC.cxx
- PWGEM/Dilepton/Tasks/singleElectronQCMC.cxx
- PWGEM/Dilepton/Tasks/singleMuonQC.cxx
- PWGEM/Dilepton/Tasks/singleMuonQCMC.cxx
PWGEM/Dilepton: add single electron QA task
> PWGEM/Dilepton: add single electron QA task

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
This PR adds the possibility to store the information needed for the tracking systematic uncertainty.
> PWGHF: Add possibility to evaluate tracking sys unc

- PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
In this pr I add the option to fill the DCA THnSparse according to pdgcode in MCProcess. It's possible choose to fill both Matter/Antimatter or only one of them. 
I add also the pt correction for He3/4 in Tof Mass
> [PWGLF]: Fill DCA THnSparse with pdgcode in MCProcess, add pt correction for He tof Mass

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorCascade.cxx
- PWGHF/TableProducer/candidateCreatorDstar.cxx
- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
- PWGHF/Tasks/taskMcValidation.cxx
This PR optimizes the logic for rejecting the generated candidates from reject events and removes unnecessary configs from the mc-validation task
> PWGHF: optimise cand. creator logic

- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
The 2023 pp data does not have centrality calibration (at least for some of the runs) thus the code must be updated to be able to run without centrality (just a new process added).
> Update to run analysis on data without centrality info

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/CMakeLists.txt
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/PhotonMeson/TableProducer/CMakeLists.txt
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/Dilepton: update analysis tasks
> PWGEM/Dilepton: update analysis tasks

- Common/TableProducer/qVectorsTable.cxx
As commented by @ddobrigk , https://github.com/AliceO2Group/O2Physics/pull/7023
It is convenient to make max. centrality configurable.
> Common/TableProducer/qVectorsTable.cxx: make max. cent. configurable

- .github/workflows/mega-linter.yml
MegaLinter does not create an automatic formatting PR if linters have found errors. The reported error messages are referring to lines in formatted files which can make it difficult to locate the corresponding lines in the committed files. See https://github.com/oxsecurity/megalinter/issues/3399 Formatted files can be uploaded in artifacts, which gives the PR author the possibility to see which lines the linters complain about.
> MegaLinter: Add missing step for artifact upload

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/associateMCinfoPhoton.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaEMCEMC.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCEMCEMC.cxx
- PWGEM/PhotonMeson/Utils/ClusterHistograms.h
- Remove columns from skimmedCluster table that are not needed for analysis to reduce size of derived data
- Remove index to collision table to avoid unbound indices
- Absorb matched tracks in cluster table
- Remove dedicated matched track arguments from GammaGamma task
> PWGEM/PhotonMeson: Reduce size of derived skimmed photon AO2Ds

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
> Check for the tertiary tracks 

- Common/Core/RecoDecay.h
This PR adds a check in `RecoDecay::getCharmHadronOrigin` that returns immediately if a parton is found as first mother in case of `searchUpToQuark == false`. In fact, no beauty hadron can decay to a parton, so if a parton is found as mother it means that the charm hadron doesn't come from a beauty-hadron decay. If it comes from a beauty-hadron decays in fact, the function will return before finding the first parton mother.
This is very important for the analysis of Pb-Pb MCs, since the analysis code is very slow otherwise.
> Common/Core: add check in getCharmHadronOrigin to reject in case of first mother parton

- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackTrack.cxx
- PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackV0.cxx
This PR addresses two fixes
- Remove filters used in pair-track-V0 task. When using filters, we encountered problems with applying deta-dphi cut. Applying selections of V0 and tracks separately with partitions has fixed the issue. 
- Use the new feature of configurable groups by declaring the prefix only once (in track-track and track-v0 task)
> PWGCF: Fix in FemtoDream

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I have modified the processes for evaluating both the candidate and associated particle efficiencies in order to consider at the kinematic level only those collisions which are reconstructed with the same selections applied on data. 
Let me know for any comments,
Cheers,
Samuele
> PWGHF: Ds-h correlation, effciency processes modified

- PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
Modifications to the D+ - h correlation task:
--> Add possibility for prompt, feed-Down, and tracking  efficiency to be taken from ccdb
--> Fix to mcrec level
> PWGHF: DpHCorr, efficiency from ccdb

- PWGHF/HFL/Tasks/CMakeLists.txt
- PWGHF/HFL/Tasks/taskSingleMuonReaderAssoc.cxx
Create a new muon-reader task for the dq-table-maker-(mc)-with-association which applied the new refit for global muons
> PWGHF: Add corresponding muon reader for table-maker-association in HFL

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
By Mistake added the` hPtGenerated ` in the efficiency plot for the radius as I've checked it locally so updated it with adding `hPtRadiusGenerated`
> [DPG] Fix filled efficiency

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
- adding pT histograms for MC particles (MC origin) in femtoUniverseEfficiencyBase.cxx
- changing processV0antiV0 to processV0V0 and checking if particle is V0 or antiV0 with PDG code
- adding charge cuts
- adding z vertex cut for MC truth collisions in Producer
> PWGCF: Add pT histograms for MC particles

- PWGDQ/Core/VarManager.h
Apparently recently reintroduced. Required by ROOT 6.32.XX
> One more fix to missing std::

- PWGCF/TableProducer/filterCorrelations.cxx
- PWGHF/D2H/Tasks/CMakeLists.txt
- PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR adds the HF event selections in the process function to compute the EP resolution in HF flow analyses. It also adds the `TPCtot` to the list of subsystems.
> PWGHF: Adding HF event selection in resolution process function for flow analyses

- PWGDQ/Core/CutsLibrary.cxx
Adding setting of cut variations.
> [PWGEM]: Add CutSetting with 30 cut variations

- Tools/PIDML/KaonPidTask.cxx
- Tools/PIDML/README.md
- Tools/PIDML/pidOnnxInterface.h
- Tools/PIDML/pidOnnxModel.h
- Tools/PIDML/qaPidML.cxx
- Tools/PIDML/simpleApplyPidOnnxInterface.cxx
- Tools/PIDML/simpleApplyPidOnnxModel.cxx
* remove detector count setting and reorder network arguments (with NaNs if detector not available)
* update README.md
* markdownlint changes
> PIDML: evaluate FSE + self-attention network

- PWGLF/Utils/collisionCuts.h
`trackOccupancyInTimeRange_noCut` histogram has to be filled only in run3 case.
> PWGLF: Prevent crush of collisicon cut in run2 case

- DPG/Tasks/AOTTrack/tagAndProbeDmesons.cxx
- move the `ConfigurableAxis` outside the `init`, otherwise they are not seen as configurable
- add `VARIABLE_WIDTH` at the beginning for those supposed to define bins of different widths by default
> DPG/AOTTracks: fix ConfigurableAxis.

- Common/DataModel/Qvectors.h
- Common/TableProducer/qVectorsTable.cxx
- Common/Tasks/qVectorsCorrection.cxx
New labeling added for the Q-vector tables, with backwards compatibility with the old labeling convetion.
Internal variables have been changed directly.
> (QVecDev) Added tables with new labeling

- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
Added the requirement of isGlobalTrackWoDCA for track selection in the efficiency process which was missing.
Cheers,
Samuele
> PWGHF: Ds-h correl, Adding isGlobalTrack requirement

- PWGUD/Tasks/CMakeLists.txt
- PWGUD/Tasks/eventByevent.cxx
A  new task to study pions candidates event-by-event using SG derive data by producing a reduced tree. The CMakeList.cxx task is updated accordingly.
> PWGUD: add eventByevent.cxx task

- PWGJE/Tasks/emcalPi0EnergyScaleCalib.cxx
This small update in emcalPi0EnergyScaleCalib.cxx allows to use different cluster definitions
> PWGJE: Update emcalPi0EnergyScaleCalib.cxx

- Common/TableProducer/qVectorsTable.cxx
Automatic Q-vector detection for Q-vectors used in the analysis depends on "useDetector" map. This map is now updated to account for the relabeling of the Q-vectors.
> (QVecDev) Automatic Q-vector detection updated

- PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
This commit adds the usage of collision labels to the non-prompt cascade
task in the ALICE PWGLF analysis. The changes ensure that the correct
collision information is used when processing the Monte Carlo
information, improving the accuracy of the analysis.
The key changes include:
- Accessing the collision label information from the `aod::McCollisionLabels`
table and associating it with the cascade candidates.
- Updating the `NPCTableMC` function to use the collision label information
instead of the `collisionID` field.
- Modifying the `processTrackedCascadesMC` function to include the
`aod::McCollisionLabels` table as an input.
These changes help to enhance the reliability and correctness of the
non-prompt cascade analysis in the ALICE PWGLF framework.
> feat: Add collision labels to non-prompt cascade task

- EventFiltering/Zorro.cxx
- EventFiltering/Zorro.h
The changes add a new method `getTriggerOfInterestResults` to the `Zorro` class. This method returns a vector of boolean values indicating which Triggers of Interest (TOIs) were selected in the last run of the `isSelected` method. This functionality is useful for providing the results of the TOI selection to the users.
> feat(EventFiltering/Zorro): Add getTriggerOfInterestResults method

- PWGCF/FemtoUniverse/Core/FemtoUniverseEventHisto.h
- PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
- add a check if V0 are identical and use CombinationsStrictlyUpperIndexPolicy for identical and CombinationsFullIndexPolicy for non identical in femtoUniversePairTaskTrackV0Extended.cxx
Additionally:
- change configurable description in femtoUniverseEfficiencyBase.cxx to simplify setting them,
- change binning of one histogram in FemtoUniverseEventHisto.h to cover larger range
> PWGCF: Change combinations policy for non identical V0s in V0 task

- PWGDQ/Core/CutsLibrary.cxx
- PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
- PWGEM/Dilepton/Tasks/smearing.cxx
Add cut setting for resolution maps
rename histogram axis in Efficiency task
> [PWGEM]: add cut for resolutions, typo tixes

- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
This PR introduces some modifications to the charm resonances data creator to reconstruct on-the-fly V0s daughters to be paired with D mesons, in order to reduce the memory consumption of the data creation workflow.
> PWGHF: Developements on Charm Resonances data creator

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGJE/Tasks/fulljetspectrapp.cxx
In this PR, I have updated the EMCAL event selection for the full jet finder processes functions. Now the fulljet finder at the DATA and MCD (also for the MCD to MCP matching) should only see those events that are readout by the EMCAL. For clarity, I have added more bin labels in the event histograms to clearly distinguish among the selected events in each process functions.
> Updated EMCAL event selection for Full Jet Finders

- PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
In femtoUniverseEfficiencyBase.cxx I added ConfMomPion configurable  to set momentum treshold for TOF use in PID for pions. I also moved more configurables concerning both tracks to ConfBothTracks configurable group.
> PWGCF: Add configurable for momentum treshold for TOF use in PID for pions

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
- recent commit on fixing V0-V0 Combinations Policy duplicated same block of code twice. I used lambda to avoid that.
> PWGCF: FemtoUniverse track-V0 task -- to avoid duplication

- EventFiltering/Zorro.cxx
- EventFiltering/Zorro.h
Add a new method `getTriggerOfInterestResults` that fetches the data for a given
bunch crossing global ID and tolerance, and returns the vector of boolean
results indicating whether each trigger of interest is satisfied. This is a
convenience method that combines the existing `fetch` and
`getTriggerOfInterestResults` methods.
Also add a new method `isNotSelectedByAny` that returns whether within a given tolerance a bunch
crossing global ID was not selected by any trigger.
This is a useful utility method for selecting parasitic MB events
> feat: add method to get trigger of interest results

- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/CMakeLists.txt
- PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/Dilepton: add a skimming task for EoI
> PWGEM/Dilepton: add a skimming task for EoI

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/Tasks/CMakeLists.txt
- PWGEM/Dilepton/Tasks/vpPairQC.cxx
- PWGEM/Dilepton/Tasks/vpPairQCMC.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/Dilepton: add a QC task for virtual photon in low mass
> PWGEM/Dilepton: add a QC task for virtual photon in low mass

- PWGHF/D2H/Tasks/taskD0.cxx
Remove BDT score axis in the THnSparse if ML is not applied, set MC gen output THnSparse as default.
> PWGHF: add output THnSparse for non-ML D0 analysis

- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
- PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaKa.cxx
- PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaPi.cxx
- PWGHF/TableProducer/candidateSelectorToXiPi.cxx
- Fix cast error showing up at running time in the Xic0Omegac0 candidate creator
- Fix abs value after having changed getter for LF daughter tracks in previous PR (https://github.com/AliceO2Group/O2Physics/pull/7332/files)
> PWGHF: fix cast error Xic0Omegac0Creator

- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
- EventFiltering/filterTables.h
- PWGJE/Tasks/phiInJets.cxx
@zhangbiao-phy @mpuccio this PR adds
- 4 triggers for HF for single charm hadrons for the normalisation of more complex triggers ("inclusive" or "non-prompt enhanced")
- the possibility to apply manually downscaling factors for standalone tests
> EventFiltering: add normalisation triggers for HF and possibility to apply manual downscaling

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Producer: I've updated the information, which are saved for D0/D0bar daughters. I declared additional flag to mark if the daughter is from either D0 or D0bar.
Task: I've added the QA histograms for D0/D0bar daughters and hadrons. I added the possibility to calculated the angular correlations with: only D0s, only D0bars, D0 and D0bar mesons (passing one mass hypothesis) and all D0 and D0bar candidates (passing both mass hypothesis).
> PWGCF:FemtoUniverse - D0 analysis update

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/Converters/v0coresconverter2.cxx
- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
- PWGLF/TableProducer/Strangeness/cascademcbuilder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeromcbuilder.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Fix derived data production to deal with the decoupling between V0Cores and V0MCCores + adapt analysis task 
- Enable all event selections in MC 
- Add histograms to estimate event splitting, event loss and signal loss
- Add option to access casc. mom. info at prim. vtx (@ddobrigk)
- Remove obsolete event selections related to occupancy
> [PWGLF] Fix derived data production + adapt analysis task

- PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
- PWGHF/TableProducer/candidateSelectorDstarToD0Pi.cxx
- PWGHF/Utils/utilsAnalysis.h
This PR:
- fixes the pt-differential D0 mass cut in the D0 <- D*+ (only applied for D*+ and not D*-, as a function of D* pT instead of D0 pT)
- splits up the configurables for 2-prongs and 3-prongs to avoid the confusion created by configurables that do not have any effect for given selectors 
Auto-approving since needed for HP performance plots.
> PWGHF: factorise 2 and 3 prong configurables, fix bug in D0 <-D*mass cut

- ALICE3/Core/CMakeLists.txt
- ALICE3/Core/DetLayer.h
- ALICE3/Core/FastTracker.cxx
- ALICE3/Core/FastTracker.h
- ALICE3/Core/FastTrackerLinkDef.h
- ALICE3/TableProducer/OTF/CMakeLists.txt
- ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
@jesgum 
This adds the `FastTracker` utility capable of flexibly pseudo-tracking secondary particles at any position and with any momentum after decay. Still a lot to be developed, debugged and tested, including material (MS/e-loss) effects - more to follow but ready for a first test drive.
> ALICE 3: add FastTracker

- PWGHF/D2H/Tasks/taskDs.cxx
This PR reduces the amount of repeated code in the Ds Task. This facilitates future modifications and reduces the possibility to introduce bugs in the code
- The code in the different process functions has been moved to the `runMcAnalysisPerCollision` and `runDataAnalysisPerCollision` functions, and the partition for the candidates per collision is now passed as an argument to these functions
- The `hasDsMlInfo` concept is now added to automatically infer if the ML table is available, so that this information is not required to be "transported" across the different functions as a template argument. Two `fillSparse` functions have been added to fill the mass sparse, and differ on the requirements on the ML information
> PWGHF: Reduce code repetitions in Ds Task

- ALICE3/Core/DetLayer.h
- ALICE3/Core/FastTracker.cxx
- ALICE3/Core/FastTracker.h
- ALICE3/DataModel/OTFMulticharm.h
- ALICE3/DataModel/tracksAlice3.h
- ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
- ALICE3/TableProducer/alice3-multicharm.cxx
> ALICE 3: tracksExtra with silicon/TPC point counters

- PWGLF/Tasks/Nuspex/AngularCorrelationsInJets.cxx
moved configurables for filter back into main struct, added NaN guards for Phi_0_2pi
> PWGLF: fixes for AngularCorrelationsInJets.cxx

- PWGJE/Tasks/jetfinderQA.cxx
Due to the difference between event selections in Data and MC currently, only TVX-selected true jets seem to make the difference when unfolding Data and MC (response matrix: selMC -> kIsTVXtriggered != sel8 -> kIsTVXtriggered).
> PWGJE: restrict true jets to evnet selected level as well as reco jets

- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
With this PR the possibility of adding a veto on candidates whose mass falls in the signal region of D+ mesons for the PiKPi mass hypothesis is implemented. 
This should reduce the amount of correlated background from D+->PiKPi decays in the analyses of Ds->KKPi
> PWGHF: Add veto for D+->PiKPi correlated background in Ds Task

- PWGJE/Tasks/bjetTaggingML.cxx
- PWGJE/Tasks/bjetTreeCreator.cxx
A cut on the pT hard has been added to reject jets with pT much larger pthard. This removes the outliers from the distribution. Copied from jetfinderQA.cxx
> [PWGJE] Adding a pThard cut to reject outliers

- PWGDQ/Core/MCProng.cxx
- PWGDQ/Core/MCSignal.cxx
- PWGDQ/Core/MCSignal.h
- PWGDQ/Core/MCSignalLibrary.cxx
- PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
These are some changes to add the option excluding signals that share a common ancestor.
This is needed to differ between electron pairs coming from same ancestor (e.g. B->De->ee, same Mother and Grandmother)
and pair which have not the same ancestor relation (pair from B->D->e and bar{B}->e)
If the extra boolean `fExcludeCommonAncestor`  is true it rejects the MC signal if the ancestors are equal and accepts them if the boolean is false.
Since this is a change concerning more analysers I would like to ask @iarsene to have a look.
Those changes are required for the HP conference and thus merging this in the next days would be very nice.
> [PWGDQ] add option to exclude MC signal which share common ancestor

- PWGLF/DataModel/LFStrangenessTables.h
Fix cosPA calculation when using the cascade momentum at the prim. vtx (useCascadeMomentumAtPrimVtx = on), in order to always the cosPA computed using the decay daughters momenta
> Fix cosPA calculation

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- this process function only provides generated MC data and can be used for model comparison
@basiach @alicja-pp @mm1707
> PWGCF: FemtoUniverse track-V0 task -- added a process function to provide MC Gen for model comparisons

- ALICE3/TableProducer/alice3-multicharm.cxx
@jesgum this adds minimal selections for us to be able to do Pb-Pb with zero MC requirements - crucially, a XiC mass window requirement was still missing. I've also added a flag that disables the filling of `MCharmCores` so as to not use memory excessively when not producing derived data and changed the key output histos to be THxDs instead of THxFs to accommodate giant data samples properly (the generation is still extremely fast).
> ALICE 3: minimal sels for no MC assoc added

- PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
Update HfCandLcFullPs table in treeCreatorLcToPKPi.cxx
- Remove `McCollisionId` and `McParticleId` in HfCandLcFullPs to account for the Unbound indices problem.
> PWGHF: Update LcToPKPi tree creator

- Common/DataModel/Multiplicity.h
- Common/TableProducer/multiplicityExtraTable.cxx
- Common/TableProducer/multiplicityTable.cxx
n.b. touches only the extra multiplicity table, main mult table unchanged
> Common: add bc2mult / mult2bc maps

- PWGJE/TableProducer/secondaryVertexReconstruction.cxx
The track tuner is causing some the covariant matrix to be a bit messed up leading the DCAFitter to crash. I added a try catch block in order to catch the error thrown by the DCAFitter.
> [PWGJE] Adding a try catch to the SV reconstruction task

- PWGHF/TableProducer/candidateSelectorD0.cxx
Follow-up of PR #7556, correcting for missing header in the candidate Selector D0
> PWGHF: selectorD0, missing include

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
This PR adds:
- the possibility to build Lc->pK0S candidates without vertex reconstruction
- the possibility to apply a cut on the pK0S mass window
- repropagates to PV the reassociated tracks for the proton bachelor 
@skundu692 for info
> PWGHF: improve pK0S channel in track index skim creator

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/tableReader_withAssoc.cxx
Adding recalculation of pair values like DCA based on propagated tracks when using Track to Collision association.
@iarsene You can have a second look on this.
> [PWGDQ] TtCA, adding propagation of track to collisions on pair level

- PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
- PWGDQ/TableProducer/tableMaker_withAssoc.cxx
- Implementing Muon and Barrel processes for skimmed data in tableMaker_withAssoc, allowing to use Zorro instead of dq-filter
- Fixing the logic to call skimMuons: if one does not subscribe to the MFT table, normal skimming. If one subsribes to MFT table, allows to refit the global muon tracks.
- Rejecting global muon tracks for which the standalone Muon is outside a given acceptance
- Reinitializing the "trackTempFilterMap" flag at each iteration of muonAssoc, otherwise all muons are skimmed after the first iteration
> [PWGDQ] Implementing processes for skimmed data in tableMaker_withAssoc and bug fixes

- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: quick fix after #7491
This is a quick fix for histograms and XYZ component in derived data of V0 legs.
> PWGEM/PhotonMeson: quick fix after #7491

- PWGJE/Tasks/jetHadronRecoil.cxx
fix z vertex selection for particle level analysis - old version only selects events with zvtx > 10 cm, now fixed to select events with abs(zvtx) < 10 cm 
also add histogram to plot z vertex position
> fix and plot z vertex selection

- PWGHF/TableProducer/trackIndexSkimCreator.cxx
This PR updates the pK0S channel in the track-index skim creator, by removing obsolete / not working cuts and using the momenta of the V0 daughters evaluated in the proper point (V0 decay vertex)
> PWGHF: Update p-K0S finding in trackIndexSkimCreator

- PWGDQ/Core/VarManager.h
Add flow resolution factors in `FillEvent` in order to access resolution histograms from `analysis-event-selection` in `table-reader`
> [PWGDQ] Add flow resolution factors at event filling level

- PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: simplify 3d analysis
> PWGEM/Dilepton: simplify 3d analysis

- Common/DataModel/Multiplicity.h
- Common/TableProducer/multiplicityTable.cxx
It seems this also requires to have an `s` at the end of the table that is being indexed, which is extremely unfortunate - and has required that I change the name of the table as well. `using` has been used to avoid backwards incompatibility.
> Common: interlink MC extras with reco coll info

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
Dear @victor-gonzalez 
in this commit we're attempting to fix a bug I spotted recently: O2Physics tags after 15 Aug in the HL were producing strange distributions on k*  -- discrete values like the values that are supposed to be float were rounded to int. I didn't manage to reproduce the issue on my machine but I assume that might be due to the usage of abs() function that might return "int" or "float" depending on if it was overloaded, compiler settings etc. Maybe in the middle of August the building settings for O2 were changed and this caused the bug. Maybe in that case it can also be helpful to notify other analysers.
So, I changed it everywhere where floats needed to fabs(). On my local machine it doesn't make any difference (I used today's build of O2 on a Mac), but hopefully it'll …
> fixing abs rounding with fabs

- Common/TableProducer/timestamp.cxx
This change adds the caching of the start-of-run and end-of-run timestamps
in addition to the orbit-reset timestamp. It also validates that the
calculated timestamp is within the run duration before adding it to the
timestamp table. This ensures that only valid timestamps are used,
improving the reliability of the data.
> Protect against and diagnose OrbitReset issues

- Common/TableProducer/eventSelection.cxx
This avoids crashes due to bogus values of the timestamp of the first BC in the data frame
> Use run-wise timestamp to query the CCDB and optionally reject BCs outside run duration

- Common/Core/TrackSelection.h
- PWGCF/TableProducer/dptdptfilter.h
See also https://github.com/AliceO2Group/O2Physics/pull/7634
> Fix unexpected behavior in DCA cuts due to `abs` returning an integer

- PWGDQ/TableProducer/tableMaker.cxx
1. Add a new process for producing electron-muon table without TOF-related variables to avoid large memory consumption;
2. Group the cfgs of adding histograms to avoid reaching the element limits for a structure.
> PWGDQ: Add the process for electron-muon analysis in the tableMaker

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- PWGEM/PhotonMeson/Utils/ClusterHistograms.h
- PWGEM/PhotonMeson/Utils/NMHistograms.h
- Add a "EMEventsWeight" table that is joinable with EMEvents
- Table is filled in createEMEventPhoton
- Default is 1. (for data and non JJ MC)
- When "processJJMC" is activated in createEMEventPhoton the weight is extracted from the corresponding MC collision
- Added this weight to all pi0/eta and EMC cluster QC histograms
> PWGEM/PhotonMeson: Add event weight table for JJ MCs

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/lambdakzerofinder.cxx
Remove unnecessary Pz argument in dynamic column for pt MC 
Fix typo in lambdakzerofinder about collision.posY() --> collision.posZ()
> [PWGLF] Remove unnecessary arguments in dyn. col. + fix typo in lambdakzerofinder

- PWGLF/DataModel/LFNonPromptCascadeTables.h
- PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
This commit adds the PDG code of the mother and grandmother
particles to the NPCascCandidate struct and the corresponding
columns in the NPCascTableMC table. This additional MC
information will be useful for further analysis and
understanding of the non-prompt cascade candidates.
> Add grandma pdg code

- PWGDQ/Tasks/tableReader.cxx
@iarsene  
Addition of exceptions to exit the init in unused process functions. This should allow to reduce the memory usage for the various tasks.
If it works it will be extended to all the tasks.
> [PWGDQ ]Adding exceptions to exit the init in unused process functions [PWGDQ-83]

- PWGJE/TableProducer/jetderiveddataproducer.cxx
- PWGJE/Tasks/jettaggerhfQA.cxx
The `sigmadcaXYZ` taken from `getDcaXYZ` is squared, so a `std::sqrt` was need before writing it in the table.
> [PWGJE] Fixing a small bug with derived data producer

- PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Hi @fgrosa !
In this PR, I added two new histograms for PV Contributors to calculate the MC weight factors to find efficiency.
Let me know if any changes need to be made. Thanks
> PWGHF/D2H: PV Contributors for efficiency purpose

- PWGDQ/Core/HistogramsLibrary.cxx
Adding correlators <<2>> and <<4>> for charged tracks at mid-rapidity (output saved inside AnalysisResults.root )
> [PWGDQ] Adding Ref Flow histograms <<2>> and <<4>> for charged tracks at mid-rapidity

- PWGJE/Tasks/jetfragmentation.cxx
- PWGJE/Tasks/v0qa.cxx
* Fixed bugs with histograms
* Perp Cone now uses only matched jets
* For events without V0s, use charged jets for Perp Cone
* Added process for matched MCD jets
* Matched V0 daughter hist now fill daughter particle pt, not daughter track pt
> [PWGJE] Jet Fragmentation & V0 QA

- PWGJE/Tasks/ChJetTriggerQATask.cxx
Due to an issue with the phi distribution of high pT tacks, it was proposed to study tracks with relaxed conditions on the DCA. 
The updated code implements functionality to adjust DCA cuts for the quality tracks:
1) DcaZ cut is const and it can be tuned in JSON file
2) DcaXY cut has pT dependence of a track (taking here: https://github.com/AliceO2Group/O2Physics/blob/master/Common/Core/TrackSelectionDefaults.cxx#L37); Additional multiplication factor is introduced to relax this condition
> PWGJE: Custom DCA cuts for quality tracks

- PWGHF/TableProducer/treeCreatorDsToKKPi.cxx
This PR adds the centrality and number of contributors to Ds tree creator output, which will be needed to extract multiplicity weights for the efficiency evaluation using the sPlot technique
> PWGHF: Add centrality and number of contributors to Ds tree creator output

- PWGJE/Tasks/jetfragmentation.cxx
* Added process for perp cone that does not use matched jets
* Perp cone processes skip events without V0s
> [PWGJE] Jet Fragmentation: Perp Cone updates

- DPG/Tasks/AOTTrack/PID/TPC/qaPIDTPCMC.cxx
Adding definition of missing histo.
NB for @njacazio : beware that, as written now, for `nSigmaMC` histogram the code always fills `hnsigma/El/*` histograms. This is because you loop from 0 to 8 here https://github.com/AliceO2Group/O2Physics/blob/master/DPG/Tasks/AOTTrack/PID/TPC/qaPIDTPCMC.cxx#L580-L583 and therefore always these histos are filled: https://github.com/AliceO2Group/O2Physics/blob/master/DPG/Tasks/AOTTrack/PID/TPC/qaPIDTPCMC.cxx#L83-L85
I'm not fixing it, I'd leave it to you to avoid any clash in case somebody is massively using it in your crew.
> Add nSigmaMC.

- PWGCF/Flow/Tasks/flowGFWOmegaXi.cxx
- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/candidateCreatorB0Reduced.cxx
- PWGHF/D2H/TableProducer/candidateCreatorBplusReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
- PWGHF/D2H/Tasks/taskBplusReduced.cxx
- PWGHF/DataModel/CandidateReconstructionTables.h
This PR adds a flag to the B0 and B+ outputs for tagging B mesons associated with a wrong collision at MC level.
Few minor bugs were also fixed in the B+ reduced task.
> PWGHF: Add check for wrong collision association for B0 and B+ mesons

- PWGHF/HFL/Tasks/CMakeLists.txt
- PWGHF/HFL/Tasks/taskElectronWeakBoson.cxx
PWGHF: a new task for W/Z decay to electron in midrapidity in Run3
> PWGHF: new task for W/Z->e in mid-rapidity

- PWGHF/TableProducer/candidateCreator3Prong.cxx
Fixing Lambda(1520) PDG code in candidateCreator3Prong.cxx, aligning it to the expected value, as done in O2DPG here: [PR #1673](https://github.com/AliceO2Group/O2DPG/pull/1673).
Tested on 1 file of `HF_LHC24g5_All` MC production (see bin centered at 3 below):
> PWGHF: fix L(1520) PDG code.

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/Converters/straevselsconverter2.cxx
- PWGLF/TableProducer/Strangeness/Converters/v0mlscoresconverter.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
Add collision flags to the StraEvSels derived table in order to allow the separation between events with and without UPC mode
> Add collision flags to StraEvSels derived table

- Common/Core/RecoDecay.h
This PR introduces an optional parameter to getMatchedMCRec to disable the checks on the number of daughters of the candidate particle.
This allows to match also particles with partly reconstructed decays. 
This change is needed for the PWGHF D resonances analysis
@vkucera, @fgrosa  how does it look to you?
> Common: Modified RecoDecay.h for MC matching of incompletly reconstructed decays

- PWGJE/Tasks/PhotonIsolationQA.cxx
Due to a missing preslice the task was iterating over all tracks per timeframe instead of per collision. Also added 2 histograms
> PWGJE: Fixed bug in PhotonIsolationQA.cxx

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/CMakeLists.txt
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
- PWGEM/Dilepton/TableProducer/filterEoI.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx
- PWGEM/Dilepton/TableProducer/treeCreatorSingleElectronQA.cxx
- PWGEM/Dilepton/Utils/EventHistograms.h
- PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: add a task to select EoI
> PWGEM/Dilepton: add a task to select EoI

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
- PWGDQ/Tasks/tableReader_withAssoc.cxx
Removing propagation in muon propagation. Rejecting same MFT-IDs only if the tracks are MFT-matched.
> [PWGDQ] Dimuon fixes

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/Tasks/QC/CMakeLists.txt
- PWGLF/Tasks/QC/strangederivedqa.cxx
* Adds a task to do quality assurance and basic cross-checks of derived data indices to help with debugging certain issues when analysing a very large number of simulation AO2Ds @romainschotter @gianniliveraro
> [PWGLF] strangeness derived data QA added

- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
- PWGHF/D2H/Tasks/taskB0Reduced.cxx
- PWGHF/D2H/Tasks/taskBplusReduced.cxx
- PWGHF/D2H/Tasks/taskBs.cxx
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreatorBs.cxx
- PWGHF/TableProducer/candidateSelectorBsToDsPi.cxx
- PWGHF/TableProducer/treeCreatorBsToDsPi.cxx
A few things still need to be polished but it should work already.
@apalasciano, @fchinu, @AlexBigO, please check that this PR does not disrupt your workflows.
> PWGHF: Add Bs meson to creator of reduced data model 

- PWGHF/HFC/Tasks/taskCharmHadronsFemtoDream.cxx
- Constrain the mixed-event strategy 
- Adjust the structure
> PWGHF: Constrain the mixed-event strategy and adjust the structure

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/filterPbPb.cxx
* Save info on whether UPC settings were used to reconstruct an event in the event filter.
* Add corresponding variable, cuts, and histograms.
> PWGDQ: Add bit for ITSUPCMode to event filter

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx
- PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx
- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- Change pointer to value in lambda for track matching function, as the values a,b,c,d,e,f were only assigned within the DefineCuts function and therefore did not initialize the cut correctly
- Remove histogram filling in MC part of skimmer task (only to be filled in the common process function)
> PWGEM/PhotonMeson: Fix track matching memory bug

- PWGDQ/Core/VarManager.h
Added checks to ensure that values[kCORR2REF] and values[kCORR4REF] do not result in NaN or Inf. If either of these values becomes NaN or Inf after calculation, they are set to 0.
> Handle NaN and Inf values in kCORR2REF and kCORR4REF calculations

- Common/TableProducer/trackPropagation.cxx
Fixing the "`<TAxis::SetBinLabel>: Illegal bin number`" errors for non-existing bins.
> Common: trackPropagation: Fix SetBinLabel error

- PWGLF/Tasks/Resonances/k1analysis.cxx
K1 analysis task: now it can use the configurable variable `cfgModeK892orRho` that can switch between two different decay mode: K892+pi or Rho770+K.
> PWGLF: Enable another decay mode (rho)

- .github/workflows/codeowner-self-approval.yml
This is needed in order to install pip packages globally in the new Ubuntu images, the other choice would be to create a venv and install the deps there instead
https://peps.python.org/pep-0668/
https://mattermost.web.cern.ch/alice/pl/f75f33zosf8rbd9dnagywfinac
CC: @mpuccio @vkucera @ktf
> GH Actions: Bypass PEP 668 in runners

- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/CMakeLists.txt
- PWGHF/D2H/TableProducer/converterReduced3ProngsMl.cxx
- PWGUD/Tasks/upcTauCentralBarrelRL.cxx
Hi @fcatalan92 yesterday when I asked you to update the data model for the ML scores of the Ds in the Bs decay, I overlooked that it was also used by @Luca610 in the Ds reso code, for which we have derived data produced. So I developed a simple converter for the table, such that we do not have to reproduce the derived data for the Ds resonances.
> PWGHF: add converter for 3-prong ML table in D2H reduced data format

- Common/TableProducer/centralityTable.cxx
- Common/TableProducer/multiplicityTable.cxx
* changes CCDB queries in mult and cent tasks to `getForRun` (without metadata) and `getSpecificForRun` (with metadata information) 
* Adds a healthy printout explaining which object is being loaded in case of metadata use with reconstruction pass
* Rearranges the `mRunNumber = bc.runNumber();` call such that operation without crash over uncalibrated data doesn't result in unnecessary CCDB queries: attempt CCDB load only once when run number changes and switch run number regardless of outcome.
> Common: move mult/cent table producers to getForRun CCDB queries

- .github/workflows/codeowner-self-approval.yml
This reverts commit 4bb538f.
Ubuntu latest is now back to 22.04, so our workaround is broken as the pip version there is too old. I'm also pinning to 22.04 instead, seeing that the latest tag is not very stable...
https://github.com/actions/runner-images/issues/10636#issuecomment-2417303444
CC @ktf @vkucera
- **Revert "GH Actions: Bypass PEP 668 in runners (#8020)"**
- **Pin action to Ubuntu 22.04**
> Revert "GH Actions: Bypass PEP 668 in runners (#8020)"

- .github/labeler.yml
- .github/workflows/labeler.yml
This commit adds a new GitHub Actions workflow to automatically label
pull requests based on the files changed. The workflow uses the
`actions/labeler` action to apply labels to the pull request based on
the configuration defined in the `.github/labeler.yml` file.
The labels are defined for the following areas:
- `alice3`: Changes to the ALICE3 project
- `common`: Changes to the COMMON project
- `infrastructure`: Changes to the project infrastructure (e.g., CI/CD,
dependencies, packaging)
- `dpg`: Changes to the DPG
- `pwgcf`: Changes to the PWGCF
- `pwgdq`: Changes to the PWGDQ
- `pwgem`: Changes to the PWGEM
- `pwghf`: Changes to the PWGHF
- `pwgje`: Changes to the PWGJE
- `pwglf`: Changes to the PWGLF and PWGMM projects
- `pwgud`: Changes to the PWGUD project
> Add automatic pull request labeling

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
improvement of rotational background
> PWGLF : improvement of combinatorial bkg. to reduce CPU usage

- PWGJE/Tasks/v0qa.cxx
- PWGLF/DataModel/V0SelectorTables.h
- PWGLF/TableProducer/Strangeness/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/v0selector.cxx
The V0 jet framework requires filtering out V0s that would be cut away with topological or mass cuts, before running the jet finder. Because of the very general functionality of the V0 selector, it is appropriate to place it in the LF directory, rather than the JE directory.
* Creates a table containing a flag denoting whether a V0 is possible signal or if it would be rejected by cuts made in the analysis
* Allows filtering out V0s that would never be reconstructed as signal before passing them on to other table producing tasks (important for V0 jet studies)
* pT-dependent cuts for K0S, Lambda, and LambdaBar separately
* Optionally cut on invariant mass
* Optionally apply competing mass cuts
* Optionally downscale potential signal collection (important for JE checks)
* [PWGJE] Added QA …
> [PWGLF & PWGJE] Create V0 Selector Task

- PWGJE/Core/JetTaggingUtilities.h
- PWGJE/DataModel/JetTagging.h
- PWGJE/TableProducer/jettaggerhf.cxx
- PWGJE/Tasks/jettaggerhfQA.cxx
Core/JetTaggingUtilites.h
- Add IPxyz for tagging
- To avoid return value of nullptr
DataModel/JetTagging.h
- Add xyz for both of IP and SV to compare tagging depedences
TableProducer/jettaggerhf.cxx
- Add xyz for both of IP and SV to compare tagging depedences
Tasks/jettaggerhfQA.cxx
- Divide general qa, xy and xyz of tagging for light output
> [PWGJE] Add xyz of IP and sv and avoid return value of nullptr

- PWGHF/HFC/TableProducer/femtoDreamProducer.cxx
- PWGHF/HFC/Tasks/taskCharmHadronsFemtoDream.cxx
Hi @1994ra and @fgrosa, The commit I implemented last week is still not satisfactory, since the number of events that contain lc (with selection) in one DF are few. The mixed event flow can only process in one DF for the current O2. so I made further modifications. Now, the producer no longer stores only the Lc-proton pair for collisions. Instead, I’ve set a mask to tag the collisions that contain at least one Lc or at least one selected track. Let me know if you have any questions or comments. Thanks!
> PWGHF: Add the QA plots for the mixed-event and Change the strategy of mixed event

- Common/Core/TrackSelectorPID.h
- PWGHF/Core/HfMlResponseD0ToKPi.h
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/HFC/TableProducer/correlatorDMesonPairs.cxx
- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateSelectorD0.cxx
- PWGHF/TableProducer/derivedDataCreatorD0ToKPi.cxx
- PWGHF/TableProducer/pidCreator.cxx
- PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
- PWGHF/Utils/utilsPid.h
@fgrosa here a possible development for the 2-prong only. 3-prong case not yet addressed
> [Common/PWGHF]: store PID info in 2-prong candidate table and propagate it to analyses.

- PWGHF/D2H/Core/SelectorCutsRedDataFormat.h
- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/CMakeLists.txt
- PWGHF/D2H/TableProducer/candidateCreatorCharmResoReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
This pull request continues the developements of the MC analysis for Charmed resonances:
1) dataCreatorCharmResoReduced:
-added origin information for matched candidates
-added partly-reconstructed decays in decay channel Dstar-V0 for debugging purposes
-fixed partly reconstructed decay D*->D+pi0
2) candidateCreatorCharmResoReduced:
-added MC table 
3) reducedDataFormat:
-modified tables accordingly
4) selectorCutsRedDataFormat:
-added pT Labels
> PWGHF: Developement of D Resonances MC analysis

- PWGHF/TableProducer/treeCreatorToXiPi.cxx
Add TPC crossed rows information to Xic0 tree for offline systematic uncertainty calculations
> PWGHF: add to Xic0 tree TPC info for systematic

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
I change the producer and the task for MCTruth. In the producer I excluded checking isPhysicalPrimary() for D0s. In the MCTruth task I change the mixing policy for same event. Now the StrictlyUpperPolicy is set for identical particle pairs and FullIndexPolicy for non-identical particle pairs.
> PWGCF:FemtoUniverse - MCTruth update

- PWGDQ/Tasks/MIDefficiency.cxx
Edited MID efficiency task adding a THnSparse to account for event centrality in Pb-Pb as well as pt, eta and phi of muon in pp and PbPb
> [PWGDQ] Add centrality + pt + eta + phi info in MID efficiency task

- EventFiltering/Zorro.h
Changes the base CCDB path for the Zorro class from "Users/m/mpuccio/EventFiltering/OTS/" to
"Users/m/mpuccio/EventFiltering/OTS/Chunked/". This is necessary to point to the correct location of the CCDB files for the chunked data.
> Update the default base CCDB path for Zorro

- .github/workflows/labeler.yml
Sets `sync-labels: true` for the labeler which allows to update the PR labels when the PR is modified.
> Infrastructure: Labeler: Automatically sync labels

- PWGLF/DataModel/LFNonPromptCascadeTables.h
- PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
This change adds a new table, `NPCascTableGen`, to the `nonPromptCascade.cxx` task. The new table is used to store information about the generated MC particles that correspond to the reconstructed cascades, including their transverse momentum, pseudorapidity, azimuthal angle, PDG code, and the PDG code of their mother particle. Additionally, flags indicating whether the particle is from charm or beauty decay are also stored. This information is useful for further analysis of the non-prompt cascade production.
> PWGLF: add gen cascades table to non-prompt-cascades task

- Common/CCDB/EventSelectionParams.cxx
- Common/CCDB/EventSelectionParams.h
- Common/DataModel/EventSelection.h
- Common/TableProducer/eventSelection.cxx
- DPG/Tasks/AOTEvent/CMakeLists.txt
- DPG/Tasks/AOTEvent/rofOccupancyQa.cxx
New FT0C-based occupancy estimation (in addition to the track-based), cleanup of old debug occupancy bits.
Adding new bits for the in-ROF pileup rejection.
Also, supplementary rofOccupancyQa task is added.
> Update of event selection task: new FT0C-based occupancy estimation, tuning of occupancy bits, new bits for the in-ROF pileup rejection

- PWGEM/PhotonMeson/Core/EMCPhotonCut.cxx
- PWGEM/PhotonMeson/Core/EMCPhotonCut.h
- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx is the new task
PhotonMeson/TableProducer/skimmerGammaCalo.cxx:
- removed `hasPropagatedTracks` config. This was only needed for really old reconstructions at the beginning of Run 3. PhotonMeson/Core/EMCPhotonCu:
- Added new variable `mUseTM`. This variable is true by standard and can be set to false via the setter `SetUseTM`. If it is false the TM will not be checked. Most useful for PbPb, since we don't want to match tracks to cluster there.
> [PWGEM-36] Creation of task for Pi0 flow

- PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- Add two configs `maxdEta` and `maxdPhi` to cut which tracks are counted as matched to reduce the amount of saved mathed tracks, which can be full of fake matches espacially in PbPb.
> [PWGEM-36]/PhotonMeson: Add configs to cut on TM dEta and dPhi

- PWGLF/Tasks/Resonances/chargedkstaranalysis.cxx
Dear Experts,
I have started working on the charged K* analysis in pp collisions. For this, I made some changes to the chargedkstaranalysis.cxx file, ensuring that it doesn't affect the study of the previous analyzer. I used the re-initializer table for reconstruction and also utilized THnSparse to fill the reconstructed mass, multiplicity, and p_{T} distributions.
Please review the code and let me know your suggestions.
Thanks,
With Regards,
Navneet Kumar
> PWGLF:To add charged Kstar in pp using THnsparse

- PWGLF/Tasks/Resonances/k892pmanalysis.cxx
Dear Experts,
I am trying to run the o2-analysis-lf-k892pmanalysis task for testing. However, I have noticed that abs(v0.mLambda() - massLambda0) always returns a zero value. When I include the namespace, it works fine. Therefore, I kindly request that these changes be committed.
Thanks,
With Regards, 
Navneet Kumar
> PWGLF:: To add the namspace for abs

- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/TableProducer/CMakeLists.txt
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
This PR is to include the TPC nsigma electron and the possibility to use a trigger mask on the skimmed datasets.
> [PWGCF] singletrackselector: Add TPC nsigma electron and Zorro utils

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/Converters/straevselsconverter2rawcents2.cxx
- PWGLF/TableProducer/Strangeness/Converters/straevselsconverter2rawcents3.cxx
- PWGLF/TableProducer/Strangeness/Converters/straevselsconverter3.cxx
- PWGLF/TableProducer/Strangeness/cascadepid.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeropid.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- change ccdb getters in lambkzero/cascade pid tasks + allow to force specific timestamp/run
- add converter task to go from StraEvSels_002 to StraRawCents_004 (allow to use anterior O2Physics with current derived data)
- change strangeness data model to incorporate new occupancy definition based on the sum of FT0-C amplitudes --> add StraEvSels_003
- add converter tasks to StraEvSels_003 
- Adapt derived table producer task to fill StraEvSels_003 table with the new occupancy definition
- Adapt analysis task to deal with new occupancy event selections and new occupancy definition
> [PWGLF] Add new occupancy features + change ccdb getters in lambdakzero/cascade pid

- PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx
adds the possibility to run the treeCreator also on EM derived data.
additional changes:
- add centrality to collision table
- write only collisions that have at least one selected track
- basic collision selection (VtxZ, occupancy)
- basic electron pid selection (nSigmaElTPC, nSigmaElTOF (if availalbe))
> PWGEM: treeCreatorElectronML also for derived data

- PWGUD/TableProducer/UPCCandidateProducer.cxx
- PWGUD/Tasks/upcTauCentralBarrelRL.cxx
After [this PR](https://github.com/AliceO2Group/O2Physics/commit/d71cfadb5bec112a65ee917a6648d224ef94b642#diff-3a6ed49cd6043ddee2f1608ae04181cd1ba9f0fcc9ae1a59104f7aa698688370L96) UPCCandProducer stopped working and was returning 
`[ERROR] SEVERE: Device upc-cand-producer (85030) had at least one message above severity 5: Unhandled o2::framework::runtime_error reached the top of main of o2-analysis-ud-upccand-producer, device shutting down. Reason: Trying to dereference index with a wrong type in _as<>. Note that if you have several compatible index targets in your process() signature, the last one will be the one actually bound to the getter.` 
This PR should fix it.
In addition, personal task modification are pushed to master.
> [PWGUD] Fixing UPCCandProducer problem after upcflag introduction + personal task modification

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/TableProducer/Resonances/LFResonanceInitializer.cxx
- Add `collision.trackOccupancyInTimeRange()` in the `ResoCollisions` table for the occupancy study.
> PWGLF: Add occupancy in the reso collision table

- PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
Delete unused function which was used to recalculate tof signal
Create histograms according to the enabled process function
> PWGLF: Delete unused tof pid recalculation and modify histograms creation for decay3bodybuilder

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
> PWGLF: added occupancy selection

- PWGHF/HFC/DataModel/DerivedDataCorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I've added 3 new tables in order to store the information on collisions containing a Ds-meson with the idea of using them to save derived data in order to perform the ME offline with the current framework already available in O2Physics.
Cheers,
Samuele
> PWGHF: Derived data for ME in Ds-h correlation analysis

- PWGCF/DataModel/FemtoDerived.h
- PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerReducedTask.cxx
- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
- PWGHF/HFC/TableProducer/femtoDreamProducer.cxx
Add triton and He3 PID to femtodream data model.
> PWGCF: add triton and He3 PID to femtodream data model

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: bug fix
#8100
sign of M_PI/2. was wrong.
.2 was wrong.
#8146
Histogram name was wrong.
if-else logic was wrong.
The linear cut is part of the elliptic cut. Namely, the linear deta cut is equivalent at the limit of dphi-> infinity.
If one wants to apply linear deta cut, one should set cfg_min_dphi = 1e+10, and vice versa.
> PWGEM/Dilepton: bug fix after #8100 and #8146

- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding a table for cascade analysis to FemtoDerived data model (it is created only when analyzing cascades). Changing the table used for cascades in Producer and TrackCascadeExtended task. Adding histograms for new saved variables to Cascade task.
> PWGCF: FemtoUniverse - Adding FDCascParticles table to FemtoDerived

- PWGHF/TableProducer/mcPidTof.cxx
- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
This PR modifies the task to get the NsigmaTOF distributions recentered in the MC for pi, K, p for HF analyses in order to comply with the recent modification of TOF tasks (TOFBase task deprecated).
It is based on https://github.com/AliceO2Group/O2Physics/blob/master/Common/TableProducer/PID/pidTOFMerge.cxx, so it inherits all the new features developed by @njacazio (including recopass automatically fetched from metadata)
> PWGHF: refactory of TOF MC task with recalibration following main TOF tasks

- PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
- PWGLF/TableProducer/Nuspex/threebodyRecoTask.cxx
- PWGLF/Tasks/Nuspex/hypertriton3bodyanalysis.cxx
Fix a bug in pre-selection (which is applied with a tighter cut in final selection later) of decay3bodybuilder
Change the order of cuts
> PWGLF: Fix a bug of TPC nclusters cut and change the order of cuts on tracks for analysis of hypertriton 3body decay

- Common/Core/FFitWeights.cxx
- Common/Core/FFitWeights.h
- Common/DataModel/EseTable.h
- Common/TableProducer/eseTableProducer.cxx
Added existing Q-vector framework. FFitWeights now holds the spline functionality of the event shape engineering procedure. Table columns for FT0-A and FV0-A added.
> Common: ESE splines for FT0-A and FV0-A

- PWGCF/Flow/Tasks/CMakeLists.txt
- PWGCF/Flow/Tasks/FlowRunbyRun.cxx
- PWGCF/Flow/Tasks/FlowTask.cxx
Hi reviewers, 
The `FlowTask.cxx` I am using has already consume a lot of memory (>500 MB per wagon). So I'd like to create to new task to hold the run-by-run output. This task would be lightweight for each run.
> PWGCF: flow: add Run3ITSall7Layers option and a new run-by-run task

- PWGLF/TableProducer/Strangeness/lambdakzerobuilder.cxx
- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
* This PR adds a specific TPC PID + MassWindow selection for photons in lambdakzerobuilder.
> PWGLF: Adding TPC PID + Mass pre-selection for photons

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
@ZFederica this adjusts the covariance matrices traditionally used for regular cascades to a format that is transparent with respect to the ones from tracked cascades (called `TraCascCovs`), with the main purpose of having fully uniform getters now also for covariance matrices for both regular and tracked cascades and allowing for template functions to be used to easily switch as desired. Please let me know if you face any problems!
> PWGLF: seamless treatment of cascade cov mats in builder / data model

- .checkov.yml
Exclude CKV_GHA_7 to tolerate workflow_dispatch inputs in https://github.com/AliceO2Group/O2Physics/pull/8199
See details in https://github.com/bridgecrewio/checkov/issues/3839
> checkov: Add configuration file with exceptions.

- PWGCF/DataModel/FemtoDerived.h
- PWGCF/FemtoDream/Tasks/femtoDreamHashTask.cxx
- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/Tasks/femtoUniverseHashTask.cxx
- PWGCF/FemtoWorld/Tasks/femtoWorldHashTask.cxx
- Tutorials/src/eventMixing.cxx
- Tutorials/src/tracksCombinations.cxx
Hello!
Upcoming O2 update will introduce `aod::Hash` template used in the core of refactored table types and providing mapping between string hash and the string. Unfortunately, it would clash with the aliases already defined in O2Physics. To ensure that O2 update would be seamless and do not require any interventions, I've took the liberty of renaming the `aod::Hashes` tables into `aod::MixingHashes` and the clashing alias to `using MixingHash = aod::MixingHashes::iterator;`.
> DPL Analysis: rename `aod::Hashes` for upcoming O2 update

- PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h
- PWGCF/FemtoDream/Core/femtoDreamUtils.h
Use named constants for pdg codes everywhere. Also adds pdg codes for triton and He3 go the get mass functions and removes obsolte functions to select PID.
> PWGF: Fix pdg codes in femtodream

- Common/Tasks/centralityStudy.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
This PR introduces some small changes to the MC matching to treat the case in which one of daughter tracks is a muon from pi decay.
> [PWGHF] Modified Resonance Data Creator to include muons

- PWGLF/Tasks/Strangeness/lambdak0sflattenicity.cxx
Following are the details of changes made in this version of the pull request.
1. Calculation of flattenicity in FV0 region added for MCGen 
2. Configurables are added to  control event selection cuts
3. 3D Histograms are added to store flattenicity versus v0s versus pT in MCGen, MCRec and Run3Data process functions
4. Configurables are added to control the Calculations of flattenicity from one or many detectors
5. Configurables are added to store flattenicity QA plots
> [PWGLF] Flattenicity calculation in FV0 region added for MCGen

- PWGLF/Tasks/Strangeness/lambdak0sflattenicity.cxx
I have added a fix to the memory leak issue in flattenicity calculation in processMCGen function.
> [PWGLF] Fix memory leak in Flattenicity Calculations in processMCGen

- PWGHF/D2H/Tasks/taskLc.cxx
- Fixed the default setting for the processes (there are 3 process functions be enabled simultaneously before)
- Adjust the structure to analyze data and mc per collision, reference as taskDs.cxx
- Add helper functions to make the structure clean (`fillHistosMcGen`, `fillHistosMcRec`, `fillHistosData` for the histogram and THnSparse filling)
> [PWGHF] Adjust the structure of the Lc to pkpi task

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
1) Apply the event selection: `o2::aod::evsel::kNoCollInTimeRangeStandard` 
2) Apply FT0C-based occupancy cut
`collision.ft0cOccupancyInTimeRange()`
> [PWGLF] PWGMM/Mult/Tasks/heavy-ion-mult.cxx: Add FT0C based Occupancy cut

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackSpherHarMultKtExtended.cxx
In this commit, I fixed the memory allocation and de-allocation issue that was earlier present in the pair-loop for same events. Also, I added randomness in making pair from mixed events (similar to the PR: https://github.com/AliceO2Group/O2Physics/pull/8279).
> [PWGCF] FemtoUniverse : Adding randomness in mixing for SH 

- Common/Tasks/centralityStudy.cxx
- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
using the particles constrained to the production vertex to calculate the decay length.
> [PWGHF] Fixing the decay length calculation using the KFParticle in the Omegac0 reconstruction.

- PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
Adding cuts on pT value, both min and max, in order to reduce the output of the derived table produced.
> [PWGLF] Add cuts pT max and min for tree saving

- Common/TableProducer/trackPropagation.cxx
- Common/Tools/TrackTuner.h
With this PR I add a user-friendly interface to configure the `TrackTuner` object in the  `Common/TableProducer/trackPropagation.cxx` workflow.
Inspired by the PR #6311 , I'm now proposing to make the `struct TrackTuner` to inherit from `o2::framework::ConfigurableGroup`. In this way:
- `Configurable`s data members can be defined for the `struct TrackTuner`;
- they appear automatically in the list of `Configurables` of the workflow in which the instance of the `TrackTuner` is declared. In particular,  the `TrackTuner` configurations appear now in the `Configurable` list of `Common/TableProducer/trackPropagation.cxx` in a `trackTuner` block, i.e.:
```
"track-propagation": {
"trackTuner": {
"debugInfo": "false",
"updateTrackDCAs": "true",
"updateTrackCovMat": "true",
"updateCurvature": …
```
> [Common]: add user-friendly interface for trackTuner configuration.

- PWGHF/HFC/Tasks/taskFlow.cxx
- PWGHF/Tasks/taskMcValidation.cxx
In this PR, I added : 
- Lc-h correlations for TPC-TPC case
- Lc-h correlations for TPC-MFT case
- QA plots associated with the respective cases
- Eta cut on MFT tracks (configurable, min and max)
- Cut on the number of clusters of the reconstructed track (configurable, min) 
Concerning Lc-h correlations, it is basically a copy/paste of D0-h correlations.
> [PWGHF] taskFlow.cxx: adding Lc-h correlations for TPC-TPC and TPC-MFT cases. Adding cuts on MFT tracks.

- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/candidateCreatorCharmResoReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
- PWGHF/D2H/Tasks/CMakeLists.txt
- PWGHF/D2H/Tasks/taskCharmResoReduced.cxx
1. dataCreatorCharmResoReduced.cxx:  
- added decay channel of Ds1 with at least one muon in the final state
- changed debug histogram ranges
2. candidateCreatorCharmResoReduced.cxx: 
- Removed indices from output table to avoid unbound indices in slim derived data
- Moved Mixed event here
- Added debug histograms to MC reconstruction analysis
3. taskCharmResoReduced:
- Added output tree for offline analysis
- Added MC process functions
> [PWGHF] Developments for charm resonances workflow

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/Tasks/vpPairQC.cxx
- PWGEM/Dilepton/Tasks/vpPairQCMC.cxx
PWGEM/Dilepton: add possibility to apply TOF chi2 cut
> [PWGEM/Dilepton] add possibility to apply TOF chi2 cut

- PWGLF/DataModel/LFSlimNucleiTables.h
- PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
**Description:**
This pull request adds the Time of Flight (TOF) chi-square calculation to the nuclei slim derived module. The TOF chi-square is a useful metric for evaluating the quality of the TOF information associated with a nuclei object, which can be important for various downstream analyses.
<###>Add TOF chi2 to the nuclei slim derived
> [PWGLF] Add TOF chi2 to the nuclei slim derived

- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx
- PWGHF/TableProducer/treeCreatorXicToXiPiPi.cxx
@creetz16 @JaeYoonCHO
- Fix bug related to uncertainties of PV/SV in DCAFitter case
- Add topological chi2 before applying the corresponding topological constraints to check for biases
> [PWGHF] XicToXiPiPi: Add chi2topo before applying topological constraints

- PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
- PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Fixed the problem of returning instead continuing after a collision did not fulfill all event cuts
- Added QA flags to enable event, cluster and meson QA plots
- Reduced THnSparse for flow to only 4D (minv, pt, cent, scalar product)
- Changed some config base values to be more reasonable
- minv binning, cent binning and scalar product binning
- Added option in createEMEventPhoton.cxx to only save collisions which have EMCal or PHOS readout. This option could help reduce dervied data size in PbPb. Default values are set, that this is not used!
> [PWGEM,PWGEM-36] Fix Pi0Flow task low collision count

- PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Changed Resolution to be 1D Profile
- Added possibility to cut on FT0 occupancy
- Added event mixing process function
- Added check to the three used QVectors to be within reasonable range as collision cut
- Fixed min value cut of minv and pT from configurable axis. First value is the size of the vector, not the first value of the underlying vector
> [PWGEM,PWGEM-36] i0FlowTask - Fix Resolution definition

- PWGLF/Tasks/Strangeness/lambdak0sflattenicity.cxx
In this version of PR, the following changes have been made.
1. Fix processRecMC stops after certain iterations, Replacing "return" with "continue"
2. A histogram is added to check the correlation between flattenicity from the generated and reconstruction levels.
> [PWGLF] Fix processRecMC stops after certain iterations

- PWGJE/DataModel/EMCALClusters.h
With the changes to our clusterizer algorithm https://github.com/AliceO2Group/AliceO2/pull/13643 we decided to change the EMCALClusterDefinition that we have. We now have:
- kV3NoSplit
- kV3NoSplitLowSeed
- kV3NoSplitLowerSeed
- kV3Default
- kV3MostSplit
- kV3LowSeed
- kV3MostSplitLowSeed
- kV3Default is our default setting.
- LowSeed/LowerSeed if the seed energy is 300/200 MeV
- NoSplit if the gradient cut is turned off -> this should be basically like the V1 clusterizer from Run 1 and 2. We decided to not name it V1 because it could be missunderstood as a worse version compared to V3.
- MostSplit if the gradient cut is turned on but the gradient value is set to 0, so only cells with less energy can be added to a cluster.
> [EMCAL-1149,PWGJE] EMCALClusterDefinition definition changes

- PWGEM/PhotonMeson/Utils/ClusterHistograms.h
- PWGJE/Tasks/mcgeneratorstudies.cxx
- Add a counter for BCs with and without collisions, and their respective generated particles
- Add QA histograms in the EMC cluster QA for track matching
> [PWGJE/EMCal,PWGEM/PhotonMeson] Add BC wise generated particles and track matching QA histos

- PWGUD/TableProducer/UPCCandidateProducer.cxx
Update for the selection of forward tracks in the UPCCandidateProducer: use a global (MFT-MCH-MID) track if the track is within the MFT acceptance; otherwise, use MCH-MID only.
> [PWGUD] Update of global forward tracks in UPCCandidateProducer

- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Add rotation background estimation to the Pi0 flow task via the function `RotationBackground`
- The rotation background proofed very useful in Run 2 and could help here in Run 3, especially with 
- Needed some dependancies from EMCal (`O2::EMCALBase O2::EMCALCalib `) which had to be added in the CMakeLists.txt
> [PWGEM,PWGEM-36] Pi0Flow: Add Rotation background method

- Common/DataModel/TrackSelectionTables.h
- DPG/Tasks/AOTTrack/qaImpPar.cxx
@phymanshu this should allow you to do the study on dcaXY by applying the default cut on dcaZ < 2 cm (beware: default cut only, i.e. not changeable at the moment)
> [Common,DPG] Add selection mask for global tracks w/o dcaXY cut.

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMultKtExtended.cxx
Change multiplicity policy to centrality policy in 'femtoUniversePairTaskTrackTrackMultKtExtended.cxx'; plus, correct two variables' names.
> [PWGCF] FemtoUniverse: Change multiplicity policy to centrality policy in MultKt.

- PWGUD/DataModel/UDTables.h
- PWGUD/TableProducer/UPCCandidateProducer.cxx
- a new table `UDCollisionSelExtras` was defined that stores information about the number of active channels in all FIT detectors (FT0A, FT0C, FDDA, FDDC, FV0A). 
- FDD information (time, amplitude) is now correctly filled in both forward processes
- signal coincidence is used to get the number of active channels in FDD
> [PWGUD] Fill FDD tables using UPCCandidateProducer

- PWGDQ/Tasks/MIDefficiency.cxx
Fixed typo in efficiency task -> commit is not urgent since the affected part of the code is not used for the moment but I fixed it now since I noticed it
> [PWGDQ] Fixed typo in efficiency task -> not urgent

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
adding efficiency correction test
> [PWGLF] adding efficiency correction test

- PWGHF/TableProducer/CMakeLists.txt
- PWGHF/TableProducer/converterDstarIndices.cxx
This PR adds a converter to allow the analyses of HF derived data for D* after the fix in https://github.com/AliceO2Group/O2Physics/pull/8322
> [PWGHF] add converter for table with Dstar indices

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Calling for an instanziation of the EMCal geometry is now only done once in the init, instead of every time one wants to check if the rotated clusters are still on the EMCal.
- The check if rotated clusters are still on the EMCal surface was moved from inside the cluster loop that was inside the rotation method to before the loop, since the rotated clusters do not change in the loop.
- These changes should give a speedup factor of around 10 in PbPb for the call of the Rotationmethod
> [PWGEM,PWGEM-36] Speed up EMCal Rotation method

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
There are is an undefined histogram that are filled in AnalysisDileptonTrack
1. When defining the histogram, subgroups must be given. Therefore `DefineHistograms(fHistMan, fHistNamesDileptonTrack[icut], "")`, the latter agument was set to` fConfigHistogramSubgroups.value.data()`
2. The histograms should be defined in a loop over the cuts on the electron legs `objArray`, not the cuts on the associated ytrack `objArraySingleCuts`. Therefore `objArraySingleCuts -> objArray`
3. However `fTrackCutBit`should be initialized with a the cuts on the associated track. Therefore this part of the for-loop was moved out.
> [PWGDQ] [PWGDQ-120] debugging of undefined histogram in AnalysisDileptonTrack (dqEfficiency_withAssoc.cxx)

- PWGLF/TableProducer/Strangeness/cascademcbuilder.cxx
- PWGLF/TableProducer/Strangeness/lambdakzeromcbuilder.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
This PR ensures the labeler service provided to help with V0 and cascade analysis still labels V0s/cascades correctly in case a kink decay (pion -> muon + antineutrino) is found in the MC association step. This happens frequently, as the TPC track carries the label and thus a plain de-reference of a V0 that includes a pion that decayed into a muon will have a muon+X in its association. Note that such cases will also be flagged as fake associations by corresponding bits of the track table (if checked).
After this PR is merged, the label will still point to the originating particle regardless, meaning a case in which e.g. Lambda -> p + pi -> p + mu + antineutrino, with the V0 made up of (p+mu), will be correctly labeled with the mcParticle label for the Lambda. For general use, please note …
> [PWGLF] Handle kink decays in association for V0/casc labeler

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
When using centrality (ConfUseCent) replace MutlNtr with MultV0M in binning policy.
Add mixing QA histogram.
> [PWGCF] Change mixing to use centrality when needed in V0 task

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/Converters/stramccollisionconverter.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
@ChiaraDeMartin95 this tiny change will allow for the closure tests to be done for cascade v2 straight from the strangeness derived data (it is a simple passthrough of the event plane angle from the generator, added to the main data model for this purpose).
> [PWGLF] add EP angle to stra der data

- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
Adding a PID scenario which doesn't use TOF nSigma for electron selection while applying TPC electron selection.
Used for DQ and EM comparison.
> [PWGEM] add PID scenario: TPC only selection hadron rej, TOF required"

- PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- added process functions for same event and mixed event to plot track-cascade correlations
- renamed some functions and variables in the cascade selection header to accommodate changes for both Xi and Omega analysis
- Kept Xi as the default configuration
> [PWGCF] FemtoUniverse cascade task -- added process functions for track-cascade analysis

- PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add a cell time shift in EMCalCorrectionTask
- Use parameters extracted from LHC22o (very similar between different periods)
> [PWGJE] [PWGJE,EMCAL-670]Add offline time calibration for data in EMCalCorrectionTask

- PWGHF/D2H/TableProducer/candidateSelectorB0ToDPiReduced.cxx
- PWGHF/D2H/TableProducer/candidateSelectorBplusToD0PiReduced.cxx
- PWGHF/D2H/TableProducer/candidateSelectorBsToDsPiReduced.cxx
- PWGHF/HFC/Tasks/taskCharmHadronsFemtoDream.cxx
- PWGHF/HFL/Tasks/taskSingleMuon.cxx
- PWGHF/TableProducer/candidateSelectorBsToDsPi.cxx
- PWGHF/TableProducer/candidateSelectorD0.cxx
- PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx
- PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx
- PWGHF/TableProducer/candidateSelectorDstarToD0Pi.cxx
- PWGHF/TableProducer/candidateSelectorLc.cxx
- PWGHF/TableProducer/candidateSelectorLcToK0sP.cxx
- PWGHF/TableProducer/candidateSelectorXicToPKPi.cxx
> [PWGHF] Fix int8_t configurables

- PWGLF/TableProducer/Strangeness/cascadeflow.cxx
> [PWGLF] Fix int8_t configurables

- Tutorials/ML/applyMlSelection.cxx
> [Tutorial] Fix int8_t configurables

- PWGDQ/Tasks/dqCorrelation.cxx
- PWGDQ/Tasks/dqFlow.cxx
> [PWGDQ] Fix uint8_t configurables

- PWGCF/Flow/Tasks/flowPtEfficiency.cxx
Summary of Changes:
- Added additional track selection criteria, including:
- Chi2 per TPC clusters
- TPC crossed rows
- Pt-dependent cuts for DCAxy and DCAz, tailored for Run 3 pp
- `GlobalTrackRun3ITSMatching::Run3ITSall7Layers` selection
- Implemented selection criteria for vertex z.
- Enabled processing for specific runs of interest only.
> [PWGCF] Add some selections to pt-effeciency code

- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Fix the logic for obtaining the number of generated V0s/cascades/etc as a function of the occupancy 
--> create two functions: "getListOfRecoCollIndices" to find the recoed collision associated to a given MC collision, and "fillGeneratedEventProperties" to fill MC event histograms used for event splitting/loss estimation
--> fix ptmc and ymc to use the values calculated based on mother info and not the decay daughters info (not always available, most notably if the generated particle has not been reconstructed)
- group all event selection checks in a common function ("IsEventAccepted")
- introduce isTriggerTVX event selection
- add configurable to select the cut on the PVz position
> [PWGLF] Fix logic of the number of generated particles + others

- PWGJE/Tasks/bjetTaggingML.cxx
> [PWGJE] Fix int8_t configurables

- PWGLF/DataModel/LFNonPromptCascadeTables.h
- PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
Adds a new column `PdgCodeITStrack` to the non-prompt cascade tables to store the PDG code of the ITS track associated with the cascade. This information is useful for further analysis and identification of the tracked cascade origin.
> [PWGLF] feat: Add PDG code of ITS track to non-prompt cascade tables

- PWGJE/DataModel/EMCALClusters.h
- PWGJE/Tasks/emcclustermonitor.cxx
- Add three new clusterizer settings:
- `kV3StrictTime` with a cell time window of +- 500 ns
- `kV3StricterTime` with a cell time window of +- 100 ns
- `kV3MostStrictTime` with a cell time window of +- 50 ns
These setting can be used to test the effect of different cell time windows on Pi0 analysis. The clustermonitor task also got two new histograms to monitor this:
- `clusterCellTimeMean` which stores the mean cell time per cluster
- `clusterCellTimeDiff` which stores the difference of each cell times for each cluster. This is done FOR EACH cell pair in a cluster, not just cell_i to leading cell!
> [PWGJE,EMCAL-670] EMCal Clusterizer - add different MinMax time setting

- PWGDQ/Core/CutsLibrary.cxx
Two new cuts added til cutsLibrary.cxx:
1. `electronSelection1_idstoreh`: The same cut as `electronSelection1_ionut`, but with `kIsITSibAny` (Run 3 variable) in stead of `kISSPDany`(Run 2 variable)
2. `kaonPID3_withDCA`: changed from `kISSPDany` to `kIsITSibAny`  and added a DCA cut on the kaon with composit cut `dcaCut1_ionut`
> [PWGDQ] [PWGDQ-120] cutsLibrary.cxx: DCA cut on kaon, SPDAny->ISITSibAny for kaon and electron

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/DataModel/LFResonanceTablesMergeDF.h
- PWGLF/TableProducer/Resonances/LFResonanceInitializer.cxx
- PWGLF/TableProducer/Resonances/LFResonanceMergeDF.cxx
- PWGLF/Tasks/Resonances/lambda1520_PbPb.cxx
e() member for MC particles is added in ResoInitiliser table producer tasks, as I need it for my tasks to retrieve the mass of generated MC particles. Additionally, I included occupancy cuts, which I plan to use in my tasks while producing after derived datasets.
> [PWGLF] added e() memeber in reso. initilliser for mc particles and added occupancy cut in lamba1520_pb tasks

- PWGJE/Tasks/bjetTaggingML.cxx
Changing the bjetTraggingML task to process events without using the event weight for normalization.
> [PWGJE] Making the code process events without using weight

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
1. Defined new column in namespace
2. Added this column to BmesonCandidates table declared in namespace
3. Filled this column with mcDecision in BmesonsTable() within AnalysisDileptonTrack()
> [PWGDQ] [PWGDQ-120] dqEfficiency_withAssoc.cxx: added mcDecision to table of B meson candidates

- Common/TableProducer/Converters/CMakeLists.txt
- Common/TableProducer/Converters/tracksExtraV002Converter.cxx
@mpuccio This PR adds a new converter for the tracks extra table to v002, which includes the difference between findable and PID clusters in TPC https://github.com/AliceO2Group/AliceO2/pull/13617. This converter contains two process functions to act on both v000 and v001.
> [Common] add track extra converter to v002

- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
> [PWGCF] Config ccdb path for trigger selections

- EventFiltering/cefpTask.cxx
This change adds a new configurable option `cfgSkipUntriggeredEvents` to the
`centralEventFilterTask` in the `EventFiltering` module. When this option is
enabled, the task will skip processing events where both the trigger and
decision flags are false, reducing the overall processing output.
> [Trigger] Add option to skip untriggered events

- PWGLF/Tasks/Resonances/k892analysis_PbPb.cxx
Modified k892analysis_PbPb.cxx to analyze Run 2 converted data
> [PWGLF] Implementing a Run2 analysis functionality on the K892 PbPb analysis

- Common/TableProducer/match-mft-mch-data.cxx
The workflow made much size trees so it couldn't be submitted to the large data size analyses.
This PR removes the extra columns from the tables.
Furthermore, comfigurable parameters are set.
In addition to the modification, some function names are modified to understand easely.
> [Common] Modified the match-mft-mch-data.cxx to reduce table size

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
In this PR, I changed the modular or independent (of the collision table) filling of tracks to the nested filling of tracks. The track table will be filled only if the collision is selected. The changes are made only for the centrality analyses (i.e. Pb-Pb system). Next, I'll implement the same changes for multiplicity analyses also.
> [PWGCF] FemtoUniverse: From modular to nested filling of trks

- PWGLF/TableProducer/Strangeness/cascademcbuilder.cxx
Add again the pdgCodeV0 column filling for recoed cascade, that got removed by accident
@ChiaraDeMartin95
> [PWGLF] Re-add pdgCodeV0 column filling for recoed cascade

- PWGCF/FemtoDream/Core/femtoDreamPairCleaner.h
Fixed the Pair Cleaner, to check if the daughter is really not the same track as primary track in the pairs based on information stored at the producer level
> [PWGCF] Updated pair cleaner

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Controlling run dependent variations of Vx and Vy along with commenting out some line of code (not needed at present). Reduced the number of axis of THnSparse for acceptance corrections to avoid merging issue in Hyperloop.
> [PWGLF] added histogram to monitor run dependent variations of vxy and commented few section of code

- PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
Using generic framework for computing the two-particle correlation v2 for pions, kaons, and protons.
> [PWGCF] Generic Framework: PID v2

- PWGUD/DataModel/UDTables.h
Introducing a fix of the table definition string, which (probably) causes the problem with unbound indices at hyperloop
> [PWGUD] Fixing definition of UDMCPARTICLE and UDMCCOLLISION tables

- PWGLF/DataModel/LFSlimNucleiTables.h
- PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
In this PR I add to the table the PDGcode of mother od secondary particles. I also use the bit(7) of flags to check if track is matched with correct collision
> [PWGLF] Add MotherPDG and flag for ambiguous tracks

- PWGJE/DataModel/EMCALClusterDefinition.h
- PWGJE/DataModel/EMCALClusters.h
- PWGJE/DataModel/GammaJetAnalysisTree.h
- PWGJE/TableProducer/emcalCorrectionTask.cxx
- PWGJE/Tasks/gammaJetTreeProducer.cxx
- changed structure of isotree task to allow for photon triggers
- added cluster definition to gammaiso tree
- added changes to cluster definition in preparation for future changes in O2 (further testing needed in O2 before separate PR)
> [PWGJE] adding trigger capabilities and cluster definition to gammaisotree

- .github/workflows/o2-linter.yml
- Scripts/o2_linter.py
Adds a GitHub action that runs a script that checks for O2-specific issues in the code.
The script can run standalone, taking paths of files as arguments.
When running in the GitHub action on the pull_request event, the script tests files modified by the PR and generates error messages as GitHub annotations which appear as comments on the relevant lines or at the top of the file in case of per-file tests.
When running in the GitHub action on the push event, the script tests files modified in the branch w.r.t. the main branch and does not produce annotations.
False positives should be rare but, if any, they can be silenced per line for most of the tests by adding a comment in a given format.
Implements the following tests.
Bad practice:
- included `iostream`
- importing names from the …
> [Infrastructure] Add O2 linter

- PWGHF/D2H/Tasks/taskD0.cxx
Hi @Mingyu3360715 this is the change that we discussed offline:
- I added PV contributors (needed for JPsi-D efficiency maps) in the sparses for MC
- I removed a couple of unnecessary axes for data, to reduce data size (note that I also changed slightly the order of the axes, to have the common one in data and MC in the same position)
Informing also @atavirag
> [PWGHF] Add PV contributors in D0 sparse for MC and remove unnecessary axes

- PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
@Mingze129 this PR adds the info of pi/K -> mu in the MC sparses
@mfaggin I did not add it for the Lc, I let you judge if relevant or not
> [PWGHF] Add info about number of tracks decayed to muons for D* spin alignment

- Common/DataModel/PIDResponseITS.h
- PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
This commit adds new histograms to study the matching between ITS, TPC, and TOF
for nuclei candidates. The new histograms are added to the `hMatchingStudy`
array and are filled with the following information:
- Transverse momentum (`p_T`)
- Azimuthal angle (`phi`)
- Pseudorapidity (`eta`)
- ITS n-sigma for Helium-3
- TPC n-sigma
- TOF beta
The matching study is controlled by the `doprocessMatching` flag, which is set
to `false` by default. When enabled, the new histograms will be filled for both
matter and antimatter candidates.
> [Common,PWGLF] feat(nucleiSpectra): Add matching study histograms

- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
Hi @ddobrigk 
You probably remember that I added this part some time ago. After another detailed discussion with the KF authors it turned out that we should not use the SetProductionVertex in this case. I changed the code accordingly. 
Let me know if you have any comments on this. :)
Cheers
Carolina
> [PWGLF] Fix KF cascade daughter DCA calculation in cascadebuilder

- Common/TableProducer/Converters/CMakeLists.txt
- Common/TableProducer/Converters/trackQAConverter.cxx
Will not pass CI until https://github.com/AliceO2Group/AliceO2/pull/13633 is merged.
> [Common] TrackQA: Add converter for _000 to _001
