AliceO2Group/O2Physics

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
Just another fix of the histogram names
Cheers,
Samuele
=> PWGHF: Ds-h correlation, Fixed histogram names

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx, PWGEM/Dilepton/Utils/MomentumSmearer.h
First working version of HF cocktail analysis task (charm + beauty)
=> PWGEM: LMee HF cocktail task

PWGLF/Tasks/Resonances/lambda1520analysis.cxx
Added track selections, additional MC histos
=> Update lambda1520analysis task

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
Just added a missing table in the ME process
Cheers,
Samuele
=> PWGHF: Ds-h corr: add missing table

PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
I replaced the partition with the filter..
=> PWGHF: Replacing partition with filter

EventFiltering/PWGLF/strangenessFilter.cxx, PWGDQ/Core/CutsLibrary.cxx
New kinematic cut to be implemented in the updated Jpsi2ee tree.
=> Updated KineCut

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMEvent.cxx, PWGEM/PhotonMeson/TableProducer/skimmerDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/PhotonHBT.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
PWGEM/PhotonMeson: fix for event mixing in ee
PWGEM/PhotonMeson: fix for event mixing in ee
=> PWGEM/PhotonMeson: remove bz dependency

PWGEM/Tasks/phosElId.cxx
Added several cluster energy spectra histograms.
We fill them with conditions depending on cluster parameters.
=> [PWGEM] PhosElId new spectra histograms

PWGHF/D2H/TableProducer/candidateCreatorCharmResoReduced.cxx, PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx, PWGLF/Tasks/Resonances/k892analysis.cxx
dataCreatorCharmResoReduced: fixed Dstar mass calculation
candidateCreatorCharmResoReduced: fixed loop on candidates belonging to the same collision
=> PWGHF: Fixed bugs in Resonance Analysis

PWGHF/HFL/Tasks/taskSingleMuonSource.cxx
Select muon+ and muon- separately
=> PWGHF: Add the muon charge separation selection in HFL muon source task

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
Addition of new histograms.
Fix of faulty cut criteria.
=> PWGUD: Update of jpsi-central-corr task

PWGEM/Tasks/phosElId.cxx
Fixed if statements and added new histogram to check cluster time calibration quality
=> [PWGEM] PhosElId - new histogram to check cluster time, fixed if statements

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/MCSignalLibrary.cxx, PWGDQ/Core/MixingLibrary.cxx, PWGDQ/Tasks/tableReader.cxx
Add event plane in mixing pool
Add function with Q vector information to calculate event plane in event selection of the tableReader
Add MC signal with e from all conversions (also from different conversions)
Add cuts for Pb--Pb to do eta>0 and eta<0 dielectron analysis
=> Event plane in event mixing

PWGDQ/Core/HistogramsLibrary.cxx, PWGEM/Dilepton/Tasks/MCtemplates.cxx
Add a boolean to MC templates task:
to disable MCGenPairing
=> [PWGEM] MCtemplates: add a boolean to run MCGenPairs

PWGHF/Core/HfMlResponseBplusToD0Pi.h, PWGHF/D2H/DataModel/ReducedDataModel.h, PWGHF/D2H/TableProducer/CMakeLists.txt, PWGHF/D2H/TableProducer/candidateCreatorB0Reduced.cxx, PWGHF/D2H/TableProducer/candidateCreatorBplusReduced.cxx, PWGHF/D2H/TableProducer/candidateSelectorB0ToDPiReduced.cxx, PWGHF/D2H/TableProducer/candidateSelectorBplusToD0PiReduced.cxx, PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx, PWGHF/D2H/Tasks/taskB0.cxx, PWGHF/D2H/Tasks/taskB0Reduced.cxx, PWGHF/D2H/Tasks/taskBplus.cxx, PWGHF/D2H/Tasks/taskBplusReduced.cxx, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/DataModel/CandidateSelectionTables.h, PWGHF/TableProducer/candidateCreatorB0.cxx, PWGHF/TableProducer/candidateCreatorBplus.cxx, PWGHF/TableProducer/candidateSelectorB0ToDPi.cxx, PWGHF/TableProducer/candidateSelectorBplusToD0Pi.cxx, PWGHF/TableProducer/treeCreatorBplusToD0Pi.cxx
Update of the B+ reduced workflow ( based on B0 @AlexBigO @fgrosa )
- possibility of ML selections on D0 and B+ included
=> PWGHF: B+ reduced workflow with ML

PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
hello @vkucera, I fixed the problems you highlighted in an old PR https://github.com/AliceO2Group/O2Physics/pull/5893
=> PWGHF: implement requested changes in old PR omegac xic

PWGJE/TableProducer/jettaggerhf.cxx
Quick fix for memory leakage of std::vector
=> [PWGJE] Fix memory leak

PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
- Add pT dependent DCA cut
- Reduce memory required 
- Optimise logic (work in progress)
=> [PWGLF] LightNucleiTask - Add pT dependent DCA cut

PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
=> PWGEM/PhotonMeson: remove bz

Common/TableProducer/qVectorsTable.cxx, PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h
=> [event plane] add cfg for correction level

PWGEM/PhotonMeson/Core/CMakeLists.txt, PWGEM/PhotonMeson/Core/DalitzEECut.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Utils/EventMixingHandler.h
PWGEM/PhotonMeson: add EventMixingHandler.h and ML PID
=> PWGEM/PhotonMeson: add EventMixingHandler.h and ML PID

PWGEM/PhotonMeson/Tasks/pcmQC.cxx
PWGEM/PhotonMeson: quick fix for cut definition
=> PWGEM/PhotonMeson: quick fix for cut definition

PWGEM/PhotonMeson/Core/DalitzEECut.cxx, PWGEM/PhotonMeson/Core/DalitzEECut.h, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Utils/EventMixingHandler.h
PWGEM/PhotonMeson: add ITSib any/1st requirement
=> PWGEM/PhotonMeson: add ITSib any/1st requirement

PWGCF/TwoParticleCorrelations/TableProducer/identifiedBfFilter.cxx, PWGCF/TwoParticleCorrelations/TableProducer/identifiedBfFilter.h, PWGCF/TwoParticleCorrelations/Tasks/identifiedbf.cxx
Removed unidentified charged hadrons and muons
=> PWGCF: Added plots of N-sigma, wrong species tracking, and removed unused particles

PWGEM/Tasks/phosElId.cxx
removed unnecessary histograms,
added phi to kinematic variables histogram to address strange track propagation to Phos
=> [PWGEM] PhosElId - fixed several histograms

PWGUD/Tasks/exclusivePhi.cxx, PWGUD/Tasks/upcPionAnalysis.cxx
Updated upcPionAnalysis.cxx and exclusivePhi.cxx tasks.
=> fixed conflicts among branches

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx, PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
Just fixed the name of an histogram.
Cheers,
Samuele
=> PWGHF: Ds-h, Correct a bug in histogram name

PWGMM/Mult/Tasks/heavy-ion-mult.cxx
1) Add extra phi cut to eliminate the portions phi~0, phi~pi and phi~2pi 2) Add checks for Fake ITS tracks
=> PWGMM/Mult/Tasks/heavy-ion-mult.cxx: Add checks for Fake ITS tracks

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/MCSignalLibrary.cxx
Use more sub groups in the HistManager to avoid useless Histograms in the output
=> [PWGDQ] HistManager additional sub groups, VarManager new lmee signal

PWGDQ/Core/MixingLibrary.cxx
Event plane are defined from -Pi/2 to Pi/2
=> Fix the binning for event plane

PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h, PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Changes:
- cuts set up for dEtadPhiStar 
- removing unnecessary configurables and cuts in the producer
- adding configurables and cuts in same and mixed processes in the task
=> PWGCF:FemtoUniverse - D meson analysis update

PWGJE/Tasks/jetHadronRecoil.cxx
Also changing all outstanding M_PI to o2::constants::math::PI
=> PWGJE: Adding deltaR for recoil jets

PWGUD/Tasks/CMakeLists.txt, PWGUD/Tasks/exclusivePentaquark.cxx, PWGUD/Tasks/exclusivePhiLeptons.cxx, PWGUD/Tasks/exclusiveTwoProtonsSG.cxx
pp measurement:
- fixed pT ranges
- added rough analysis of high mass pp states
- added analysis task of SG events (to compare with DG events)
exclusive phi->ee:
- added angle check for the topology (angle between two vectors is pi within 10deg)
pentaquark measurement:
- expanded to SG from DG mode
=> [PWGUD] Fix pT pp, added SG pp, added angle check for exclusive phi, pentaquark in SG mode

PWGLF/Tasks/Resonances/kstarpbpb.cxx, PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
added rotational background for kstar v2
added QA plots and modify mc for phi resonance
=> added rotational background and QA plots and modify mc

DPG/Tasks/AOTTrack/qaMatchEff.cxx
modified from today's master branch
=> trackXhist* histos cleaned

PWGDQ/Tasks/MIDefficiency.cxx
Removed extra printout and comments
[Still to do] use cuts library
=> [PWGDQ] Removed extra printout and comments

PWGEM/Tasks/phosElId.cxx
fixed histograms tied to track kinematics
=> [PWGEM] PhosElId - mini fix

PWGUD/Core/UPCJpsiCentralBarrelCorrHelper.h, PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* Additional TOF histograms.
* New IVM cuts on Jpsi peak.
* Testing of PID strategies.
=> PWGUD: new histos and PID strategies

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
Fix efficiency hist load issue. Local test pass.
=> PWGLF: HStrangeCorrelation -> Fix efficiency hist load issue

Common/DataModel/EventSelection.h, Common/TableProducer/eventSelection.cxx, DPG/Tasks/AOTEvent/eventSelectionQa.cxx
Add calculation of occupancy in predefined time range, result is stored as a new column ("NumTracksInTimeRange", trackOccupancyInTimeRange(), int).
Occupancy is calculated in terms of nITStracks with nCls >=5.
=> Add calculation of occupancy in predefined time range

PWGUD/Tasks/exclusivePentaquark.cxx, PWGUD/Tasks/exclusivePhi.cxx, PWGUD/Tasks/exclusivePhiLeptons.cxx, PWGUD/Tasks/exclusiveTwoProtons.cxx, PWGUD/Tasks/exclusiveTwoProtonsSG.cxx, PWGUD/Tasks/sgExclusivePhi.cxx
- Added (as separate instances) dcaXY and dcaZ in all tasks
=> [PWGUD] Added dcaXY and dcaZ checks and histograms

PWGCF/Flow/Tasks/CMakeLists.txt, PWGCF/Flow/Tasks/FlowZDCtask.cxx
adding new task to PWGCF/Flow/Tasks to calculate q vectors using ZDC
=> Add Flow ZDC task

PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/tableReader.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
PWGDQ: Fix unbound indices in dielectronsAll table and add dielectronsAll table to tableReader_withAssoc.cxx
=> PWGDQ: Fix unbound indices in dielectronsAll table and add dielectronsAll table to tableReader_withAssoc.cxx

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] fix bug

PWGCF/FemtoWorld/Tasks/femtoWorldEfficiencyTask.cxx
Adding generated primary histograms to FemtoWorldEfficiencyTask to calculate TOF matching efficiency
=> PWGCF: FemtoWorld - Adding generated primary histograms to EfficiencyTask

PWGUD/Tasks/exclusiveTwoProtonsSG.cxx
Changing names since Hyperloop seems to be complaining about symbols
=> [PWGUD] Differentiate struct name

PWGLF/Tasks/Resonances/k892analysis.cxx
Additional configurable test selections on deltaEta and deltaPhi of daughers
=> Adding selection on deltaEta and delta Phi

PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGamma.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Utils/EventHistograms.h, PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: update pi0eta MC for flexibility
=> PWGEM/PhotonMeson: update pi0eta MC for flexibility

PWGUD/Tasks/exclusiveTwoProtons.cxx, PWGUD/Tasks/exclusiveTwoProtonsSG.cxx
- simplified DCA logic in both SG and DG tasks (à la `trackselector.h`)
- tested on both DG and SG small samples
=> [PWGUD] Fix DCA logic

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] separate PID selection

PWGDQ/TableProducer/tableMakerMC.cxx
Function with cov, mult and cent
=> Function with cov Mult and Cent

PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx, PWGEM/Dilepton/Utils/MCUtilities.h
Added the possibility to check at the partonic level if an electron pair comes from the same c-cbar/b-bbar pair.
Functions to do so are implemented in MCUtilities.h
=> PWGEM: hf cocktail task updates

PWGDQ/Core/MixingLibrary.cxx, PWGDQ/TableProducer/tableMakerMC.cxx
Fix the process with Cent and Mults together + add more bin in z vertex for mixed event pools
=> Fix tableMC and add more bin in mixing class

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] add shift correction

PWGHF/Tasks/taskMcEfficiencyToXiPi.cxx
Fix tables to be used in different process functions in toXiPi task for efficiency calculation
=> PWGHF: fix tables in different process functions toXiPiEff

PWGHF/HFC/DataModel/CorrelationTables.h, PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
modified aod::lcSel from bool to int,
added two flags for collisions to choose whether filter collsions contain Lambda_c or not,
add a variable to set how many events should be mixed,
modified V0M to T0M
=> PWGHF:modification for mixed event

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
fix mass getter function
event plane
v0 selection
add QA
=> [PWGLF] fix mass getter function, event plane, v0 selection

PWGDQ/TableProducer/tableMakerMC.cxx
To get mc truth histograms and histrograms in case of ProcessBarrelOnlyWithCentAndMults
=> Further fixes

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/tableReader_withAssoc.cxx
Implement triplet KFParticle vertexing and vertexing errors
Add cuts and adjust histograms for open charm analysis
Implement common track cuts for AnalysisAsymmetricPairing
=> [PWGDQ] Open charm analysis improvements

PWGLF/Tasks/Nuspex/NucleiEfficiencyTask.cxx, PWGLF/Tasks/Nuspex/NucleiHistTask.cxx, PWGLF/Tasks/Nuspex/QAHistTask.cxx
Fixed the MC PDG code implementation.
=> Bugfix: NucleiHistTask, NucleiEfficiecyTask & QAHistTask

PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Hi @vkucera, @fgrosa , In this PR,  I tried to fix typos in the naming of some histograms.
=> PWGHF: Histogram's naming typo fixed

PWGHF/D2H/Tasks/taskLb.cxx, PWGHF/TableProducer/candidateCreatorLb.cxx, PWGHF/TableProducer/candidateSelectorLbToLcPi.cxx
I added a basic framework to the Lb task for initial studies. In tests there was also a problem with taking the collision from the pion rather than the Lc in the candidate creator, which is occasionally empty, so I changed that.
=> PWGHF: Basic Lambda_b task setup

PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
In this PR I added a THnSparse containing dcaxy, dcaz, pt and systematic
=>  PWGLF:Add THnSparse for DCA in nucleiSprectra

Common/Tools/PID/handleParamBase.h
- Modify PID parameter handler (for CCDB uploads) to use STF/ETF instead of SOR/EOR information from RCT object on CCDB (following https://its.cern.ch/jira/browse/O2-3868)
- in case STF/ETF are not available for the requested run numbers (e.g. in Run 2 data), the SOR/EOR are used as fallback
- Automatically adds recommended 2-minute buffer to start and end of validity when values from CCDB are used
- Fix minor bug in printout when setting timestamp
=> PID tools: modify handleParamBase.h to use STF/ETF

PWGLF/Tasks/Resonances/KshortKshort.cxx
added rotational background in the code and mass correlation plot
=> added rotational background in the code and mass correlation plot

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
updates on hyperon polarization
=> [PWGLF] updates on hyperon polarization

PWGJE/Core/JetTaggingUtilities.h, PWGJE/TableProducer/jettaggerhf.cxx, PWGJE/Tasks/jettaggerhfQA.cxx
Core/jettaggingUtilites.h
- Remove unused parameters
TableProcuder/jettaggerhf.cxx
- Modification of resolution function with flavour
Tasks/jettaggerhfQA.cxx
- debugging code because the histograms that should be the same are not.
=> [PWGJE] Modification of resolution function for b-jet tagging and debugging on tasks

PWGLF/Tasks/Nuspex/spectraTOF.cxx
Added a configurable for enabling the DCAXYPhi histogram to manage memory usage.
=> Added a configurable option for enabling the DCAxyPhi histogram

DPG/Tasks/AOTTrack/qaMatchEff.cxx
Removed TPC cluster histo filling not booked, saved the correct implementation for future use
=> Removed fauly histo filling in MC section

PWGDQ/Core/MCSignalLibrary.cxx
correct signals on single track level
new signals on pair level
=> PWGEM: MC signals, correct signals on single track level, new signals on pair level

PWGDQ/Core/MCSignalLibrary.cxx, PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] updates on QA

PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
PWGEM/PhotonMeson: reduce histogram bins
=> PWGEM/PhotonMeson: reduce histogram bins

PWGDQ/Tasks/tableReader_withAssoc.cxx
- Additional protections for same-event-pairing
- Removal of fConfigQA from event selection causing breaking when not enabled
=> [PWGDQ] Fixing bugs of table-reader-with-association

Common/Tasks/integrationTest.cxx
Used for thinning quality assurance and debugging
=> Common: add extra debug information to integration test

PWGLF/Tasks/QC/CMakeLists.txt, PWGLF/Tasks/QC/mcParticlePrediction.cxx, PWGLF/Utils/mcParticle.h
=> [PWG-LF] add MC task

PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx
PWGEM/PhotonMeson: update event mixing
=> PWGEM/PhotonMeson: update event mixing

PWGEM/PhotonMeson/Core/DalitzEECut.h, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx
PWGEM/PhotonMeson: change default value for skimming primary electron
=> PWGEM/PhotonMeson: change default value for skimming primary electron

PWGJE/Tasks/phiInJets.cxx, PWGUD/Tasks/sgPIDSpectra.cxx
Relatively self-explanatory in title
=> Enables BR selection, and first attempt at creating a 4D response matrix

PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/PhotonMeson: quick fix to PR #6438
=> PWGEM/PhotonMeson: quick fix to PR #6438

PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx
PWGEM/PhotonMeson: make bins configurable
=> PWGEM/PhotonMeson: make bins configurable

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* Additional PID histograms with Nsigma for tpc and tof for studies of best PID technique.
* New PID selection.
* New TOF histograms.
=> PWGUD: New version of J/Psi central barel analysis.

PWGCF/EbyEFluctuations/Tasks/MeanPtFlucIdentified.cxx
=> PWGCF: Update MeanPtFlucIdentified.cxx

PWGUD/Tasks/exclusivePhiLeptons.cxx
- new topology with 2 electrons in TPC and 0 in TOF (to increase statistics, some statistical fluctuation at around the phi mass can already be seen)
- new topology with restricted angles between the electron momenta
- configurable PID selections
=> [PWGUD] new topologies phi->ee, configurable pid selections

PWGLF/Tasks/Nuspex/NucleiEfficiencyTask.cxx, PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
Added non pT version of various histograms.
=> Update NucleiHistTask & NucleiEfficiencyTask

DPG/Tasks/AOTTrack/qaMatchEff.cxx
Changed structure of thnsparse for compatibility with set of macros for dca analysis
=> Changed structure of thnsparse

ALICE3/Tasks/alice3-cdeuteron.cxx
=> ALICE3: Fix compilation warnings

DPG/Tasks/AOTTrack/PID/HMPID/qaHMPID.cxx, DPG/Tasks/AOTTrack/qaMatchEff.cxx
=> DPG: Fix compilation warnings

PWGHF/D2H/TableProducer/candidateSelectorBplusToD0PiReduced.cxx, PWGHF/D2H/Tasks/taskBplusReduced.cxx, PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx, PWGHF/HFL/TableProducer/electronSelectionWithTpcEmcal.cxx, PWGHF/Tasks/taskMcValidation.cxx
=> PWGHF: Fix compilation warnings

PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/PhotonMeson: fix to PR #6443
=> PWGEM/PhotonMeson: fix to PR #6443

PWGDQ/Core/HistogramsLibrary.cxx
Adding extra histograms for QC studies
=> [PWGDQ] Adding extra histograms for QC studies

PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add occupancy plot in MC (forgot to do it in earlier PR: https://github.com/AliceO2Group/O2Physics/pull/6448)
=> [PWGLF] Add Occupancy plot in MC

PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx
PWGEM/PhotonMeson: fill track histograms for each electron source
=> PWGEM/PhotonMeson: fill track histograms for each electron source

PWGMM/UE/Tasks/CMakeLists.txt, PWGMM/UE/Tasks/lambdak0sflattenicity.cxx
I have added a new task for the analysis of the production of K0s Lambda and AntiLambda as a function of charged particle flattenicity
=> PWGMM Strangeness vs Flattenicity

Common/Tools/PID/checkPidPacking.cxx
=> Common: Fix compilation warnings

PWGUD/AQC/udQCmidRap.cxx, PWGUD/Core/SGSelector.h, PWGUD/TableProducer/SGCandProducer.cxx, PWGUD/TableProducer/UPCCandidateProducer.cxx, PWGUD/Tasks/exclusiveTwoProtons.cxx, PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
unused-parameter
braced-scalar-init
=> PWGUD: Fix compilation warnings

PWGLF/Tasks/Nuspex/spectraTOF.cxx
Added DCAxy axis to reconstructed spectra plots
=> Update SpectraTOF.cxx for secondary estimation

PWGJE/Core/JetMatchingUtilities.h, PWGJE/TableProducer/secondaryVertexReconstruction.cxx, PWGJE/Tasks/hffragmentationfunction.cxx, PWGJE/Tasks/jetHadronRecoil.cxx, PWGJE/Tasks/jetfragmentation.cxx, PWGJE/Tasks/jetsubstructurehfoutput.cxx, PWGJE/Tasks/phiInJets.cxx
=> PWGJE: Fix compilation warnings

PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
In this PR I add configurable option for DCA histogram
=> PWGLF: Add configurable option for DCA histogram

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/converters/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/converters/ambElectronIdconverter.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Utils/EMTrack.h
PWGEM/PhotonMeson: implement self index array for amb ele
=> PWGEM/PhotonMeson: implement self index array for amb ele

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
Adding checks for ZDC intercalib
=> [PWGDQ] Adding QA histograms

PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
- Fixed skipping of some MC particles
- Fixed wrong filling of MC nSigma TOF
=> Bugfix NucleiHistTask.cxx

PWGEM/Dilepton/Tasks/smearing.cxx, PWGEM/Dilepton/Utils/MomentumSmearer.h
Give the possibility to load resolution and efficiency files from CCDB
=> PWGEM/Dilepton: ccdb for smearing task

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: update pcmQCMC
=> PWGEM/PhotonMeson: update pcmQCMC

PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/treeCreatorSingleElectronQA.cxx
PWGEM/Dilepton: add a task to create single electron tree for QA
=> PWGEM/Dilepton: add a task to create single electron tree for QA

PWGMM/Mult/Tasks/dndeta-hi.cxx
=> V0finder updated

PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add newly implemented occupancy-based event selections
=> [PWGLF] Add new occupancy-based event selections

Common/TableProducer/PID/pidTOFMerge.cxx
=> [PID] update metadata usage

PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
Tagging @DelloStritto @gluparel @strogolo @saganatt @zhangbiao-phy @1994ra for their info.
With this, the `centrality` workflow can be removed from the dependencies, if centrality is not needed.
Beware that there are no more `processData` and `processMc`, but `processDataNoCentrality`, `processDataWithCentrality`, `processMcNoCentrality`, `processMcWithCentrality` are now present.
=> PWGHF: factorize centrality table in Lc tree creator.

PWGDQ/Core/CutsLibrary.cxx
I am not a fan of this cut class. But if this is ok, we would add this tighter Pb--Pb cuts for the dielectron analysis.
=> Tighter Pb--Pb cuts

PWGLF/TableProducer/Strangeness/sigma0builder.cxx, PWGLF/Tasks/Strangeness/sigmaanalysis.cxx
This PR fixes some selections in sigma0-analysis task and also repairs MC processing in sigma0-builder. New QA histos were also added to both tasks.
=> Sigma0: General repairs + add QA histos

PWGCF/Femto3D/DataModel/singletrackselector.h, PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx, PWGCF/Femto3D/TableProducer/singleTrackSelectorExtra.cxx
Dear @victor-gonzalez,
We open this pull request after today's discussion. Here we add the info for the "occupancy" plus some other minor modifications. Could you please approve it? Thank you.
@njacazio @ercolessi
=> Updating the data model and table producer

PWGEM/PhotonMeson/Tasks/dielectronQC.cxx
PWGEM/PhotonMeson: add occupancy for event mixing classification
=> PWGEM/PhotonMeson: add occupancy for event mixing classification

EventFiltering/PWGHF/HFFilter.cxx
@zhangbiao-phy this fixes the issue in the Ds* selection
=> EventFiltering/PWGHF: Fix typo in indices for Ds* selection

PWGDQ/Core/MixingLibrary.cxx
=> Finner mixing pools

PWGCF/FemtoWorld/TableProducer/femtoWorldProducerTask.cxx
Otherwise we have more than 100 elements in the task, which is unsupported.
=> Move configurables in a ConfigurableGroup

PWGUD/Core/DGCutparHolder.h, PWGUD/Core/DGPIDSelector.cxx, PWGUD/Core/DGPIDSelector.h, PWGUD/TableProducer/DGCandProducer.cxx
. Changed default values of CollisionSel
. Added setters in DGAnaparHolder
. Corrected bin-labels of histogram reco/Stat
=> PWG-UD: Updates of  DGCutparHolder, DGPIDSelector.cxx, and DGCandProducer.cxx

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Tasks/dqFlow.cxx
- Fixing dq-flow task for reduced tables creation
- Adding rapidoty axis to THnSparse for dimuon flow
=> [PWGDQ] Fixing dq-flow task for reduced tables creation

PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx, PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I've added in the processes for evaluating the efficiencies both the check on the z-vertex position and the one on the NoSameBunchPileUp (added also in the processes for the collision selection used for data analysis).
Let me know for any comment.
Cheers,
Samuele
=> PWGHF: Ds-h correlation, adding checks for MC Closure Test

PWGCF/Femto3D/DataModel/singletrackselector.h, PWGCF/Femto3D/Tasks/femto3dPairTask.cxx, PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx, PWGCF/Femto3D/Tasks/femto3dQA.cxx, PWGCF/Femto3D/Tools/checkPacking.cxx
Dear @victor-gonzalez,
This commit follows the changes introduced to the data model we did last week after the PF. Now we want to take use of the new info. Could you please approve the changes? Thank you.
@njacazio
=> taking use of new info in the data model

Common/DataModel/Qvectors.h, Common/TableProducer/qVectorsTable.cxx, PWGJE/Tasks/trackEfficiency.cxx
add vectors columns for multiple event planes
Q-vector from TPC full tracks
=> [Event plane] add vectors columns for multiple event planes

PWGDQ/Core/MixingLibrary.cxx
Add the possibility to mix events only with similar occupancy
=> Add occupancy in mixing

PWGMM/Mult/Tasks/dndeta-mft.cxx
Put the phi cut to false by default
=> [PWGMM] dndeta-mft.cxx

PWGUD/Tasks/upcTauCentralBarrelRL.cxx
One more configurable to better control performance
=> [PWG-UD] modifying personal analyzer

PWGEM/Dilepton/TableProducer/treeCreatorSingleElectronQA.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h, PWGEM/Dilepton/Utils/PairUtilities.h, PWGEM/PhotonMeson/Core/CMakeLists.txt, PWGEM/PhotonMeson/Core/DimuonCut.cxx, PWGEM/PhotonMeson/Core/DimuonCut.h, PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/converters/emeventsconverter.cxx, PWGEM/PhotonMeson/TableProducer/createEMEvent.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx, PWGEM/PhotonMeson/Tasks/dimuonQC.cxx, PWGEM/PhotonMeson/Utils/EMFwdTrack.h, PWGEM/PhotonMeson/Utils/EMTrack.h, PWGEM/PhotonMeson/Utils/NMHistograms.h
This PR contains following changes:
update histograms for ee and nm
add dimuon analysis
=> PWGEM/PhotonMeson: update histograms for ee and nm

PWGDQ/Core/MCSignalLibrary.cxx
Adding additional MC Signals for Xic Baryons
=> PWGEM: Add MCSignals for Xi-Baryons

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/createEMEvent.cxx, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Utils/EventHistograms.h, PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: support multiple harmonics of q vector
=> PWGEM/PhotonMeson: support multiple harmonics of q vector

PWGCF/Femto3D/DataModel/singletrackselector.h, PWGCF/Femto3D/Tasks/femto3dPairTask.cxx, PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx, PWGCF/Femto3D/Tasks/femto3dQA.cxx
Sorry for bothering you again. Here we want to add one more event selection flag. Could you please approve it. Thank you!
@njacazio
=> adding another evsel flag

PWGJE/Tasks/bjetTreeCreator.cxx
Adding a parameter to decided how many of the secondary vertices to keep. Since jets with large number of constituents could have thousands of SVs. We decided selected only the largest SVs (n * nConstit).
Another parameter was added which tell the fraction of events to be dropped, to minimize the output file size.
=> PWGJE: Reducing the number of SVs to reduce the size of the output file

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] remove fatal

PWGLF/Utils/collisionCuts.h
I have added a histogram for selection QA, which plots the number of events per event selection step. Additionally, I have plotted the z primary vertex distribution before selection.
=> PWGLF : Add event selection QA histogram

PWGHF/HFC/Tasks/taskCorrelationD0Hadrons.cxx
Hello,
I want to make some changes to the previous histograms. The previous histograms had too many dimensions, making the storage too large. Therefore, I want to split them into three parts for storage.
=> PWGHF: taskCorrelationD0Hadrons.cxx: Add a condition to fill Toward, Transverse, and Away regions.

EventFiltering/PWGHF/HFFilter.cxx, PWGCF/Flow/Tasks/flowAnalysisGF.cxx
=> PWGCF: Add extra event and track QA plots for flow analysis

PWGUD/Tasks/upcTauCentralBarrelRL.cxx
=> [PWGUD] personal analyzer changes

PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/associateMCinfo.cxx, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx, PWGEM/PhotonMeson/Tasks/dimuonQCMC.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: add task dimuonQCMC and setPID for electron
=> PWGEM/PhotonMeson: add task dimuonQCMC and setPID for electron

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] fix modulation assignment

PWGMM/UE/Tasks/lambdak0sflattenicity.cxx
I have added the process functions for MCGen and MCRec. These would be useful for efficiency x acceptance calculations.
=> PWGMM: Adding MCRec and MCGen process functions

PWGEM/PhotonMeson/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/PhotonMeson: recalculate momentum of muon at PV
=> PWGEM/PhotonMeson: recalculate momentum of muon at PV

PWGUD/Tasks/upcTauCentralBarrelRL.cxx
=> [PWGUD] changes to personal analyzer

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
PWGEM/PhotonMeson: fix histogram name for rotation bkg
=> PWGEM/PhotonMeson: fix histogram name for rotation bkg

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* New histograms to verify cuts.
* Improved PID for leptons and protons.
=> PWGUD: new PID for central barrel J/psi

PWGEM/Dilepton/TableProducer/treeCreatorElectronML.cxx, PWGEM/Dilepton/Utils/PairUtilities.h
- missing track covariance term cZY for single track
- additional single track filters for pT, itsChi2NCls, itsNCls, itsNClsInnerBarrel, tpcNCls
- pair filters for pTee, mee
- new pair features: cosOpAng, cosPA, transverse decay length, Chi2AtPCA
- new single track features: trdSignal, trdPattern (for future use)
- separate down sample factors for different particle species
=> PWGEM: update treeCreatorElectronML

DPG/Tasks/AOTTrack/qaMatchEff.cxx
Modified PID codes to gain back-compatibility with previous analyses
=> ThnSparse modified

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/tableReaderBarrel.cxx
tableReaderBarrel with flexible cuts in configurable variables.
=> tableReaderBarrel with flexible cuts

PWGLF/Tasks/Resonances/kstarpbpb.cxx, PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
added occupancy for kstar v2
PID change for phi
=> occupancy and PID

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/dielectronQCMC.cxx, PWGEM/PhotonMeson/Tasks/dimuonQC.cxx, PWGEM/PhotonMeson/Tasks/dimuonQCMC.cxx, PWGEM/PhotonMeson/Utils/EventHistograms.h, PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: add dilepton v2
=> PWGEM/PhotonMeson: add dilepton v2

PWGLF/Tasks/Resonances/f0980analysis.cxx
This pull request adds track selection and Particle Identification (PID) to the base code.
The track selection is based on the reference 'k892analysis.cxx'.
=> PWGLF : Added track selection and PID

DPG/Tasks/AOTTrack/qaMatchEff.cxx
Corrected an error in the ThnSparse filling logic, where a mix of identified particles was selected, single particles bin where not filled
=> Thnsparse filling logic

PWGLF/Tasks/Resonances/kstarpbpb.cxx
improved rotational background to remove correlation between decay daughters
=> improved rotational background

CODEOWNERS
=> Update CODEOWNERS -> add Igor

PWGEM/Dilepton/Tasks/tableReaderBarrel.cxx
Improve configurable:
Check that the size of the std::vectors are consistent.
Put one cut as default
=> Improve configurable

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Tasks/filterPbPb.cxx
* New track cut for single gap event skimming with lower pT cut and which allows ITS-only tracks.
* More descriptive outcome histogram for filterPbPb.
=> [PWGDQ] New track cut for single-gap skimming

Common/Tasks/qVectorsCorrection.cxx
validation code for multiple event planes
=> [Event plane] validation code for multiple event planes

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Tasks/dielectronQC.cxx, PWGEM/PhotonMeson/Tasks/dimuonQC.cxx, PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/PhotonMeson: update tasks for v2 and v3
=> PWGEM/PhotonMeson: update tasks for v2 and v3

PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/DalitzEECut.h
PWGEM/PhotonMeson: add TOFif PID
=> PWGEM/PhotonMeson: add TOFif PID

PWGHF/TableProducer/treeCreatorOmegacSt.cxx
- link candidates with Monte Carlo charmed baryons
=> Extend tree creator for Omega_c with ST

Common/TableProducer/qVectorsTable.cxx
=> [event plane] fix index bug

PWGUD/Core/UPCTauCentralBarrelHelperRL.h, PWGUD/Tasks/upcTauCentralBarrelRL.cxx
Better handling of PID for testing.
=> PWGUD: Upgrade of personal task

PWGUD/Core/UPCTauCentralBarrelHelperRL.h, PWGUD/Tasks/upcTauCentralBarrelRL.cxx
A simple rework of debug messages to have control over output log files.
=> PWGUD: Modification of personal task

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
Add a new process for pure MC to do closure test.
Fix some small bugs.
=> PWGLF: Add a new process for closure text

PWGEM/PhotonMeson/TableProducer/associateMCinfoPhoton.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
PWGEM/PhotonMeson: quick fix to PR6770
=> PWGEM/PhotonMeson: quick fix to PR6770

PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
PWGEM/PhotonMeson: remove unused histograms
=> PWGEM/PhotonMeson: remove unused histograms

PWGHF/Core/HfHelper.h, PWGHF/D2H/Tasks/CMakeLists.txt, PWGHF/D2H/Tasks/taskSigmacToCascade.cxx, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/candidateCreatorSigmac0plusplusCascade.cxx
Dear @fgrosa, @mfaggin , @fcatalan92,
I have implemented the comments received from my last commit and prepared the task accordingly for Sigma_c analysis in the cascade channel. Please have a look and approve it.
Thank you.
Rutuparna and Andrea Alici
=> PWGHF: Add task for the SigmaCInCascade channel

PWGDQ/Tasks/tableReader_withAssoc.cxx
Adding process function including collision info in the code
=> [PWGDQ] Adding process function including collision info in the code

PWGUD/Tasks/upcTauCentralBarrelRL.cxx
Adding the machinery to calculate trueGap + histos refactoring + adding PID histos + splitting histos to gain more control over task performance
=> PWGUD: Personal task modification

PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx, PWGDQ/Tasks/filterPP.cxx, PWGDQ/Tasks/filterPPwithAssociation.cxx, PWGDQ/Tasks/filterPbPb.cxx
I ran into multiple occasions where the limit of an integer is not enough any more.
So I changed TH*I to TH*F
=> [PWGDQ] use float type for statistic histograms

PWGHF/D2H/TableProducer/candidateCreatorB0Reduced.cxx, PWGHF/D2H/TableProducer/candidateCreatorBplusReduced.cxx, PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx, PWGHF/TableProducer/candidateCreator2Prong.cxx, PWGHF/TableProducer/candidateCreator3Prong.cxx, PWGHF/TableProducer/candidateCreatorB0.cxx, PWGHF/TableProducer/candidateCreatorBplus.cxx, PWGHF/TableProducer/candidateCreatorBs.cxx, PWGHF/TableProducer/candidateCreatorCascade.cxx, PWGHF/TableProducer/candidateCreatorDstar.cxx, PWGHF/TableProducer/candidateCreatorLb.cxx, PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx, PWGHF/TableProducer/treeCreatorOmegacSt.cxx
@pstahlhu @creetz16 @JaeyoonCho
=> PWGHF: Add vertexing protection in XicToXiPiPi

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
This table is needed for some run 5 jet tagging measurements
=> ALICE3: Adding DCACov table to the tracking

PWGDQ/TableProducer/tableMaker_withAssoc.cxx
Adding the track propagation to `skimTracks` of table maker. 
@rbailhac Could you have a second look at this?
=> [PWGDQ/EM] track propagation to associated vtx in tableMaker

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx, PWGEM/Dilepton/Tasks/emuCorrelation.cxx, PWGEM/Dilepton/Tasks/emuCorrelationMC.cxx
PWGEM/Dilepton: add emuCorrelation task
=> PWGEM/Dilepton: add emuCorrelation task

PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx, PWGEM/Dilepton/Tasks/emuCorrelationMC.cxx
PWGEM/Dilepton: quick fix to #6833
=> PWGEM/Dilepton: quick fix to #6833

PWGUD/Core/UPCTauCentralBarrelHelperRL.h, PWGUD/Tasks/upcTauCentralBarrelRL.cxx
Adding options for PID hyphotesis tester + some more PID histos
=> PWGUD: Personal task modifications

PWGLF/Tasks/QC/tracked_cascade_properties.cxx
=> replaced Track_as with itsTrack_as to get ITS track with all properties

PWGUD/Tasks/upcTauCentralBarrelRL.cxx
fix to avoid calling undefined histograms
=> PWGUD: Personal task fix

PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: update dielectron MC task
=> PWGEM/Dilepton: update dielectron MC task

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
Adding MC Reco process for the track-Phi analysis
=> PWGCF: FemtoUniverse -- Adding Track-Phi MC process to the producer

PWGCF/EbyEFluctuations/Tasks/FactorialMomentsTask.cxx, PWGDQ/Core/VarManager.h
Avoids issues when compiling with newer ROOT.
=> Use std::isnan

PWGJE/Tasks/trackEfficiency.cxx
increase binning for sigma
PWGJE - trackEfficiency.cxx add split_nonprimary for tracks
PWGJE - trackEfficiency.cxx add histograms for pT=10->100 for eff/purity
PWGJE - trackEfficiency.cxx add histograms for pT=10->100 for eff/purity - fix
PWGJE - trackEfficiency.cxx: track res histograms add bins above 50
PWGJE - purity split  hist name fix
=> PWGJE - trackEfficiency: increase range sigmapt, 10-100GeV range for hists

PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx
PWGEM/Dilepton: select wide rapidity range for vector mesons
=> PWGEM/Dilepton: select wide rapidity range for vector mesons

PWGEM/Dilepton/Core/EMEventCut.cxx, PWGEM/Dilepton/Core/EMEventCut.h, PWGEM/PhotonMeson/Core/CMakeLists.txt, PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/CutsLibrary.h, PWGEM/PhotonMeson/Core/EMPhotonEventCut.cxx, PWGEM/PhotonMeson/Core/EMPhotonEventCut.h, PWGEM/PhotonMeson/Core/PWGEMPhotonMesonCoreLinkDef.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/MaterialBudget.cxx, PWGEM/PhotonMeson/Tasks/MaterialBudgetMC.cxx, PWGEM/PhotonMeson/Tasks/SinglePhoton.cxx, PWGEM/PhotonMeson/Tasks/SinglePhotonMC.cxx, PWGEM/PhotonMeson/Tasks/TagAndProbe.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0.cxx, PWGEM/PhotonMeson/Tasks/TaggingPi0MC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx, PWGEM/PhotonMeson/Tasks/emcalQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: make separate EMPhotonEventCut
=> PWGEM/Dilepton: make separate EMPhotonEventCut

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/TableProducer/treeCreatorSingleElectronQA.cxx, PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx
PWGEM/Dilepton: reduce memory consumption
=> PWGEM/Dilepton: reduce memory consumption

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/emuCorrelation.cxx, PWGEM/Dilepton/Tasks/emuCorrelationMC.cxx, PWGEM/Dilepton/Tasks/singleElectronQCMC.cxx
PWGEM/Dilepton: add single electron qc task
=> PWGEM/Dilepton: add single electron qc task

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/Tasks/singleElectronQCMC.cxx
PWGEM/Dilepton: add getSubGeneratorId for gap triggered MC
=> PWGEM/Dilepton: add getSubGeneratorId for gap triggered MC

PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
=> PWGHF: fix typo in track eta selection

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx, PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx, PWGEM/Dilepton/Tasks/emuCorrelation.cxx, PWGEM/Dilepton/Tasks/emuCorrelationMC.cxx, PWGEM/Dilepton/Tasks/singleElectronQCMC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: update dimuon task and associateMCinfoDilepton
=> PWGEM/Dilepton: update dimuon task and associateMCinfoDilepton

PWGCF/FemtoUniverse/Tasks/CMakeLists.txt, PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
Only track-track efficiency task included for now. Modularity included - process function for every type of analysis.
=> PWGCF: FemtoUniverse -- Efficiency task for FemtoUniverse (first commit)

PWGEM/Dilepton/Tasks/dimuonQCMC.cxx
PWGEM/Dilepton: minor fix to axis label
=> PWGEM/Dilepton: minor fix to axis label

PWGEM/Dilepton/Tasks/dimuonQC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx, PWGEM/Dilepton/Utils/EMFwdTrack.h, PWGEM/Dilepton/Utils/EMTrack.h, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: fix polarization calculation
=> PWGEM/Dilepton: fix polarization calculation

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/Tasks/PhotonHBTEEEE.cxx, PWGEM/Dilepton/Tasks/PhotonHBTPCMEE.cxx, PWGEM/Dilepton/Tasks/PhotonHBTPCMPCM.cxx, PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: update polarization
=> PWGEM/Dilepton: update polarization

PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dimuonQC.cxx
PWGEM/Dilepton: update dielectron and dimuon task
=> PWGEM/Dilepton: update dielectron and dimuon task

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
Adding PID for the efficiency task
=> PWGCF: FemtoUniverse -- Changes in the efficiency task

PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dimuonQC.cxx
PWGEM/Dilepton: change output format from THnSparse to TProfile3D for flow
=> PWGEM/Dilepton: change output format from THnSparse to TProfile3D for flow

PWGLF/Tasks/Resonances/KshortKshort.cxx
- Added helicity frame
- Gottfried-Jackson frame
- Production plane
- Random plane
- Continuous rotational background
=> added different planes for polarization studies

PWGLF/Tasks/Resonances/kstarpbpb.cxx
InvMass range changed to utilize more normalization range
=> InvMass range changed

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Tasks/dielectronQC.cxx, PWGEM/Dilepton/Tasks/dimuonQC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: update dilepton flow analysis
=> PWGEM/Dilepton: update dilepton flow analysis

PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx
PWGEM/Dilepton: add skimmerSecondaryElectron for tag-and-probe
=> PWGEM/Dilepton: add skimmerSecondaryElectron for tag-and-probe

PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: add min/max. TPC n sigma El separately
=> PWGEM/PhotonMeson: add min/max. TPC n sigma El separately

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] fix mass

PWGLF/Tasks/Resonances/f0980analysis.cxx
This pull request adds configurable binning for pT and centrality axes,
and configurable mass bins.
=> PWGLF : Added configurable binning for axes (mass, pT, centrality).

PWGEM/Dilepton/Tasks/dielectronQCMC.cxx, PWGEM/Dilepton/Tasks/dimuonQCMC.cxx, PWGEM/Dilepton/Utils/MCUtilities.h
PWGEM/Dilepton: add eh,hh correlated bkg for dilepton MC
=> PWGEM/Dilepton: add eh,hh correlated bkg for dilepton MC

PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/v0topologicalcuts.cxx
Added task to investigate best topological cuts for V0s.
Nikolaos Karatzenis
(Birmingham Uni)
=> PWGLF: Added Task for V0s Studies

PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: reduce histogram dimension
=> PWGEM/Dilepton: reduce histogram dimension

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h
PWGEM/Dilepton: add a configurable
=> PWGEM/Dilepton: add a configurable

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
Changing binning of nsigma for TPC and TOF histograms
=> PWGCF: Change binning of nsigma histograms

PWGDQ/Core/CutsLibrary.cxx
an additional PID cut with TOF requirement
=> [PWGEM] add cut TOF required for pp

PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
Resonance (phi) included in table produces. Reso reconstructed from inv mass of daughters.
=> PWGCF: FemtoDream - Phi Reso added to TableProducer Task

PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
Additional check to the correlation task for the efficiency application
=> PWGHF: D+-h Corr - Extra check

EventFiltering/macros/uploadOTSobjects.C
Support for Alien storage is added by connecting to TGrid with the specified
path; the baseCCDBpath is updated to reflect changes in the file structure.
=> refactor: Modify paths and add support for Alien in uploadOTSobjects

PWGLF/DataModel/LFClusterStudiesTable.h, PWGLF/TableProducer/Nuspex/LFTreeCreatorClusterStudies.cxx
Added MC option. Only anti-deuterons are selected for the trees
=> LFTreeCreatorClusterStudies: MC available. Deu tree only fills anti-deu

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqFlow.cxx
- Adding extra zdc tables for SP calibrations
- Adding histograms for offline checks
=> [PWGDQ] Adding extra zdc tables for SP calibrations

PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
This PR is resulut of [old PR] (https://github.com/AliceO2Group/O2Physics/pull/6886). 
This assign the centrality to McCollision from Reconstructed Collisions.
=> PWGHF: Add multiplicity dependence v2

PWGLF/DataModel/LFResonanceTables.h, PWGLF/TableProducer/Resonances/LFResonanceInitializer.cxx, PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/kstar892analysis.cxx, PWGLF/Utils/collisionCuts.h
-adding a new task for K*(892)  analysis in PbPb using filters and partitions on ResonanceTables 
-adding TrackOccupancyInTimeRange and ImpactParameter to ResonanceTables
=> K*(892) optimized

PWGLF/Tasks/Resonances/kaonkaonanalysis.cxx
1. Added helicity frame
2. Gottfried-Jackson frame
3. Production plane
4. Random plane
5. Continuous rotational background
=> Added frames for polarization studies

PWGLF/DataModel/LFClusterStudiesTable.h, PWGLF/TableProducer/Nuspex/LFTreeCreatorClusterStudies.cxx
fixed he3 mass, added K nsigmatpc selection
=> LFTreeCreatorClusterStudies: fixed he3 mass, added K nsigmatpc selection

PWGMM/UE/Tasks/lambdak0sflattenicity.cxx
The event-selection cuts are rearranged to compare with other analyses
=> PWGMM: Event Selection cuts rearranged

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/kaonkaonanalysis.cxx, PWGLF/Tasks/Resonances/kstarqa.cxx
**kstarqa code**
- Added helicity frame
- Gottfried-Jackson frame
- Production plane
- Random plane
-
**kaonkaonanalysis and kshortkshortanalysis**
- continuous rotation background
- TPC dE/dx
- Multiplicity and centrality distribution
=> added polarization frames in kstarqa code, minor changes in other codes

Common/TableProducer/qVectorsTable.cxx
Common/TableProducer/qVectorsTable.cxx: change max cent from 80 to 90
=> Common/TableProducer/qVectorsTable.cxx: change max cent from 80 to 90

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
=> PWGEM/Dilepton: reduce nbins

PWGHF/TableProducer/candidateCreatorDstar.cxx
Fixing typo introduced in #7013
=> PWGHF: fix typo introduced in PR#7013

PWGDQ/Tasks/tableReader_withAssoc.cxx
Add configurable to make track propagation optional.
=> [PWGEM] TableReader_withAssoc, make track propagation optional

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: reduce histograms
=> PWGEM/Dilepton: reduce histograms

PWGDQ/DataModel/ReducedInfoTables.h, PWGEM/Dilepton/Tasks/smearing.cxx, PWGEM/Dilepton/Utils/MomentumSmearer.h
- add DCA to SmearedTracks table
- change structure of resolution file (only TH2 instead of TObjArray)
=> PWGEM: add DCA to SmearedTracks table

PWGDQ/DataModel/ReducedInfoTables.h
=> [PWGDQ:Update ReducedInfoTables.h]

PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx, PWGDQ/Tasks/tableReader.cxx
Adding code to use zorro selections for DQ analyses
=> [PWGDQ] Apply zorro selections for DQ analyses

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: reduce histogram bins
=> PWGEM/Dilepton: reduce histogram bins

PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
Following what @qgp did in the Xi_c/Omega_c analysis
=> Use SmallGroups to avoid issues in MC processing

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/Utils/EventHistograms.h, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/Dilepton: implement protection
=> PWGEM/Dilepton: implement protection

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
add hist for trigger eff and purity, changed efficiency correction, QA plots
=> PWGLF: change in hStrangeCorrelation

PWGDQ/Core/HistogramsLibrary.cxx
- Removed extra histograms in `flow-dimuon` subgroup
=> [PWGDQ] Small fix to remove extra declarations in histogram class subgroup

PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: update single lepton efficiency
=> PWGEM/Dilepton: update single lepton efficiency

PWGLF/Tasks/Resonances/kstarpbpb.cxx
improve PID for kaon and pion 
modified occupancy range
=> improve PID and occupancy

.github/workflows/mega-linter.yml, PWGCF/Flow/Tasks/FlowPbPbpikp.cxx
Fixed the specified format errors by alibuild.
=> PWGCF/Flow: Fixed format errors

EventFiltering/CMakeLists.txt
Add the dependency explicitly to try to fix the issue on hyperloop
=> Add Arrow dependency to EventFilteringUtils

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: reduce histogram bins in MC task
=> PWGEM/Dilepton: reduce histogram bins in MC task

PWGJE/Tasks/mcgeneratorstudies.cxx
- Add possibility to require gammagamma decay channel
- Add more event selection cuts
- Add event cut histogram from EM for comparisons
- Add accepted particle histograms (in gamma gamma channel)
=> PWGJE: Add functionality to MCGeneratorStudies task

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
Add option for the on-the-fly tracker to treat xi's
=> ALICE3: Add option for otf-tracker to treat xi's

PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
=> PWGHF: fix bug in MC table processing for Omegac/Xic creator

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: change histogram names for consistency
=> PWGEM/Dilepton: change histogram names for consistency

PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
ProcessTrackV0 for task femtoUniverseEfficiencyBase
=> PWGCF: Add ProcessTrackV0 to Efficiency Base

PWGHF/D2H/Tasks/taskXic.cxx, PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
Added in `taskXic.cxx` THnSparse
- Mother particle Pt and Y
- Flag for MC particle in acceptance
=> PWGHF: Add MC information in THnSparse in taskXic

PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: reduce memory usage
=> PWGEM/Dilepton: reduce memory usage

PWGDQ/DataModel/ReducedInfoTables.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/Tasks/createResolutionMap.cxx, PWGEM/Dilepton/Tasks/dielectronMC.cxx, PWGEM/Dilepton/Tasks/dimuonMC.cxx, PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx, PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx, PWGEM/Dilepton/Tasks/singleElectronQCMC.cxx, PWGEM/Dilepton/Tasks/singleMuonQCMC.cxx, PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton: update smearing task
=> PWGEM/Dilepton: update smearing task

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Tasks/createResolutionMap.cxx
PWGEM/Dilepton: update smearing task in MC
PWGEM/Dilepton: update dilepton flow analysis
=> PWGEM/Dilepton: update smearing task in MC

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: update dilepton tasks in data and MC
=> PWGEM/Dilepton: update dilepton tasks in data and MC

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: add multiplicity filter
=> PWGEM/Dilepton: add multiplicity filter

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: avoid double counting when using TTCA
=> PWGEM/Dilepton: avoid double counting when using TTCA

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h
PWGEM/Dilepton: avoid double counting of pairs when using TTCA
=> PWGEM/Dilepton: avoid double counting of pairs when using TTCA

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h
PWGEM/Dilepton: change default value of cfgApplyWeightTTCA
=> PWGEM/Dilepton: change default value of cfgApplyWeightTTCA

ALICE3/DataModel/OTFMcTrackExtra.h, ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
- QA plots for daughters of the Xi when created in the tracker
- Produce new table with mc information of the created daughters
=> ALICE 3: Add QA plots and produce new table in otf-tracker

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMultKtExtended.cxx
Add selection for deuterons to femtoUniversePairTaskTrackTrackMultiKtExtended.cxx
=> PWGCF: Add De to MultKtExtended

PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton: fix for accessing files on CCDB
=> PWGEM/Dilepton: fix for accessing files on CCDB

PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx
PWGEM/Dilepton: fix Join table in MC skimming task
=> PWGEM/Dilepton: fix Join table in MC skimming task

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- added process for correlations of TrackV0 in centrality bins for MC
- added check for origin for both particles in analysis
=> PWGCF: correlations TrackV0 in centrality bins for MC

Common/TableProducer/eventSelection.cxx
add possibility to use metadata in the event selection to pick between Run2 and Run3
=> [Event selection] add metadata

DPG/Tasks/AOTTrack/qaMatchEff.cxx
Moved AxisSpec to init functions and made them const
=> Fixed ConfigurableAxis not working

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx
reordering some cuts
adding additional cuts
fixing typo
=> [PWGEM]: update/add cut setting, fix typo

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/kaonkaonanalysis.cxx, PWGLF/Tasks/Resonances/kstarqa.cxx
changed the TPC dE/dx plot x axis from pT to p
=> changed the TPC dE/dx plot x axis from pT to p

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton: fix BEC variables
=> PWGEM/Dilepton: fix BEC variables

PWGHF/D2H/Tasks/taskDs.cxx
Hello @fgrosa,
I have added the information on the PV contributors to the task output, which is a necessary ingredient to study the multiplicity dependence of the efficiency.
=> PWGHF: Add PV contributors information to Ds task output

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Checking if the configurable is working correctly, 
Removing unused configurables for Phi meson
=> PWGCF:FemtoUniverse -- Checks in the producer

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/kaonkaonanalysis.cxx, PWGLF/Tasks/Resonances/kstarqa.cxx
FT0M amplitude axis is made configurable
fixed competing cascade cut
=> Axis made configurable now and competing cascade cut fixed

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
A fix of emEfficiencyTask, bring back changes from #5909
=> [PWGEM]: emEfficiencyTask include changes of older PR5909

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: reduce occupancy nbins
PWGEM/Dilepton: add possibility to require TOF during skimming
=> PWGEM/Dilepton: reduce occupancy nbins

PWGLF/Utils/collisionCuts.h
`CollCutCounts` was not defined in Run2 case.
=> PWGLF: Fix CollCutCount hist for Run2 dataset

PWGCF/JCorran/Core/JEPFlowAnalysis.h
Output filesizes were too big on hyperloop -> output histograms' sizes reduced.
=> Output filesize reduced with coarser bins

PWGDQ/Core/CutsLibrary.cxx
Fixing cuts by adding `return cut;`
=> [PWGEM]: fix of cut variations, add missing 'return cut;'

PWGUD/Tasks/CMakeLists.txt, PWGUD/Tasks/sgExclusivePhiITSselections.cxx
Exclusive (in)coherent phi search in the KK channel
Powered up ITS pseudo-PID, following suggestions from ITS experts
Adapted to use with both SG and DG skimmed data
=> [PWGUD] Exclusive phi revisited with powered up ITS psuedo-PID

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx, PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx, PWGEM/PhotonMeson/TableProducer/associateMCinfoPhoton.cxx
PWGEM/Dilepton: reduce data size and support EPA in MC
=> PWGEM/Dilepton: reduce data size and support EPA in MC

PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
In this PR I add a check on matching with correct PV in ProcessMC.
@ivorobye @mpuccio, for your information
=> PWGLF: Add a check on matching with correct PV in MC

PWGDQ/Core/HistogramsLibrary.cxx, PWGUD/Tasks/CMakeLists.txt, PWGUD/Tasks/upcEventITSROFcounter.cxx
=> PWGUD: Task to count UPC events in ITSROF

PWGEM/Tasks/phosElId.cxx
=> phosElId DCA cut

PWGCF/FemtoDream/Core/femtoDreamUtils.h
Add phi mass to femtodreamutils (specifically adding the phi pdg code to the get mass function).
=> PWGCF: Update femtodreamutils

PWGDQ/Core/CutsLibrary.cxx
I have added the 3 Sigma cut for cut optimization of muon tracks
=> [PWGDQ] Adding 3 sigma cut for pDCA cut optimization

PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: remove unnecessary variables
=> PWGEM/Dilepton: remove unnecessary variables

PWGDQ/TableProducer/CMakeLists.txt, PWGDQ/TableProducer/tableMakerJpsiHf.cxx, PWGHF/Macros/computeFonllPlusPythiaPredictions.C
@lucamicheletti this is the development that allows us to spare ~1 GB of memory as discussed offline
=> PWGDQ: JPsi-D combination task that directly reads output of table-maker

PWGLF/Tasks/Strangeness/phik0sanalysis.cxx
- Added signal loss study
- More QA in RecMC and GenMC
- Minor changes and fixes
=> PWGLF: Improvement in GenMC processes

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: add TOFbeta cut
=> PWGEM/Dilepton: add TOFbeta cut

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: fix histograms
=> PWGEM/Dilepton: fix histograms

PWGLF/Tasks/Resonances/KshortKshort.cxx
Corrected the multiplicity distribution fill and the number of Ks produced in an event.
=> Bug fixing in the code

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Utils/EMFwdTrack.h, PWGEM/Dilepton/Utils/EMTrack.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
PWGEM/Dilepton: fix event mixing
=> PWGEM/Dilepton: fix event mixing

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: add an option to require TOF in skimmerPrimaryElectron
=> PWGEM/Dilepton: add an option to require TOF in skimmerPrimaryElectron

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: reduce MC data size
=> PWGEM/Dilepton: reduce MC data size

PWGLF/Tasks/Resonances/KshortKshort.cxx
Filling the v0 daughters' parameters after selection for equal entries in both daughters histograms.
=> Minor changes

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Utils/EMTrack.h
=> PWGEM/Dilepton: update BEC

PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
- remove unnecessary includes,
- update comments and description of some configurables,
- change binning of come TempFitVar, add configurables for it,
- add z vertex cut on collisions
=> PWGCF: Changes in femtoUniverseEfficiencyBase task

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
fix dca to PV cut and axis for MC gen correlation function
=> PWGLF: hStrangeCorrelation.cxx: Bug fix in DCA to PV cut

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
=> ALICE 3: fix cascade indexing bug

PWGDQ/Core/VarManager.h, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqFlow.cxx
Updating the Flow framework for the new Q-vector names
=> [PWGDQ] Updating the Flow framework for the new Q-vector names

PWGHF/D2H/Tasks/taskDs.cxx
=> PWGHF: Cleanup unused partitions in Ds task

PWGJE/DataModel/EMCALClusters.h
Added a cluster definition in EMCALClusters.h which is a variation of the kV3Default
=> PWGJE: Added clusterdefinition EMCALClusters.h

PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h, PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Fixing the same QA histogram name issue for cascades and adding bachelor to QA histos. Adding DCA cuts for cascade daughters and cleaning up code in CascadeSelection.
=> PWGCF: FemtoUniverse - Fixing the same histogram name issue for cascades

PWGDQ/TableProducer/tableMaker.cxx
PWGDQ: add the option to only load LUT in the table-maker
=> PWGDQ: add the option to only load LUT in the table-maker

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/k892analysis.cxx, PWGLF/Tasks/Resonances/kaonkaonanalysis.cxx, PWGLF/Tasks/Resonances/kstarqa.cxx
- Made the rotational angle as configurable
- Added the rotational background in k892analysis code
=> changed the rotation angle for combinatorial background 

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: add protection against event mixing in close BCs
=> PWGEM/Dilepton: add protection against event mixing in close BCs

PWGEM/Dilepton/Tasks/createResolutionMap.cxx
PWGEM/Dilepton: update a task to create resolution map
=> PWGEM/Dilepton: update a task to create resolution map

PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: add a QA histogram for occupancy
=> PWGEM/Dilepton: add a QA histogram for occupancy

PWGLF/Tasks/Resonances/KshortKshort.cxx
Modified the competing cascade rejection cut
=> Modified the competing cascade rejection cut

PWGDQ/Tasks/taskJpsiHf.cxx
Fixing the issue of unsorted indexes in J/psi - D0 analysis task
=> [PWGDQ] Fixing the issue of unsorted indexes in J/psi - D0 analysis task

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/EMEventCut.cxx, PWGEM/Dilepton/Core/EMEventCut.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Utils/EventHistograms.h, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: add kNoCollInTimeRangeStandard in event selection
=> PWGEM/Dilepton: add kNoCollInTimeRangeStandard in event selection

Common/TableProducer/qVectorsTable.cxx, PWGHF/TableProducer/treeCreatorOmegacToOmegaPi.cxx
Adding a MC process to fill the table with MC results and adding an if condition to determine whether the candidate passes the selection or not.
=> PWGHF: Adding a MC process for Omegac0ToOmegaPi KF table in treeCreator 

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Undo the changes to the function runRecTrack base on the PR #7128
=> [PWGEM]: emEfficiency task, revert changes in runRecTrack

DPG/Tasks/AOTTrack/tagAndProbeDmesons.cxx
=> DPG: add minimum value for D-meson pt.

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
I've done some small changes in the producer and task for D0 analysis. In the task I've started preparing the code for MC analysis. I've added a dedicated process function. In general it is work in progress. 
In the task I've done small change for CPR and removed some comments.
=> PWGCF:FemtoUniverse - D0 analysis update and MC for D0

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
Adding selections for events:
* kNoSameBunchPileup
* kIsGoodZvtxFT0vsPV
* kIsVertexITSTPC
=> PWGCF:FemtoUniverse -- Removing unused variables + adding new selections for events

PWGUD/Tasks/upcRhoAnalysis.cxx
A collection of updates to personal task. Typo fixes, addition of a few more control histograms, changes to defaults of configurables, and separation of Xn0n events to Xn0n and 0nXn.
=> PWGUD: updates to upcRhoAnalysis task

PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
In this PR I add two axes in DCA THnSparse. One for primary-not primary, the other for decay from weak decay or not.
@fmazzasc @ivorobye
=> [PWGLF]: Add axes for secondary and secondary from weak decay in nucleisprectra

PWGEM/Dilepton/Tasks/emEfficiencyEE.cxx
Add cfg to only select injected Events, use subGenerator for selection
=> [PWGEM]: efficiency task add Selection for injected events

PWGDQ/Core/HistogramsLibrary.cxx
Introduce subgroup for PID histograms using postCalibration
=> [PWGDQ] reduce number of standard selected histos

PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Tasks/createResolutionMap.cxx
PWGEM/Dilepton: update MC event selection
=> PWGEM/Dilepton: update MC event selection

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
=> ALICE 3: Fix to treating of xi decay

PWGEM/Dilepton/DataModel/dileptonTables.h
PWGEM/Dilepton: add swt for leptons
=> PWGEM/Dilepton: add swt for leptons

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx
1) implement the time from start of run as a variable in VarManager
2) modify the VarManager SEL8 to include also the cut on the ITS ROF border and the time frame border cut, similar to the event selection
=> [PWGDQ] Implement time from SOR in VarManager and update definition of SEL8

PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
Add and option and configurable ConfIsDebug in efficiency task to create debug histograms such as nSigmas distributions for tracks.
Also change some functions arguments names to match better their meaning.
=> PWGCF: Add option to create debug histograms, change some arguments names

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: fix FIXED_WIDTH and VARIABLE_WIDTH in mixing bins
=> PWGEM/Dilepton: fix FIXED_WIDTH and VARIABLE_WIDTH in mixing bins

PWGEM/Dilepton/Core/Dilepton.h
PWGEM/Dilepton: improve flow analsyis
=> PWGEM/Dilepton: improve flow analsyis

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx, ALICE3/TableProducer/alice3-multicharm.cxx
=> ALICE 3: fix another indexing bug

PWGEM/PhotonMeson/Core/EMCPhotonCut.h, PWGEM/PhotonMeson/Tasks/emcalQC.cxx, PWGEM/PhotonMeson/Utils/ClusterHistograms.h
- Fix bug in the filling of EMCal pT/E histograms
- Simplify EMC cuts (removed tracks which are part of clusters)
=> PWGEM/PhotonMeson: Fix EMC QA histogram filling

PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/TableProducer/Strangeness/hStrangeCorrelationFilter.cxx, PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
@lhusova @ChiaraDeMartin95 @kcui1
=> PWGLF: h-str correlations: Changes to perform systematics in one go

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/Tasks/vpPairQC.cxx
PWGEM/Dilepton: update vpPairQC
=> PWGEM/Dilepton: update vpPairQC

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMultKtExtended.cxx
Add an extra function for stricter TPC Kaon Sigma selection for K+ and K-.
=> PWGCF: FemtoUniverse -- Add stricter kaon selection (CORRECTED)

Common/Tasks/qVectorsCorrection.cxx
Common/Tasks: add histograms for Q vector resolution
=> Common/Tasks: add histograms for Q vector resolution

PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
PWGEM/Dilepton: update a filter task
=> PWGEM/Dilepton: update a filter task

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: add occupancy filter for speed-up
=> PWGEM/Dilepton: add occupancy filter for speed-up

PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update event QC task
=> PWGEM/Dilepton: update event QC task

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- set the default of ConfIsActivateV0 to FALSE
- added ConfActivateSecondaries to fill secondary MC generated particles that were reconstructed
- added a template argument resolveDaughs (by default FALSE) which enables outputing the indices of the v0 daughters for MC truth
=> PWGCF: FemtoUniverse track-V0 task -- resolved v0 MC daughters and added configurable to activate secondaries

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGLF/Tasks/Resonances/f0980analysis.cxx
=> [PWGLF] add switch for RT analysis

PWGJE/Tasks/bjetTreeCreator.cxx
Fixing a bug with lf-jets tag number.
=> [PWGJE] fixing a small bug with jet flavor

PWGLF/Tasks/Strangeness/phik0sanalysis.cxx
- Added process functions for MCclosure test
- Added histograms for MB analysis
- Fixed GenMC collision selection with associated Reco collision
- Minor changes
=> PWGLF: Added process functions for MCclosure test

Common/DataModel/Centrality.h, PWGCF/TableProducer/dptdptfilter.h, PWGCF/TwoParticleCorrelations/TableProducer/identifiedBfFilter.h
Avoid recursive lookup in the schema while doing so.
=> Use C++20 concepts to determine which Centrality to return

PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
added tof as veto to improve PID selection for kaon
=> improve PID

PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMultKtExtended.cxx
Modify deuteron and kaon selection in MultKt task; check kaon selection consistency with Run2 in Efficiency task.
=> PWGCF: FemtoUniverse -- Modify De & K selection

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/TableProducer/tableMaker_withAssoc.cxx
1) TPC pileup estimators
2) VarManager fill function which takes as arguments the collision and the table of tracks
=> [PWG-DQ] Implementation of a few TPC pileup estimators

Common/Tasks/qVectorsCorrection.cxx
=> [EPDev] add occupancy selection

PWGLF/Tasks/Resonances/kstarqa.cxx
added boolean for PbPb studies
=> added boolean for PbPb studies

PWGLF/Tasks/Strangeness/cascadecorrelations.cxx
also change from eta to rapidity and implement PID logic in filling THnSparses
=> PWGLF: Add ME + eff corrections to cascadecorrelations

PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
- CPR check: added rectangular cut for v0-v0 pairs
- added CPR check back for mixed events
- removed unused configurable
=> PWGCF: FemtoUniverse track-V0 task -- added rectangular CPR cut and removed CPR for mixed events

Common/DataModel/Multiplicity.h, Common/TableProducer/multiplicityTable.cxx
Common: add multNGlobalTracks in multiplicity table
=> Common: add multNGlobalTracks in multiplicity table

ALICE3/DataModel/OTFMulticharm.h, ALICE3/TableProducer/OTF/onTheFlyTracker.cxx, ALICE3/TableProducer/alice3-multicharm.cxx
=> A3: Development of analysis-level tree for XiCC

PWGLF/Tasks/Resonances/k892analysis.cxx
1. TH3F -> THnSparse
2. Boolean to fill separate histograms for anti-particles
3. Boolean to fill PID histograms
=> memory optimization in the code

PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
change PID 
add occupancy 
change MC
=> PID and MC fix

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: update efficiency task for track-to-collision re-association
=> PWGEM/Dilepton: update efficiency task for track-to-collision re-association

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: update eventQC task
=> PWGEM/Dilepton: update eventQC task

PWGEM/Tasks/phosElId.cxx
added a new workflow for constructing mass spectra of dielectrons where one of the candidate electrons if from PHOS readings
=> [PWGEM] phosElId mass spectra update

PWGCF/GenericFramework/Core/FlowPtContainer.cxx, PWGCF/GenericFramework/Core/FlowPtContainer.h, PWGCF/GenericFramework/Tasks/flowGenericFramework.cxx
FlowPtContainer:
- Added support for switching between raw and central moments for vn-pt correlations
flowGenericFramework task:
- Added configurable to control this switch
=> Added central moment switch to FlowPtContainer

PWGDQ/Core/MCSignalLibrary.cxx
Adding an additional MC signal
=> [PWGEM] Add MC signal of direct B->c->e decay

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h, PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
PWGEM/Dilepton: remove q vectors for 4th harmonics
=> PWGEM/Dilepton: remove q vectors for 4th harmonics

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/TableProducer/skimmerOTS.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/Dilepton: add a skimming task for OTS
=> PWGEM/Dilepton: add a skimming task for OTS

PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
PWGEM/Dilepton: replace abs with fabs
=> PWGEM/Dilepton: replace abs with fabs

PWGLF/Tasks/Resonances/f0980analysis.cxx
=> [PWGLF] clean up

PWGDQ/Core/HistogramsLibrary.cxx
Add THnspare for differential rapidity-polarization studies
=>  Add THnspare for differential rapidity-polarization studies

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/kstarqa.cxx
- Added booleans to save Like sign or rotational background histograms
- corrected the Armenteros cut condition
=> Optimasation of code

PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
Fixes bug introduced by PR #7373 (@romainschotter please take a look)
=> PWGLF: cascadebuilder bug fix

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/eventSelection.cxx, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/Dilepton: add event selection task
=> PWGEM/Dilepton: add event selection task

Common/Tasks/qVectorsCorrection.cxx
=> [EPDev] add occupancy study

PWGHF/TableProducer/candidateSelectorD0.cxx
CandidateSelectorD0.cxx modified to allow selections from trigger class
=> PWGHF: D0selector Mass Cut from Triggers

PWGJE/Tasks/jettaggerhfQA.cxx
Solving table join problems by dividing tasks
=> [PWGJE] Divide task of tagging

PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/tableReader.cxx
Adding first version of mini tree. This new table is meant to provide a tool to do unbinned analysis
=> [PWGDQ] Adding first version of mini tree

PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
At gen level, considering only correlations between D->\pi K \pi and other charged particles considering the flagMcMatchGen flag
=> PWGHF: DpH Corr check Gen Flag

ALICE3/TableProducer/alice3-multicharm.cxx, PWGEM/Tasks/phosElId.cxx
=> ALICE 3: Add missing same mother check for XiCC

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateSelectorD0.cxx
This PR is about uncommenting the DCA cut in the D0 selector, which is expected to suppress the beauty component.
=> PWGHF: Uncomment the DCA cut in the D0 selector

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update dilepton and QC task
=> PWGEM/Dilepton: update dilepton and QC task

PWGJE/Tasks/jetfinderQA.cxx
Due to some git conflicts in local, PR again with advised version.
It locally tested, and works well
=> PWGJE: constituent pT max cut

Common/Core/CMakeLists.txt, Common/Core/CollisionTypeHelper.cxx, Common/Core/CollisionTypeHelper.h, Common/TableProducer/PID/pidTOFMerge.cxx
Reopening https://github.com/AliceO2Group/O2Physics/pull/7559
=> [TOF] switch based on coll system

Common/DataModel/Multiplicity.h, Common/TableProducer/multiplicityExtraTable.cxx
With work from @njacazio - thanks!
=> Common/Mult: add pvZ from FT0 for centrality

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
@lhusova @kcui1 @ChiaraDeMartin95
=> PWGLF/hStrCorr: add extra debug/QA histos

PWGJE/Tasks/jettaggerhfQA.cxx
Add histograms of tagged jet for sv
=> [PWGJE] Add histograms of tagged jet for sv

PWGHF/HFC/TableProducer/correlatorDplusHadrons.cxx
Make D-meson daughter removal configurable
=> PWGHF: DpCorr - Add option for daughters removal

PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
Adding track propagation to skimTracks in tableMakerMC_withAssoc.cxx
=> [PWGEM] Add track propagation in TableMakerMC

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update SP resolution
=> PWGEM/Dilepton: update SP resolution

PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: include TOFif in TPChadrej
=> PWGEM/Dilepton: include TOFif in TPChadrej

PWGCF/GenericFramework/Core/FlowPtContainer.cxx, PWGCF/GenericFramework/Core/FlowPtContainer.h, PWGCF/GenericFramework/Core/GFWConfig.h, PWGCF/GenericFramework/Core/GFWPowerArray.cxx
FlowPtContainer:
- Fixed newly added vectors lacking clear in the ClearVector() method
- Added various brackets
Other files:
- Fixes to warnings between unsigned/signed comparison
=> Missing vector clear on event change

Common/DataModel/CMakeLists.txt, Common/DataModel/MatchMFTFT0.h, Common/TableProducer/CMakeLists.txt, Common/TableProducer/match-mft-ft0.cxx
The code builds a table giving a list of BCs matched with each MFT track
The table can be joined with the MFTTracks table
=> [Common] Add a code matching MFT tracks to FT0-C signals

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
adding propagation of tracks on pair level in dq efficiency task
=> [PWGDQ] Add track propagation for pairs in dqefficiency task

PWGEM/Dilepton/TableProducer/eventSelection.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: include TOFif in TPChadrej at skimming
=> PWGEM/Dilepton: include TOFif in TPChadrej at skimming

PWGLF/Tasks/Strangeness/v0topologicalcuts.cxx
Corrections to plot names, a segmentation error and axes
=> PWGLF: v0topologicalcuts task corrections

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Tasks/vpPairQCMC.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update 2vp task
=> PWGEM/Dilepton: update 2vp task

Common/Core/CollisionTypeHelper.cxx, Common/TableProducer/PID/pidTOFMerge.cxx
=> [TOF] update configuration of merged task

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/DimuonCut.cxx, PWGEM/Dilepton/Core/DimuonCut.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: add possibility to select phi range
=> PWGEM/Dilepton: add possibility to select phi range

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
Remove ambiguous from standard output, use fConfigQA to write them to the output
=> [PWGDQ] place ambiguous information behind ConfigQA configurable

PWGJE/Core/JetTaggingUtilities.h, PWGJE/TableProducer/jettaggerhf.cxx, PWGJE/Tasks/jettaggerhfQA.cxx
delete prongAcceptance in loop
Add prongAcceptance in tagged jets
Add parameter of cut selection for tagged jet
=> [PWGJE] Add tight cut for sv method

PWGHF/TableProducer/candidateSelectorD0.cxx
@wuctlby @stefanopolitano this fixes the bug in the impact parameter selection
=> PWGHF: fix impact parameter selection in D0 selector

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
=> PWGLF: Change in hStrangeCorrelation.cxx

PWGDQ/TableProducer/tableMaker.cxx
@iarsene 
This modification requires the inclusion of the histogramRegistry, so that the automatic zorro histograms are produced in the table-maker. The same modification will be done in the table-maker-with-association after few checks.
=> [PWGDQ] Adding control histograms for zorro

PWGLF/Tasks/Resonances/kstarpbpb.cxx
remove fake kaon
pileup rejection cut
improve mixing of events
improve PID
=> fake kaon rejection

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: add N TPC shared clusters in data table
=> PWGEM/PhotonMeson: add N TPC shared clusters in data table

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
=> [PWGDQ] add LS histograms to output of MC selected signals

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update resolution estimation
=> PWGEM/Dilepton: update resolution estimation

PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
=> PWGEM/Dilepton: update 2vp

PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: add qc histograms
=> PWGEM/PhotonMeson: add qc histograms

DPG/Tasks/AOTTrack/qaImpPar.cxx, PWGLF/TableProducer/Nuspex/hyperRecoTask.cxx
Dear all,
I have added the track position at inner most update information. Let me know for any comment.
Cheers,
Samuele
=> DPG: AOTTrack: added track position at IU info

Common/DataModel/CMakeLists.txt, Common/DataModel/ZDCInterCalib.h, Common/TableProducer/CMakeLists.txt, Common/TableProducer/zdc-task-intercalib.cxx
This commit is needed in order to work on the optimization of the ZN tower intercalibration, whose calibrated signal are then used in all analyses making use of the spectator plane.
=> Table producer for ZN tower intercalibration for spectator flow studies

EventFiltering/PWGUD/diffractionFilter.cxx, PWGUD/Core/UDHelpers.h
This solves an issue with the DGFilter
=> Move Partition out of process function

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
@lhusova @ChiaraDeMartin95 @kcui1 will still cross-check in the morning ...
=> PWGLF: optionally require trigger particle as ev sel

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
Additional plots and cuts for central barrel jpsi study.
=> PWGUD: jpsi-centra-barrel-v5

PWGLF/DataModel/LFStrangenessMLTables.h, PWGLF/TableProducer/Strangeness/cascadebuilder.cxx, PWGLF/TableProducer/Strangeness/lambdakzerobuilder.cxx, PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Allow ML selections using either:
- the BDT scores stored in derived data
- the BDT scores from a custom ML model that the user can provide locally or get from CCDB
=> [PWGLF] Add ML selections

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
...selecting only on `doProcessSelectEventWithTrigger` didn't work but this does (checked).
=> PWGLF: protect use case of no trigger requirement + bugfix

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Tasks/vpPairQCMC.cxx
PWGEM/Dilepton: add possibility to apply DCA3D cut in 2vp
=> PWGEM/Dilepton: add possibility to apply DCA3D cut in 2vp

PWGLF/TableProducer/Nuspex/lnnRecoTask.cxx
And some corrections in axis legend.
=> PWGLF: Fix hdEdx fill lnnRecoTask

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
Completely new LF cocktail task
Necessary to run on hyperloop using the standard O2 table format o2mcparticles and o2mccollisions (old version was running on McTracks directly from o2sim_Kine.root file, which is not possible for on-the-fly analyses on hyperloop)
=> PWGEM: new LF cocktail task

PWGJE/Tasks/emcvertexselectionqa.cxx
Add histograms to study the correlation between z Vertices of BCs containing two collisions
=> PWGJE: Add z-vertex correlation histogram

PWGCF/Femto3D/DataModel/singletrackselector.h, PWGCF/Femto3D/TableProducer/Converters/CMakeLists.txt, PWGCF/Femto3D/TableProducer/Converters/singleTrackSelectorConverter.cxx, PWGCF/Femto3D/TableProducer/Converters/singleTrackSelectorConverterV1.cxx
adds a converter to move to the new format from v1 and fixes the unpacking
@glromane @sofiatomassini @ercolessi
=> [STS] add converter

PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/jetfragmentation.cxx, PWGJE/Tasks/v0jetspectra.cxx, PWGJE/Tasks/v0qa.cxx
jetfragmentation.cxx: perpendicular cone, combinatorial V0s, V0 signal weighting
v0qa.cxx: V0 qa task in jet framework
=> [PWGJE] Jet Fragmentation V0s

PWGLF/DataModel/Vtx3BodyTables.h, PWGLF/DataModel/pidTOFGeneric.h, PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx, PWGLF/TableProducer/Nuspex/threebodyRecoTask.cxx
delete useless output
add an option to enable PIDCut in decay3bodybuilder
=> PWGLF: Update 3body decay analysis

PWGLF/Tasks/Resonances/kstarpbpb.cxx, PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
background modification
pt dependent PID
=> background modification

PWGJE/Tasks/mcgeneratorstudies.cxx
- Add NEvent and Generated Pi0 histograms with BCID on the x-axis to investigate bunch train dependence of generated particles
- Bug fix in NEvent histogram filling
=> PWGJE: Add BC investigations to MCGen Studies

DPG/Tasks/AOTEvent/detectorOccupancyQa.cxx
cleanup, more qa histos (dEdx vs occupancy, pt, eta, phi vs high occupancy in dt bins, per-orbit occupancy qa, etc)
=> Update detectorOccupancyQa.cxx: cleanup, more qa histos

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] configurable axis

PWGJE/Tasks/emcvertexselectionqa.cxx
Add possibility for event selection to the vertex qa task to investigate collision splitting for different types of events
=> PWGJE: Add event selection to vertex qa task

PWGUD/TableProducer/DGCandProducer.cxx
This improves the filling of the UDtables with MC truth information
=> PWG-UD Proper processing of MC truth data

PWGLF/Tasks/Resonances/kstarqa.cxx
updated TRandom initialization
=> updated TRandom initialization

DPG/Tasks/AOTTrack/qaImpPar.cxx
Dear all,
I've modified the code in order to retrieve the track global coordinates instead of using the coordinates in the tracking frame (for the track IU part). 
Cheers,
Samuele
=> DPG: AOTTrack: Global track IU coordinates used

PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/dqEfficiency_withAssoc.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
Adding return from Dummy process functions
=> [PWGDQ] Adding return from Dummy process functions

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/k892analysis.cxx, PWGLF/Tasks/Resonances/kaonkaonanalysis.cxx
Memory leak issue resolved by not creating TRandom repreatedly
=> Memory leak issue resolved by not creating TRandom repreatedly

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
=> PWGLF: change in  hStrangeCorrelation.cxx

PWGCF/Flow/Tasks/flowGFWOmegaXi.cxx
Sorry, I closed the pull request due to misoperation. Please approved it again. Thanks a lot.
=> PWGCF: Add topological cut in flowGFWOmegaXi.cxx #7790

DPG/Tasks/AOTEvent/matchingQa.cxx
status presented at the AOT meeting on Sep 26
=> Update on matching QA

PWGMM/Mult/Tasks/heavy-ion-mult.cxx
I update the task to study the effect of occupancy cut on dNch/dη observable
=> PWGMM/Mult/Tasks/heavy-ion-mult.cxx: Add occupancy cut

Common/Tasks/qVectorsCorrection.cxx
=> [Event plane] update for pileup study

PWGJE/Tasks/PhotonIsolationQA.cxx
Implemented a function to calculate the number of local maxima in a cluster and another to identify the first mother of a photon. Additionally, I incorporated bunch crossings into the process function and reorganized the histograms.
=> PWGJE: Updated PhotonIsolationQA

PWGEM/PhotonMeson/Tasks/emcalQC.cxx, PWGJE/Tasks/emceventselectionqa.cxx, PWGJE/Tasks/mcgeneratorstudies.cxx
- JE: Move BC histograms from MCGen to EMC Event QA task
- JE: Reorder event selections in MCGen task
- EM: Add histogram for NEvents after subsequent cuts in EMC QC task
=> PWGJE/EMCal + PWGJE/PhotonMeson: Changes to Yield and Event Histograms

PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt, PWGLF/TableProducer/Strangeness/Converters/straevselsconverter2rawcents.cxx, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- add a converter task to re-create StraRawCents tables (now deprecated but necessary if we want to use old O2Physics tag)
- few fixes to study V0 production in UPC (or very low mult. coll.)
=> [PWGLF] Add converter + fixes for studying UPC

PWGJE/Tasks/v0qa.cxx
Added processes for studying feed-down correction
=> [PWGJE] Jets V0 QA

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/tableReader_withAssoc.cxx
Add process function for D_s in tableReader_withAssoc
=> PWGDQ: Add process function for D_s

PWGJE/Core/JetTaggingUtilities.h, PWGJE/TableProducer/jettaggerhf.cxx, PWGJE/Tasks/jettaggerhfQA.cxx
Add var of dispersion of sv for improvement
Add leading pt of maximum refer to jetfinderQA.cxx
Add tagged jet and mass on jettaggerhfQA.cxx
Fix input table of JP for data on jettaggerhfQA.cxx
=> [PWGJE] Add cut dispersion of sv

CODEOWNERS
Updates for LF and MM suggested by @njacazio
=> update codeowners for PWGLF and PWGMM

DPG/Tasks/AOTTrack/PID/TPC/qaPIDTPCMC.cxx, PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
f0 980 analysis in Pb-Pb without resonance initializer
=> [PWGLF] f0 980 analysis in Pb-Pb without resonance initializer

PWGUD/TableProducer/SGCandProducer.cxx
Add configurables to enable/disable filling the track and forward track tables
=> Add configurables to disable filling track tables

PWGLF/Tasks/QC/mcParticlePrediction.cxx
=> PWGLF:MC To add the histogram

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/DimuonCut.cxx, PWGEM/Dilepton/Core/DimuonCut.h
fix for https://github.com/AliceO2Group/O2Physics/pull/7876
=> PWGEM/Dilepton: fix for #7876

PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
=> PWGLF: Fix removal of MC check in decay3bodybuilder

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: update flow analysis
=> PWGEM/Dilepton: update flow analysis

PWGLF/DataModel/Vtx3BodyTables.h, PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx, PWGLF/TableProducer/Nuspex/threebodyRecoTask.cxx, PWGLF/Tasks/Nuspex/hypertriton3bodyMCQA.cxx, PWGLF/Tasks/Nuspex/hypertriton3bodyanalysis.cxx
Use the innermost position of daughter tracks for criteria 
Addition and bug fixed for derived data
Some modifications on QA plots
=> PWGLF: Update derived data and QA plots for 3body decay analysis

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] add flag for event selections

Tutorials/PWGHF/DataModelMini.h, Tutorials/PWGHF/dpl-config_skim.json, Tutorials/PWGHF/dpl-config_task.json, Tutorials/PWGHF/run_skim.sh, Tutorials/PWGHF/run_task.sh, Tutorials/PWGHF/skimCreatorMini.cxx, Tutorials/PWGHF/taskMini.cxx
=> PWGHF: Update tutorial

PWGHF/TableProducer/candidateCreatorCascade.cxx
Hi @prottayCMT, this should fix the tag of the Lc->pK0S signals in the creator.
=> PWGHF: fix tagging of Lc->pK0S signals

PWGCF/EbyEFluctuations/Tasks/FactorialMomentsTask.cxx
Updated  DCA cuts and  Phi smearing  applied.
=> PWGCF:/EbyEFluctuations/Tasks/FactorialMomentsTask.cxx

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: change default value of process switch
=> PWGEM/Dilepton: change default value of process switch

PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
Fix in dataCreatorCharmHadPiReduced.cxx :
- correct table filling for MC checks
=> PWGHF: Fix in B+ MC dataCreator

PWGJE/Core/JetTaggingUtilities.h, PWGJE/TableProducer/jettaggerhf.cxx, PWGJE/Tasks/jettaggerhfQA.cxx
Core/JetTaggingUtilites.h
Function modification of jetFromProngMaxDecayLength to connect table directly
Divide prong acceptance and sv acceptance
TableProducer/jettaggerhf.cxx
Modification resolution function for JP from LHC23d4 to LHC24g4 which is weighted
Tasks/jettaggerhfQA.cxx
Add JP weighted and matched for different definition of jet-flavour
=> [PWGJE] Update JP weighted and modification of prong and sv acceptance

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
=> PWGLF: Fix histo creation bug in hStrangeCorrelation.cxx

Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask1.cxx, Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask2.cxx, Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask3.cxx, Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask4.cxx, Tutorials/PWGCF/FemtoFramework/src/CFTutorialTask5.cxx
Update to the exercises in the PWGCF tutorial for ATO2 edition 4.
=> PWGCF: update tutorial exercises

Tutorials/PWGLF/Resonance/CMakeLists.txt, Tutorials/PWGLF/Resonance/README.md, Tutorials/PWGLF/Resonance/resonances_step3.cxx, Tutorials/PWGLF/Resonance/resonances_step4.cxx, Tutorials/PWGLF/Resonance/resonances_step5.cxx, Tutorials/PWGLF/Resonance/resonances_step6.cxx
* `resonance_step3.cxx` Starting point for MC: loop over all Generated MC particles
* `resonance_step4.cxx` Producing histograms (pt distributions etc.) for Generated MCs
* `resonance_step5.cxx` Loop over all MC Tracks and produce basic QA histograms
* `resonance_step6.cxx` Resonance reconstruction
=> [PWGLF] Add Resonance Tutorials

PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
Followup on https://github.com/AliceO2Group/O2Physics/pull/7950
=> PWGHF: Use PDG name for Ds*

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: add a cut to ITS cluster size for hadron rejection
=> PWGEM/Dilepton: add a cut to ITS cluster size for hadron rejection

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: add protection against double counting of generated info
=> PWGEM/Dilepton: add protection against double counting of generated info

PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
adding event selections in PbPb
fixing minor bugs
=> [PWGLF] adding event selections in PbPb

PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx, Tutorials/ML/applyMlSelection.cxx, Tutorials/ML/dpl-config_applyMlSelection.json
Hi @fmazzasc @fcatalan92 I made some minor changes in the skeleton code and updated the dpl configuration to run the example
=> [ML]: update tutorial code and configuration

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Added the scalar product v1calculations to compare with RUN1 results as suggested by FLOW PAG.
=> PWGLF: added v1 calculations for ZDC Callibration

PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx, Tutorials/PWGCF/EventPlane/CMakeLists.txt, Tutorials/PWGCF/EventPlane/README.md, Tutorials/PWGCF/EventPlane/doc/README.md, Tutorials/PWGCF/EventPlane/src/CMakeLists.txt, Tutorials/PWGCF/EventPlane/src/qVectorstutorial.cxx
initial commit of tutorial code for event plane
=> [PWGCF] initial commit of tutorial code for event plane

DPG/Tasks/AOTTrack/qaImpPar.cxx
@phymanshu here the fixes that we discussed in the morning:
- `customITShitmap_exclude` new Configurable ITS hitmap were to indicate the layers to be excluded (beware: (1) always on top of the ITS hit selections imposed by `trackSelection`; (2) always with binary representation, similarly to the already existing `customITShitmap`)
- fix the initialization of THnSparses for pions, kaons and protons
I tested it locally, and all seems to work
=> DPG/AOT: add exclusion ITS hitmap and fix PID sparse creation.

PWGHF/Core/HfMlResponseB0ToDPi.h, PWGHF/Core/HfMlResponseBplusToD0Pi.h, PWGHF/Core/HfMlResponseBsToDsPi.h, PWGHF/Core/SelectorCuts.h, PWGHF/D2H/TableProducer/CMakeLists.txt, PWGHF/D2H/TableProducer/candidateCreatorBsReduced.cxx, PWGHF/D2H/TableProducer/candidateSelectorBplusToD0PiReduced.cxx, PWGHF/D2H/TableProducer/candidateSelectorBsToDsPiReduced.cxx, PWGHF/D2H/Tasks/CMakeLists.txt, PWGHF/D2H/Tasks/taskBplusReduced.cxx, PWGHF/D2H/Tasks/taskBsReduced.cxx, PWGHF/D2H/Utils/utilsRedDataFormat.h, PWGHF/TableProducer/candidateCreatorBs.cxx, PWGHF/TableProducer/candidateSelectorBsToDsPi.cxx, PWGHF/Utils/utilsEvSelHf.h
@fchinu @AlexBigO @apalasciano I made a couple of simplifications and fixes also for B0 and B+, please have a look
=> PWGHF: Add Bs candidate creator, selector, and task for reduced data format

PWGLF/Tasks/Resonances/k1analysis.cxx
1. Fix bug for MC process - remove "hTrueK1pt" filling
2. Remove unused QA histograms
=> PWGLF: Clean unused histograms

PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
add filtering to events and tracks
=> [PWGLF] add filtering to events and tracks

PWGHF/D2H/Tasks/taskD0.cxx
Prompt BDT score axis added for studying the performance of selection based on prompt score
=> PWGHF: add THn axis for prompt BDT score in D0 task

PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: update eventQC
=> PWGEM/Dilepton: update eventQC

Common/TableProducer/eventSelection.cxx
Reverts AliceO2Group/O2Physics#8044
=> Revert "Common/EventSelection: switch back to aod::Tracks subscription for Run2"

PWGMM/Mult/Tasks/heavy-ion-mult.cxx
Bug fixes in "processStrangeYield" process function
=> PWGMM/Mult/Tasks/heavy-ion-mult.cxx: Bug fixes 

PWGEM/Dilepton/Core/Dilepton.h
PWGEM/Dilepton: minor change in histogram
=> PWGEM/Dilepton: minor change in histogram

Common/TableProducer/eventSelection.cxx
=> Common: fix Run 2 evSel

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update ITS cluster size cut
=> PWGEM/Dilepton: update ITS cluster size cut

PWGUD/Tasks/upcRhoAnalysis.cxx
Small updates to personal task - code cleanup, addition of control histograms + track selection histogram.
=> PWGUD: updates to upcRhoAnalysis.cxx

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* Cleanup of unused configurables.
* New checks.
* Addition of upc flag option.
* Addition of new track cuts.
* Addition of SG process.
* Addition of charge ordering.
=> PWGUD: personal changes in code and code cleanup

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: revert ITS cluster size cut
=> PWGEM/Dilepton: revert ITS cluster size cut

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Corrected a bug for azimuthal angle of particles for calculation of v1{ZDC}
=> PWGLF: corrected a bug for azimuthal angle calculation of particles

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
Increase the range of the DCA axis from 10 to 20 sigma
=> [PWGEM] Single track QC: Increase range of DCA axis

CODEOWNERS
Actually in this case I do not know what label I should put (suggestions appreciated, of course :-) )
=> Update JE codeowners

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: add flexibility to apply asymmetric zvtx cut
=> PWGEM/Dilepton: add flexibility to apply asymmetric zvtx cut

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
added QA plots for v1 cross check
=> PWGLF: added more QA plots for cross check with published

PWGDQ/Tasks/CMakeLists.txt, PWGDQ/Tasks/taskFwdTrackPid.cxx
- Adding task to do Fwd tracks PID
- The old task in tableReader will be deleted once the new one is tested
=> [PWGDQ] Adding task to do Fwd tracks PID

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
adding lambda vn histograms for QA
=> [PWG:LF] adding lambda vn histograms for QA

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
continuing different checks for v1 calculation to validate ZDC in RUN3
=> PWGLF: added SP method for v1 and 2D histogram of Q vs cent for validating ZDC callibration

PWGHF/D2H/Tasks/taskLc.cxx
To make the centrality differential analysis more convenient for offline process
=> PWGHF: Add centrality (FT0C as default) in Lc task

PWGMM/Mult/Tasks/heavy-ion-mult.cxx
The following changes are made in the code:
1) Merge `THnSparse::hdatadndetaOccupancy + THnSparse::hdatadndeta` into one `THnSparse::hdatadndeta`
2) Add occupancy cut in MC reconstructed level
3) Add TPCNCls cut and PID selection cuts in the process function `processStrangeYield`
=> PWGMM/Mult/Tasks/heavy-ion-mult.cxx: Add occupancy cut MC reco level

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
- added process functions to run MC for V0-V0 pairs
=> PWGCF: FemtoUniverse track-V0 task -- added MC process functions for V0-V0 pairs

PWGHF/D2H/Tasks/taskXic.cxx
- Add prompt/non-prompt directory structure in MC reco and gen histogram directories
=> PWGHF: Add histograms directories to Xic task

PWGUD/Tasks/sgTwoPiAnalyzer.cxx
=> [PWGUD] Two-pi analyzer task output AO2D added

PWGDQ/Tasks/tableReader.cxx, PWGDQ/Tasks/taskFwdTrackPid.cxx
Removing useless part to the PID task
=> [PWGDQ] Removing useless part to the PID task

PWGJE/Tasks/jetfinderQA.cxx, PWGJE/Tasks/jetfinderfullQA.cxx, PWGJE/Tasks/jetfinderhfQA.cxx
- Add histogram to check matched jet response for different outlier cuts
- make exponent variable in these checks
- fix binning ranges
=> checks on outlier cut for matched jets

PWGJE/Tasks/jetSpectraEseTask.cxx
I've added process function for matched part and det MC to create the response matrix, and also a process function to fill jet pt to create efficiencies.
=> [PWGJE] Add efficiency and response matrix (MC)

CODEOWNERS
=> Update CODEOWNERS as per PWG-CF convener request

PWGHF/Tasks/taskMcValidation.cxx
This PR adjusts the centrality histograms' binning and the centrality's initialization value.
=> PWGHF: Adjust histos in mc validation task

PWGLF/DataModel/SPCalibrationTables.h, PWGLF/TableProducer/Common/spvector.cxx, PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Checks for ZDC callibration for polarisation study ongoing
=> PWGLF: Added more variables for derived data table and flag to use global vs tpc momentum

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] adding occupancy selection

PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR enables the possibility to turn off EP-related axes to reduce thnsparse size. (@wuctlby for your information)
=> PWGHF: Turn off EP-related axes in flow thnsparse

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
=> [PWGLF] adding QA histogram

PWGLF/TableProducer/Nuspex/threebodyRecoTask.cxx, PWGLF/Tasks/Nuspex/hypertriton3bodyanalysis.cxx
Add reconstruction process of like-sign background in threebodyRecoTask
Small updates for 3body decay analysis
=> PWGLF: Add like-sign reconstruction for hypertriton 3body analysis

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGEM/Dilepton/Tasks/MCtemplates.cxx
Additionally it  is adding a cut setting to do a comparison between DQ and EM framework
=> [PWGDQ] add TPCnCRoverFindCls as variable 

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx
- variable name for cosine of the pointing angle in VarManager.cxx
- histograms for applying cuts on triplet candidates in dilepton-track:multidimentional-vertexing-histograms in HistogramsLibrary.cxx. 
The histograms were added to do multidimentional cuts in the B→ J/psi + K analysis of Jpsi2EE PAG
=> [PWGDQ-120] added multidimentional histogram in dilepton-track (HistogramLibrary.cxx)

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: add possibility to use DCAz
=> PWGEM/Dilepton: add possibility to use DCAz

PWGDQ/Core/HistogramsLibrary.cxx
I have removed the multiplicity bins for polarization analysis and added the rapidity one. Since the multiplicity selection is not clear at this moment
=> [PWGDQ] Update HistogramsLibrary.cxx

EventFiltering/macros/checkBCrangesSkimming.C
Fix a bug which might cause unexpected matches of skimmed singles and original multiplies
Small updates on naming and comments
=> [Trigger] EventFiltering: Update trigger QA of BCId compatibility

PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Hi @fgrosa @fcatalan92,
In this PR, I added a THnSparse to store BDTScore with Invariant mass, pT and Centrality.
Could you please look into this and let me know if there are any suggestions.
Thanks.
=> [PWGHF/D2H] Added THnSparse for Invariant mass vs BDT score

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
changes necessary for track merging studies
=> [PWGLF] Changes in hStrangeCorrelation.cxx

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/EMEventCut.cxx, PWGEM/Dilepton/Core/EMEventCut.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/Dilepton/Tasks/tableReaderBarrel.cxx, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Tasks/vpPairQCMC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx, PWGEM/PhotonMeson/Tasks/emcalQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
PWGEM/Dilepton: add possibility to select FT0C occupancy
=> [PWGEM/Dilepton] add possibility to select FT0C occupancy

PWGLF/Tasks/Resonances/KshortKshort.cxx, PWGLF/Tasks/Resonances/k892analysis.cxx
Added occupancy cuts
Codes modified:
KshortKshort.cxx
k892analysis.cxx
=> [PWGLF] Added occupancy cuts

PWGLF/Tasks/Resonances/kstarpbpb.cxx
modify PID selection for only TOF study
=> [PWGLF] : modified PID selection for only TOF study

PWGLF/Tasks/Strangeness/v0ptinvmassplots.cxx
Added some configurables for the plot so it can be adjusted depending on the Pt range
Added some cuts/filters: zvertex, rapidity and IsPrimary().
=> [PWGLF] PWGLF:v0ptinvmassplots Updated the Generated Pt Spectrum Process

PWGLF/TableProducer/Common/spvector.cxx, PWGLF/Tasks/Strangeness/lambdapolsp.cxx
=> [PWGLF] added Sumw2 in TProfiles and changed float to double and switch coordinates

PWGUD/Tasks/upcRhoAnalysis.cxx
Changes to personal task for UPC rho analysis. Changes to track ordering in 2D histograms, extension of track quality selections, roll-back to TLorentzVector.
=> [PWGUD] changes to upcRhoAnalysis.cxx

PWGJE/TableProducer/emcalCorrectionTask.cxx
- Added a histogram to check the timeresolution distribution of collisions that are mapped to only one BC. Depending on how this looks we might want to do further studies and even cut on the timeresolution.
- Changed all histograms of integer type to double to ensure we have no integer limitations as we have seen before for the `hBC` histo
- Removed `hasPropagatedTracks` config, since we no longer need it. It was only needed for the very first reconstructions which no longer exist.
=> [EMCAL-670] emcalCorrectionTask - add time resolution histogram

PWGCF/Flow/Tasks/FlowZDCtask.cxx
=> [PWGCF] Updated neutron skin process in FlowZDCtask.cxx

PWGCF/FemtoUniverse/Core/FemtoUniversePairSHCentMultKt.h
In this PR, I reduced the numbers of dimensions of the sets of TH1 and TH3 histograms, which should reduce the memory usage while running the code.
=> [PWGCF] FemtoUniverse: Reducing number of arrays in sets of TH1 and TH3

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: update chi2 TOF histogram
=> [PWGEM/Dilepton] update chi2 TOF histogram

PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Hi @fgrosa!
Just fixed typos on name of hist axes.
=> [PWGHF/D2H] fixing typos in axes name

PWGJE/Tasks/nucleiInJets.cxx
Hi @nzardosh,
Could you please approve the PR once all the tests are passed?
Have a nice day.
Arvind
=> [PWGJE] Functionality to use TPC custom parameters

PWGHF/HFC/DataModel/DerivedDataCorrelationTables.h, PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I modified the table names in the DataModel to address an error with unbound indices. Let me know for any comments or suggestions.
Cheers,
Samuele
=> [PWGHF] Ds-h correlation derived data - correction table names

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack3DMultKtExtended.cxx
In this PR, I replace MutlNtr with MultV0M in colBinning for event mixing.
=> [PWGCF] FemtoUniverse: Replacing MutlNtr with MultV0M in colBinning

PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/EMEventCut.cxx, PWGEM/Dilepton/Core/EMEventCut.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Tasks/vpPairQCMC.cxx
PWGEM/Dilepton: add possibility to select kNollInRof
=> [PWGEM/Dilepton] add possibility to select kNollInRof

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
configurables for switching between different histograms
=> [PWGLF] added configurable axis and configurables to switch between different type of histograms

PWGUD/DataModel/SGTables.h, PWGUD/Tasks/CMakeLists.txt, PWGUD/Tasks/sgPIDAnalyzer.cxx, PWGUD/Tasks/sgPIDSpectraTable.cxx
changing output to reduced derived data and adding a task that produces TOF sigma output
=> [PWGUD] Update on personal PID Spectra analyzer

PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
adding new event selection + sorting of configurables
=> [PWGLF] Change in derivedcascadeanalysis.cxx

PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
I included an invariant mass histogram without efficiency in the correlation task for debugging.
=> [PWGHF] Histogram  w/o efficiency included in the task for debugging

PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
Added option to choose the momentum getter,
deleted unused code + other optimisations
=> [PWGLF] Update NucleiHistTask.cxx

PWGUD/Tasks/sgPIDAnalyzer.cxx
=> [PWGUD] Update sgPIDAnalyzer.cxx

ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
To be changed back once AliceO2Group/AliceO2#13617 is merged
=> [ALICE3] Produce versioned StoredTrackExtra table for the time being

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* Bug fixes.
* Additional plots for track quality selections.
* ZDC classes.
=> [PWGUD] changes to eprsonal task

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: add possibility to select AC combination
=> [PWGEM/Dilepton] add possibility to select AC combination

PWGHF/D2H/Tasks/taskLc.cxx
This pr maybe can fix the issue of CPU consumption when run the task using real data
=> [PWGHF] taskLc: Remove track loop in the fill histogram function of data

PWGLF/Tasks/Strangeness/lambdak0sflattenicity.cxx
In this version of PR, I have added new histograms that are useful to calculate event and signal correction factors.
=> [PWGLF] Histograms added for event and signal corrections

PWGUD/DataModel/UDTables.h, PWGUD/TableProducer/SGCandProducer.cxx
De, Tr, He, Al for LF studies.
=> [PWGUD] PID Extra information added to Single Gap Events

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx, PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx, PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton: add v2 in LF cocktail
PWGEM/Dilepton: minor fix to histogram path
implement deta-dphi cut in LF and HF cocktail
=> [PWGEM/Dilepton] add v2 in LF cocktail

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Tasks/vpPairQC.cxx
PWGEM/Dilepton: add constant phiv cut
=> [PWGEM/Dilepton] add constant phiv cut

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Cleaned up the code and replaced TProfile resolution with THnSparse
=> [PWGLF] replaced TProfile with ThnSparse and cleaned up the code

PWGJE/Tasks/jetSpectraEseTask.cxx
Added histograms for calculating event plane resolution using 3-sub events for several detectors.
=> [PWGJE] EP resolution+histograms

PWGJE/TableProducer/emcalCorrectionTask.cxx
- A shift in the cluster time was observed, caused by the tof to the EMCal surface.
- Discussed in https://indico.cern.ch/event/1469237/
- Two options are implemented:
- Case 1: Constant shift of 15ns
- Case 2: Eta dependent shift. Based on the lenght from vertex to the specific cell If applyCellTimeShift is set to 0, no shift is applied.
=> PWGJE/EMCal: Add option to shift cluster time in MC

PWGLF/Tasks/Resonances/kstarpbpb.cxx
added different PID strategy for better PID selection
=> [PWGLF] added different PID strategy

PWGCF/TwoParticleCorrelations/Tasks/lambdaR2Correlation.cxx
Added ccdb service to read correction factors from TH3F histograms 
Added new TH3F histograms to compute pT, eta, posZ dependent efficiencies
=> [PWGCF] Update lambdaR2Correlation.cxx

PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/k892analysis_PbPb.cxx, PWGLF/Tasks/Resonances/kstar892analysis.cxx
- Adding new task k892analysis_PbPb.cxx not using ResonanceInitializer
- fixing pdgcode check in kstar892analysis.cxx
=> [PWGLF] K*(892) PbPb: new task without ResonanceInitializer

PWGLF/Tasks/Resonances/highmasslambda.cxx, PWGLF/Tasks/Resonances/phipbpb.cxx
code clean up, add TOF Beta cut, Improved PID selection, optimized and update histogram bin and entries
=> [PWGLF] code clean up resonance flow and PID improvement

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Removing several histograms to reduce memory usage in hyperloop
=> [PWGLF] added configurable for reducing no. of defined histograms for memory usage

PWGDQ/Core/MCSignalLibrary.cxx
=> [PWGDQ] Adding Upsilon MC signals

PWGDQ/Tasks/taskFwdTrackPid.cxx
This PR adds the possibility of sampling tracks when studying mfttracks. @lucamicheletti93  for your information.
=> [PWGDQ] Adding downsample in fwd pid task

PWGJE/Tasks/PhotonIsolationQA.cxx
For MC data the collision weights are now processed
=> [PWGJE] Updated PhotonIsolation.QA

PWGHF/D2H/Tasks/CMakeLists.txt, PWGHF/D2H/Tasks/taskDirectedFlowCharmHadrons.cxx
code for analysis of directed flow of D mesons
=> [PWGHF] code for v1 of D mesons using SP

PWGLF/Tasks/Strangeness/v0topologicalcuts.cxx
variable number of histos according to config
=> [PWGLF] V0dev

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
Request: https://github.com/AliceO2Group/O2Physics/pull/7466#issuecomment-2465400726
=> [PWGCF] FemtoUniverse -- Fixing MC truth task as requested by Vit Kucera

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: update track propagation
=> [PWGEM/Dilepton] update track propagation

PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/TableProducer/tableMakerMC.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx
Fixing issue with updated ambiguous tables
=> [PWGDQ] Fixing issue with updated ambiguous tables

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
fix  bug for wrong v0 selection
=> [PWGLF] Fix V0 DCA cut in Lambda polarisation task

PWGLF/Tasks/Resonances/kstarpbpb.cxx, PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
Phi task : clean up , efficiency check, different PID check, occupancy for MC.
K*0 task : clean up and PID check
=> [PWGLF] Optimized phi and kstar resonance task

PWGLF/Tasks/Strangeness/lambdapolsp.cxx
added DCA V0 to PV and no. of TPC crossed row selection cuts
=> [PWGLF] added DCAV0toPV and TPCcrossed row cuts

PWGLF/Tasks/Strangeness/phik0sanalysis.cxx
- New track and PID selection for phi
- Changed histograms filling for efficiencies
- Removed unused mixed event
- Minor changes
=> [PWGLF] New track and PID selection for phi in phik0sanalysis.cxx
