- PWGLF/Tasks/Resonances/lambda1520analysis.cxx
Added Rotational Background technique for invariant mass distribution
> [PWGLF] Added Rotational Background

- PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
charge dependent trigger particle for MC gen
> [PWGLF] Change in hStrangeCorrelation.cxx

- PWGJE/Tasks/PhotonIsolationQA.cxx
I added an energy dimension to one histogram
> [PWGJE] Update PhotonIsolationQA.cxx

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/TableProducer/tableMakerMC.cxx
- PWGDQ/Tasks/taskFwdTrackPid.cxx
Adding code to process MC events in Fwd PID task
> [PWGDQ] Adding code to process MC events in Fwd PID task

- PWGLF/DataModel/LFhe3HadronTables.h
- PWGLF/TableProducer/Nuspex/he3HadronFemto.cxx
- Added collision id  and z vertex position in multiplicity table for offline event mixing
- Fixed name of the unlike-sign flag in the table
- Fixed a bug in tof selection 
- Fixed a bug to store the correct signed pt of protons in unlike-sign background
> [PWGLF] pwglf: table addition and bug fixes

- PWGHF/D2H/Tasks/taskBplus.cxx
- PWGHF/DataModel/DerivedTables.h
- PWGHF/TableProducer/CMakeLists.txt
- PWGHF/TableProducer/candidateCreatorBplus.cxx
- PWGHF/TableProducer/derivedDataCreatorBplusToD0Pi.cxx
- PWGHF/TableProducer/derivedDataCreatorD0ToKPi.cxx
- PWGHF/TableProducer/derivedDataCreatorLcToPKPi.cxx
- PWGHF/Utils/utilsDerivedData.h
- PWGHF/Utils/utilsPid.h
FYI: @nzardosh @qgp @DelloStritto
> [PWGHF] Add self-contained derived-data format for B+

- CODEOWNERS
@catalinristea, @noferini @alcaliva , FYI.
I don't know but it seems Catalin is not recognized, @ktf , @singiamtel , can you please check?
> [Infrastructure] Update of DPG coordinators

- PWGHF/D2H/Tasks/taskDirectedFlowCharmHadrons.cxx
added few histograms for direct v1 odd and even calculation and a boolean to reduce the no. of histograms in output root file
> [PWGHF] added flag and histograms for direct v1 calculation for cross check

- PWGHF/HFC/Tasks/taskCharmHadronsFemtoDream.cxx
- fix the bug of mix-event setting
- implement the option to select momentum type of the track QA plots
> [PWGHF] fix the bug of mix-event setting and complete the track QA plots

- Common/Core/RecoDecay.h
- PWGJE/Core/JetTaggingUtilities.h
To use jet-flavour definition from jet group
Modification of problem about initialize for track and particle
> [Common,PWGJE] Add getParticleOrigin and modified init problem

- PWGDQ/Core/HistogramsLibrary.cxx
Binning of  Psi2A_FT0C, Psi2B_FT0C, and Psi2C_FT0C histograms changed from 18 to 90.
> [PWGDQ] Change of binning of  Psi_FT0C Histograms for DQ Flow

- PWGHF/D2H/Tasks/taskDirectedFlowCharmHadrons.cxx
Hi @adubla, Here is the commit for D0 v1. Thanks, @prottayCMT, for creating the task! I’ve also extended the BDT score to include the prompt in addition to adding the D0 case, as we sometimes need this control to achieve results with a high prompt fraction.
Let me know if you have any feedback! Thanks!
> [PWGHF] add the v1 for D0

- PWGLF/Tasks/Nuspex/nuclei_in_jets.cxx
@alcaliva this should help with the event normalization
> [PWGLF] Add QC histo for event selection

- PWGJE/Tasks/jetchargedv2.cxx
jetchargedv2.cxx
1. fix problems of charged jet v2 filling issues
2. add QA plots
> [PWGJE] fix charged jet v2 in-plane and out-of-plane filling issue

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
This PR adds the centrality and occupancy information in the efficiency task for qa
> [DPG] Add occupancy information in qa efficiency task

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/tableReader.cxx
- PWGDQ/Tasks/tableReader_withAssoc.cxx
- PWGEM/Dilepton/Tasks/tableReaderBarrel.cxx
- Resolution factors provide by event-level task will be uploaded to CCDB and then read by Same-Event/Event-Mixing task in table-reader for flow analysis
- Some news QA histograms/profiles added
> [PWGDQ,PWGEM] Completion of flow calculation with on-the-flight resolution factors

- PWGCF/TableProducer/filterCorrelations.cxx
Adding the possibility filter 2 particle correlations using a cut in multiplicity to enhance the sample at large multiplicity values.
> [PWGCF] Updating to allow for a minimum cut value in multiplicity

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
adding configurable for PV selection variation
> [PWGLF] adding configurable for PV selection variation

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- added clean pair check for cascade pair building from same and mixed events
- other minor fixes
> [PWGCF] FemtoUniverse cascade task -- applied clean pair check for cascade pair building

- PWGLF/Tasks/Strangeness/lambdak0sflattenicity.cxx
Several of the histograms were limited by the maximum bin content provided by the histogram type. Thus, in this version of PR, I have changed TH1I and TH1F to TH1D.
> [PWGLF] Fix maximum bin content reached in histograms

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
PWGEM/Dilepton: first version of prefilter to reject photon conversion
> [PWGEM/Dilepton] first version of prefilter to reject photon conversion

- PWGUD/Core/UPCJpsiCentralBarrelCorrHelper.h
- PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
* Personal code changes (plot addition).
* Deletion of unused functions.
* First addition of MC process function.
> [PWGUD] addition of MC and code cleanup

- PWGCF/TableProducer/filterCorrelations.cxx
adding configurable for occupancy selection range
> [PWGCF] adding configurable for occupancy selection range

- PWGHF/D2H/Tasks/taskBplusReduced.cxx
Following modifications introduced in PR #8537
> [PWGHF] Add single track variables in B+ reduced task

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationLcHadrons.cxx
1. Add efficiency weight both for Lc and Hadron on taskCorrelation
2. Modification for the method to getdaughters( the old one is not able to run now)
> [PWGHF] modification for efficiency weight

- PWGJE/Tasks/ChJetTriggerQATask.cxx
This histogram is needed as a part of high pT tracks QA
> [PWGJE] Add histogram with q/pT vs phi for tracks

- PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add energy-dependent smearing of the cell time to MC to better describe data
- Change configurable from int to boolean for simplicity for the analyzer (includes shift and smearing)
- Add histogram for (corrected) cell time vs energy
- Fix the row/column range of the respective histogram
> [PWGJE] [PWGJE]Add cell time smearing in MC

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
change lambda mass to anti-lambda mass
> [PWGLF] change lambda mass to anti-lambda mass

- PWGHF/D2H/Tasks/taskXicToXiPiPi.cxx
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx
- PWGHF/TableProducer/candidateSelectorXicToXiPiPi.cxx
- PWGHF/TableProducer/treeCreatorXicToXiPiPi.cxx
@creetz16 @JaeYoonCHO 
- Add PID information of final state particles to output tree tables
- Remove unused vertices from candidate table and output tree tables
- Fix update of daughter tracks at PCA of the secondary vertex
- Fix PV residual/pull calculation
- Add counter histogram to candidate creator
- Small improvements to histogram task
> [PWGHF] Update XicToXiPiPi workflow

- PWGHF/TableProducer/mcPidTof.cxx
`PWGHF/TableProducer/mcPidTof.cxx` aligned to `Common/TableProducer/PID/pidTOFMerge.cxx` as in PR #8616 .
BEWARE: a similar operation will be probably needed as soon as PR #8692 will be merged.
> [PWGHF] align mcPidTof with pidTofMerge as in PR 8616.

- PWGCF/JCorran/Tasks/CMakeLists.txt
- PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
- PWGCF/TableProducer/filterCorrelations.cxx
initial commit for d0 flow with EP
> [PWGCF] initial commit for d0 flow with EP

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/dptdptcorrelations.cxx
- PWGCF/Tasks/match-reco-gen.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also fixing a few linter errors on the table producer
> [PWGCF] DptDpt - Improved event selection tracking

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
Add MotherPDG Histogra(Xi and Lambda)
> [DPG] Update qaEfficiency.cxx

- PWGCF/JCorran/Tasks/jEPDzeroFlowAnalysis.cxx
> [PWGCF] fix duplicated histograms

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
1. Defined new column in namespace
2. Added this column to BmesonCandidates table declared in namespace
3. Filled this column with mcDecision in BmesonsTable() within AnalysisDileptonTrack()
> [PWGDQ] [PWG-DQ-120] added mcDecision to B meson candidate table

- PWGCF/Flow/Tasks/FlowGFWPbPb.cxx
- PWGCF/Flow/Tasks/flowGFWOmegaXi.cxx
Add and change some cuts for event selection and topological cut
Add switch of daughter TOF and TPC check
Add V0 cuts QA
Add uncertainties using Jackknife method (10 sub-samples)
> [PWGCF] add topological cut QA and flow uncertainties

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/EMEventCut.cxx
- PWGEM/Dilepton/Core/EMEventCut.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
- PWGEM/Dilepton/Tasks/vpPairQC.cxx
- PWGEM/Dilepton/Tasks/vpPairQCMC.cxx
- PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: update prefiter task and phiv sorted by pT
> [PWGEM/Dilepton] update prefiter task and phiv sorted by pT

- PWGHF/D2H/Tasks/taskDirectedFlowCharmHadrons.cxx
Added a boolean for using rapidity for proper comparison and corrected trigger condition based on header macro
> [PWGHF] added rapidity flag and corrected trigger condition

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/match-reco-gen.cxx
- PWGCF/TwoParticleCorrelations/Tasks/efficiencyAndQc.cxx
Also getting rid of the use of `TDatabasePDG`
> [PWGCF] DptDpt - Splitting the PID QC information

- Common/Tasks/centralityStudy.cxx
> [Common] centrality study update

- PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
PWGEM/Dilepton: update prefilter task for geom cut in ULS
> [PWGEM/Dilepton] update prefilter task for geom cut in ULS

- PWGHF/TableProducer/mcPidTof.cxx
- PWGLF/Tasks/Nuspex/NucleiHistTask.cxx
Added ability to recenter TPC track (track-by-track) using a TF1 (configurable)
Fixed sign error for recentering using TF1
> [PWGLF] Update NucleiHistTask

- PWGLF/Tasks/Nuspex/spectraTOF.cxx
Detailed study of TPC and TOF spectra as a function of occupancy
> [PWGLF] PWGLF/Tasks/Nuspex/spectraTOF.cxx

- PWGLF/TableProducer/Common/spvector.cxx
updated callibration with shift correction
> [PWGLF] added shift callibration

- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
PID and occupancy checks for MC
> [PWGLF] occupancy checks for MC

- PWGUD/Tasks/upcRhoAnalysis.cxx
Addition of histograms for QA.
> [PWGUD] updates to upcRhoAnalysis.cxx

- .github/workflows/o2-linter.yml
Currently it fails the check without files
CC @vkucera
> [Infrastructure] Don't try to lint when no files are found

- PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add parameters for MC broadening for LG and HG cells, as well as data shift for LG and HG cells
- Made the EMCalCorrectionTask o2linter compliant
> [PWGJE,EMCAL-670] Add LG cell time correction parameters

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.h
Reverts AliceO2Group/O2Physics#8813
> [PWGDQ] Revert "[PWGDQ] Adding Tprofiles with Cumulants weights + fixing Pi constant …"

- PWGJE/Tasks/trackJetQA.cxx
Hi @nzardosh,
this is a mini fix of the axis range for the track snp distribution.
This can be directly merged as nothing else but a deleted 0 changed.
Many thanks in advance !
> [PWGJE] fix snp binning trackJetQA.cxx

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.h
Adding  Tprofiles with M11, M11etagap and M1111 as function of centrality + adding math constants from O2 CommonConstants
> [PWGDQ] Adding TProfile with cumulants weights + PI constants correctly

- PWGHF/TableProducer/derivedDataCreatorBplusToD0Pi.cxx
> [PWGHF] Remove unnecessary subscriptions from B+ derived data creator

- PWGLF/Tasks/Resonances/lambdav2.cxx
- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
checking possible misidentification of particle and antiparticles along with other particles flow
> [PWGLF] added checks for misidentification of particle with antiparticle and comparison with other particles

- Common/Core/RecoDecay.h
Add support for the customisation of the angle periodicity.
Used in flow analyses for harmonics.
> [Common] RecoDecay::constrainAngle: Support harmonics

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
PWGEM/Dilepton: update prefilter task
> [PWGEM/Dilepton] update prefilter task

- PWGHF/D2H/Tasks/taskDirectedFlowCharmHadrons.cxx
Lower order cumulant corrections
> [PWGHF] added cumulant corrections for flow

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
PWGEM/Dilepton: update createResolutionMap.cxx
> [PWGEM/Dilepton] update createResolutionMap.cxx

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
Add the histo to cal. the decaylength of the mother particle
> [DPG] Add the histo to cal. the decaylength of the mother particle

- PWGCF/Tasks/correlations.cxx
adding ddbar histograms for normalization
separating useraxis for the same and mixing containers
> [PWGCF] adding ddbar mass histograms for normalization

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
updated code to reduce misidentification of particles and antiparticles
> [PWGLF] added flags for TOF cuts and v0 to fourvector kinematics along with lower order cumulant corrections for charged particles

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/chk892flow.cxx
- PWGLF/Utils/collisionCuts.h
chk892flow.cxx : Fill histograms (QA, THnSparse) for charged K(892) flow analysis 
CMakeLists.txt : Add chk892flow analysis
collisionCuts.h : Some changes on cuts from Bong-Hwi
> [PWGLF] Charged K(892) flow analysis fill histograms

- PWGUD/Tasks/upcRhoAnalysis.cxx
Added a function to check the number of collision reconstructions between MC/reco data for MC QA.
> [PWGUD] QA updates to upcRhoAnalysis.cxx

- PWGJE/DataModel/EMCALClusterDefinition.h
- PWGJE/DataModel/EMCALClusters.h
- PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add the time difference allowed between the seed cell and aggregation cells to be added to a cluster to the struct of the ClusterDefinition
- Added 500, 100 and 50 ns time diff definitions as varaitions for kV3Default and kV3MostSplit
> [PWGJE,EMCAL-670] Add time differences into the clusterdefinition

- PWGLF/Tasks/Strangeness/CMakeLists.txt
- PWGLF/Tasks/Strangeness/lambdalambda.cxx
- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
initial commit for v0v0 reconstruction
> [PWGLF] initial commit for v0v0 reconstruction

- PWGLF/Tasks/Resonances/k892analysis_PbPb.cxx
In k892analysis_PbPb.cxx
- modified some selections
- fixed bugs in ProcessMixedEvent()
> [PWGLF] Fixing bugs in K*0 analysis in PbPb

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
Replaced the boost daughter of protons
> [PWGLF] Boosting daughter with v0 momentum

- PWGCF/Flow/TableProducer/zdcQVectors.cxx
- PWGCF/Flow/Tasks/flowSP.cxx
+ change functions in flow task to get right averages in (eta,pt,cent) bins
> [PWGCF] Fill registry only when events are selected

- PWGCF/Flow/Tasks/pidcme.cxx
add self correlation terms for pikp cme signal and bkg
> [PWGCF] add self corr

- PWGLF/Tasks/Nuspex/AngularCorrelationsInJets.cxx
> [PWGLF] added configurable selections and new histos

- PWGDQ/TableProducer/tableMaker.cxx
Create a table not to include TOF-Beta and muon PID
> [PWGDQ] Create a table with only standard PID information

- Common/TableProducer/Converters/trackQA002Converter.cxx
Fixes https://github.com/AliceO2Group/O2Physics/pull/8901
> [Common] Fix the bug -PR8901

- PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h
- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- added process functions for cascade - cascade pair same and mixed events
- fixed typos and added comments
> [PWGCF] FemtoUniverse cascade task -- added process functions for cascade - cascade correlation

- PWGEM/PhotonMeson/Tasks/emcalQC.cxx
- Implemented bugfix for "abs-bug" reported by Vit via the o2linter (https://github.com/AliceO2Group/O2Physics/pull/8942)
> [PWGEM/PhotonMeson] Fix abs in emcalQC task

- PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
- Add cut on edge clusters for SE distribution to match acceptance between SE and rotation background
> [PWGEM] [PWGEM-36] Cut on edge clusters for neutral meson flow

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
removing TOF tables for particle identification
> [PWGLF] removed TOF tables due to memory consumption in Hyperloop

- PWGDQ/Core/VarManager.h
Handling correlators and weights (Corr and M) as paired values in the validation checks.
> [PWGDQ] Adding correct Flow checks

- PWGUD/DataModel/SGTables.h
- PWGUD/DataModel/UDTables.h
- PWGUD/TableProducer/CMakeLists.txt
- PWGUD/TableProducer/Converters/CMakeLists.txt
- PWGUD/TableProducer/Converters/UDCollisionSelExtrasConverter.cxx
- PWGUD/TableProducer/DGCandProducer.cxx
- PWGUD/TableProducer/SGCandProducer.cxx
- PWGUD/TableProducer/UPCCandidateProducer.cxx
- PWGUD/Tasks/sgPIDSpectraTable.cxx
Added to UDCollisionSelExtra Table.
+ Converter created to version 001
+ Change to SGCandProducer to save these values
+ Change to UPCCandProducer to save dummy values for IR and Occupancy.
DGCandProducer was not saving the SelExtras, so I didn't touch it.
> [PWGUD] Data Model Change: IR and Occupancy

- DPG/Tasks/AOTTrack/qaEfficiency.cxx
Redefine the Histogram for the mother
> [DPG] Redefine the Histogram for the mother

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
adding histograms for cumulant calculations
> [PWGLF] adding histograms for cumulant calculations

- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
PWGEM/Dilepton: add cent info in norm table
> [PWGEM/Dilepton] add cent info in norm table

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
> [PWGLF] boosting with four vector mass

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/higherMassResonances.cxx
- PWGLF/Tasks/Resonances/kShortkShort.cxx
- PWGLF/Tasks/Resonances/kstarqa.cxx
"o2-linter: disable=name/o2-workflow"
"o2-linter: disable=name/workflow-file"
> [PWGLF] Added generated and reconstructed MC

- PWGUD/Core/UPCTauCentralBarrelHelperRL.h
- PWGUD/Tasks/upcTauCentralBarrelRL.cxx
> [PWGUD] Update of personal task

- PWGLF/TableProducer/Nuspex/hypKfRecoTask.cxx
Fix a bug in https://github.com/AliceO2Group/O2Physics/pull/9025 from yesterday
> [PWGLF] Bug fix

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
replace event plane v2 with scalar product v2
> [PWGLF] replace event plane v2 with scalar product v2

- PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
because there is a limit of max. 512 histograms in the histogram registry, I took out all DCA histograms for the moment.
> [PWGEM] LF Cocktail: add psi(2S) and upsilon

- CODEOWNERS
> [Infrastructure] Update code owners for AOT-Tracks.

- PWGLF/Tasks/Resonances/higherMassResonances.cxx
Added track candidated in Reconstructed MC
> [PWGLF] Added track candidated in Reconstructed MC

- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
@adubla @Yunfan-Liu @fgrosa @fcolamar @creetz16 @rutuparnarath @pstahlhu @fcatalan92 @mfaggin
> [PWGLF] add path for findable cascades with KF

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
1. -Add LambdaC and Hadron table which will be used for mixed event calculation offline.
> [PWGHF] Add Lc and Hadron table

- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
@apalasciano @zhangbiao-phy this PR adds the vertex reconstruction for all the other B hadron species
> [PWGHF,Trigger] Add vertex reconstruction for all B hadrons in software triggers

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
- PWGEM/Dilepton/Tasks/eventQC.cxx
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
PWGEM/PhotonMeson: add a column for v0leg moved by vdrifter
> [PWGEM/PhotonMeson] add a column for v0leg moved by vdrifter

- PWGLF/Tasks/Resonances/kstarqa.cxx
Fixed memory warnings and added cut to remove fake tracks
> [PWGLF] Fixed memory warnings and added cut to remove fake tracks

- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Tasks/eventQC.cxx
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: add TOF chi2 in QC task
> [PWGEM/Dilepton] add TOF chi2 in QC task

- PWGCF/Core/AnalysisConfigurableCuts.h
- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/Tasks/matchRecoGen.cxx
Also fine tuning relaxed track selection conditions
> [PWGCF] DptDpt - Tracking the fraction of shared TPC clusters

- PWGCF/Tasks/correlations.cxx
adding event mixing with 2prong pair
> [PWGCF] adding event mixing with 2prong pair

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
PWGEM/PhotonMeson: remove unnecessary flag
> [PWGEM/PhotonMeson] remove unnecessary flag

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/kshortlambda.cxx
Added task for higher mass resonances in non identical Vzero pairs (L-Kshort)
> [PWGLF] PWGLF:Added task for higher mass resonances in non identical Vzero pairs

- DPG/Tasks/AOTEvent/detectorOccupancyQa.cxx
added true/false flags for in-ROF and prevROF event selection for occupancy histos
> [DPG] adding checks after ROF occupancy sel.bits

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
- PWGEM/Dilepton/Tasks/eventQC.cxx
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: update event QC task
> [PWGEM/Dilepton] update event QC task

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update norm in dilepton task
> [PWGEM/Dilepton] update norm in dilepton task

- PWGCF/FemtoUniverse/Core/FemtoUniverseAngularContainer.h
- PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h
- PWGCF/FemtoUniverse/Core/FemtoUniverseCutculator.h
- PWGCF/FemtoUniverse/Core/FemtoUniversePhiSelection.h
- PWGCF/FemtoUniverse/Core/FemtoUniverseTrackSelection.h
- PWGCF/FemtoUniverse/Core/FemtoUniverseV0Selection.h
- PWGCF/FemtoUniverse/Core/femtoUtils.h
- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerReducedTask.cxx
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTaskV0Only.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniverseDebugTrack.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniverseDebugV0.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniverseHashTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackNucleus.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrack3DMultKtExtended.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMC.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMcTruth.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackMultKtExtended.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackSpherHarMultKtExtended.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
Fixing O2 linter errors for FemtoDerived.h file
> [PWGCF] FemtoUniverse -- FemtoUniverse.h O2 linter fixes

- PWGLF/TableProducer/Common/spvector.cxx
iterative recentering method added
> [PWGLF] updated code with iterative recentering

- PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: update hbt task
> [PWGEM/Dilepton] update hbt task

- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/Tasks/smearing.cxx
- PWGEM/Dilepton/Utils/MomentumSmearer.h
PWGEM/Dilepton: update 3D smearing
> [PWGEM/Dilepton] update 3D smearing

- PWGLF/Tasks/Strangeness/phik0sanalysis.cxx
- Removed automatic grouping on MCReco to allow proper slicing
- O2 linter fixes
> [PWGLF] Removed automatic grouping on MCReco to allow proper slicing

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
- PWGEM/Dilepton/Tasks/smearing.cxx
- PWGEM/Dilepton/Utils/MomentumSmearer.h
PWGEM/Dilepton: update resolution map vs. centrality
> [PWGEM/Dilepton] update resolution map vs. centrality

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
> [PWGLF] fix PID

- PWGLF/TableProducer/Strangeness/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/hStrangeCorrelationFilter.cxx
- PWGLF/Tasks/Strangeness/CMakeLists.txt
- PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
@lhusova @ChiaraDeMartin95 @kcui1
> [PWGLF] add Zorro to h-str correlations

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
- PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: update prefilter
> [PWGEM/Dilepton] update prefilter

- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: add max pin for pion rejection
> [PWGEM/Dilepton] add max pin for pion rejection

- Common/TableProducer/trackPropagation.cxx
...meant as safety feature only
> [Common] Only load matLUT once, avoid reload when switching runs 

- PWGLF/TableProducer/Common/spvector.cxx
Corrected overwriting of ccdb histograms
> [PWGLF] corrected the histograms being overwritten in subsequent iterations

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding the option to use centrality instead of multiplicity and adding event histograms.
> [PWGCF] FemtoUniverse: Adding centrality and event histograms to track-cascade task

- PWGCF/Flow/Tasks/pidcme.cxx
add PID check and ITSnSigma cuts
> [PWGCF] add ITSnSigmaCut

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
- PWGEM/Dilepton/Utils/MomentumSmearer.h
PWGEM/Dilepton: update smearing task
> [PWGEM/Dilepton] update smearing task

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: remove unnecessary filter
> [PWGEM/Dilepton] remove unnecessary filter

- PWGHF/HFC/DataModel/CorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
Hi @fgrosa , @fcatalan92 , @vkucera 
In this PR, I tried to implement following...
1. Corrected the filling of D* table 
2. Adding some QA histogram to be used for offline postprocessing
Please have a look at it and let me know if any suggestions. Thanks
> [PWGHF/HFC] D*-H correlation: Correcting the filling of D* and hadron table 

- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/jetSpectraCharged.cxx
fix the bugs in processQC function for MC detector level and change the name of matched histograms
> [PWGJE] fix bugs for MCD level in jetSpectraCharged task

- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/Tasks/CMakeLists.txt
- PWGEM/Dilepton/Tasks/associateMCcollision.cxx
- PWGEM/Dilepton/Tasks/smearing.cxx
PWGEM/Dilepton: add a task to associate mc col to rec col
> [PWGEM/Dilepton] add a task to associate mc col to rec col

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
scalar product method added to K*0 flow task
> [PWGLF] added scalar product method

- PWGCF/Flow/Tasks/flowAnalysisGF.cxx
- PWGCF/GenericFramework/Core/FlowPtContainer.cxx
- PWGCF/GenericFramework/Core/FlowPtContainer.h
- PWGCF/GenericFramework/Tasks/flowGenericFramework.cxx
- PWGLF/Tasks/Nuspex/AngularCorrelationsInJets.cxx
- Added missing custom merge for fCovList
- Replaced 4d c-array with 1d std::vector to avoid TBrowser crashing on inspect
- O2 linter suggestions
> [PWGCF] Fixed merge and streamer bugs in FlowPtContainer

- PWGDQ/Core/CutsLibrary.cxx
Add 6 electron cuts for e-mu trigger test, mainly concerning the value of nSigma
> [PWGDQ] Add test cuts for e-mu trigger

- Common/DataModel/ZDCInterCalib.h
- Common/TableProducer/zdc-task-intercalib.cxx
Needed to study centroid in Pb-Pb for spectator flow related studies
> [Common] Introducing a configurable cut on ZN TDCs to select more clean samples

- PWGEM/Dilepton/Tasks/eventQC.cxx
> [PWGEM/Dilepton] add ITS PID

- PWGLF/Tasks/Nuspex/spectraTOF.cxx
Fixed a function definition and missing hist.
> [PWGLF] Update Tasks/Nuspex/spectraTOF.cxx

- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update eventQC
> [PWGEM/Dilepton] update eventQC

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
updated misidentification condition
> [PWGLF] changed misidentification condition of particles with antiparticles

- DPG/Tasks/AOTTrack/qaImpPar.cxx
Dear all,
I have added an histogram where the info on the cluster size is saved for the IU tracks.
Cheers,
Samuele
> [DPG] AOTTrack, adding cluster size histogram

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
> [PWGLF] change in derived cascade analysis

- PWGJE/Tasks/jetHadronRecoil.cxx
As Delta R caries no meaning for single track jets, we remove them
> [PWGJE] Removing single track jets

- PWGMM/UE/Tasks/CMakeLists.txt
- PWGMM/UE/Tasks/dedx_analysys.cxx
DeDx analysis was added to UE folder
> [PWGLF] DeDx analysys

- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx
- PWGEM/Dilepton/Tasks/Converters/CMakeLists.txt
- PWGEM/Dilepton/Tasks/Converters/electronConverter2.cxx
- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: add ITS PID in data table
> [PWGEM/Dilepton] add ITS PID in data table

- PWGEM/Tasks/phosElId.cxx
fixed logic for J/psi search with phos
added logic to search chi_c via J/psi gamma to dielectron gamma decay channel removed 1sigma and 2sigma track matching to Nsigma with a configurable N
> [PWGEM] phosElId chi_c logic added

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
Fixing issue with MCH and MFT track Ids
> [PWGDQ] Fixing issue with MCH and MFT track Ids

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
PWGEM/Dilepton: add ITS n sigma Ka, Pr exclusion
> [PWGEM/Dilepton] add ITS n sigma Ka, Pr exclusion

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackNucleus.cxx
Correct combinations creation in the track-nucleus task.
> [PWGCF] FemtoUniverse -- Track-nucleus combinations correction.

- PWGCF/Flow/Tasks/pidcme.cxx
add gamma and delta matter and antimatter check
> [PWGCF] update on pidcme

- PWGLF/TableProducer/Strangeness/Converters/stradautracksextraconverter2.cxx
...accidentally closed previous PR - sorry!
> [PWGLF] Fix dau track extras converter

- PWGHF/D2H/Tasks/taskD0.cxx
1. Add the axes of centrality and occupancy
2. Add the process with centrality
3. Change the way of defining the axes of thnsparse
> [PWGHF] Add the axes of centrality and occupancy in thnsparse in taskD0

- PWGDQ/Tasks/tableReader.cxx
Adding new option that enables the calculation of cumulants unless weights or correlators are zero.
> [PWGDQ] Corrected histogram filling logic for cumulants analysis

- PWGDQ/Core/HistogramsLibrary.cxx
Adding histograms for Upsilon analysis
> [PWGDQ] Adding histograms for Upsilon analysis

- PWGEM/Tasks/phosElId.cxx
chic logic change, fixed Jpsi region
now there are several flags to see effects of track matching, MIP cuts and cluster dispersion on the statistics of photons in chic mass spectra
many new histograms for every flag combination
> [PWGEM] phosElId.cxx chic histograms

- PWGLF/Tasks/Resonances/lambda1520analysis.cxx
Update On TOF PID and Histogram Type ( TH3F->THnSparseF )
> [PWGLF] Update On PID and Histogram Type

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackNucleus.cxx
Correct track-nucleus combinations mixing.
> [PWGCF] FemtoUniverse -- Mixing correction.

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/EMEventCut.cxx
- PWGEM/Dilepton/Core/EMEventCut.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/Tasks/eventQC.cxx
- PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: add event selection based on good ITS layers
> [PWGEM/Dilepton] add event selection based on good ITS layers

- Common/Tasks/CMakeLists.txt
- Common/Tasks/flowTest.cxx
For cross-PWG studies and validation / Final QA of https://its.cern.ch/jira/browse/O2-5544
> [Common] Add synthetic flow MC QC task

- PWGLF/Tasks/Strangeness/phik0shortanalysis.cxx
- Improved pion selection
- Added configurable further selection on K0S
- Removed specific K0S decay channel in GenMC
- Distinguished tracking and matching efficiency computation for pions
> [PWGLF] Improved associated particles selection in phik0shortanalysis.cxx

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/VarManager.h
- PWGDQ/TableProducer/tableMaker.cxx
- PWGDQ/TableProducer/tableMaker_withAssoc.cxx
Adding:
- BC tolerance for zorro as a configurable
- and new Ev. sel. for Pb-Pb studies
> [PWGDQ] Adding BC tolerance for zorro and new Ev. sel.

- PWGJE/Tasks/trackJetQA.cxx
Hi @nzardosh , @fjonasALICE,
I added the pt and eta filters along with a few more layer combinations to figure out which its pattern would be best to improve the high pt resolution without losing too much efficiency.
Cheerio,
Johanna
> [PWGJE] trackJetQA.cxx - adding a new  filter and additional ITS pattern

- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update eventQC task
> [PWGEM/Dilepton] update eventQC task

- ALICE3/Core/FastTracker.cxx
- ALICE3/Core/FastTracker.h
- ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
- Addition of ms and eloss corrections to the fasttracker
- Strangeness tracking now gets resolution from the current layer from the fasttracker
- Grouped cascade configurables
> [ALICE3] Add ms & eloss to fasttracker

- PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx
Recent PR, which introduced ITS PID femtodream, introduced breaking changes for MC processing. Fix with this PR.
> [PWGCF] Fix MC processing in FemtoDream

- PWGLF/DataModel/Vtx3BodyTables.h
- PWGLF/TableProducer/Nuspex/CMakeLists.txt
- PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
- PWGLF/TableProducer/Nuspex/threebodyKFTask.cxx
- Added track rotation
- Added tracked cluster size and process for strangeness tracked 3body candidates
- Added zorro event counting for skimmed data processing
> [PWGLF] Update KFParticle 3-body hypertriton reconstruction in decay3bodybuilder

- PWGCF/Flow/Tasks/flowGFWOmegaXi.cxx
Updated event selection, add dead ITS staves cut.
Updated particle reconstruction.
> [PWGCF] Add dead ITS staves cut

- PWGLF/Tasks/Nuspex/QAHistTask.cxx
Bugfix: fixed bug with cut on Lorenzvector cut
Some code cleanup
> [PWGLF] Update QAHistTask

- PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
PWGEM/Dilepton: quick fix to axis label
> [PWGEM/Dilepton] quick fix to axis label

- DPG/Tasks/AOTTrack/qaImpPar.cxx
Dear all,
Just swapped the axis of the histogram to match the histogram definition.
Cheers,
Samuele
> [DPG] AOTTrack: Swap axis in cluster size histogram

- PWGCF/Flow/Tasks/flowGFWOmegaXi.cxx
Fix two bugs in Lambda and Xi PID.
> [PWGCF] Fix some bugs.

- PWGMM/UE/Tasks/CMakeLists.txt
- PWGMM/UE/Tasks/dedxAnalysis.cxx
Made adjustments to address and fix errors flagged by the O2 linter, including naming conventions and workflow structure
> [PWGLF] Adjustments made to resolve issues related to the O2 linter and a new workflow was added

- PWGUD/Tasks/upcTauCentralBarrelRL.cxx
> [PWGUD] Modification of personal task

- PWGDQ/Core/HistogramsLibrary.cxx
Adding FT0C histogram for Pb-Pb generated
> [PWGDQ] Adding FT0C histogram for Pb-Pb generated

- PWGLF/Tasks/Strangeness/derivedcascadeanalysis.cxx
enable efficiency calculation as a function of Nch
> [PWGLF] PWGLF change in derivedcascadeanalysis.cxx

- PWGLF/TableProducer/Strangeness/cascadeflow.cxx
Thanks to @prottayCMT to spot it!
> [PWGLF] Fix assignment of proton vector in Xi local polarisation

- PWGLF/Tasks/Strangeness/CMakeLists.txt
- PWGLF/Tasks/Strangeness/cascpolsp.cxx
Initial commit for cascade polarization with normal AO2Ds. Soon the code will be updated for the Strangeness Derived data.
> [PWGLF] Task for cascade global polarization

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/TableProducer/eventSelection.cxx
- PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx
- PWGEM/Dilepton/Tasks/eventQC.cxx
- PWGEM/Dilepton/Utils/EventHistograms.h
PWGEM/Dilepton: update event qc task and fix axis label
> [PWGEM/Dilepton] update event qc task and fix axis label

- .github/labeler.yml
- .pre-commit-config.yaml
Adds automatic formatting at the time of `git commit`.
See https://pre-commit.com/
> [Infrastructure] Add pre-commit hooks

- PWGUD/Tasks/upcTauCentralBarrelRL.cxx
Trying to satisfy o2linter warnings + histograms for K* investigation
> [PWGUD] personal task modification

- PWGLF/Tasks/Resonances/kshortlambda.cxx
Optimise macro for memory warning
> [PWGLF] “[PWGLF] optimise macro for memory warning”

- PWGMM/UE/Tasks/dedxAnalysis.cxx
Some corrections were made to avoid the warning message "memory consumption too large to run" when I tried to run a train on hyperloop
> [PWGLF] Corrections related with memory comsumption

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
- PWGDQ/TableProducer/tableMaker.cxx
Also adding multiplicity table dependencies to Muon PbPb processes
> [PWGDQ] Adding multiplicity correlation cut for flow studies

- PWGDQ/Core/VarManager.h
There is a typo in Eq.B16 of arXiv:1010.0233.
> [PWGDQ] Correcting calculation of 4-particle correlation

- PWGHF/D2H/Tasks/taskDplus.cxx
- PWGHF/D2H/Tasks/taskDs.cxx
@Marcellocosti @fchinu @scattaru this PR should fix the issue of the high CPU time for the Ds MC and it adds a configurable to choose whether to fill bkg histos or not in Ds and D+ tasks in case of MC
> [PWGHF] Remove unnecessary gen bkg histos and add configurable to fill or not reco bkg histos

- PWGJE/Tasks/jetChargedV2.cxx
close fit output to log fileAdd files via upload
> [PWGJE] Charged jet v2, close fit output to log fileAdd files via upload

- EventFiltering/PWGCF/CFFilterAll.cxx
- Add an option to select on ITS PID for tracks
- Memory usage of the cf-trigger is becoming rather large. Therefore, the number of bins in 2-dimensional histograms is reduced.
> [PWGCF,Trigger] Add ITS PID for track selection

- PWGLF/Tasks/Strangeness/v0topologicalcuts.cxx
Cleaning up the signal so added competitive v0 cut, pseudorapidity cut on v0 daughters, TPC PID.
> [PWGLF] Added cuts

- PWGLF/Tasks/Nuspex/spectraTOF.cxx
Added nsigma PID cuts to MC recons. particles,
refined the code for using impact param to estimate the generated particle spectra instead of using FT0C
> [PWGLF] Update PWGLF/Tasks/Nuspex/spectraTOF.cxx

- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update event qc for PID
> [PWGEM/Dilepton] update event qc for PID

- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: remove unnecessary tagging in PID
> [PWGEM/Dilepton] remove unnecessary tagging in PID

- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update PID with TAP
> [PWGEM/Dilepton] update PID with TAP

- PWGLF/Tasks/Strangeness/lambdak0sflattenicity.cxx
> [PWGLF] Replaced Flattenicity from MCGen to MCRec for event and signal loss calculations

- PWGLF/Tasks/Resonances/k892analysis_PbPb.cxx
- adding process function for MixedEvent  in MC
- implementing rotational background
> [PWGLF] k892analysis_PbPb.cxx - Mixed event in MC, Rotational bkg

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
> [PWGLF] added new event selection cuts and v1toavgpx separately for A and C along with angle bw daughter tracks

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
- PWGEM/Dilepton/Tasks/eventQC.cxx
- PWGEM/Dilepton/Utils/MCUtilities.h
PWGEM/Dilepton: add fake rejection in creation of resolution map
> [PWGEM/Dilepton] add fake rejection in creation of resolution map

- PWGMM/Mult/Tasks/heavy-ion-mult.cxx
1) Add two event selection conditions
`o2::aod::evsel::kNoCollInRofStandard)`
`o2::aod::evsel::kNoHighMultCollInPrevRof`
2) Add new centrality estimators
> [PWGLF] Add event selection and new centrality estimator

- PWGCF/Flow/Tasks/flowPbpbPikp.cxx
Added the v2{4PC} after aligning local repository with O2 master
> [PWGCF] Adding v2 four particle cumulants

- PWGJE/Tasks/jetSpectraCharged.cxx
Add centrality selection for response matrix after background subtraction and modify names of some histograms
> [PWGJE] add centrality selection for response matrix

- PWGHF/TableProducer/derivedDataCreatorBplusToD0Pi.cxx
- PWGHF/TableProducer/derivedDataCreatorD0ToKPi.cxx
- PWGHF/TableProducer/derivedDataCreatorLcToPKPi.cxx
> [PWGHF] Add McGenOnly process function to the init check in derived data creators

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/Tasks/dptdptcorrelations.cxx
- PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx
Also
- fine tuning the vertex reconstruction efficiency
- singles collection for bidimensional simplified efficiency
- proper signal when tuned on data
> [PWGCF] DptDpt - Generator level not reconstructed processing

- PWGDQ/Core/HistogramsLibrary.cxx
Removing temporarily v3 histos from flow-dimuon & res-flow-dimuon to study the memory issye
> [PWGDQ] Removing temporarily v3 histos from flow-dimuon & res-flow-dimuon

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Remove unused type definitions to reduce memory usage
- Optimise the binning to have lighter outputs
> [PWGLF] K892PM Flow - Optimise the binning and remove unused variables

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- Now it is possible to fill mc truth cascades
> [PWGCF] FemtoUniverse cascade task -- to fill output cascades for mc truth

- PWGLF/Tasks/Resonances/higherMassResonances.cxx
- Grouped all configurable
- Added option to select events with only two Ks
- Added void function to fill invariant mass instead of separately fillilng the mass
> [PWGLF] Added option to select events with only two Ks

- PWGJE/Tasks/jetTaggerHFQA.cxx
> [PWGJE] To fix MCP about weight

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
- PWGDQ/Tasks/tableReader_withAssoc.cxx
Adding Prompt-non-prompt Separation Table
> [PWGDQ] Update dqEfficiency_withAssoc.cxx

- PWGLF/Tasks/Strangeness/v0ptinvmassplots.cxx
Added zvertex cut, v0compmasscut, daughter pseudorapidity cut and Armenteros plot for visualisation.
> [PWGLF] Extra cuts to v0ptinvmassplots task

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
different selection for proton and pion
> [PWGLF] different selection for proton and pion

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Add configurable to modify the v2 axis
- Fix constraining function for rotation bkg v2 (from 2PI to PI)
> [PWGLF] K892PM Flow: Allow modifying v2 axis 

- PWGDQ/Macros/evalMchTrackingEfficiency.cxx
This PR aims to add a macro to evaluate the efficiency of the MCH muon tracking. It uses the sparse created in taskMuonTrkEfficiency.cxx as input.
> [PWGDQ] Add macro to evaluate MCH tracking efficiency

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
Additional flags incorporated to the MB selection
- kNoCollInTimeRangeStandard
- kNoCollInRofStandard
Incorporated minimum value for the occupancy selection
> [PWGCF] DptDpt - Event selection tune

- PWGHF/D2H/Tasks/taskCharmResoReduced.cxx
This PR adds a selection on the invariant mass of the Charm resonance in order to reduce the output file size
> [PWGHF] Added mass cut to Resonance Task

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Simply add a new configurable for the additional axis filling: `cfgFillAdditionalAxis`
> [PWGLF] Chk892Flow: Add switch for an additional axis

- PWGLF/TableProducer/Resonances/resonanceInitializer.cxx
- PWGLF/TableProducer/Resonances/resonanceModuleInitializer.cxx
- PWGLF/Tasks/Resonances/chk892Flow.cxx
- PWGLF/Tasks/Resonances/chk892flow_pp.cxx
- PWGLF/Tasks/Resonances/chk892pp.cxx
- PWGLF/Utils/collisionCuts.h
- Remove unused trigger check 
- Add additional event selections
- Propagate it to the task using it.
> [PWGLF] CollisionCuts: Remove unused trigger check and add additional event selections

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Add a new v0 selection cut based on the different mass hypothesis (lambda and anti-lambda)
> [PWGLF] chk892Flow: Add new v0 selection cut

- PWGCF/Flow/Tasks/flowGfwTask.cxx
- PWGJE/Core/JetDerivedDataUtilities.h
Fix amplitude limits and ITSGOODITSLAYERSALL comment.
> [PWGCF] Fix FT0 low cut

- PWGJE/Tasks/recoilJets.cxx
Edited material:
1.    introduce conditions to prevent the creation of empty histograms when it is not needed
2.    change the range of histograms
3.    add selection cuts on MC particles
4.    fix the issue when a neutral MC particle could be accepted for the analysis
> [PWGJE] Hadron jet recoil

- PWGMM/UE/Tasks/dedxAnalysis.cxx
A variable binning for the moment and 4 histograms to distinguish between particles of different charges were added, and on the other hand, calibration factors were adjusted.
> [PWGLF] Variable binning was added to momentum and AxisSpec was moved

- PWGLF/Tasks/Nuspex/NucleiEfficiencyTask.cxx
Bugfix: fixed centrality cut implementation for reconstructed MC
> [PWGLF] Update NucleiEfficiencyTask.cxx

- EventFiltering/filterTables.h
- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Tasks/filterPP.cxx
- PWGDQ/Tasks/filterPPwithAssociation.cxx
1. Extend the dq trigger group in filterTable
2. Activate the CEFP related code for e-mu trigger in filterPPwithAssociation
3. Modify the filterPP correspondingly for the compile
4. Add related cuts in CutsLibrary
> [PWGDQ,Trigger] Proposal for the electron-muon pp trigger

- PWGLF/Tasks/Resonances/k892analysis_PbPb.cxx
- new organization of functions
- adding manual cuts on track quality
- adding QA plots and rotational bkg for MC
- adding histos for MC bkg study, cut on tof beta
> [PWGLF] k892analysis_PbPb.cxx -- bkg studies

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
> [PWGLF] added v2 calculation and using full plane with modified qvec after SC

- PWGLF/Tasks/Resonances/phianalysisTHnSparse.cxx
- PWGLF/Utils/rsnOutput.h
- Multiplicity and centrality for MC Gen process added
- 2 options for Event mixing production (Vz + centrality, Vz + multiplicity)
- Event and track selection monitoring histograms
> [PWGLF] Multiplicity for processGen, Event Mixing options, QA

- PWGEM/Dilepton/Tasks/CMakeLists.txt
- PWGEM/Dilepton/Tasks/studyMCTruth.cxx
PWGEM/Dilepton: add a task for MC truth
> [PWGEM/Dilepton] add a task for MC truth

- PWGEM/Dilepton/Tasks/studyMCTruth.cxx
PWGEM/Dilepton: update MC study
> [PWGEM/Dilepton] update MC study

- Common/Tools/Multiplicity/multGlauberNBDFitter.cxx
- Common/Tools/Multiplicity/multGlauberNBDFitter.h
Allows for (much) more modular operation of average Npart, Ncoll calculation machinery
> [Common] centrality / minor changes for modular operation

- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
hi @fgrosa, here is the PR for the ITSPID of the deuterons, let me know if you have any comments. Thanks a lot!
> [PWGHF,Trigger] Add ITSPID slection on the deuteron of LcDe femto trigger

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
@ddobrigk updated the strangeness table with ZDC q vectors
> [PWGLF] added q vectors information in strangeness derived data tables

- PWGLF/Tasks/GlobalEventProperties/dndeta-mft-pp.cxx
> [PWGLF] Updated task for generated MC

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
Add PID flag and change the loop of filling histogram using two for loop
> [PWGLF] Add PID flag and change main loop using two for loop

- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGHF/D2H/TableProducer/candidateCreatorBplusReduced.cxx
- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
- PWGHF/D2H/Tasks/taskBplusReduced.cxx
First implementation of correlated bkg identification (kept similar to B0 for the moment)
> [PWGHF] B+ improve correlated background identification

- Common/Tasks/flowTest.cxx
...for quick check of proton v2 non-closure in MC
> [Common] Add PDG selection for flow test

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Add flag `cfgFillQAPlots`: `true` by default, to keep the QA plots.
> [PWGLF] chk892Flow: Add flag for saving QA plots

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/kstarFlowv1.cxx
Initial task for first-order flow harmonics of K*(892)
> [PWGLF] Initial task for first-order flow harmonics of K*(892)

- PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
@vkucera @atavirag This is the followup of our discussion in https://github.com/AliceO2Group/O2Physics/pull/9885
> [PWGHF] Cleanup table filling in D0 tree creator

- PWGJE/Tasks/hadronPhotonCorrelation.cxx
- PWGUD/Tasks/CMakeLists.txt
- PWGUD/Tasks/testMCstdTabsRL.cxx
Creating a task, which test MC production of standard tables by plotng some standard variables against generatorID
> [PWGUD] Task to test generatorID of UD MC production on hyperloop

- PWGJE/Core/JetTaggingUtilities.h
- PWGJE/Core/MlResponseHfTagging.h
- PWGJE/TableProducer/jetTaggerHF.cxx
- PWGJE/Tasks/bjetTaggingML.cxx
- Tools/ML/model.h
I implement a utility class for the b-jet ML methods called "MlResponseHfTagging.h".
This class can any take any features' names from the user and gives a vector of these inputs that will be used for hf tagging.
> [PWGJE] Implementing a utility class for b-jet tagging ML methods

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
detector acceptance corrections added
> [PWGLF] added cumulant corrections for v2

- PWGMM/Mult/Core/include/Functions.h
- PWGMM/Mult/Tasks/dndetaMFTPbPb.cxx
- Updated with new centrality estimators
- Minor: Added process function to check ambiguous MFT tracks
- Minor: Added occupancy axis
> [PWGLF] Updated with new centrality estimators

- PWGLF/TableProducer/Resonances/LFResonanceMergeDF.cxx
Fixed incorrect occupancy filling logic
> [PWGLF] Fixed incorrect occupancy filling logic

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: remove unused configurable variable
> [PWGEM/Dilepton] remove unused configurable variable

- PWGLF/TableProducer/Strangeness/v0selector.cxx
* Can now set minimun and maximum values for every cut
* Centralised cutting code
* Fixed bug with pt bins
> [PWGLF] Update V0 Selector

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
> [PWGLF] adding qa plots

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: quick fix to treeCreator MLDDA
> [PWGEM/Dilepton] quick fix to treeCreator MLDDA

- PWGCF/GenericFramework/Core/GFWWeights.cxx
- PWGCF/GenericFramework/Core/GFWWeights.h
GFW_Core dictionary is broken when include AnalysisTask.h
> [PWGCF] debug, fix GFW dictionart problem

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: quick fix to tree creator ML DDA
> [PWGEM/Dilepton] quick fix to tree creator ML DDA

- PWGEM/Dilepton/Tasks/studyMCTruth.cxx
PWGEM/Dilepton: add a task to study event selection bias in MC
> [PWGEM/Dilepton] add a task to study event selection bias in MC

- PWGCF/Tasks/correlations.cxx
adding ML selection in the correlations task
> [PWGCF] adding ML selection in the correlations task

- PWGMM/Mult/Tasks/CMakeLists.txt
- PWGMM/Mult/Tasks/dndetaMFTPbPb.cxx
- Added checks for interaction rate in PWGMM/Mult/Tasks/dndetaMFTPbPb.cxx
- Added library for ctp rate fetcher in PWGMM/Mult/Tasks/CMakeLists.txt
- cleanup
> [PWGLF] Added checks for interaction rate

- PWGLF/DataModel/Vtx3BodyTables.h
- PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
- PWGLF/TableProducer/Nuspex/threebodyKFTask.cxx
Add TPC chi2 of deuteron track
Check mother PDG code for all MC particles
Add daughter PDG codes
> [PWGLF] Few additions for hypertriton 3-body decay reconstruction KFParticle (new)

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Correction for a simple mistake...
> [PWGLF] chk892Fliow - Hot fix for resolution in SC method

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/lstarpbpbv2.cxx
code to calculate elliptic flow for lstar resonance
> [PWGLF] initial commit for LStar v2

- PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx
PDG code 423 to be replaced as PR [#13972](https://github.com/AliceO2Group/AliceO2/pull/13972) get merged
B+ -> **D0** \pho , B+ -> **Dstar(2007)0** \pi
> [PWGHF] B+ corr. bkg, add charm mother PDGs

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
calculating ITS-TPC matching efficiency
> [PWGLF] calculating ITS-TPC matching efficiency

- PWGCF/Tasks/correlations.cxx
adding switch for different correlations
adding selection for QA plots
adding doprocess where needed
> [PWGCF] adding switch for different correlations

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
added rotational bkg for phi production and mixed event bkg for kstar flow
> [PWGLF] added different combinatorial bkg for phi and kstar task

- PWGEM/Dilepton/Core/DileptonMC.h
Differentiate between prompt and non-prompt Pi0 when filling dilepton histograms
> [PWGEM] DileptonMC: differentiate between PromptPi0 and NonPromptPi0

- PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
- PWGLF/TableProducer/Strangeness/strangenessbuilderfindable.cxx
- PWGLF/Utils/strangenessBuilderHelper.h
Fix collision indexing in default path of strangeness builder as well as in new findable tests. Some more indexing work will probably be needed for the findable path - more to follow.
> [PWGLF] Fix strangeness builder indexing

- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
This PR fixes a bug on the resonance data creator workflow with ML
> [PWGHF] Fixed bug on resonance data creator

- CODEOWNERS
Adding Jacek (FIT project leader), Sahil (FIT SW coordinator), myself and Artur (developers) as code owners of the FIT related code.
> [Infrastructure] Update CODEOWNERS for FIT

- PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
- PWGLF/TableProducer/Nuspex/threebodyKFTask.cxx
> [PWGLF] Fix 3body data-linking + improve MC matching

- PWGHF/HFC/DataModel/DerivedDataCorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I have added some code in order to see the feasibility of producing self-contained derived data for the SE analysis. I have also add a minor contribution in the track efficiency process in order to enable/disable the track origin separation.
Cheers,
Samuele
> [PWGHF] Ds-h correlation, adding derived data for SE analysis

- PWGLF/DataModel/ReducedHeptaQuarkTables.h
- PWGLF/TableProducer/Resonances/HeptaQuarktable.cxx
adding TOF hits
correcting event number plot
joining centrality task
> [PWGLF] adding TOF hits

- PWGCF/TwoParticleCorrelations/Tasks/neutronProtonCorrZdc.cxx
- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
Addition of two histograms to check the A/C side asymmetry on the ZDC common channels
> [PWGCF] Adding A/C side asymmetry histograms

- PWGLF/Tasks/Resonances/chk892Flow.cxx
Configuration group applied to avoid build crash due to the number of variables in the structure.
> [PWGLF] chK892Flow - refactor with configuration group

- PWGJE/Tasks/jetFragmentation.cxx
- PWGJE/Tasks/v0QA.cxx
* Update to use V0 signal flags
* Bug fixes
> [PWGJE] V0 QA & Jet Fragmentation

- PWGJE/Tasks/jetChargedV2.cxx
Fix leading track cut, test different method to get delta pt
> [PWGJE] Fix leading track cut, test different method to get delta pt

- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
Change type of histogram hDCAz_Pt_collType kTH3F to kTHnSparseF. Use name space std:: for abs()
> [PWGEM] Change type of histogram hDCAz_Pt_collType

- PWGLF/Tasks/Strangeness/lambdalambda.cxx
> [PWGLF] adding qa for event reduction

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: fix in treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] fix in treeCreatorElectronMLDDA.cxx

- PWGEM/Dilepton/Tasks/associateMCcollision.cxx
- PWGEM/Dilepton/Tasks/studyMCTruth.cxx
PWGEM/Dilepton: update studyMCTruth.cxx
> [PWGEM/Dilepton] update studyMCTruth.cxx

- PWGCF/Flow/Tasks/flowGfwTask.cxx
There was a problem with the centrality decision. Here is fixed.
> [PWGCF] Fix centrality decision

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: update treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] update treeCreatorElectronMLDDA.cxx

- PWGLF/DataModel/Reduced3BodyTables.h
- PWGLF/TableProducer/Nuspex/reduced3bodyCreator.cxx
> [PWGLF] Fix Zorro initialization and extended table

- PWGLF/Tasks/Resonances/kstarpbpb.cxx
- PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
kstar task : added MC to calculate efficiency, purity checks
phi task : purity checks
> [PWGLF] added MC for Kstar flow task and purity for phi task

- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/TableProducer/Strangeness/strangenessbuilderfindable.cxx
@romainschotter this should allow for derived data with the findable mode of the strangeness builder now as well
> [PWGLF] Strangeness builder vs derived builder streamlining

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: remove unused table in treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] remove unused table in treeCreatorElectronMLDDA.cxx

- PWGJE/Core/JetTaggingUtilities.h
- PWGJE/Core/MlResponseHfTagging.h
- PWGJE/Tasks/bjetTaggingML.cxx
Adding the event weight to the THnSparse. In Addition to formatting changes.
> [PWGJE] Adding event weight to THnSparse

- PWGJE/Tasks/jetSpectraCharged.cxx
Fix a bug in JetMatching (with bkg subtraction) function and change few histograms' name
> [PWGJE] Fix a bug in JetMatching function

- PWGCF/Femto3D/Core/femto3dPairTask.h
- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx
- PWGCF/Femto3D/TableProducer/singleTrackSelectorPIDMaker.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
- PWGLF/Tasks/Strangeness/k0_mixed_events.cxx
> [PWGCF,PWGLF] adding ITS PID and other minor changes

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
add lower cumulants
update shift correction
> [PWGLF] add lower cumulants

- CODEOWNERS
Adding Gleb Romanenko from Bologna group
> [Infrastructure] Update CODEOWNERS

- PWGDQ/Core/HistogramsLibrary.cxx
- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/heptaquark.cxx
initial commit for heptaquark search task
> [PWGLF] initial commit for heptaquark search task

- PWGUD/Tasks/CMakeLists.txt
- PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
- PWGUD/Tasks/upcJpsiCorr.cxx
* addition of trees for unbinned fits
* O2 linter requirement fixes (including name file change in CMakeList)
* use of template functions to reduce the code length
> [PWGUD] Jpsi central v10

- PWGJE/TableProducer/heavyFlavourDefinition.cxx
Fixing a bug in the determination of the heavy flavor type of the jet for the particle level jets.
> [PWGJE] Fixing a bug in the hf determination using distance method

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
PR opened on behalf of @dongjokim
- Fix histogram name 
- Fix groupped track loop.
> [PWGCF] jFlucEfficiencyTask - fix crash

- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
- Fix ITS PID related MC bug 
- Add pseudo rapidity cut correction
> [PWGLF] NucleiTask - Fix ITS PID related MC bug

- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/nucleiInJets.cxx
Good morning. Please approve the PR.
Have a nice day.
Arvind
> [PWGJE] Histograms for the skimmed data

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGLF/Tasks/Resonances/chargedkstaranalysis.cxx
> [PWGEM/Photon] fix abs, fabs

- PWGDQ/Core/VarManager.h
- PWGDQ/Tasks/tableReader.cxx
Adding charge information to minitree
> [PWGDQ] Adding charge information to minitree

- PWGLF/DataModel/lambdaJetpolarization.h
- PWGLF/TableProducer/Strangeness/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/lambdaJetpolarizationbuilder.cxx
- PWGLF/Tasks/Strangeness/CMakeLists.txt
- PWGLF/Tasks/Strangeness/lambdaJetpolarization.cxx
Dear Experts:
The recent code is mainly used to calculate Lambda local polarization induced by jet.
I have two .cxx files and one header file to complete my analysis.
TableProducer : lambdaJetpolarizationbuilder.cxx : produce V0 QA and Jet QA histogram and same derived datas
Tasks ：lambdaJetpolarization.cxx : calculate local polarization use datas form TableProducer
DataModel : lambdaJetpolarization.h : some tables that I created myself for my analysis.
Best wishes,
Youpeng Su
> [PWGLF] PWGLF:Lambda polarization induced by jet in pp collision in 13.6 TeV

- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: add collision cov. matrix and matlut for track propagation
> [PWGEM/Dilepton] add collision cov. matrix and matlut

- PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/Core/V0PhotonCut.cxx
- PWGEM/PhotonMeson/Core/V0PhotonCut.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Tasks/prefilterPhoton.cxx
- PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/Photon: add a prefilter task for photons from pi0s
> [PWGEM/Photon] add a prefilter task for photons from pi0s

- PWGEM/PhotonMeson/Core/DalitzEECut.cxx
- PWGEM/PhotonMeson/Core/DalitzEECut.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCPCMPCM.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Tasks/prefilterPhoton.cxx
- PWGEM/PhotonMeson/Utils/PairUtilities.h
PWGEM/Photon: update prefilterPhoton.cxx
> [PWGEM/Photon] update prefilterPhoton.cxx

- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
PWGEM/Dilepton: upadte dalitzEEQC
> [PWGEM/Dilepton] upadte dalitzEEQC

- PWGLF/Tasks/Strangeness/lambdapolarization.cxx
> [PWGLF] weighting polarization

- PWGCF/EbyEFluctuations/Tasks/CMakeLists.txt
- PWGCF/EbyEFluctuations/Tasks/kaonIsospinFluctuations.cxx
MC part, truth level and reco level analysis added
> [PWGCF] Kaon isospin fluctuation : Reco Level and Truth Level analysis added

- PWGJE/Tasks/CMakeLists.txt
- PWGJE/Tasks/bjetTaggingGNN.cxx
- PWGJE/Tasks/bjetTaggingGnn.cxx
`bjetTaggingGNN.cxx`
- Added `THnSparse::Sumw2()` call option for error calculation.
- Fixed bugs on counting the number of not-physical-primary tracks.
- Revised some histogram registry entries.
> [PWGJE] Added THnSparse::Sumw2() call option for error calculation, Fixed bugs.

- PWGHF/TableProducer/candidateCreator2Prong.cxx
- PWGHF/TableProducer/candidateCreator3Prong.cxx
- PWGHF/TableProducer/candidateCreatorB0.cxx
- PWGHF/TableProducer/candidateCreatorBplus.cxx
- PWGHF/TableProducer/candidateCreatorBs.cxx
- PWGHF/TableProducer/candidateCreatorCascade.cxx
- PWGHF/TableProducer/candidateCreatorDstar.cxx
- PWGHF/TableProducer/candidateCreatorLb.cxx
- PWGHF/TableProducer/candidateCreatorSigmac0plusplusCascade.cxx
- PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
- PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx
- PWGHF/TableProducer/candidateSelectorBplusToD0Pi.cxx
- PWGHF/TableProducer/candidateSelectorBsToDsPi.cxx
- PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaKa.cxx
- PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaPi.cxx
- PWGHF/TableProducer/candidateSelectorToXiPi.cxx
- PWGHF/TableProducer/candidateSelectorXic0ToXiPiKf.cxx
- PWGHF/TableProducer/candidateSelectorXicToPKPi.cxx
- PWGHF/TableProducer/mcPidTof.cxx
- PWGHF/TableProducer/pidCreator.cxx
- PWGHF/TableProducer/trackIndexSkimCreator.cxx
- PWGHF/TableProducer/treeCreatorB0ToDPi.cxx
- PWGHF/TableProducer/treeCreatorToXiPi.cxx
Important changes:
Fixed names of configurables:
- PWGHF/TableProducer/candidateSelectorBsToDsPi.cxx @pstahlhu please check
- PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaPi.cxx @ZFederica please check
- PWGHF/TableProducer/treeCreatorB0ToDPi.cxx (not actively used AFAIK)
> [PWGHF] Fix linter issues

- PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h
- added a check to see if bachelor track has TOF and if it has then only TOF cut is applied, otherwise not. @basiach
> [PWGCF] FemtoUniverse cascade task -- implemented TOF cut for bachelor tracks with TOF

- PWGHF/HFC/DataModel/DerivedDataCorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
- PWGHF/HFC/TableProducer/correlatorDsHadronsReduced.cxx
Dear all,
I have realized that the information on the Ds prongs are missing in self-contained derived data. I added them in this PR. 
Let me know for any comments,
Cheers,
Samuele
> [PWGHF] Add Ds prong info and offline processes

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/TableProducer/Resonances/resonanceMergeDF.cxx
- Updated the resonance table descriptions to solve the warnings in hyperloop
- Add Xi1530 candidates producer in mergeDF
> [PWGLF] ResonanceMergeDF - Add derived dataset candidates for Xi1530 study

- PWGDQ/Core/CutsLibrary.cxx
- PWGDQ/Core/HistogramsLibrary.cxx
Adding new cuts and histograms
> [PWGDQ] Adding new cuts and histograms

- Common/TableProducer/occupancyTableProducer.cxx
added QA histograms and increased the arraySize to make task  workable for run3 PbPb 2024 data
> [Common] Added QA histograms and increased arraySize

- PWGCF/Flow/Tasks/pidcme.cxx
updates on cme signal and TOF QA
> [PWGCF] updates on cme signal and TOF QA

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Add `hZVertexReco` in data process
> [PWGCF] jFlucEfficiencyTask - Add QA histo

- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
- PWGEM/Dilepton/Tasks/studyMCTruth.cxx
PWGEM/Dilepton: update createResolutionMap.cxx and studyMCTruth.cxx
> [PWGEM/Dilepton] update createResolutionMap.cxx and studyMCTruth.cxx

- PWGLF/TableProducer/Strangeness/lambdaJetpolarizationbuilder.cxx
- PWGLF/Tasks/Strangeness/lambdaJetpolarization.cxx
Dear Experts:
The recent code is mainly used to calculate Lambda local polarization induced by jet.
I have two .cxx files and one header file to complete my analysis.
TableProducer : lambdaJetpolarizationbuilder.cxx : add some configurations about v0 selection
Tasks ：lambdaJetpolarization.cxx : modified the polarization calculation formula.
DataModel : lambdaJetpolarization.h : There were no changes.
Best wishes,
Youpeng Su
> [PWGLF] PWGLF:Lambda local polarization induced by jet in pp collision 13.6 TeV

- PWGDQ/Core/HistogramsLibrary.cxx
Fixing issue in the filling of histograms for Upsilon
> [PWGDQ] Fixing issue in the filling of histograms for Upsilon

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Apply missing track selection filters
- Add primary track selection filter 
- Unify histogram names
> [PWGCF] jFlucEfficiencyTask.cxx - Apply track filter

- PWGJE/Tasks/jetChargedV2.cxx
Fixed delta pt distribution and use right randomConePhi to get rholocal at delta pT step. Add check plots for rho_local vs phi and rho_local vs centrality
> [PWGJE] fixed delta pt distribution, add check plots with rho_local vs phi and centrality

- PWGLF/DataModel/LFResonanceTables.h
- PWGLF/TableProducer/Resonances/resonanceInitializer.cxx
- PWGLF/TableProducer/Resonances/resonanceModuleInitializer.cxx
- Remove `s` at the end of each table description
- Remove `FV0` values from initializers
> [PWGLF] Resonance Table - Update table descriptions

- PWGJE/Tasks/jetFinderQA.cxx
- add leading track variables
- change eta and phi resolution figures so that they correspond to absolute resolution and not relative resolution (which doesn't make sense for these variables
> [PWGJE] add leading track response and fix phi and eta resolution

- PWGEM/Dilepton/Core/SingleTrackQC.h
Adding some labels to track QC histograms
> [PWGEM] adding labels to single track histograms

- PWGUD/Tasks/upcTauTau13topo.cxx
Added MC part based on UD tables, 
section cuts order changed,
UPC flag stored
> [PWGUD] Added MC part based on UD tables, section cuts order changed

- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update PCM tasks
> [PWGEM/PhotonMeson] update PCM tasks

- PWGLF/TableProducer/Strangeness/hStrangeCorrelationFilter.cxx
Add correct eta and pt cut for cascade and omega
Fixing errors from O2linter
> [PWGLF] Bug fixing for h-strangeness filter

- PWGLF/Tasks/Strangeness/lambdaJetpolarization.cxx
Dear Experts:
The recent code is mainly used to calculate Lambda local polarization induced by jet.
I have two .cxx files and one header file to complete my analysis.
TableProducer : lambdaJetpolarizationbuilder.cxx : The file has not been modified.
Tasks ：lambdaJetpolarization.cxx : Corrected the matrix transformation parameters, added some QA plots, and modified the polarization calculation formula.
DataModel : lambdaJetpolarization.h : The file has not been modified.
Best wishes,
Youpeng Su
March 6, 2025
> [PWGLF] Lambda local polarization induced by jet in pp collision 13.6 TeV

- PWGCF/Flow/Tasks/flowGfwTask.cxx
Make a new efficiency correction task adding event and track cuts for Reco MC and apply the doprocess on histograms.
> [PWGCF] Modify efficiency corrections

- ALICE3/TableProducer/alice3-multicharm.cxx
Add new histogram and changes to some configurables
> [ALICE3] Changes to configurables and histograms in multi-charm task

- PWGHF/HFC/TableProducer/correlatorDsHadronsReduced.cxx
- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
I have added the TPC crossed rows selection in the efficiency process.
Cheers,
Samuele
> [PWGHF] DS-h correlation, adding TPC crossed rows check in efficiency process

- PWGCF/Flow/Tasks/flowEfficiencyCasc.cxx
> [PWGCF] Add PDGCode check

- PWGHF/HFC/Tasks/taskFlow.cxx
- PWGJE/Tasks/fullJetSpectraPP.cxx
fixed bugs related to outlier rejection cuts + added correlation histograms for jet eta and phi at Det and Part level
> [PWGJE] fixed outlier bugs+ added correlation histos

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx
This PR fixes minor issue where configurable for PDG cut was not being picked up in `Partition` for MC truth. Now we just use plain `if`s to filter for desired particles by PDG & charge.
> [PWGCF/FemtoUniverse] Properly filter by PDG and charge in `track-track-extended` task

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update photon data table and pcm qc
> [PWGEM/PhotonMeson] update photon data table and pcm qc

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: update pcm data table and tasks
> [PWGEM/PhotonMeson] update pcm data table and tasks

- PWGDQ/Tasks/tableReader_withAssoc.cxx
table-reader-with-assoc: event-selection
a) added additional protection in the init function for when the dummy function is enabled
table-reader-with-assoc: same-event-pairing
a) option to reject split collision candidates, as determined by the event selection task via two-event correlations;
b) added additional process function for barrel only analysis, but with extra multiplicity estimators being available, mainly for TPC occupancy checks
> [PWGDQ] Added option to reject collision splitting candidates

- Common/TableProducer/centralityTable.cxx
Will reduce confusion when interpreting errors
> [Common] Improve warning message for estimator not available

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/Converters/stramccollisionconverter2.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add GeneratorID in the strangeness data model (useful for separating processes for UPC MC dataset)
@nepeivodaRS for your information
> [PWGLF] Add Generator ID in strangeness data model

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
Add PID flag for test code using kaon instead of pion
> [PWGLF] Add test code using kaon instead of pion

- PWGCF/Flow/Tasks/pidcme.cxx
add asymmetric pid nsigma  selections
> [PWGCF] update on pidselection

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Add two data, mc process for Run2
> [PWGCF] jFlucEfficiencyTask - Add process for Run2 QA

- PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding a TOF nSigma cut on cascade daughters that have TOF signal and moving the bachelor cut to task level.
> [PWGCF] FemtoUniverse - Adding a TOF nSigma cut on cascade daughters

- PWGJE/Tasks/jetBackgroundAnalysis.cxx
- PWGJE/Tasks/jetSpectraCharged.cxx
- add skipMBGapEvents to jetspectraCharged.cxx and jetBackgroundAnalysis.cxx
- add checkLeadConstituentMinPtForMcpJets to jetspectraCharged.cxx
> [PWGJE] jetspectraCharged and jetBackgroundAnalysis updates

- PWGJE/Tasks/jetChargedV2.cxx
Add event number check plot in each event select and track select step, add rho_local check plot to check different centrality region, add event plane resolution(using 3-sub-event method) plots
> [PWGJE] Add event number check plot, rho_local check plot about centrality, add event plane resolution plots

- PWGEM/PhotonMeson/DataModel/gammaTables.h
- PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: add histograms for misidentified ee as V0 photons in MC
> [PWGEM/PhotonMeson] add histograms for misidentified ee as V0 photons in MC

- PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: update ConfYllBins
> [PWGEM/Dilepton] update ConfYllBins

- PWGCF/TableProducer/dptdptfilter.cxx
- PWGCF/TableProducer/dptdptfilter.h
- PWGCF/TwoParticleCorrelations/Tasks/dptDptPerRunQc.cxx
Also
- tracking orbits of interest
- tracking inclusive not reconstructed
- configurable for the proper interaction rate source
> [PWGCF] DptDpt - Tracking each of the track selection criteria

- PWGCF/Flow/Tasks/pidcme.cxx
updates on Systematic checking
> [PWGCF] updates on Systematic checking

- DPG/Tasks/AOTEvent/timeDependentQa.cxx
New histos, cleanup, bug fixes, tuned cuts.
> [DPG] Update timeDependentQa.cxx - new histos, bug fixes

- PWGJE/Tasks/jetShape.cxx
I added new histgrams to my own code jetShape.cxx to calculate purity of proton and pion.
> [PWGJE] Improvements to my own code, jetShape.cxx

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Add default Centrality cut on event (0 - 80)
- Modify the default values of the configurable
> [PWGLF] chk892Flow - Add centrality cut and modify default values

- PWGLF/Tasks/Strangeness/lambdalambda.cxx
add event selection flag
separate DCA selections
fix bug
> [PWGLF] add event selection flag

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
Adding process filling histogram of mother particle PDG of pair obtained while mixing to get Pair Fractions
> [PWGCF] Pair Fractions

- DPG/Tasks/AOTEvent/timeDependentQa.cxx
add RCT flags vs time monitoring
> [DPG] Update timeDependentQa.cxx - add RCT flags vs time monitoring

- PWGDQ/Core/MCProng.cxx
- PWGDQ/Core/MCProng.h
- PWGDQ/Core/MCSignal.h
- PWGDQ/Core/MCSignalLibrary.cxx
- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
Adding the HEPMC status code 11 (final state) in the MCProng source list; 
Fix a bug in the MCSignal check sources; 
Adding a function to count the generator level signal only for selected reconstructed collisions in Dilepton-Hadron task
> [PWGDQ] Changes to MCProng/MCSignal and dq-effieciency for generator level signal counting

- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: fix std::abs, std::fabs
> [PWGEM/Dilepton] fix std::abs, std::fabs

- PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
Did not use o2::constants::Physics::Pdg for the pdg due to lack of time.
> [PWGUD] Added 4 More table columns, fixed O2linter errors, whithout disabling them.

- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx
- PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
- PWGEM/PhotonMeson/Tasks/prefilterPhoton.cxx
PWGEM/PhotonMeson: update qc task
> [PWGEM/PhotonMeson] update qc tasks

- PWGLF/TableProducer/Nuspex/he3HadronFemto.cxx
> [PWGLF] add ITS Ncluster configurable

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Add automatic check of Run2 process
> [PWGCF] jFlucEfficiencyTask - Add run2 event cut option

- PWGLF/DataModel/cascqaanalysis.h
- PWGLF/TableProducer/Strangeness/cascqaanalysis.cxx
- PWGLF/Tasks/Strangeness/derivedupcanalysis.cxx
- PWGLF/Utils/strangenessMasks.h
1. genPt and genY for rec. cascades
2. feeddown correction for lambdas in UPC analysis
> [PWGLF] update xi in pp and UPC analyses

- PWGEM/PhotonMeson/Tasks/pcmQC.cxx
- PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: fix in pcmQCMC.cxx
> [PWGEM/PhotonMeson] fix in pcmQCMC.cxx

- PWGCF/Flow/Tasks/flowEfficiencyCasc.cxx
Fix a bug about histogram name.
> [PWGCF] Fix a bug

- PWGLF/TableProducer/Strangeness/lambdakzerobuilder.cxx
- PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
> [PWGLF] Adds QA, preparation for modular stra builder

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding a TOF nSigma cut to track-cascade correlations (not just QA).
> [PWGCF] FemtoUniverse - Adding a TOF nSigma cut to cascade correlations

- PWGLF/Tasks/Resonances/chk892Flow.cxx
- Hot fix to correct the scalar production
> [PWGLF] chk892Flow - hot fix of EP resolution

- PWGUD/Tasks/upcTauTau13topo.cxx
Added TauTau skimmer for 1+3 topology (4 tracks)
> [PWGUD] TauTau 1+3 topo skimmer

- DPG/Tasks/AOTEvent/detectorOccupancyQa.cxx
add configs to suppress heavy histos
> [DPG] Update detectorOccupancyQa.cxx - add configs to suppress heavy histos

- PWGCF/Flow/Tasks/flowEfficiencyCasc.cxx
- PWGCF/Flow/Tasks/flowGfwOmegaXi.cxx
Add topological cut QA histograms.
Add event selection in MCRec.
> [PWGCF] Add some QA histos and event selection cut

- PWGJE/Tasks/nucleiInJets.cxx
Good evening. Please approve the PR once all the tests are passed.
Many thanks.
Arvind
> [PWGJE] Added histograms for MC study

- PWGUD/Tasks/upcTauTau13topo.cxx
FIT veto eneabled be default
default is 2BC 
efficiency histogram in skimming process
dynamic histogram booking dependent on MC or Data
> [PWGUD] FIT veto eneabled be default + efficiency skim histo

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Add `Run2BCInfos` to the subscription
> [PWGCF] jFlucEfficiencyTask - Subscribe b2 info for run2 converted data

- DPG/Tasks/AOTTrack/qaImpPar.cxx
Dear all,
I have just added some histograms to perform the study on the impact parameter resolution differential in PID.
Cheers,
Samuele
> [DPG] AOTTrack: Adding pID and DCA to cluster size histograms

- PWGLF/DataModel/ReducedLambdaLambdaTables.h
- PWGLF/TableProducer/Nuspex/he3HadronFemto.cxx
- PWGLF/TableProducer/Strangeness/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/LambdaLambdatable.cxx
initial commit of lambdalambda table producer
> [PWGLF] initial commit of lambdalambda table producer

- Common/DataModel/PropagatedFwdTrackTables.h
- Common/TableProducer/fwdtrackPropagation.cxx
Common: fix to #10618
dcaX, dcaY were forgotten
index to mtached MCH track was wrong.
> [Common] fix to #10618

- DPG/Tasks/AOTTrack/qaImpPar.cxx
Dear all,
Just a minor adjustment to switch the THn to THnSparse histograms. 
Let me know for any comments,
Cheers,
Samuele
> [DPG] AOTTrack Impact parameter: move THn to THnSparse

- EventFiltering/PWGLF/strangenessFilter.cxx
HM omegas selected using normalised multiplicity - code copied from multFilter.cxx.
> [PWGLF,Trigger] Omegamult

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/DimuonCut.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/filterEoI.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/Dilepton/Utils/EMFwdTrack.h
- PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update muon analysis
> [PWGEM/Dilepton] update muon analysis

- PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: reduce calling CCDB
> [PWGEM/Dilepton] reduce calling CCDB

- PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: fix in skimmerPrimaryMuon.cxx
> [PWGEM/Dilepton] fix in skimmerPrimaryMuon.cxx

- Common/TableProducer/fwdtrackPropagation.cxx
Common: update refit global muon in fwdtrackPropagation.cxx
> [Common] update refit global muon in fwdtrackPropagation.cxx

- PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
Fix an error introduced by #10681.
> [PWGCF/FemtoUniverse] Fix hPt_Primary histogram name

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Trivial hot fix for `doprocessMCRun2`
> [PWGCF] JFlucEfficiencyTask  - Add MC histo flag check for run2

- Common/Core/fwdtrackUtilities.h
- Common/TableProducer/fwdtrackPropagation.cxx
> [Common] update DCA with MFT

- PWGCF/Flow/Tasks/flowGfwOmegaXi.cxx
Add closure test
Optimize some code
> [PWGCF] Add closure test

- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/Tasks/CMakeLists.txt
- PWGEM/Dilepton/Tasks/matchingMFT.cxx
PWGEM/Dilepton: add a task to study MFT-matching
> [PWGEM/Dilepton] add a task to study MFT-matching

- Common/TableProducer/fwdtrackPropagation.cxx
Common: update minRabs for global muons in fwdtrackPropagation.cxx
> [Common] update minRabs for global muons in fwdtrackPropagation.cxx

- PWGLF/Tasks/Nuspex/angularCorrelationsInJets.cxx
> [PWGLF] debugging angular correlation pp histo filling

- PWGLF/DataModel/LFHypernucleiTables.h
- PWGLF/TableProducer/Nuspex/hyperRecoTask.cxx
adding the information on the amplitude to compute flow with scalar product
@skundu692 can you have a quick look? :)
> [PWGLF] adding Q-vec amplitude to switch to SP flow

- PWGJE/Tasks/jetSpectraCharged.cxx
1. fix a bug of fillTrackHistograms() in processQC function
2. Add a new histogram to fill MCP weighted events
> [PWGJE] fix tracks hist and add fill MCP weighted events

- PWGJE/Tasks/jetShape.cxx
I modified the histograms used to calculate purity from the perspective of memory consumption.
> [PWGJE] Fix histgrams for PID

- PWGLF/Tasks/Nuspex/angularCorrelationsInJets.cxx
yield analysis already implemented in antinucleiInJets.cxx
> [PWGLF] angularCorrelationsInJets.cxx: fixed track filter, cleared up task

- PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
- PWGLF/Tasks/Nuspex/CMakeLists.txt
- PWGLF/Tasks/Nuspex/NucleitpcPbPb.cxx
task for analysis of nuclei in Pb-Pb
> [PWGLF] task to for nuclei

- PWGJE/Tasks/nucleiInJets.cxx
Hi @nzardosh,
Please approve the PR once the tests are passed. Have a nice weekend.
Many thanks.
> [PWGJE] Histograms for MC study

- EventFiltering/PWGHF/HFFilter.cxx
- EventFiltering/PWGHF/HFFilterHelpers.h
Hi @fgrosa, Is it Ok? I only change the mass hypothesis from pion to kaon.
> [PWGHF,Trigger] Add Bc decay to D0K into the HF filter

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
- PWGEM/Dilepton/Tasks/matchingMFT.cxx
> [PWGEM/Dilepton] add BC info

- EventFiltering/PWGEM/HeavyNeutralMesonFilter.cxx
- PWGEM/PhotonMeson/Tasks/HeavyNeutralMeson.cxx
Separated the omega and eta' mass/pT histogram from one another and some general clean up
> [PWGEM/PhotonMeson,EventFiltering] Separate omega and eta' QA histogram

- PWGHF/D2H/Tasks/taskSigmac.cxx
> [PWGHF] small bug fixed in sigmaC task, add Thns for gen level

- PWGLF/Utils/strangenessBuilderHelper.h
> [PWGLF] protect against empty / problematic DFs

- PWGJE/Tasks/jetFragmentation.cxx
- PWGJE/Tasks/v0QA.cxx
Jet Fragmentation:
* Weighting method for background subtraction implemented and checked
* Prevent double filling of histograms
V0 QA: check for V0s with 3+ flags
> [PWGJE] Jet Fragmentation & V0 QA

- PWGJE/Tasks/phiInJets.cxx
Dear expert, 
To prevent memory leaks related to histograms, I have changed the histogram type to THnSparse. 
Additionally, I added a configuration option to adjust the mass range. 
I kindly request your review and approval of the PR
Best regards, 
Jimun
> [PWGJE] phiInJets.cxx : Adding a configuration to adjust the mass range and changhing the type of histogram

- PWGEM/Dilepton/Tasks/matchingMFT.cxx
PWGEM/Dilepton: update matchingMFT.cxx
> [PWGEM/Dilepton] update matchingMFT.cxx

- PWGLF/DataModel/LFStrangenessTables.h
- PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt
- PWGLF/TableProducer/Strangeness/Converters/straevselsconverter5.cxx
- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
- PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Add RCT flag bits in the strangeness data model (introduction of a new version of StraEvSels: StraEvSels_004 --> StraEvSels_005)
- Add converters for StraEvSels table
- Add option to select on the RCT flags at analysis task level
> [PWGLF]  Add RCTFlagsChecker in strangeness data model

- PWGUD/DataModel/UDIndex.h
- PWGUD/TableProducer/CMakeLists.txt
- PWGUD/TableProducer/tauEventTableProducer.cxx
- PWGUD/TableProducer/udMcCollisions2udCollisions.cxx
- PWGUD/TableProducer/udMcParticles2udTracks.cxx
Adding new function to table producer, which should run over truth and store its reco info (if any). To associate truth to reco two new helper tasks are introduced.
> [PWGUD] TauTable producer preparation for MC

- PWGLF/Tasks/GlobalEventProperties/heavyionMultiplicity.cxx
1) Modification in MC process function
2) Add process functions for pp
> [PWGLF] PWGLF/Tasks/GEP/heavyionMultiplicity.cxx: rework on the task

- PWGDQ/Core/CutsLibrary.cxx
New event selection added in CutsLibrary.cxx
> [PWGDQ] Adding new event selection called eventStandardSel8VtxQuality1

- PWGJE/Tasks/recoilJets.cxx
Add new histograms; add functionality to skip the MB events with gap for MC production
New feature: study the outlier removal impact on the track pT spectrum.
> [PWGJE] Code update for hadron-jet analysis

- PWGJE/Tasks/jetChargedV2.cxx
delta pT process: removes the leading jet η–ϕ band from the random cone selection in delta pT; 
tracksQA process: prepare trackong efficiency process; 
remove some test plots
> [PWGJE] removes the leading jet η–ϕ band from the random cone selection in delta pT; prepare trackong efficiency process; remove some test plots

- PWGJE/Tasks/dijetFinderQA.cxx
remove unnecessary parts and rename the parameters for clarity
> [PWGJE] PWGJE:dijet mass analysis task

- PWGCF/Tasks/correlations.cxx
adding delta phi differential histograms
> [PWGCF] adding delta phi differential histograms

- PWGLF/Tasks/Strangeness/lambdalambda.cxx
> [PWGLF] fixing bug

- PWGLF/Tasks/Strangeness/taskLambdaSpinCorr.cxx
Possible solution for hyperloop errors
> [PWGLF] removed unnecessary table subscriptions

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
remove useless configurations and tables
change some of configuration name
> [PWGLF] remove useless configurations and tables and change configuration names

- PWGJE/Tasks/fullJetSpectraPP.cxx
This PR includes the following:
- updated and consistent event selections
- new QA histos for unfolding
- includes two new process functions to study the multiplicity dependence of full jets and NEF
> [PWGJE] process function to study multiplicity dependence of fulljets and NEF

- PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
PDG check added in process doMCRecTrackTrack() in femtoUniverseEfficiencyBase.cxx
> [PWGCF] FemtoUniverse - update in  efficiency base task

- Scripts/o2_linter.py
Fix GitHub annotations with line number 0 which were not displayed.
> O2 linter: Fix position of per file messages

- CODEOWNERS
Updating codeowner rights according to the current Strangeness and Global Event Properties PAG coordinators: @romainschotter and @abmodak
> [Infrastructure] Updating codeowner rights for PAG Strangeness and GEP

- PWGJE/Tasks/nucleiInJets.cxx
Please approve the PR once the tests are done.
Have a nice evening.
Arvind
> [PWGJE] Added abs value for nSigmaTPC

- PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- Fix V0/Casc MC mother table filling in case "mcMotherParticleId" = -1
@ddobrigk for your information
> [PWGLF] Fix V0/Casc MC mother table filling

- PWGJE/Tasks/phiInJets.cxx
Dear expert,
Hello, I am Jimun
I was trying to run the code on Hyperloop, but due to memory consumption issues, I couldn't execute it properly.
To address this, I organized the process by using switches to obtain only the essential histograms.
*[PWGJE: phiInJets.cxx]
Thank you
Jimun Lee
> [PWGJE] Organized histograms by switch

- PWGHF/Tasks/taskPidStudies.cxx
@fchinu here the fix we discussed yesterday.
> [PWGHF] Add track sel. QA histogram and fix bug in applying track and event sels.

- PWGEM/Dilepton/Tasks/CMakeLists.txt
- PWGEM/Dilepton/Tasks/taggingHFE.cxx
PWGEM/Dilepton: add a task to study tagging HFE in MC
> [PWGEM/Dilepton] add a task to study tagging HFE in MC

- Common/TableProducer/Converters/CMakeLists.txt
- Common/TableProducer/Converters/trackQA003Converter.cxx
Goes with https://github.com/AliceO2Group/AliceO2/pull/14144 and substitutes https://github.com/AliceO2Group/O2Physics/pull/10748 from @f3sch
> [Common] Add TrackQAConverter003

- PWGJE/Tasks/phiInJets.cxx
Dear experts,
Hello I'm Jimun
I have been continuously optimizing the code to reduce the computational load when running the Hyperloop.
I further refined it so that the computations are executed only when the specific configuration is run.
+ The previous one was closed, so I’ve submitted it again
Thank you
Best regards,
Jimun Lee
> [PWGJE] Reduced the process of calculation corresponding to the configuration in phiInJets.cxx

- CODEOWNERS
Pinging @skundu692 , @sustripathy , @njacazio
> [Infrastructure] Update LF codeowners

- PWGLF/TableProducer/Strangeness/hStrangeCorrelationFilter.cxx
- PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
add a simple correction for a check, implentation of O2 linter warnings fix
> [PWGLF] change in PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx

- PWGHF/TableProducer/candidateCreator3Prong.cxx
@fchinu this should solve what you observed yesterday
> [PWGHF] Fill proton PID info only if necessary, to save memory.

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- synced the task with the changes in the cascade filter
- implemented refined cascade pile up check by rejecting cascades sharing a daughter
- O2 linter fixes
> [PWGCF] FemtoUniverse cascade task -- refined cascade pile up check

- PWGLF/Tasks/GlobalEventProperties/dndeta-mft-pp.cxx
New control histograms for normalization in MFT analysis
> [PWGLF] New control histograms for normalization in MFT analysis

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
Add a flag for track's index
change some configuration names
> [PWGLF] Add a configuration flag and change configuration names

- PWGHF/TableProducer/candidateCreatorDstar.cxx
Fixing bug due wrong Track table type subscribed in process function
> [PWGHF/D2H] Fixing bug due wrong Track table type subscribed in process function

- PWGEM/Dilepton/Core/DielectronCut.h
Fixed typo in the definition of the pion rejection in the TOF sample
> [PWGEM] LMee: lowB PID fix

- PWGEM/Tasks/phosElId.cxx
PHOS tag and probe method remade for TPC
added Sel8 event flag
removed unused histograms, histograms now use directories
new histograms for CPV trackmatching, will be used for comparisions
> [PWGEM] phosElId TPC efficiency checker

- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/mcGeneratorStudies.cxx
- Task that produces a 2D histogram with the pT spectrum of any particle on one, and the event multiplicity on the other axis
> [PWGEM/PhotonMeson] Add task for on-the-fly MC generator studies

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding a pT vs invM vs mult histogram to Cascade task.
> [PWGCF] FemtoUniverse - Adding a pT vs invM vs mult histogram to Cascade task

- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: update skimmerPrimaryElectron.cxx to reduce memory
> [PWGEM/Dilepton] update skimmerPrimaryElectron.cxx to reduce memory

- PWGHF/TableProducer/treeCreatorTccToD0D0Pi.cxx
- add a flag for vertex build 
- fix the issue of CPU time consumption by moving the vertex rebuild into the innermost loop
> [PWGHF] add a flag for vertex build and fix the issue of CPU time consumption 

- EventFiltering/filterTables.h
> [Trigger] Fix the Heavy Neutral Meson Filter description

- PWGJE/Tasks/jetHadronRecoil.cxx
For studying the pT differential distributions in eta and phi
> [PWGJE] Adding inclusive jet 3D histograms

- .mega-linter.yml
- cppcheck_config
Defines a list of suppressed errors which result from false positives.
> [Infrastructure] MegaLinter: Configure cppcheck

- PWGEM/Tasks/phosElId.cxx
minor fixes
removed unused histograms
fixed tag-n-probe prefilters
> [PWGEM] phosElId.cxx code refactored

- EventFiltering/PWGCF/CFFilterAll.cxx
Fix the filling and naming scheme of some histograms.
> [Trigger,PWGCF] Fix histogram filling/naming

- ALICE3/TableProducer/alice3-decayfinder.cxx
- added further plots for efficiency evaluation
- separate mass plots for signal, reflection, and background contributions
- further minor tweaks
> [ALICE3] Updates to decay finder for integration with DDbar correlations

- PWGJE/Tasks/dijetFinderQA.cxx
clean up dijetFinderQA.cxx 
modify the original algorithm
> [PWGJE] update dijetFinderQA.cxx

- CODEOWNERS
Approved by PWG-LF conveners and Physics Coordination
> [Infrastructure] Adding Omar Vazquez as code owner for PWGLF PAG-GEP

- PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
Needed to compute the efficiencies for non-prompt analysis
> [PWGLF] Store also secondaries for MC generated particles

- ALICE3/TableProducer/alice3-decayfinder.cxx
- New topological variables on decay length for LoI compatibility
- Evaluate topological cut distributions for S and B separately, to check cuts effectiveness
> [ALICE3] Further refinements to decay finder code

- ALICE3/TableProducer/alice3-decayfinder.cxx
- Added mcTruth cases for topological distribution histogram filling
- Bug fix on histogram name from previous commit
> [ALICE3] Completing separation of topological distribution for S and B

- PWGDQ/Core/VarManager.h
Update VarManager.h to correct the cos theta definition in the production plane
> [PWGDQ] Update VarManager.h to correct the cos theta definition in PP frame

- PWGLF/Tasks/Strangeness/cascadecorrelations.cxx
Split the cascade selector process in 2, needed for MC matching. Also added MC generator level process.
> [PWGLF] Implement MC processes in cascade selector

- PWGLF/Tasks/Resonances/CMakeLists.txt
- PWGLF/Tasks/Resonances/lstaranalysis.cxx
This is standalone task to reconstruct Lambda1520 resonance
> [PWGLF] Initial commit of lstaranalysis task

- PWGHF/TableProducer/treeCreatorOmegacSt.cxx
reset decayChannel=1 when decay Channel not recongized
> [PWGHF] reset decayChannel=1

- PWGHF/HFC/Tasks/taskCorrelationDplusHadrons.cxx
Selection of prompt or non-prompt scores within a defined range to implement the data-driven method for prompt/FD subtraction.
> [PWGHF] Selection of prompt and non-prompt scores within a defined range

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/DimuonCut.cxx
- PWGEM/Dilepton/Core/DimuonCut.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: update in DimuonCut
> [PWGEM/Dilepton] update in DimuonCut

- PWGJE/Tasks/jetShape.cxx
I added some track selection conditions, and corrected incorrect calculations in the jetShape.cxx.
> [PWGJE] improvement of the track selection in jetShape.cxx

- PWGLF/Tasks/Strangeness/strangenessInJets.cxx
> [PWGLF] Fix the reweighting for cascades in MC + temporarily disabling histograms for secondary lambdas

- PWGJE/Tasks/recoilJets.cxx
Instead of removing an outlier jet, now the code excludes the whole event
> [PWGJE] PWGJE Change scheme for outlier removal

- PWGCF/Flow/Tasks/flowGfwOmegaXi.cxx
Add V0 and cascade v3{2}
Optimize configurable variable of track selections and builder options
Add ITS nsigma and track quality cut
Separate K0s, Lambda, Xi and Omega's axis
Some change for apass5 data
> [PWGCF] Add v3 flow and optimized track selection

- PWGLF/Tasks/Strangeness/v0ptinvmassplots.cxx
> [PWGLF] v0ptinvmassplots: Added INEL>0

- PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- Refactored the cascade tables to use FDParticle instead of FDCascParticle for protons
- Optimized the task to be compatible with the changes
> [PWGCF] FemtoUniverse cascade task -- Refactored the cascade tables to utilize FDParticle

- PWGHF/D2H/Tasks/taskSigmac.cxx
- PWGHF/DataModel/CandidateReconstructionTables.h
- PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx
> [PWGHF] add soft-pi dcaXY, dcaZ to SigmaC THnSparse.

- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
- PWGDQ/Tasks/tableReader_withAssoc.cxx
- PWGLF/Tasks/Resonances/higherMassResonances.cxx
B meson table (used for PWG-DQ 120) extended with features, to match that in tableReader. 
tableReader_withAssoc: changed from using pT of the legs and associated track to pIN.
> [PWGDQ] Tasks/dqEfficiency_withAssoc: Extended B meson table

- PWGLF/Tasks/Resonances/lstaranalysis.cxx
Added switch for rapidity and eta cut
> [PWGLF] update MC process

- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
> [PWGEM/Dilepton] upadte ITSsa

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: fix for thresholds in PID ML
> [PWGEM/Dilepton] fix for thresholds in PID ML

- PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
- Added configurable axis for pt, y, angles, and inv mass histograms
- Added Filtering the tables by occupancy
- Added option to enable or disable the TOF requirement that at least one TOF is required for event selection
- Modified the MC to work without the occupancy (will have to change it later)
> [PWGUD] Modified Occupancy and TOF COnditions

- PWGCF/EbyEFluctuations/Tasks/meanPtFlucId.cxx
Modified the PID selection task to have better purity.
> [PWGCF] Update meanPtFlucId.cxx

- PWGHF/Core/HfHelper.h
- PWGHF/TableProducer/mcPidTof.cxx
@fgrosa Can you please check whether the default values in `mcPidTof` can potentially be used anywhere in the code?
> [PWGHF] Fix argument copies and uninitialised members

- PWGCF/FemtoDream/Tasks/CMakeLists.txt
- PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrackPbPb.cxx
Summer student project on PbPb three-body femtoscopy.
Separate task from pp collisions until benchmarked also on hyperloop and finalized.
> [PWGCF] Add producer task for Pb-Pb collisions with centrality filter

- PWGHF/D2H/Macros/compute_fraction_cutvar.py
- PWGHF/D2H/Macros/config_cutvar_example.json
- PWGHF/D2H/Macros/cut_variation.py
Critical issues (preventing from script running) fixed:
- module `utils.style_formatter` replaced with `style_formatter` as it appears in the script folder
- `itemset` replaced with `[...] = ...` assignment in order to be compatible with `NumPy 2.x`
Not critical issues
- added check for not being a **nullptr** for histograms read from file
- reduced code duplication when printing histograms into pdf
- get rid of warnings about having histograms and canvases with the same string name
Plot enhancement
- added text line with pT bin number and ranges to each pdf with plots
> [PWGHF] Cut variation - enhance plotting features, minor code cleaning and chore

- PWGLF/Tasks/Strangeness/cascadecorrelations.cxx
Also move autocorrelation check to dedicated function, and added track Chi2 selections
> [PWGLF] Add signs to THnSparses, change logic accordingly

- PWGCF/FemtoUniverse/Core/FemtoUniverseContainer.h
- PWGCF/FemtoUniverse/Core/FemtoUniversePairCleaner.h
- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- PWGCF/FemtoUniverse/Tasks/CMakeLists.txt
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskV0CascadeExtended.cxx
- combined v0-cascade dataset
- v0-cascade pair cleaner
- v0-cascade correlation task
- fixed typos
> [PWGCF] FemtoUniverse V0Cascade task -- combined v0-cascade dataset & v0-cascade correlation task

- PWGEM/Dilepton/DataModel/lmeeMLTables.h
- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: reduce data size of tree ML DDA
> [PWGEM/Dilepton] reduce data size of tree ML DDA

- PWGJE/Tasks/trackEfficiency.cxx
- separate collision processes
- add ptHard vs ptHard with weight and hepmcxsection methods
- add MC pt res
> [PWGJE] trackEfficiency workflow additions

- PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
- added few more histograms too
> [PWGUD] Modified a wrongly placed histogram for four pion pt

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
optimized track index selection using template
fixed PID selection like ref
> [PWGLF] optimized track index selection and fixed PID selection

- Common/TableProducer/eventSelection.cxx
- PWGLF/Tasks/Resonances/chk892Flow.cxx
Occupancy axis was added for charged K* analysis and invariant distribution of K0s was modified to be filled.
> [PWGLF] chk892Flow.cxx : Added occupancy axis and fill invariant mass distribution for K0s

- PWGHF/D2H/Tasks/taskSigmac.cxx
@Mingyu3360715 this should fix the issue with the `ConfigurableAxes`
> [PWGHF] Σc0,++: fix configurable axes in Sigmac task.

- PWGCF/Flow/Tasks/CMakeLists.txt
- PWGCF/Flow/Tasks/flowEseTask.cxx
Add files for task of flow and event shape engineering correlation with other observation.
> [PWGCF] [PWGCF]Add files for ese calculation

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerMCTruthTask.cxx
Changes:
- zvtx cut added
- O2 linter issues fixed
- headers order changed 
- some unused configurables removed
> [PWGCF] FemtoUniverse - MCTruth producer update

- PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
- Removed 2 configurables: ifPass5 and checkOneTOF
- Removed MC gen and MC reco process. (Newer one will be implemented later)
- Added 2 more columns in the derived data tables: Run Number and hasAtleastOneTOF
> [PWGUD] Removed different cuts for different datasets

- PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
Sorry for the mistake. I have found another issue with the histogram definition. Fixed now.
Cheers,
Samuele
> [PWGHF] Ds-h correlation - Fixing bug on histograms

- PWGEM/Dilepton/DataModel/lmeeMLTables.h
- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: remove muon columns from treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] remove muon columns from treeCreatorElectronMLDDA.cxx

- PWGCF/Flow/Tasks/flowEsePHe3.cxx
updates on ESERef selection and also V2 Tar and Ref self correction
> [PWGCF] updates on ESERef selection

- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/Tasks/createResolutionMap.cxx
This PR contains follow commits:
add possibility to use ITSsa in createResolutionMap.cxx,
add configurable for narrow DCAee bins
> [PWGEM/Dilepton] add possibility to use ITSsa in createResolutionMap.cxx

- PWGJE/Tasks/jetShape.cxx
We added a new axis to tpcDedx and tofBeta.
We also made the bin number, as well as the minimum and maximum values, in tpcTofPr and tpcTofPi configurable.
> [PWGJE] add new histgrams

- PWGEM/Dilepton/TableProducer/skimmerOTS.cxx
> [PWGEM/Dilepton] fix bc in OTS

- PWGLF/Tasks/Resonances/f0980analysis.cxx
Apply TPC and TOF cuts for PID, depending on the availability of TOF.
> [PWGLF] Add the PID option for using TOF

- PWGEM/Dilepton/Core/DielectronCut.cxx
- PWGEM/Dilepton/Core/DielectronCut.h
- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/Core/SingleTrackQCMC.h
Add the possibility to select phi regions (MFT services or not for example)
> [PWGEM] Add the possibility to select Phi regions

- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx
PWGEM/Dilepton: add mc label of MFTTracks
> [PWGEM/Dilepton] add mc label of MFTTracks

- Scripts/format_includes.awk
Fixes include style:
- `#include "header"`: O2Physics and other local-looking files
- `#include <header>`: anything else
> Add script to fix include style

- PWGEM/Dilepton/DataModel/dileptonTables.h
- PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: update for tpc
> [PWGEM/Dilepton] update for tpc

- PWGHF/D2H/TableProducer/dataCreatorJpsiHadReduced.cxx
- PWGHF/TableProducer/candidateCreator2Prong.cxx
Also added some additional control histograms in `candidateCreator2Prong.cxx`
> [PWGHF] Select correct hfflag when running JPsiToee

- PWGLF/Tasks/Strangeness/lambdapolsp.cxx
several closure/null tests of polarization by randomizing phi*, psi and phi of lambda by various mixing styles
> [PWGLF] added histogram for resolution in mixed events and option for randomizing psi and process function for fifo mixing

- PWGJE/Tasks/triggerCorrelations.cxx
* Added an offline process for trigger correlation studies
> [PWGJE] Trigger Correlations:

- PWGHF/HFL/Tasks/CMakeLists.txt
- PWGHF/HFL/Tasks/taskSingleElectron.cxx
implement the previous comments.
> [PWGHF] eID study for single electron analysis

- PWGEM/Dilepton/Utils/EventHistograms.h
- PWGEM/PhotonMeson/Core/DiphotonHadron2PC.h
- PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/CMakeLists.txt
- PWGEM/PhotonMeson/Tasks/diphotonHadron2PCPCMDalitzEE.cxx
- PWGEM/PhotonMeson/Tasks/diphotonHadron2PCPCMPCM.cxx
- PWGEM/PhotonMeson/Tasks/prefilterPhoton.cxx
- PWGEM/PhotonMeson/Utils/EventHistograms.h
PWGEM/PhotonMeson: add a task for diphoton-hadron 2PC
> [PWGEM/PhotonMeson] add a task for diphoton-hadron 2PC

- PWGHF/HFC/DataModel/DerivedDataCorrelationTables.h
- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I have added the possibility to produce derived data for the correlations allowing for the selection of specific particles based on PID selections.
Cheers,
Samuele
> [PWGHF] Ds-h correlation, adding separation in PID

- Common/Tasks/qaMuon.cxx
- PWGLF/Tasks/Strangeness/phik0shortanalysis.cxx
Added multidimensional histograms to study the muPos and muNeg as a function of dimuon pT and invariant mass.
Fixed MegaLinter warnings
> [Common] Added dimuon-muon correlations to muonQA

- PWGHF/D2H/Macros/HFInvMassFitter.cxx
- PWGHF/D2H/Macros/config_massfitter.json
- PWGHF/D2H/Macros/runMassFitter.C
I can see @lubynets works on refactoring the D2H fitter -- what do you think about adding these functionalities?
> [PWGHF] D2H fitter: Add possibility to set fixed manual mean and second sigma for double gauss

- PWGLF/Tasks/Resonances/lambda1520analysisinpp.cxx
- PWGLF/Utils/collisionCuts.h
1. Added new process function for rotational method
2. Improved efficiency of the analysis task
3. Added a switch for QA plots in collisionCuts.h
> [PWGLF] Added new process function for rotational method 

- PWGLF/Tasks/Resonances/kstarInOO.cxx
Dear Conveners in LF,
I updated the parts of the invariant mass distributions in SE, ME. 
Once it works well in the hyperloop, I will upload more. 
Thank you
Jimun Lee
> [PWGLF] Added the part of same event of KstarInOO.cxx

- Common/Tasks/qaMuon.cxx
Memory issues orignated from the too fine binning of 3 dimensional histograms in the previous PR
> [Common] Fixed memory issues with 3D histograms

- PWGLF/Tasks/Strangeness/CMakeLists.txt
- PWGLF/Tasks/Strangeness/lambdaTwoPartPolarization.cxx
- PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
initial commit on polarization correlations
> [PWGLF] initial commit on polarization correlations

- PWGEM/Dilepton/Core/DileptonHadronMPC.h
- PWGEM/Dilepton/Core/EMTrackCut.cxx
- PWGEM/Dilepton/Core/EMTrackCut.h
- PWGEM/PhotonMeson/Core/DiphotonHadronMPC.h
- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
PWGEM/Dilepton: update EMTrackCut
> [PWGEM/Dilepton] update EMTrackCut

- PWGLF/Tasks/Resonances/f0980pbpbanalysis.cxx
> [PWGLF] Added eventmixing histogram

- PWGLF/Tasks/Strangeness/lambdaTwoPartPolarization.cxx
> [PWGLF] adding cosine axis

- DPG/Tasks/AOTEvent/detectorOccupancyQa.cxx
propagation of phi to the inner radius of the TPC; bugfix for negative tracks; flag to study phi distributions on A- and C-sides separately
> [DPG] more options for phi-dependent study

- PWGLF/Tasks/Strangeness/strangenessderivedbinnedinfo.cxx
@miranov25 for your information
> [PWGLF] Add 2 extra dimensions: PtArmV0 and AlphaV0

- PWGJE/Tasks/recoilJets.cxx
Add some new features:
1) Outlier removal from JE framework
2) Add histograms for ZDC and FT0 signals
> [PWGJE] Add multiplicity selection

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
- PWGEM/Dilepton/TableProducer/skimmerPrimaryTrack.cxx
- PWGEM/Dilepton/Tasks/Converters/electronConverter4.cxx
> [PWGEM/Dilepton] fix to #12343

- PWGEM/Dilepton/Core/DileptonHadronMPC.h
PWGEM/Dilepton: quick fix in 2PC
> [PWGEM/Dilepton] quick fix in 2PC

- PWGCF/TwoParticleCorrelations/Tasks/diHadronCor.cxx
- PWGLF/TableProducer/Strangeness/cascadeflow.cxx
> [PWGLF] fix index for bkg candidates

- PWGJE/Tasks/jetHadronRecoil.cxx
This histogram has caused a bug within O2, I don't think we need it in hindsight so its getting removed
> [PWGJE] Removing random track historam

- Common/TableProducer/qVectorsTable.cxx
eta selection with configurable
> [Common/EventPlane] eta selection with configurable

- PWGLF/Tasks/Strangeness/lambdaTwoPartPolarization.cxx
adding sign for two particle polarization
> [PWGLF] adding sign for two particle polarization

- PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
PWGEM/PhotonMeson: reduce data size of ele from dalitz
> [PWGEM/PhotonMeson] reduce data size of ele from dalitz

- PWGEM/Dilepton/TableProducer/filterEoI.cxx
PWGEM/Dilepton: remove unnecessary function in filterEoI.cxx
> [PWGEM/Dilepton] remove unnecessary function in filterEoI.cxx

- PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- added zorro software trigger to be used for v0-cascade analysis
- all the configurations under colcut class had to be grouped to reduce the number of class attributes and for compilation to work
- removed some unused commented configurable
> [PWGCF] FemtoUniverse v0cascade task -- added zorro software trigger

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding setPDGCodes to set particle mass for same and mixed event container in cascade task.
> [PWGCF] FemtoUniverse - Adding PDG mass for same and mixed event container in cascade task.

- PWGHF/Core/DecayChannels.h
- PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
- PWGHF/Utils/utilsMcMatching.h
This PR implements the MC matching of D*->D0pi in resonances workflow for correlated background studies
> [PWGHF]  Charm resonances: Matching of D*->D0pi

- PWGUD/Tasks/upcTauTau13topo.cxx
New 2D histos (m3pi vs aco),
new variables (track DCA, TPC chi2, ITS chi2, rct) in tau tree,
MC histograms properly defined in different processes
> [PWGUD] New 2D histos and vars (tracks, rct) in tau tree

- PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Hi @fgrosa , 
I have tried to implement weight method to calculate centrality at generator level by taking ratio of PvContribution histograms from Data and MCRec.  Can you check if it looks fine and let me know any modification needed?
> [PWGHF/D2H] Add weight method to achieve centrality at generator level

- PWGJE/Tasks/jetShape.cxx
added  nσ distribution histogram for the perpendicular cone to calculate purity of pion and proton in the perpendicular cone.
> [PWGJE] Addition of nσ distribution plot for the perpendicular cone.

- PWGEM/Dilepton/TableProducer/filterEoI.cxx
PWGEM/PhotonMeson: fix in filterEoI.cxx
> [PWGEM/PhotonMeson] fix in filterEoI.cxx

- PWGCF/Femto3D/DataModel/singletrackselector.h
- PWGCF/Femto3D/Tasks/femto3dPairTask.cxx
- PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx
- PWGCF/Femto3D/Tasks/femto3dQA.cxx
added  ITSlayersall cut for the event selection
> [PWGCF] added Event_cut for removing time ranges with dead ITS - dips

- PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx
PWGEM/Dilepton: add eoi in MC for consistency
> [PWGEM/Dilepton] add eoi in MC for consistency

- PWGCF/MultiparticleCorrelations/Tasks/threeParticleCorrelations.cxx
Changed the configuration of the trackFilters function to be compatible with the new Z-vertex limit.
> [PWGCF] Changed the configuration of the trackFilters function

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Helicity.cxx
Add extra histograms to helicity analysis.
> [PWGCF] FemtoUniverse -- Add extra histograms to helicity analysis.

- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h
- PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
- PWGEM/PhotonMeson/Core/TaggingPi0MC.h
PWGEM/PhotonMeson: reduce dependency in MC
> [PWGEM/PhotonMeson] reduce dependency in MC

- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: add option to require TOF in treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] add option to require TOF in treeCreatorElectronMLDD.cxx

- PWGEM/Dilepton/DataModel/lmeeMLTables.h
- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: add tpcNClsPID in treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] add tpcNClsPID in treeCreatorElectronMLDDA.cxx

- PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- PWGEM/PhotonMeson/Core/DiphotonHadronMPC.h
- Add PID process for study
- Add TPC sector dependence check
- Add pT uncertainty histogram
> [PWGCF] jFlucEfficiencyTask - Modify structure and add systematic study histograms

- PWGEM/Dilepton/Tasks/taggingHFE.cxx
PWGEM/Dilepton: update taggingHFE.cxx
> [PWGEM/Dilepton] update taggingHFE.cxx

- PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Improving daughter nSigma selection in  processCascadeQA for Cascade task to use the same functions as doSameEvent. Removing unused configurables.
> [PWGCF] FemtoUniverse - Improving daughter nSigma selection in  processCascadeQA for Cascade task

- PWGHF/TableProducer/treeCreatorOmegac0ToOmegaPi.cxx
Needed for the analysis vs multiplicity. @mtorresc15
> [PWGHF] Add number of PV contributors to OmegaC trees

- PWGDQ/DataModel/ReducedInfoTables.h
- PWGDQ/Tasks/dqEfficiency.cxx
- PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
- PWGDQ/Tasks/tableReader.cxx
- PWGDQ/Tasks/tableReader_withAssoc.cxx
Pseudo-proper decaylength variables added to DielectronAll table
> [PWGDQ] added variables to DielectronAll table

- PWGHF/HFC/TableProducer/correlatorDstarHadrons.cxx
Hi @fgrosa, 
I have just added a single QA hist for multiplicity distribution.
Please have a look and let know if suggestion. Thanks
> [PWGHF/HFC] adding a new QA histogram for multiplicity

- .github/workflows/stale.yml
As documented here
https://github.com/actions/stale/blob/8f717f0/README.md#recommended-permissions
CC @vkucera
> [Infrastructure] Fix stale action permissions

- PWGHF/HFL/Tasks/taskElectronWeakBoson.cxx
- PWGLF/Tasks/Strangeness/lambdaTwoPartPolarization.cxx
> [PWGLF] updating the mixing for V0s

- PWGHF/HFL/Tasks/taskSingleElectron.cxx
> [PWGHF] Add TPC nSigma vs P

- PWGCF/Tasks/correlations.cxx
add deta differential study
fix bug for V0
> [PWGCF] add deta differential study

- PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: add axis for acc in generated hs
> [PWGEM/Dilepton] add axis for acc in generated hs

- CODEOWNERS
I haven't reviewed any CF PRs for quite some time, and I won't be available for a long time. Other WUT people do the reviews.
> [Infrastructure] Remove me from CF-related codeowners

- PWGJE/Tasks/recoilJets.cxx
Update adding the histogram which contains the correlation between scaled FT0M signal and ZNA vs ZNC
> [PWGJE] correlation scaled FT0M vs ZNA vs ZNC

- PWGHF/D2H/DataModel/ReducedDataModel.h
- PWGLF/Tasks/Resonances/higherMassResonances.cxx
Sign column was uint8_t, changed to int8_t
> [PWGHF] Fix sign column in reduced workflow

- PWGMM/Mult/Tasks/dndetaMFTPbPb.cxx
Major: 
- Added new method for track reassociation based on propagateToDCAhelix
Minor:
- Added new event selection based on RCT flags
- Added basic correlation histos Nch/PV tracks vs FT0C
> [PWGLF] Added new method for track reassociation

- Common/Tools/TrackPropagationModule.h
Also adds a printout warning about potential correctness issues. Relevant for @rspijkers
> [Common] Enable interdependency autoenable

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: update polarization frame
> [PWGEM/Dilepton] update polarization frame

- PWGLF/Tasks/Strangeness/lambdaJetpolarization.cxx
Dear Experts:
The recent code is mainly used to calculate Lambda local polarization
I have two .cxx files and one header file to complete my analysis.These codes have been updated.
TableProducer : lambdaJetpolarizationbuilder.cxx : The file has not been modified.
Tasks ：lambdaJetpolarization.cxx : The configurable axis for pT and the invariant mass have been modified.
DataModel : lambdaJetpolarization.h : The file has not been modified.
Best wishes,
Youpeng Su
Sep 11, 2025
> [PWGLF] The local polarization calculation

- PWGJE/Tasks/jetHadronRecoil.cxx
> [PWGJE] Adding process for running recoil jets with rho subtraction

- PWGLF/Tasks/Nuspex/LFNucleiBATask.cxx
- Change axis in pdgMom histogram, checking for sign 
- Optimise code
- Remove unused histograms 
- Add histogram for protons
> [PWGLF] NucleiTask - Change pdgMothers axis

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/SingleTrackQC.h
- PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
> [PWGEM/Dilepton] update mlpid

- PWGEM/Dilepton/Core/Dilepton.h
- PWGEM/Dilepton/Core/DileptonMC.h
- PWGEM/Dilepton/Core/PhotonHBT.h
PWGEM/Dilepton: remove acc axis in Gen
> [PWGEM/Dilepton] remove acc axis in Gen

- PWGHF/HFC/TableProducer/correlatorDsHadrons.cxx
Dear all,
I have just added the separation in LS and ULS paris in MC processes for studying Ds+-K+ and Ds+-K- correlations.
Cheers,
Samuele
> [PWGHF] Added particle sepatartion ULS and LS in MC process

- ALICE3/macros/a3geo.ini
Added initial ALICE3 geometry configuration in TEnv format.
> [ALICE3] Create a3geo.ini with ALICE3 geometry settings

- PWGJE/Core/JetMatchingUtilities.h
Also pass const vectors by reference.
> [PWGJE] JetMatchingUtilities: Simplify passing expressions as template arguments

- PWGLF/Tasks/QC/systematicsMapping.cxx
Updated the registration of reconstructed histograms to include additional parameters for K and K0s particles.
> [PWGLF] Enhance histogram registration for reconstructed particles

- PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update eventQC.cxx
> [PWGEM/Dilepton] update eventQC.cxx

- PWGLF/TableProducer/Strangeness/strangenesstofpid.cxx
> [PWGLF] Fix autodetection of old format in strangeness tof pid

- PWGLF/Tasks/Resonances/k892analysispbpb.cxx
Adding a preslice to fix processMC error: 
[ERROR] Exception while running: Disabled cache Tracks/fIndexCollisions is requested
> [PWGLF] k892analysispbpb.cxx - bug fix
