PWGCF/TwoParticleCorrelations/Tasks/lambdaR2Correlation.cxx
1. Modified the lambda selection methods
2. Added correction factor histograms from ccdb
=> [PWGCF] Update lambdaR2Correlation.cxx

PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx
Adding selection on antimatter for triton measurement in order to reduce the output of derived data, storing only antimatter candidates.
=> [PWGLF] Adding cut for selecting antitriton for tree saving

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Changes:
- inv. mass cut moved from process function to partitions
- configurables, functions and stuct naming changed according to the comments from O2 linter
- missing "const&" added
- ROOT entities replaced by c++ equivalents
- new process function in which QA plots are filled for selected D0 and D0bar candidates
=> [PWGCF] FemtoUniverse - D0 task update

PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/cascadecorrelations.cxx
This PR adds a rapidity cut and the ability to use the offline trigger selection through zorro.
It also fixes a bug in the ME by initializing the binning policy in the process function of the mixed events, as reported to the O2 analysis mattermost channel
=> [PWGLF] Add rapidity cut and trigger selection to cascade correlations task

PWGDQ/TableProducer/tableMaker_withAssoc.cxx
Attempting to fix CI regression
Bisect df9d954090
```
/System/Volumes/Data/build/alice-ci-workdir/o2physics/sw/SOURCES/O2Physics/8807/0/PWGDQ/TableProducer/tableMaker_withAssoc.cxx:567:37: error: non-constant-expression cannot be narrowed from type 'int64_t' (aka 'long long') to 'int' in initializer list [-Wc++11-narrowing]
std::vector<int32_t> evs = {collision.globalIndex()};
```
=> [PWGDQ] Fix vector type

PWGLF/DataModel/LFNonPromptCascadeTables.h, PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
This commit introduces several new features to the NonPromptCascadeTask:
1. Calculates the delta PT between the cascade and the ITS track, and stores it in the `DeltaPtITSCascade` column of the `NPCascTable`.
2. Adds a new column `HasReassociatedCluster` to the `NPCascTable` to indicate if the ITS track has reassociated clusters.
3. Modifies the `cpa` calculation to use the cascade momentum instead of a separate array.
4. Adds the `deltaPt` and `hasReassociatedCluster` fields to the `NPCascCandidate` struct and the corresponding `emplace_back` calls.
These changes aim to provide more detailed information about the non-prompt cascade candidates, which can be useful for further analysis and selection.
=> [PWGLF] feat: Add new features to the NonPromptCascadeTask

PWGJE/TableProducer/emcalCorrectionTask.cxx
- Shaper correction should only be applied for LG cells (oversight in O2Physics implementation), see 
https://github.com/alisw/AliPhysics/blob/master/PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx#L458
=> [PWGJE,EMCAL-670] Bugfix in EMCalCorrectionTask for ShaperCorrection

PWGHF/D2H/Tasks/taskLc.cxx
- Add MC Generated ThnSparse into the task
- Complete the ptB and tracklets into the task
=> [PWGHF] Add MC Generated ThnSparse in Lc task

PWGDQ/Core/VarManager.h
Square root of kVertexingLxy and kVertexingLz is taken after those quantities are used to calculate kVertexingLxyz
=> [PWGDQ] [PWGDQ-120] debug of definition of cosine of pointing angle in dilepton-track-vertexing/VarManager.h

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
PWGEM/Dilepton: update prefilter task
=> [PWGEM/Dilepton] update prefilter task

PWGUD/Tasks/upcJpsiCentralBarrelCorr.cxx
- Adjustment of MC true code to account for all studied decays.
- Addition of process function for reconstruction efficiency studies.
- Fix of incoherent studies.
=> [PWGUD] personal task modification

PWGCF/Tasks/correlations.cxx
adding decay mask to second track
separating d0 and t0bar into different dimension
=> [PWGCF] adding decay mask to second track

PWGLF/Tasks/Strangeness/lambdapolarization.cxx
daughter momentum from v0 table
=> [PWGLF] daughter momentum from v0 table

PWGEM/PhotonMeson/Tasks/emcalQC.cxx, PWGEM/PhotonMeson/Utils/ClusterHistograms.h
- In EMCalQC task: Change SkimEMCCluster to MyEMCCluster, containing the EMEventId
- Template "fillClusterHistograms" function to allow for this different cluster class
=> [PWGEM/PhotonMeson] Fix Cluster-Collision assignment in emcQC task

PWGCF/MultiparticleCorrelations/Tasks/ThreeParticleCorrelations.cxx
For the purpose of improving the track PID, the full TOF NSigma distribution has been added to the analysis.
=> [PWGCF] Added the full TOF NSigma distribution to the Track QA

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Tasks/vpPairQCMC.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/Dilepton: update dilepton HBT
=> [PWGEM/Dilepton] update dilepton HBT

Common/TableProducer/Converters/CMakeLists.txt, Common/TableProducer/Converters/trackQA002Converter.cxx
=> [Common] TrackQAConverter002- for TOF modification

EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterHelpers.h
Hi @fgrosa , @zhangbiao-phy ,
This is the first draft for reconstructing secondary vertices in triggers.
This PR is for testing the B+(->D0).
Selections (CPA, DecLength, ImpactParameterProduct) are implemented for beauty candidates.
=> [PWGHF,Trigger] Beauty 2nd Vertex in triggers

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/MCSignalLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/dqEfficiency_withAssoc.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
Add open charm MC analyses. Add cuts and histograms for cosine of pointing angle. Remove KKPi process function.
=> [PWGDQ] Add open charm MC analyses

PWGHF/HFC/Tasks/taskCharmHadronsFemtoDream.cxx
It can be done offline for mix-event tree, but do it online can help reduce the tree size
=> [PWGHF] Add pt and inv.mass cuts also in mixed event

PWGDQ/Tasks/quarkoniaToHyperons.cxx
- Add IsTriggerTVX selection
- Add treatement of K0s-K0s pairs (@dmallick2)
- Remove MegaLinter and O2Linter warnings (except for the ones regarding the configurable group, which makes things worse on Hyperloop)
=> [PWGDQ] Enable building K0s-K0s pairs

PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/jetHadronRecoil_OO.cxx, PWGJE/Tasks/recoilJets.cxx
A new task designed to study hadron-jet correlations in the upcoming OO collisions.
Could you review the code? Also, I want to ask 2 questions:
1. we discussed some time ago that the JE framework does not contain functionality to estimate rho background for particle level MC. Do we plan to add such functionality?
2. when we want to get a weight for MC detector level simulations, we use ``auto weight = collision.mcCollision().weight()``. There is a function that checks whether a collision has an associated MC collision: ``collision.has_mcCollision()``. So, not all detector-level collisions have associated particle-level collisions? Are we protected from the output not being garbage due to the absence of the associated MC collision when calling …
=> [PWGJE] Task for hadron-jet correlations in O-O collisions

PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/hadronPhotonCorrelation.cxx
Analysis task for angular correlations between trigger hadrons (as proxy for jets) and photons 
@fjonasALICE @nzardosh
=> [PWGJE] Add hadron-photon correlation analysis task

PWGDQ/Core/CutsLibrary.cxx
Add three electron cuts for the e-mu trigger test:
The new cuts contain loose PID cuts no_Corr and kIsITSibAny cut
=> [PWGDQ] CutLibrary: Add electron cuts for e-mu trigger test

PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- fix occupancy selection when the lower bound selection is 0 (before, for a bin of "0 < occ. < 100", the selection consisted rather in "occ. < 100")
- Enable rejection of ITS afterburner tracks
- Add TOF PID Nsigma distributions
- Add TPC crossed rows and ITS clusters Vs centrality Vs pt QA plots
=> [PWGLF] Fix occupancy selection, enable ITS AB track rejection, add QA plots

PWGLF/DataModel/ReducedF1ProtonTables.h, PWGLF/TableProducer/Resonances/f1protonreducedtable.cxx, PWGLF/Tasks/Resonances/f1protoncorrelation.cxx
Add TPC PID info in f1 table + add momentum dependent PID cut to select f1 daughters + improved rotational background estimation
=> [PWGLF] TPC PID info in f1 table, improved PID and background for f1

PWGCF/TableProducer/dptdptfilter.cxx, PWGCF/TableProducer/dptdptfilter.h, PWGCF/Tasks/match-reco-gen.cxx, PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx
Also
- TOF signal in global momentum
- TPC signal from MC tune on data when required
=> [PWGCF] DptDpt -- Tracking the TPC sector borders

DPG/Tasks/AOTTrack/qaEfficiency.cxx
Bug: Fix histogram filling for Mother pT and Decay Length
=> [DPG] Bug: Fix histogram filling for Mother pT and Decay Length

PWGLF/TableProducer/Resonances/resonanceInitializer.cxx, PWGLF/TableProducer/Resonances/resonanceModuleInitializer.cxx
1. **Resolved Duplicate V0 Filling**:
- Removed duplicate calls to `fillV0s` in `resonanceInitializer.cxx` for efficient processing.
2. **Added New Processes**:
- Introduced `processSpherocity` and `processEventPlane` methods in `resonanceModuleInitializer.cxx`:
- Spherocity processing includes configurable track-based spherocity calculations.
- Event plane processing incorporates event plane resolutions with flexible configurations.
3. **Enhanced Filters and Configurations**:
- Simplified the PID filter definitions by removing commented and redundant code.
- Introduced spherocity-specific configuration options:
- `cfgTrackSphMin` and `cfgTrackSphDef`.
=> [PWGLF] Refinements and Enhancements in Resonance Initialization and Module Setup

PWGEM/PhotonMeson/Utils/EventHistograms.h
- Incrementing by one sometimes did not work because of float precision with high numbers of events
=> [PWGEM/PhotonMeson] Change event counter precision (float -> double)

PWGHF/Core/HfHelper.h
This change includes the impact parameters of the D0 and Pion in the selector, which were not cut on before
=> [PWGHF] Adding selections on impact parameter of D0 and Pi to B+ selection

PWGDQ/Core/VarManager.h, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqEfficiency.cxx, PWGDQ/Tasks/dqEfficiency_withAssoc.cxx, PWGDQ/Tasks/tableReader.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
And fixing filling of event flags in FillEvent method
=> [PWGDQ] Adding event selection flags to dimuonAll table

PWGDQ/Core/CutsLibrary.cxx
=> [PWGDQ] Fix the error in emu cuts

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/prefilterDielectron.cxx, PWGEM/Dilepton/Utils/EventHistograms.h, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: remove dz-rdphi cut
=> [PWGEM/Dilepton] remove dz-rdphi cut

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt, PWGLF/TableProducer/Strangeness/Converters/stradautracksextraconverter2.cxx, PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx, PWGLF/Tasks/Strangeness/lambdapolsp.cxx
As discussed with @prottayCMT, this PR adds a process function to the lambda polarization task that uses the centrally produced strangeness derived data for the analysis. The algorithm should match precisely what is done in original AO2Ds. A few relevant comments: 
* the 'check published' option is not available, since it requires all original tracks and these are not saved. 
* the 'use global momentum' is not available when using derived data, since daughter track momenta are only stored at the decay point. 
* in order to be able to fully port the code to derived data, a change had to be done to the derived data format itself:
* the `DauTracksExtra` did not previously contain findable TPC clusters, which had to be added. Furthermore, I have revamped the data model such that it now more …
=> [PWGLF] addition of derived data path for lambda polarization

PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
1.  Lack of bc declaration at processData
=> [PWGHF] Fix bc at declaration

PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
This adds a path in which no PID is required to build strangeness derived data: in this case, NSigmas will be defaulted to zero, meaning all checks will pass (and that part of the data will also be heavily compressed out). It is meant to enable a quick look at uncalibrated data (e.g. 2024 Pb-Pb apass1 with no TPC calibs). In addition, this PR also adds some more friendly printouts that may help in debugging uses of the strangeness derived builder - noting that we could probably simplify / streamline this further. Tagging @romainschotter @gianni for completeness.
=> [PWGLF] Strangeness derived builder changes

PWGUD/DataModel/UDTables.h, PWGUD/TableProducer/UPCCandidateProducer.cxx
The global forward tracks (MFT-MCH-MID type) were not selected properly for each BC, now this is done using the global BC info. 
The tangent lambda information is stored in a new table to be able to perform the global muon refit as is done in DQ.
=> [PWGUD] Fix global forward tracks selection and store tan lambda information

PWGHF/D2H/Tasks/taskDstarToD0Pi.cxx
Hi @fgrosa @fcatalan92, 
In this PR I tried to add MC processes with ml application to calculate prompt and non-prompt efficiencies. Also a check if right combination of process functions are true.
=> [PWGHF/D2H] Adding ML application in MC processes for analysis on Multiplicity Dependent D* Production Cross Section

PWGCF/TwoParticleCorrelations/Tasks/CMakeLists.txt, PWGCF/TwoParticleCorrelations/Tasks/neutronProtonCorrZdc.cxx
Updated the structure of the analysis task to a more realistic one. Changed the output structure, using folders for the A- and C-side of the ZDC. In addition also implemented centrality dependence for more histograms.
See for a full history of recent changes this closed PR: https://github.com/AliceO2Group/O2Physics/pull/9045
=> [PWGCF] Update analysis structure and add centrality dependence

PWGHF/TableProducer/candidateCreator2Prong.cxx, PWGHF/TableProducer/candidateCreator3Prong.cxx, PWGHF/TableProducer/candidateCreatorCascade.cxx, PWGHF/TableProducer/candidateCreatorDstar.cxx, PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx, PWGHF/Tasks/taskMcValidation.cxx, PWGHF/Utils/utilsEvSelHf.h
Add histogram with the number of generated collisions vs centrality.
This histogram is needed to compute the efficiency collision reconstruction as a function of the multiplicity
=> [PWGHF] Add mc collision counter vs centrality

PWGHF/DataModel/DerivedTables.h
Needed to resolve the discrepancy in the identifiers for table names and descriptions (e.g Bplus and BP) which break the merger
=> [PWGHF] Fixing indexing on derived collision tables

PWGCF/TwoParticleCorrelations/Tasks/lambdaR2Correlation.cxx
1. Added the functionality to compute correlation function in rapidity or pseudo-rapidity
2. Add the option to correct for efficiency as pT vs Rap or pT vs Eta
=> [PWGCF] Lambda R2 Correlation Update

PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
In this commit I just added the process to perform the ME using self-contained derived data in the taskCorrelationDsHadrons.
Cheers,
Samuele
=> [PWGHF] Ds-h correlation, adding ME derived precess in task

PWGCF/TwoParticleCorrelations/Tasks/lambdaR2Correlation.cxx, PWGHF/Core/CentralityEstimation.h, PWGHF/D2H/Tasks/taskDplus.cxx, PWGHF/D2H/Tasks/taskDs.cxx, PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx, PWGHF/TableProducer/candidateCreator2Prong.cxx, PWGHF/TableProducer/candidateCreator3Prong.cxx, PWGHF/Tasks/taskMcValidation.cxx, PWGHF/Utils/utilsAnalysis.h, PWGHF/Utils/utilsEvSelHf.h
In this PR, occupancy and centrality axes are added to existing sparses. Plus, the information on the B hadron mother pdg and pt is stored for nonprompt candidates. Finally, sparse histograms are added for generated MC candidates.
=> [PWGHF] Extend information of sparses for efficiency evaluation. Refactor analysis utilities.

Tools/ML/MlResponse.h
`MlResponse.h`
- I have updated ln 161 to resolve the template ambiguity issue first.
I plan to make a draft `MlResponse` to be capable of utilizing the most general types of inputs and outputs (multiple, variable-sized, multi-dimensional tensors). However, since I would like to use `MlResponse` as soon as possible, I would appreciate it if you could merge the current changes first, if possible.
Thank you.
=> General types of inputs and outputs for MlResponse and OnnxModel

PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Added the EMCal cluster definitions to the emcal cuts. Without this it defaults to the kV3Default setting which is not in the newest dervied data for the 2023 PbPb.
=> [PWGEM,PWGEM-36] Add clusterdefinition to the emcal cuts

PWGCF/DataModel/FemtoDerived.h, PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h, PWGCF/FemtoDream/Core/femtoDreamTrackSelection.h, PWGCF/FemtoDream/Core/femtoDreamUtils.h, PWGCF/FemtoDream/Core/femtoDreamV0Selection.h, PWGCF/FemtoDream/TableProducer/femtoDreamProducerReducedTask.cxx, PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx, PWGCF/FemtoDream/Tasks/femtoDreamDebugTrack.cxx, PWGCF/FemtoDream/Tasks/femtoDreamDebugV0.cxx, PWGCF/FemtoDream/Utils/femtoDreamCutCulator.h, PWGHF/HFC/TableProducer/femtoDreamProducer.cxx
Add ITS PID in femtodream for analysis with light nuclei.
Adding the ITS PID information it was necessary to add new columns to the debug table with the ITS information. Similarly, since new information is added to the bitmask for PID selection, changes to the cutculator had to be made.
Using ITS PID is optional in the producer and has to be activated explicitly. Similarly, the calculator asks the user if ITS PID is to be considered for the bitmask.
=> [PWGCF,PWGHF] Add ITS PID to femtodream

PWGLF/DataModel/LFSigmaTables.h, PWGLF/TableProducer/Strangeness/sigma0builder.cxx, PWGLF/Tasks/Strangeness/sigmaanalysis.cxx
This PR introduces several key improvements and fixes:
- Adapts the sigma0builder to correctly handle asymmetrically populated V0MCCores tables;
- Adds a new module with configurable options for event selection;
- Implements TPC crossed rows selection for Lambda candidates in the sigmaanalysis task to improve track quality;
- Adds pT resolution histograms for QA;
- Introduces specific photon selection criteria:
- Line-cut in the RZ plane;
- Psi-pair cut;
- TPC nSigma cut for pion rejection;
- Updates the usage of BDT scores for analysis.
- Fixes the table population logic in sigma0builder to ensure correct data filling.
=> [PWGLF] Improvements in sigma0 tasks

PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add generated collisions with a centrality > 100% (i.e. not associated to a recoed collision, stored in the overflow bin) in all histograms
=> [PWGLF] Add non-recoed collisions in histograms

PWGDQ/Core/HistogramsLibrary.cxx
Added histograms of the projection of pseudoproper dacay length in pT bins to allow for apple to apple comparison across the PAG.
=> [PWGDQ] vertexing histograms added (HistogramLibrary.cxx)

PWGLF/TableProducer/Strangeness/CMakeLists.txt, PWGLF/TableProducer/Strangeness/cascademlselection.cxx
- Add task for a posteriori cascade ML score calculation, in the same spirit as the lambdakzeromlselection.cxx task (@gianniliveraro )
- Allows also to fill the ML scores tables with dummy values (-1). In such case, this task acts also as a converter task
=> [PWGLF] Add task for a posteriori cascade ML score calculation

PWGCF/DataModel/FemtoDerived.h, PWGCF/FemtoDream/Core/femtoDreamCascadeSelection.h, PWGCF/FemtoDream/Core/femtoDreamDetaDphiStar.h, PWGCF/FemtoDream/Core/femtoDreamPairCleaner.h, PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h, PWGCF/FemtoDream/Core/femtoDreamTrackSelection.h, PWGCF/FemtoDream/Core/femtoDreamUtils.h, PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx, PWGCF/FemtoDream/TableProducer/femtoDreamProducerTaskForSpecificAnalysis.cxx, PWGCF/FemtoDream/Tasks/CMakeLists.txt, PWGCF/FemtoDream/Tasks/femtoDreamDebugCascade.cxx, PWGCF/FemtoDream/Tasks/femtoDreamPairTaskTrackCascade.cxx, PWGCF/FemtoDream/Utils/femtoDreamCutCulator.cxx, PWGCF/FemtoDream/Utils/femtoDreamCutCulator.h
- The producer task can select now also Cascades (for now only Xis supported; Omegas will follow soon)
- Cutcullator and FemtoDreamParticleHisto updated accordingly
- Cascade selection happens in dedicated task
- Debug Cascade and pair-track-Cascade task included
- Updated the "femtoDreamProducerTaskForSpecificAnalysis.cxx" to support Cascades
=> [PWGCF] FemtoDream: Implementing Cascades

DPG/Tasks/AOTTrack/qaEfficiency.cxx
=> [DPG] Fix histo axis defined name

PWGEM/PhotonMeson/TableProducer/associateMCinfoPhoton.cxx, PWGEM/PhotonMeson/Utils/MCUtilities.h, PWGJE/Tasks/mcGeneratorStudies.cxx
- Added std:: in front of all abs() calls in associateMCinfoPhoton
- Corrected PDG code requirement in MCGeneratorStudies (should not have caused any issues)
- Added option to only count generated pi0 and eta that decay into gammagamma
- Cosmetic changes in associateMCinfo
=> [PWGEM,PWGJE] Bug fix for generated neutral mesons

Common/Core/RecoDecay.h, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreator2Prong.cxx, PWGHF/TableProducer/candidateCreator3Prong.cxx, PWGHF/TableProducer/candidateCreatorDstar.cxx
This PR implements the possibility to match daughter tracks interacting with material (see https://github.com/AliceO2Group/O2Physics/pull/9391) for the 2-prong, 3-prong and D* creators. To be extended to other channels.
=> [PWGHF] Add possibility to match decay daughters interacting with material in HF

PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Creates look up table once inside init ccdb including bad channel map. This look up table can be used to check if photons inside rotation method are within EMCal acceptance, at the edge, on bad channels or just on good channels. This also makes it possible to remove the edges from the same event distribution.
- Added eta phi maps before and after the removal for background and same event
- Added new configurable to set what kind of photons you want to cut on in the rotation method
=> [PWGEM,PWGEM-36] Meson flow: Speed up rotation background

PWGLF/DataModel/LFHStrangeCorrelationTables.h, PWGLF/TableProducer/Strangeness/hStrangeCorrelationFilter.cxx, PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
using template function for assoc hadrons
=> [PWGLF] Changes in h-Strangeness correlation code

PWGUD/Tasks/CMakeLists.txt, PWGUD/Tasks/upcQuarkoniaCentralBarrel.cxx
Add new analysis task to study quarkonia (although, mainly charmonia) decaying ppbar in UPC
=> [PWGUD] Add Quarkonia --> ppbar analysis task in UPC

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: use filter for v0 selection
PWGEM/Dilepton: add MC ee signals from charm hadrons
PWGEM/Dilepton: update event qc task for v0
=> [PWGEM/Dilepton] use filter for v0 selection

PWGCF/FemtoUniverse/Core/FemtoUniverseEfficiencyCalculator.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx
- Fix an issue with `EfficiencyCalculator` where the `OutputObj`, nested inside `EfficiencyConfigurableGroup`, was not registered by a task. The uploading to CCDB worked, however the efficiency histograms were not saved to analysis result root file.
- Replace `OutputObj` with `HistogramRegistry` for efficiency histograms.
- Apply corrections also in `processMixedEvent` function.
- Separate configurable for CCDB objects' timestamps.
- Add configurable for lifetime of the uploaded CCDB objects.
=> [PWGCF/FemtoUniverse] Fix `EfficiencyCalculator` not saving efficiency to the analysis output

PWGHF/TableProducer/treeCreatorToXiPi.cxx
The FT0M, FT0A, FT0C and numContrib has been added to Xic0 event lever
=> [PWGHF] Add centrality information to Xic0

PWGJE/Tasks/jetHadronRecoil.cxx
- fix delta R and phi ranges to better span measured values
- optimise response binning to reduce size (wider bins in pT + phi)
=> [PWGJE] optimise binning in phi and pT

PWGJE/Tasks/jetFinderFullQA.cxx, PWGJE/Tasks/jetFinderHFQA.cxx, PWGJE/Tasks/jetFinderQA.cxx
rejection on minimum bias events in minimum bias gap productions, for process functions which subscribe and iterate over collisions/tracks rather than jets.
The jet rejection is now done in the jet finder (see https://github.com/AliceO2Group/O2Physics/commit/d7b61f70070f8b765c7caa660fcb8cc86ebdac81 ) - we also want to be able to get track and collision information only for the signal jet-jet events.
=> [PWGJE] add MB gap event rejection for tracks and collisions

PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Fixed mixed event method: The collision filter had problems with the query for sel8. Removed it since event selection will take care of this anyway.
- FT0C occupancy cut was not properly used, instead the TPC track occupany cut values were used. This is now fixed. all occuoancy cuts are now FT0C occupancy.
=> [PWGEM,PWGEM-36] Pi0 Flow - Fix Mixed event and occpuancy cut

PWGLF/Tasks/Resonances/chk892flow.cxx
- Code Cleanup:
- Removed unnecessary includes (TMath.h, TDatabasePDG.h, TPDGCode.h).
- Replaced TMath::Abs with standard std::abs for better portability.
- Updated variable names to follow a consistent naming convention (e.g., DetId to lDetId).
- Performance Improvements:
- Introduced the use of std::cos, std::atan2 instead of ROOT-specific functions for efficiency.
- Optimized event selection by refactoring redundant configurations.
- Replaced repeated calculations with pre-computed values where applicable.
- New Features:
- Added configuration options for rotated background analysis, allowing flexibility in pion rotation settings.
- Implemented histogram for tracking rotated background angles.
- Code Style and Readability:
- Renamed and refactored several methods to improve clarity and …
=> [PWGLF] Refactor and Optimize chk892flow.cxx for Improved Readability and Performance

PWGDQ/TableProducer/tableMakerMuonMchTrkEfficiency.cxx
This PR aims to fix a minor bug in the definition of "myReducedMuons" and  "myReducedMuonsMC" that was preventing the code from running on derived datasets.
=> [PWGDQ] fix bug in tableMakerMuonTrkEfficiency

PWGDQ/Tasks/tableReader.cxx
Quick fix for wrong process calling in Event-Mixing for flow calculations
=> [PWGDQ] Fix wrong process calling

PWGJE/Tasks/jetFinderQA.cxx
fix to allow event selection on particle-level jets if option enabled
=> [PWGJE] fix event matching for particle level weighted process function

PWGLF/TableProducer/Strangeness/CMakeLists.txt, PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
Meant to do further reduction of memory footprint of the new strangeness builder via removal of the unnecessary `O2::DetectorsBase`. 
For the record, current numbers indicate that the replacement of the `lambdakzerobuilder` and `cascadebuilder` as well as of the labeler services ('mc' builders) leads to a reduction of up to 1GB of memory use already, even still pulling in the entire `DetectorsBase` (which is unnecessary). Speed is also significantly better and is currently being tested. V0s have been proven to be fully equivalent to the ones provided by the canonical `lambdakzerobuilder`; cascades to be tested.
=> [PWGLF] Library cleanup for strangeness builder

PWGCF/EbyEFluctuations/Tasks/netprotonCumulantsMc.cxx, PWGLF/Tasks/Resonances/chk892flow.cxx
Flexibility between FT0C and impact parameter for centrality estimation
=> [PWGLF] Updat PWGLF/Tasks/Nuspex/spectraTOF.cxx

PWGHF/D2H/Tasks/taskD0.cxx
Hi @mfaggin , @fcatalan92 , and @zhangbiao-phy , this pr is about updating the `if` condition of collision type in MC process. 
Since I split the process into one with and without centrality, the `if` condition of collision type in MC process should be modified at the same time. (#9294 )
Last time, I overlooked this part, so it led to the centrality and occupancy not being filled in the `Gen` THnSparse. This pr is addressing this issue.
Please let me know if you have further suggestions or comments! Thanks a lot!
=> [PWGHF] update the collision type in MC process

PWGLF/Tasks/Strangeness/lambdalambda.cxx
reject the same event when mixing events
=> [PWGLF] reject the same event

PWGLF/DataModel/LFResonanceTables.h, PWGLF/Tasks/Resonances/lambda1520_PbPb.cxx
- Updated the type alias from `aod::ResoCollisions` to `aod::ResoCollisionDFs` to match the latest framework changes.
=> [PWGLF] Update type alias in lambda1520_PbPb.cxx

PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Fix missing `mesonConfig.enableTanThetadPhi` for rotation background and mixed event method
- Enabling mixed event to now fill the correct background histo instead of the same event histo.
=> [PWGEM,PWGEM-36] Pi0Flow - Fix TanTheta cut being applied most of the time

PWGCF/Femto3D/DataModel/singletrackselector.h, PWGCF/Femto3D/TableProducer/CMakeLists.txt, PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx, PWGCF/Femto3D/TableProducer/singleTrackSelectorExtra.cxx, PWGCF/Femto3D/TableProducer/singleTrackSelectorPIDMaker.cxx, PWGCF/Femto3D/Tasks/femto3dPairTask.cxx, PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx, PWGCF/Femto3D/Tasks/femto3dQA.cxx, PWGLF/Tasks/Nuspex/hadronnucleicorrelation.cxx, PWGLF/Tasks/Strangeness/k0_mixed_events.cxx
=> [PWGCF,PWGLF] Data model update

PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/Chk892Flow.cxx, PWGLF/Tasks/Resonances/chk892Flow.cxx
1. File and Struct Renaming:
- Renamed `chk892flow.cxx` to `Chk892Flow.cxx` to align with standard naming conventions.
- Updated struct name from `chk892flow` to `Chk892Flow` for consistency.
2. Code Cleanup and Enhancements:
- Replaced hardcoded PDG codes with constants from `o2::constants::physics::Pdg` for better maintainability.
- Standardized naming conventions across the codebase (e.g., `binType` → `BinType`).
- Added configurable options for minimum and maximum transverse radius of `K0s`.
- Enabled `QA/K0sCutCheck` histogram only when `cfgReturnFlag` is set.
3. Performance Optimization:
- Optimized the `K0s` selection function by grouping common cuts into a lambda function to reduce redundancy.
- Improved PID selection logic for better efficiency and readability.
- Removed unused …
=> [PWGLF] Refactor and Rename K892pm flow with Code Improvements

PWGLF/TableProducer/Strangeness/sigma0builder.cxx, PWGLF/Tasks/QC/strderivedGenQA.cxx
As requested by @altsybee, this PR removes the usage of `kNoCollInTimeRangeVzDependent` event selection bit from `sigma0builder` and `strderivedGenQA` tasks.
=> [PWGLF] Removing event selection bit

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Changes:
- saving D0/D0bar candidates with double mass hypothesis -> optional, configurable added for it
- removing the correlation with D0/D0bar cand. with double mass hypothesis as well as filling the corresponding histograms
- new process function in the producer processTrackD0DataML and new dedicated function fillD0D0barUsingML, implemented to run D0 analysis with ML selection (It will be developed)
- new process function in the task for optimization of ML selection criteria
=> [PWGCF] FemtoUniverse - producer and D0 task update (ML)

PWGHF/Core/HfMlResponseXicToXiPiPi.h, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/treeCreatorXicToXiPiPi.cxx
In this PR,
1) Several variables have been added into MlResponseXicToXiPiPi
2) Typo in the name of variable has been fixed in CandidateReconstructionTables and treeCreatorXicToXiPiPi
=> [PWGHF] Add variables in MlResponse and fix typo in XicToXiPiPI workflows

PWGJE/JetFinders/jetFinder.cxx
added capabilities to require fulfilled EMCal event selection when running charged jet finder. This significantly improves CPU usage for analyses that require EMCal information, either when running directly on AO2Ds or for production of dedicated derived JE datasets.
By default, this option is set to false and default behaviour is not modified!
=> [PWGJE] adding EMCal event selection for charged jets

PWGLF/Tasks/Resonances/chk892Flow.cxx
Add `std::abs` to the daughter DCA to PV values.
=> [PWGLF] Hot fix absolute value check in K892PM flow task

PWGHF/D2H/Macros/compute_fraction_cutvar.py, PWGHF/D2H/Macros/cut_variation.py
@atavirag this PR adds two methods to the cut-variation class, to compute fractions provided efficiencies and corrected yields from cut variation as inputs (so externally). This allows the calculation of the raw fraction for any set of selections, without requiring to re-run the minimisation
It also adds a 4-panel plot in the script (useful for presentations)
=> [PWGHF] Add methods to compute fraction, provided both efficiencies and cut-variation results externally

PWGLF/TableProducer/Resonances/resonanceInitializer.cxx, PWGLF/TableProducer/Resonances/resonanceModuleInitializer.cxx, PWGLF/Utils/collisionCuts.h
- Introduced new configurable event selection options:
- `cfgEvtCollInTimeRangeNarrow` (NoCollInTimeRangeNarrow selection)
- `cfgEvtRun2AliEventCuts` (Run 2 AliEventCuts.isAccepted)
- `cfgEvtRun2INELgtZERO` (Run 2 INEL>0 selection)
- Updated `collisionCuts.h` to handle the new selections.
- Improved debug logging for event selection.
- Adjusted `processDummy` method to use `aod::Collisions`.
=> [PWGLF] Add event selection options for Run2 and Run3 further cuts in collisionCuts

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt, PWGLF/TableProducer/Strangeness/Converters/stramccollmultconverter.cxx, PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- Add total MC multiplicity in StraMCCollMults table
- Add converter
@nepeivodaRS for your information
=> [PWGLF] Add total MC multiplicity in StraMCCollMults table

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/bcCounter.cxx
PWGEM/Dilepton: add a task for BC counter
=> [PWGEM/Dilepton] add a task for BC counter

PWGJE/Tasks/jetSpectraEseTask.cxx
Change particle level. Added pure det lvl process function. Added centrality to geo matched
=> [PWGJE] Added det level process function and modified existing MC

PWGJE/Tasks/jetHadronRecoil.cxx
Also:
- Removing unused histograms to help with memory consumption issues while running
- Fixing a bug where the Signal and Reference pt histograms are filled with trigger tracks
=> [PWGJE] Adding centrality selection

PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Allow to apply (or not) event selections in the denominator of the efficiency (and the numerator of signal loss)
- Remove deprecated event selection (kNoCollInTimeRangeVzDep)
- Increase some histograms granularity
=> [PWGLF] Add option to apply evt sel in efficiency denominator + remove deprecated event selection

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx, PWGLF/Utils/strangenessBuilderHelper.h
* Makes strangeness builder fully equivalent to lambdakzero + cascade builder (tested to be true), producing precisely the same candidates (compared 1-to-1). 
* Typical memory footprint of the new service is up to 4x smaller in memory than the old combo of `lambdakzerobuilder` + `cascadebuilder` + labeler services, with full autodetect of all tables instead of manually disabling unnecessary generation e.g. of V0s when processing cascades. Will hopefully make life easier when using Hyperloop. 
* CPU performance is approximately 2x faster when building the full payload of V0s + Cascades + KF Cascades + Tracked Cascades due to simplified single-loop algorithm and dramatic reduction in DPL device counts and function calls in the new building scheme. Expect larger gains in case of cascade-only …
=> [PWGLF] Strangeness builder commissioning: improvements and fixes

Common/DataModel/CMakeLists.txt, Common/DataModel/FwdTrackReAlignTables.h, Common/TableProducer/CMakeLists.txt, Common/TableProducer/muonRealignment.cxx
1. Add new tables definition for re-aligned forward tracks keeping the same getters as the original forward tracks
2. Add a new table producer which will do muon re-alignment at analysis-level, providing re-aligned tracks information that can be accessed by any PWG analysers.
=> [Common] Analysis-level muon re-alignment task and new tables definition

DPG/Tasks/AOTTrack/PID/ITS/qaPIDITS.cxx, PWGLF/Tasks/Resonances/chk892Flow.cxx
2(phi-Psi_2) axis is added to the InvmassK0s and InvmassKstar (THnSparse).
=> [PWGLF] Added 2(phi-psi) axis for inv mass

PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
Initializes the impact parameter object with default values of -999.f to mark the cases in which the propagation fails
=> [PWGLF] Initialize impact parameter with default values

PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h
Bug fix, so that we now also require events to be weighted before filling generated particles (when the JJ option is on)
=> [PWGEM/PhotonMeson] Add missing JJ weight requirement for gen particles

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Tasks/createResolutionMap.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: fix std::fabs
PWGEM/Dilepton: fix track propagation
PWGEM/Dilepton: add possibility to require true track-to-collisio association
=> [PWGEM/Dilepton] add possibility to require true track-to-collisio association

PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
The changes in this commit rename the `mDCA` variable to `motherDCA` for better clarity and readability of the code. The `motherDCA` struct is used to store the DCA (distance of closest approach) information of the mother particle (cascade) with respect to the primary vertex.
=> [PWGLF] Rename `mDCA` to `motherDCA` for clarity

PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Add ctpRateFetcher service
- Add event selections on local IR
=> [PWGLF] Add ctpRateFetcher service

PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Utils/PCMUtilities.h
PWGEM/PhotonMeson: std::abs and std::fabs for PCM
=> [PWGEM/PhotonMeson] std::abs and std::fabs for PCM

PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: update 2vp task
=> [PWGEM/Dilepton] update 2vp task

PWGCF/FemtoUniverse/Core/FemtoUniverseEfficiencyCalculator.h, PWGCF/FemtoUniverse/Scripts/femto_universe_efficiency_calculator.py
- expand help messages for efficiency calculator script
- update script flags:
- now Alien path to analysis results is provided through `--alien-path` flag instead of positional argument
- replace general flag `--task` with more specific `--mc-reco` & `--mc-truth` to have more control over which histograms to use in efficiency calculation 
- if `--ccdb-labels` flag is provided, the number of its values must match the number of specified histograms 
- change `ConfigurableAxis` to just `std::vector<std::string>` for CCDB timestamps configurable
```
$ ./PWGCF/FemtoUniverse/Scripts/femto_universe_efficiency_calculator.py --help
usage: femto_universe_efficiency_calculator.py [-h] [--alien-path ALIEN_PATH] --mc-reco MC_RECO [MC_RECO ...] --mc-truth
MC_TRUTH [MC_TRUTH ...] --ccdb-path CCDB_PATH …
```
=> [PWGCF/FemtoUniverse] Add more flags to efficiency calculator script + fix configurable for timestamps 

PWGEM/Dilepton/Utils/MCUtilities.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/Utils/NMHistograms.h, PWGJE/Tasks/emcalGammaGammaBcWise.cxx
- PWGEM:
- Add getMotherPDG function to retrieve mother of photon for new true histogram
- Implement opening angle cut for EMCal in gammagamma tasks
- New histogram for "true" pi0/eta where both found particles originate from the same gamma
- PWGJE (EMCal standalone gammagamma task):
- Add acceptance cut for rotation background
- Add cluster definition filter
- Add opening angle cut
=> [PWGJE/EMCal,PWGEM/PhotonMeson] Add true pi0 from same gamma histogram and opening angle cut

PWGLF/Tasks/Resonances/chk892Flow.cxx
- Introduced a new configurable option `cfgUseScalProduct` to enable the scalar product method for flow calculations.
- Updated the event-plane (EP) method by ensuring proper handling of `v2` values.
- Implemented scalar product calculations using real (`qvecRe`) and imaginary (`qvecIm`) components of the flow vector.
- Updated histogram filling logic to support both methods consistently.
- Adjusted the default binning range of `v2` to `[-1,1]` for EP-based analysis.
=> [PWGLF] chk892Flow: Add scalar product method

PWGHF/TableProducer/treeCreatorD0ToKPi.cxx
This PR aims to fix the way HfCandD0Mls is filled. In the previous version, candidates saved as D⁰ and D⁰bar simultaneously were counted four times, two as D⁰ and two as D⁰bars, causing a mismatch between the number of candidates in HfCandD0Lites and HfCandD0Mls.
=> [PWGHF] Fix ML variable addition to tree creator

PWGLF/TableProducer/Strangeness/lambdakzerobuilder.cxx, PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
- Remove TrackIU in TracksWithExtra joined table (allows ultimately to produce derived data out of Run2 converted data)
- Fix typo in the lambdakzerobuilder
@ddobrigk for your information.
=> [PWGLF] Remove TrackIU in TracksWithExtra joined table

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/TableProducer/tableMaker_withAssoc.cxx, PWGDQ/Tasks/CMakeLists.txt, PWGDQ/Tasks/filterPbPb.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
* New process function in filterPbPb which uses the SGSelector class
* New DQ table which contains event filter bitmap and FIT, ZDC info from the nearest BC in which the FIT signal is above the selection threshold
* New process function in TableMaker_withAssoc which writes to the DQ tables the ZDC and FIT info found for the closest BC which surpassed the threshold in SG event selection
* Put D meson 3d histograms in separate subgroup
* Fix bug in check of ambiguous legs.
=> [PWGDQ] Add process function which uses SGSelector to filterPbPb. Smaller changes to UPC D meson analysis.

PWGHF/D2H/Tasks/taskDplus.cxx, PWGHF/D2H/Tasks/taskDs.cxx
This PR changes the order of the THnSparse in the output of the Ds and D+ tasks.  
Informing @Marcellocosti @stefanopolitano @scattaru @fgrosa.
Let me know if this is fine for you!
=> [PWGHF] Restore backward compatibility of Ds and D+ tasks

PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaPi.cxx, PWGHF/TableProducer/treeCreatorOmegacToOmegaPi.cxx, PWGLF/TableProducer/Strangeness/v0qaanalysis.cxx
Save only signal in MC(originRec != 0) and fix candidates pT cut in selector
=> [PWGHF] Save only mc signal in treecreator.

Common/DataModel/FwdTrackReAlignTables.h, Common/TableProducer/muonRealignment.cxx, PWGDQ/Core/CMakeLists.txt, PWGDQ/Core/VarManager.h, PWGDQ/TableProducer/tableMaker.cxx
1. Small adaptations in `FwdTrackReAlign` table definitions
2. Add new process for associated muons using realigned tracks (kinematics and propagation are re-evaluated using realigned tracks)
3. Few adaptations in `VarManager.h` to allow the case of using realigned forward tracks
=> [Common,PWGDQ] A First version of process using realigned muon tracks in table-maker

PWGHF/D2H/Tasks/taskDs.cxx
Hi @Marcellocosti @stefanopolitano @scattaru @fgrosa, sorry for opening a second PR. I realised just now that the sparse for FD candidates did not have the axis for the number of pv contributors, and I have also added the information on B hadrons for the D+, for consistency.
=> [PWGHF] Add npv contributors axis for non prompt outputs

PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/k892analysis_PbPb.cxx, PWGLF/Tasks/Resonances/k892analysispbpb.cxx
- fixing o2linter errors
- adding TOF only selection
- adding plots for MC bkg study
- adding process function for Event and Signal loss
=> [PWGLF] k892analysispbpb - MC studies, signal and event loss

PWGCF/FemtoDream/Core/femtoDreamParticleHisto.h, PWGCF/FemtoDream/TableProducer/femtoDreamProducerTask.cxx, PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx, PWGCF/FemtoDream/Tasks/femtoDreamDebugV0.cxx, PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrack.cxx, PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackV0.cxx
New implementations:
1.  Tracks selections for refit ITS and TPC, also for chi2 TPC and ITS per cluster
2. Transverse radius plot for V0s as a function of pT
3. Armenteros-Podolanski Plot
4. pT dependent DCA cut
=> [PWGCF] Addition of new QA histograms and also track selections

PWGHF/HFC/TableProducer/correlatorLcHadrons.cxx
Added configurable eventFractionToAnalyze that allow to fill the two tables used for offline event mixing in Lc-hadron correlator only in the specified fraction of event, skipping the others
=> [PWGHF] Add option to fill ME tables of Lc-h in a fraction of events

PWGLF/TableProducer/Strangeness/CMakeLists.txt, PWGLF/TableProducer/Strangeness/strangenessbuilderfindable.cxx, PWGLF/Utils/strangenessBuilderHelper.h
Adds a test version of the strangeness builder in which two findable modes exist: 1) generate complementary findables and add to existing V0s and 2) generate only findables, disregard existing V0s. The addition is temporarily provided in a new task so that large-scale memory and CPU tests can be performed. The new task will be removed and the changes merged with the regular `strangenessbuilder` soon.
=> [PWGLF] Add findable mode for new strangeness builder

PWGHF/TableProducer/treeCreatorTccToD0D0Pi.cxx
Changing the tag value of reflection case for D0 bar in Tcc tree creator for avoiding double counting of reflection
=> [PWGHF] change the tag value of reflection case for D0 bar in Tcc tree creator

PWGHF/TableProducer/derivedDataCreatorDplusToPiKPi.cxx
- Prefilter candidates which passed cuts at least until the step before ML.
- Reject candidates which did not pass ML immediately inside the candidate loop when ML selection is required.
FYI: @nzardosh @DelloStritto
=> [PWGHF] Fix and improve D+ selection in derived-data creator

PWGJE/Tasks/jetSpectraCharged.cxx
1. Add centrality selection and eventselection for mcCollisions which can be matched to the reconstructed events
2. Add jet histograms without background subtraction on Data and MCD level
3. Modify names of some histograms
=> [PWGJE] Add centrality selection for MCP jets

PWGJE/Tasks/jetChargedV2.cxx
Update event selection and leadingConstituentPt, fix Nbin error in fit
=> [PWGJE] Update event selection and leadingConstituentPt, fix Nbin error in fit

Common/CCDB/EventSelectionParams.cxx, Common/CCDB/EventSelectionParams.h, Common/DataModel/EventSelection.h, Common/TableProducer/eventSelection.cxx, DPG/Tasks/AOTEvent/rofOccupancyQa.cxx
Cleanup: removal of the kNoCollInTimeRangeVzDependent bit (not useful), also the bcInTF column from the evSel table
=> [Common,DPG] Cleanup: removal of kNoCollInTimeRangeVzDependent bit and bcInTF column

PWGCF/DataModel/FemtoDerived.h
Does not affect any results for FemtoDream users as the px and py values are not used in the analysis.
=> [PWGCF] Fix bug in Data Model for FemtoDream

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt, PWGLF/TableProducer/Strangeness/Converters/stradautracksextraconverter3.cxx, PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Several changes in the data model and analysis task:
**In the data model:**
- Add tpc chi2 per clusters + shared clusters in strangeness data model, allowing to select on those in the analysis task
**In the analysis task:**
- Add ITS/TPC chi2 per clusters histograms
- Allow selections on ITS/TPC chi2 per clusters
- Allow selection on TPC shared clusters
- Allow selection on TPC crossed rows over findable
- Enable the option to select V0s formed exclusively of afterburner tracks
- Fix occupancy selection allowing to keep the lower bound (especially to keep occupancy = 0)
- Replace handmade afterburner track tagging by the standard method
@ddobrigk for your information
=> [PWGLF] Add TPCchi2 and shared clusters in strangeness data model + fixes in V0 analysis task

PWGEM/Tasks/phosElId.cxx
mass spectra histograms have changed to 3D with centrality on z axis, histograms changed names to reflect centrality estimators have been added
binning for some axes and some limits became configurable, to not cause large memory usage in 3D histograms at their default some minor tweaks
=> [PWGEM] phosElId.cxx centrality update

PWGLF/TableProducer/Strangeness/sigma0builder.cxx, PWGLF/Tasks/Strangeness/lambdapolsp.cxx, PWGLF/Tasks/Strangeness/sigmaanalysis.cxx
This PR:
- Replaces the explicit lambda mass value with o2::constants::physics::MassLambda0;
- Adds a set of QA histograms specifically designed to monitor signal loss and background rejection after each selection;
- Introduces an optional phi selection for photons and adjusts the photon mass selection;
- Replaces the original TH1 mass histograms for photons and lambdas with a TH3 histogram - they will be used to evaluate the peak mean and sigma per pT bin;
- Adds a process function to retrieve the interaction rate (IR) per collision, intended for use with standard strangeness derived data;
- Updates the pT mass resolution histograms.
=> [PWGLF] Modifications in Sigma0 tasks

Common/TableProducer/multiplicityTable.cxx
Fill multNContribs variables for Run 2 converted data, allowing to apply INEL > 0, > 1, etc in consistent manner as what we do in Run 3
=> [Common] Fill multNContribs variables for Run 2 converted data

PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- Change bestCollisionIndex finding in MC for Run 2 analysis, as the variable `multPVTotalContributors` is not filled in the multiplicity task for Run 2 converted data
- Add TPC found over findable clusters histograms and cuts
- Change default value of process_switch for process function `processRealDataRun2` from true to false
=> [PWGLF] Fix bestCollisionIndex finding for Run2 analysis + other fixes in analysis task

PWGUD/TableProducer/UPCCandidateProducer.cxx
- in case of global fwd tracks: check the bits corresponding to ROF and TF borders for TVX & TCE lumi counter 
- add `collectForwardGlobalTracks` where such tracks (corresponding to BCs at ROF/TF borders) are omitted
=> [PWGUD] Remove ROF and TF borders for global fwd tracks

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx, PWGHF/TableProducer/treeCreatorXicToXiPiPi.cxx
@JaeYoonCHO
- bug fix: add 'fillHistogram' condition before filling counter histogram
- remove PV and SV uncertainties from output tables
- add DCA values associated to Xi (and its daughters) to KF tables
=> [PWGHF] XicToXiPiPi: Update output table structures

PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
@iarsene @MauriceCoke 
These 2 extra trees are added for:
-  the offline calculation of the Axe
- to perform iterative tuning of the Axe as done in Run 2 analyses
Some checks is necessary on hyperloop on large samples
=> [PWGDQ] Adding minitree to esimate offline Axe

PWGDQ/Core/HistogramsLibrary.cxx
…ilon.
I added this for the polarization measurements of Upsilon resonances.
It is exactly same to the earlier histograms named dimuon-polarization-he and dimoun-polarization-cs.
Just mass range is extended in the new histograms so as to use them for Upsilons.
=> [PWGDQ] Add CosTheta and Phi distribution histograms for Upsilon

PWGJE/DataModel/JetReducedData.h, PWGJE/TableProducer/derivedDataProducer.cxx, PWGJE/TableProducer/derivedDataWriter.cxx, PWGJE/Tasks/jetFinderQA.cxx
- add accepted, attempted, and cross section information to MC collision derived data
- add related histograms to jet QA task
=> [PWGJE] add cross section info for derived,reduced data

PWGUD/TableProducer/UPCCandidateProducer.cxx
Storing more event selection bits (kNoCollInTimeRangeStandard, kNoCollInRofStandard, kNoHighMultCollInPrevRof) as an output of the UPCCandidateProducer in case of using the global forward tracks.
=> [PWGUD] Add more selection bits to UPCCandidateProducer

PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
Adds 2D histograms of lambdas invariant mass vs pT in `PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h` and invariant mass vs centrality in `PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx`
=> [PWGCF] FemtoUniverse: add invariant mass vs pT and centrality histograms

PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx, PWGCF/TwoParticleCorrelations/Tasks/dptDptPerRunQc.cxx
We keep tracking the collision orbit but the dead chips maps can be produced offline at any moment Also incorporate the crossing in the tracking of delta eta and delta phi
=> [PWGCF] DptDpt - Remove tracking the ITS dead chips

PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/Tasks/mchAlignRecord.cxx
1. Use realigned muon in filling index table for matching.
2. Updating record task using slicing to get correct cluster-muon matching.
=> [PWGDQ] Couple of updates regarding muon (re-)alignment

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Updates in the task:
- including the D0/D0bar candidates flagged as both to increase the statistics, thus new process function for SameEvent and MixedEvent
- for now, keeping the possibility to run SameEvent and MixedEvent without double cases 
- improvements in the MCTruth process and corrections in the histograms for MCTruth
=> [PWGCF] FemtoUniverse: D0 task update

Scripts/find_dependencies.py
Add support for searching dependencies in the forward direction, i.e. table consumers and workflow output tables.
**Examples**
Normal (backward) mode:
- `-t BC_001` (table producers)
```bash
Table: BC_001
BC_001 <- ['o2-analysis-bc-converter']
```
- `-w o2-analysis-bc-converter` (workflow inputs)
```bash
Workflow: o2-analysis-bc-converter
o2-analysis-bc-converter <- ['BC']
```
Reverse (forward) mode:
- `-T BC` (table consumers)
```bash
Table: BC
BC -> ['o2-analysis-bc-converter']
```
- `-W o2-analysis-bc-converter` (workflow outputs)
```bash
Workflow: o2-analysis-bc-converter
o2-analysis-bc-converter -> ['BC_001']
```
=> Dependency finder: Add reverse mode

PWGLF/TableProducer/Nuspex/CMakeLists.txt, PWGLF/TableProducer/Nuspex/nucleiFlowTree.cxx, PWGLF/TableProducer/Nuspex/nucleiSpectra.cxx, PWGLF/TableProducer/Nuspex/nucleiUtils.h
Refactor nuclei flow tree implementation and add nuclei utilities header
Refactor nuclei flow tree and spectra to use kTriton flag for track filtering. Rearrangement of if chain for readability
Refactor nucleiFlowTree configuration and improve code readability
Removed unnecessary configurables
Added copyright header
Fix float conversion in event selections histogram and update header guard in nucleiUtils.h
Fix header guard in nucleiUtils.h to ensure proper inclusion
=> [PWGLF] Add task specific to flow

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx, PWGCF/Flow/Tasks/flowGfwTask.cxx
Apply last comments (Thank you) and take out of doProcessData the EventCounter histogram.
=> [PWGCF] Fix hEventCounter histogram

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- added Close Pair Rejection check for cascade - cascade pairs
- enabled O2-linter check for all the configurable (it was disabled before). O2-linter error for the configuration names will be ignored because this would affect many of my wagon configurations in the hyperloop.
=> [PWGCF] FemtoUniverse cascade task -- implemented Close Pair Rejection for cascade - cascade pairs

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/tableReader.cxx
Implementation of calculations in muon-selection task for single muon cumulant correlators that will be further used for reconstructing mixed-event v2 for cumulants method.
=> [PWGDQ] Implementation of single muon cumulants in muon selection

Common/Core/TrackSelection.cxx, Common/Core/TrackSelection.h, Common/Core/TrackSelectionDefaults.cxx, Common/Tools/trackSelectionRequest.cxx, Common/Tools/trackSelectionRequest.h, PWGJE/Core/JetDerivedDataUtilities.h, PWGJE/TableProducer/derivedDataProducer.cxx
Matching the 2011 definition (https://twiki.cern.ch/twiki/bin/viewauth/ALICE/HybridTracks). Verified consistency with AliPhysics via local tests
=> [PWGJE] hybrid track cuts for Run2 converted data

Common/TableProducer/PID/pidITS.cxx
- Simple renaming of `key` variable to `dataType`
=> [Common] Rename variable for temporary gitleaks hotfix

PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
PWGEM/PhotonMeson: fix to process function names
=> [PWGEM/PhotonMeson] fix to process function names

PWGJE/Tasks/jetTaggerHFQA.cxx
- Add processValFlavourDefMCD and processValFalvourDefMCP for validation of heavy-flavour definition
- fix response matrix (mcdjet.pt()->mcpjet.pt(), mcpjet.pt()->mcdjet.pt())
=> [PWGJE] Add validation function of heavy-flavour definition and fix response matrix

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
`femtoUniversePairTaskTrackV0Extended.cxx`:
- adds processes processSameEventV0MCReco and processMixedEventV0MCReco for analysis of MC V0 (similar to already existing processSameEventMCReco and processMixedEventMCReco fot track-V0)
- moves code from processSameEventV0 and processMixedEventV0 to doSameEventV0 doMixedEventV0 functions so it can also be used in new processes
- changes processMCSameEventV0 to fill QA for both V0s
`femtoUniverseProducerTask.cxx`:
- adds process processTruthAndFullMCCentRun3V0 for processing tracks and V0 MC with information about centrality in Pb-Pb collisions
=> [PWGCF] FemtoUniverse: add processes for analysis of MC reconstructed V0s

PWGHF/D2H/Tasks/taskD0.cxx, PWGHF/TableProducer/candidateSelectorD0.cxx
The track quality selection is added in D0 candidate selector as a simple filter, without changing any existing table structure.
The ITS cluster found and TPC crossed rows information is added into the ThnSparse with configurable option, for the purpose of analysis under different track quality selections in a single train run.
Modifications are tested both with data and MC, results are shown below. The modification works as expected.
=> [PWGHF] Add track quality selection for D0 candidate selector, add track quality axis in Thn for taskD0

PWGLF/DataModel/LFResonanceTables.h, PWGLF/TableProducer/Resonances/resonanceInitializer.cxx, PWGLF/TableProducer/Resonances/resonanceModuleInitializer.cxx, Tutorials/PWGLF/Resonance/resonancesCombine.cxx
- Simply detached the index columns.
- `cfgBypassCollIndexFill`, `cfgBypassTrackIndexFill` option added for derived dataset production
=> [PWGLF,Tutorial] Resonance Framework - Separate index table for derived dataset

PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
Replace GetGeneratorID (which is a 7-bits integer going from 0 to 127) to generatorID (which is a 16-bits integer going from 0 to 255), allowing to separate DPMjet events (generatorID=127) from Pythia events (generatorID = 255)
@nepeivodaRS for your information
=> [PWGLF] Replace GetGeneratorID to GeneratorID

PWGHF/D2H/Tasks/taskDirectedFlowCharmHadrons.cxx
added a flag to reduce the number of THnSparse histograms (for timebeing) because of large output root file size
=> [PWGHF] updated code to reduce memory size of the output file

PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- When using the `cfgDoReverseScaling` option the photon candidates no longer had zero mass. This should be fix with this change
=> [PWGEM,PWGEM-36] Fix Pi0FlowEMC non zero mass

PWGCF/FemtoUniverse/Core/FemtoUniverseEfficiencyCalculator.h, PWGCF/FemtoUniverse/Core/FemtoUniverseEfficiencyCorrection.h, PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackTrackExtended.cxx
- fixes segfault when CCDB timestamps configurable array is not empty
- changes the default values for some of the configurables for convenience
- updates the binning of `Tracks_*_MC/hPt` histogram to take values from `confTempFitVarpTBins` configurable (in `FemtoUniverseParticleHisto.h`)
- adds a new `EfficiencyCorrection` class, that builds on top of the `EfficiencyCalculator`
- it assumes the necessary weights are already calculated and directly stored in CCDB (instead of simple efficiency histograms)
- simplifies the flow on the side of the framework (less configurables, no metadata needed for CCDB objects) in preparation for support of histograms of more dimensions
- `EfficiencyCalculator` is kept for backward compatibility, however its flow is limited, as it does not include other …
=> [PWGCF/FemtoUniverse] Add `EfficiencyCorrection` class & fix pT binning in `FemtoUniverseParticleHisto`

PWGCF/MultiparticleCorrelations/Core/MuPa-Configurables.h, PWGCF/MultiparticleCorrelations/Core/MuPa-DataMembers.h, PWGCF/MultiparticleCorrelations/Core/MuPa-Enums.h, PWGCF/MultiparticleCorrelations/Core/MuPa-MemberFunctions.h, PWGCF/MultiparticleCorrelations/Tasks/multiparticle-correlations-ab.cxx
- support to skip bad runs from further processing
- prevent conflict between FixedNumberOfRandomlySelectedTracks and Toy NUA
- change TH1I to TH1F for CutCounter histos to prevent integer overshooting
- new series of QA profiles 2D (corr vs. ir vs. …, ir is always x-axis)
- fix for O2Linter, part 3 (prepending std:: all over the place)
=> [PWGCF] - improved memory management based on valgrind + massif profiling

PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR adds info for checking on residual miscalibration in EP determination for D meson analyses and process functions for Xic v2 studies.
@Marcellocosti @wuctlby for your information
=> [PWGHF] Adding azimuthal info of D and Xic

PWGCF/Flow/Tasks/flowGfwTask.cxx
Adding efficiency evaluation for 0-5%. Probably, this is redudant as it can be done through the **Filter collisionFilter** on the  FT0C. However, it is convinient to have both min bias and UCC in the same task.
=> [PWGCF] Add UCC efficiencies

PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
- Added a new Process function `processDataFast` which uses Filtered UD tables instead of the full ones, and it only produces derived data except 2-3 histograms. 
-  Removed the configurables `fddaCut`, `fddcCut` and `StrictEventSelection ` which is not required any more
- Small modifications in code
=> [PWGUD] Added new Process function and modified the tables

PWGUD/Tasks/flowCumulantsUpc.cxx
Remove BCsWithTimestamps, and define the run number directly from collision (for future use)
=> [PWGUD] Remove BCsWithTimestamps, and define the run number

EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterHelpers.h, PWGHF/TableProducer/trackIndexSkimCreator.cxx
@zhangbiao-phy @apalasciano in this PR I:
1) added the possibility to use TPC PID variables in the BDTs for Lc (and possibly Xic) in the software triggers
2) slightly modified some selections: for D0Pr and D*+Pr I added minimal track selections for the proton, while for the femto I modified the deuteron PID selections in order to be one sided only (for ITS or TPC we only keep > -Nsigma, while for TOF we only keep < Nsigma). Please note the signs, that imply that in the configurable the values should always be **without sign**
=> [PWGHF,Trigger] Add the possibility to use TPC PID in BDT for HFfilters + minor changes to selections

PWGJE/Tasks/jetSpectraCharged.cxx
- fix matched histogram eta selection so that one can get efficiency with eta sel only on mcp jet, and purity with eta sel only on mcd jet
- checkLeadConstituentPtForMcpJets now applies to max pt of lead track
- pTHatMaxMCD was used in place of pTHatMaxMCP in some places
- fix matched hist names in rhoareasubtracted case to fit in convention used in rest of file
=> [PWGJE] jetSpectraCharged: eta selection fixes for efficiency and purity, checkLeadConstituentPtForMcpJets fixes

ALICE3/Core/FastTracker.cxx, ALICE3/Core/FastTracker.h, ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
Adding the hit efficiency corrections used in the SolveTrack method in Delphes that is used to produce the LUTs for the OTF simulations 
link: https://github.com/AliceO2Group/DelphesO2/blob/master/src/DetectorK/DetectorK.cxx#L1421
=> [ALICE3] Add hit efficiency correction to the fasttracker

Common/CCDB/ctpRateFetcher.cxx, Common/CCDB/ctpRateFetcher.h
This PR adds an optional boolean argument (`fCrashOnNull`) to `ctpRateFetcher::fetch()`, controlling whether a fatal error is triggered when the CCDB file for a given RunNumber is missing.
`fCrashOnNull` is true by default, keeping the current behavior unchanged - and ensuring no impact on other tasks.
Tagging @mpuccio, @ddobrigk, @romainschotter and @lhusova for completeness.
=> [Common] Add option to prevent fatal error in ctpRateFetcher::fetch()

PWGCF/MultiparticleCorrelations/Tasks/threeParticleCorrelations.cxx
Several histograms were changed back from TH(1/2/3)F to TH(1/2/3)D to avoid hitting the floating point precision limit. The histograms that govern the correlations were left as THnSparseF.
=> [PWGCF] Changed several histograms back to Doubles

PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx
PWGEM/PhotonMeson: fix histogram name in pcmQCMC.cxx
=> [PWGEM/PhotonMeson] fix histogram name in pcmQCMC.cxx

PWGLF/Tasks/Resonances/heptaquark.cxx
separating lambda and anti-lambda
=> [PWGLF] separating lambda and anti-lambda

EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterHelpers.h
Follow-up of #10625 :
- revert changes in **isSelectedBachelorForCharmBaryon** method
- include an independent function for selecting Proton bachelors from Lc*
=> [PWGHF,Trigger] Fix selection and revert changes

PWGCF/Femto3D/DataModel/PIDutils.h, PWGCF/Femto3D/DataModel/singletrackselector.h, PWGCF/Femto3D/Tasks/femto3dPairTask.cxx, PWGCF/Femto3D/Tasks/femto3dQA.cxx
@njacazio @sofiatomassini @ercolessi
=> [PWGCF] adding SFINAE checks for PID + optimisation of the tasks

PWGLF/TableProducer/Strangeness/CMakeLists.txt, PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx, PWGLF/Utils/strangenessBuilderHelper.h
This PR: 
* adds an option `moveTPCOnlyTracks` to the strangenessBuilder whenever dealing with PCM candidates (using the TPC drift manager from @f3sch - thanks!) 
* moves all KF helper calls to the KFUtilities by @creetz16 - thanks a lot for modularizing! 
* adds a `buildV0CandidateWithKF` helper to the `strangenessBuilderHelper` for direct studies of DCAFitter with collinear option versus KFParticle fits. The `buildV0CandidateWithKF` has relevant options to be tested - mainly mass constraint and PV constraint. Similarly to what is done with the KF fit to cascades, a pre-minimization step with material corrections could also be added (since KFParticle fits do not consider material LUTs and such). 
@gianniliveraro pending some cross-checks from your side, this could go I guess... thanks!
=> [PWGLF] Improved treatment of photons in strangeness builder

Common/Core/fwdtrackUtilities.h, Common/DataModel/CMakeLists.txt, Common/DataModel/PropagatedFwdTrackTables.h, Common/TableProducer/CMakeLists.txt, Common/TableProducer/fwdtrackPropagation.cxx
This PR aims common effort for muon propagation (mainly for DQ, EM).
=> [Common] implement common muon-propagation task

PWGLF/DataModel/LFNonPromptCascadeTables.h, PWGLF/Tasks/Strangeness/nonPromptCascade.cxx, PWGUD/Tasks/upcTauTau13topo.cxx
=> [PWGLF] Add information to non prompt table

Common/TableProducer/centralityTable.cxx, Common/TableProducer/multiplicityTable.cxx
This fixes 
```
Cannot read class info from buffer of ATSK/12c99cc07f5f____/0
Cannot read class info from buffer of ATSK/12c99cc0863a____/0
```
errors that are the result of a `nullptr` being serialized. Now the empty list is always created, even if `produceHistograms` is `false`. I will add protection for `OutputObj` in a separate PR so we can avoid further issues like this. 
@njacazio @ktf @mhemmer-cern
=> [Common] Always initialize listCalib as it is serialized unconditionally

PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h
This PR adds a new $p_T$ histogram to `FemtoUniverseParticleHisto` only from primaries, for correct reconstruction efficiency calculation.
=> [PWGCF/FemtoUniverse] Add pT histo with only primaries.

PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
Adding muonBasic process function for code optimization. The menory consumption of Multiplicity table is ~200 MB for basic muon task, bringing beyond the limit the PSS memory for the dqEfficiency_withAssoc. Including this minimal muon process function should optimize the preocessing.
=> [PWGDQ] Adding muonBasic process function for code optimization

Scripts/o2_linter.py
Report comparisons against literal numbers other than -1, 0, 1.
Rationale:
- [ALICE O² C++ Coding Guidelines](https://rawgit.com/AliceO2Group/CodingGuidelines/master/coding_guidelines.html#Magic_numbers)
- [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-magic)
=> O2 linter: Add test for magic numbers

PWGUD/TableProducer/SGCandProducer.cxx, PWGUD/Tasks/sginclusivePhiKstarSD.cxx
The modification in SG Producer is done by adding the line 347 if(!collision.has_mcCollision()) return; to overcome the error "o2-analysis-ud-sgcand-producer, device shutting down. Reason: Accessing invalid index for mcCollision". It gives an error when there is no associated mc collision to a collision index.
=> [PWGUD] MC related error Solved

PWGLF/Tasks/Nuspex/antinucleiInJets.cxx
the response matrix of the jet pt is uploaded to a ccdb and retrieved now in the task for online unfolding of the reconstructed  pt of the jet
=> [PWGLF] adding response matrix for unfolding jet pt

EventFiltering/PWGLF/strangenessFilter.cxx, PWGLF/DataModel/LFNonPromptCascadeTables.h, PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
strangenessFilter:
- added counter for negative amplitudes to monitor new condition
- some debug prints removed
nonPromptCscade:
- multFT0A and FT0C added
- validated on data
https://cernbox.cern.ch/s/xLaeQfUkav5IiAE
https://cernbox.cern.ch/s/TJ7BMKhes9HGydO
=> [PWGLF,Trigger] dev: 1 added counter for negative amps filter 2 mult added to nonpromtcascade task

PWGLF/Tasks/Nuspex/antinucleiInJets.cxx
This PR refactors getPerpendicularAxis and getCorrectedPt for improved performance, numerical stability, and code clarity.
=> [PWGLF] small changes for code optimization

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update muon QA
=> [PWGEM/Dilepton] update muon QA

PWGLF/TableProducer/Strangeness/cascadebuilder.cxx
See #10754, the issue manifests with the latest xcode clang, to be seen if the CI will be happy
=> [PWGLF] Fix -Wmissing-template-arg-list-after-template-kw

PWGUD/Tasks/upcQuarkoniaCentralBarrel.cxx
See #10754, the issue manifests with the latest xcode clang, to be seen if the CI will be happy
=> [PWGUD] Fix -Wmissing-template-arg-list-after-template-kw

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx
- Adding event selection 
- fix muon propagation. Missing initailization of the magnetic field for muon tracks (VarManager::SetupMuonMagField();)
=> [PWGDQ] Adding event selection and fix muon propagation

Common/TableProducer/fwdtrackPropagation.cxx, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/matchingMFT.cxx
Common: update MFT matching
PWGEM/Dilepton: update mft task
=> Common: update MFT matching

PWGJE/Tasks/emcEventSelectionQA.cxx
- Add histogram to check if there are any EMCinTVX collisions without TVX
- Make last adjustments for O2Linter
=> [PWGJE,EMCAL-850] Add TVX check histogram for EMCal QA

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/Tasks/matchingMFT.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update table producer of muon
=> [PWGEM/Dilepton] update table producer of muon

PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx
=> [PWGHF] Fix matching to MC for generated Sc(2455).

PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: update skimmerPrimaryMuon.cxx
=> [PWGEM/Dilepton] update skimmerPrimaryMuon.cxx

Common/TableProducer/fwdtrackPropagation.cxx
Common: update fwdtrackPropagation.cxx
=> [Common] update fwdtrackPropagation.cxx

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
`FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx`:
- adds configurable `confStoreMCmothers` - if true, the PDG of the mother is stored in tempFitVar (0 for the primary particle), if false the particle PDG is saved (as before),
- adds `getMotherPDG` function that returns the PDG code of a mother, as it appears few times in the code,
- changes `fillMCParticle` to fill table with mother's PDG if `confStoreMCmothers` is true.
`FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx`:
- adds histogram to store PDGs of V0s mothers,
- add process function `processPairFractionsMCTruthV0` to fill this new histogram.
=> [PWGCF] FemtoUniverse: V0V0 pair fractions for MC truth

EventFiltering/PWGEM/HeavyNeutralMesonFilter.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/HeavyNeutralMeson.cxx, PWGEM/PhotonMeson/Utils/HNMUtilities.h
- HNM task based on HNM software trigger task
- To be used to debug omega meson resolution
- A configurable allows for SM wise shifts in eta and phi of clusters to align with extrapolated TPC track coordinates
=> [PWGEM/PhotonMeson] Add HeavyNeutralMeson analysis task

PWGDQ/TableProducer/tableMakerMC.cxx
Removing extra histogram filling doubling the number of counts in muon histograms
=> [PWGDQ] Removing ambiguous histogram filling

PWGHF/HFC/Tasks/taskFlow.cxx
In this PR I changed the binning in histograms to make them all configurable directly from the JSON file. 
For most histograms, I used the already defined "axisDeltaEta" or "axisDeltaPhi", I may create "axisEta/Phi" in a later PR if I see that it is problematic.
=> [PWGHF] taskFlow.cxx: change binning in histograms

DPG/Tasks/AOTEvent/eventSelectionQa.cxx
add dEdx vs occupancy QA histo, to monitor dEdx in a narrow momentum bin
=> [DPG] Update eventSelectionQa.cxx - add dEdx vs occupancy QA histo

PWGDQ/Core/MCSignalLibrary.cxx, PWGDQ/TableProducer/tableMakerMC.cxx
Adding extra signals for muclei and removing histos from table-maker
=> [PWGDQ] Adding extra signals for muclei and removing histos from table-maker

PWGEM/Dilepton/Tasks/matchingMFT.cxx
PWGEM/Dilepton: remove unnecessary histogram
=> [PWGEM/Dilepton] remove unnecessary histogram

PWGEM/Dilepton/Tasks/matchingMFT.cxx
PWGEM/Dilepton: update matchingMFT.cxx in MC
=> [PWGEM/Dilepton] update matchingMFT.cxx in MC

PWGEM/Dilepton/Tasks/matchingMFT.cxx
PWGEM/Dilepton: update matchingMFT.cxx
=> [PWGEM/Dilepton] update matchingMFT.cxx

PWGLF/DataModel/v0qaanalysis.h, PWGLF/TableProducer/Strangeness/v0qaanalysis.cxx, PWGLF/Tasks/Strangeness/v0postprocessing.cxx
=> [PWGLF] v0 analysis vs multiplicity: fix selections  add QA plots add feeddown

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/eventSelection.cxx, PWGEM/Dilepton/TableProducer/filterDielectronEvent.cxx, PWGEM/Dilepton/TableProducer/skimmerSecondaryElectron.cxx, PWGEM/Dilepton/Tasks/Converters/CMakeLists.txt, PWGEM/Dilepton/Tasks/Converters/eventConverter2.cxx, PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
PWGEM/Dilepton: support RCT flag
=> [PWGEM/Dilepton] support RCT flag

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/eventSelection.cxx
PWGEM/Dilepton: update RCT selection
=> [PWGEM/Dilepton] update RCT selection

PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/kstarpbpb.cxx
=> [PWGLF] updated existing flow code for spin alignment study

PWGHF/D2H/Tasks/taskOmegac0ToOmegapi.cxx, PWGHF/TableProducer/candidateSelectorOmegac0ToOmegaPi.cxx, PWGHF/TableProducer/treeCreatorOmegacToOmegaPi.cxx
Fixed some issues in histogram filling and selections. In particular, the reconstruction flag was not checked before filling the trees, and the current boolean flag that is provided by the candidate selector has some problems when used with partitions. Please @Yunfan-Liu have a look.
@mtorresc15
=> [PWGHF] Fixes for OmegaC0 workflows

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/matchingMFT.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update DCA calculation
=> [PWGEM/Dilepton] update DCA calculation

PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx
In hyperloop, modifying the pT bins of interest makes the tests to fail while locally they don't fail
Tracking the insertion of the pT bins of interest will allow to check what the issue is
=> [PWGCF] DptDpt - Tracking the insertion of pT bins of interest

PWGLF/Tasks/Resonances/chk892Flow.cxx
- Add Run Condition Table Flag checker
=> [PWGLF] Chk892Flow - Add RCT flag Checker

PWGCF/GenericFramework/Tasks/flowGenericFramework.cxx, PWGCF/JCorran/Tasks/jFlucEfficiencyTask.cxx
- Add track selection cut additionally with detailed configurations.
- Add RCT flag checker
=> [PWGCF] jFlucEfficiencyTask - Add track selection systematics

PWGJE/Core/utilsBcSelEMC.h, PWGJE/Tasks/emcEventSelectionQA.cxx
- Add Core/utilsBcSelEMC.h where EMCEventSelection struct is defined with configurables to select BCs based on different selection bits.
- Add EMCEventSelection to emcEventSelectionQA.cxx
=> [PWGJE,EMCAL-670] Add BC selection to EMCal QA task

PWGLF/TableProducer/Resonances/resonanceInitializer.cxx, PWGLF/TableProducer/Resonances/resonanceModuleInitializer.cxx
Add common RCT flag checker helper, disabled by default.
=> [PWGLF] Resonance Framework: Add RCT Flag checker

PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx
Also
- fixed `linter` magic number usage recommendations
- don't process individual tracks if only pairs are required
=> [PWGCF] DptDpt - Increasing the level of pT bins tracking

PWGDQ/TableProducer/tableMaker.cxx
1. Regrouping some configurables to make space for more definitions
2. Using double-slicing for realigned muon table
=> [PWGDQ] Fix JIT compilation memory leak using double slicing

Scripts/o2_linter.py
`name/function-variable`: Fix false positives for `throw`
=> O2 linter: TestNameFunctionVariable: Fix false positives

PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx
Also
- full support for `linter` recommendations
- independence of detector and generator level processing
=> [PWGCF] DptDptQc - Proper initialization of pT bins of interest map

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx, PWGLF/Utils/strangenessBuilderHelper.h
Adds a check to reject TPC-only tracks from V0 building via the strangeness builder helper. Controlled by the last `buildV0candidate` parameter, with default behaviour being reject. 
Crucially, this rejects 80-90% of `aod::V0s` in high-IR pp because of the way we store V0s with at least one TPC-only track: we duplicate V0s many times (up to 20x) in different collisions, and having this overlooked when doing traditional (K0/Lambda) building could introduce unwanted CPU usage and, in the worst case, spurious background in large quantity. 
Tagging also @mpuccio as this will directly impact current trigger code as well even if the change is not in the EventFiltering directory. Hope this helps and happy easter!
=> [PWGLF] Protect against accidental acceptance of TPC-only V0s

PWGLF/DataModel/LFStrangenessTables.h, PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx
Add Neutrons within the ZDC acceptance in the strangeness data model in order to mimic the ZDC response in MC (proportional to the number of neutrons)
=> [PWGLF] Add Neutrons within the ZDC acceptance in the strangeness data model

PWGDQ/Core/VarManager.h, PWGDQ/TableProducer/tableMaker.cxx
Small fix to ensure the full functionality of muon selection criteria in the case of using realigned muon tracks
=> [PWGDQ] Add reading of track type from realigned muons

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/MCSignalLibrary.cxx, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/taskFwdTrackPid.cxx
Nuclei signals + Nuclei tables + Nuclei cuts + minimal muon cuts
=> [PWGDQ] Update Nuclei cuts and signals

EventFiltering/PWGLF/strangenessFilter.cxx, EventFiltering/filterTables.h, PWGLF/Tasks/Nuspex/angularCorrelationsInJets.cxx
adding trigger condition for lambdalambda
=> [PWGLF,Trigger] [Event Filtering] adding trigger condition for lambdalambda

EventFiltering/CMakeLists.txt, EventFiltering/PWGCF/CFFilterAll.cxx, EventFiltering/filterTables.h, PWGLF/TableProducer/Nuspex/hypertriton3bodyfinder.cxx
This PR contains the following changes:
- add ρ-d and Φ-d trigger
- Use 2 trigger channels for each CF trigger. With this setup, we can have one trigger with loose selection on kstar/q3. This trigger can be downsampled and later used to obtain a mixed event or background correlation function. The other trigger has tight selection on kstar/q3, allowing us to keep all critical events.
- Rework the  directory structure for QA histograms
- Organize the configurable in groups and add a configurable to change the binding of QA histograms
- Move to strangenessbuilderhelper to be independent of strangenessbuilder
=> [PWGCF,PWGLF,Trigger] Update PWGCF trigger for 2025 data taking

PWGHF/HFC/Tasks/taskCorrelationDsHadrons.cxx
Dear all,
Just added the possibility to select a BDT prompt score interval in view of performing a fully data-driven analysis.
Cheers,
Samuele
=> [PWGHF] Ds-h correlation, added possibility to select a BDT prompt score interval

EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterHelpers.h
=> [PWGHF,Trigger] Separate proton pt threshold for LcRes and ThetaC

PWGEM/PhotonMeson/DataModel/bcWiseTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/bcWiseClusterSkimmer.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/emcalBcWisePi0.cxx, PWGJE/DataModel/EMCALClusters.h, PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add BC wise skimming tables for 
- BCs
- Collisions within the BC
- (MC) clusters in the BC
- Generated pi0s in the BC
- Add skimming task to fill these tables
- Add analysis task that produces invmass-pT distributions from the derived data tables
- Add MC labels to ambiguous clusters in JE EMCal correction task
=> [PWGEM/PhotonMeson,PWGJE/EMCal] Add bc wise skimming and analysis task

.github/workflows/o2-linter.yml, Scripts/o2_linter.py
- Support severity levels and tolerated tests per directory
- Unify error message format.
Summary of the new features:
- Introduce two levels of severity (warning, error) which are distinguished with a "tolerated" flag.
- Both levels are reported in the terminal log but only errors make the linter fail and only errors show up in the PR as GitHub annotations.
- The total numbers of errors (issues), warnings (tolerated), and disabled issues are reported as a comment in the PR.
- Example: "**O2 linter results:** ❌ 41 errors, ⚠️ 13 warnings, 🔕 0 disabled"
- The default level for all tests is "error" and the "tolerated" flag is set per test and per file based on the list of tolerated tests listed in a special file `o2linter_config` in one of the parent directories.
- Configs in a deeper …
=> [Infrastructure] O2 linter: Support severity levels and tolerated tests per directory

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
@Marcellocosti - fixes the autodetection of versioned tables - tested for the `V0MCCores_002` one you faced but will work also for all other tables with versions bigger than base. 
Also adds an extra printout to the enabled tables list such that the task(s) that enabled each one of the tables can be more readily inspected from the logs.
=> [PWGLF] Autodetect fix: properly find versioned tables

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h
I have added the definition of angular variable in production plane for polarization analysis
=> [PWGDQ] Adding polarization variable in production plane

EventFiltering/PWGEM/HeavyNeutralMesonFilter.cxx, EventFiltering/filterTables.h
- Remove the four trigger flags for spectra trigger (as required downscaling would be too large)
- Split up ppomega and domega trigger (same for eta')
-> 6 trigger channels instead of 8
- Also added K*/Q3 Vs Pt histograms
=> [PWGEM,Trigger] [EventFiltering] Remove HNM spectra trigger

PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx, PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx, PWGHF/TableProducer/candidateCreator2Prong.cxx, PWGHF/TableProducer/candidateCreator3Prong.cxx, PWGHF/TableProducer/candidateCreatorCascade.cxx, PWGHF/TableProducer/candidateCreatorDstar.cxx, PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx, PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx, PWGHF/Utils/utilsEvSelHf.h
Hi @mfaggin @zhangbiao-phy, this PR adds the possibility to apply the RCT event selection in the HF code. 
I still keep it draft for the pending questions I asked to the experts in the mail thread.
@pstahlhu @creetz16 @JaeYoonCHO @sh-lim (I could not find Krista, please add her if you know her github account) while implementing this I noticed that there is no event selection applied at all for the Xic+ -> XiPiPi, could you please add it in a dedicated PR, or do you prefer me to do it?
=> [PWGHF] Add RCT selection in HF event selection utils

PWGJE/Core/utilsBcSelEMC.h
- removed rejection flags unique to collisions from BC selection
- updated sel8 definition from Run2 definition to Run 3 definition
- fixed setting of bitmask for sel8 to be set when BC fails sel8 selection, was the other way around before
=> [PWGJE,EMCAL-670] Update BC selection to EMCal QA task

ALICE3/TableProducer/OTF/onTheFlyTOFPID.cxx
=> [ALICE3] A3:  Add option for ev time

PWGJE/TableProducer/jetTaggerHF.cxx, PWGJE/Tasks/jetTaggerHFQA.cxx
jetTaggerHFQA.cxx
- To reduce unnecessary memory usage, the histograms filled by FillXY, FillZ, and FillXYZ are subdivided into finer bins.
jetTaggerHF.cxx :
- Modification of the IP tagging method
- IIf the number of resolution functions loaded from the CCDB is not 7 (since the pT range is divided into 7 bins), a constant value will be used as the parameter instead.
- Modified to load different resolution parameters from the CCDB depending on the jet flavour.
=> [PWGJE] modification of IP tagging method

PWGEM/PhotonMeson/DataModel/bcWiseTables.h, PWGEM/PhotonMeson/TableProducer/bcWiseClusterSkimmer.cxx, PWGEM/PhotonMeson/Tasks/emcalBcWisePi0.cxx
- Add true + gen functionality to bc wise pi0 task
- Remove unnecessary tables from bc wise derived data format
- Allow for "trigger selection" via configurable when using bc wise pi0 task
=> [PWGEM/PhotonMeson] Add MC functionality to BC wise pi0 task

PWGDQ/TableProducer/tableMaker_withAssoc.cxx
Same implementation for table-maker-with-assoc as previously done in commit [826faec](https://github.com/AliceO2Group/O2Physics/commit/826faec55b2bfc1e870642a3abfb2e117df9fb84)
=> [PWGDQ] Process using realigned muon track in table-maker-with-assoc

PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx, PWGEM/Dilepton/Utils/MCUtilities.h
Put for the moment both normalization to check with charm on a big scale that this is ok.
=> [PWGEM] Fix for normalization of beauty cocktail.

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
Adding processMCGen & processMCGenWithEventSelection as for B->J/psi+K analysis
=> [PWGDQ] Updating dqEfficiencyWithAssociation

PWGHF/HFC/TableProducer/CMakeLists.txt, PWGHF/HFC/TableProducer/femtoDreamProducer.cxx
For the Lcp femto analysis with triggered data: apply the second BDT application on top of the Lc selector with BDT used for triggered data. @fgrosa
=> [PWGHF] Implement the additional BDT model application on top of the trigger BDT used in the Lc selector

PWGEM/PhotonMeson/DataModel/bcWiseTables.h, PWGEM/PhotonMeson/TableProducer/bcWiseClusterSkimmer.cxx, PWGEM/PhotonMeson/Tasks/emcalBcWisePi0.cxx
- Filters in emcalBcWisePi0.cxx now correctly use the configurable values and not just the defaults -> changed a few data types from unsigned to signed int to allow for filter comparison
- z vertex position now correctly read as int16 (instead of int8)
- Added MC pi0 min pT configurable to reduce derived data size
- Added check for mc particle ID in map before calling its value (map does not contain all pi0s, as not all pi0s are stored)
=> [PWGEM/PhotonMeson] Bug fixes for BC wise pi0 task

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
@fcatalan92 this fixes the bug that manifested itself in the omegaC when building in the KF path. 
The issue is that in a recent commit I introduced a check for TPC-only V0s being used in cascades in the first entry point of the builder and removed those cascades from the pool, which accidentally renders the joinability between `Cascades` and the `Cascades`-to-[]Data interlinks false because a tiny amount of candidates is rejected and the interlink tables are smaller. This is inadequately reported by the framework for some reason in the particular use case of the OmegaC building, since there was a segmentation fault instead of a message of "table size mismatch" (tagging also @aalkin - I suspect it may be because we are dealing with linked derived data here, not sure). I found out the …
=> [PWGLF] Fix bug in to-build cascade list mapping

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreatorXic0Omegac0.cxx
Evaluate the resolution of the particles reconstructed using the KFParticle method.
=> [PWGHF] Add KFParticle Quality Assurance in XicToXiPi candidate creator

ALICE3/TableProducer/alice3-multicharm.cxx
This PR aligns the selections in the analysis task with the ones from the LoI
=> [ALICE3] Add additional selections with corresponding QA histograms

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
Issue of dqEfficiency_withAssoc when running on hypeloop (not when running locally on MacOs). Test moving to a single process function to take into accout all and selected only MC collisions.
=> [PWGDQ] Fixing issue for dqEfficiency_withAssoc

ALICE3/TableProducer/OTF/onTheFlyRICHPID.cxx
Solved issues with original onTheFlyRICHPID.cxx task.
Now updates should be done correctly according to .json input.
Added a new function for analytic calculation of ring angular resolution sector-by-sector.
Included the possibility to have different aerogel refractive index for the different modules.
=> [ALICE3] Update OTF RICH PID

PWGDQ/TableProducer/tableMaker_withAssoc.cxx
We need all clusters for global tracks, both from MCH and MFT. I added this information into the MuonExtra table.
=> [PWGDQ] Adding global clusters to MuonExtra table

PWGLF/Tasks/Strangeness/cascadeanalysisMC.cxx
These obsolete V0 tables cause segmentation faults when using the new strangenessbuilder
=> [PWGLF] Remove obsolete tables from cascadeanalysisMC

PWGHF/TableProducer/CMakeLists.txt, PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx
@fgrosa @JaeYoonCHO @sh-lim @klsmith15k
=> [PWGHF] Add HF event selection and centrality process functions to Xic to Xi Pi Pi

PWGLF/TableProducer/Nuspex/CMakeLists.txt, PWGLF/TableProducer/Nuspex/he3HadronFemto.cxx
Li4 dose not have pdg code in PDG_t and constants::physics::Pdg so I just leave it there
=> [PWGLF] remove DCAfitter and fixed O2linter error

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
Add QC histogram for checking the filling and reading of boolean standard columns
=> [PWGLF] Add QC histogram for checking the filling and reading of boolean standard columns

PWGLF/DataModel/LFNonPromptCascadeTables.h, PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
Fix MC table filling + restore variables cleaned by mistake in PR https://github.com/AliceO2Group/O2Physics/pull/10742.
@lietava @mpuccio
=> [PWGLF] Fix table filling in the nonPromptCascade task

PWGEM/PhotonMeson/DataModel/bcWiseTables.h, PWGEM/PhotonMeson/TableProducer/bcWiseClusterSkimmer.cxx, PWGEM/PhotonMeson/Tasks/emcalBcWisePi0.cxx
- Add accepted pi0 histogram
- Only fill generated histograms for primary pi0s
- Add epsilon to each float conversion to avoid binning effects
=> [PWGEM/PhotonMeson] Changes to BC wise pi0 task

PWGLF/TableProducer/Strangeness/cascqaanalysis.cxx, PWGLF/Tasks/Strangeness/derivedupcanalysis.cxx
Changed several histograms from TH1F to TH1D in cases where the expected number of counts may exceed 2^(24). This prevents potential precision loss or overflow issues in bins with very high statistics.
TH1F uses 32-bit floats, which lose precision when bin counts exceed ~16 million -- small increments may be ignored. Switching to TH1D (64-bit) ensures accurate bin content in high-statistics cases.
=> [PWGLF] switch TH1F to TH1D for high-count histograms

Common/TableProducer/fwdtrackToCollisionAssociator.cxx
Common: add setBcWindow in fwdtrackToCollisionAssociator.cxx
=> [Common] add setBcWindow in fwdtrackToCollisionAssociator.cxx

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
Increase the Range of the DCAz from 1.0 to 3.5 cm
And DCAxy,z from 10 to 20 sigma
=> [PWGEM] increase range of DCA QA histograms for singleTrackQCtask

EventFiltering/PWGLF/nucleiFilter.cxx
=> [PWGLF,Trigger] Nuclei trigger: fix wrong nested loop and V0 CosPA calculation

PWGCF/FemtoUniverse/Core/FemtoUniverseCascadeSelection.h, PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- With these changes both Xi and Omega cascades can be produced simultaneously
- Competing mass rejection is implemented by allowing either Xi or Omega but not both
=> [PWGCF]  PWGCF: FemtoUniverse cascade task -- implemented changes to produce both Xi and Omega simultaneously

Common/CCDB/CMakeLists.txt
to be added into $O2PHYSICS_ROOT/include (and solve the compilation of O2OpenAccess application)
=> [Common] [Common]::CCDB:: add RCTSelectionFlags.h as header only library

PWGEM/PhotonMeson/DataModel/bcWiseTables.h, PWGEM/PhotonMeson/TableProducer/CMakeLists.txt, PWGEM/PhotonMeson/TableProducer/bcWiseClusterSkimmer.cxx, PWGEM/PhotonMeson/Tasks/emcalBcWisePi0.cxx
- Add centrality axis to most histograms in analysis task
- Add pile-up correction information (mu based on interaction rate)
- Fix rounding error from derived data -> nextafter instead of +epsilon
=> [PWGEM/PhotonMeson] Add pile-up and centrality dependence to pi0 task

PWGEM/Dilepton/Tasks/lmeeHFCocktail.cxx
Only electrons from open-charm or open-beauty hadrons expected to decay semileptonicly. Otherwise quarkonia are still inside.
=> [PWGEM] Reject all quarkonia in the HF cocktail

PWGLF/TableProducer/Strangeness/lambdaJetpolarizationbuilder.cxx, PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/lambdaJetpolarization.cxx
Dear Experts:
The recent code is mainly used to calculate Lambda local polarization induced by jet.
I have two .cxx files and one header file to complete my analysis.These codes have been updated.
TableProducer : lambdaJetpolarizationbuilder.cxx : The file has not been modified.
Tasks ：lambdaJetpolarization.cxx : Add fast-jet algorithm to reconstruct jet
CMakeLists.txt : The dependencies related to jet reconstruction libraries have been added to this task.
O2Physics::PWGJECore FastJet::FastJet FastJet::Contrib O2Physics::EventFilteringUtils
DataModel : lambdaJetpolarization.h : The file has not been modified.
Best wishes,
Youpeng Su
May 9, 2025
=> [PWGLF] Lambda local polarization induced by jet in pp collision 13.6 TeV

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/TableProducer/tableMakerMC.cxx
1. Fix the reconstructed muon histogram filling issue: add a reset of iteration
2. Add a subgroup of histograms in the histogram library
=> [PWGDQ] Fix the QA histogram filling issue of muons in table-Maker-MC

PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx, PWGHF/TableProducer/treeCreatorXicToXiPiPi.cxx
@JaeYoonCHO @sh-lim @klsmith15k
- Update MC matching to include the latest updates to RecoDecay functions from recent PRs
- remove debug flags from the output trees (unnecessary memory consumption, different logic between reconstructed + generated), instead add counter histogram for the matching of the reconstructed candidates
- add histograms for the number of decayed pions and number of material interactions of daughter particles from matched $\Xi_{\rm{c}}^{+} \rightarrow \Xi^{-} \pi^{+} \pi^{+}$ decays
- Use a filter for filling of generated particle tables in the tree creator
=> [PWGHF] Update MC matching in XicToXiPiPi workflow

PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/DataModel/FemtoDerived.h
Adding DCA plots needed for the template fit for the p-phi analysis. This will add this option also for other correlations.
=> [PWGCF] FemtoUniverse -- Adding DCA plots

PWGHF/D2H/TableProducer/converterReducedHadronDausPid.cxx, PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx, PWGHF/D2H/Tasks/taskXic.cxx, PWGHF/DataModel/CandidateReconstructionTables.h, PWGHF/HFC/TableProducer/femtoDreamProducer.cxx, PWGHF/TableProducer/candidateSelectorDplusToPiKPi.cxx, PWGHF/TableProducer/candidateSelectorDsToKKPi.cxx, PWGHF/TableProducer/candidateSelectorLc.cxx, PWGHF/TableProducer/candidateSelectorLcPidMl.cxx, PWGHF/TableProducer/candidateSelectorXicToPKPi.cxx, PWGHF/TableProducer/derivedDataCreatorDplusToPiKPi.cxx, PWGHF/TableProducer/derivedDataCreatorLcToPKPi.cxx, PWGHF/TableProducer/treeCreatorDplusToPiKPi.cxx, PWGHF/TableProducer/treeCreatorDsToKKPi.cxx, PWGHF/TableProducer/treeCreatorLbToLcPi.cxx, PWGHF/TableProducer/treeCreatorLcToPKPi.cxx, PWGHF/TableProducer/treeCreatorXicToPKPi.cxx
Necessary modifications due to https://github.com/AliceO2Group/O2Physics/pull/11141
=> [PWGHF] Fix data type for D+ and Ds tables.

PWGHF/D2H/TableProducer/dataCreatorCharmHadPiReduced.cxx, PWGHF/D2H/Tasks/taskB0Reduced.cxx, PWGHF/D2H/Tasks/taskBplusReduced.cxx, PWGHF/D2H/Tasks/taskBsReduced.cxx, PWGHF/D2H/Tasks/taskLbReduced.cxx, PWGHF/DataModel/CandidateReconstructionTables.h
Hi @fgrosa @fcatalan92 @apalasciano, with this PR I included the B->DK decay channels into the workflow, as the production of the corresponding MC is ongoing. Can you please take a look to check if this is fine for you? Note that this changes the value for the selection of `PartlyRecoDecay`.
@zhangbiao-phy I have changed the name of the `enum` entry for the Lb->LcK decay, and fixed an inconsistency in the histogram filling, can you also check this is fine for you?
=> [PWGHF] Add B->DK decay channels in analysis workflows

PWGJE/Core/JetTaggingUtilities.h, PWGJE/Core/MlResponseHfTagging.h, PWGJE/TableProducer/jetTaggerHF.cxx, PWGJE/TableProducer/secondaryVertexReconstruction.cxx, PWGJE/Tasks/bjetTaggingML.cxx, PWGJE/Tasks/bjetTreeCreator.cxx
A cut on the IPxy and IPz has been implemented to reject tracks with extremely large DCAs for training the ML model and also for the secondary vertex reconstruction.
I also implemented a compatibility with models that uses multi classification with softmax instead of just using binary classification with sigmoid.
=> [PWGJE] Adding a cut on IP for TreeCreator and SV reconstruction

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: update skimmerPrimaryElectron.cxx for eID in low B
=> [PWGEM/Dilepton] update skimmerPrimaryElectron.cxx for eID in low B

PWGLF/TableProducer/Strangeness/Converters/CMakeLists.txt, PWGLF/TableProducer/Strangeness/Converters/straevselsconverter5.cxx, PWGLF/TableProducer/Strangeness/Converters/zdcneutronsconverter.cxx
- add RCT info in `straevselsconverter5` to allow the use of RCT conditions for previous derived data (with StraEvSels_004 or below)
- add dummy ZDC neutron table if required in task subscription
=> [PWGLF] Add converters in strangeness data model for missing info/tables

DPG/Tasks/AOTTrack/qaEfficiency.cxx
=> [DPG] Add TF border cut.

PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
1. This follows the previous 826faec which implemented a process in standard table-maker using realigned muon tracks; the same implementation is now made for table-maker-mc-with-assoc.
2. Two new process(pp and PbPb) are added into table-maker-mc-with-assoc using realigned muons.
=> [PWGDQ] Process using realigned muon track in table-maker-mc-with-assoc

PWGCF/DataModel/FemtoDerived.h, PWGHF/HFC/TableProducer/femtoDreamProducer.cxx, PWGHF/HFC/Tasks/taskCharmHadronsFemtoDream.cxx
For convenience in doing the mixed event locally, I added the collision index to the table 
- Separate into 3 tables: charm, track, and collision
- Add eta and phi into the table --> calculate k*, kT, mT locally
- Remove table filling in the mix-event function (if the test is smooth, this part will be deleted later)
=> [PWGHF,PWGCF] Split same-event table and add the collision infos into lcp femto task 

PWGDQ/Core/HistogramsLibrary.cxx
SetRange option in THnSparse doesn't allow for measurement within 1GeV interval. Fine binning is required.
=> [PWGDQ] Fine binning for precise measurement

Common/DataModel/FwdTrackReAlignTables.h, Common/TableProducer/muonRealignment.cxx, PWGDQ/Core/VarManager.h, PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx
- Data model changed for realigned muons so they will take the same format as original fwdtrack tables with only necessary kinematics updated if requiring realignment. At DQ maker level, this new table will be treated in the same way as fwdtracks table.
- Only `fwdtrack_as` has to be replaced by `rawIteratorAt` to make use of `fwdtrackId` in `FwdTrackAssoc` in case of realigned muons which is not bounded to `FwdTrackAssoc` table. The later operation is safe in the sense that realigned muons table preserves the row-by-row correspondance with the orignal fwdtracks table.
=> [Common,PWGDQ] Optimising muon realignment code

PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
Here are few changes that i made:
- Removed process functions (data and MC reco) which used only the filtered tables, instead i used filtering on the main functions
- Changed the `TLorentzVector` to recommended template.
- Added few more configurables for vertex cuts and number of PV Contributors. 
- Renamed few variables
- Only single truegapside=2 events selected
=> [PWGUD] Removed 2 process functions and fixed o2-linter issues

PWGCF/Femto3D/TableProducer/singleTrackSelector.cxx, PWGCF/Femto3D/Tasks/femto3dPairTaskMC.cxx, PWGCF/Femto3D/Tasks/femto3dQA.cxx
=> [PWGCF] adding RCT evsel flag + ITS param. for PID in MC

PWGCF/TableProducer/CMakeLists.txt, PWGCF/TableProducer/dptDptFilter.cxx, PWGCF/TableProducer/dptDptFilter.h, PWGCF/Tasks/CMakeLists.txt, PWGCF/Tasks/dptDptCorrelations.cxx, PWGCF/Tasks/dptDptFilterQa.cxx, PWGCF/Tasks/matchRecoGen.cxx, PWGCF/TwoParticleCorrelations/Tasks/dptDptEfficiencyAndQc.cxx, PWGCF/TwoParticleCorrelations/Tasks/dptDptPerRunExtraQc.cxx, PWGCF/TwoParticleCorrelations/Tasks/dptDptPerRunQc.cxx
It will take a few steps because we wanted to keep track of the changes 
This first step is just source file renaming when needed
=> [PWGCF] DptDpt - First step in implementing linter recommendations

PWGJE/Tasks/jetHadronRecoil.cxx
=> [PWGJE] Adding a histogram filled with inclusive jet constituents

CODEOWNERS, PWGHF/D2H/Macros/HFInvMassFitter.cxx, PWGHF/D2H/Macros/HFInvMassFitter.h, PWGHF/D2H/Macros/config_massfitter.json, PWGHF/D2H/Macros/runMassFitter.C
**Code cleaning:**
* obsolete headers, variables and pieces of code removed;
* use `TH1` instead of `TH1F` to be more general with possible input histogram type;
* more safe type castings employed (e.g. avoid `reinterpret_cast` and use `Get<TH1>()` instead of `Get()` before `static_cast`);
* instances from the standard library (`string`, `vector`, `cout`, etc.) prepended with `std::`;
* removed **using** directive from header;
* the code is made less D0-hardcoded;
* fixed typos in comments and variable names.
**Enhancement:**
* added signal evaluation via bin counting (in addition to integral);
* added plotting features:
* semi-opaque pure signal plot
* background pre-fit function
* highlight peak region (which is usually 3 sigma) with vertical lines.
The json config file is updated …
=> [PWGHF] HF invariant mass fitter: code cleaning and minor enhancement

PWGLF/TableProducer/Strangeness/strangederivedbuilder.cxx, PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
-  Add TPC PID Vs Mass correlation cuts in the strangeness builder 
-  Capture spurious cascade with TPC-only-V0 (thanks @gianniliveraro for catching this)
@ddobrigk for your information
=> [PWGLF] Add TPC PID Vs mass correlation cuts + other fix in the strangenessbuilder

PWGLF/TableProducer/Strangeness/hStrangeCorrelationFilter.cxx, PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
add extra eta cut for mother particles while doing feed down matrix
set some parameters to save memory using
=> [PWGLF] Small bug fix for feed-down correction

.mega-linter.yml
The current default configuration confuses the C++ code with C.
=> [Infrastructure] MegaLinter: Configure cppcheck

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx, PWGEM/Dilepton/Tasks/taggingHFE.cxx
PWGEM/Dilepton: update treeCreatorElectronMLDDA.cxx
=> [PWGEM/Dilepton] update treeCreatorElectronMLDDA.cxx

PWGCF/FemtoUniverse/Core/FemtoUniverseParticleHisto.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
- fixed naming issue of cascade QA histograms
- added new comments
- added TOF check for cascade children in cascade-cascade process functions
=> [PWGCF] FemtoUniverse cascade task -- fixed cascade QA histogram and added TOF check for cascade-cascade

PWGHF/HFC/Tasks/taskFlow.cxx
What is new in this PR : 
- added new filters on MFT tracks (also, moved the MFT tracks eta cut from a function to a filter -> I tried it before I thought it didn't work but it should work, this will slightly improve memory consumption)
- changed the selectionFlag for HF
- added new ConfigurableAxis to make the difference between plots which requires eta/phi distribution or delta eta/delta phi distribution
- added process functions and all configurables + declarations needed to make it work for MC generated
- added an attempt to create process function for MFT track efficiency (to be extended to D0 and Lc efficiencies, also Tpc tracks ?)
- added differential invariant mass plots vs pT vs Multiplicity
=> [PWGHF] taskFlow.cxx: change in histograms, change in MFT track selection, new process functions for MC

PWGJE/Tasks/fullJetTriggerQATask.cxx, PWGLF/DataModel/LFSigmaTables.h, PWGLF/TableProducer/Strangeness/sigma0builder.cxx, PWGLF/Tasks/Strangeness/sigmaanalysis.cxx
This PR includes the following updates:
- New functions for processing generated photons and Lambdas, taking event selection into account. These are intended for use in efficiency calculations and follow the implementation used in derivedlambdakzeroanalysis. A similar approach for Sigma0s is planned for a future update;
- Removal of IR information from the Sigma0 data model;.
- Safeguard added to the analyzeV0CollAssoc function to prevent double-counting of V0s. A check to ensure that only primary particles are considered has also been introduced.
=> [PWGLF] Function to process generated V0s in sigma0 tasks + minor fixes

Common/Tasks/trackqa.cxx
- Include what you use.
- `Shifting 32-bit value by 63 bits is undefined behaviour [shiftTooManyBits]`
=> [Common] Fix bugs found by cppcheck and cpplint

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
Add option to select only physical primary MC V0s (if not associated to a recoed one)
=> [PWGLF] Add option to select only physical primary MC V0s (if not associated to a recoed one)

PWGJE/Core/JetTaggingUtilities.h, PWGJE/Tasks/trackJetQA.cxx
- `Invalid abs() argument nr 1. A non-boolean value is required. [invalidFunctionArgBool]`
- `Shifting 32-bit value by 63 bits is undefined behaviour [shiftTooManyBits]`
=> [PWGJE] Fix bugs found by cppcheck

ALICE3/DataModel/A3DecayFinderTables.h, ALICE3/TableProducer/CMakeLists.txt, ALICE3/TableProducer/alice3-correlatorDDbar.cxx, ALICE3/TableProducer/alice3-decayfinder.cxx, ALICE3/Tasks/CMakeLists.txt, ALICE3/Tasks/alice3-taskcorrelationDDbar.cxx
Slight revision of decay finder code (produce tables used by DDbar correlation codes, add MC truth outcome, add further kinematic quantities) and commit of DDbar correlator and DDbar analysis task, to be used with on-the-fly simulations for ALICE3
=> [ALICE3] First development of DDbar correlations for usage with OTF sims

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
- Add lifetime preselection of V0s and cascades, in addition to the already implemented mass Vs TPC PID correlation selections
- Add QA histogram for keeping track of the effectiveness of the preselections
=> [PWGLF] Add lifetime preselection + QA histogram in strangenessbuilder

ALICE3/Core/FastTracker.cxx, ALICE3/Core/FastTracker.h, ALICE3/TableProducer/OTF/CMakeLists.txt, ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
- align executables with names
- manage FastTracker variable space
=> [ALICE3] A3 FastTracker: updated data member protection

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: fix in treeCreatorElectronMLDDA.cxx
=> [PWGEM/Dilepton] fix in treeCreatorElectronMLDDA.cxx

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: fix treeCreatorElectronMLDDA.cxx again
=> [PWGEM/Dilepton] fix treeCreatorElectronMLDDA.cxx again

EventFiltering/PWGHF/HFFilterHelpers.h
For some reason with an asymmetric cut (to keep everything compatible with deuteron and heavier) we select many tracks with very large `NsigmaTPC(de)`, which increase drastically the selectivity of the charm femto triggers, see e.g.
```
[3721435:hf-filter]: [19:35:58][INFO] ACCEPTED pT = 0.8474335, NSIGMATPC 1203.5966 (cut -3), NSIGMAITS -3.3222082 (cut -4), NSIGMATOF -999 (cut -3)
[3721435:hf-filter]: [19:33:58][INFO] ACCEPTED pT = 0.99228996, NSIGMATPC 147.07945 (cut -3), NSIGMAITS -2.176171 (cut -4), NSIGMATOF -999 (cut -3)
[3721435:hf-filter]: [19:33:58][INFO] ACCEPTED pT = 0.81965065, NSIGMATPC 319.33163 (cut -3), NSIGMAITS -3.2618442 (cut -4), NSIGMATOF -999 (cut -3)
[3721435:hf-filter]: [19:33:58][INFO] ACCEPTED pT = 0.81965065, NSIGMATPC 319.33163 (cut -3), NSIGMAITS -3.2618442 …
```
=> [PWGHF,Trigger] Revert to symmetric NsigmaDe cut for charm femto trigger

PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: fix collision selection in skimmerPrimaryMuon.cxx
=> [PWGEM/Dilepton] fix collision selection in skimmerPrimaryMuon.cxx

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/MCSignalLibrary.cxx
1. remove the kPhyiscalPrimay restriction for muon from various sources in MCSignals
2. add two cuts for mouns: muonQualityCuts + type0/3 selection
3. modified a tempory histogram subgroup
=> [PWGDQ] remove the kPhyiscalPrimay restriction for muon from various sources in MCSignals

DPG/Tasks/AOTTrack/qaEventTrack.cxx
- `Shifting 32-bit value by 63 bits is undefined behaviour [shiftTooManyBits]`
=> [DPG] Fix bug found by cppcheck

PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackD0.cxx
Prerequisite for:
- https://github.com/AliceO2Group/O2Physics/pull/11357
=> [PWGCF] Include What You Use

EventFiltering/PWGHF/HFFilter.cxx, EventFiltering/PWGHF/HFFilterCharmHadronSignals.cxx, EventFiltering/PWGHF/HFFilterHelpers.h, EventFiltering/PWGHF/HFFilterPrepareMLSamples.cxx
Prerequisite for:
- https://github.com/AliceO2Group/O2Physics/pull/11357
=> [PWGHF,Trigger] Include What You Use

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/associateMCinfoDilepton.cxx
PWGEM/Dilepton: update associateMCinfoDilepton.cxx
=> [PWGEM/Dilepton] update associateMCinfoDilepton.cxx

PWGCF/GenericFramework/Tasks/flowGenericFramework.cxx
- add b axis for OTF
- add configurables for more track cuts
=> [PWGCF] add configurable mult cut

Scripts/o2_linter.py
Improve search patterns, mostly using regular expressions:
- `magic-number`
- `name/constexpr-constant`
- `name/enum`
- `name/class`
- `name/struct`
- `name/configurable`
=> O2 linter: Improve search patterns

PWGJE/TableProducer/emcalCorrectionTask.cxx
Used clang-tidy to:
- Remove headers that where not needed
- Add headers that were needed and missing
=> [PWGJE,EMCAL-1154] emcalCorrectionTask: fix include headers

PWGUD/Tasks/exclusiveRhoTo4Pi.cxx
Put the condition such that only the events in which  at least one track has TOF
=> [PWGUD] Updated the Event Selection

PWGDQ/Core/CutsLibrary.cxx, PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx
1. add a new set of electron cuts for e-mu
2. remove the out of date electron cuts for the filter test (previous added by me)
3. fix the muon histogram filling bug (reset the iterator)
=> [PWGDQ] add new set of electron cuts for e-mu and fix the tableMaker_withAssociation

PWGHF/D2H/DataModel/ReducedDataModel.h, PWGHF/D2H/TableProducer/dataCreatorCharmResoReduced.cxx
This PR refactors the dataCreatorCharmResoReduced workflow adding the following features:
- posisbility to create resonances that decay into a D0 + track or V0
- possibility to create simultaneously resonances with a V0 or a track in their final state to produce derived data to be stored on grid
- minor: added generated invariant mass to MC reco table for resolution determination
A refactor of MC matching functions will follow soon after the merge of PRs #11382 and #11418
=> [PWGHF] Refactor of charm resonances derived data creator

Common/Tasks/CMakeLists.txt, Common/Tasks/qaMuon.cxx
Adding muon QA task for tracks in MCH-MID and MFT-MCH-MID. Can be used for MCH and MFT-MCH relative alignment studies.
=> [Common] Adding muonQA task

ALICE3/Core/DelphesO2LutWriter.cxx, ALICE3/Core/DelphesO2LutWriter.h, ALICE3/Core/DetLayer.cxx, ALICE3/Core/DetLayer.h, ALICE3/Core/FastTracker.cxx, ALICE3/Core/FastTracker.h, ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
=> [ALICE3] A3: update protection of DetLayer

PWGLF/TableProducer/Common/kinkBuilder.cxx, PWGLF/Utils/svPoolCreator.h
The changes in this commit update the usage of the aod::BCsWithTimestamps data
source to the more generic aod::BCs data source. This simplifies the code and
removes the need for the specific BCsWithTimestamps data source, which is no
longer required. The changes ensure that the kinkBuilder functionality
continues to work with the updated data source.
=> [PWGLF] feat(kinkBuilder): use aod::BCs instead of aod::BCsWithTimestamps

PWGDQ/Tasks/tableReader_withAssoc.cxx
At the moment, the AnalysisDileptonTrack fails for muon tracks, due to the geometry not being loaded. This PR adds a check for the geometry similar to the ones in AnalysisMuonSelection and AnalysisSameEventPairing tasks, along with the required configurables. 
A from hyperloop of the error produces is here: [stdout.log](https://github.com/user-attachments/files/20611510/stdout.log)
=> [PWGDQ] Add loading of geometry to dilepton-track task

DPG/Tasks/ITS/CMakeLists.txt, DPG/Tasks/ITS/itsImpParStudies.cxx
Dear all,
I have added a task related to impact parameter studies to the ITS Working Group.
Let me know for any comments,
Cheers,
Samuele
=> [DPG] Adding ITS task for impact parameter studies

PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx
=> [PWGLF] PWGLF Change in hStrangeCorrelation.cxx

PWGCF/Femto/TableProducer/PiDeuteronFemto.cxx
add function of computing kstar and switch of fill table
=> [PWGCF] Update PiDeuteronFemto.cxx

ALICE3/TableProducer/alice3-decayfinder.cxx
As from the title of the PR, this allows to evaluate the D0 meson efficiency by counting at gen level only D0 mesons with the proper decay in Kpi
=> [ALICE3] Adding decay channel check for D efficiency evaluation in decay finder

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackCascadeExtended.cxx
Adding an option to use centrality for MC cascades to the Producer task and Cascade task. Adding a PDG histogram without a PDG cut to EfficiencyBase task.
=> [PWGCF] FemtoUniverse - Adding centrality for MC cascades and a PDG histogram

PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/DimuonCut.cxx, PWGEM/Dilepton/Core/DimuonCut.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx, PWGEM/Dilepton/Tasks/createResolutionMap.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h
PWGEM/Dilepton: update dimuon analyses
=> [PWGEM/Dilepton] update dimuon analyses

PWGHF/Core/HfMlResponseLcToPKPi.h, PWGHF/TableProducer/candidateSelectorLc.cxx, PWGHF/TableProducer/treeCreatorLcToPKPi.cxx
1. Kalman Filter specific variables are added to the list of available features for ML selection of `Lc->PKPi` decays.
2. ML scores are propagated to the output of the `treeCreatorLcToPKPi` workflow.
=> [PWGHF] Enable ML selection in KF-based LcToPKPi reconstruction

PWGHF/D2H/Tasks/taskFlowCharmHadrons.cxx
This PR introduces the flow analysis task for the decay channel Xic⁰ → Ξ⁻ π⁺ in taskFlowCharmHadrons.cxx, and fixes previously existing O2 linter issues as follows:
1. Replaced  2. * TMath::Pi() with the constant o2::constants::math::TwoPI.
2. Used RecoDecay::constrainAngle to normalize angles within the proper range.
3. Reorganized struct members in HfTaskFlowCharmHadrons to follow pwghf/struct-member-order: 
Moved HfHelper and SliceCache before using declarations and 
Placed ConfigurableAxis after Partition.
5. Renamed variables (axes_reso → axesReso) to follow lowerCamelCase convention.
=> [PWGHF] Add Xic0 flow task and fix previous O2 linter issues

EventFiltering/PWGCF/CFFilterAll.cxx
Fix the order of enums. The number of triggered Evens for the PhiD and RhoD had been switched.
=> [Trigger,PWGCF] Fix order of enums

Common/Tasks/qaMuon.cxx
Bug Fix: For global muons one needs to look at the clusters associated to the MCH track
=> [Common] Use MCH track counterpart of global muon

Common/DataModel/Multiplicity.h
to avoid HY unbound indices complaint (actual index value was fine)
=> [Common] Change index column identifier

.clang-tidy
Adds configuration of O2 naming conventions for the clang-tidy check
[readability-identifier-naming](https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html).
=> [Infrastructure] Configure naming conventions in clang-tidy

PWGJE/Core/JetBkgSubUtils.cxx, PWGJE/Core/JetBkgSubUtils.h
=> [PWGJE] Fix: make doRhoAreaSub take jet by const reference

dependencies/FindKFParticle.cmake
Attempt at getting rid of the spurious error about KFParticle.
Requires https://github.com/alisw/KFParticle/pull/7
=> [Infrastructure] Support non-flat KFParticle headers distribution

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
Updating the THnSparse of SingleTrackQC tasks
=> [PWGEM] SingleTrackQC update to THnSparse Data and MC

PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
This PR contains 2 commits.
PWGEM/Dilepton: fix chi2 in global muon
PWGEM/Dilepton: fix dca bins
=> [PWGEM/Dilepton] fix chi2 in global muon

PWGLF/Tasks/Resonances/higherMassResonances.cxx
added polar angle in helicity frame in MC
=> [PWGLF] added polar angle in helicity frame in MC

PWGEM/PhotonMeson/TableProducer/bcWiseClusterSkimmer.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/emcalBcWiseGammaGamma.cxx, PWGJE/Tasks/emcEventSelectionQA.cxx
EM:
- Move from collision wise to BC wise centrality in gammagamma task
- Rename pi0task to gammagamma task to allow for addition of eta (in a later PR)
JE:
- Add DMC7 as DCal L0 trigger to list of emcal readout triggers (Bugfix)
=> [PWGEM/PhotonMeson,PWGJE/EMCal] Include BCWise centrality and qa histograms

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Utils/MlResponseDielectronSingleTrack.h, PWGEM/Dilepton/Utils/MlResponseO2Track.h
=> [PWGEM/Dilepton] upadte PID ML

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
The O2 PR https://github.com/AliceO2Group/AliceO2/pull/14421 adds sanity check for the table filling cursor and it fails in `PWGDQ/Tasks/dqEfficiency_withAssoc.cxx`:2080 - the filling call has 8 arguments while the table has 9 columns. From the context I assume that the centrality value was missing. Could you please verify that this is a correct fix? Thank you.
=> [PWGDQ] Fix for invalid cursor call with 8 arguments instead of 9

PWGHF/D2H/DataModel/ReducedDataModel.h, PWGHF/D2H/TableProducer/candidateCreatorBToJpsiReduced.cxx, PWGHF/D2H/Tasks/taskBplusToJpsiKReduced.cxx, PWGHF/D2H/Tasks/taskBsToJpsiPhiReduced.cxx
When the B+ workflow is run alone, `Spawns<aod::HfRedBach1Ext> rowTracksExt1;` would cause the workflow to crash (as the B+ decays in J/Psi K and the table for the second LF track is not produced).
This solves the issue as we now use a dynamic column and there is no need to extend the table anymore
=> [PWGHF] Remove need for extended pt column in B -> J/Psi workflow

PWGHF/Utils/utilsMcGen.h, PWGHF/Utils/utilsMcMatching.h
In this PR, two issues introduced in PR #11418 are fixed:
- Wrong PDG codes in `utilsMcMatching.h`
- Restore new flags for D+ and Ds in `utilsMcGen.h`
=> [PWGHF] Fix issues in correlated bkg matching

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/Tasks/prefilterDielectron.cxx, PWGEM/Dilepton/Tasks/vpPairQC.cxx, PWGEM/Dilepton/Tasks/vpPairQCMC.cxx, PWGEM/Dilepton/Utils/EventHistograms.h, PWGEM/Dilepton/Utils/MCUtilities.h, PWGEM/PhotonMeson/Core/DalitzEECut.cxx, PWGEM/PhotonMeson/Core/DalitzEECut.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx, PWGEM/PhotonMeson/Utils/EventHistograms.h, PWGEM/PhotonMeson/Utils/MCUtilities.h, PWGEM/PhotonMeson/Utils/NMHistograms.h
PWGEM/Dilepton: update for ITSsa and include headers
=> [PWGEM/Dilepton] update for ITSsa and include headers

PWGLF/DataModel/Reduced3BodyTables.h, PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx, PWGLF/TableProducer/Nuspex/hyperhelium4sigmaRecoTask.cxx, PWGLF/TableProducer/Nuspex/reduced3bodyCreator.cxx, PWGLF/Utils/decay3bodyBuilderHelper.h
1. Enable event selection based on trigger in decay3bodybuilder
2. Add like-sign analysis
3. Fix bugs and a few o2_linter warnings
=> [PWGLF] Enable event selection based on trigger and add like-sign analysis

PWGDQ/Core/HistogramsLibrary.cxx
I am facing warning in wagon due to large memory consumption. So, I have deleted the histogram for rapidity differential study
=> [PWGDQ] Optimize the histograms to avoid memory issue

DPG/Tasks/AOTTrack/D0CalibTables.h, DPG/Tasks/AOTTrack/derivedDataCreatorD0Calibration.cxx
Dear  @mfaggin, 
The PR is ready for review, Kindly please review and accept it.
@fgrosa, @miranov25 and I are working on this task.
Best Regards,
Rahul
=> [DPG] Added TrackMeanOccupancy variable in the D0 daughter candidates

PWGHF/TableProducer/candidateCreator2Prong.cxx
To possibly include J/Psi candidates
=> [PWGHF] Make mass axis configurable in candidateCreator2Prong

PWGCF/FemtoUniverse/Core/FemtoUniverseContainer.h, PWGCF/FemtoUniverse/Core/FemtoUniverseEfficiencyCorrection.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Extended.cxx
`femtoUniversePairTaskTrackV0Extended.cxx` - add efficiency calculation with EfficiencyCorrection class to V0 task.
`FemtoUniverseContainer.h` - small include changes.
`FemtoUniverseEfficiencyCorrection.h` - changes by @davkk to make the class compatible with non-basic FdCollision types.
=> [PWGCF] FemtoUniverse: Add efficiency calculation with EfficiencyCorrection class to V0 task

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
Some MCsignals (e.g. non-prompt J/psi) crash without this fix, due to problem with binding of internal indices.
=> [PWGDQ] Fix for event-selected MCsignal in processMCGen

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: change from max pin to max p
=> [PWGEM/Dilepton] change from max pin to max p

PWGCF/FemtoDream/Tasks/CMakeLists.txt, PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx, PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackTrackPbPb.cxx
Summer student project on PbPb three-body femtoscopy.
=> [PWGCF] Fix naming and other bugs in producer task for Pb-Pb collisions

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/DataModel/lmeeMLTables.h, PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/filterEoI.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryTrack.cxx, PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: add a task to produce derived data for primary track
=> [PWGEM/Dilepton] add a task to produce derived data for primary track

PWGEM/Dilepton/Core/DileptonMC.h
Implement pt_gen - pt_rec vs DCA histogram
Study the DCA shape of prompt and non-prompt sources which experience Bremsstrahlung.
=> [PWGEM] Implement histogram for momentum loss vs DCA, intention to select track w/wo Bremsstrahlung

PWGJE/Tasks/gammaJetTreeProducer.cxx
- fix for getDaughtersInChain to recursively go through all branches of the decay chain
=> [PWGJE] fixed getDaughtersInChain function for GammaJetTrees

PWGLF/Tasks/QC/CMakeLists.txt, PWGLF/Tasks/QC/trackedCascadeProperties.cxx
- Introduced histograms that are filled using the cluster size truncated mean
- Added option to run on skimmed datasets via config flag
=> [PWGLF] add truncated mean histograms and configurable to run on skimmed data

PWGDQ/Core/MCSignalLibrary.cxx
Adding MC signals for mumuFromPromptJpsi, mumuFromPromptPsi2S, mumuFomNonPromptJpsi, mumuFromNonPromptPsi2S based on dielectron MC signals; fixing promptPsi2S MC signal based on promptJpsi MC signal
=> [PWGDQ] Adding & fixing MC signals

PWGDQ/Tasks/tableReader.cxx
Temporary removal of a part of the code that could be problematic in the current issue to run over derivd data on hyperloop. The removed part will be restored after the test
=> [PWGDQ] Temporary test for issues in running in hyperloop

PWGHF/TableProducer/candidateCreatorSigmac0plusplus.cxx
@Mingyu3360715 this PR should solve the issue we observe for the MC matching.
PS: we need to wait the PR https://github.com/AliceO2Group/O2Physics/pull/11854 before merging the current one, convert to draft
=> [PWGHF] Σc0,++: Remove duplicated consuming of McParticles.

Common/Tasks/centralityStudy.cxx
- Add histograms for FIT signals vs time after start of run
=> [Common] Add time dependency study to centrality task

PWGJE/TableProducer/emcalCorrectionTask.cxx
- Add the option to use the old Run2 alignment which should be fine for EMCal, but might differ for DCal. This is a pure expert option, if you do not know what it does, do not use it.
- Remove old debug loops we no longer need and had marked for removal with TODO before
=> [PWGJE,EMCAL-670] Add option to use Run2 alignment

Common/Tasks/qaMuon.cxx
Two changes:
- Small bugfix changing the definitions of left-right to quadrants 0 and 3 and 1 and 4, respectively.
- Distinguished the top-bottom and bottom-top origin studies for dimuons from the MCH chamber 1 to explicitly say which of the two muons came from where. The same is done for left-right and right-left.
=> [Common] Added further distinction of muon origins in MCH

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx
PWGEM/Dilepton: add possibility to store only true electron in MC
=> [PWGEM/Dilepton] add possibility to store only true electron in MC

PWGJE/Tasks/jetSpectraCharged.cxx, PWGJE/Tasks/trackEfficiency.cxx
1. Add occupancy cut to trackEfficiency.cxx for general purpose Pb-Pb MC 
2. Fix some cuts in weighted process functions
=> [PWGJE] Add occupancy cut to trackEfficiency task

Common/Tasks/CMakeLists.txt, Common/Tasks/centralityStudy.cxx
This pr adds profiles vs time for:
- PVz (from collisions)
- PVz (from BCs)
- IR
@ddobrigk
=> [Common] Add PVz and IR profiles vs time to centrality task

PWGCF/FemtoUniverse/Core/FemtoUniverseEfficiencyCorrection.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackPhi.cxx
Added as in [this PR](https://github.com/AliceO2Group/O2Physics/pull/11270). Thanks @davkk! :)
=> [PWGCF] FemtoUniverse -- Adding correction on secondary contaminations for the p-phi analysis

PWGHF/D2H/Tasks/taskCharmPolarisation.cxx
Incorrect use of iterator, lead to error when slice on candidates.
=> [PWGHF] taskCharmPolarisation: Stop using the iterator at collisions for PbPb collision process

PWGLF/Tasks/Resonances/kstarqa.cxx
Added configurable for centrality/multiplicity estimating using different detectors.
=> [PWGLF] Configurable for centrality estimation

PWGHF/D2H/Macros/compute_fraction_cutvar.py, PWGHF/D2H/Macros/cut_variation.py
* implemented a possibility to run cut variation script with a single pT bin using following (optional) field in json config: `"pt_bin_to_process": 1`. If this field is missing, all pT bins will be analyzed by default;
* added warnings if cut sets are correlated and at least one of the following sequences is not monotonous: raw yield, raw yield uncertainty, residual vector uncertainty (i.e. diagonal elements of covariance matrix);
* added a plot with raw yield uncertainty and residual vector uncertainty as a function of the cut set for better visual perception of problematic cut sets
=> [PWGHF] Cut variation: make analysis more flexible and output more informative

PWGHF/Core/SelectorCuts.h, PWGHF/TableProducer/candidateCreatorXicToXiPiPi.cxx, PWGHF/TableProducer/candidateSelectorXicToXiPiPi.cxx
@JaeYoonCHO @sh-lim @klsmith15k
- Add $\Sigma p_{\rm{T}}(\pi\leftarrow\Xi_{c}^{+})$ cut
- Add QA histograms for daughter track properties to candidate selector: $\eta$, TPC clusters and crossed rows of all final state daughter particles; ITS clusters of $\pi$ from $\Xi_{c}^{+}$
- Improve counter histogram filling conditions
- Fill counter histograms in candidate creator and selector by default, and make filling of other histograms configurable
=> [PWGHF] Add QA histograms to XicToXiPiPi candidate selector

PWGLF/Tasks/Resonances/higherMassResonances.cxx, PWGLF/Tasks/Resonances/phianalysisrun3_PbPb.cxx
1. Added centrality estimator in the Phi code
2. Modification in the MC part in K0s K0s code
=> [PWGLF] Optimised both codes

PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/qVectorDummyOTF.cxx
PWGEM/Dilepton: add a task to produce OTF qVector
=> [PWGEM/Dilepton] add a task to produce OTF qVector

PWGCF/FemtoUniverse/Tasks/femtoUniverseEfficiencyBase.cxx
Changes:
- two new configurable -> possibility to enable and disable the QA plots for MCGen and MCReco for tracks
- moving histogram filling in processTrackTrack before the verification of the particle origin and PDG
- fixing headers' order
=> [PWGCF] FemtoUniverse: EfficiencyBase task update

EventFiltering/Zorro.cxx, EventFiltering/Zorro.h, EventFiltering/ZorroHelper.h, EventFiltering/ZorroSummary.cxx, EventFiltering/ZorroSummary.h
- Member variable ... is not initialized in the constructor. (cppcheck)
- Function parameter ... should be passed by const reference. (cppcheck)
- Searching before insertion is not necessary. Use `try_emplace` instead. (cppcheck)
- Use `static_cast` instead of deprecated casting style. (cpplint)
- IWYU (clang-tidy)
- Include external headers with `<>`. (manual)
- Sort includes. (clang-format)
- Replace `size_t` with `std::size_t`.
- Use `const&` to iterate `std::vector<ZorroHelper>`. (O2 linter)
=> [Trigger] Zorro: Fix various C++ issues

PWGLF/TableProducer/Strangeness/sigma0builder.cxx, PWGLF/Tasks/Strangeness/phik0shortanalysis.cxx
This PR updates the sigma0builder task to adopt a custom v0 grouping strategy - which involves the use of a simple vector-of-vectors. Other small changes were made to improve performance.
=> [PWGLF] Custom v0 grouping in sigma0builder

Tools/PIDML/pidMl.h, Tools/PIDML/pidMlBatchEffAndPurProducer.cxx, Tools/PIDML/pidMlEffAndPurProducer.cxx, Tools/PIDML/pidMlProducer.cxx, Tools/PIDML/pidOnnxInterface.h, Tools/PIDML/pidOnnxModel.h, Tools/PIDML/qaPid.cxx, Tools/PIDML/qaPidMl.cxx, Tools/PIDML/simpleApplyPidOnnxInterface.cxx, Tools/PIDML/simpleApplyPidOnnxModel.cxx
- Fix bugs:
- Parameter ... can be declared as (reference to) const. (cppcheck)
- Member variable ... is not initialized in the constructor. (cppcheck)
- `PidONNXModel::mPid`
- `PidONNXModel::mMinCertainty`
- `PidONNXInterface::mNPids`
- Expression is always true because 'else if' condition is opposite to previous condition. (cppcheck)
- Fix includes:
- IWYU (clang-tidy)
- Include external headers with `<>`. (manual)
- Sort includes. (clang-format)
=> [Tools] Fix C++ issues

ALICE3/TableProducer/alice3-decaypreselector.cxx
Allows to consider tracks for the RICH selection only if they are above threshold for the Cherenkov radiation emission, and a minimum number of photons is acquired. Otherwise, the RICH selection is not processed (fixes the previous behaviour where the track was automatically rejected)
=> [ALICE3] Implementing new ALICE 3 RICH flags in analysis preselection task

PWGCF/Femto3D/Tasks/CMakeLists.txt, PWGCF/Femto3D/Tasks/PIDoptimization.cxx
new task for PID Optimization in femto analyses
=> [PWGCF] [Femto3D] adding a new task for PID Optimization

PWGCF/Flow/Tasks/flowGfwOmegaXi.cxx
add cascades v24 with eta gap
add competing inv. mass rejection for cascades
=> [PWGCF] Add cascades v24 with eta gap

PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx
- Add `needEMCTrigger` configurable option. If one uses this one for the EM Event Selection, one also needs to enable this here to ensure the table sizes of `EMCEMEventId` and `SkimEMCClusters` have the same size.
- Header cleanup with `clang-tidy`
- Incorporate changes coming from O2-Linter
=> [PWGEM,PWGEM-36] skimmerGammaCalo: Add `needEMCTrigger` configurable

Common/DataModel/PIDResponseITS.h
Pinging @giovannimalfattore (thanks for spotting the issue)
=> [Common] Fix Z=2 PID response for dynamic columns

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/filterEoI.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: remove unnecessary Preslice
PWGEM/Dilepton: reduce function arguments
=> [PWGEM/Dilepton] remove unnecessary Preslice

Common/Core/TableHelper.h
Reverts AliceO2Group/O2Physics#11898
=> [Common] Revert "[Common] Improve verbose message in TableHelper"

PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx
PWGEM/Dilepton: keep backward compatibility for qvec
=> [PWGEM/Dilepton] keep backward compatibility for qvec

PWGEM/Dilepton/Core/DimuonCut.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: reduce number of calling propagateMuon
=> [PWGEM/Dilepton] reduce number of calling propagateMuon

PWGEM/PhotonMeson/Tasks/dalitzEEQC.cxx, PWGEM/PhotonMeson/Tasks/dalitzEEQCMC.cxx
PWGEM/PhotonMeson: remove dependency
=> [PWGEM/PhotonMeson] remove dependency

Common/TableProducer/multCentTable.cxx, Common/Tools/MultModule.h
=> [Common] Adjust PYTHIA autodetect for Pb-Pb

PWGLF/TableProducer/Nuspex/he3LambdaAnalysis.cxx
Adds new configurable parameters for the He3 Lambda analysis:
- `etaMax`: Maximum He3 pseudorapidity
- `minTPCrigidity`: Minimum He3 rigidity
These parameters are used to further refine the He3 selection criteria
in the analysis.
=> [PWGLF] New selections on eta and rigidity

PWGEM/Dilepton/Core/CMakeLists.txt, PWGEM/Dilepton/Core/DileptonHadron.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/EMTrackCut.cxx, PWGEM/Dilepton/Core/EMTrackCut.h, PWGEM/Dilepton/Core/PWGEMDileptonCoreLinkDef.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/eventSelection.cxx, PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx, PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/dielectronHadron2PC.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/Dilepton/Tasks/matchingMFT.cxx, PWGEM/Dilepton/Utils/PairUtilities.h
PWGEM/Dilepton: add a task for dilepton-hadron 2PC
=> [PWGEM/Dilepton] add a task for dilepton-hadron 2PC

PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/DataModel/dileptonTables.h
PWGEM/Dilepton: fix for dimuon analyses
=> [PWGEM/Dilepton] fix for dimuon analyses

PWGHF/Core/HfMlResponseDstarToD0Pi.h, PWGHF/TableProducer/candidateSelectorDstarToD0Pi.cxx
This PR introduces the possibility of applying ML selection on the D0 daughter of a D* candidate, in order to allow a correct efficiency evaluation in triggered data.
=> [PWGHF] ML selections for D0 in D* selector

PWGDQ/Core/HistogramsLibrary.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Tasks/dqEfficiency_withAssoc.cxx, PWGDQ/Tasks/tableReader.cxx
warning: previously the order of the muon vars in the miniTree was defined in the varManager, now it is moved at the time of the filling of the trees
=> [PWGDQ] Adding histograms for tag and probe

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx
PWGEM/PhotonMeson: add an option to require ITS hit to V0 legs
PWGEM/Dilepton: update treeCreatorElectronMLDDA.cxx
=> [PWGEM/PhotonMeson] add an option to require ITS hit to V0 legs

ALICE3/Tasks/alice3-multicharm.cxx
Fix bug that causes a crash when a unexpected pdg code is found
=> [ALICE3] Fix to mcharm pid histograms

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
Currently, photon-like candidates (V0 type != 1) are correctly skipped from final analysis table population if the configuration is such that they are not of interest, but they could be skipped in a more optimized manner (earlier in the processing chain) as done with this PR to save CPU. Note: V0 data link is still generated for V0s skipped due to this change, which is a necessity to keep that link joinable with `aod::V0s`.
=> [PWGLF] Optimization: skip V0s not satisfying configuration earlier

PWGEM/Dilepton/Core/DileptonHadronMPC.h, PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/dielectronHadronMPC.cxx, PWGEM/Dilepton/Tasks/dimuonHadronMPC.cxx, PWGEM/PhotonMeson/Core/DiphotonHadronMPC.h, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/diphotonHadronMPCPCMDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/diphotonHadronMPCPCMPCM.cxx
PWGEM/Dilepton: fix header file names
=> [PWGEM/Dilepton] fix header file names

PWGLF/TableProducer/Common/epvector.cxx, PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/strangenessderivedbinnedinfo.cxx
Add task running over strangeness derived data and producing binned information about V0s/cascades 
@miranov25 for your information
=> [PWGLF] Add task to produce binned information about V0s/cascades

Common/DataModel/Multiplicity.h, Common/Tasks/centralityStudy.cxx
This PR includes the following changes 
-  Addition of `MultsRun3` which no longer joins the Run 3 multiplicity tables with the Run 2 `TrackletMults` and changing subscription in the process functions accordingly.
- Created `initRun` which creates the essential histograms dynamically for each Run. Each Run adds ~80 MB of memory needed by the histogram registry which initially needs ~50MB.
- Flag for ir fetcher which sometimes causes crashes in light ion runs.
- Add subscription and histograms for FV0AOuter in process functions calling `genericProcessCollision()`.
- Added 3d histogram FV0A vs FV0AOuter vs time which needs to be enabled with flag `doTimeStudyFV0AOuterVsFT0A3d` (not created per Run).
=> [Common] Update centrality task with run dependant histograms

Common/TableProducer/eventSelection.cxx, PWGLF/Tasks/Resonances/chk892pp.cxx
For the analysis code 'chk892pp.cxx',
- Rotational background is added to describe the combinatorial background
- Configurables for secondary selections (Lambda mass hypothesis cut, maximum radius)
- Grouping configurables depending on the selections
- Fixed some of o2linter issues
=> [PWGLF] Add rotational bkg and configurables for secondary selections for 'chk892pp.cxx'

PWGLF/DataModel/Vtx3BodyTables.h, PWGLF/TableProducer/Nuspex/decay3bodybuilder.cxx
=> [PWGLF] Fix MC info resetting in decay3bodybuilder

PWGCF/Tasks/correlations.cxx
This PR adds the possibility to select the rapidity range of V0s in the correlation function
=> [PWGCF] Adding selection on V0 rapidity in cf correlation

ALICE3/DataModel/OTFMulticharm.h, ALICE3/TableProducer/alice3-multicharmTable.cxx, ALICE3/Tasks/CMakeLists.txt, ALICE3/Tasks/alice3-multicharm.cxx
Minor changes to the multi-charm data model and added bdt use to the task
=> [ALICE3] Add use of BDT to otf multi-charm

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx
This PR includes the initialization of the ccdbApi object in the strangenessbuilder to load BDT models from the CCDB. 
Tagging @romainschotter @ddobrigk
=> [PWGLF] Fix initialization of ccdbApi in strangenessbuilder

PWGEM/Dilepton/Tasks/eventQC.cxx
PWGEM/Dilepton: remove unused parameters
=> [PWGEM/Dilepton] remove unused parameters

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/prefilterDielectron.cxx
PWGEM/Dilepton: add dphiPosition
=> [PWGEM/Dilepton] add dphiPosition

PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h, PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- added bitmask to store NSigma values to be used v0 and cascade analysis
- this is to optimize the v0-cascade derived table output by removing the dependency on debug table
=> [PWGCF] FemtoUniverse v0cascade task -- PID bitmask for v0 and cascade analysis

PWGEM/Dilepton/TableProducer/filterEoI.cxx
PWGEM/Dilepton: update filterEoI.cxx
=> [PWGEM/Dilepton] update filterEoI.cxx

PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx
PWGEM/Dilepton: support new data of global muons
=> [PWGEM/Dilepton] support new data of global muons

Common/TableProducer/trackPropagationTester.cxx, Common/Tools/StandardCCDBLoader.h, Common/Tools/TrackPropagationModule.h, PWGLF/TableProducer/Strangeness/propagationService.cxx
Since the tracktuner class derives from ConfigurableGroups, it has to be put in the analysis task itself for the relevant configurables to be exposed directly to the user of a joint service such as propagationService.
=> [Common,PWGLF] Expose configurables inside TrackTuner in propagationService

PWGEM/Dilepton/Core/DileptonMC.h
Adding TH2 to DielectronMC task for promptPi0 and PromptJPsi, to check DCA1 vas DCA2 of tracks
=> [PWGEM] Add DCA1 vs DCA2 hist to DielectronMC task

PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx, PWGLF/Utils/strangenessBuilderModule.h
-  Fix V0DataLink filling, creating discrepancies between the V0 and the V0DataLink table sizes (@ChiaraDeMartin95 @ercolessi for your information)
-  Replace return calls by continue calls when moving TPC only tracks
@ddobrigk @gianniliveraro for your information
=> [PWGLF]  Fix V0DataLink filling + return calls when moving TPC only tracks

PWGJE/Tasks/nucleiInJets.cxx
This PR just fixed the 3D histogram filling. Please approve the PR once tests are done.
Have a nice day.
=> [PWGJE] Fixed 3D histogram filling

PWGEM/Dilepton/Tasks/smearing.cxx, PWGEM/Dilepton/Utils/MomentumSmearer.h
PWGEM/Dilepton: add muons in struct CheckSmearing
=> [PWGEM/Dilepton] add muons in struct CheckSmearing

Common/Tools/MultModule.h
=> [Common] Improve printouts for easier debugging

PWGJE/Tasks/nucleiInJets.cxx
I have removed TMath dependency and tried to solve some of the issues related to the O2 linter in this PR (Thanks to @vkucera for suggestions). Please approve the PR once tests are passed.
Have a nice afternoon.
=> [PWGJE] Replace TMath methods with O2 ones

PWGDQ/Tasks/dqEfficiency.cxx
This PR fixes the same issue as #11478 but for the efficiency task.
A check is added for the geometry similar to the one in AnalysisSameEventPairing tasks, along with the required configurables.
=> [PWGDQ] Add geometry loading to dilepton-track task

Scripts/o2_linter.py
Relax the expected pattern to just require at least 3 characters.
=> O2 linter: Accept (almost) any exception reason

PWGEM/Dilepton/Core/EMTrackCut.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryTrack.cxx, PWGEM/Dilepton/Utils/EMTrackUtilities.h, PWGJE/Tasks/nucleiInJets.cxx
=> [PWGEM/Dilepton] update 2PC

EventFiltering/PWGEM/EMPhotonFilter.cxx
EventFiltering/PWGEM: fix std
reported in https://github.com/AliceO2Group/O2Physics/pull/12363
=> [Trigger,PWGEM] fix std

PWGLF/Utils/strangenessBuilderModule.h
@romainschotter I think we missed the incorporation of https://github.com/AliceO2Group/O2Physics/pull/12196 into the module when we merged the propagation service. This will save the same CPU as that PR (output unchanged).
=> [PWGLF] One more minor optimization change to str builder module

PWGCF/TwoParticleCorrelations/Tasks/longrangeCorrelation.cxx
1) Fix the initialisation of `fv0det` geometry pointer  
2) Add `addHistos` function instead of using `addClone`
=> [PWGCF] Fix bug in FV0 eta calculation

PWGDQ/Core/CMakeLists.txt, PWGDQ/Core/CutsLibrary.cxx, PWGDQ/Core/CutsLibrary.h, PWGDQ/Core/DQMlResponse.h, PWGDQ/Core/VarManager.cxx, PWGDQ/Core/VarManager.h, PWGDQ/Macros/bdtCut.json, PWGDQ/Macros/bdtCutMulti.json, PWGDQ/Tasks/CMakeLists.txt, PWGDQ/Tasks/tableReader.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx
Implement ML-based response class (DQMlResponse) for dielectron DQ-analysis selections
Supports both binary and multiclass BDT evaluation using ONNX
Example JSON files included for reference
=> [PWGDQ] ML response for DQ-analysis selections

PWGHF/DataModel/CandidateReconstructionTables.h, PWGLF/DataModel/LFStrangenessTables.h
Adds a safety feature in the strangenenss/V0 data model in which the `V0Type` is checked before returning a K0, Lambda or AntiLambda mass. This extra safety feature covers the (unusual) case in which the strangeness builder is used with photon creation enabled (in any of the de-duplication modes) and avoids spurious (potentially duplicate) candidates being used without explicit intention. `m[Species]_unchecked` getters are provided in case the mass calculation is to be used without checking v0 type, and a comment in the data model explains the rationale. 
This PR touches HF slightly as well: there, the `mK0Short`, `mLambda` and `mAntiLambda` getters were used from the `v0data` namespace, which needed to be adjusted. This because the revised getters take `v0data::v0type` as argument - but …
=> [PWGLF,PWGHF] Add photon safety layer to strangeness getters

ALICE3/TableProducer/alice3-multicharmTable.cxx, ALICE3/Tasks/alice3-multicharm.cxx
- Fix axis for bdt score vs pt and add an additional qa plot
- Add mass cut when creating of tree of xicc candidates
=> [ALICE3] Add more qa of ml use to otf multi-charm task

PWGMM/Mult/Tasks/dndetaMFTPbPb.cxx
1. Major: Added QA histograms for track selections
2. Minor: Change of vertex selection instead of taking the absolute value
=> [PWGLF] Added QA histos for track selection

PWGHF/HFC/TableProducer/correlatorHfeHadrons.cxx, PWGHF/HFL/TableProducer/electronSelectionWithTpcEmcal.cxx
Use DeltaEta and DeltaPhi from EMCalMatchedTracks Table for Track-Cluster Matching
=> [PWGHF] Used DeltaEta and DeltaPhi from EMCalMatchedTracks Table for Track-Cluster Matching

Common/CCDB/ctpRateFetcher.cxx, Common/TableProducer/eventSelection.cxx, Common/TableProducer/qVectorsTable.cxx, Common/Tools/PID/handleParamTPCResponse.cxx, DPG/Tasks/AOTEvent/detectorOccupancyQa.cxx, EventFiltering/PWGCF/CFFilterQA.cxx, EventFiltering/PWGLF/filterf1proton.cxx, PWGDQ/TableProducer/tableMaker.cxx, PWGDQ/TableProducer/tableMakerMC_withAssoc.cxx, PWGDQ/TableProducer/tableMaker_withAssoc.cxx, PWGDQ/Tasks/muonDCA.cxx, PWGDQ/Tasks/tableReader_withAssoc.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/Tasks/matchingMFT.cxx, PWGLF/TableProducer/Resonances/f1protonreducedtable.cxx, PWGLF/TableProducer/Resonances/filterf1proton.cxx, PWGLF/Tasks/Strangeness/hStrangeCorrelation.cxx, PWGUD/TableProducer/fwdTrackPropagation.cxx
The header TJAlienCredentials.h polluted the global namespace, included usually with CCDB or something related.
See AliceO2Group/AliceO2#14524 for more background.
This prepares for the removal of the polluted namespace.
=> [Common,PWGCF,PWGDQ,PWGEM,PWGLF,PWGUD,DPG,Trigger] [Cleanup] Add fully qualified names for std::string and std::map

PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/PhotonMeson/Core/CutsLibrary.cxx, PWGEM/PhotonMeson/Core/DiphotonHadronMPC.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/Core/TaggingPi0.h, PWGEM/PhotonMeson/Core/TaggingPi0MC.h, PWGEM/PhotonMeson/Core/V0PhotonCut.cxx, PWGEM/PhotonMeson/Core/V0PhotonCut.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaConversion.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/Converters/electronFromDalitzConverter1.cxx, PWGEM/PhotonMeson/Tasks/Converters/pcmConverter1.cxx, PWGEM/PhotonMeson/Tasks/pcmQC.cxx, PWGEM/PhotonMeson/Tasks/pcmQCMC.cxx, PWGEM/PhotonMeson/Tasks/prefilterPhoton.cxx
PWGEM/PhotonMeson: remove track::x,y,z from derived data
=> [PWGEM/PhotonMeson] remove track::x,y,z from derived data

PWGJE/Tasks/taskEmcExtensiveMcQa.cxx
- Add centrality as an extra axis, for pp this should be set to size 1 from -1.5 to -0.5, since the default value for cent is -1.f
- Add leading particle energy axis, its true generated momentum and the ratio between these two
- Add number of contributors to clusters as an extra axis
- Add a new histogram which stores the cluster energy vs the number of contributors vs the leading particle energy deposition vs the leading particle momentum vs the ratio of the last two vs cent
- Increased detail for PoI:
- Electrons are now seperated between priamry and secondary
- Add Muons
- Split Hadron in charged and neutral, where neutral means Neutron, K0L, K0S, Lambda0, Xi0 and Sigma0
=> [PWGJE] taskEmcExtensiveMcQa: Add more cluster energy informations

PWGEM/PhotonMeson/Tasks/compconvbuilder.cxx, PWGLF/Tasks/Strangeness/derivedlambdakzeroanalysis.cxx
- when applying TOF PID selections, only consider it if the track has a hit in the TOF
- add almost all centrality estimators in the strangeness derived data model
=> [PWGLF] Apply TOF only if available + add different centrality estimators

PWGHF/TableProducer/trackIndexSkimCreator.cxx
- Use only bachelor tracks for vertexing.
- Apply preselection before vertexing: Xi mass, Xic pt, Xic mass.
- Apply selection after vertexing: Xic pt, Xic CPA, Xic decay length.
- Unrelated changes:
- Remove alias PDG mass variables.
FYI: @JaeYoonCHO @pstahlhu
=> [PWGHF] XicToXiPiPi: Improve vertexing and selections in skimming

PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryTrack.cxx, PWGEM/Dilepton/Tasks/Converters/CMakeLists.txt, PWGEM/Dilepton/Tasks/Converters/trackConverter1.cxx
PWGEM/Dilepton: reduce charged track size
=> [PWGEM/Dilepton] reduce charged track size

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonHadronMPC.h
PWGEM/Dilepton: remove unused argument
=> [PWGEM/Dilepton] remove unused argument

PWGCF/DataModel/CorrelationsDerived.h, PWGCF/JCorran/Core/JFFlucAnalysis.cxx, PWGCF/JCorran/Core/JFFlucAnalysis.h, PWGCF/JCorran/Core/JFFlucAnalysisO2Hist.cxx, PWGCF/JCorran/Core/JFFlucAnalysisO2Hist.h, PWGCF/JCorran/Tasks/jflucAnalysisTask.cxx, PWGCF/TableProducer/filterCorrelations.cxx, PWGCF/Tasks/correlations.cxx
- Add multiplicity correlations histogram to CF correlations and JCorran analysis tasks
- fixes the V0 rapidity default behaviour.
=> [PWGCF] CF correlations and JCorran multiplicity correlations

PWGEM/PhotonMeson/Core/DiphotonHadronMPC.h
=> [PWGEM/PhotonMeson] update 2PC

Common/Tools/MultModule.h
Thanks to @Luzhiyongg for spotting!
=> [Common] fix bug in z-vertex eq for Nglobal estimator

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: remove collinear from treeCreatorElectronMLDDA.cxx
=> [PWGEM/Dilepton] remove collinear from treeCreatorElectronMLDDA.cxx

PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: use pin instead of ppv
=> [PWGEM/Dilepton] use pin instead of ppv

PWGHF/HFL/Tasks/taskSingleElectron.cxx
=> [PWGHF] Add a method for electron source selection

EventFiltering/macros/uploadOTSobjects.C
The changes made in this commit simplify the process of uploading OTS objects
to the CCDB. The main changes are:
- The default value for the `chunkedProcessing` parameter is set to `true`,
making it the default behavior.
- The base CCDB path is updated to use the `EventFiltering/Zorro/` directory
instead of the hardcoded `Users/m/mpuccio/EventFiltering/OTS/` path.
- The `uploadOTSobjects` function that takes a `periodName` parameter has been
updated to always use `chunkedProcessing = true`, simplifying the function
call.
These changes make the OTS object upload process more consistent and easier to
use, while also ensuring that the CCDB path is more generic and not tied to a
specific user's directory.
=> [Trigger] feat: Update OTS object upload process

PWGCF/FemtoUniverse/Core/FemtoUniverseDetaDphiStar.h, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskV0CascadeExtended.cxx
- added CPR for v0-cascade combination
- implemented bitmask in the v0-cascade task
- removed commented codes
=> [PWGCF] FemtoUniverse v0cascade task -- implemented bitmask and CPR in v0-cascade task

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectronQC.cxx
PWGEM/Dilepton: update skimmerPrimaryElectronQC.cxx
=> [PWGEM/Dilepton] update skimmerPrimaryElectronQC.cxx

PWGCF/FemtoDream/Core/femtoDreamDetaDphiStar.h, PWGCF/FemtoDream/Tasks/CMakeLists.txt, PWGCF/FemtoDream/Tasks/femtoDreamPairTaskV0V0.cxx
- Included the V0V0 pair task
- updated the ClosePairRejection task to support V0-V0 pairs
=> [PWGCF] Adding V0-V0 pair task

DPG/Tasks/AOTTrack/qaImpPar.cxx
=> [DPG] Bug fix for physical-primary selection in DPG dca task.

PWGJE/JetFinders/jetFinder.cxx, PWGJE/JetFinders/jetFinderHF.cxx, PWGJE/JetFinders/jetFinderV0.cxx
* Changed THnSparse to THnD from THnC
This histogram is used only for V0 jet analyses, so this change affects no other jet work.
When used in an analysis train the THnC overflows, resulting in negative entries (see attached figure). This can be seen in e.g. trains [426828](https://alimonitor.cern.ch/hyperloop/train-run/426828/general) and [474334](https://alimonitor.cern.ch/hyperloop/train-run/474334/general).
The issue is likely due to the fact that the bin content is stored in a char, rather than a float/double. Changing this should fix the issue.
=> [PWGJE] V0 Jet Finder

PWGEM/Dilepton/Tasks/taggingHFE.cxx, PWGLF/Tasks/Resonances/CMakeLists.txt, PWGLF/Tasks/Resonances/initializereventqa.cxx, PWGLF/Tasks/Resonances/xi1530Analysisqa.cxx
**xi1530Analysisqa.cxx**
- Added an explicit INEL>0 selection in the analysis code because the embedded INEL>0 selection via the MultCent table is not functioning correctly in the current workflow.
- For MC analyses, added logic to retrieve the generator-level multiplicity percentile via mcCentrality.cxx.
**initializerevetqa.cxx**
Generator-level QA of event-loss and signal-loss corrections for ResonanceInitializer in pp collisions (referred to TableProducer/Strangeness/cascqaanalysis.cxx).
Following discussions at two PAG meetings (https://indico.cern.ch/event/1518979, https://indico.cern.ch/event/1575984), we introduce an auxiliary task that, when resonanceInitializer.cxx is used, computes generator-level event-loss and signal-loss correction factors. With minor tuning of the …
=> [PWGLF] added initializerevetqa.cxx and updated xi1530Analysisqa.cxx

PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx
- Add option to use additional calibration for EMCal clusters. This calibration aims to shift the reconstructed Pi0 mass to the PDG value.
=> [PWGEM,PWGEM-36] taskPi0FlowEMC: Add additional EMCal calib

PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectronQC.cxx
PWGEM/Dilepton: update PID ML in TableProducer
=> [PWGEM/Dilepton] update PID ML in TableProducer

PWGJE/Tasks/bjetTaggingGnn.cxx, PWGJE/Tasks/bjetTreeCreator.cxx
Some parts of source codes `bjetTreeCreator.cxx` and `bjetTaggingGnn.cxx` for GNN-based b-jet analysis are updated.
- Training/Evaluation dataset separation using `collisionId`
- New configurables for GNN analysis
- Flavour definition by the common task `jet-hf-definition` in GNN approach part of `bjetTreeCreator`
=> [PWGJE] GNN-based b-jet tagging analysis code updated

PWGLF/DataModel/LFHyperNucleiKinkTables.h, PWGLF/TableProducer/Nuspex/hyperkinkRecoTask.cxx
Update criteria and qa histograms, remove useless column in the datamodel for hypertriton kink analysis
=> [PWGLF] Update criteria for hypertriton kink analysis

ALICE3/Core/FastTracker.cxx, ALICE3/Core/FastTracker.h, ALICE3/TableProducer/alice3-multicharmTable.cxx, ALICE3/Tasks/alice3-multicharm.cxx
- Add functionality to Fasttracker for offline use
- Add picc dcaZ preselection in mcharm table producer
- Fix histogram bug in mcharm consumer
=> [ALICE3] Update fasttracker and mcharm histograms

PWGEM/Dilepton/Tasks/CMakeLists.txt, PWGEM/Dilepton/Tasks/studyDCAFitter.cxx
PWGEM/Dilepton: add studyDCAFitter.cxx
=> [PWGEM/Dilepton] add studyDCAFitter.cxx

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx
- added bitmask for saving strangeness TOF sigmas
- added strangeness TOF debug option
=> [PWGCF] FemtoUniverse cascade task -- implemented strangeness TOF sigmas for cascade analysis

PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonHadronMPC.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectronQC.cxx, PWGEM/Dilepton/Tasks/prefilterDielectron.cxx, PWGEM/Dilepton/Utils/MlResponseO2Track.h
PWGEM/Dilepton: 1st version of PID ML
=> [PWGEM/Dilepton] 1st version of PID ML

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
This PR fixes the same issue as #12355 but for the efficiency task with assoc.
A check is added for the geometry similar to the one in AnalysisMuonSelection tasks, along with the required configurables.
=> [PWGDQ] Add geometryloading to dileptontrack task for MC with assoc

Common/TableProducer/eventSelection.cxx, Common/Tools/EventSelectionTools.h
Number of orbitsPerTF is set to 8 "by hand" for the MC production LHC25f3 anchored to Pb-Pb 2023 apass5 (to be removed once the info for this production is in ccdb).
This productions seems to be using an old software which is the reason why the entry is missing.
=> [Common] Set orbitsPerTF to 8 for MC production LHC25f3

PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h
PWGEM/Dilepton: minor update Dilepton.h
=> [PWGEM/Dilepton] minor update Dilepton.h

PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/Tasks/eventQC.cxx, PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx
PWGEM/Dilepton: update eventQC
=> [PWGEM/Dilepton] update eventQC

Tutorials/src/filters.cxx
Simplify filter tutorial to be able to run without extra workflows and add the demonstration of the string filter parsing.
Draft until tomorrows tag.
=> [Tutorial] Tutorials: simplify and update filters tutorial

Common/Core/fwdtrackUtilities.h, PWGLF/Tasks/GlobalEventProperties/heavyionMultiplicity.cxx
adding histograms of centrality vs global/ft0c/fv0a multiplicity
=> [PWGLF] Lightions dN/deta at midrapidity  -- correlation histograms

PWGJE/Core/JetTaggingUtilities.h, PWGJE/Tasks/bjetTreeCreator.cxx
`JetTaggingUtilities.h`
- Replaced IP3D/sigmaIP3D to IPz/sigmaIPz for GNN input features
`bjetTreeCreator.cxx`
- Replaced histograms of IP3D/sigmaIP3D to IPz/sigmaIPz (trivial)
=> [PWGJE] Replaced IP3D/sigmaIP3D to IPz/sigmaIPz for GNN input features

PWGLF/Tasks/Strangeness/lambdaTwoPartPolarization.cxx, PWGLF/Tasks/Strangeness/phik0shortanalysis.cxx
=> [PWGLF] adding event mixing

PWGHF/D2H/Tasks/taskOmegac0ToOmegapi.cxx
@Yunfan-Liu @mtorresc15 Please have a look, since this likely impact your offline macros.
I re-worked the output of the task, now when running on data only a ThnSparse called `hReco` is produced, while running on MC you will get also one with the generated information `hMcGen` (and `hMcGenWithRecoColl` in case one runs with the centrality information on). The axes of the sparses depend on the process function selected (more axes are added when running with centrality).
=> [PWGHF] OmegaC task, rework output structure + add info for vs mult. analysis

Common/Tools/TrackTuner.h
This development should prevent conflicts in calibration file download/reading in case of multi-thread execution (`pipeline` option)
=> [Common] move from retrieveBlob to getFromtimeStamp for TrackTuner inputs

PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: update in QC histograms
=> [PWGEM/Dilepton] update in QC histograms

PWGHF/HFL/Tasks/taskElectronWeakBoson.cxx, PWGLF/Tasks/Strangeness/CMakeLists.txt, PWGLF/Tasks/Strangeness/lambdalambda.cxx
adding pp trigger analysis
updating event mixing for V0s
=> [PWGLF] adding pp trigger analysis

PWGHF/HFC/DataModel/DerivedDataCorrelationTables.h, PWGHF/HFC/TableProducer/CMakeLists.txt, PWGHF/HFC/TableProducer/correlatorFlowCharmHadrons.cxx
Hi @stefanopolitano, @scattaru! Here a first version of the task that we could use to fill the tables for Ds and D+ to study the correlations in small systems. Please let me know your feedback!
=> [PWGHF] Task for D+ and Ds correlations in small systems

PWGLF/TableProducer/Strangeness/v0selector.cxx
* Bug fix: check randomSelection flag before randomly selecting V0s
* Random selection flag is now off by default
* Added flags for turning on or off K0S/Lambda/AntiLambda cuts
=> [PWGLF] V0 Selector

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h
PWGEM/Dilepton: update DielectronCut
=> [PWGEM/Dilepton] update DielectronCut

PWGEM/Dilepton/Tasks/createResolutionMap.cxx, PWGEM/Dilepton/Utils/MomentumSmearer.h
PWGEM/Dilepton: fix for global muon in createResolutionMap.cxx
=> [PWGEM/Dilepton] fix for global muon in createResolutionMap.cxx

CODEOWNERS
Following the [CB of 18/07/2025](https://indico.cern.ch/event/1558336/), `codeowners` should have the changes:
* add @mpuccio to LF conveners effective 01/09/2025
* add @XiaozhiBai to DQ conveners effective 01/09/2025
=> [Infrastructure] Codeowners update due 1st September

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
- fixing minitree filling in dqEfficiencyWithAssoc
- Setting manually magnetic field in AnalysisMuonSelection if not available in ccdb
=> [PWGDQ] Fixing minitree filling in dqEfficiencyWithAssoc

EventFiltering/Zorro.cxx, EventFiltering/Zorro.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonHadronMPC.h, PWGEM/Dilepton/Core/PhotonHBT.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/DataModel/dileptonTables.h, PWGEM/Dilepton/TableProducer/createEMEventDilepton.cxx, PWGEM/Dilepton/TableProducer/skimmerOTS.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectron.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryElectronQC.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryMuon.cxx, PWGEM/Dilepton/TableProducer/skimmerPrimaryTrack.cxx, PWGEM/PhotonMeson/Core/DiphotonHadronMPC.h, PWGEM/PhotonMeson/TableProducer/createEMEventPhoton.cxx, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx, PWGEM/PhotonMeson/TableProducer/skimmerPrimaryElectronFromDalitzEE.cxx
PWGEM/Dilepton, Trigger: update trigger analysis in LMEE
=> [PWGEM/Dilepton,Trigger] update trigger analysis in LMEE

Common/Tools/Multiplicity/MultModule.h
This PR addresses a corner case in the power-law mapping of data to MC used in the centrality framework that was leading to NaNs when specific sets of parameters were used.
Interestingly, even if the MC calibration mapping procedure has been power-law-based for many years, this corner case in which parameters led to NaNs in the intermediate evaluation has only appeared in light ion monte carlo. This adjustment will sanitize all instances of this effect also in the future, as the mapping function is adjusted in the evaluation code (no change needed in ccdb).
=> [Common] Sanitize power-law mapping in corner cases

PWGEM/Dilepton/Core/DimuonCut.h
PWGEM/Dilepton: fix in DimuonCut.h
=> [PWGEM/Dilepton] fix in DimuonCut.h

PWGLF/Tasks/Resonances/chk892Flow.cxx
For chk892Flow.cxx, rapidity cut |y| < 0.3 is applied for K0s daughters to see if the significance can be improved.
=> [PWGLF] Added rapidity cut for K0s daughters

PWGMM/Mult/DataModel/bestCollisionTable.h, PWGMM/Mult/TableProducer/CMakeLists.txt, PWGMM/Mult/TableProducer/ambiguousTrackPropagation.cxx, PWGMM/Mult/TableProducer/trackPropagation.cxx
1. PWGMM/Mult/TableProducer/trackPropagation.cxx
- Added new process function, including the propagateToDCAhelix method from PR https://github.com/AliceO2Group/AliceO2/pull/14460
2. PWGMM/Mult/DataModel/bestCollisionTable.h
- Added new table for forward DCAxyz (used in trackPropagation.cxx)
3. PWGMM/Mult/TableProducer/CMakeLists.txt
- Rename trackPropagation.cxx to ambiguousTrackPropagation.cxx
=> [PWGLF] Updated with propagateToDCAhelix method

PWGCF/FemtoUniverse/TableProducer/femtoUniverseProducerTask.cxx, PWGCF/FemtoUniverse/Tasks/femtoUniversePairTaskTrackV0Helicity.cxx
Add new MCTruth analysis to helicity study.
=> [PWGCF] FemtoUniverse -- Add new MCTruth analysis to helicity study.

PWGJE/Tasks/taskEmcExtensiveMcQa.cxx
Was compiling by accident because of namespace pollution from PWGUD headers.
=> [PWGJE] taskEmcExtensiveMcQa: Fix missing namespace prefix

PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
toiMap was not filled for the skipped zorrocounting
=> [PWGLF] double count fix II

PWGEM/PhotonMeson/Core/TaggingPi0.h, PWGEM/PhotonMeson/Core/TaggingPi0MC.h
PWGEM/PhotonMeson: update TaggingPi0
=> [PWGEM/PhotonMeson] update TaggingPi0

PWGEM/Dilepton/Core/SingleTrackQCMC.h
PWGEM/Dilepton: add a histogram for PC in SingleTrackQCMC.h
=> [PWGEM/Dilepton] add a histogram for PC in SingleTrackQCMC.h

PWGHF/D2H/TableProducer/candidateCreatorCharmResoReduced.cxx
Hi @Luca610 and @fgrosa, I found some issues during doing the analysis of D0lambda channel, I try to fix it in this pr. Let me know if you have any comments on that.
=> [PWGHF] Improve the mass window selection and v0 type matched for lambda

PWGLF/TableProducer/Strangeness/strangenesstofpid.cxx
Very minor change: initialize data members to `nullptr` to avoid that 'time exceeded' problems in HY are not accompanied by a problematic destructor call sequence ([example](https://alimonitor.cern.ch/hyperloop/wagon-test/500396/general)). But: timeouts are sadly still very much unsolved ...
=> [PWGLF] Minor safety changes for strangenesstofpid task

PWGDQ/Tasks/dqEfficiency_withAssoc.cxx
This PR
1. Add an additional check to the one implemented in #12723 checking for MC tracks in the two lepton legs for the rare cases where it does not exist
2. Moves the dimuon-track table implemented in #12850 to the right case
=> [PWGDQ] Fixes to dilepton track mc

PWGCF/FemtoDream/Tasks/CMakeLists.txt, PWGCF/FemtoDream/Tasks/femtoDreamCollisionMasker.cxx, PWGCF/FemtoDream/Tasks/femtoDreamTripletTaskTrackTrackV0PbPb.cxx
Adding a new task for 3-body femtoscopic studies (2 tracks and V0) in PbPb
Adding back the 3-tracks task to the cmakelists
=> [PWGCF] A correlation task for triplets (track-track-v0) in Pb–Pb collisions

PWGHF/TableProducer/trackIndexSkimCreator.cxx
- Fix types of bitmaps `nCutStatus2ProngBit`, `nCutStatus3ProngBit`, `prong2CutStatus`, `prong3CutStatus`.
- Reduce unnecessary operations in `applyPreselection2Prong`, `applyPreselection3Prong`.
- Use `do3Prong` as `bool` properly.
- Improve `const` correctness.
- Simplify `array` declarations using type deduction.
- Fix `array` initialisations.
- Fix `UChar_t` type for `itsClusterMap`.
- Pass by `const&`.
- Use `auto` more to capture return values.
- Remove default template arguments of `applyMlSelectionForHfFilters3Prong`, `run2And3Prongs`.
- Remove useless argument of `getHfCollisionRejectionMaskWithUpc`.
- Define `etaMinDefault` to fix magic numbers.
=> [PWGHF] Improve skimming code

PWGCF/DataModel/FemtoDerived.h, PWGCF/FemtoDream/Core/femtoDreamObjectSelection.h, PWGCF/FemtoDream/Core/femtoDreamResoSelection.h, PWGCF/FemtoDream/Core/femtoDreamTrackSelection.h, PWGCF/FemtoDream/Core/femtoDreamUtils.h, PWGCF/FemtoDream/Core/femtoDreamV0SelectionK0Short.h, PWGCF/FemtoDream/TableProducer/CMakeLists.txt, PWGCF/FemtoDream/TableProducer/femtoDreamProducerTaskReso.cxx
Resonance selection via reconstruction of the invariant mass has been implemented in the producer Task.
Several files were modified/added in order to support this implementation.
Efforts were made to comply with linter and formatting suggestions; however, some warnings persist due existing files that were not modified.
@AntonRiedel 
@gmantzar
=> [PWGCF] Implementation of Phi and K0Short

PWGCF/Femto/Core/dataTypes.h, PWGCF/Femto/Core/kinkBuilder.h, PWGCF/Femto/Core/kinkHistManager.h, PWGCF/Femto/Core/modes.h, PWGCF/Femto/Core/partitions.h, PWGCF/Femto/Core/trackHistManager.h, PWGCF/Femto/DataModel/FemtoTables.h, PWGCF/Femto/TableProducer/femtoProducer.cxx, PWGCF/Femto/Tasks/CMakeLists.txt, PWGCF/Femto/Tasks/femtoKinkQa.cxx
Adding sigma particle to new femto framework
- Adding new table for the sigmas
- extending producer
- adding dedicated qa task for sigmas
=> [PWGCF] add Sigma particles to femto framework

ALICE3/Core/FastTracker.cxx, ALICE3/Core/FastTracker.h
=> [ALICE3] Add possibility to use generic geometry

PWGCF/JCorran/Tasks/jflucWeightsLoader.cxx
CCDB access added for efficiency. NUA and NUE corrections can now be accessed locally or from CCDB with automatic assignment depending on the given path.
=> [PWGCF] CCDB access added properly for NUA and NUE corrections

ALICE3/Core/FastTracker.cxx, ALICE3/TableProducer/OTF/onTheFlyTracker.cxx
@njacazio tested locally with https://github.com/AliceO2Group/O2Physics/pull/13086 to work
=> [ALICE3] Let fasttracker use the generic geometry

PWGCF/Femto/Core/closePairRejection.h, PWGCF/Femto/Core/femtoUtils.h, PWGCF/Femto/Core/kinkHistManager.h, PWGCF/Femto/Core/pairBuilder.h, PWGCF/Femto/Core/pairCleaner.h, PWGCF/Femto/Core/pairHistManager.h, PWGCF/Femto/Tasks/CMakeLists.txt, PWGCF/Femto/Tasks/femtoPairTrackKink.cxx
This PR adds the PairTrackKink task to correlate pairs of tracks and kinks and the surrounding infrastructure.
=> [PWGCF] Add track-kink pair task

DPG/Tasks/AOTEvent/eventSelectionQa.cxx
added condition on ambi tracks loop to avoid crashes (in particular, for some Pb-Pb MC)
=> [DPG] added condition on ambi tracks loop to avoid crashes

PWGLF/Tasks/Strangeness/nonPromptCascade.cxx
allowing data flow run1,run2,run1
=> [PWGLF] Omega: allowing split runs

PWGLF/Tasks/Strangeness/cascadecorrelations.cxx
- remove obsolete TracksDCA tables
- fix double counting in eventselection histograms
- properly apply efficiency correction to inv mass histograms
=> [PWGLF] use cent instead of mult + bugfixes

PWGLF/Tasks/QC/strangepidqa.cxx
Fixes very silly mistake in cross-check / QA histo filling
=> [PWGLF] Bugfix: missing std::fabs

PWGLF/Utils/strangenessBuilderHelper.h, PWGLF/Utils/strangenessBuilderModule.h
Optimization changes: 
* When including photon processing, the V0 building done to evaluate duplicates was propagating prongs with XIU = 83.1f to the PV to calculate the DCA to PV, incurring in a large CPU cost for obtaining a variable that isn't checked in the de-duplication process. This PR makes it such that this propagation is skipped when constructing V0s in the de-duplication procedure, but kept for all other use cases, keeping default operation unchanged. Will lead to a sizable improvement in performance when processing photons. Tagging @gianniliveraro 
* Switches the propagate-to-PV call for V0 prongs to be done only on `TrackPar` (instead of `TrackParCov`) to avoid that multiple scattering contributions are calculated needlessly as only DCAxy is used, further saving some CPU.
=> [PWGLF] Optimize de-duplication and DCAtoPV calculation

DPG/Tasks/TPC/tpcSkimsTableCreator.cxx, PWGDQ/DataModel/ReducedInfoTables.h, PWGDQ/Tasks/v0selector.cxx, PWGLF/DataModel/LFStrangenessTables.h
Enabled filling a clean kaon sample for TPC PID NN training (in addition to existing samples of electrons, pions and protons).
* [PWGLF/DataModel/LFStrangenessTables.h](https://github.com/AliceO2Group/O2Physics/blob/b178c96d03ede873ee769ef8a4d7c1e21bf78332/PWGLF/DataModel/LFStrangenessTables.h): cascade table is extended with dynamic columns like in V0 table, i.e. Armenteros-Podolanski variables, Psi pair angle etc.
* [PWGDQ/Tasks/v0selector.cxx](https://github.com/AliceO2Group/O2Physics/blob/b178c96d03ede873ee769ef8a4d7c1e21bf78332/PWGDQ/Tasks/v0selector.cxx): implemented selection of $\Omega\rightarrow\Lambda K^-$ decays reconstructed by [PWGLF/TableProducer/Strangeness/strangenessbuilder.cxx](https://github.com/AliceO2Group/O2Physics/blob/b178c96d03ede873ee769ef8a4d7c1e21bf78332/PWGLF/T …
=> [PWGDQ,PWGLF,DPG] TPC PID: fill clean kaon sample from Omega decay

PWGEM/Dilepton/Core/DielectronCut.cxx, PWGEM/Dilepton/Core/DielectronCut.h, PWGEM/Dilepton/Core/Dilepton.h, PWGEM/Dilepton/Core/DileptonMC.h, PWGEM/Dilepton/Core/SingleTrackQC.h, PWGEM/Dilepton/Core/SingleTrackQCMC.h, PWGEM/Dilepton/Tasks/createResolutionMap.cxx
PWGEM/Dilepton: add possibility to select phiPosition
=> [PWGEM/Dilepton] add possibility to select phiPosition

PWGHF/D2H/Tasks/taskDplus.cxx
This is a minor fix in the number of contributors at the generated level.
=> [PWGHF] Minor Fix in the number of contributors 

PWGEM/Dilepton/Utils/MlResponseDielectronSingleTrack.h, PWGEM/Dilepton/Utils/MlResponseO2Track.h
PWGEM/Dilepton: update MlResponse
=> [PWGEM/Dilepton] update MlResponse

PWGLF/DataModel/LFAntinCexTables.h, PWGLF/TableProducer/Nuspex/CMakeLists.txt, PWGLF/TableProducer/Nuspex/nucleiAntineutronCex.cxx
This PR adds the final table producer and data model in the correct location, with minimal changes:
- Add table producer: `PWGLF/TableProducer/Nuspex/nucleiAntineutronCex.cxx`
- Add data model: `PWGLF/DataModel/LFAntinCexTables.h`
- Update `PWGLF/TableProducer/Nuspex/CMakeLists.txt` with the workflow entry
This PR **supersedes** the previous one that included the initial/experimental task and its CMake changes. The old PR can be closed.
=> [PWGLF] Nuspex: antineutron CEX table producer (clean PR)

Common/DataModel/Qvectors.h, Common/TableProducer/qVectorsTable.cxx, Common/Tasks/qVectorsCorrection.cxx, PWGLF/TableProducer/Strangeness/cascadeflow.cxx
adding shift correction
based on the recent report in DPG meeting:
https://indico.cern.ch/event/1568257/contributions/6686897/attachments/3133733/5559683/DPG_AOT_EP_OO_and_Ne_Ne_110925.pdf
=> [Common] EventPlane: adding shift correction

PWGEM/Dilepton/TableProducer/CMakeLists.txt, PWGEM/Dilepton/TableProducer/treeCreatorElectronMLDDA.cxx
PWGEM/Dilepton: update treeCreatorElectronMLDDA.cxx to support Zorro
=> [PWGEM/Dilepton] update treeCreatorElectronMLDDA.cxx to support Zorro

PWGLF/Tasks/Strangeness/lambdaJetpolarization.cxx
Dear Experts:
The recent code is mainly used to calculate Lambda local polarization
I have two .cxx files and one header file to complete my analysis.These codes have been updated.
TableProducer : lambdaJetpolarizationbuilder.cxx : The file has not been modified.
Tasks ：lambdaJetpolarization.cxx : 
1.The configurable axis for pT and the invariant mass have been modified.
2.modified the event selections,V0 cut selections.
3.Add some QA plots such as proton distribution on theta and phi, plots of intermediate process.
DataModel : lambdaJetpolarization.h : The file has not been modified.
Best wishes,
Youpeng Su
Sep 28, 2025
=> [PWGLF] Local polarization of Lambda induced by jets in Run3 pp collisions at 13.6 TeV

DPG/Tasks/TPC/tpcSkimsTableCreator.cxx
**Reduced code repetition:**
* merged process functions "with" and "without" dEdx correction;
* merged process functions "WithdEdxTrQA" and "WithTrQA";
* iteration by V0s (tracks) in V0 (TOF) tree creator replaced with a for-loop over a dedicated **struct** for mentioned objects;
* removed a redundant **if-esle** construction with identical consequent and alternative in **struct** `TreeWriterTPCTOF`.
**Readability and code cosmetics:**
* added `const` and `const&` where possible and necessary, ~~removed `const` from function arguments passed by value~~;
* introduced constexpr shortcuts for particles' masses and ids;
* removed `sqrtsNN` from member functions' arguments since `sqrtsNN` is a **struct**'s configurable;
* renamed `TreeWriterTPCTOF::processStandard2()` function into …
=> [DPG] Refactor tpcSkimsTableCreator

EventFiltering/PWGEM/HeavyNeutralMesonFilter.cxx, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGamma.h, PWGEM/PhotonMeson/Core/Pi0EtaToGammaGammaMC.h, PWGEM/PhotonMeson/DataModel/gammaTables.h, PWGEM/PhotonMeson/TableProducer/photonconversionbuilder.cxx, PWGEM/PhotonMeson/TableProducer/skimmerGammaCalo.cxx, PWGEM/PhotonMeson/Tasks/CMakeLists.txt, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaEMCEMC.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCEMCEMC.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCPCMDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaMCPCMPCM.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaPCMDalitzEE.cxx, PWGEM/PhotonMeson/Tasks/Pi0EtaToGammaGammaPCMPCM.cxx, PWGEM/PhotonMeson/Tasks/calibTaskEmc.cxx, PWGEM/PhotonMeson/Tasks/taskPi0FlowEMC.cxx, PWGEM/PhotonMeson/Utils/ClusterHistograms.h, PWGEM/PhotonMeson/Utils/EventHistograms.h, PWGEM/PhotonMeson/Utils/HNMUtilities.h, PWGEM/PhotonMeson/Utils/MCUtilities.h, PWGEM/PhotonMeson/Utils/NMHistograms.h, PWGEM/PhotonMeson/Utils/PCMUtilities.h, PWGEM/PhotonMeson/Utils/TrackSelection.h, PWGEM/PhotonMeson/Utils/emcalHistoDefinitions.h, PWGEM/PhotonMeson/Utils/gammaConvDefinitions.h, PWGHF/HFL/TableProducer/electronSelectionWithTpcEmcal.cxx, PWGHF/HFL/Tasks/taskSingleElectron.cxx
- Preparation for https://github.com/AliceO2Group/AliceO2/pull/14662 where eta, omega and etaPrime are added to the `PhysicsConstants.h` which clashed with some local enum definitions here.
1. Removal of `using` in some header files and necessary changes because of this removal (EventFiltering for example)
2. Cleaning up includes in most touched files here after the removal of `using`
3. PI from match constanst, naming of some variables and other O2 Linter errors. Changes to configurable names were not done since this would mess up all ongoing analyses wagons.
4. Addition of new task for EMCal cluster energy calibration. For high mult AA collisions the cluster energy needs some extra calibration, since a single cluster often has energy deposition from more than just the photon that we are …
=> [PWGEM,PWGHF,Trigger] Fix O2linter warnings

PWGJE/Tasks/CMakeLists.txt, PWGJE/Tasks/jetOutlierQA.cxx
This task is for studying the event migration outliers (high-weight jets or tracks with pT >> pThat) found in the jet-jet MCs. Includes:
- jet-based QA for all jets + jets identified as probable outliers 
- event-based QA for events containing probable outliers
- track-level QA on event position in z, which is a probable cause of the migration (-> event merging) as seen in PWGDQ studies 
- track-level QA for ambiguous tracks and those without corresponding particles
=> [PWGJE] Add MC outlier QA task
